### ISSUE TITLE
Word tokenizer without splitting contractions

### ISSUE THREAD

**Issue by knyghty** [explosion/spaCy#1004]
I think this may have been mentioned before, but couldn't find it.

It would be nice to have a tokenizer that just gets words out, omiting punctuation and not splitting contractions into multiple tokens.

For a use-case, consider language style matching, which requires splitting words and only words and checking the words against several word lists, many of which contain contractions, especially aux verbs.

**Comment by honnibal** [comment]
The problem is that this type of tokenizer would then be incompatible with the tagger, parser, vectors, NER etc that are trained to expect the other type of tokenization.

Would your use-case be satisfied by just having an iterator that accepted a `Doc` object and yielded out the tokenization you need?

**Comment by knyghty** [comment]
Yeah I think that's probably the best solution. It would be nice if this could be provided, perhaps by an attribute on a `Doc`.

**Comment by ines** [comment]
@knyghty This will be possible in spaCy v2.0 (currently in alpha, but already available as `spacy-nightly` on pip). More details:

* https://explosion.ai/blog/spacy-v2-pipelines-extensions
* https://alpha.spacy.io/usage/processing-pipelines#custom-components-attributes
