### ISSUE TITLE
Non-deterministic evaluation when using the experimental `edit_tree_lemmatizer`

### ISSUE THREAD

**Issue by oroszgy** [explosion/spaCy#10107]
Hi! (@kadarakos )

There is strange bug we are facing when using the `edit_tree_lemmatizer` for [huspacy](https://github.com/huspacy/huspacy). Evaluating the module can be non-deterministic yielding scores below 70% and above 90%.

## Reproducing the bug 

1. `git clone https://github.com/huspacy/huspacy.git`
2. `git checkout experimental-edit-tree-lemmatizer`
3. `poetry install`
4. `cd hu_core_news_lg`
5. `spacy project assets`
6. `spacy project run train_edit_tree_lemmatizer`

Non-deterministic behavior is produced by `spacy project evaluate` (included in the `train_edit_tree_lemmatizer` workflow`)

## Your Environment

* Operating System: Ubuntu 20.04.3 LTS Linux-5.13.0-27-generic-x86_64-with-glibc2.29
* Python Version: 3.8.10
* spaCy Version: spacy==3.2.1, spacy-experimental==0.2.0

**Comment by oroszgy** [comment]
@qeterme please provide further details if necessary.

**Comment by adrianeboyd** [comment]
I didn't try to run this project, but I tested a few of the UD models I trained recently with the edit tree lemmatizer and don't see any evidence that the predictions or the evaluation with `spacy evaluate` is non-deterministic. It looks like there's a `merge-eval-results` script that's used in the `evaluate` step but not included in the project repo?

There is some non-determinism when training on GPU (just training, not inference!), but I haven't seen instances where it led to large differences in model accuracy in the end. It's enough to be frustrating while experimenting with hyperparameters, but not +/20%.

**Comment by qeterme** [comment]
It's only happening with the assembled model. When I try to evaluate only the `edit-tree-lemmatizer` model, I get every time the same results. But when I try to evaluate the assembled model with the `spacy evaluate` command multiple times (around 5 or so) I get different results. Yes, sure a few percentages would be okay, but not around 20%. 

The assembler copies the `tok2vec` layer from the `edit-tree-lemmatizer` model, maybe that occurs this strange behavior?

**Comment by adrianeboyd** [comment]
Do you see different results every single time, or does it just vary between 2-3 different results?

Does a single assembled pipeline give non-deterministic results or do you only see differences between different project runs where the saved pipeline directories aren't identical (aside from the scores in `meta.json`)? If there's a single pipeline that is non-deterministic, can you share a link to it for us to test?

**Comment by qeterme** [comment]
It varies around 5 or so results. (67.28, 67.29, 66.15, 66.93, 93.90) When evaluating by itself it returns the same value (93.88) all the time. 

I uploaded one assembled model (hu_core_news_lg-0.4.2) and the lemmatizer and parser to assemble if you want. 

Steps to reproduce:
1. `git clone https://github.com/huspacy/huspacy.git`
2. `git checkout experimental-edit-tree-lemmatizer`
3. `poetry install`
4. `cd hu_core_news_lg`
5. `poetry shell`
6. `spacy project assets`
7. `spacy project run preprocess_ud`
8. copy the models from the zip into `huspacy/models`
9. `spacy project run evaluate` multiple times

If you want to assemble and evaluate:
1. `spacy project run assemble`
2. `spacy project run evaluate` multiple times

Link to download: https://mega.nz/file/5t8kVAJJ#n74V1xe2AE31bFd_wG9tckNJFzW4ZW3Q8AapVstos98

**Comment by adrianeboyd** [comment]
Thanks! I do also see similar non-deterministic results. My initial guess was crossed wires between multiple `tok2vec` components when the pipeline was assembled, but I think it's something related to vectors instead.

I think the main issue is that you've trained the lemmatizer with vectors enabled, but with an empty set of vectors. When you add it to the other parser pipeline, it suddenly has vectors where before it just had zeros. I suspect you meant to also override `--paths.vectors` for the edit tree lemmatizer in the train command?

I think straightening out the vectors should resolve the non-deterministic behavior, but I would have expected deterministic (bad) results rather than this, so we'll take another look at the edit tree lemmatizer. There's an additional error, which is not specific to the lemmatizer, when you try to run the component with the mismatched vectors on GPU, too.

**Comment by adrianeboyd** [comment]
So it turns out that there should have been the same error on CPU as on GPU, but due to a bug in `blis` the vector code returned non-deterministic nonsense instead. The edit tree lemmatizer itself was not involved as far as we can tell, so we do still think that specifying the vectors correctly will fix the problem, and we'll see if can get better warnings in spacy related to having `include_static_vectors = true` without vectors in the vocab.

**Comment by qeterme** [comment]
Yes, it looks like you were right, and I forgot to include the vectors. My bad. I ran the train-assemble-evaluate process again and it now returns the same results all time! I also run one training with `include_static_vectors = false` and it returns the same value every time as well. 
Thanks for the quick problem-solving!
