### ISSUE TITLE
unable to access the link

### ISSUE THREAD

**Issue by vibhutibindal** [explosion/spaCy#1012]
## Your Environment

* Operating System: windows 7
* Python Version Used: python 2.7.13 64 bit
* spaCy Version Used: spacy 1.7.5
* Environment Information: 

i am looking for a tutorial on how to load pre-trained glove vectors using spacy(wikipedia corpus) and i am unable to access the link https://spacy.io/tutorials/load-new-word-vectors/.

**Comment by vibhutibindal** [comment]
can anyone provide the code snippet on how to use glove pretrained vectors(Wikipedia corpus) with spacy.

**Comment by ines** [comment]
Sorry for only getting to this issue now – we've since improved the vector loading and GloVe vectors support in spaCy v2.0, currently in alpha. You can test the new version by running `pip install spacy-nightly`.

The new version also comes with re-written and restructured docs, including a new section on word vectors: https://alpha.spacy.io/usage/vectors-similarity

See here for the relevant section on loading GloVe vectors:
https://alpha.spacy.io/usage/vectors-similarity#custom-loading-glove
