### ISSUE TITLE
can spacy be used to parse headlines, in which words are capitalized at frist letter?

### ISSUE THREAD

**Issue by ajige** [explosion/spaCy#1023]
Like this one:
Moody's Withdraws The Issuer Rating Of Isagen
UpSnap Announces Full Year and Q4 2016 Financial Results

how is model trained?  Is there headlines in training data? 
thanks.

**Comment by adack123** [comment]
What exactly are you trying to accomplish? 

I'm currently using spaCy with financial headlines like you have above and adding custom entities to the NER. 

https://github.com/explosion/spaCy/blob/master/examples/training/train_ner.py

**Comment by ajige** [comment]
Hi, Did you solve the problem I raised? 
If word is in right case, spacy can recognize; but if it is not, spacy cannot recognize them as name entity.
how you solved it?

**Comment by ines** [comment]
Sorry for only getting back to you now – we've since released spaCy v2.0, and updated [all training examples](https://github.com/explosion/spaCy/blob/master/examples/training/) for the new version. Usage should now be much simpler, and most examples include the expected output and additional documentation.

See [`train_new_entity_type.py`](https://github.com/explosion/spaCy/blob/master/examples/training/train_new_entity_type.py) and the step-by-step guide in the new documentation: https://spacy.io/usage/training#example-new-entity-type

You should also check out this guide on training and updating the models: https://spacy.io/usage/training
