### ISSUE TITLE
example provided does not work anymore

### ISSUE THREAD

**Issue by rafikg** [explosion/spaCy#10265]
## Your Environment
* Operating System: linux
* Python Version Used: 3.8.10
* spaCy Version Used: 3.0.7
* Environment Information:

```
from pysbd.utils import PySBDFactory

nlp = spacy.blank('en')
nlp.add_pipe(PySBDFactory(nlp))

doc = nlp('My name is Jonas E. Smith. Please turn to p. 55.')
print(list(doc.sents))

```

### [ValueError: [E966] `nlp.add_pipe` now takes the string name of the registered component factory, not a callable component. Expected string, but got <pysbd.utils.PySBDFactory object at 0x7f01c81edd90> (name: 'None').

- If you created your component with `nlp.create_pipe('name')`: remove nlp.create_pipe and call `nlp.add_pipe('name')` instead.

- If you passed in a component like `TextCategorizer()`: call `nlp.add_pipe` with the string name instead, e.g. `nlp.add_pipe('textcat')`.

- If you're using a custom component: Add the decorator `@Language.component` (for function components) or `@Language.factory` (for class components / factories) to your custom component and assign it a name, e.g. `@Language.component('your_name')`. You can then run `nlp.add_pipe('your_name')` to add it to the pipeline.]()

**Comment by pmbaumgartner** [comment]
Hey @rafikg - thanks for posting.

The issue is that this third-party library, `pySBD`, works with spacy v2 and hasn't been updated to work with spacy v3. In another issue, we've documented a solution to create a new component that works with v3: https://github.com/explosion/spaCy/issues/10207#issuecomment-1030049888. We're also working on cleaning up the spaCy Universe documentation to catch things like this.

Give that a shot and if there's something else you need help with, feel free to open a [discussion](https://github.com/explosion/spaCy/discussions/new) and we can work through it.
