### ISSUE TITLE
What's the expected output of `examples/training/train_new_entity_type.py`?

### ISSUE THREAD

**Issue by jnj16180340** [explosion/spaCy#1028]
A few questions about the NER example: 
1. In the NER training example, is it expected for there to be no output?
2. Does no output signify failure due to insufficient training data, or something else?
3. Why is the size of the output model .tgz file smaller than the original model .tgz file?

---
Download, install, and link English model:
`pip install /models/en_core_web_md-1.2.1.tar.gz`
`python -m spacy link en_core_web_md en`

Run example: 
`python ./train_new_entity_type.py en ./output`

Output:
```
Loading initial model en
Ents in 'Do you like horses?':
Loading from output
```
---
## Your Environment
* Operating System: Ubuntu 16.10, Debian Jessie (Docker) x86_64
* Python Version Used: 2.7.12+, 3.5.2+, 3.4.5 (Docker)
* spaCy Version Used: 1.8.2 (github `master`), 1.8.2 (pip), 1.8.0 (gh tag), 1.7.6 (gh tag)
* Environment Information: Model is en_core_web_md

**Comment by ines** [comment]
Sorry for only getting back to you now – we've since released spaCy v2.0, and updated [all training examples](https://github.com/explosion/spaCy/blob/master/examples/training/) for the new version. Usage should now be much simpler, and most examples include the expected output and additional documentation.

See [`train_new_entity_type.py`](https://github.com/explosion/spaCy/blob/master/examples/training/train_new_entity_type.py) and the step-by-step guide in the new documentation: https://spacy.io/usage/training#example-new-entity-type
