### ISSUE TITLE
Best Practice for using Spacy in a web application

### ISSUE THREAD

**Issue by sixhobbits** [explosion/spaCy#1029]
There are many other issues relating to reducing the time of `nlp = English()`. Is there a single best-practice way of achieving a load time short enough for spaCy to be used as part of a web application? I've seen references to Redis, running another process to serve spaCy (e.g. https://github.com/kootenpv/spacy_api/) or a dockerized version of spaCy (e.g. https://github.com/jgontrum/spacy-api-docker). 

I'd be happy to put together and example Flask application and tutorial that shows how to set up spaCy for use in a web app, but I'm not sure if this already exists, or if there's a way it's usually done.

**Comment by ines** [comment]
Hey! There's currently no recommended "best practice" or anything like that, so we always appreciate feedback and suggestions from the community.

To solve the problem of loading models, @kootenpv's library is definitely a great resource – especially since it was built pretty recently and already uses spaCy 1.7+. The smaller English model `en_core_web_sm` (50MB, about 2% less accurate than the larger one) should also help a lot.

Here are some additional resources I know of:
* REST services we use to power our demos: https://github.com/explosion/spacy-services (But just because we're doing it this way, doesn't mean it's necessarily *the best* way to do it – some of our older code tends to be a little hacky.)
* Client by @kengz that exposes spaCy to Node via socket.io: https://github.com/kengz/spacy-nlp (he also wrote a [guest post for our blog](https://explosion.ai/blog/chatbot-node-js-spacy) about building a knowledge base for a chat bot)

If you want to give this a go and write a tutorial and example app, this would be great! We'd be happy to publish and/or promote it. In our [user survey](https://survey.spacy.io) so far, several people have requested more "real world" examples of using spaCy in an application and we'd love to have more docs/tutorials/examples available for that.

I've also been thinking about adding a simple `spacy serve` command to the CLI that serves a model via a REST API... but it's not so easy to make this actually useful while still keeping it simple. We do wanna be selective in terms of what we ship with spaCy to avoid library bloat, so maybe this feature is just a better fit for separate libraries.

**Comment by sixhobbits** [comment]
Thanks for the response! I'll try out some of the options and write up something if I work out what what works well.

**Comment by kootenpv** [comment]
Btw @sixhobbits, note that once you start passing along vectors, it'll get slow pretty fast. Even with the really fast backend included in `spacy_api`. For us it works well though: based on the environment variable `PRODUCTION` we either use `spacy_api` to load `spacy` in process, and in development we communicate with another process.
