### ISSUE TITLE
Add descriptive information for parts of speech tag

### ISSUE THREAD

**Issue by kracekumar** [explosion/spaCy#1034]
I am following a tutorial about [spaCy](https://github.com/cytora/pycon-nlp-in-10-lines/blob/master/00_spacy_intro.ipynb). The tutorial focuses on part of speech tagging, the code snippet outputs jargons like `PROPN, ADP`. It's hard to judge what this means. It will be useful to have descriptive details about the names.

The developer can later look up somewhere 

```python
>get_descprition(token.pos_)
 'Proper noun <and some more info>
```

**Comment by ines** [comment]
This is a nice idea!

I think the best way to do this would be to add a module `spacy.explain` that checks strings (and possibly symbols) against a "glossary" dictionary and returns the description. This would let you do something like:

```python
print(token.pos_, spacy.explain(token.pos_))
# PROPN Proper noun
```

I'll play around with this and test it – should be easy to get something simple together for the next release and then keep updating it over time.

It's tempting to also extend this beyond strings and let users pass in objects as well... but I'm not sure if this is really a good idea. (For example, if you pass in an instance of `Tokenizer`, what should `spacy.explain` return that's not already covered by `help()`?)

**Comment by ines** [comment]
Just added [`spacy.glossary`](https://github.com/explosion/spacy/blob/master/spacy/glossary.py) and the update will be included in the next release. The glossary currently has explanations for the English and German POS tagging and dependency labelling scheme, plus the available entity labels.

You can either import `explain()` from `spacy.glossary``, or call `spacy.explain()`, for example:

```python
spacy.explain('NORP')
# Nationalities or religious or political groups

doc = nlp(u'Hello world')
for word in doc:
    print(word.text, word.tag_, spacy.explain(word.tag_))
# Hello UH interjection
# world NN noun, singular or mass
```

If a term can't be found it the glossary, `explain` currently returns nothing (this seemed better than raising a `KeyError` or something, because there might still be some terms that are missing).

**Comment by kracekumar** [comment]
That was super fast! Thank you @ines
