### ISSUE TITLE
Bizarre history-dependent sentence segmentation

### ISSUE THREAD

**Issue by lvilnis** [explosion/spaCy#1042]
Using the default 'en' model:

`d=nlp(u"""Sawyer hated spaghetti. He thought it looked like worms. When he was visiting, his best friend's Mom made spaghetti. His best friend told his Mom about Sawyer's dislike. His Mom made Sawyer a hot dog instead.""")`
`print(list(d.sents))`

Outputs:

`[Sawyer hated spaghetti.,
 He thought it looked like worms.,
 When he was visiting,,
 his best friend's Mom made spaghetti.,
 His best friend told his Mom about Sawyer's dislike.,
 His Mom made Sawyer a hot dog instead.]`

I know the segmenting is done by the parser, so I'm just reporting this issue not as something that is easily fixable but I suppose more as evidence that something extremely funky is going on with spaCy's default English sentence segmentation/parsing. It thinks "visiting" is the root in the previous case.

If it parses the sentence in isolation, it does fine though and correctly predicts visiting as advcl:

`d=nlp(u"""When he was visiting, his best friend's Mom made spaghetti""")`
`print(list(d.sents))`

Outputs:

`[When he was visiting, his best friend's Mom made spaghetti.]`

Messing around with the previous example, it appears to be having trouble because of the "looked like X" construction. 

It seems worth including an option to parse each sentence in isolation according to a simple punctuation-based segmenter to avoid surprises for well-formed data like this.

## Info about spaCy

* **Python version:** 2.7.13
* **Platform:** Darwin-16.5.0-x86_64-i386-64bit
* **spaCy version:** 1.8.2
* **Installed models:** en

**Comment by lvilnis** [comment]
If there's any interest for debugging/training/curiosity purposes, I can give around 50 other examples of 5-sentence stories that spaCy improperly segments into 6 sentences like this. They come from the "story cloze" dataset (http://cs.rochester.edu/nlp/rocstories/)

**Comment by honnibal** [comment]
If you make calls to `parser.update()`, you could train the parser to improve on these. The parser does support partial training, but in practice it's not so good to leave a lot of information unspecified, or the model suffers "catastrophic forgetting. So it's usually good to create the objective from the previous parse.

Suggested approach:

1. Load two instances of the parser: `original` and `learner`
1. Split the text into sentences using rules
2. Parse the sentences using `original`
3. Use the parses to construct `heads` and `deps` arrays, to create a `GoldParse` object for the whole text
4. Update `learner` using a doc for the whole text and the new gold parse

I've always wanted to try this, but have never had time --- it should work pretty well, in theory. You could do even better by using an ensemble as the oracle in 2, making this a form of "uptraining".

I agree that pre-specified rules would be a good enhancement --- I've had a branch for this open for some time.

You can patch this behaviour yourself without editing spaCy's source, though, by writing to the function pointers that validate the different parser actions. You'll need to do this from Cython. You want to be changing the `parser.moves.c[i].is_valid` function for the `Shift` and `RightArc` actions, so that they're marked as invalid when you're at a pre-specified sentence boundary. The relevant code to look at is in `spacy/parser/arc_eager.pyx`

**Comment by ines** [comment]
Closing this and making #1057 the master issue – work in progress for spaCy v2.0!
