### ISSUE TITLE
Tokenizer result does not match with explain result for token_match.

### ISSUE THREAD

**Issue by XavierDDD** [explosion/spaCy#10455]
## How to reproduce the behaviour

Saw a similar issue #10130 and #9136 but still have issue when applying token_match function in 3.2.3.

```
nlp = spacy.blank("en")
nlp.tokenizer.token_match = re.compile("^id$").match

text = "user id and user name"
doc = nlp(text)

for token in doc:
    print(token.text)

#user
#i
#d
#and
#user
#name

print(nlp.tokenizer.explain(text))
#[('TOKEN', 'user'), ('TOKEN_MATCH', 'id'), ('TOKEN', 'and'), ('TOKEN', 'user'), ('TOKEN', 'name')]
```

## Your Environment

- **spaCy version:** 3.2.3
- **Platform:** Linux-5.4.0-1057-gcp-x86_64-with-glibc2.27
- **Python version:** 3.8.11
- **Pipelines:** en_core_web_lg (3.2.0), en_core_web_sm (3.2.0)

**Comment by adrianeboyd** [comment]
Thanks for the report! That does look like a bug in `Tokenizer.explain`. We'll look into it!

To fix the underlying issue (`id` is treated as "I'd" by the default English exceptions), it would be cleaner to remove the exception instead:

```python
nlp.tokenizer.rules = {key: value for key, value in nlp.tokenizer.rules.items() if key != "id"}
```

**Comment by XavierDDD** [comment]
> Thanks for the report! That does look like a bug in `Tokenizer.explain`. We'll look into it!
> 
> To fix the underlying issue (`id` is treated as "I'd" by the default English exceptions), it would be cleaner to remove the exception instead:
> 
> ```python
> nlp.tokenizer.rules = {key: value for key, value in nlp.tokenizer.rules.items() if key != "id"}
> ```

Thanks for the suggestion, I'll adopt this solution.
Just want to confirm, which result is the correct result by design?
I thought the `Tokenizer.explain` is the right one, but you said that it's bug in `Tokenizer.explain`.

**Comment by adrianeboyd** [comment]
In most cases, we primarily want `Tokenizer.explain` to mirror `Tokenizer`. The docs are actually not 100% clear here, but checking the code, the long-standing behavior of `Tokenizer` is that special cases are checked before any other steps. The top-level explanation in the docs does prioritize special cases initially (https://spacy.io/usage/linguistic-features#tokenization), but the detailed step-by-step explanation and the pseudo-code doesn't (in this expanded box: https://spacy.io/usage/linguistic-features#how-tokenizer-works).

There was one exception to this recently where a mismatch between `Tokenizer` and `Tokenizer.explain` pointed to a bug in the tokenizer algorithm itself, where both `Tokenizer.explain` and the tokenizer documentation expected the same behavior, so there we actually did change the `Tokenizer` algorithm instead, in v3.2.0. But we don't take changes to the tokenizer algorithm lightly (it affects nearly all users), so in most cases unless the documentation clearly conflicts, we'd rather modify `Tokenizer.explain`.

Usually this doesn't come up in practice because there aren't interacting/overlapping `token_match` and exceptions.

**Comment by XavierDDD** [comment]
Got it, thanks for your explanation.
