### ISSUE TITLE
spacy-1.8.2: changing the default model download destination in cli/download.py

### ISSUE THREAD

**Issue by sdll** [explosion/spaCy#1063]
In [NixOS](https://nixos.org/), home directories of packages are read-only, which means that `python -m spacy download en` fails, because `pip` cannot just copy the model to site-packages.

One of the ways to approach this problem (inspired by [this](https://www.johbo.com/2016/using-pip-inside-of-nix-shell.html) and [this](https://stackoverflow.com/questions/2915471/install-a-python-package-into-a-different-directory-using-pip)) is to add the option of specifying the directory for the **spaCy** data (in case the option is enabled, for example, **spaCy** can possibly add `--install-option="--prefix=$SPACY_DATA"` to the `pip` commands it runs). 

This is similar to what **nltk** does while searching for models (there is an option to download all the models to the special directory `~/nltk_data`). It would be nice to have an opportunity to change the default directory by changing the environment variable. 

## Your Environment

* **Operating System**: https://github.com/NixOS/nixpkgs/pull/25791
* **spaCy version:** 1.8.2
* **Python version:** 3.5.3
* **Installed models:** 
* **Platform:** Linux-4.9.27-x86_64-with-glibc2.3.4

**Comment by ines** [comment]
Thanks a lot for the report and suggested solution!

Just to make sure I understand this correctly: In NixOS, packages can be installed via pip, but after installation, the site-packages are read-only? Or do you actually have to add an `--install-option` flag etc. every time you install via pip?

The `download` command itself is mostly a convenience wrapper for `pip install`, which installs the model data as its own package. So assuming package installation is not an issue, the main problem here might actually be the "shortcut links" spaCy creates after model installation. This is done by creating a symlink in `spacy/data` in the site packages, so this will obviously fail.

Does the model show up in your installed packages when you run `pip list` etc? If so, only the linking has failed and you can still import and use it as a module. Some users actually prefer this method over calling `spacy.load()`:

```python
import en_core_web_sm
nlp = en_core_web_sm.load()
```

If not, we definitely need to find a better way to customise the internal pip command spaCy runs. Some solutions we've been thinking about to solve the model downloading/linking/pip/environment problems: 

* Allow setting an environment variable (and maybe spaCy-internal option) to specify pip or site-packages path. It's important for spaCy to know whether a model is a pip package or just a model data directory, because the directory structure is different. (This will become slightly more relevant in v2.0 as well, since we want to get rid of all the different loading weirdnesses and instead have `spacy.load` resolve the model path – by checking for shortcut links, installed packages or direct paths.) 
* Improve overall error messaging when model linking fails – `link` is executed by `download`, which means that the download command will appear to "fail", even if downloading and installing a model was successful and only the linking failed. This is obviously bad.

**Comment by sdll** [comment]
@ines, 

Thank you very much for your quick reply!

> Just to make sure I understand this correctly: In NixOS, packages can be installed via pip, but after installation, the site-packages are read-only? Or do you actually have to add an --install-option flag etc. every time you install via pip?

**pip** cannot install any packages if run with default options, because **pip** tries to install the package to the **python** home directory, which is stored in `/nix/store`, just like any other package. In this way, for example, Nix allows to have different versions of the same package installed without producing any conflicts. The key is that `/nix/store` is read-only, and if the user wants to use some package, then it is symlinked to their _profile_.  

**pip** tries to modify the site packages in the **python** home directory, and fails. If, however,  `--install-option="--prefix=$SPACY_DATA"` is used, then the model is installed successfully to $SPACY_DATA/lib/python3.5/site-packages. It is not listed in the output of `pip list` though.

I like the idea with the environment variable containing the path to site-packages, because in this way the path to the site-packages directory, in which model installed with **pip**'s `--install-option"--prefix=$SPACY_DATA"` is located, can be appended to the variable.

**Comment by ines** [comment]
@sdll Thanks for the detailed response – that's good to know and the solution makes a lot of sense then!

The only problem we'll still have to solve is how to best make those packages installed to custom locations available from within spaCy (assuming `pip.get_installed_distributions()` won't work in this case, which is how spaCy normally checks if a string maps to an installed package). The easiest would probably be something like this:

```bash
# Install model to /some/path/lib/python3.5/site-packages
SPACY_PKG=/some/path python -m spacy download en
```

```python
from spacy.util import set_pkg_path
set_pkg_path('/some/path/lib/python3.5/site-packages')

# If a package path is set, spaCy won't try fetch packages via pip and 
# just look in this directory instead. Needs to be the exact path to 
# site-packages, though.
```

---

Btw, just to be make this clear in case others come across this issue later:
> You can use `spacy.util.set_data_path()` to change where spaCy expects the data to be loaded from

It's important to note that a model package != a data package. Model packages contain an outer wrapper for the data directory ([see here](https://spacy.io/docs/usage/models#download-manual)). So it's generally not wise to also use spaCy's data path as the pip site-packages path. This can easily lead to unexpected results when loading a model, because spaCy expects everything in `/spacy/data` to be a model data directory or a symlink to one. So in terms on internals and terminology, we should distinguish between a `data_path` and a `package_path`.

**Comment by ines** [comment]
Merging this with #1456!
