### ISSUE TITLE
can't load separate json patterns file

### ISSUE THREAD

**Issue by chamthesleeptalker** [explosion/spaCy#1068]
```
matcher.load("{{path to file}}", nlp.vocab)
````
produces the following error:
```
TypeError: unsupported operand type(s) for /: 'str' and 'str'
````
Looking at matcher.pyx, it might be at https://github.com/explosion/spaCy/blob/master/spacy/matcher.pyx#L191

## Your Environment

* Operating System: Win 10
* Python Version Used: 3.6
* spaCy Version Used: 1.8.2
* Environment Information: virtualenv

**Comment by ines** [comment]
Sorry for the late reply – it looks like `Matcher.load` doesn't perform a check on the path and convert it to a pathlib `Path` object. So the easiest workaround should be:

```python
from pathlib import Path
matcher.load(Path('/path/to/file'), nlp.vocab)
```

FYI, `Matcher.load` will be deprecated in v2.0. The way it currently works is pretty unideal, as it only allows saving patterns as JSON, but not the callback functions (which can now be assigned to a group of patterns to perform actions on each match). Since spaCy v2.0 will fully support Pickle, you'll be able to just pickle the `Matcher` to save its state. (For more info, see the [v2.0 alpha docs](https://alpha.spacy.io/docs/usage/rule-based-matching) on how rule-based matching is going to work in the future.)
