### ISSUE TITLE
How to resolve "Term 'ROOT' not found in glossary. "?

### ISSUE THREAD

**Issue by jarodtang** [explosion/spaCy#10817]
Hi There, 

I have installed newese spacy, and try to run something like this 

```
import spacy
nlp = spacy.load('en_core_web_sm')

doc1 = nlp(u'We can overtake them.')
doc2 = nlp(u'You must specify it.')
for i in range(len(doc1)-1): 
    if doc1[i].dep_ == doc2[i].dep_:
        print(doc1[i].text, doc2[i].text, doc1[i].dep_, spacy.explain(doc1[i].dep_))
```

And it continues with following warnings, how can I resolve it? ( I have tried to reinstall spacy, warning was stilll there).

Regards,
Jarod

```
We You nsubj nominal subject
can must aux auxiliary
/Users/Jarod/.pyenv/versions/3.8.3/lib/python3.8/site-packages/spacy/glossary.py:19: UserWarning: [W118] Term 'ROOT' not found in glossary. It may however be explained in documentation for the corpora used to train the language. Please check `nlp.meta["sources"]` for any relevant links.
  warnings.warn(Warnings.W118.format(term=term))
overtake specify ROOT None
them it dobj direct object

```

## Environment

* Operating System:
* Python Version Used: 3.8.3
* spaCy Version Used: 3.3.0
* Environment Information: MacOS

**Comment by polm** [comment]
This warning is because there is no glossary entry for ROOT. It's just the root of the sentence. So you aren't doing anything wrong. 

I will go ahead and add a glossary entry for that, but note that `explain` isn't really intended to be used in that way. Typically you would use it interactively the first time you see something, but not otherwise.

**Comment by jarodtang** [comment]
Thanks for your info.

BR/Jarod
