### ISSUE TITLE
How to improve NER accuracy?

### ISSUE THREAD

**Issue by ajige** [explosion/spaCy#1083]
## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information: 

I find the NER is quite weak.
My sentence is a headline:
**Avigilon Joins NVIDIA in Silicon Valley to Showcase Advanced AI Video Analytics at GPU Technology Conference**
I want to print all the name entities, in the below sentence:
nlp = spacy.load('en_default')
doc = nlp(line.lower())
for ent in doc.ents:
      print (ent.label_, ent)

The result is, it didnot print any name entity. How to improve this?

**Comment by ajige** [comment]
If I change the headline cases manually, as below:
**Avigilon joins NVIDIA in Silicon Valley to showcase advanced AI video analytics at GPU Technology Conference** 

It can recognize the below entity:
ORG Avigilon
ORG NVIDIA
LOC Silicon Valley
ORG GPU Technology Conference

But how can I change the word case automatically?

**Comment by honnibal** [comment]
We're getting pretty close to having an alpha ready for spaCy 2, which will feature much better NER. For now there are a few workarounds.

Probably the one I would try first is the following workflow:

1. Collect non-headline sentences on which spaCy seems to perform acceptably
2. Load two copies of the tagger and NER: `teacher` and `student`
3. Analyse your non-headline sentences with `teacher`
4. Change the casing of your sentences, to resemble headlines (i.e. title-case them)
5. Use the analysis from `teacher` and the re-cased sentences to train `student`.

It will take some fiddling to get this right, and the training API in 1.0 has some traps -- I suggest browsing around the issue tracker for previous threads about this. The main thing to keep in mind is to make sure you're training both the POS tagger and the NER, and that you're saving out all of the models, including the `vocab`.  `nlp.save_to_directory()` is the best way to do this. You'll want to add some tests to ensure that you're getting the same results after saving and loading, to make sure it's being done correctly. The master branch also has a `dropout` option, which is not supported in the version on pip. This might be useful if you want to train on not much text.

The philosophy behind this approach is pretty simple. Instead of pre-processing the headline text to resemble normal text, we teach the models to analyse the text the same regardless of how it is cased.

**Comment by ines** [comment]
See the [v2.0.0 alpha release](https://github.com/explosion/spaCy/releases/tag/v2.0.0-alpha) notes and #1105 🎉

The workflow described above will be ported over to the docs as well, including code examples and more details.

**Comment by arjunmenon** [comment]
If I can bring to your attention. There is an automatic [truecasing library](https://github.com/nreimers/truecaser) available which does the job you described.

If you can include it in the main framework and make it zippy, this would swallow most informal text issues, particularly on twitter data.
