### ISSUE TITLE
Incorrect underscores in lemmas - Dutch

### ISSUE THREAD

**Issue by JannesSarens** [explosion/spaCy#10876]
## How to reproduce the behaviour

While extracting lemmas using the Dutch pipeline, certain words unexpectedly have an underscore in their lemmas.
Example:
```
nlp_nl = spacy.load('nl_core_news_lg')
sentence = "Wij zullen ons aansluiten bij deze voorstellen. We gaan een verklaring afleggen voor de projectbegroting want dat is onze beroepsactiviteit."
doc = nlp_nl(sentence)
for token in doc:
  print(token.lemma_)
```

Results in the following:
```
wij
zullen
ons
aan_sluiten
bij
deze
voorstel
.
we
gaan
een
verklaring
af_leggen
voor
de
project_begroting
want
dat
zijn
ons
bero_epsactiviteit
.
```
A few weeks/months back, this wasn't occurring. 
I tested with the small Dutch model as well -> it seems fewer words incorrectly have an underscore with this model. Using the same example, the lemma of 'projectbegroting' and 'beroepsactiviteit' is correct.

## Your Environment
* Operating System: Windows
* Python Version Used: 3.8.10
* spaCy Version Used: 3.3.0

**Comment by polm** [comment]
Thanks for the report! This is probably due to the introduction of the new [edit-tree lemmatizer](https://explosion.ai/blog/edit-tree-lemmatizer) in recent versions. We'll take a look at what's up.

**Comment by adrianeboyd** [comment]
Yes, this is due to the switch from the rule-based lemmatizer to the trainable lemmatizer, which learns the lemmas from the training corpora (currently UD Dutch Alpino and UD Dutch Lassy Small). They appear to use `_` for compound boundaries and separable verb particles. We agree that we don't really want these characters in the spacy lemma output, so for the v3.4. we'll plan to remove the `_` characters from our training data.

For the v3.3.0 models, you could switch back to the rule-based lemmatizer to get the same lemmas as in v3.2.0.
