### ISSUE TITLE
Different results

### ISSUE THREAD

**Issue by prabhatM** [explosion/spaCy#1089]
I was trying to extract noun chunks from the following 

" Achilles tendon rupture, left lower extremity. Primary repair left Achilles tendon. The patient was stepping off a hilo at work when he felt a sudden pop in the posterior aspect of his left leg. The patient was placed in posterior splint and followed up at ABC orthopedics for further care."

I get different results from my local machine Spacy installation and online demo site - http://textanalysisonline.com/spacy-noun-chunks-extraction

The online result is better. But why ?

I use window 7, Python 2.7.12, Spacy 1.8.2 and default english model.

**Comment by honnibal** [comment]
The default English model is only 50mb. During training a heavy L1 penalty is applied to force the model to make most features 0-weight, so that a smaller model is produced, at the cost of accuracy. If you download the `en_core_web_md` model, results should be close to what you see on the web demo (although they may be slightly different). The v2 neural network models will be both small and accurate, but somewhat slower than the linear models.

**Comment by prabhatM** [comment]
Hi,
Thank you for the clarification.
I should have thought about it.

Regards
Prabhat Mohanty
