### ISSUE TITLE
Setting up new language model - Instructions

### ISSUE THREAD

**Issue by praveen049** [explosion/spaCy#1091]
Seems there is a possible issue with the instructions provided here:
https://spacy.io/docs/usage/adding-languages
The instructions provided for adding new language include modifying the setup.py in ~/spacy directory.
But this file does not exist in this directory. 
Also, it's possible to add new language model without the changes mentioned in this file. 
Are the instructions outdated or am i missing something ?
   

 Info about spaCy

    Python version     2.7.5
    Platform           Linux-3.10.0-514.16.1.el7.x86_64-x86_64-with-redhat-7.3-Maipo
    spaCy version      1.8.2
    Installed models
    Location           spacy

**Comment by ines** [comment]
If you want to add your own language and language data, you'll need to clone the GitHub repository and then compile spaCy from source (see the [installation docs](https://spacy.io/docs/usage/) for more info).  This will let you make modifications to the source and then rebuild your modified version of spaCy. This should probably be more clear in the instructions, sorry!

Btw, If you're using the latest version from master, you won't actually have to modify the [`setup.py`](https://github.com/explosion/spaCy/blob/master/setup.py) anymore – a few weeks ago, we changed it to use `find_packages` to list all available directories automatically.

> Also, it's possible to add new language model without the changes mentioned in this file.

This depends on what you're trying to do – if you want to train a language model for a language that's not yet available or in [alpha support](https://spacy.io/docs/api/language-models#alpha-support), you'll have to add the `Language` subclass and data to spaCy first. This is necessary so that spaCy knows how to tokenize the new language, and where to find all other language-specific data.

**Comment by praveen049** [comment]
Thanks for the response, Its working fine now.
