### ISSUE TITLE
fill install in window

### ISSUE THREAD

**Issue by jingtianming1** [explosion/spaCy#1100]
I try install spacy in window,I set cl.exe and set INCLUDE with D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include  ；C:\Users\asus\AppData\Local\Programs\Common\Microsoft\VisualC++forPython\9.0\VC\include
but is alway tell me    ***.h not find,and   alway   tell    me
 preshed/maps.cpp': No such file or directory
please help me

**Comment by ines** [comment]
Sorry for only getting back to you now. I think the best solution would be to use `conda`.

We're currently waiting to get spaCy v2.0 built for conda (it's just taking a bit longer because of Travis errors and the OSX backlogs 😓). If there are still problems with conda install and the new version, feel free to reopen.
