### ISSUE TITLE
Should pin an old-ish version of numpy in the pyproject.toml build requirements

### ISSUE THREAD

**Issue by njsmith** [explosion/spaCy#11020]
Currently, spacy's pyproject.toml `build-system.requires` key declares a requirement on numpy that's unbounded on the upper end:

https://github.com/explosion/spaCy/blob/9738b69c0e3babb365cafaa26b872ca1028c9696/pyproject.toml#L10

This means that if you do `pip install spacy` on a platform where no wheels are available -- e.g., Linux/arm64, as used by everyone running docker on macOS w/ Apple Silicon -- then pip will automatically build a spacy wheel from source, and in the build environment, it will install the newest available version of numpy.

Yesterday, numpy v1.23.0 [was released](https://pypi.org/project/numpy/1.23.0/), which apparently bumped the numpy C ABI version. The way numpy's ABI works is: you can build your extension against any version of numpy that has all the features you need, and then your built binary is guaranteed to run on that version *or* any newer version.

So consider a requirements.txt that uses pinning, like:

```
spacy==3.3.1
numpy==1.22.4
```

And let's say you do `pip install -r requirements.txt` inside a docker container on an M1 mac. As of yesterday, this will fail, because:

- pip observes there's no prebuilt wheel for spacy
- so it pulls down the source distribution, and builds it
- the source distribution's `pyproject.toml` requests that the latest version of numpy be available in the build environment, so pip installs numpy 1.23.0 in a temporary environment, and uses this to build a spacy wheel
- then pip installs this spacy wheel into the actual environment that we're trying to set up, which has numpy 1.22.4.

Now attempting to import `spacy` will fail with:

```
Traceback (most recent call last):
  File "__init__.pxd", line 942, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...", line 14, in <module>
    import spacy
  File "/usr/local/lib/python3.9/site-packages/spacy/__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "/usr/local/lib/python3.9/site-packages/spacy/pipeline/attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy/pipeline/pipe.pyx", line 1, in init spacy.pipeline.pipe
  File "spacy/vocab.pyx", line 1, in init spacy.vocab
  File "spacy/lexeme.pyx", line 6, in init spacy.lexeme
  File "__init__.pxd", line 944, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
```

To avoid this confusing failure, spacy should pin an old-ish version of numpy in its pyproject.toml, e.g. the oldest version that spacy still supports. This won't force users to use an old version of numpy -- just the opposite. It just means that spacy will be *built* against an old version of numpy, so when it comes to actually *using* spacy, users can pick any newer version and it should work just fine.

**Comment by adrianeboyd** [comment]
So we've considered doing this and we did do it briefly for a few patch releases, but it's extremely difficult to maintain and do well. It ends up looking like this, and continually breaks / requires maintenance / isn't compatible with new architectures:

https://github.com/scipy/oldest-supported-numpy/blob/main/setup.cfg

Instead, we recommend using build constraints with `PIP_CONSTRAINT`.

**Comment by njsmith** [comment]
Oh, ick, right, now I remember why this is hard :-/

Are you saying that if you set the `PIP_CONSTRAINTS` environment variable, then that propagates through and applies to the isolated scratch environments that pip uses to build packages from source? That's a neat trick! I... kinda suspect the pip authors would be surprised to learn that that's possible.

**Comment by adrianeboyd** [comment]
This is all extremely frustrating for users but I haven't found a better solution. Even if you did something like `oldest-supported-numpy`, it's only really relevant for which versions have wheels on pypi and isn't general enough for all potential use cases.

The constraints in `pyproject.toml` are technically correct and then `wheelwright` always applies `build-constraints.txt` when building wheels for pypi if it's present in the repo (mainly `blis`, `thinc`, `spacy`, but also a few others).

`PIP_CONSTRAINT` propagates through, `pip install -c` doesn't. I don't think it's intentional that they behave differently (the env vars are just supposed to mirror the commandline options), but I'm pretty sure they're aware of this and there's been some discussion about what to include from the settings when setting up the isolated build envs. I haven't checked on the status of this in pip in a while, though.

If we put tighter constraints in `pyproject.toml`, they are extremely hard to override just with `pip`, but if we leave `pyproject.toml` as it currently is, then users can still override as necessary when installing from the source package on pypi.

I extended the thinc install instructions recently to include `PIP_CONSTRAINT` but haven't made the same changes in the spacy docs yet, I don't think.

Publishing wheels for more architectures is probably the most helpful thing to do for users related to this.

**Comment by njsmith** [comment]
Yeah, when setting up isolated build envs there's a set of configuration they explicitly pass through, basically package index configuration, binary/source preferences, and `--pre`:

https://github.com/pypa/pip/blob/422719863a061640a84c6292e7d86d81e22c938c/src/pip/_internal/build_env.py#L227-L273

So `PIP_CONSTRAINT` is just sneaking through accidentally as part of the ambient environment. IMO this is actually a bug in pip -- for the isolated pip, they should be sanitizing the environment by removing all `PIP_*` options, because that's the only way to reliably control what's being passed through and what isn't. But... that's neither here nor there really, just some observations.

> Publishing wheels for more architectures is probably the most helpful thing to do for users related to this.

Yes, let's do this :-)

**Comment by baxtree** [comment]
My two cents for a temporary workaround although it seems slowing down a few operations:
```
DOCKER_DEFAULT_PLATFORM=linux/amd64
```

**Comment by adrianeboyd** [comment]
I think that that only helps because it switched to precompiled wheels from pypi that were built with the correct build constraints.

We just published linux aarch64 wheels for the recent versions of most of packages, so I'd suggest trying it again without the setting.
