### ISSUE TITLE
pip install spacy throwing error python 3.5

### ISSUE THREAD

**Issue by Jethi** [explosion/spaCy#1116]
Hi when I tried to install spacy I am getting the following error. Please help me with this issue.

![image](https://user-images.githubusercontent.com/8430165/26932371-ef328d68-4c80-11e7-8d68-ee1f28496e7e.png)

spacy whl version: spacy-1.8.2-cp35-cp35m-win_amd64.whl

**Comment by ines** [comment]
Which download command did you use? `conda install -c conda-forge spacy`?

I just did a quick Google search for the error and it seems to be related to conda and pip, see [here](https://stackoverflow.com/questions/42543863/installing-tensorflow-with-gpu-in-windows-fails-with-exception) or here for example: https://github.com/tensorflow/tensorflow/issues/7556

**Comment by Jethi** [comment]
Hi @ines conda install -c conda-forge spacy this actually works. Earlier I tried with pip install which gave the 
"AttributeError: 'NoneType' object has no attribute 'splitlines' error. 
Now Spacy is installed, but when I am trying to do 'python -m spacy download en_core_web_sm I am getting again the above error "AttributeError: 'NoneType' object has no attribute 'splitlines' error. "

Your help is much appreciated :smile:

**Comment by Jethi** [comment]
hey @ines  I found the above issue in this loop https://github.com/tensorflow/tensorflow/issues/7556

I re-installed version 1.7.3 for spacy and downloaded the en model. It worked. One question though, the spacy version I installed was of version 1.8.2 from conda. doesn't conda have en model for the above spacy version?

**Comment by ines** [comment]
Glad it worked!

The models all need to be downloaded separately – they don't come with spaCy, and they're also not available via the package managers.

When you call `python -m spacy download en`, spaCy gets the model download link from our [spacy-models](https://github.com/explosion/spacy-models) repository. Because the models are all Python packages, spaCy uses pip to install them. But under the hood, all models are `.tar.gz` archives that are downloaded via an URL. This means you can also download and install them manually (for more info, see the [models docs](https://spacy.io/docs/usage/models#download-manual)).
