### ISSUE TITLE
Example.to_dict doesn't include spans

### ISSUE THREAD

**Issue by stefawolf** [explosion/spaCy#11260]
I'm working with data augmentation for examples that include spans. I think there is a bug in the Example.to_dict method where data about spans gets lost.

```
def to_dict(self):
        return {
            "doc_annotation": {
                "cats": dict(self.reference.cats),
                "entities": doc_to_biluo_tags(self.reference),
                "links": self._links_to_dict()
            },
           ....
      }
```
Is it correct, that something like `spans: dict(self.reference.spans)` should be added? I'll try to open a PR with this solution.

**Comment by adrianeboyd** [comment]
Since `Example.from_dict` supports this, I think it makes sense to include the spans in the `Example.to_dict` output. The spans format in the output needs to be supported by this method, which is expecting a format with the span information in tuples rather than as `Span` objects:

https://github.com/explosion/spaCy/blob/2d89dd9db898e66058bf965e1b483b0019ce1b35/spacy/training/example.pyx#L456-L476

I initially thought `doc.spans` wasn't supported at all here, since it's not in the docs and this is more of a transition format from the simple v2 training dict format than something that is intended to support all possible doc annotation.

**Comment by stefawolf** [comment]
Ok, thanks! I've updated my PR #11261 to use tuples instead of spans now.
