### ISSUE TITLE
Tokenizer special case doesn't work when followed by punctuations.

### ISSUE THREAD

**Issue by acohan** [explosion/spaCy#1135]
The tokenization special case handling is not working when there is a punctuation after the special token. To replicate:

```
import spacy
from spacy.symbols import ORTH, LEMMA, POS
nlp = spacy.load('en', vectors=False,parser=False, entity=False) 
nlp.tokenizer.add_special_case(u'<MATH>', [{ORTH: u'<MATH>'}])
doc1 = nlp('This is a test <MATH>. Another <MATH> token.')

[e.text for e in doc1]

Out[4]: 
['This',
 'is',
 'a',
 'test',
 '<',
 'MATH>.',
 'Another',
 '<MATH>',
 'token',
 '.']
```

As you can see the first `<MATH>` breaks into `<` and `MATH>.'

* **spaCy version:** 1.8.2
* **Platform:** Linux-4.4.0-78-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.5.2
* **Installed models:** en

**Comment by honnibal** [comment]
This is a tricky case. The problem is that the final period doesn't segment off, because it's attached to a `>` character. If the `suffix_re` expression is updated to split this, it should work. I'm not sure we want to do this by default though.

Given that the `.` doesn't split off, the lack of match from the special-case rule is expected behaviour: the special cases only trigger over whole chunks, not substrings.

**Comment by saiabishek1** [comment]
@honnibal How should I change the `suffix_re` expression to split <MATH> into <,MATH,> instead of <,MATH> ?
