### ISSUE TITLE
Thought on StringStore

### ISSUE THREAD

**Issue by aikramer2** [explosion/spaCy#1139]
To reduce storage requirements, and potentially speed up lookups, are we interested in converting the string store to a generalized suffix tree?

**Comment by honnibal** [comment]
It's not an idea I've explored. I'd be interested if it indeed performed better. Here's the current data structure (hash table with open addressing and linear probing):

https://github.com/explosion/preshed/blob/master/preshed/maps.pxd

And the store itself:

https://github.com/explosion/spaCy/blob/master/spacy/strings.pxd

Each entry in the hash table stores only the 64-bit key and the 64-bit pointer. A small string optimisation is used so that we make use of the 64-bit pointer for the string value if it's less than 7 characters. So for short strings, we're only storing the 64-bit hash and the string content. We maintain between 50% and 75% density, so on average for each 128bit entry we have between 64 and 128 bits of overhead (for the empty portion of the hash table).

For a short string, lookups will take 2 memory reads (one to fetch the value from the table, the other to read the pointer). Longer strings take 3 reads, because we have to follow the pointer to the string content as well.

I haven't studied suffix trees in detail, but my understanding is that there's no easy way to keep the tree contiguous in memory, while also being able to insert elements? If we have to chase pointers to do lookups, I suspect the tree would perform worse than the current hash table, and will require more memory.

The data structure/algorithm in the library that I'm least happy with at the moment is the `Matcher`. When I wrote the `Matcher` code I tried to get away with a very simple algorithm. It's since been retrofit with quantifiers, but the quantifiers are buggy. The current implementation is pretty half-assed. It really needs someone to sit down and rethink this properly. It's a well-studied problem, after all.
