### ISSUE TITLE
the yellow icons for "Needs statistical model" in SpaCy 101

### ISSUE THREAD

**Issue by karst10607** [explosion/spaCy#1149]
https://alpha.spacy.io/docs/usage/spacy-101#features

Hi there, I am a tech writer and I volunteer to work on the Chinese translation for this manual.
Here's my page https://syntaxed.atlassian.net/wiki/x/WaxKAg
I am stuck here becuase I don't understand what the yellow icon means here.
Does it mean "it depends"?
Surely green means "yes, it requires model"
Red means "no, it doesn't need to install a model"

Am I getting a wrong understanding?
Thanks!

**Comment by ines** [comment]
Sorry – just realised that this is probably not very clear. But yes, it's supposed to mean "it depends" or "not necessarily".

For example, serialization in itself doesn't require a statistical model – but if you want to serialize a model's output, you'll obviously need a model installed. The same goes for training, because you can start without a model and train it from scratch. But maybe the choice of icons here actually makes it _more_ confusing instead of more clear.

(Btw, thanks again for the translation and the progress so far! 👍)

**Comment by karst10607** [comment]
Ok, thank you for the fast response. It's really fast!
I will think about how to write that clearly in Chinese.
You are welcome ines, I aslo learn a lot in the process of studying SpaCy 101 !
I will create new issues when encountering new troubles.
