### ISSUE TITLE
Is activation function is added to NER,POS classification?

### ISSUE THREAD

**Issue by search4mahesh** [explosion/spaCy#1160]
Hi,

 Is activation function is added to NER,POS classification which can give us non linear functionality/classifier?

Thanks
Mahesh

**Comment by honnibal** [comment]
The 1.8 models use a linear classifier, while the v2 models use neural networks, that include non-linear activations. I think from your question, it's possible you might have some misconceptions about how these things work. You might find it useful to create your own small implementation of these systems, so that you can play with all the elements of the solution yourself.
