### ISSUE TITLE
v2: inconsistency in token.shape_

### ISSUE THREAD

**Issue by ankesh-pandey** [explosion/spaCy#1164]
string: "3/14-present"
correct shape: d/dd-xxxxxxx
output shape: d/dd-xxxx

I used the following code:

import en_core_web_sm
parser = en_core_web_sm.load()
parsed = parser(unicode("3/14-present"))
for token in parsed:
	print token.orth_, token.pos_, token.shape_

This behaviour is common to all strings with number of small letters more than 4. is it by design?
or am i missing something?

# Environment
* Operating System: Ubuntu 15.04
* Python Version Used: 2.7
* spaCy Version Used: 2.00 aplha

**Comment by Liebeck** [comment]
Yes, it is by design, check https://github.com/explosion/spaCy/blob/master/spacy/orth.pyx#L137-L162
I must admit that I wondered about the issue three weaks ago as well. Maybe we should update the documentation and insert the hint that more than 4 following characters of the same _class_ will be truncated.

**Comment by ankesh-pandey** [comment]
Thanks for the clarification @Liebeck :)
