### ISSUE TITLE
AttributeError: attribute 'suffix_' of 'spacy.tokens.token.Token' objects is not writable

### ISSUE THREAD

**Issue by killia15** [explosion/spaCy#11658]
I found a case with the Spanish model where it doesn't properly capture the suffix for the conditional. Ex. moriríamos should have a suffix of íamos instead of just mos. This also leads to the incorrect lemmatization for the conditionals. I looked into overriding the nlp.tokenizer.find_suffix method but it looks like it's a cython function and I don't have access to the original. I'd like to keep everything else about the tokenizer - just fix the conditional suffixes.

So my next idea was to add step to the pipeline where I override the suffix, but it looks like there's not a setter implemented. There was a similar case with #973 where there was no setter for Token.lemma_. Is this something that the maintainers would be open to me contributing, or if there a specific reason not having it?

Also, is there a way to get the Tokenizer.find_suffix function for Spanish? That might be easier if I could fix that. That's another contribution that I'd be happy to give as well.

**Comment by polm** [comment]
Thanks for the report about this, this does seem to be a limitation in the models related to handling of suffixes. Just to be clear though, there are a couple of different but unrelated suffixes that have come up here:

- `Token.suffix` is a string of fixed length and not determined based on linguistic details, which is why you can't set it (it's a computed value)
- `Tokenizer.find_suffix` refers to suffixes to split off of tokens, like punctuation, or units, or something, not morphological suffixes
- There is no explicit representation of a linguistic suffix in spaCy (well, it could be in individual languages, but it's not in the Spanish lemmatizer anyway)

There is a genuine issue that the models need some way to see suffixes so that they can make reasonable predictions internally, and a fixed-length short suffix isn't good enough for that. @richardpaulhudson is working on improving that in #11583. 

As a workaround for this right now, you could look at training a custom model where the suffix length is greater than the default 3. That can be configured in the tok2vec settings when you set up a model. You still won't get a suffix that's linguistically defined, but the models should be able to do better with extra information than without enough information.
