### ISSUE TITLE
Documentation doesn't have good search engine optimization

### ISSUE THREAD

**Issue by swetepete** [explosion/spaCy#11697]
After getting much more experienced with Spacy I have gotten better at knowing specific keywords I am searching for in the documentation, or specific questions I have. If I Google these questions, what very frequently comes up are very, very general Spacy documentation pages like "SpaCy 101: Everything you need to know" and "Linguistic Features". The information may be on that page, but it doesn't jump to the relevant section and it's actually somewhat hard to know where in all that info is the answer to your question. Space's internal search is great but Google isn't linking to highly specific topics in its search results.

By contrast, if you google "mdn html reference a href" the first link is a webpage clearly titled "a: The Anchor element - HTML: HyperText Markup Language". So it's much easier to search for a specific command or concept and get a single specifically categorised page on just that topic.

## Which page or section is this issue related to?

All of Spacy

**Comment by polm** [comment]
Thanks for the suggestion, I've also run into this before. We'll look into this, but if you have any concrete suggestions we'd be happy to consider them.

**Comment by swetepete** [comment]
Thanks.

I'm not experienced enough to have a concrete suggestion but I think since you don't want to make separate webpages for each topic you can get Google to link to page sections with the "#" in the URL, this is about Jump Links, could be a start:

https://www.sebkin.de/en/tutorials/seo-jump-links

Also, each individual page of Spacy's documentation doesn't have a table of contents for that class: https://spacy.io/api/lemmatizer

And the font is quite big so you have to scroll from top to bottom wondering if what you're looking for is even there. It would be better to see compactly at the top all the class methods, attributes, page sections, etc. listed so I could quickly realize this page isn't what I was looking for.

Thanks

**Comment by swetepete** [comment]
Actually I see now that Spacy already has jump links, maybe the only solution is to create an index for the whole package, so you don't have to redesign your current documentation pages.

Actually this is really common amongst programming languages to have a super dense page where every single relevant keyword is listed with links. It could also show pure programmatic information like arguments of functions. I think Spacy could benefit from having that one dense, comprehensive page in addition to the more explanatory API. Thanks very much

**Comment by polm** [comment]
Thanks for the suggestions! We'll take a look at implementing them and the idea more generally.

I will say I think it's pretty hard to get good SEO for docs in general though - the official Python docs are pretty well known for regularly ranking below random blog posts reiterating them. 

Also note you can tell Google has picked up on our anchor links, as seen in this search result:

![2022-10-28T20-01-26](https://user-images.githubusercontent.com/286278/198572431-56c511be-a15b-4fec-a0e2-5b2a419d5f6c.png)

So that's working at least.

**Comment by polm** [comment]
Following up on this a little, I confirmed we already have a sitemap that lists all our pages for indexing, and our API pages list basically all our documented functions, along with their arguments, which seems pretty consistent with other packages. 

Since there's no other concrete action here, I'll go ahead and mark this as resolved for now, but we'll continue to keep it in mind and look for ways to improve - thanks for bringing it to our attention!
