### ISSUE TITLE
Sample values of positional arguments in examples/multi_word_matches.py

### ISSUE THREAD

**Issue by ghosthawkone** [explosion/spaCy#1173]
I've been trying to figure out how to run the example programs in the examples/ directory. 
Specifically, when I try to run examples/multi_word_matches.py, I get this:

```
usage: multi_word_matches.py [-h] patterns_loc text_loc counts_loc [n]
multi_word_matches.py: error: the following arguments are required: patterns_loc, text_loc, counts_loc

```
I can tell that patterns_loc and counts_loc seem to be directories. 
What are their directory structures, and where can I find a sample patterns_loc and counts_loc directory?

I'm quite new to the NLP scene. Maybe that could be the source of my frustration. 

Environment
 * **spaCy version:** 1.8.2
* **Platform:** Linux-4.4.0-83-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.1
* **Installed models:** en

**Comment by ines** [comment]
Sorry for only getting to this now! We've since released a new version of spaCy, v2.0, which comes with a lot of improvements around the `Matcher` API, including a new `PhraseMatcher` that lets you match large terminology lists as `Doc` objects. See here for details:

* [Matching usage guide](https://spacy.io/usage/linguistic-features#section-rule-based-matching)
* [`phrase_matcher.py` example](https://github.com/explosion/spaCy/blob/master/examples/information_extraction/phrase_matcher.py) of matching mutli-word tokens
