### ISSUE TITLE
Errors in SpaCy Polish language lemmatization

### ISSUE THREAD

**Issue by DamianBisewski** [explosion/spaCy#11756]
I'm using SpaCy for lemmatization of tweet texts written in Polish. Unfortunately, many Polish words are lemmatized incorrectly - this includes spelling errors and misidentification of parts of speech.
Versions of libraries:
spacy 3.4.2
model pl_core_news_lg  3.4.0
windows 11
python 3.10

Examples of incorrect lemmatization are shown below. These are not all the cases the lemmatizer worked differently than expected:
|word| Actual lemm. | Expected lemm. |
|:-------:|:-------:|:-------:|
|ciągniesz| ciągnieć | ciągnąć |
|zawiodłam| zawiodć być | zawieść |
|Wysyła| wysyć | wysłać |
|podpalonych| podpaloć | podpalić |
|załatwione| załatwiyć | załatwić |
|zamówieniu| zamówiyć | zamówić |
|zamówionego| zamówiyć | zamówiony |
|Znalazłem| znalazłem | znaleźć |
|zawiodłem| zawiodć być | zawieść |
|dostarczenia| dostarczeć | dostarczyć |
|nasycone| nasycyć | nasycić |
|Przestancie| przestant | przestać |
|Zakupy| zakupa | zakup |
|kruszcu| kruszc | kruszec |
|Wspaniały| wspaniać | wspaniały |
|zabezpieczony| zabezpieczić | zabezpieczony |
|dostarczone| dostarczić | dostarczyć |
|Szybka| szybky | szybki |
|zajrzę| zajrząć | zajrzeć |
|zamówione| zamówiyć | zamówić |
|dostarczenia| dostarczić | dostarczyć |
|wspaniały| wspaniać | wspaniały |
|spisuje| spisować | spisywać |
|sportowcom| sportowc | sportowiec |
|odnalezienie| odnalezieć | odnalezienie |
|kupiony| kupiić | kupić |

**Comment by adrianeboyd** [comment]
Thanks for the report, we'll take a look!

We're using the new trainable lemmatizer for Polish in the v3.3+ pipelines because there were overall performance improvements vs. the previous lemmatizer, but the kinds of you see with a statistical lemmatizer can be quite different than for lookup or rule-based lemmatizers.

If you'd like to try out the previous POS lookup-based lemmatizer, you can switch back as described under "Switch from trainable lemmatizer to default lemmatizer" here: https://spacy.io/models#design-modify

**Comment by DamianBisewski** [comment]
Thank you, @adrianeboyd , for the answer. I tried to do what is written in the link you sent me. So firstly I ran the lines:
```bash
nlp = spacy.load("pl_core_web_sm")
assert nlp.get_pipe("lemmatizer").is_trainable
```
It worked fine. I proceeded to:
```bash
nlp.remove_pipe("lemmatizer")
nlp.add_pipe("lemmatizer").initialize()
```
However this gave me an error:
```bash
File "J:\nlp-senti\test.py", line 85, in <module>
    nlp.add_pipe("lemmatizer").initialize()
  File "J:\nlp-senti\venv\lib\site-packages\spacy\pipeline\lemmatizer.py", line 159, in initialize
    lookups = load_lookups(lang=self.vocab.lang, tables=required_tables)
  File "J:\nlp-senti\venv\lib\site-packages\spacy\lookups.py", line 30, in load_lookups
    raise ValueError(Errors.E955.format(table=", ".join(tables), lang=lang))
ValueError: [E955] Can't find table(s) lemma_lookup_adj, lemma_lookup_adp, lemma_lookup_adv, lemma_lookup_aux, lemma_lookup_noun, lemma_lookup_num, lemma_lookup_part, lemma_lookup_pron, lemma_lookup_verb for language 'pl' in spacy-lookups-data. Make sure you have the package installed or provide your own lookup tables if no default lookups are available for your language.

Process finished with exit code 1
```
How can I resolve this mistake?

**Comment by polm** [comment]
Did you install `spacy-lookups-data`?

**Comment by richardpaulhudson** [comment]
Thanks for the detailed list of errors. We're aware of some of the issues with the trainable Polish lemmatizer and I'm looking at various ways to resolve them.

I was originally confused by lemmas like `zamówić być` as well (I speak Polish myself) but that is how such forms are labelled in the training corpus we used, and on reflection / further investigation it turns out that this labelling is not actually incorrect, just somewhat unintuitive.

The point is that the final morpheme in forms like `zamówiłam` and `zamówiłem` is historically a form of the verb `być` even though you wouldn't necessary feel it to be such analysing the modern language synchronically. This can still be seen in marginal forms like `Głodnyś?` ('are you hungry?'). In constructions such as `Myślałem, żeś to zrobiła` to mean `Myślałem, że to zrobiłaś` ('I thought you'd done it') where the morpheme derived from `być` is realised separately from the verb it is modifying, it is impossible to lemmatise the two parts of the verb together, which is why the authors of the training corpus chose to separate them everywhere.

**Comment by DamianBisewski** [comment]
There is no such thing as a "double infinitive" in Polish. The earlier version of the lemmatizer didn't have this "być" and it was correct. "Myślałem, żeś to zrobiła" is in the past tense, and even if it comes from any past version of Polish, this does not change modern Polish grammar, in which such infinitives as "zrobić być" do not exist.

**Comment by richardpaulhudson** [comment]
This is an interesting conversation, but ultimately we're discussing something neither of us control. spaCy allows you to train models using any training corpora. Where we find a training corpus or corpora whose license allows it, we publish a standard model for a language as an example that people can use or not use depending on whether it meets their needs. In this case the authors of the training corpus we used had made the decision to label these constructions in this way. If you can source another training corpus that has labelled them differently (or label one yourself) you can certainly train a model with it, and if the license fits we could even consider switching to it for the standard model.

"Earlier" and "later" versions of the lemmatizer are also something of a misnomer. Although the new statistical lemmatizer model is now in the published standard model, we're continuing to support the rules-based model because we realise it better meets many users' requirements. So you are free to use either.

**Comment by DamianBisewski** [comment]
Yes, thank you for your answer. I conducted a series of tests and for me just the rules-based lemmatizer seems to work significantly better than the statistical lemmatizer. I understand that the statistical lemmatizer had to be fed with data and the data may have had some flaws, but I only wanted to report some errors in its work.

**Comment by richardpaulhudson** [comment]
Thanks again for your error analysis — as I mentioned above I'm currently working on a series of strategies to improve the accuracy of the statistical lemmatizer and am using your list of errors as one of the resources to test these strategies. Although a machine-learning-based lemmatizer will probably always throw up occasional errors that can't be readily explained, please watch this space as I hope we can publish a Polish statistical lemmatizer with improved accuracy in the near to medium future.
