### ISSUE TITLE
token.like_url triggers for plain filenames

### ISSUE THREAD

**Issue by marhoy** [explosion/spaCy#11786]
## Problem

The `token.like_url` property is `True` even for plain filenames that doesn't contain any URL-like details:

## How to reproduce the behaviour

```
>>> import spacy
>>> nlp = spacy.load("en_core_web_lg")
>>> doc = nlp("This text contains test.jpg, which is a filename, NOT a URL")
>>> [token for token in doc if token.like_url]
[test.jpg]
```

## Your Environment
* Operating System: Linux
* Python Version Used: 3.10.6
* spaCy Version Used: 3.4.2

**Comment by adrianeboyd** [comment]
If you're noticing this as a difference to earlier versions of spacy, it's because we added the same URL regex that's used in the tokenizer to `LIKE_URL` in v3.2.0.

The URL regex is fairly permissive in order to tokenize things like `whatever.newtopleveldomain` as a single token, so it doesn't really distinguish between filenames and domain names.

If you'd prefer `LIKE_URL` to be more strict, you can customize it in a custom language just like any other defaults, as described here: https://spacy.io/usage/linguistic-features#language-subclass

The customization for `LIKE_URL` looks the same as the customization for `LIKE_NUM` that's already in most language definitions, e.g.:

`LIKE_NUM` defintion for `English`:

https://github.com/explosion/spaCy/blob/322b5dc1df7031139780963cebaa081a75384834/spacy/lang/en/lex_attrs.py#L22-L44

And how it's added to the defaults:

https://github.com/explosion/spaCy/blob/322b5dc1df7031139780963cebaa081a75384834/spacy/lang/en/__init__.py#L6-L18

The current `LIKE_URL` definition is here, which you can copy and modify as you'd like:

https://github.com/explosion/spaCy/blob/322b5dc1df7031139780963cebaa081a75384834/spacy/lang/lex_attrs.py#L90-L115
