### ISSUE TITLE
Dependency hell with regex library due to lack of semver

### ISSUE THREAD

**Issue by bpartridge** [explosion/spaCy#1184]
Somewhere in our stack we had an old version of regex, `regex 0.1.20110315`, installed by an old dependency. However, PR #996 began to use more recent features, including the presence of a constant `regex.VERSION1`. For some reason, `spacy==1.8.2` didn't ensure that `regex` was recent enough, and so tried to use that old version. It compiled and installed fine, but every `import spacy` would be met with:

`AttributeError: 'module' object has no attribute 'VERSION1'`

Setting `regex>=2017.06.23` in my own requirements.txt fixed the problem. Spacy should probably do something similar in its setup.py so others don't run into this.

## Your Environment

* Operating System: both OS X and Ubuntu 14.04
* Python Version Used: 2.7.12
* spaCy Version Used: 1.8.2
* Environment Information:

**Comment by ines** [comment]
Thanks for the report and analysis – will look into this!

`regex` is a little annoying in that respect because it doesn't use semver... I think we've already had similar problems in the past, and I vaguely remember some problems with using `>=` and pip not being able to resolve it properly because of the date-based versioning. (At least, something like this is definitely the reason we've had to use `regex==` in the requirements.)

**Comment by saitogroup** [comment]
I'm also having this problem @bpartridge ; can you explain where you find this requirements file that I can modify?

**Comment by saitogroup** [comment]
Or, some other fix, @ines, I looked in the other thread (1062) and didn't really understand what they were doing.

Operating System: Ubuntu 16.04.3 LTS
Python Version Used: 2.7.12
spaCy Version Used: 1.9.0

**Comment by ines** [comment]
@saitogroup Sorry for the late reply! If you want to try running spaCy with a different version of the `regex`package, you should be able to simply update it to a newer version in the same environment, e.g:

```bash
pip install regex==2017.06.23
```

We did update the `regex` requirements in v1.9.0 (see 5494605689758238e92703fa759a2f56cbb00598), so I'm surprised this issue is still coming up / it's still possible to end up with spaCy and an old version of `regex`. 

Could you run `pip freeze` in your spaCy environment and see which version it lists for `regex`?

**Comment by ines** [comment]
Hoping to finally fix this problem in the new version, v2.0. We're currently waiting to get it built for conda (it's just taking a bit longer because of Travis errors and the OSX backlogs 😓). 

Once the version is up, could you try again? [See here](https://spacy.io/usage/v2) for details on what's new in v2.0. If there are still problems with conda install and the new version, feel free to reopen.

**Comment by saitogroup** [comment]
@ines hello, so I installed regex 2017.06.23, and then tried to run my program and got this error:

```
Traceback (most recent call last):
  File "word_vec.py", line 5, in <module>
    import spacy
  File "/usr/local/lib/python2.7/dist-packages/spacy/__init__.py", line 10, in <module>
    from . import en, de, zh, es, it, hu, fr, pt, nl, sv, fi, bn, he, nb, ja
  File "/usr/local/lib/python2.7/dist-packages/spacy/en/__init__.py", line 4, in <module>
    from ..language import Language
  File "/usr/local/lib/python2.7/dist-packages/spacy/language.py", line 22, in <module>
    from . import language_data
  File "/usr/local/lib/python2.7/dist-packages/spacy/language_data/__init__.py", line 3, in <module>
    from .punctuation import *
  File "/usr/local/lib/python2.7/dist-packages/spacy/language_data/punctuation.py", line 5, in <module>
    re.DEFAULT_VERSION = re.VERSION1
AttributeError: 'module' object has no attribute 'VERSION1'

```
Anything I can do/should do? Any other information you need for a diagnosis? Really pumped to use spacy and want to make it work.

**Comment by ines** [comment]
@saitogroup Sorry for the late reply!

Can you verify that your environment is definitely using a recent version of `regex` and that `pip list` shows the correct version as well? The problem here seems to be that if any of your other packages and dependencies require an older `regex` version, and pip doesn't correctly resolve the version constraints specified by spaCy, you may end up overwriting the new version with an older one that doesn't support setting `DEFAULT_VERSION`.

The way spaCy is currently setting the regex version is unfortunately pretty bad, as it seems to modify the regex version globally (see #1623). We definitely want to replace this going forward, and probably get rid of the `regex` package alltogether, as it just keeps causing problems, and has also allowed us to end up with pretty bad regular expressions overall, which seem to slow down the tokenizer. Will open a separate issue about this as well.

**Comment by saitogroup** [comment]
from pip list, I get:

regex (2017.6.23)
spacy (1.9.0)

**Comment by saitogroup** [comment]
Duuuuuuuu !!! omg, there was a regex.py in the folder that I was trying to run my script from; eliminated it. 

Works now.
