### ISSUE TITLE
Tagger wrongly assigning _SP tag in Polish language models since SpaCy 3.4.0 (and greater versions)

### ISSUE THREAD

**Issue by Woodchucks** [explosion/spaCy#12002]
Tokens tagged wrongly with _SP are mostly nouns (but it also happenes with verbs and adjectives). 
As from our observation it is mostly **affecting last words in sentences** (or last words in compound sentences parts)<br /> **ending with punctuation marks or line breaks**.

Up to Spacy 3.2.2 we did not face this issue.

Code used for testing:
```
import spacy

nlp = spacy.load("pl_core_news_lg")

text_file = open('text/mały_książę.txt')
doc = nlp(text_file.read())
text_file.close()

for token in doc:
    if token.tag_ == '_SP':
        print(token.text, token.pos_, token.pos, token.tag_)
```
Example sentences of tokens wrongly tagged with _SP.
![image](https://user-images.githubusercontent.com/37177696/208662037-15010d5a-05d2-4724-9d41-3164d1e1fd65.png)

Full list of examples:
[wrong_SP_tags_examples.txt](https://github.com/explosion/spaCy/files/10268210/wrong_SP_tags_examples.txt)

## Your Environment
* Python Version Used: 3.10.6
* spaCy Version Used: 3.4.1

**Comment by adrianeboyd** [comment]
Copying the original comment over:

@Woodchucks: We also noticed this, and it appears to be a problem related to the whitespace augmentation in the training settings for a tagger that's trained on its own rather than with a shared `tok2vec`, where Polish is the only language in the provided trained pipelines with a completely independent `tagger` component.

To be honest the behavior is pretty bizarre and surprising. It doesn't show up (at least not enough to lead to much lower `TAG` scores) in evaluations of the dev data, which might be due to fewer unseen tokens in the dev data from the same corpus, and it's still possible there's an underlying bug. We haven't noticed this for other languages, so it seems like training a tagger with a shared `tok2vec` (with a morphologizer, lemmatizer, and/or parser) prevents the model from predicting that unseen tokens might be `_SP`, but in this case, the tagger on its own seems to lump whitespace tokens and unseen tokens into the same category.

The upcoming v3.5.0 trained pipelines for Polish should improve this by adding `IS_SPACE` as a feature so that the model has enough information to differentiate whitespace tokens from other tokens.

**Comment by Woodchucks** [comment]
@adrianeboyd, thank you again for the fast reply yesterday. I would have two additional questions:
Since you mentioned **v3.5.0** - is it considering implementing the following to the **Polish models**?
1) Not uppercasing tags at all
2) Returning detailed morphosyntactic tags, e.g.: subst:sg:nom:m1, praet:sg:f:imperf. for xpos?

**Comment by adrianeboyd** [comment]
A user provided the converted NKJP data to us with the tags in this format, maybe to make them look more similar to all the other trained pipelines in spacy? Lowercasing tags would be easy to do with a custom component if you need that for your pipeline.

I'm actually not sure whether detailed tags are available for the whole NKJP corpus? I took a look again at the 1-million-word subcorpus and my initial impression is that it looks like the detailed tags are available for the token type but aren't disambiguated in context, however I could just be confused about the annotation format/details.

The morphologizer (`token.morph` and `token.pos`) is trained on UD Polish PDB. How different are the `XPOS` tags in UD PDB vs. the `POS`+`MORPH` tags? The overall performance is lower because it's a smaller corpus and a much much larger tagset, but maybe this provides the annotation you're looking for?
