### ISSUE TITLE
No module named spacy /download Model

### ISSUE THREAD

**Issue by ArtaMoaser** [explosion/spaCy#1200]
Hi 
I have both of anaconda and python interpreter in my macOS and I try to download a model of spaCy's models in terminal with "python -m spacy download en_core_web_sm", I make a python VirtualEnv with Pycharm and try to download it, but I get this error "/Library/Anaconda/anaconda/bin/python: No module named spacy" 
I install spacy in python ( not in anaconda ) 
I want to download it in my VirtualEnv but I can't

**Comment by honnibal** [comment]
It seems that when you run `python`, you're getting Anaconda's Python --- this would be due to the way your PATH variable is structured. Honestly I think Anaconda isn't a very good citizen in this respect.

If you explicitly execute the python within your virtualenv, it will run the correct library.

This is a general Python thing, not really a spaCy issue, so I'm going to go ahead and close this. Thanks!
