### ISSUE TITLE
Tokenize on numeric/alphabet boundary

### ISSUE THREAD

**Issue by oxymor0n** [explosion/spaCy#1205]
Hi everyone,

So, I need to adjust SpaCy's tokenizer to split strings such as `'4years'` or `'10mg'` into two separate tokens, i.e. `['4', 'years']` and `['10', 'mg']`.

I think using a regex expression would have been easiest, but so far I have not seen such an option in the documentation. Am I missing something? Is there another way that this could be accomplished?

**Comment by honnibal** [comment]
You should be able to change the `prefix_re` function, so that when there's numbers at the start of the string, it splits them off as a token. https://spacy.io/docs/usage/customizing-tokenizer#native-tokenizers

Here's the part of the code where the Tokenizer is actually constructed: https://github.com/explosion/spaCy/blob/master/spacy/language.py#L58

You see how it references the `Language.Defaults.prefixes` attribute, defined here? https://github.com/explosion/spaCy/blob/master/spacy/language.py#L139

That's a list of strings, which are used to compile the regular expression. The function that does this is here: https://github.com/explosion/spaCy/blob/master/spacy/util.py#L58

If you write to `English.Defaults.prefixes` before calling `spacy.load()`, you'll change how the prefixes regular expression is constructed. This should let you control the tokenizer. You might decide to write to `suffixes` and/or `infixes`, depending on what's easiest for you.

**Comment by oxymor0n** [comment]
Thanks @honnibal, the comment was very helpful. Executing

    spacy.en.English.Defaults.prefixes += (r'\b\d+', )

did the trick.
