### ISSUE TITLE
Segfault when import spacy with profiling function on using Python 3.11

### ISSUE THREAD

**Issue by gaogaotiantian** [explosion/spaCy#12105]
## How to reproduce the behaviour

```python
import sys
def func(*args):
    frame = args[0]
    while frame:
        frame = frame.f_back

sys.setprofile(func)
import spacy
```

The segfault happens at ``<frame at 0x7f2c80f1fa30, file 'thinc/backends/numpy_ops.pyx', line 1, code __Pyx_PyMODINIT_FUNC PyInit_numpy_ops(void)>``.

I believe this is caused by some incompatiblities from the frame layout in 3.11 and Cython. Not sure if this is an issue for spaCy, thinc, Cython or possibly CPython. Feel free to report this to upstream if you have investigated in your code base and did not find anything wrong.

The original problem is found at https://github.com/gaogaotiantian/viztracer/issues/307

## Your Environment

* Operating System: Ubuntu 20.04
* Python Version Used: 3.11.1
* spaCy Version Used: 3.4.4
* Environment Information:

**Comment by shadeMe** [comment]
Thanks for example code! However, the error stems from neither spaCy nor Thinc as we're able to reproduce the crash with any Python package that uses Cython modules. 

Seeing how this issue is more pertinent to your profiler, it makes more sense if upstream CPython/Cython received a report directly from you.
