### ISSUE TITLE
TFR inconsistent and wrong break in doc.sents iterator.

### ISSUE THREAD

**Issue by ldmtwo** [explosion/spaCy#12123]
The issue here is that TFR breaks at odd places and inconsistently. When the text was short, it worked. I had a long paragraph that I expected it to parse into sentences. I have to use markers in the text to identify split points between XML tags. To do so, I used `<pad>` as a non-whitespace delimiter so I can reverse the transformation. For some reason (attention?), it will disconnect part of the tags and become `pad>`. The SM version seems to be working. White space doesn't matter, but those tags and other visible characters do. Ideally, I would like to just have a list of indices of where each sentence starts. I cannot fix the input and I've already done the work to create a reversible XML text extraction process.

## How to reproduce the behaviour
```
import spacy

## fails sometimes
# nlp = spacy.load("en_core_web_trf")
## works
# nlp = spacy.load("en_core_web_sm")

def get_sentences(text):
    doc = nlp(text)
    return [sent for sent in doc.sents if True]
line = '-'*100
## fails
text = 'Word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word.  The Arbitration Act 1996 will apply. [The person appointed will act as expert and not as arbitrator.] <pad>  [the [exclusive OR non exclusive] jurisdiction of the courts of England and Wales.] <pad>   '
## works
text = 'The Arbitration Act 1996 will apply. [The person appointed will act as expert and not as arbitrator.] <pad>  [the [exclusive OR non exclusive] jurisdiction of the courts of England and Wales.] <pad>   '
for out in get_sentences(text):
    print(f'{line}\n{out}\n')
```
Output 1:
```
----------------------------------------------------------------------------------------------------
Word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word.

----------------------------------------------------------------------------------------------------
 The Arbitration Act 1996 will apply.

----------------------------------------------------------------------------------------------------
[The person appointed will act as expert and not as arbitrator.]

----------------------------------------------------------------------------------------------------
<

----------------------------------------------------------------------------------------------------
pad>

----------------------------------------------------------------------------------------------------
 [the [exclusive OR non exclusive] jurisdiction of the courts of England and Wales.]

----------------------------------------------------------------------------------------------------
<

----------------------------------------------------------------------------------------------------
pad>

----------------------------------------------------------------------------------------------------
  
```
Output 2:
```
----------------------------------------------------------------------------------------------------
The Arbitration Act 1996 will apply.

----------------------------------------------------------------------------------------------------
[The person appointed will act as expert and not as arbitrator.] <pad>

----------------------------------------------------------------------------------------------------
 [the [exclusive OR non exclusive] jurisdiction of the courts of England and Wales.] <pad>

----------------------------------------------------------------------------------------------------
  

```

## Your Environment

* Operating System: Mac M1 2022
* Python Version Used: Python 3.9.12
* spaCy Version Used: just updated today
* Environment Information:

**Comment by Nickersoft** [comment]
Just updated to 3.5.0 and can confirm I'm seeing this same behavior – I had a test for these custom sentence breaks, and before, when giving an index of 7, it would break "I love my girlfriend" into ["I love", "my girlfriend."]. Now it breaks it into ["I love", "my", "girlfriend."].

**Comment by adrianeboyd** [comment]
A big part of the reason is that the provided trained pipelines aren't trained on texts that include XML tags like this, so you'll get fairly unpredictable results. In general it would be better to store this information is some other form than inserting special tokens in the text, especially if you want to use the provided English pipelines and not a custom model that is trained on texts containing these kinds of tokens.

Beyond that, there are a couple things going on:

* The default English tokenizer settings split `<pad>` into three tokens `< pad >`. If you want `<pad>` to be a single token, you can add it as a tokenizer exception ("special case"): https://spacy.io/usage/linguistic-features#special-cases. You can also modify prefixes and suffixes if you'd like to do something more general with `<` and `>`.
* If you know that the token `<pad>` is never the start of a sentence, you can add a custom component before the `parser` to preprocess your docs and mark `token.is_sent_start = False` for all these tokens.
* Don't use `<pad>` with `en_core_web_trf` because it is a special token for the internal transformer model `roberta-base` (and for lots of related models). The transformer tokenizer encoding is not able to distinguish special tokens from the same string in the input text, so I suspect this is the source of some of the unexpected results.

  You can see all the special tokens (I'm not sure how stable/consistent the `transformers` API is for all transformer model types, but this works for the current `transformers` + current `en_core_news_trf`):

  ```python
  print(nlp.get_pipe("transformer").model.tokenizer.special_tokens_map)
  ```

  ```python
  {'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'sep_token': '</s>', 'pad_token': '<pad>', 'cls_token': '<s>', 'mask_token': '<mask>'}
  ```

**Comment by adrianeboyd** [comment]
Let me move this to the discussions board...
