### ISSUE TITLE
de_core_news_lg lemmatization getting progressively worse

### ISSUE THREAD

**Issue by lsmith77** [explosion/spaCy#12152]
We recently updated from spaCy 3.2 to 3.4 and found several regression with lemmatization. We now updated to 3.5 and noticed that things got worse.

Essentially spaCy is lemmatizing to nonexistent or incorrect words. I have quite a long list if such issues but here are some examples:

* Lernpate => Lernpat
* Mutterkonzern => Mutterkonzer
* Alphaweibchen => Alphaweibch <= new issue in 3.5
* Eingeborene => eingeboren
* Hofmedien => Hofmedie
* verfechten => verfechen <= new issue in 3.5
* schwarzmalen => Schwarzmal
* folgendermaßen => Folgendermaße

Overall it also seems to attempt to lemmatize English words to German where it previously did nothing.

* resyncen => Resynce
* Allnighter => allnight
* Backender => Backend
* Bullet-point => bullet-poine

## How to reproduce the behaviour
```
import spacy

model = spacy.load("de_core_news_lg")

examples = [
    "Lernpate",
    "Mutterkonzern",
    "Alphaweibchen",
    "Eingeborene",
    "Hofmedien",
    "verfechten",
    "schwarzmalen",
    "folgendermaßen",
    "resyncen",
    "Allnighter",
    "Backender",
    "Bullet-point",
]

print("Text => Lemma\n")
for example in examples:
    print(example + " => " + model(example)[0].lemma_)
```

## Your Environment
* Operating System: OSX
* Python Version Used: 3.11
* spaCy Version Used: 3.5
* Environment Information:

**Comment by danieldk** [comment]
I am sorry to hear that you are experiencing regressions in the lemmatization accuracy! In principle there should be no substantial regressions from 3.3-3.5, since there were no significant changes to the lemmatizer or training data. There may be some changes between versions, because GPU training is not fully deterministic and we [augment](https://spacy.io/api/top-level#augmenters) the training data. Data augmentation also introduces randomness and can sometimes introduce erroneous edit trees.

Could you give some examples of sentences in which the given words were lemmatized incorrectly, so that we can investigate what causes the errors? I tried some sentences with _Lernpate_, _Mutterkonzern_, _Alphaweibchen_ and _verfechten_ and only _Lernpate_ was lemmatized incorrectly. Lemmatizing words in isolation as in the provided code example will result in a high error rate, since selecting the correct edit tree requires that the model can infer the correct part-of-speech, which is difficult in single-word documents.

In case that you want to revert to the lookup/rule-based lemmatizer of spaCy 3.2, that is also possible. The [rule-based lemmatizer](https://spacy.io/api/lemmatizer) is still included in spaCy.

**Comment by lsmith77** [comment]
> For many models, including the German model, we switched from a lookup-based lemmatizer to a machine learning-based lemmatizer in spaCy 3.3. In case that you want to revert to the lookup-based lemmatizer of spaCy 3.2, that is also possible since [it is still included in spaCy](https://spacy.io/api/lemmatizer).

Ah that makes sense.

I noticed the issues after running our QA tool which checks if `key` words in our rule based algorithm are properly chosen as lemmas that spaCy will use after detection. As such during this process I don't have an example sentence, and so I am not surprised that the ML based approach then gives bad results.

So the good news is that maybe there is no "real world" issue at all and all we need to do is re-think how we do QA of our rules.

We have in the past already fixed issues in spacy lemmatization with our own custom lookup, which had to refactor for spaCy 3.3+. So I am familiar with the link you shared but it is still not clear to me how I can choose the old lemmatizer.

**Comment by danieldk** [comment]
The following section of the documentation describes how you can swap out the lemmatizer under _Switch from trainable lemmatizer to default lemmatizer_:

https://spacy.io/models/#design-modify
