### ISSUE TITLE
incomplete tokenization of English contractions

### ISSUE THREAD

**Issue by kwhumphreys** [explosion/spaCy#1217]
`hadn't` is correctly tokenized as VBD + RB.
`hasn't` and `haven't` are not split and are incorrectly tagged as NNP.

Only `had` appears to be handled in the code: https://github.com/explosion/spaCy/blob/master/spacy/en/tokenizer_exceptions.py#L215

**Comment by honnibal** [comment]
Thanks, we'll update!

**Comment by christian-storm** [comment]
Sorry to pile on but here are some more to tack onto that list for English.  I also found lemmas that don't match.  It is all embodied in the attached script.  I hope this is helpful?!
[contractions.py.zip](https://github.com/explosion/spaCy/files/1229086/contractions.py.zip)


Contractions that aren't split into separate tokens:
'cause
hasn't
haven't
ma'am
o'clock
sha'n't
so've
to've
will've
would've
y'all'd
y'all'd've
y'all're
y'all've
doin'
goin'
nothin'
somethin'

Contractions that aren't expanded into the proper lemmas:
'cause because
hasn't have not
haven't have not
how 'd how do
how 'd 'y how do -PRON-
let 's let -PRON-
ma'am madam
o'clock of the clock
sha'n't shall not
so've so have
so 's so be
that 'd that would
there 'd there would
to've to have
when 's when be
where 'd where do
why 's why be
will've will have
would've would have
y' all -PRON- all
y'all'd -PRON- all would
y'all'd've -PRON- all would have
y'all're -PRON- all be
y'all've -PRON- all have
-PRON- will have -PRON- shall have
doin' do
goin' go
nothin' nothing
somethin' something

**Comment by ines** [comment]
The above error should be fixed in edc596d9a77cf0281b3641297fd5abd62a74edf2!

@christian-storm Thanks for the detailed analysis!  👍 Some of those are already added in v2.0 alpha ([see here](https://github.com/explosion/spaCy/blob/develop/spacy/lang/en/tokenizer_exceptions.py)) – if I remember correctly, we've also improved the way lemmatization is handled in the tokenizer exceptions to make sure none of the pre-defined lemmas are overwritten by the model. I'm not sure if this was fixed on the 1.x branch or only in 2.x – the problem was that the model would overwrite the lemma if no `TAG` was set in the exceptions.  (A good way to check this would be to run the tests with only `English()` or the tagger disabled as well, and see if the results are identical. I'll check this out.)

It'd be cool to include your test in the [English tokenizer tests](https://github.com/explosion/spaCy/tree/develop/spacy/tests/lang/en) on `develop`, so we can work through the examples systematically for v2. (Feel free to submit a PR if you have time – otherwise, I can port this over as well.)

Btw, shouldn't "ma'am" be one token, though? I think spaCy currently has it as `"ma'am": {ORTH: "ma'am", LEMMA: "madam", NORM: "madam"}`.
