### ISSUE TITLE
Unusual Behaviour: spaCy convert command taking a long time when converting .conll files to .spacy and .json files

### ISSUE THREAD

**Issue by ricardoguedes0** [explosion/spaCy#12170]
The spaCy converter command for spaCy v3.3.1 takes well over an hour to convert a .conll file with around 460,000 lines  equivalent to around 18,000 sentences.
The .conll file follows the  CoNLL 2003 NER format which starts with ```-DOCSTART- -X- O O```. 
A sample of this data for reference:
![image](https://user-images.githubusercontent.com/116196030/214333458-11f79aa4-f668-43dd-af14-6e5aa9de9d90.png)

Picture of the time it takes to convert the .conll file into .json which outputted the same message twice:
![image](https://user-images.githubusercontent.com/116196030/214357137-48b6e083-64ed-4ab8-ba37-8c86bbde87aa.png)

However, for reference, using spaCy v2.3.5 and the same document, the exact same converter command is capable of converting the same .conll file into .json in only 4.7 seconds.
![image](https://user-images.githubusercontent.com/116196030/214357992-267cd3cd-a9d6-4feb-beee-9fc0dd781fb8.png)

## How to reproduce the behaviour

The command line to obtain the .json file being used goes as: 
```python -m spacy convert "C:\\path_to\\train_data.conll" "C:\\path_to_output_dir\\" -c ner -t json``` 

while the .spacy file version is simply:
```python -m spacy convert "C:\\path_to\\train_data.conll" "C:\\path_to_output_dir\\" -c ner ```

## Your Environment

The first enviroment where it is taking a long time for the file to be generated:
* Operating System: Windows-10-10.0.19044-SP0
* Python Version Used: 3.8.16
* spaCy Version Used: 3.3.1

The second environment where the conversion is done in 4.7 seconds: 
* Operating System: Windows-10-10.0.19044-SP0
* Python Version Used: 3.8.16
* spaCy Version Used: 2.3.5

**Comment by ricardoguedes0** [comment]
## Issue Fixed

There seems to be a bug with spaCy when reading the conll files that have the ```-DOCSTART- -X- O O``` . Instead of that at the beginning of each file use ```-DOCSTART- -X- -X- O```. It worked on my end.

**Comment by adrianeboyd** [comment]
The converter currently only supports `-DOCSTART- -X- O O`, so watch out that it hasn't interpreted `-DOCSTART-` in other cases as a token and inserted it into your texts.

The v3 conversion is going through a `Doc` representation in the middle, which is why it will take longer than a v2 conversion, but it's definitely unusual that it's taking this long. I'm not sure whether it's the `Doc` creation itself or creating the JSON representation for either one huge `Doc` in the case where it hasn't added any document boundaries or if it's the overhead of converting tons of small docs.
