### ISSUE TITLE
Can I use the new Spacy and the old spacy together?

### ISSUE THREAD

**Issue by rikkuporta** [explosion/spaCy#1222]
Or do I have to deinstall the old spacy and lose access to it? I would love to test the neural network.

**Comment by ines** [comment]
No, spaCy 1.x is not compatible with spaCy 2.x. This includes the models, and the vocabulary IDs – spaCy 2.x uses [hash values instead of integer IDs](http://alpha.spacy.io/docs/usage/v2#features-hash-ids) to always ensure matching IDs, even across models.

If you want to use the v1.x and v2.0.0 alpha side by side, I'd recommend setting up a new virtual environment. This will install spaCy in a user directory (instead of doing a system installation and overwriting your current spaCy installation). For example:

```bash
python -m pip install -U venv
venv .env
source .env/bin/activate
pip install spacy-nightly
```

If you're on Python 2, you need to replace `venv` with `virtualenv`. If you're using Windows, you can activate your environment using `.env\Scripts\activate` instead of `source`.
