### ISSUE TITLE
If a dictionary contains double-byte hyphens(ー), it is not registered in the user dictionary.

### ISSUE THREAD

**Issue by Dormir30** [explosion/spaCy#12332]
## How to reproduce the behaviour
If I register a word in csv that contains a double-byte hyphen, the registration is not reflected and it is broken up. Words that do not contain double-byte hyphens are reflected correctly.
The procedure is as follows.

1. Input the word in the csv
2. Update the dic in sudachipy
!sudachipy ubuild -s '{site_package}/sudachidict_core/resources/system.dic' ./.sudachi/user_dic.csv -o ./.sudachi/user.dic
3. Change the path in sudachi.json ("userDict")
4. The json file is then changed to utf-8.

After this, it will not work, for example, if I run the following on the command line.

echo "ビューティーキラー" | sudachipy

If I do this, they will be separated by a double-byte hyphen.
After that, for some reason it works in other environments, but not in this one.

## My Environment
* Operating System:　Windows 10 Pro
* Python Version Used:Python 3.10.5
* spaCy Version Used: spacy 3.5.0
* Environment Information:Intel(E) core(TM) i7-7700 CPU

Other library info:
spacy-alignments                   0.9.0
spacy-legacy                       3.0.11
spacy-loggers                      1.0.4
spacy-transformers                 1.1.9
SudachiDict-core                   20221021
SudachiPy                          0.6.6
SudachiTra                         0.1.7

**Comment by polm** [comment]
It sounds like this is a configuration issue with SudachiPy rather than an issue with spaCy - have you tried asking at the [SudachiPy repo](https://github.com/WorksApplications/sudachi.rs)?

Also, to be clear, it looks like the character you're using is [U+30FC](https://www.fileformat.info/info/unicode/char/30fc/index.htm), which is the normal long vowel mark, and not a "double byte hyphen". It's also hard to understand what the issue is since you don't include expected or actual output. For example, with the default SudachiPy core dict I get this output, which is unsurprising:

```
ビューティー    名詞,普通名詞,一般,*,*,*        ビューティー
キラー  名詞,普通名詞,一般,*,*,*        キラー
EOS
```

**Comment by Dormir30** [comment]
The same result, as you say, can be obtained as follows
ビューティー    名詞,普通名詞,一般,*,*,*        ビューティー

キラー  名詞,普通名詞,一般,*,*,*        キラー

However, even after registering it in the dictionary, it is still split as above.
But I want to register it in the dictionary and not split it up. Like this
ビューティー キラー   名詞,固有名詞,一般,*,*,*        ビューティーキラー
Should I ask this to spaCy?

**Comment by polm** [comment]
If you're seeing the same result after registering it in the dictionary, it sounds like the issue is that the cost you used in the dictionary is higher than the cost for existing words. In any case, that's a SudachiPy issue, and not a spaCy one, and you should ask at their repo.

Whether you want to handle this tokenization in spaCy or in SudachiPy depends on why you want to do this. It might be easier to use an [EntityRuler](https://spacy.io/usage/rule-based-matching#entityruler) and merge tokens.

**Comment by Dormir30** [comment]
Thank you very much. I was able to run it successfully, but from the command line it was garbled (?). and I can't get any results.
The following are the results of the execution.

echo ビューティーキラー | java -jar sudachi-0.6.3.jar -s '{"systemDict":" C:/Users/XXXXX/Desktop/code /system_core.dic","userDict":["C:/Users/XXXXX/Desktop/code/user.dic"]}' -d
=== Input dump:
echo ?r???[?e?b?[?l???[ | java -jar sudachi-0.6.3.jar -s '{"systemdict":" c:/users/a969402/desktop/code /system_core.dic","userdict":["c:/users/a969402/desktop/code/user.dic"]}' -d
=== Lattice dump:

**Comment by polm** [comment]
I think you meant to respond to this issue? 

https://github.com/WorksApplications/sudachi.rs/issues/229

**Comment by Dormir30** [comment]
Yes, I do. I will talk to them over there.
