### ISSUE TITLE
Issue\Query on lemmatization

### ISSUE THREAD

**Issue by dipanjanS** [explosion/spaCy#1236]
Hi guys, I'm the author of [Text Analytics with Python](http://www.springer.com/us/book/9781484223871) where I had mentioned about `spaCy`. Currently working on my next book where I will be including some sections about using the same, especially in text pre-processing\normalization.

While working on some code I came across the following scenario in lemmatization.

The word of interest here is **need** and with `spaCy` I'm getting the lemma as **ne** and I'm not sure if that is correct and why I'm getting that?

Part of text under analysis: "this is something you need to see, but it's a pass for anyone else."

```
In [204]:  for word in tn.nlp(test_reviews[doc_index]):
                 print(word.text, word.lemma_, word.tag_)

this this DT
is be VBZ
something something NN
you -PRON- PRP
need ne VBP
to to TO
see see VB
.....
```

Following are some comparisons of the word of interest in `nltk` and `spaCy`.

```
# nltk
In [205]:  from nltk import WordNetLemmatizer
           wnl = WordNetLemmatizer()
           wnl.lemmatize('need', 'v')

Out [205]:  'need'

# spaCy
In [206]:  r = tn.nlp('need')
           for item in r:
               print(item.text, item.lemma_, item.tag_)

need ne VBP
```

Would be great if you folks could let me know in case i'm doing something wrong or how do I keep the word unchanged as **need** even after lemmatization?

Following are details for my environment
## My Environment

* **Python version:** 3.5.2
* **Installed models:** en
* **spaCy version:** 1.9.0
* **Platform:** Windows-10-10.0.15063-SP0

**Comment by dipanjanS** [comment]
@ines @honnibal @syllog1sm: Your feedback and any inputs on this would be appreciated!

**Comment by GruffPrys** [comment]
I've noticed this as well on both v.2 and v1.82:

```
>>> doc = nlp("need")
>>> doc[0].pos_
'VERB'
>>>doc[0].lemma_
'ne'
```

I assume it's caused by the implementation of the rules for lemmatizing regular verbs ending with the past tense suffix -ed, namely `["ed", ""]` . 

```
VERB_RULES = [
    ["s", ""],
    ["ies", "y"],
    ["es", "e"],
    ["es", ""],
    ["ed", "e"],
    ["ed", ""],
    ["ing", "e"],
    ["ing", ""]
]

```
(from https://github.com/explosion/spaCy/blob/v2.0.0-alpha/spacy/lang/en/lemmatizer/_lemma_rules.py)

What's strange is that this problem doesn't arise with other similar words such as _weed_, _seed_ and _feed_. Not only are these similar in form, they can also represent nouns or verbs, as is the case with _need_.

So why don't _weed_, _seed_ and _feed_ lemmatize to _we_, _se_ and _fe_ respectively?

One difference is that the model identifies _need_ as a VERB and _weed_, _seed_, and _feed_ as NOUNS in isolation:

```
>>> doc = nlp("need")
>>> doc[0].pos_
'VERB'
>>> doc = nlp("seed")
>>> doc[0].pos_
'NOUN'
>>> doc = nlp("feed")
>>> doc[0].pos_
'NOUN'
```

As a result the lemma rules for verbs above might be being applied to _need_ and not _seed_ and _feed_.

However, if that's so I can't explain why _need_ is lemmatized correctly here:

```
>>> doc = nlp("I will need the car")
>>> doc[2].pos_
'VERB'
>>> doc[2].lemma_
'need'
```

**Comment by dipanjanS** [comment]
@GruffPrys: True, even I couldn't understand why it didn't arise with the other words you mentioned and your last example definitely seems strange and interesting  where it is correctly lemmatized even after it's detected as a  verb. Might need to look into this more when I get some time.

**Comment by dipanjanS** [comment]
@ines @honnibal  @syllog1sm : Any update on this? Just wanted to know if there is anyway of bypassing or resolving this.

**Comment by honnibal** [comment]
Hi @dipanjanS , sorry I missed this issue!

This bug should be resolved now in v2. I wish I'd seen this issue sooner, as obviously this has affected a lot of words.

**Comment by dipanjanS** [comment]
Excellent, thank you so much! @honnibal
