### ISSUE TITLE
Model suggestions for Danish (Norwegian and Swedish) Transformer

### ISSUE THREAD

**Issue by KennethEnevoldsen** [explosion/spaCy#12376]
I simply wanted to suggest an update to use the `vesteinn/DanskBERT` instead of `Maltehb/danish-bert-botxo` as it performs notably better (63.87 ± 1.26 vs 50.76 ± 1.75) on the [ScandEval benchmark](https://scandeval.github.io/nlu-benchmark/) created by @saattrupdan. my general experience with the benchmark is that it captures the downstream ranking of the models well (for the models with spaCy for DaCy it corresponds 1-1). The plan it also to update DaCy using the same model (if you prefer I can let you know when I have updated the models).

Similar suggestion exist for the Swedish model (`KB/bert-base-swedish-cased` vs no existing model) and the Norwegian model (`NbAiLab/nb-bert-base` vs no existing models), but I am unsure if you wish to support transformer models for these languages (I would def. appreciate it though).

I think both the Norwegian and Swedish models are continually updated.

**Comment by adrianeboyd** [comment]
Thanks for the note!

It looks like the license for `vesteinn/DanskBERT` isn't compatible with the other resources in `da_core_news_trf`, but we could possibly consider switching the default recommendation for Danish for the training config quickstart. The licenses of some of the transformer models aren't really clear so we're not being 100% consistent here, but given this license information I'm not sure it makes sense for us to provide it as a default recommendation.

We already recommend `KB/bert-base-swedish-cased` for Swedish and `NbAiLab/nb-bert-base` for Norwegian. Recently I've only been adding `trf` models for new languages if we can provide `core` models with NER (vs. `dep`-only), but that requires training resources with dependency+NER annotation and those are relatively rare. But if you think a `dep_*_trf` model would be useful for Swedish or Norwegian for a particular reason, I'm willing to be convinced otherwise?

**Comment by KennethEnevoldsen** [comment]
Ahh right, then the `NbAiLab/nb-roberta-base-scandinavian` might be a more reasonable model (its license is CC-BY-4.0) for Danish. Performance is approximately similar to DanskBERT but with a larger Vocab.

Ahh I see that makes sense (given the comments in #12307) it would predominantly be for dep. parsing. Then I probably agree that I wouldn't add it at the moment.

**Comment by adrianeboyd** [comment]
> Ahh right, then the `NbAiLab/nb-roberta-base-scandinavian` might be a more reasonable model (its license is CC-BY-4.0) for Danish. Performance is approximately similar to DanskBERT but with a larger Vocab.

That model says "This is just a Test Model. Do NOT use for anything!"?

**Comment by KennethEnevoldsen** [comment]
Ah right should have noted that! I think Per Kummervold is currently developing the model. I will send him a e-mail asking about it.

Alternatively the `microsoft/mdeberta-v3-base` (MIT License) performs on par as well.

**Comment by vesteinn** [comment]
> Thanks for the note!
> 
> It looks like the license for `vesteinn/DanskBERT` isn't compatible with the other resources in `da_core_news_trf`, but we could possibly consider switching the default recommendation for Danish for the training config quickstart. The licenses of some of the transformer models aren't really clear so we're not being 100% consistent here, but given this license information I'm not sure it makes sense for us to provide it as a default recommendation.
> 
> We already recommend `KB/bert-base-swedish-cased` for Swedish and `NbAiLab/nb-bert-base` for Norwegian. Recently I've only been adding `trf` models for new languages if we can provide `core` models with NER (vs. `dep`-only), but that requires training resources with dependency+NER annotation and those are relatively rare. But if you think a `dep_*_trf` model would be useful for Swedish or Norwegian for a particular reason, I'm willing to be convinced otherwise?

FYI, the license has been modified to MIT.

**Comment by KennethEnevoldsen** [comment]
Wonderful to hear @vesteinn! I have been getting some impressive results with it so far. Next version of DaCy will def. include it given the updated license

**Comment by adrianeboyd** [comment]
Thanks, we'll try it out for the next round of model training.

**Comment by adrianeboyd** [comment]
We switched the Danish transformer model in v3.6: https://github.com/explosion/spaCy/releases/tag/v3.6.0

Thanks for the suggestions!
