### ISSUE TITLE
Korean blank model crashes if mecab-ko not installed, but not during initialization

### ISSUE THREAD

**Issue by stephantul** [explosion/spaCy#12449]
Initializing a Korean spacy.blank model throws an error when `natto-py` is not installed, and asks the user to install both `natto-py` and `mecab-ko`. However, if only `natto-py` (and not `mecab-ko`) is installed, the initialization no longer throws an error. Instead, the model throws the following error on trying to process a document. It doesn't matter if this document actually contains korean orthography.

```
MeCabError: libmecab.dylib could not be found, please use MECAB_PATH
```

I think that maybe the initialization should still throw an error, or this `MeCabError` should be coerced into something more specific to spaCy (e.g., `please install mecab-ko` etc. etc.)

## How to reproduce the behaviour

Only install `natto-py`, but not `mecab-ko`, then run the following:

```python
import spacy

model = spacy.blank("ko")  # no error
model("꿀벌")  # error
model("dog walks home")  # same error
```

## Your Environment

- **spaCy version:** 3.5.1
- **Platform:** macOS-12.5-arm64-arm-64bit
- **Python version:** 3.9.15

**Comment by adrianeboyd** [comment]
It's intentional that there is no error message on initialization with `spacy.blank("ko")` (see #10295, in particular https://github.com/explosion/spaCy/pull/10295#discussion_r808852488). This isn't great from a UX perspective for the example above, but it made it easier to work with non-mecab-ko alternatives as in the `ko_core_news_*` pipelines.

If `natto-py` is installed and mecab is missing, then this error doesn't seem extremely confusing to me, but you're right that it doesn't explain that you need `mecab-ko` specifically for Korean. (As far as I know there's no way to have both the Japanese and Korean mecab installations run in parallel for spacy, as in older v2 versions of spacy that used mecab wrappers for both Japanese and Korean.)

The external `mecab-ko` installation causes a lot of headaches and we're planning to switch to other alternatives in spacy v4 (#12328, #12416).

Depending on your task, you can also potentially use the rule-based tokenizer as in `ko_core_news_*` and avoid mecab entirely: https://spacy.io/usage/models#korean

**Comment by stephantul** [comment]
Hi! Thanks for the quick reply and clarification!
