### ISSUE TITLE
RuntimeError: Array bounds exceeded while searching for root word. This likely means the parse tree is in an invalid state.

### ISSUE THREAD

**Issue by leighhopcroft** [explosion/spaCy#1253]
I'm trying to merge any multi-token entities found in a text in to a single token with the following code adapted from https://explosion.ai/blog/sense2vec-with-spacy

My code within a function that processes a generator of texts:

```
for doc in nlp.pipe(texts, batch_size=batch_size, n_threads=n_threads):
    # Iterate over named entities
        for ent in doc.ents:
            if len(ent) > 1:
                # Merge them into single tokens
                ent.merge(ent.root.tag_, ent.text, ent.label_)
```

I get the following error on one entity when trying to perform the merge:

```
File "spacy/tokens/span.pyx", line 307, in spacy.tokens.span.Span.root.__get__ (spacy/tokens/span.cpp:7562)
  File "spacy/tokens/span.pyx", line 415, in spacy.tokens.span._count_words_to_root (spacy/tokens/span.cpp:10330)
RuntimeError: Array bounds exceeded while searching for root word. This likely means the parse tree is in an invalid state. Please report this issue here: http://github.com/explosion/spaCy/issues
```

The particular entity in question is `"£32 million"` and the error seems to occur when trying to access the `ent.root.tag_` attribute.

I'm using a Python 3.6.2 Conda environment:
`'3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]'`

## Info about spaCy

* **spaCy version:** 1.9.0
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.2
* **Installed models:** en

**Comment by carolingfish** [comment]
I've encountered a similar error.
I'm using en_core_web_sm and it seems that running its parser on (some type of tokenized text that has been tagged) more than once, corrupts the state of the parse tree, causing exception in _count_words_to_root.

Repro Step:
import en_core_web_sm
SPACY_EN_CORE_WEB_SM = en_core_web_sm.load()

tokenized_text = SPACY_EN_CORE_WEB_SM.tokenizer(text)

def ss(tt):
...   for i in range(len(tt)-1):
...     for j in range(i+1, len(tt)):
...       tt[i:j].root

t_t = SPACY_EN_CORE_WEB_SM.tokenizer("Highly rated - I'll definitely")
SPACY_EN_CORE_WEB_SM.tagger(t_t)
SPACY_EN_CORE_WEB_SM.parser(t_t)
SPACY_EN_CORE_WEB_SM.parser(t_t)
ss(t_t)

  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in ss
  File "spacy/tokens/span.pyx", line 307, in spacy.tokens.span.Span.root.__get__ (spacy/tokens/span.cpp:7562)
  File "spacy/tokens/span.pyx", line 415, in spacy.tokens.span._count_words_to_root (spacy/tokens/span.cpp:10330)
RuntimeError: Array bounds exceeded while searching for root word. This likely means the parse tree is in an invalid state. Please report this issue here: http://github.com/explosion/spaCy/issues

**Comment by honnibal** [comment]
@carolingfish Thanks for the clues! That makes things a fair bit easier.

@leighhopcroft Until the error is fixed, you might be able to work around this by gathering the entities first, and then merging them together. I think the problem at the moment is that the document is changing tokenization after the `doc.ents` property produces the spans. This usually works, but it seems the call to `span.root` is throwing it off. If you get a list of the entities and their tags in one step, and then merge them in the next step, it might work around the bug.
