### ISSUE TITLE
lemma_ returns empty string

### ISSUE THREAD

**Issue by alvercau** [explosion/spaCy#1259]
This is what I did:
nlp = en_core_web_sm.load()
tokens = nlp.tokenizer(text)
for token in tokens:
    print(token.lemma_)

And it returns empty strings only. The model is installed and can be found (by the way, if you use python from anaconda, you have to cd into the anaconda folder to download it, otherwise python cannot find it. It would be better if it went to the right place immediately, like all other python packages), because it works perfectly well if I do it like this:

nlp = en_core_web_sm.load()
tokens = nlp(text)
for token in tokens:
    print(token.lemma_)

What am I doing wrong?
Furthermore, there are some problems with the stemmer. For instance 'left' (as in left vs. right) is stemmed as 'leave'. Maybe it would be an idea to look at the context for stemming? Or at POS?

Environment
* **spaCy version:** 1.7.3
* **Platform:** Linux-4.4.0-1030-aws-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.1
* **Installed models:** en

**Comment by ines** [comment]
```python
tokens = nlp.tokenizer(text)
```

When you run the line above, you're telling spaCy explicitly to *only* run the tokenizer and not load the model. This is why the lemma is not assigned. spaCy currently uses the model's predictions, i.e. POS tags, for lemmatization. However, when you load the model into the `nlp` object and use it to process the text, it loads the model and assigns the lemma:

```python
nlp = en_core_web_sm.load()
tokens = nlp(text)
```

So in short, you haven't been doing anything wrong – you just need to make sure the model is loaded if you want to access the `lemma_`. 🙂

> Furthermore, there are some problems with the stemmer. For instance 'left' (as in left vs. right) is stemmed as 'leave'. Maybe it would be an idea to look at the context for stemming? Or at POS?

This is how spaCy currently handles stemming / lemmatization. But of course this also means that if the POS tags happen to be incorrect, the lemmatization might be off as well. Since the model is statistical, there's always some error potential here.

> The model is installed and can be found (by the way, if you use python from anaconda, you have to cd into the anaconda folder to download it, otherwise python cannot find it.

Could you explain this in more detail or show an example? Under the hood, spaCy uses pip to download and install the model package when you run `python -m spacy download en`. This should install the model into your current environment. In spaCy v2 ([currently in alpha](https://alpha.spacy.io)), the models will be much smaller (~15MB for the default English model!), so we're thinking about also distributing them as packages on pip and conda. This should hopefully make the integration even easier, because it'd let you do `conda install spacy_en_core_web_sm` (or something similar).

**Comment by naoko** [comment]
I'm getting empty lemma as well and please see the usage below:
```
$ pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_md-1.2.1/en_core_web_md-1.2.1.tar.gz
$ pip freeze | grep spacy
spacy==1.7.5
```
```
>>> import spacy
>>> en_nlp = spacy.load('en_en_core_web_md')
>>> doc = en_nlp("Billing Question")
>>> doc
Billing Question
>>> [t.lemma_ for t in doc]
['', '']
```

**Comment by ines** [comment]
Sorry for the late reply – I hope I understand your question correctly, but when you run this:

```
pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_md-1.2.1/en_core_web_md-1.2.1.tar.gz
``` 

... pip will simply install that package and won't perform any linking or compatibility checks. All that logic lives in the `spacy download` command. It will check which version is available for your spaCy installation, install it using `pip` and link it to the model shortcut.

When you only run `pip install`, the model is still installed and can be imported as a package via `import` – but spaCy will have no way of knowing that this is the model you want to have available as `'en'`. So you'll either have to run `spacy link` to create that shortcut link, or use `spacy download` to take care of this.
