### ISSUE TITLE
no model ound for 'en'   Only loading the 'en' tokenizer

### ISSUE THREAD

**Issue by wmaharani** [explosion/spaCy#1269]
I have installed spacy 1.9.0.
But why I can't load spacy 'en'??

--------------------------------
>>> import spacy
>>> nlp=spacy.load('en')

[93m    Warning: no model found for 'en' [0m

    Only loading the 'en' tokenizer.

>>> spacy.load('en')

[93m    Warning: no model found for 'en' [0m

    Only loading the 'en' tokenizer.

<spacy.en.English object at 0x0000000007B2AEF0>

--------------------------------------------------------

I have download the model "en_core_web_sm".
>>> import en_core_web_sm
>>> nlp=en_core_web_sm.load()

And I have linked the "en_core_web_sm" and "en" : 
C:\Users\Warih>python -m spacy link en_core_web_sm en --force
You do not have sufficient privilege to perform this operation.

←[93m    Linking successful←[0m

    C:/Python27/lib/site-packages/en_core_web_sm/en_core_web_sm-1.2.0 -->
    C:/Python27/lib/site-packages/spacy/data/en

    You can now load the model via spacy.load('en').

----------------------------------

Why I can't still load spacy('en') ?

## Your Environment

* Operating System: Windows 8.1
* Python Version Used: 2.7.13
* spaCy Version Used: 1.9.0
* Environment Information: 

C:\Users\Warih>python -m spacy info

    ←[93mInfo about spaCy←[0m

    Python version     2.7.13
    Platform           Windows-8.1-6.3.9600
    spaCy version      1.9.0
    Installed models
    Location           C:\Python27\lib\site-packages\spacy

**Comment by ines** [comment]
I think the problem lies here:

```
You do not have sufficient privilege to perform this operation.
```

spaCy creates "shortcut links" for models by creating a symlink of that name in the `spacy/data` directory. To do this, you need permissions to write to that folder. If you've installed spaCy in a system directory (which seems to be the case from looking at the path), this is usually not the case.

So you'll either have to re-run the `spacy link` command as admin, or install spaCy in a virtual environment instead (which will create a user directory). For more info on [this section](https://spacy.io/docs/usage/troubleshooting#symlink-privilege) in the troubleshooting guide.

(I agree that the success message is misleading, though – no idea why it happened here and didn't throw an error. Will have a look at this.)

**Comment by ines** [comment]
Merging this with #1283, as it seems to be related to the same issue!
