### ISSUE TITLE
Nondeterministic bug calling spaCy when typing-extensions==4.6.3

### ISSUE THREAD

**Issue by richardpaulhudson** [explosion/spaCy#12698]
## How to reproduce the behaviour
Unfortunately the behaviour is not consistently reproducible, but see e.g. these Github Actions runs, in each of which the problem has occurred at a different point within a different combination of OS, python version and spaCy version:

https://github.com/richardpaulhudson/coreferee/actions/runs/5177746525/jobs/9328240759
https://github.com/richardpaulhudson/coreferee/actions/runs/5177799134/jobs/9328364850
https://github.com/richardpaulhudson/coreferee/actions/runs/5178156770/jobs/9329239645 

Based on this [bug report]( https://stackoverflow.com/questions/76313568/typeerror-issubclass-arg-1-must-be-a-class-when-importing-langchain-in-flask) I pegged `typing-extensions==4.5.0` which has solved the problem.

Perhaps it would make sense to declare the peg for spaCy itself?

**Comment by adrianeboyd** [comment]
We added `typing_extensions<4.6.0` to spacy v3.2.6 and v3.3.3 because it isn't easy to make them compatible with newer `pydantic` for those versions.

For spacy v3.4 and v3.5, a new install with the most recent `pydantic` should work with the current v3.4.x and v3.5.x patch releases. If you have an old venv, you might need upgrade `pydantic`, although that shouldn't be what's going on the CI.

I'd recommend a requirement like `spacy~=3.3.3` (so also including newer patch releases) instead of `spacy==3.3.0` if possible? We can't retroactively modify the pypi releases at all, so there's no way to make `spacy==3.3.0` work out of the box in a new venv unless you add additional requirements like `typing_extensions<4.6.0` to your requirements. (This is frustrating, I wish there were a better solution.)

There are some more details in this issue: #12659

**Comment by richardpaulhudson** [comment]
OK, thanks, that makes sense!
