### ISSUE TITLE
Importing spacy makes the Python built-in "print()" method not working

### ISSUE THREAD

**Issue by CYUlysses** [explosion/spaCy#1280]
OS: Windows 10
Python Flavor: Python 3.6.1, Anaconda 64-bit
Console: Ipython 5.3.0, running inside Spyder IDE

Codes to replicate the error:

(Open a new console)
print('foo string')
foo string

import spacy
print('foo string')

(nothing happens)

**Comment by CYUlysses** [comment]
Strange, this error does not occur on another of my PC's that had a generally same build. Looking into more details for helping reproducing the errors.

**Comment by ines** [comment]
Thanks – this looks very strange indeed. Does this only happen with spaCy? It seems unlikely that it's caused by spaCy specifically/directly, since spaCy shouldn't mess with `stdout` at all. (And the only place where spaCy hooks into IPython is in v2.0 when outputting displaCy visualisations [here](https://github.com/explosion/spaCy/blob/develop/spacy/displacy/__init__.py#L11), via [this function](https://github.com/explosion/spaCy/blob/develop/spacy/util.py#L202).)

Maybe there's some Ipython weirdness going on here? Either way, even if it's not spaCy-related, I'm definitely curious to find out what caused it.

**Comment by CYUlysses** [comment]
I was able to reproduce the error again, but this error only occurs in Spyder's IPython console installed with Anaconda3; I reinstalled using Anaconda2 while using an environment with python3, and such error disappeared.

The previous installation also prints error messages when IPython is opened alone, so it is probably something complicated with Anaconda/Spyder, hence I'm closing the issue in this repo.

Probably gonna bring the issue there.

**Comment by CYUlysses** [comment]
One more comment: among the various packages I use (numpy, scipy, pandas, BeautifulSoup4, nltk, etc., etc.), the error only occurred after "import spacy", but did not happen with any other packages (even nltk). 
Hope this is some helpful information; looking forward to spaCy 2.0 beta.

**Comment by ines** [comment]
Interesting – thanks for updating! Will keep this in mind in case this comes up again.

Which spaCy version were you using btw?

**Comment by CYUlysses** [comment]
Sorry for the late response. I was using spaCy 1.9.0, installed from conda-forge with the label np112py36_vc14_1
