### ISSUE TITLE
en model not loading

### ISSUE THREAD

**Issue by ankitarath2011** [explosion/spaCy#1283]
## Your Environment

`
## Info about spaCy

* **Python version:** 2.7.13
* **Platform:** Windows-10-10.0.14393
* **spaCy version:** 1.9.0
* **Installed models:**`

While loading "en" I am getting following error.

.
```
import spacy
spacy.load("en")

 Warning: no model found for 'en'

    Only loading the 'en' tokenizer
```.
Have already followed these steps

python -m spacy download en

python -m spacy download en_core_web_md
python -m spacy link en_core_web_md en 

still not working. Please help

**Comment by ines** [comment]
Did the download and link commands work okay, or did you get an error? And does importing the model work for you?

```python
import en_core_web_sm
nlp = en_core_web_sm.load()
```

If the above code works, this usually means that the model installed correctly, but the linking to `'en'` failed – possibly because you've installed spaCy in a system directory and don't have admin permissions. So try re-running the `link` command as admin ([see here](https://spacy.io/docs/usage/troubleshooting#symlink-privilege) for more info).

If you don't care about the `'en'` shortcut, you can also just keep using the `import` syntax. Some users actually prefer loading models this way because it's cleaner and more transparent.

**Comment by ankitarath2011** [comment]
The above code is working fine. I am running cmd as admin and executing the link command. It is giving following output.

```
C:\windows\system32>python -m spacy link en_core_web_md en
You do not have sufficient privilege to perform this operation.

    Linking successful

    C:/Python27/lib/site-packages/en_core_web_md/en_core_web_md-1.2.1 -->
    C:/Python27/lib/site-packages/spacy/data/en

    You can now load the model via spacy.load('en').
```

**Comment by ines** [comment]
Ah, so maybe there's actually a bug that causes spaCy to display a success message, even if the linking fails – somehow, this error doesn't seem to be caught properly (this already came up in #1269). See this message: 

```
You do not have sufficient privilege to perform this operation.
```

Did a quick search for the error and found this thread on the topic: https://superuser.com/questions/129299/got-not-sufficient-privileges-message-in-cmd-when-logged-on-as-administrator

Do any of the suggestions here work for you? Looks like there are some weirdnesses around admin / symlink privileges on Windows. If it still doesn't work on your setup, I'd recommend just using the `import` syntax instead. 

---

### Some background on `spacy link` vs. `import`

I've been meaning to write this down anyways (in case you're interested and for everyone else who comes across this issue) Going forward, we're actually thinking about encouraging the `import` syntax more, or even making it the default, recommended way of loading models. Originally, the symlinks were introduced to allow users to only download a model once and then link it across environments (since the models are quite large and up to 1GB). It also allowed us to keep backwards compatibility on `spacy.load('en')`, even as more English models became available.

In [spaCy v2.0](https://alpha.spacy.io/docs/usage/v2), most models will be much smaller (~15MB for the default English model). So except for the word vectors (which will still be around 500MB), re-downloading models won't be such a big issue anymore. It'd then also be possible for us to upload the models to PyPi and conda, so users can do something like `pip install spacy_en_core_web_sm`.

Using the `import` syntax has the following advantages:

* Easier debugging and better, native error messages. If `import`ing a model fails because it's not installed, Python will tell you. Your code will also fail immediately, instead of somewhere down the line when you call `spacy.load`. This also makes testing and CI workflows more convenient (especially relevant for production users).
* More transparency. It's clear which model packages are being used, and you always know exactly which model you're loading. Otherwise, you might end up with the wrong model linked as `en` and not notice until much later when you get unexpected results.
* Better collaboration and dependency management. You don't have to rely on all of your team members having the same models linked to the same shortcuts. Instead, all you have to do is add the model packages to the `requirements.txt` and `setup.py`.

Advantages of `spacy link` and `spacy.load()`:

* Shorter and easier to read.
* Loading models programmatically from a string. For example, if your models are `['en', 'de']`, you can pass the string names into `spacy.load()` them when you need them, without having to export them first, or use `importlib` workarounds.
* Custom names for models.

**Comment by ankitarath2011** [comment]
Added user name in "Create symbolic links" in "Local Security Policy". and then downloaded again using "python -m spacy download en" . Now it is working fine. Thanks.

**Comment by gabefair** [comment]
Is anyone else still having this issue? If so, could we have formal documentation for this fix?
