### ISSUE TITLE
Bug: Spacy spannish model tokenize in the middle of a word

### ISSUE THREAD

**Issue by siulkilulki** [explosion/spaCy#1300]
Here is my pipeline:

```
>>> import es_core_web_md as spacy_es_model
>>> nlp = spacy_es_model.load()
>>> nlp(u'vamos pal mundial')[1]
pa
>>> nlp(u'vamos pal mundial')[2]
l
>>> nlp(u'vamos pal mundial')[3]
mundial
```
As you can see Spacy spannish model tokenize in the middle of a word! 

## Your Environment

* **spaCy version:** 1.9.0
* **Platform:** Linux-4.4.0-93-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.1
* **Installed models:** es_core_web_md

**Comment by honnibal** [comment]
Seems bad. Thanks for the report.

**Comment by ines** [comment]
Sorry for only getting to this now: the tokenization of the example above happens because there is an exception pattern defined for "pal". See here on `master` (v1.x) and `develop` (v2.0):

https://github.com/explosion/spaCy/blob/841e2225a326e527b008a2a4d6ac8f62961c70ba/spacy/es/tokenizer_exceptions.py#L8-L12

https://github.com/explosion/spaCy/blob/86d6bd75032a5882180585dcd5c222dcc6c3366a/spacy/lang/es/tokenizer_exceptions.py#L9-L11

Just like "can't" &rarr; `["ca", "n't"]` in English, the tokenization exceptions define tokens like contractions that should be split. The original form of the word is usually assigned as the `NORM`, which you can access via the `norm_` attribute:

```bash
>>> doc = nlp(u'vamos pal mundial')
>>> [(t.text, t.norm_) for t in doc]
[('vamos', 'vamos'), ('pa', 'pa'), ('l', 'el'), ('mundial', 'mundial')]
```

However, it may be that this particular exception rule is actually incorrect or problematic. If you think that this is the case, feel free to submit a PR or open another issue on this topic so we can discuss – and hopefully get some feedback from other Spanish users on how this should be handled 🙂
