### ISSUE TITLE
Should tokens without vector be used to calculate the document vector?

### ISSUE THREAD

**Issue by znat** [explosion/spaCy#1328]
https://github.com/explosion/spaCy/blob/33313c01ad79caa18184429780c0611de6796caf/spacy/tokens/doc.pyx#L275

Would something like that make sense?
```
t_with_vecs = filter(lambda t: t.has_vector, self) 
self._vector = sum(t.vector for t in t_with_vecs) / len(t_with_vecs) 
```

**Comment by honnibal** [comment]
This is really a good question; I've been thinking about this a lot.

It's pretty difficult to handle OOV tokens in a satisfying way with only word vectors. The problem is, if you're making a similarity calculation, two documents having the same OOV word is a really great feature. The current average-of-vectors algorithm loses this feature completely, which is a big problem.
