### ISSUE TITLE
Segmentation Fault while training NER

### ISSUE THREAD

**Issue by socialglass** [explosion/spaCy#1335]
I am using the NER trainer to train for a new entity type and have about ~10k training documents. The code I use is the same as given in the spacy examples -

```
    for raw_text, _ in train_data:
        doc = nlp.make_doc(raw_text)
        for word in doc:
            _ = nlp.vocab[word.orth]
    random.seed(0)
    nlp.entity.model.learn_rate = 0.001
    for itn in range(1000):
        random.shuffle(train_data)
        loss = 0.
        for raw_text, entity_offsets in train_data:
            doc = nlp.make_doc(raw_text)
            gold = GoldParse(doc, entities=entity_offsets)
            nlp.tagger(doc)
            loss += nlp.entity.update(doc, gold, drop=0.9)
```
I am getting Segementation fault while doing nlp.entity.update() and not for a specific text. Every run, the segfault is for a different training document.

How to check what is exactly causing this? Are there any rules about having punctuations (comma, dot, apostrophe etc.)  in the entity name in training documents ?

## Your Environment
* Operating System: RHEL 6 64-bit
* Python Version Used: 2.7.2
* spaCy Version Used:  1.9
* Environment Information: ~11GB free RAM, ~40GB free disk space
* Model: en_core_web_md

**Comment by todayokay** [comment]
@socialglass  I don't think this problem is about comma,dot or anything specific with the text. Seg, fault is caused by malloc %99 of the time. Can you post the exact error message possibly?

**Comment by honnibal** [comment]
Please see here --- the training is much improved in v2, and we've tried to give a lot more guidance about how to make good use of it: https://spacy.io/usage/training

**Comment by peustr** [comment]
I would just like to mention that I am experiencing the same error - I am getting a Segmentation Fault when I am training a new NER model starting from a blank language model.

The weird thing is that it happens kind of randomly; when I execute the same python script many times, sometimes I get it, sometimes not. I am following the exact tutorial from https://spacy.io/usage/training , except I use my own dataset rather than the animal example.

I am using spacy 2.0.9 and my code is pretty much the same as the tutorial. The only difference is that my training snippets are large paragraphs, and not sentences, and the "entities" dictionary contains multiple annotations, e.g.

```
(
"Large snippet here, about 3000-5000 characters on average",
{
    "entities": [
        (offset1, offset2, "something"),
        ...
        about 100 of these
    ]
}
)
```
