### ISSUE TITLE
Check that filter_spans input is a Span 

### ISSUE THREAD

**Issue by Nelson-Gon** [explosion/spaCy#13354]
I was trying to remove duplicate entities for exploratory purposes and realized there is no dedicated way to do that and also that simply using a `set` does not solve the problem.

Since, `util.filter_spans` works for `Spans`, I fed it `doc.ents` (which are Spans indeed) and it runs with no errors, but returns the exact same object unchanged. I think it might be worthwhile to add assertions for the expected type (in this case a tuple). Currently, even giving the function a list will work with no warning/error. 

## How to reproduce the behaviour
1. Create a doc with duplicate entities 
2. Run `filter_spans(doc.ents)`. 

Interestingly, this will work with an ordinary list, only throwing an `AttributeError` at the `Span` processing stage

## Your Environment
- **spaCy version:** 3.7.4
- **Platform:** macOS-14.3.1-arm64-arm-64bit
- **Python version:** 3.10.13
- **Pipelines:** en_core_web_sm (3.7.1), en_core_web_md (3.7.1)

**Comment by svlandeg** [comment]
Hi!

I'm not sure I fully understand your issue or request, so let me try to recap.

> Since, util.filter_spans works for Spans, I fed it doc.ents (which are Spans indeed) and it runs with no errors but returns the exact same object unchanged. 

Right - that is in fact the expected behaviour. Entities stored on `doc.ents` can not be overlapping (by design), so `util.filter_spans` won't remove any `Span` objects from that list.

Usually, this function is used in the reverse direction: when creating `Span` objects manually that could be overlapping, then calling `filter_spans` before setting the set of resulting objects as `doc.ents`.

> I think it might be worthwhile to add assertions for the expected type (in this case a tuple). Currently, even giving the function a list will work with no warning/error.

As [documented](https://spacy.io/api/top-level#util.filter_spans), the type that `util.filter_spans` expects is `Iterable[Span]` so it should work fine for either a tuple or list of `Span` objects.

Can you provide an example code snippet that doesn't work for you, that exhibits behaviour that is unexpected?

**Comment by Nelson-Gon** [comment]
Hi, thanks. I think I will close this one as I perhaps misinterpreted what `filter_spans` is meant to do
