### ISSUE TITLE
Tokenizer creates strange tokens

### ISSUE THREAD

**Issue by blester125** [explosion/spaCy#1370]
The tokenizer produces some very strange tokens. This example shows it pretty well.

```python
import spacy
nlp = spacy.load('en')
string = ' This has     spaces  '
doc = nlp(string)
for token in doc:
    print("'{}'".format(token.text), end="|")
```

`' '|'This'|'has'|'    '|'spaces'|' '|`

Note the tokens that are only spaces. This seems like very strange behavior. I understand it from the point of view of being about to recreate the original string however I feel like tokenization like this introduces noise when used for the actual NLP tasks.

This seems like a performance Issue. 

Removing these space tokens completely (adding a `if not in_ws:` before the span, and cache stuff in the `tokenizer.pyx`) is pretty easy but if they are needed then I would think two different ways to iterate on a doc (one without these tokens for nlp and one with for string recreation) would be nice.

## Your Environment

* **spaCy version:** 1.9.0
* **Platform:** Linux-4.10.0-35-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.2
* **Installed models:**

**Comment by honnibal** [comment]
This is expected behaviour: spaCy preserves all characters of the input in the `Doc` object. The original string is actually not stored anywhere. When you call `doc.text`, what you're getting is `[(w.text + w.whitespace_) for w in doc]`

I often trim whitespace as a preprocess on the raw string, using a simple regex. If you know you don't want these characters, I would recommend that.

Earlier versions of the library trained the models with some data augmentation, that added and removed whitespace, capitalisation and punctuation from the training data. This made the models a bit more robust to this type of noise. I stopped using the data augmentation because I didn't have a good way to evaluate it, but some recent reports have made me think it might have been helping. I plan to experiment with this a bit more for spaCy 2.
