### ISSUE TITLE
Windows: Model linking not working on Python 2

### ISSUE THREAD

**Issue by farizrahman4u** [explosion/spaCy#1378]
Downloaded `en` model using:

```bash
python -m spacy download en
```

Model was downloaded successfully, with message `You can now load the model via spacy.load('en').`

But `nlp = spacy.load('en')` is unable to find the model:

```bash
Warning: no model found for 'en'

Only loading the 'en' tokenizer.
```

I had to manually copy model files from `C:/Python27/lib/site-packages/en_core_web_sm/en_core_web_sm-1.2.0` to `C:/Python27/lib/site-packages/spacy/data/en`

* Operating System: Windows 10
* Python Version Used: 2.7
* spaCy Version Used: 1.9.0

P.S Linking works on python 3.5.

**Comment by ines** [comment]
Thanks for the report – so if I understand this correctly, linking worked on Python 3.5, but not on Python 2.7 on Windows?

And when you scroll up from the first success message, was there any warning or error along the lines of "symbolic link privilege not held" or something similar, e.g. related to permissions? spaCy needs permission to create symlinks in system directories, so if you didn't run the command as admin, it might have failed creating the symlink ([see here for details](https://spacy.io/docs/usage/troubleshooting#symlink-privilege)). Although, spaCy should technically complain if that happens...

Btw, instead of using the shortcut links and `spacy.load()`, you can always import a model package directly and call its `load()` method:

```python
import en_core_web_sm
nlp = en_core_web_sm.load()
```

This will always work if the package is installed – and some users actually prefer this over the `spacy.load()` workflow, since it's cleaner and more "native", and often easier to debug.

**Comment by farizrahman4u** [comment]
My bad, it works when run as admin. A warning should be shown nevertheless.
