### ISSUE TITLE
Parsing performance worse in spaCy 2?

### ISSUE THREAD

**Issue by ashaffer** [explosion/spaCy#1426]
I'm on OS X, and i'm seeing about 4x worse parsing performance in spaCy 2 than spaCy 1. Is there something that would be causing this? I'm disabling tagging, entity recognition, and tensorization, so i'm fairly certain it's the parser. And i've run it against the same documents and consistently see substantially worse performance in spaCy 2. I've tried with the default pip install of spacy-nightly as well as building from source.

EDIT: I should add two things:

1. I'm using the `.pipe` api to batch process documents.
2. The performance seems to degrade when I make the pipe larger. For instance, processing 200 documents at once, I get about 100ms/document (was 20ms in spacy 1). But if I process 1000 documents, I get about 300ms / document.

**Comment by honnibal** [comment]
By performance you mean speed right?

Unfortunately that's a thing right now, especially on CPU. It's a bit better if run through `.pipe()` -- the single-document case is especially slow right now.

The model architecture is now fairly stable, so we can start putting more work into optimising it. But it's likely that there will still be an efficiency gap between v1 and v2 for the release candidate.

One of the things that's held up the efficiency improvements is that it's been hard to call into linear algebra routines from Cython across platforms. Without C-level calls into the linear algebra routines, there's a fair bit of overhead on doc-by-doc processing, and it's also hard to make use of multiple cores efficiently. I've nearly solved this problem now, by developing this: https://github.com/explosion/cython-blis

If you want to help out, one of the next steps is to get `cython-blis` compiling on Windows. There seem to be a few small C dialect differences that need to be tweaked to get it compiling under MSVC. Once that's done, I can switch the CNN to the C-level implementation I have here: https://github.com/explosion/thinc/blob/feature/fast-mwe/thinc/neural/_fast_maxout_cnn.pyx . This implementation is about 3x faster on my machine than the current CNN. We should see even better improvements in parser efficiency.

**Comment by ashaffer** [comment]
Yes, I do mean speed, sorry for the confusion. Also see my edit for some more details. But cython-blis looks good, i'll take a look at it later tonight.

So a 3-5x performance degradation is to be expected? What about the decrease in performance associated with a larger pipeline?

**Comment by honnibal** [comment]
No problem -- "performance" is interestingly ambiguous for us; but yeah of course speed is the usual meaning.

Thanks for the tip about the pipe size. This means I'm setting the max batch too high. One of the processing steps takes a list of arrays for a batch, and flattens them so that we can work on them as a single tensor. It makes sense that this is only good up to a point. How long are your documents?

> So a 3-5x performance degradation is to be expected? 

At the moment yes. I'm not particularly happy about it --- some of my earlier benchmarks were in error, so I actually didn't realise the CPU performance was so much behind. I'm looking forward to writing out the model in pure Cython.

Still, I don't know whether we'll end up beating the linear model. I think you might actually be underestimating the performance of v1: on OSX it's hard to get OpenMP to work. Without openmp the v1 model is single-threaded; with openmp you should see a linear improvement in speed, up to around 4 threads per core.

My best advice at the moment would be to try setting maximum threads to only 2 or 3, and using joblib to multi-process. spaCy 2 at least loads very quickly, and with a low batch size the `en_core_web_sm` model should be very memory efficient.

**Comment by ashaffer** [comment]
My documents have an average length of ~3000 characters. And ya, I was setting the batch size super high, because threading wasn't working for me in v1. I was only using the parser, so I think threading doesn't work at all for that, I discovered. But in v2 decreasing the batch size and increasing the thread count did help, thanks.

For anyone else looking at this, the optimal batch size for me is 25 with 4 threads on a 4 core cpu. That gets me down to about 50ms/doc.

**Comment by honnibal** [comment]
I just realised that there's a pretty simple explanation here.

The parser will be blocking until it finishes a whole batch. If we have a batch of 128 documents of mean length 20, and one document of length 100, we're going to spend a long time parsing with effectively batch size 1.

If the batch size is very large, the `parser.pipe()` method could rebatch by length before forwarding the work to the `predict_batch()` method. Once the batches are complete, it could yield the documents in order.

Alternatively I can fix the rest of the `predict_batch()` method so that I can release the global interpreter lock around the whole method. This will allow OpenMP to manage the parallelism, as it's doing in 1.x.

**Comment by ines** [comment]
The above fix is now included in `v2.0.0a18`! 🎉

**Comment by ashaffer** [comment]
Nice! Thanks!
