### ISSUE TITLE
source code for Implementation of nlp.begin_training(lambda: []) ?  for how exactly model is getting trained

### ISSUE THREAD

**Issue by prashant334** [explosion/spaCy#1482]
@ines @honnibal 

* **Python version:** 2.7.6
* **Platform:** Linux-3.16.0-77-generic-x86_64-with-Ubuntu-14.04-trusty
* **spaCy version:** 2.0.0a17
* **Models:** en, en_core_web_sm, xx_ent_wiki_sm

From where I can get source code for  Implementation of "nlp.begin_training(lambda: [])" . Because I want to know how exactly model is getting trained ?
  I am looking for implementation of **nlp.begin_training(lambda: [])** and ****minibatch(get_gold_parses(nlp.make_doc, train_data), size=3):
            docs, golds = zip(*batch)****                                                       and
 **nlp.update(docs, golds, losses=losses, sgd=optimizer,
                       drop=0.35)**
Please help me out. for this?
Thanks

**Comment by ines** [comment]
Hi! Since your `nlp` object is an instance of `Language`, spaCy first calls `Language.begin_training`:
https://github.com/explosion/spaCy/blob/7986ada1cbd24ec715400f512c88da0da8f6b3da/spacy/language.py#L431

`Language.begin_training` then delegates to the individual pipeline components:
https://github.com/explosion/spaCy/blob/7986ada1cbd24ec715400f512c88da0da8f6b3da/spacy/language.py#L456-L460

All pipeline components inherit from the `Pipe` class. For each individual pipeline component you're training, it calls the component's `begin_training` method:

https://github.com/explosion/spaCy/blob/7986ada1cbd24ec715400f512c88da0da8f6b3da/spacy/pipeline.pyx#L142-L147

If you're training the parser tagger or NER, this calls into the parser's `Model`. The model itself is implemented in [Thinc](https://github.com/explosion/thinc), spaCy's machine learning library.

https://github.com/explosion/spaCy/blob/7986ada1cbd24ec715400f512c88da0da8f6b3da/spacy/syntax/nn_parser.pyx#L226-L231

The `minibatch` function is a helper of the `Gold` class that allows you to efficiently iterate over batches of items. This is especially useful if you're working with large volumes of training data.
https://github.com/explosion/spaCy/blob/7986ada1cbd24ec715400f512c88da0da8f6b3da/spacy/gold.pyx#L147-L161

I hope this helps – I might add this explanation to the docs as well, as it'll probably be useful information for others as well. We've also updated the [code examples for training](https://github.com/explosion/spaCy/tree/develop/examples/training) btw – note that they're currently only compatible with the version on `develop` (which should be out as `v2.0.0a18` today).

**Comment by prashant334** [comment]
okay @ines  . But I have still some doubts that are remaining to clarify... what exactly pipeline is doing.?

**Comment by ines** [comment]
To answer your question from #1489:
> I AM NOT GETTING WHAT IS THE CONTENT OF LAMBDA? @ines

`get_gold_tuples` is a function you can pass to `begin_training`, which lets you generate training and evaluation examples programmatically. This is useful if you're streaming in training data from a generator. Previous versions required the argument to be set – which is why old examples define it as `lambda: []`, i.e. a lambda function that returns an empty list. In the upcoming version, `v2.0.0a18`, this is not necessary anymore, and you can leave the argument out and just iterate over your examples.

---

If you're new to spaCy, I highly recommend checking out the spaC 101 guide: https://alpha.spacy.io/usage/spacy-101 It explains all the important concepts of the library in simple terms with illustrations.

The spaCy issue tracker on GitHub is mostly for bug reports, feature request and more advanced usage questions. We're not always able to answer every usage question, but we're always working on improving the [documentation](https://alpha.spacy.io).

For basic usage questions, StackOverflow is usually a better choice – if you tag your post with `spacy` and `python`, more people will see them and be able to help.
http://stackoverflow.com/questions/tagged/spacy

**Comment by prashant334** [comment]
@ines 
Does Conditional Random Field is used for **nlp.update(docs, golds, losses=losses, sgd=optimizer,
drop=0.35)** .?
