### ISSUE TITLE
Loaded Model does not rememebr

### ISSUE THREAD

**Issue by KMohaghegh** [explosion/spaCy#1485]
I trained my model with more than 2000 sentences in spaCy 1.9, like this:
gold = GoldParse(doc1, entities=[u'O', u'O', u'O',u'U-MVE', u'U-MVE', u'U-MVE',...])
(for large doc1 file with almost 2500 sentences)
where just add one entity called "nlp.entity.add_label('MVE')" to the model. I check the entities afterwards with:

```
nlp.entity.update(doc1, gold)
nlp.entity(doc1)
for ent in doc1.ents:
    print(ent.text, ent.label_)
```

and all were captured.
Then save it with "nlp.save_to_directory('/Users/Desktop/Spacy/en_new_BNP')"
and follow the documentation and build the package with in python called en_model
then load it with: "nlpnew = en_model.load()" but when I checked it looks the load model do not remember any of "MVE" entities which I already trained for. Please give me some suggestion where might be a problem. Bellow is the code for load:

```
import en_model
nlpnew = en_model.load()
textnew= nlpnew(u"I am a safe student. I am living in Stockholm which has strong economic growth.")
doc = nlpnew(unicode(textnew))
print doc
nlpnew.entity(doc)
for ent in doc.ents:
    print(ent.text,  ent.label_)
```

As you can see "safe" and "strong economic growth" are among the training for MVEs and when I check before saving they were captured but the out put of the above code is only:

I am a safe student. I am living in Stockholm which has strong economic growth.
(u'Stockholm', u'GPE')
I expect the (u'safe', 'MVE') and also ('strong economic growth','MVE') also be captured by the load model. I also check with the exact sentences I trained the model, they also can not captured 'MVE' after the load. I do not know is this a SAVE problem or something else. I hope some one help me or give me some tips.

## Info about spaCy

* **Python version:** 2.7.13
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **spaCy version:** 1.9.0
* **Installed models:** en

**Comment by honnibal** [comment]
I'm really not sure why that wouldn't be working -- it sounds like you did the same thing that the `spacy train` command does to save the model, which is how the pre-trained models are produced.

There have been lots of problems with training, saving and loading in 1.x, which are all fixed in v2. We've just pushed a new version that you can install with `pip install spacy-nightly`. The docs for v2 are up at https://alpha.spacy.io

We expect to promote a18 to "release candidate 1" on Monday --- so, it's really not a bad time to start using v2 :).

**Comment by honnibal** [comment]
Please see here :) https://spacy.io/usage/training
