### ISSUE TITLE
💫 Rethink Doc.merge and Span.merge, add Token.split

### ISSUE THREAD

**Issue by honnibal** [explosion/spaCy#1487]
See also: #1474, #975, #758, #653, #616, #450, #429, #329, #375, #314, #214, #213, #156

Currently `Doc.merge()` and `Span.merge()` promise too much. They let you merge a span while holding references to other spans, and the span indices are supposed to be magically recalculated.

Unsurprisingly this has proven super difficult to get right. It also makes the `Doc.merge()` inefficient for repeated calls, because every time we merge something, we have to set the doc into the correct state.

We'd also really like to have a `token.split()` function, that divides tokens. This is a big hole at the moment, that really lets us down for languages like Chinese where the tokenization is an important part of the annotation to be changed through the pipeline.

I think we should consider having a `Doc.retokenize()` context manager, which you would need to activate before calling `span.merge()` or `token.split()`. This should allow us to make the retokenization more reliable and efficient. Within the block, we could keep a reference to all new `Span` and `Token` objects. Only `Span` and `Token` objects created during retokenization should be used during retokenization.

These changes are being left out of v2, because the v2 policy is to avoid breaking changes to the `Doc`, `Span` and `Token` objects (this makes it more predictable which parts of the application need to be updated).

**Comment by chaturv3di** [comment]
Does this affect v1.9.0 too?

**Comment by ines** [comment]
@chaturv3di No, this will be more like spaCy v3.0, as it will introduce breaking changes to the `Doc`, `Span` and `Token`. As @honnibal mentioned above, we've been trying to avoid introducing breaking changes to spaCy's container objects in v2.0, since the new version already affects so many other parts of the library.

The above changes also require some experimentation and we haven't really decided on the perfect solution yet. That's why we've put it up for discussion on the issue tracker 😊

**Comment by BigstickCarpet** [comment]
@ines - why was this issue closed?  Are there still plans to implement a `token.split()` method?  Currently it still [throws a NotImplementedError](https://github.com/explosion/spaCy/blob/b59e3b157f593f5f74981bf9d39deba7bc9a12a4/spacy/tokens/_retokenize.pyx#L55)  ☹

What's the best way to split tokens currently?
