### ISSUE TITLE
Custom tokenizer with infix_finditer is not working correctly.

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#1494]
## Your Environment
* Operating System: 16.04
* Python Version Used: 3.5.2 
* spaCy Version Used: develop

Ok, I am brute-forcing the tokenizer :) pardon @ines in advance haha.
Maybe I have found a bug with custom infix pattern. The code:

```
import spacy
import re
from spacy.tokenizer import Tokenizer

infix_re = re.compile(r'''[^a-z]''')

def my_tokenizer(nlp):
    return Tokenizer(nlp.vocab,
                     {},
                     infix_finditer=infix_re.finditer
    )

nlp = spacy.load('en')
nlp.tokenizer = my_tokenizer(nlp)

doc = nlp("This is a ...test")

for token in doc:
    print(token.text)
```
The output is:

```
This
is
a
.
.
.test

```

As you can see it holds the last DOT with the word "test". 
It occurs when there are three consecutive characters outside the [^a-z]. So, for example:

`doc = nlp("This is a 123test")` returns:

```
This
is
a
1
2
3test

```
`doc = nlp("This is a .-/test")` returns:

```
This
is
a
.
-
/test

```
and so on...
In this case the 3 is not a perfect number :d

The following are working correctly:

`doc = nlp("This is a 12test")`
```
This
is
a
1
2
test

```
`doc = nlp("This is a -/test")`

```
This
is
a
-
/
test

```

Hope this helps.

**Comment by fsonntag** [comment]
According to the [documentation](https://spacy.io/usage/linguistic-features#how-tokenizer-works), this behaviour is correct.
Check this part:
```
            elif find_infixes(substring):
                infixes = find_infixes(substring)
                offset = 0
                for match in infixes:
                    tokens.append(substring[offset : match.start()])
                    tokens.append(substring[match.start() : match.end()])
                    offset = match.end()
                substring = substring[offset:]
```

In the case of `"A 123test"`, it finds `"2"` and `"3"` as infixes, with a `match(start=3, end=4)` and `match(start=4, end=5)`. The tokenizer starts to split at the first match and appends `"1"` (`tokens.append(substring[offset : match.start()])`) and `"2"` (`tokens.append(substring[match.start() : match.end()]`) to `tokens`.
`offset` is set to to 4 and in the next iteration `match.start()` is also 4, so `tokens.append(substring[offset : match.start()])` has no effect anymore.

I'm currently having the same issue. I want to tokenize `foo(+)-bar` to
```
foo
(
+
)
-
bar
```

I really don't see how this is possible with the current implementation of tokenizer. Maybe modifying the tokenizer so that `offset` is set to `match.end() - 1`

**Comment by honnibal** [comment]
Pull request merged! Thanks again @fsonntag
