### ISSUE TITLE
en_core_web_sm is missing word vectors in alpha:

### ISSUE THREAD

**Issue by r-wheeler** [explosion/spaCy#1498]
en_core_web_sm is missing word vectors:

```
import spacy
from spacy.matcher import PhraseMatcher
en_core_web_sm = spacy.load('en_core_web_sm')
en_core_web_lg = spacy.load('en_core_web_lg')
from spacy.tokens import Doc, Span, Token

spacy.__version__

en_core_web_sm.vocab['dog'].has_vector

:False 

en_core_web_lg.vocab['dog'].has_vector

:True
```

## Your Environment
 spaCy version      2.0.0a17
    Location           /Users/ryan.wheeler/anaconda3/envs/spacy2/lib/python3.6/site-packages/spacy
    Platform           Darwin-16.6.0-x86_64-i386-64bit
    Python version     3.6.2
    Models             en_core_web_lg, en_core_web_sm

**Comment by honnibal** [comment]
The `en_core_web_sm` model doesn't come with a word vectors table. However, every *token* is assigned a vector, using the convolutional neural networks inside the tagger, parser and entity recognizer. The lexical similarities aren't as good as the large GloVe vector model, but you at least do get coverage for all words -- and even words that don't really exist, based on context:

    >>> doc = nlp(u'the vorpal blade')
    >>> doc2 = nlp(u'the sharp knife')
    >>> doc[1].similarity(doc2[1])
    0.65478814
    >>> doc[2].similarity(doc2[2])
    0.71718866
    >>> doc[1].similarity(doc[2])
    0.34635314

The problem is that if we add at least some word vectors, we can't really "back off" to these contextual vectors, because there's no consistent relationship between them. So we can only base the similarity model on one or the other. For the small model, we don't want to ship many word vectors (by definition), so it seems better to not have any at all, and just use the derived context vectors.

There will also be an `md` model, which has a relatively small number of vectors (between 10k and 20k), and other tokens mapped to their nearest vector. So you'll still get a vector result for over 1 million word types, by synonym. This seems to be a good compromise in our experiments.

**Comment by r-wheeler** [comment]
Makes sense, I see on the docs that it is explicit in specifying embeddings trained from the internal model vs glove. Thanks!
