### ISSUE TITLE
textcat example is not working with 2.0.0a19   

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#1500]
## Your Environment
```
    spaCy version      2.0.0a19       
    Platform           Linux-4.4.0-98-generic-x86_64-with-Ubuntu-16.04-xenial
    Location           /home/damiano/lavoro/python/nlp/spacy
    Python version     3.5.2          
    Models             en, it
```

Hello,
this example: https://github.com/explosion/spaCy/blob/v2.0.0a18/examples/training/train_textcat.py
give me this output:

```
Created blank 'en' model
Loading IMDB data...
Using 2000 training examples
Training the model...
LOSS 	  P  	  R  	  F  
Traceback (most recent call last):
  File "/home/damiano/lavoro/python/parser/train_ner.py", line 135, in <module>
    plac.call(main)
  File "/home/damiano/lavoro/python/base/lib/python3.5/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/damiano/lavoro/python/base/lib/python3.5/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/damiano/lavoro/python/parser/train_ner.py", line 73, in main
    scores = evaluate(nlp.tokenizer, textcat, dev_texts, dev_cats)
  File "/home/damiano/lavoro/python/parser/train_ner.py", line 115, in evaluate
    for i, doc in enumerate(textcat.pipe(docs)):
  File "pipeline.pyx", line 778, in pipe
  File "pipeline.pyx", line 790, in spacy.pipeline.TextCategorizer.set_annotations
  File "doc.pyx", line 843, in spacy.tokens.doc.Doc.extend_tensor
ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function
```
We should update it for this new release.

**Comment by honnibal** [comment]
The `en_core_web_sm` model doesn't come with a word vectors table. However, every *token* is assigned a vector, using the convolutional neural networks inside the tagger, parser and entity recognizer. The lexical similarities aren't as good as the large GloVe vector model, but you at least do get coverage for all words -- and even words that don't really exist, based on context:

    >>> doc = nlp(u'the vorpal blade')
    >>> doc2 = nlp(u'the sharp knife')
    >>> doc[1].similarity(doc2[1])
    0.65478814
    >>> doc[2].similarity(doc2[2])
    0.71718866
    >>> doc[1].similarity(doc[2])
    0.34635314

The problem is that if we add at least some word vectors, we can't really "back off" to these contextual vectors, because there's no consistent relationship between them. So we can only base the similarity model on one or the other. For the small model, we don't want to ship many word vectors (by definition), so it seems better to not have any at all, and just use the derived context vectors.

There will also be an `md` model, which has a relatively small number of vectors (between 10k and 20k), and other tokens mapped to their nearest vector. So you'll still get a vector result for over 1 million word types, by synonym. This seems to be a good compromise in our experiments.

**Comment by honnibal** [comment]
Thanks, fixed!
