### ISSUE TITLE
Doc typo

### ISSUE THREAD

**Issue by evanmiltenburg** [explosion/spaCy#1507]
The documentation [here](https://spacy.io/usage/training) says `nlp.update([doc], [gold], drop=0.5, sgd=optimizer)`. I guess it should be: `nlp.update([doc], [gold], drop=0.5, optimizer=sgd)`

**Comment by honnibal** [comment]
No that's correct --- does it conflict with a previous statement?

I'm not that enthused about the `sgd` keyword argument, but that currently matches Thinc, and at least it's short.

**Comment by evanmiltenburg** [comment]
It seemingly contradicts with the table directly below it. Or the table is confusing.

**Comment by ines** [comment]
Okay yeah, I had a look at that table again and I'm not sure why we did it this way... I guess the `optimizer` was supposed to describe the *variable* `optimizer` declared in the example above.  But it definitely makes a lot more sense to  the table explain the *arguments* of `nlp.update` instead of all kinds of random functions, variables and arguments that happen to occur in the example. Will fix this, thanks!  👍

**Comment by evanmiltenburg** [comment]
Thanks for the quick response! Reading the page again I should have read the code a bit more carefully. It says `optimizer = nlp.begin_training(get_data)` right there on the first line...

**Comment by ines** [comment]
Ideally, docs should even make sense if you're just skimming them 😉   This one was definitely confusing. I mean, for what it's worth, you can call your optimizer `unicorn` and that's totally fine, as long as you pass it to the `sgd` keyword argument.

Just pushed an update to the site btw!
