### ISSUE TITLE
Resizing word vectors

### ISSUE THREAD

**Issue by danielhers** [explosion/spaCy#1514]
There used to be a function `vocab.resize_vectors` for resizing each vector to a given size (#544).
This function is removed in v2. Is there a way to resize the word vectors (as in the number of columns, not rows, in the embedding matrix)?

**Comment by honnibal** [comment]
`nlp.vocab.vectors.resize()`

The vectors table works quite differently, because word vectors are now stored in a contiguous table (as they should be! In v1 each vector was attached to the `Lexeme` object.). Because it works differently, there might not be a one-to-one mapping for everything you want to do. In particular, you need to resize the word vectors table to the correct number of rows before inserting new keys. The `vocab.set_vector()` method does this for you, but direct calls to `vectors.add()` doesn't.

The word vectors code is a bit younger than most of the other v2 features. Feedback and bug reports appreciated :). API docs can be found here: https://spacy.io/api/vectors

**Comment by danielhers** [comment]
Thanks - I thought `resize` is just for adding/removing rows. How do I use it to add/remove columns? `resize` seems to be missing from https://spacy.io/api/vectors...

**Comment by ines** [comment]
Sorry about that – it's now added to the docs and backwards incompatibilities.
See here: https://spacy.io/api/vectors#resize (you might need to do a hard refresh, depending on the caching)

**Comment by danielhers** [comment]
Thanks!
