### ISSUE TITLE
nlp.vocab.get_vector returns empty vector

### ISSUE THREAD

**Issue by suryasumukh** [explosion/spaCy#1520]
nlp.vocab.get_vector returns empty vector. Vector are loaded when pipeline is run
```python
nlp = spacy.load('en')
doc = nlp(u'This is a sentence')

doc[-1] # sentence
doc[-1.vector.shape # (384, )

'sentence' in nlp.vocab # True
nlp.vocab.get_vector('sentence') # array([], dtype=float32)
```

## Environment
▶ python -m spacy info --markdown
* **OS:** macOS High Sierra
* **spaCy version:** 2.0.2
* **Platform:** Darwin-17.2.0-x86_64-i386-64bit
* **Python version:** 3.6.3
* **Models:** en

**Comment by danielhers** [comment]
I think the [default `en`](https://spacy.io/models/en#en_core_web_sm) doesn't have word vectors, but [`en_core_web_md`](https://spacy.io/models/en#en_core_web_md) does.

**Comment by ines** [comment]
Yes, that's correct. Sorry that this is a little confusing – we've spent a lot of time thinking about how to best solve this, and still haven't come up with the perfect solution.

The thing is, the `sm` models don't contain *actual word vectors* – but to make them more useful, they take advantage of the shared context-sensitive token vectors used by the tagger, parser and NER. This means that you can still use the `similarity()` methods, even without word vectors. That's pretty cool – but it also makes the story around this more complicated. 

(If we took the `similarity` away, the story and explanation would be simpler, but that's obviously bad. Similarly, if we "translate" the token vectors and make them available in the vocab, this would be confusing, too, because it'd make it seem like the model comes with word vectors – which it doesn't. If you have any suggestions on how we could solve this or get it across better, let us know!)

**Comment by suryasumukh** [comment]
Ah, i see. Thanks!

**Comment by ThorstenHen** [comment]
Hi, I know I come late to this conversation, but I am wondering what: "**shared context-sensitive token vectors used by the tagger, parser and NER**" are. Is there any description on how they are calculated and what makes them different to word embeddings?
