### ISSUE TITLE
Segmentation fault after Span.as_doc

### ISSUE THREAD

**Issue by manvithn** [explosion/spaCy#1537]
When I run the following code, I get a segmentation fault:
```
>>> import spacy
>>> nlp = spacy.load('en')
>>> doc = nlp("The sky is blue. The man is pink. The dog is purple.")
>>> sents = [s.as_doc() for s in doc.sents]
>>> list(sents[0].noun_chunks)
[The sky]
>>> list(sents[1].noun_chunks)
Segmentation fault: 11
```
Why do I get this behavior and how do I fix it?

## Info about spaCy

* **spaCy version:** 2.0.2
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.3
* **Models:** en

**Comment by ines** [comment]
Thanks for the report. A segmentation fault is always a bug – will investigate this!

**Comment by soldni** [comment]
I am having the same issue here -- Spacy 2.0.5, Ubuntu 16.04.3 LTS, Python 3.6.3 (Anaconda distribution).

**Comment by honnibal** [comment]
Thanks for the reports.

The issue occurs when we try to use some parts of the dependency parse in `Doc` objects created from `span.as_doc()`. The `.as_doc()` method is creating the `Doc` objects as a view. The new `Doc` holds a pointer to part of the underlying `TokenC*` array. The `Doc` object thinks it's holding the start of the array, but it isn't. Mostly this doesn't matter because the `TokenC` uses relative offsets for the `head` attribute. Because the offset is relative, it doesn't matter that we're in the middle of the array, instead of the start.

However, there are three `TokenC` attributes that *do* refer to absolute positions:

* `token.idx`, the character offset. This one doesn't matter for this bug, but will for other situations such as creating `doc.char_span()` objects

* `token.l_edge`: The leftmost edge of the token's subtree. This is used in `token.lefts`, which is called by `token.children`, and ultimately in `doc.noun_chunks`. This is what triggers the bug.

* `token.r_edge`: Same as `l_edge`, but for rightmost edge.

I think the edge features probably should be relative positions, for consistency. However, the `idx` attribute will still be incorrect, so I think the idea of having `span.as_doc()` return a view is just bad. We should create a new copy of the `TokenC` data for the new doc, so that we can set all the attributes correctly.

The only alternative would be for `Doc` objects to know they might be "views", from a span of a `Doc`. This would be a huge mess; I think we can rule it out right away.

**Comment by honnibal** [comment]
Fixed!
