### ISSUE TITLE
parsing compound sentences

### ISSUE THREAD

**Issue by kjmazidi** [explosion/spaCy#1545]
I'm just starting with Spacy and it doesn't seem to handle compound sentences well. However, when I look at the displacy demo here: https://demos.explosion.ai/displacy/?text=I%20love%20spinach%20and%20I%20like%20peas.&model=en_core_web_sm&cpu=1&cph=1 
and it parsed correctly.

For this simple sentence: I love spinach and I like peas. 

I nsubj love
love ROOT love
spinach dobj love
and cc spinach
I nsubj like
like prep love
peas pobj like
. punct love

There should be a conj between like and love and there are other problems.

Why would I get a different result in Spacy within a program versus the displacy online demo?

## Your Environment

* Operating System: Mac OS Sierra
* Python Version Used: 3.6
* spaCy Version Used: 2.0
* Environment Information:

**Comment by ines** [comment]
Interesting! Which model and model version are you using? (The easiest way to find out is to run `python -m spacy validate`, which will list all installed models and their versions.)

The displaCy online demo runs the latest `sm` models – so for English, that's [`en_core_web_sm`](https://spacy.io/models/en#en_core_web_sm).

**Comment by kjmazidi** [comment]
Thanks for a quick response! I used pip3 install yesterday and am just getting started. So I assume there is some default model that is downloaded.

The command above gave me this error: Command 'validate' does not exist

Is there another way to check the model or how to get the latest models?

**Comment by kjmazidi** [comment]
My apologies, I assumed that pip3 would install 2.0 

When I checked I discovered it installed 1.9.0

$ python3 -m spacy -- info
    Info about spaCy
    spaCy version      1.9.0          
    Installed models    en  

I will go install the latest and see if there is an improvement.

**Comment by ines** [comment]
Ahh yes – this was definitely the problem then. So you were accidentally using the old version of spaCy, with the old English model. (Anyway, it's good that this came up now – otherwise, you would have had many other problems down the line when following the updated documentation.)

> I assumed that pip3 would install 2.0

Yeah, pip should definitely always install the latest version – unless you have an older version installed, in which case you need to run `pip install -U [package]` to make sure it upgrades.

**Comment by kjmazidi** [comment]
I installed spacy-nightly (after dealing with thinc problem) and updated the models and now have the following:

    Installed models (spaCy v2.0.0rc2)
    /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/spacy

    TYPE        NAME                  MODEL                 VERSION                                   
    package     en-core-web-sm        en_core_web_sm        2.0.0a8  ✔      
    link        en_core_web_sm        en_core_web_sm        2.0.0a8  ✔

I am very happy to report that the new version handles compound sentences: 

I nsubj love
love ROOT love
spinach dobj love
and cc love
I nsubj like
like conj love
peas dobj like
. punct like

Yeah!

**Comment by ines** [comment]
Yay! What was the Thinc problem btw? Were you not able to install the stable spaCy v2.0? If so, we definitely want to have a look at this and fix it (if there's an underlying problem), or help you fix it (if there's some other Python weirdness going on)!

**Comment by kjmazidi** [comment]
I got the same error mentioned here: https://github.com/explosion/spaCy/issues/1374

which was : 

ValueError: thinc.extra.search.MaxViolation has the wrong size, try recompiling....

and I followed the advice in that post:

pip install thinc==6.8.1 before pip install spacy-nightly

which seems to have worked

**Comment by ines** [comment]
Ah okay – it sounds like you might have ended up in a weird system state with different, incompatible versions. Unfortunately, this is often pretty hard to prevent (at least on our end) 😞

If you're just getting started with spaCy and want to keep going, using spacy-nightly is probably fine. But ultimately, I guess don't want to be stuck on the nightly version. So once you're ready to upgrade, I'd recommend starting with a clean environment (e.g. `virtualenv`, `pyenv` or `conda`, whatever you prefer working with), and then installing the spaCy package from scratch via `pip install spacy`. This should install all updated dependencies and recompile everything.

I'll close this issue since the underlying problem is resolved – but if you do come across other problems later on, feel free to open another one!
