### ISSUE TITLE
SRL parse

### ISSUE THREAD

**Issue by kjmazidi** [explosion/spaCy#1549]
I am a new user of Spacy and I'm impressed. However there is one additional feature I'd really like: a semantic role label parse. The dependency parse gives you almost everything the SRL parse would, however there are additional things the SRL can tell you. For example, in the following sentence:

He put the key on the table. 

A dependency parse labels "on the table" as a prepositional phrase. True enough. However, prepositional phrases are sometimes modifiers and sometimes **arguments** of the predicate. An SRL parse would label 'on the table' as a numbered argument. This is important in many NLP applications as it is necessary to know which PP are required to complete the meaning of the verb and which are just modifiers adding additional info.

More here about [what I tried to express:]( http://www.cis.upenn.edu/~xtag/tech-report/node121.html)

Has Spacy considered adding an SRL parser?

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by honnibal** [comment]
Hi @kjmazidi ,

Agreed about SRL. For what it's worth, I've spent a lot of time working on complement/adjunct distinctions in my prior research, e.g. https://aclanthology.info/pdf/P/P10/P10-1022.pdf

For now probably the best approach is to wrap some of the latest models for use in spaCy. For instance, here's a wrapper for Allen NLP's work: https://gist.github.com/chssch/f788cfd227cb94d0843235a2542026fd . Given the collaboration with the folks at UW, I would expect Allen NLP to stay at the forefront of SRL developments, so wrapping their models seems like a sound strategy.

Semantic parsing is one of the longest standing feature requests. The main discussion is here: https://github.com/explosion/spaCy/issues/170 -- I know things are difficult to find on GitHub. I'll close this issue to keep the discussion centralised.

The summary is that with the new statistical models, it's easier than before to address new tasks, because there's less need for custom feature engineering. We also have the new extension attributes, which make it easier to write your own usage layer. It's no fun to just *predict* the SRL graph -- we want to actually use and query it.

The other interesting problem is training data. I think this really dominates the algorithmic concerns: if I had to choose between having 1000 sentences annotated from my target domain and a fancier algorithm, I'd always take the annotated data.
