### ISSUE TITLE
NER is sensitive to line breaks

### ISSUE THREAD

**Issue by nathanathan** [explosion/spaCy#1568]
In this span removing the line break makes the difference whether the zero is recognized as a cardinal:
```
1003 recoveries, and
0 currently active cases
```

## Your Environment

* **Python version:** 2.7.11
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **spaCy version:** 2.0.2

* Model: en_core_web_md

**Comment by CYUlysses** [comment]
I usually do a sentence parsing first before running the NER; not sure whether that satisfies for your case, though.

**Comment by ines** [comment]
We definitely aspire to be less sensitive to things like this, and add more data augmentation to the training process.

spaCy's tokenizer splits on single whitespace characters (and keeps them in `token.text_with_ws`) – but all additional whitespace is preserved in additional tokens. This is due to spaCy's "non-destructive tokenization" philosophy, which ensures that no information is lost during processing and every character that goes in is somehow represented in the `Doc`. Depending on what you're analysing, you often do want to keep and use that data later on – for example, having newlines available will let you determine original paragraphs (information that otherwise would be lost).

If this is not relevant to you, the easiest solution would be to pre-process your text before feeding it into spaCy's pipeline – for example, by replacing newlines and tabs with spaces and replacing multiple spaces with a single space.
