### ISSUE TITLE
Does 'en_core_web_md' available for spaCy2 or not?

### ISSUE THREAD

**Issue by Zhenshan-Jin** [explosion/spaCy#1596]
Based on the documentation [here](https://github.com/explosion/spacy-models/releases/tag/en_core_web_md-2.0.0), model en_core_web_md, should be available for spaCy 2. But when I run `spacy download en_core_web_md`, it shows that 
```Compatibility error     
No compatible model found for 'en_core_web_md' (spaCy v2.0.0rc2).
````
spaCy version: v2.0.0rc2

**Comment by pavillet** [comment]
`spacy download en_core_web_md` does work for me

My guess : your versions is too old, try upgrading to latest spacy

## Info about spaCy

* **spaCy version:** 2.0.3
* **Platform:** Darwin-16.6.0-x86_64-i386-64bit
* **Python version:** 3.6.1
* **Models:** fr, fr_core_news_md

**Comment by ines** [comment]
Yes – as the error message shows, it seems like you're currently running `v2.0.0rc2` (i.e. the spaCy v2.0 release candidate that's available via `spacy-nightly`).

So you'll need to upgrade to the latest spaCy version available via the `spacy` package. One thing that's very important though: If you can, try starting with a fresh environment or at least, deleting `spacy-nightly` before running the following command to update.

```python
pip install -U spacy
```

Otherwise, you can easily end up in a weird system or environment state with mismatched dependencies.

**Comment by Zhenshan-Jin** [comment]
@pavillet @ines Thanks, for spaCy 2.0.3 it works!

Just out of curiosity, I'm wondering can we say that 2.0.3 is already a stable release of spaCy?

**Comment by honnibal** [comment]
@Zhenshan-Jin 2.0.3 is the "main" release of spaCy -- it's not an alpha or a beta. So yes in that sense it's the stable release. We hope you also find it *stable* in the more subjective sense, of working well and not having too many bugs -- in this sense I think it's the most stable version of spaCy yet. But of course, this is for you to judge :)
