### ISSUE TITLE
error when `Doc.to_disk()`

### ISSUE THREAD

**Issue by kyoungrok0517** [explosion/spaCy#1597]
I see the following error when I use multi-thread pipe + serialization. In [spaCy 101](https://spacy.io/usage/spacy-101#lightning-tour-serialization) it feeds a string for saving path but it doesn't work with me. 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-24d78de5446f> in <module>()
      4 for i, doc in enumerate(nlp.pipe(texts, batch_size=100, n_threads=4)):
      5     fpath = os.path.join('./spacy/', '{}.spacy'.format(i))
----> 6     doc.to_disk(fpath)

doc.pyx in spacy.tokens.doc.Doc.to_disk()

AttributeError: 'str' object has no attribute 'open'
```

## Info about spaCy

* **spaCy version:** 2.0.2
* **Platform:** Windows-10-10.0.17025-SP0
* **Python version:** 3.5.3

**Comment by ines** [comment]
Thanks for the report – this was an error in v2.0.2 (see #1521) ans has since been fixed in v2.0.3. So simply updating spaCy to the latest version should do the trick:

```python
pip install -U spacy
```

Btw, if you're using conda, note that the latest version is not available via `conda-forge` just yet. Unfortunately, the conda builds always take a little longer – but it'll be there asap (as soon as the build is fixed an all tests pass).
