### ISSUE TITLE
ImportError: No module named en

### ISSUE THREAD

**Issue by rameshjesswani** [explosion/spaCy#1609]
I have installed spacy following these steps :

 ```
sudo apt-get install build-essential python-dev git(system level dependencies)
 pip install spacy
python -m spacy validate
python -m spacy download en
python -m spacy download en_core_web_lg
```

When I try:
```
nlp = spacy.load('en')  
```
It works fine.

But When i try to use something from "en", 
```
from spacy.en import English
```
```
I get error: ImportError: No module named en
```
Can anyone help me with this please? 

* **Python version:** 2.7.14
* **Platform:** Linux-4.4.0-98-generic-x86_64-with-debian-jessie-sid
* **spaCy version:** 2.0.3
* **Models:** en, en_core_web_lg

**Comment by ines** [comment]
Hi! I think the issue is very simple: In spaCy v2.0, the language data has been moved to a submodule `spacy.lang`, to keep things cleaner and more organised. You can find more details on the backwards incompatibilities and how to adjust your v1.x code for v2.x [on this page](https://spacy.io/usage/v2#section-incompat).

So you'll have to do:

```python
from spacy.lang.en import English
```

**Comment by rameshjesswani** [comment]
Thanks very much.
