### ISSUE TITLE
Python 2: One syntax error and two undefined names / Python 3: Five undefined names

### ISSUE THREAD

**Issue by cclauss** [explosion/spaCy#1617]
## Python 2

See: https://travis-ci.org/explosion/spaCy/builds/304678969

__python2 -m flake8 . --count --exclude=spacy/lang --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./examples/information_extraction/entity_relations.py:39:18: E999 SyntaxError: invalid syntax
    for span in [*list(doc.ents), *list(doc.noun_chunks)]:
                 ^

./spacy/tests/lang/fr/test_lemmatization.py:25:14: F821 undefined name 'FR'
    tokens = FR("il y a des Costaricienne.")
             ^

./spacy/tests/regression/test_issue910.py:81:11: F821 undefined name 'Adam'
    sgd = Adam(nlp.entity.model[0].ops, 0.001)
          ^

1     E999 SyntaxError: invalid syntax
2     F821 undefined name 'FR'
3
```

## Python 3

See: https://travis-ci.org/explosion/spaCy/builds/304678969

__flake8 . --count --exclude=spacy/lang --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./spacy/compat.py:56:16: F821 undefined name 'unicode'
    unicode_ = unicode
               ^

./spacy/compat.py:57:19: F821 undefined name 'basestring'
    basestring_ = basestring
                  ^

./spacy/compat.py:58:14: F821 undefined name 'raw_input'
    input_ = raw_input
             ^

./spacy/tests/lang/fr/test_lemmatization.py:25:14: F821 undefined name 'FR'
    tokens = FR("il y a des Costaricienne.")
             ^

./spacy/tests/regression/test_issue910.py:81:11: F821 undefined name 'Adam'
    sgd = Adam(nlp.entity.model[0].ops, 0.001)
          ^

5     F821 undefined name 'unicode'
```

**Comment by ines** [comment]
Thanks a lot for the detailed report – I hope you don't mind that I merged the two issues, since they're essentially related to the same thing.

The `spacy/compat.py` errors should probably be excluded via `# noqa: F821`. Those are the Python 2/3-specific versions of the built-ins.

I'm surprised that the tests passed... will check, but I assume `test_issue910.py` is likely xfailed, and the French lemmatization tests require the models and are only run if `--models --fr` is set when running pytest (which we're not doing on Travis, as it's too time consuming and potentially flakey at the moment). Should be easy to fix by adding the `FR` fixture to the test arguments.

> for span in [*list(doc.ents), *list(doc.noun_chunks)]:

Damn, this is a good catch. Looks like we only ever ran this example in Python 3, so will fix that to make it  compatible.
