### ISSUE TITLE
SpaCy Model Download/Build Issues w/ Visual Studio

### ISSUE THREAD

**Issue by obeavers** [explosion/spaCy#1663]
## Error Message

Hello, when I run "python -m spacy download en" from Anaconda prompt, the script gets to here:

` creating build\temp.win-amd64-3.6\Release\thinc`

Then falls apart with the following error message:

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Oliver\Anaconda3\include -IC:\Users\Oliver\AppData\Local\Temp\pip-build-qp1sxrge\thinc\include -IC:\Users\Oliver\Anaconda3\include -IC:\Users\Oliver\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /EHsc /Tpthinc/linalg.cpp /Fobuild\temp.win-amd64-3.6\Release\thinc/linalg.obj /Ox /EHsc
    linalg.cpp
    c:\users\oliver\anaconda3\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

```

### called from python -m spacy info
    spaCy version      2.0.3
    Location           C:\Users\Oliver\Anaconda3\lib\site-packages\spacy
    Platform           Windows-10-10.0.14393-SP0
    Python version     3.6.3

What to do?

**Comment by ines** [comment]
Thanks for the report. Under the hood, `spacy download` fetches the download URL of the model file and then installs the package via `pip install`. Since the model package specifies spaCy as a dependency, it looks like pip is actually installing spaCy and its dependency Thinc, which somehow fails in your environment.

As a solution, you can always [download the model archive files](https://spacy.io/usage/models#download-manual), unzip them and load in the model data manually. You can find the archive files in the [spacy-models repo](https://github.com/explosion/spacy-models), or by clicking the "Release details" button in the [models directory](https://spacy.io/models/en). `spacy.load()` accepts a model package name or a directory, so you can also do:

```python
nlp = spacy.load('/path/to/en_core_web_sm-2.0.0')  # path to data directory contained in archive
``` 

I agree that this is not perfectly convenient and elegant, and we've been thinking about solutions to this problem. There's also an open enhancement issue that discusses better solutions for the model packages in conda environments here: #1686
