### ISSUE TITLE
Models should be installable as conda packages

### ISSUE THREAD

**Issue by jnothman** [explosion/spaCy#1686]
Spacy models are currently managed by pip. They also have a number of pip dependencies. pip and conda don't always play super nice together. conda has some substantial space efficiency benefits when using multiple conda environments on the same machine, such as its use of hard links. spacy should consider maintaining a conda channel for models, and installing with Conda at least where a conda environment is active.

**Comment by honnibal** [comment]
We'd welcome a pull request that added a conda mode to the `spacy package` command. I can't say I'm thrilled at the idea of publishing a whole new set of artefacts for the models, wrapped as conda packages instead of pip packages.

Is something actually broken with the current workflow on conda?

**Comment by jnothman** [comment]
Nothing's broken with the current workflow on conda, but given the size of
models, not having separate instances in each environment would be a boon,
for instance.

**Comment by honnibal** [comment]
Fair enough. Do you know whether conda and pip both work with the same `.whl` files? This might be a nice solution, since we don't depend on executing any code in `setup.py` for the models. So if we build them with `bdist_wheel` instead of `sdist` and that means they work on both conda and pip, that would be nice.

`spacy.load()` also takes a disk path, if you prefer to manage a directory of these resources yourself. This is also helpful when you're training your own models.
