### ISSUE TITLE
python -m spacy model is not work on spaCy 2.0 

### ISSUE THREAD

**Issue by asachanmanchoi** [explosion/spaCy#1694]
Hey guys,

I'm trying to create a new model. But I found that the "model" option is removed on spacy 2.0.

python -m spacy **model** <lang> ./data/model/<lang>/spacy_model ./data/model/<lang>/<lang>_wiki.freqs ./data/model/<lang>/brown/paths ./data/model/<lang>/<lang>_wiki.word2vec.bz2

In spacy cli directory, it is no model.py file found.

How to train a my new own model in spacy 2.0?
Thanks

## Your Environment
* **Python version:** 2.7.14
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **spaCy version:** 2.0.3
* **Models:** en

**Comment by ines** [comment]
Hi, sorry about that. In spaCy v2.0, the vocabulary-related functionality of `spacy model` has been moved to the `spacy vocab` command: https://spacy.io/api/cli#vocab

There's also a pending pull request that brings back the frequencies and brown clusters options, and calls into `spacy vocab`: #1646

The only thing that's currently missing is a better name – we've never really been happy with the command being called `model`, because it's pretty vague and easily led to confusion. So if you have an idea, feel free to contribute! 😊 (I already posted some ideas in #1646, but I'm not really sure if any of them really fit.)

**Comment by ines** [comment]
**Update:** Just merged #1646 with some modifications and there will be an `init-model` command in v2.0.5 that does exactly what you're looking for. Just waiting for the tests and built and will push the new version as soon as everything's green.

**Comment by asachanmanchoi** [comment]
Many thanks
