### ISSUE TITLE
Is it expected behaviour that LIKE_URL also matches on e-mail addresses?

### ISSUE THREAD

**Issue by Bri-Will** [explosion/spaCy#1698]
For the code below, an e-mail address triggers both matching rules: 

```
import en_core_web_sm
from spacy.matcher import Matcher

nlp = en_core_web_sm.load()
matcher = Matcher(nlp.vocab)

matcher.add('EMAIL', None, [{'LIKE_EMAIL': True}])
matcher.add('URL', None, [{'LIKE_URL': True}])

doc = nlp(u'What happens with an email@address.com and how about a URL like http://www.google.com?')
matches = matcher(doc)

print (matches)
```
Results:
`[(17587345535198158200, 4, 5), (2582013287274679728, 4, 5), (2582013287274679728, 11, 12)]`

Seems like they should be distinct...I didn't think an "@" symbol could be present in a URL...

## Your Environment

* Operating System: Windows
* Python Version Used: 3
* spaCy Version Used: 2.0
* Environment Information:

**Comment by ines** [comment]
Thanks for the report 👍  This is definitely not intentional.

For performance reasons, the `like_url` getter uses simple conditionals instead of regular expressions. This means it should be easy to adjust – maybe even as simple as adding something along the lines of `'@' not in text`. The relevant source is here:

https://github.com/explosion/spaCy/blob/51d3ab21378a298c0c5abcc8fdba1ddf22223cc9/spacy/lang/lex_attrs.py#L76-L95

I'll add a `help wanted` label in case anyone wants to give it a go, adjust the getter and add a few tests for it. Otherwise, we're happy to take care of this, too.

**Comment by Bri-Will** [comment]
FYI, I added an `if` statement like so:
```
if '@' in text:
    return False
```
and it seems to works fine.

I'd love to add the fix, but I'm too much of a newbie to be trusted to do that!

**Comment by ines** [comment]
@Bri-Will Thanks for updating – nice to hear that it's working!

> I'd love to add the fix, but I'm too much of a newbie to be trusted to do that!

Don't worry – of course, you don't *have to*, but if you'd like to submit your first PR, I'm happy to assist! Your fix looks fine and you don't have to worry about adding tests for now (I'll take care of this later).

The easiest way is to just fork spaCy so it's added to your GitHub account. Then add the fix and push it to your fork, go to the [New Pull Request](https://github.com/explosion/spaCy/compare) page and hit "Compare across forks".  Select your fork as the head repo, and your change should show up. You can then create a new pull request, write a sentence describing the change and submit it 🎉 There's actually very little that can go wrong – all new PRs are tested and we'll review them before merging, so you can't break anything.

**Comment by Bri-Will** [comment]
OK, I've done this and submitted a pull request (I did not add tests for this)
