### ISSUE TITLE
Vector lengths of Doc differ after serialization 

### ISSUE THREAD

**Issue by RebornSage** [explosion/spaCy#1701]
Hello

I am trying to save a Doc object to disk and load it later to compute similarities to a sentence provided by the user. However, I got this error message:
`ValueError: shapes (300,) and (384,) not aligned: 300 (dim 0) != 384 (dim 0)`

This minimal examples shows the problem:

```python
from spacy.tokens import Doc
from spacy.vocab import Vocab
from spacy import load

nlp = load('en_core_web_md')

doc1 = nlp('Is this a bug?')
doc1.to_disk('doc.bin')
doc2 = Doc(Vocab()).from_disk('doc.bin')

user_input = nlp('Some words.')

print(doc1.vector.shape)
print(doc2.vector.shape)

print(user_input.similarity(next(doc1.sents)))
print(user_input.similarity(next(doc2.sents)))
```

```
(300,)
(384,)
0.66116987173
Traceback (most recent call last):
  File "bug.py", line 17, in <module>
    print(user_input.similarity(next(doc2.sents)))
  File "doc.pyx", line 300, in spacy.tokens.doc.Doc.similarity
ValueError: shapes (300,) and (384,) not aligned: 300 (dim 0) != 384 (dim 0)
```
What's wrong here?

## Info about spaCy

* **spaCy version:** 2.0.5
* **Python version:** 3.5.3
* **Platform:** Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty

**Comment by amirkargar** [comment]
I got the same error when getting similarity score between two tokens which were generated using different nlp objects.

**Comment by honnibal** [comment]
Usability isn't great here, but I'm not sure what the best solution is.

`doc.to_bytes()` currently avoids serialising the `Vocab`, in order to avoid dragging a copy of the vectors into each serialised `Doc` object. But then when we load the `Doc` back in, we're missing the information. The best workaround at the moment would be to do `doc2 = Doc(nlp.vocab).from_disk('doc.bin')` if possible.

@ines Thoughts on what we should do here? If nothing else I guess we should at least document this clearly. Maybe we need that `Binder` class after all?

**Comment by ines** [comment]
> @ines Thoughts on what we should do here? If nothing else I guess we should at least document this clearly. Maybe we need that `Binder` class after all?

I'll definitely add some notes about this to the docs – I think both the serialization section as well as the vectors section would make sense here.

And this is a tricky question... I agree that it's weird to have the `Doc.to_bytes` behave inconsistently, but having spaCy save out the vectors and vocab for each `Doc` would be pretty unsatisfying, too. Introducing another keyword argument on `Doc.to_bytes()` would be okay in theory, since it's already inconsistent anyways – but we'll likely want to fix this more elegantly in the future and without breaking backwards compatibility of the `Doc` API.

**Comment by ines** [comment]
Merging this with #1921, as it's both related to future changes to the serialization API.
