### ISSUE TITLE
Bug with Contiguous spaces

### ISSUE THREAD

**Issue by criver** [explosion/spaCy#1707]
Tokenization with two contiguous spaces will give results with one of the space as token. `nlp('foo  bar') -> ['foo', ' ', 'bar']`. Expected tokens `['foo', 'bar']`.

If you're looking for help with your code, consider posting a question on StackOverflow instead:
http://stackoverflow.com/questions/tagged/spacy -->

## Your Environment

* Operating System: macOS
* Python Version Used: Python 3.6
* spaCy Version Used: 2.0.1
* Environment Information:

**Comment by ines** [comment]
Thanks – this is actually by design, since spaCy will preserve all whitespace in the document. The tokenizer splits on single whitespace characters (and preserves those in the `token.text_with_ws_` attribute). All other whitespace characters will be preserved as tokens, so you'll never lose any data present in the original document.

However, you can filter out whitespace tokens by checking the token's `is_space` flag:

```python
tokens = [token for token in doc if not token.is_space]
```

You can also pre-process your text and remove all double whitespace characters if you know that you don't care about them.
