### ISSUE TITLE
AttributeError: 'FunctionLayer' object has no attribute 'vectors'

### ISSUE THREAD

**Issue by bellatrics** [explosion/spaCy#1727]
First of all, many thanks for such a nice package.

The task I am solving is to have german model (with parser, ner) with fastText vectors.
There are many different ways that cause the AttributeError: 'FunctionLayer' object has no attribute 'vectors'. This one is the most concise one:

```
data = np.ones((3, 300), dtype='f')
keys = [u'ich', u'bin', u'haha']
vectors = Vectors(data=data, keys=keys)

nlp_de = spacy.load('de')
nlp_de.vocab.vectors = vectors

nlp_de.to_disk('./model_de')

nlp = spacy.load('./model_d')
```

All good and working, but before loading. Then it raises the error

Many different things I tried: creating vocabulary, assembling a pipeline... link_vectors_to_models ...
all lead to the same thing.
What works is creating a blank model, adding a tagger. But when adding a parser or ner then it is back to the problem.

Please, explain me if it is a bug or I do something bad. Also, what is the right way to add vectors to existing model and also map the keys in the vocab?

Thanks!

## Your Environment

* **spaCy version:** 2.0.3
* **Platform:** Darwin-16.0.0-x86_64-i386-64bit
* **Python version:** 3.6.0
* **Models:** _de, de, en, en_core_web_lg, en_core_web_md

**Comment by PricelessRabbit** [comment]
same issue, see also #1661

**Comment by PricelessRabbit** [comment]
for a workaround, you can load load your model without vectors:
`nlp = spacy.load("lang")`
and then load your vectors with
`nlp.vocab.vectors.from_disk("../spacy_vectors")`

**Comment by GruffPrys** [comment]
I'm getting the same error message when loading a packaged custom language model to which I added vectors.

If I import the version without vectors, I can load the vectors with @PricelessRabbit's workaround and all is well (thanks!).

If I try and load the unpackaged version with vectors it fails to load in the pipeline from meta.json, leaving it empty.

**Comment by MarcErdmann** [comment]
I am evaluating your product Prodigy right now and I get the same error

**Comment by honnibal** [comment]
Thanks for your patience on this.

The error is occurring because the tagger model was trained when no vectors were available, and then vectors are added later. When the model is saved, the tagger is checking whether the vectors exist, and writing the wrong attribute into its config file. When the model is reloaded, it consults its config and tries to deserialise the model with the has-vectors architecture. Specifically, it follows this branch of the conditional when creating the architecture: https://github.com/explosion/spaCy/blob/v2.0.5/spacy/_ml.py#L271 . After this function exits, we next try to deserialise the weights --- which were saved when no vectors were available. This causes the error we're seeing here.

The fix I've implemented is to simply avoid overwriting this `pretrained_dims` cfg setting when writing out the model. To workaround the bug in your current models, you might load back in the cfg file and fix the value of that entry. Alternatively, you could drop the vectors before serializing your model, and then only add them after you've loaded your model back from disk.

Thanks again for the report!

**Comment by PricelessRabbit** [comment]
@honnibal thanks for the support, spacy is great! :)

**Comment by thetravelingsalesman** [comment]
To be clear @honnibol is saying change the cfg files so that every entry in ```pretrained_dims``` is 0 for every pipe (including the ner) in the model.
