### ISSUE TITLE
Unable to install Spacy in my windows 7 32 

### ISSUE THREAD

**Issue by k4m35h** [explosion/spaCy#1741]
I am trying to install Spacy for the past five days and i am tried now ... I am very much impressed with the spacy documentation but i am struggling to install it in my windows 7 32 bit os ... I have tried installing it from anaconda and pip ...

Also tried to install a wheel package of it from https://www.lfd.uci.edu/~gohlke/pythonlibs/ .... while installing the wheel file also i got unsupported message ...

- cymem-1.31.2-cp27-cp27m-win32.whl
- spacy-2.0.5-cp27-cp27m-win32_2.whl
- murmurhash-0.28.0-cp27-cp27m-win32.whl
- numpy-1.13.3+mkl-cp27-cp27m-win32_2.whl
- thinc-6.10.2-cp27-cp27m-win32.whl
- preshed-1.0.0-cp27-cp27m-win32.whl
- Error which I got

> spacy-2.0.5-cp27-cp27m-win32_2.whl is not a supported wheel on this platform.

Am trying for an working wheel for spacy is there any source or anyone could provide ??

**Comment by ines** [comment]
So sorry about that! (I can relate to the pain, though – we just got a Windows dev machine a while ago to build a bunch of wheels for different configurations and it ended up being very frustrating 😩)

One observation: The name of the file you're trying to install ends with `-win32_2.whl`, while the files from the download link all end in `win32.whl`. Could it be that you downloaded the file twice and it was renamed to xxx_2.whl? 

The file name of the wheel matters and is used to determine whether it's a "supported wheel on this platform". What happens if you rename it and remove the _2? If the specified platform matches the output of `distutils.util.get_platform()`, the wheel should definitely be correct and installable.

**Comment by k4m35h** [comment]
It Works !! Thank You **ines** ....
