### ISSUE TITLE
bug about long text. Tokenizer will loop forever

### ISSUE THREAD

**Issue by stanpcf** [explosion/spaCy#1765]
os version, python version, spacy version will be find in the picture
![image](https://user-images.githubusercontent.com/13925796/34332934-914be346-e971-11e7-9611-c1813f6fd11e.png)

the var `text` is a true comment from a web. it can't execute `nlp(text)`over

**Comment by Liebeck** [comment]
A string consisting of 175k characters is very long. I'm not sure how Ines and Matthew think about this but I would suggest that you generally split your input text into chunks, either by natural paragraphs/linebreaks or via a hard character limit.
And depending on your application, you might think about skipping such a long web comment since the author is most likely trolling ;-)

**Comment by stanpcf** [comment]
@Liebeck I select first of the 100 char of this comment to replace itself. But I think this should be a bug. spacy should raise exception when deal such the text instead of loop(my app in this place for some hours when I force it to stop) if it can't deal with such a text.  If possible and the developer of this tool is busy I will make a pull-request after some weeks

**Comment by ines** [comment]
Merging this with #1765.
