### ISSUE TITLE
german license & tiger corpus

### ISSUE THREAD

**Issue by jwijffels** [explosion/spaCy#1800]
Hello. I've got a question regarding the German license. I read that you used the TIGER corpus (http://www.ims.uni-stuttgart.de/forschung/ressourcen/korpora/tiger.html) and I was wondering how the license of the German model can be CC BY-SA 3.0 while the TIGER corpus allows only for commercial use if you get a license from them (http://www.ims.uni-stuttgart.de/forschung/ressourcen/korpora/TIGERCorpus/license/index.html)? Can you clarify on how Spacy handled this licensing issue?
Many thanks for input on this.

**Comment by honnibal** [comment]
The TIGER commercial license allows distribution of models trained with the corpus, so long as the model doesn't allow reconstruction of the original resource (e.g. we wouldn't be allowed to distribute a model which had say, 5-gram counts). This is a fairly typical situation for other corpora with commercial licensing options.

We chose the CC-BY-SA license because it's a license likely to be "whitelisted" by companies' legal teams. It's also a license that seems to raise relatively few open questions, and doesn't impose constraints on users, e.g. none of your work needs to be CC-BY-SA.

**Comment by jwijffels** [comment]
Many thanks on the input!
