### ISSUE TITLE
Potential bug report, "when" transferred into "what" in noun_chunks

### ISSUE THREAD

**Issue by Zhenshan-Jin** [explosion/spaCy#1847]
sentence: 
code
```
sentence = "when was the last time a ball hit you?"
nlp = spacy.load("en_web_core_sm")
doc = nlp(sentence)
print([ck for ck in doc.noun_chunks])
```
Result: 
![image](https://user-images.githubusercontent.com/14370804/34966614-b11888ca-fa22-11e7-9254-a360474161a1.png)

## Your Environment

* Operating System: Ubuntu 16.04
* Python Version Used: 3.6
* spaCy Version Used: 2.0.5

**Comment by ines** [comment]
This is... very bizarre. I just tested it and couldn't reproduce the error – the "what" chunk doesn't show up for me:

```bash
>>> nlp = spacy.load("en_core_web_sm")
>>> doc = nlp(u"when was the last time a ball hit you?")
>>> print([ck for ck in doc.noun_chunks])
[the last time, a ball, you]
```

Also just noticed this line in your example:

```python
nlp = spacy.load("en_web_core_sm")
```

Is this just a typo (i.e. `en_web_core` instead of `en_core_web`), or do you actually have a model of that name as well? And could you check which version of the model you're using, for example, by running `spacy validate`?

**Comment by Zhenshan-Jin** [comment]
Hi @ines ,


Thanks for the quick response, I double checked my code and found out that I re-processed the sentence and actually transfer the sentence from `when was the last time a ball hit you?` to `what was the last time a ball hit you?`.

Sorry for confusing!


Zhenshan
