### ISSUE TITLE
Tokenizer and Punctuation

### ISSUE THREAD

**Issue by rikkuporta** [explosion/spaCy#1854]
So, according to this (https://spacy.io/usage/spacy-101#annotations-token) it should be able to split up with punctuation, but if I try it, this does not happen.

```
    import spacy
    from spacy.tokenizer import Tokenizer
    nlp = spacy.load("en_core_web_md")
    tokenizer = Tokenizer(nlp.vocab)
    toks = tokenizer("i'd like to see a movie, from jean-juncker or someone?")
    for token in toks:
        print(token.text)
```

Output:
i'd
like
to
see
a
movie,
from
jean-juncker
or
someone?

Expected Output:
i'd
like
to
see
a
movie
,
from
jean-juncker
or
someone
?

Or just ommiting the punctuations at all.

* Operating System: Ubuntu
* Python Version Used: 3.62
* spaCy Version Used: 2
* Environment Information: Anaconda

**Comment by ines** [comment]
I think the problem here is that you're initialising a *new tokenizer* using only the `nlp` object's vocab – but not the tokenization rules. So in order to use the English tokenization rules that are loaded with the English model, you can simply call `nlp` on your text to process it. By default, this tokenize the text and assign part-of-speech tags, dependency labels and named entities:

```python
nlp = spacy.load("en_core_web_md")
doc = nlp("i'd like to see a movie, from jean-juncker or someone?")
print([token.text for token in doc])
# ['i', "'d", 'like', 'to', 'see', 'a', 'movie', ',', 'from', 'jean', '-', 'juncker', 'or', 'someone', '?']
```

If you only certain parts of the model, you can also use the `disable` keyword argument on `spacy.load`, e.g. `disable=['parser', 'ner']`. If you only need the tokenizer, you don't even have to load the model at all. You can simply import the `English` language class, which includes punctuation rules, tokenizer exceptions etc:

```python
from spacy.lang.en import English
nlp = English()
doc = nlp("i'd like to see a movie, from jean-juncker or someone?")
print([token.text for token in doc])
# ['i', "'d", 'like', 'to', 'see', 'a', 'movie', ',', 'from', 'jean', '-', 'juncker', 'or', 'someone', '?']
```
