### ISSUE TITLE
nlp.vocab.load_vectors function in SpaCy v2

### ISSUE THREAD

**Issue by Tiriar** [explosion/spaCy#1890]
Hello, I recently upgraded from SpaCy 1.9.0 to 2.0.4. I am working with pre-trained GloVe vectors and I used to load them as:
```commandline
model = spacy.load('en', vectors=False)
with open(glove.6B.300d.txt, 'r', encoding='utf-8') as f:
    model.vocab.load_vectors(f)
```

With the new version, it seems that the ```load_vectors``` function was removed, so I was looking for a replacement. I ran across https://spacy.io/usage/vectors-similarity, which mentions function ```from_glove```, but it only supports .bin format. However, the pre-trained vectors from the official GloVe website come as .txt files. I also tried the "loading other vectors" approach from https://spacy.io/usage/vectors-similarity, but even though it works and gives the correct results, loading in this manner is incredibly slow compared to the old ```load_vectors``` function.

So now of course I could go back to the old version of SpaCy, convert the .txt file to .bin or just put up with the loading time. But first I would like to ask if I missed something and there is another loading option of the .txt files comparable to the old approach.

Thanks.

## Info about spaCy
* **spaCy version:** 2.0.4
* **Platform:** Linux-4.13.0-31-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.3
* **Models:** en

**Comment by honnibal** [comment]
Once you've loaded the text vectors once, you can save them with `vectors.to_disk()`, and from there they should be fast to load.

I think the text file format is an okay interchange format to distribute models, because it's easy to work with. But it's always going to be slow, which is why we've preferred to focus on optimizing the binary loaders. Having a lot of serialization functions makes maintenance really difficult.

**Comment by Tiriar** [comment]
Thank you for the reply, I will try the to_disk function. I understand your decision to focus on the binary files, I am just wondering how the old load_vectors function managed to load the text file so quickly (I am talking about roughly 10 times quicker than the naive approach I am using now).

**Comment by honnibal** [comment]
I wonder whether the vectors table is sized correctly when you start adding the entries one-by-one? If not, it's possible it has to keep reallocating the array, which might take time. Otherwise I'm not sure! Here's the implementation of `load_vectors()` in 1.x: https://github.com/explosion/spaCy/blob/v1.10.0/spacy/vocab.pyx#L527 . It doesn't look especially quick to me.

**Comment by Tiriar** [comment]
Thank you, I will have a look at it. But the easiest solution as you said will probably be to save the vectors as a binary file. Thanks again, I am closing the issue ;)
