### ISSUE TITLE
Evaluating the performance (memory and speed) of different annotators in isolation from other [irrelevant] components

### ISSUE THREAD

**Issue by danyaljj** [explosion/spaCy#1894]
I want to evaluate speed/memory requirements for each of the individual components. 
The solution that I found is, disabling irrelevant components (Good so far?). 
Please help me figure out the right syntax. 

## only sentence splitter 
?

## only word tokenizer 
?

## only lemmatizer
?

## only POS 
We need only 'tagger' only: 
```python
nlp = spacy.load('en', disable=['parser', 'ner', 'parser', 'textcat', 'entity'])
```

## only (phrase) chunker 
?

## only NER 
We need only 'ner' only: 
```python
nlp = spacy.load('en', disable=['parser', 'tagger', 'parser', 'textcat', 'entity'])
```

**Comment by honnibal** [comment]
Some of the annotations you're interested in can't be accessed in isolation, because they depend on other components. For instance, lemmas are set automatically once the part-of-speech tagger is applied. There's a separate sentence splitter, but by default we use the parser to assign the sentence boundaries. The noun chunks are also set by the parser.

The `nlp.disable_pipes()` context manager might help you, especially in combination with the `nlp.pipe_names` property, which tells you which pipes are currently enabled.

**Comment by danyaljj** [comment]
@honnibal thanks for the clarification. 
A follow up on this: As you mentioned, I can check the active "pipes" (annotators?). So: 
```python 
nlp = spacy.load('en')
print(nlp.pipe_names)
```
does give me: `['tagger', 'parser', 'ner']`

And I can disable one of these. For example 'ner':  
```python 
nlp = spacy.load('en')
nlp.disable_pipes('ner')
print(nlp.pipe_names)
```
which gives me: `['tagger', 'parser']`. So far, so good. What is unclear to me is, 
 - The modules that each component depends on (for each of the components I have mentioned above)

Can you help with this?

**Comment by danyaljj** [comment]
Just to clarify the issue: 

Is this enough to process everything?: 
```python
 doc = nlp(paragraph)
```

Or I have to call all the functions explicitly? 
```python
    doc = nlp(paragraph)
    sentences = list(doc.sents)
    [tok for tok in doc]
    [chunk  for chunk in doc.noun_chunks]
    [tok.lemma_ for tok in doc]
    [entity.text for entity in doc.ents]
    [tok.pos_ for tok in doc]
```

**Comment by honnibal** [comment]
`doc = nlp(paragraph)` -- or better, with `nlp.pipe()` is enough to process everything. The annotations are not computed lazily.
