### ISSUE TITLE
POS tags of email addresses assigned by German model

### ISSUE THREAD

**Issue by e-anima** [explosion/spaCy#1895]
I did a test using the matcher with LIKE_EMAIL and  LIKE_URL
In english it works

```python
#import de_core_news_sm
import en_core_web_sm

from spacy.matcher import Matcher

#nlp = de_core_news_sm.load()
nlp = en_core_web_sm.load()
matcher = Matcher(nlp.vocab)

matcher.add('EMAIL', None, [{'LIKE_EMAIL': True}])
matcher.add('URL', None, [{'LIKE_URL': True}])

#DE
#doc = nlp(u'Ich habe eine Mail an email@address.com geschrieben die einen Link zu http://www.google.com enthält.')
#EN
doc = nlp(u'I have written an email to email@address.com with a link to http://www.google.com.')

matches = matcher(doc)

print (matches)
for token in doc:
    print(token.text, token.tag_)
```

email@address.com ADD
http://www.google.com ADD

Then i ran it with german changing the code to

```python
import de_core_news_sm
#import en_core_web_sm

from spacy.matcher import Matcher

nlp = de_core_news_sm.load()
#nlp = en_core_web_sm.load()
matcher = Matcher(nlp.vocab)

matcher.add('EMAIL', None, [{'LIKE_EMAIL': True}])
matcher.add('URL', None, [{'LIKE_URL': True}])

#DE
doc = nlp(u'Ich habe eine Mail an email@address.com geschrieben die einen Link zu http://www.google.com enthält.')
#EN
#doc = nlp(u'I have written an email to email@address.com with a link to http://www.google.com.')

matches = matcher(doc)

print (matches)
for token in doc:
    print(token.text, token.tag_)
```

Now i get

email@address.com NE
http://www.google.com NE

What i was expecting is that in german it will also get tagged with ADD. I basically only changed the model and text input.

**Comment by ines** [comment]
I hope I understand the question correctly – when I first read this issue, I thought the problem was that the matches weren't found correctly in German based on the `LIKE_URL` and `LIKE_EMAIL` attributes, which would have been worrying.

But you mostly mean the different part-of-speech tag, right?

The thing is that you're looking at the `.tag_` attribute here, which is the fine-grained part-of-speech tag. Because the English and German models were trained on different corpora, the tagging scheme of the fine-grained POS tags is also different. See [this page in the API docs](https://spacy.io/api/annotation#pos-tagging) for an overview of the different schemes across languages.

The fine-grained English tag scheme has an `ADD` tag for email addresses – however, this was never tagged in the German corpus, so the `NE` tag (proper noun) is assigned. If you look at the token's `.pos_` attribute (the coarse-grained, universal tag) instead, it should both be `PROPN`.

If the POS tag of email addresses is important to you (e.g. if your `Matcher` solution is not enough), you should be able to [update the German tagger](https://spacy.io/usage/training#example-train-tagger) pretty easily with a few examples. Email addresses are very distinct, and you can use your matcher rules to bootstrap your training data.
