### ISSUE TITLE
French Named Entity Extraction issues

### ISSUE THREAD

**Issue by shawn-mccorkell** [explosion/spaCy#1906]
I was playing around with the default French model using your visualizer for Entity Extraction.

I noticed that it has a hard time extracting the Person entities for French. Organization and Location seem pretty accurate.

Is this normal, or just not working in the visualizer? We do plan to train our own models with our data. 

I am trying with this text and I figure the default model should extract Justin Trudeau and Donald Trump.

En plus d'essuyer les tirs nourris de ses adversaires sur les questions d'éthique, Justin Trudeau devra composer avec trois incertitudes tout au long de la session parlementaire qui s'étirera au moins jusqu'à la mi-juin.

Depuis 12 mois, le gouvernement Trudeau multiplie les gestes et les missions aux États-Unis afin de convaincre l'administration de Donald Trump de ne pas déchirer l'Accord de libre-échange nord-américain (ALENA). Mais le président continue de dénoncer cet accord commercial, en vigueur depuis 1994. Il l'a fait encore vendredi durant sa visite éclair à Davos, en Suisse, où avait lieu la semaine dernière le Forum économique mondial. Les nombreuses sorties du président américain ont laissé peu de choix au gouvernement Trudeau.

[Vizualizer Test](https://demos.explosion.ai/displacy-ent/?text=En%20plus%20d%27essuyer%20les%20tirs%20nourris%20de%20ses%20adversaires%20sur%20les%20questions%20d%27%C3%A9thique%2C%20Justin%20Trudeau%20devra%20composer%20avec%20trois%20incertitudes%20tout%20au%20long%20de%20la%20session%20parlementaire%20qui%20s%27%C3%A9tirera%20au%20moins%20jusqu%27%C3%A0%20la%20mi-juin.%0A%0ADepuis%2012%20mois%2C%20le%20gouvernement%20Trudeau%20multiplie%20les%20gestes%20et%20les%20missions%20aux%20%C3%89tats-Unis%20afin%20de%20convaincre%20l%27administration%20de%20Donald%20Trump%20de%20ne%20pas%20d%C3%A9chirer%20l%27Accord%20de%20libre-%C3%A9change%20nord-am%C3%A9ricain%20(ALENA).%20Mais%20le%20pr%C3%A9sident%20continue%20de%20d%C3%A9noncer%20cet%20accord%20commercial%2C%20en%20vigueur%20depuis%201994.%20Il%20l%27a%20fait%20encore%20vendredi%20durant%20sa%20visite%20%C3%A9clair%20%C3%A0%20Davos%2C%20en%20Suisse%2C%20o%C3%B9%20avait%20lieu%20la%20semaine%20derni%C3%A8re%20le%20Forum%20%C3%A9conomique%20mondial.%20Les%20nombreuses%20sorties%20du%20pr%C3%A9sident%20am%C3%A9ricain%20ont%20laiss%C3%A9%20peu%20de%20choix%20au%20gouvernement%20Trudeau.&ents=person%2Corg%2Cloc&model=fr_core_news_sm)

**Comment by ines** [comment]
The visualizer uses the same model(s) available for download with spaCy, so the output should be identical. The French NER was trained on the WikiNER corpus (see: [Learning multilingual named entity recognition from Wikipedia](https://figshare.com/articles/Learning_multilingual_named_entity_recognition_from_Wikipedia/5462500), Nothman et al., 2013), the parser and tagger on the Universal Dependencies Corpus.

If you're working with named entities, training on your own, specific data is definitely important. The entities the model recognises strongly depend on the data it was trained on. Texts on Wikipedia contain a lot of entities – but they're also quite different from news article texts. The recency of the training data can also have an impact. A corpus from 2010 is considered fairly recent – but a model trained on it will not have seen examples of a lot of entities that are pretty relevant today.

"Trump" is also a good example of that. Many English models trained on the standard corpora often tend to tag it as an `ORG` instead of a `PERSON`, because the data they were trained on contained more mentions of Trump hotels and other business ventures, and fewer mentions of the person (which is very different from the usage of that entity today).

If you have data available that's close to the texts your model will have to process at runtime, you should be able to update the French model pretty easily, and correct its predictions. You can find examples of this [in the training documentation](https://spacy.io/usage/training). The [`examples/training` directory](https://github.com/explosion/spaCy/tree/master/examples/training) also has a range of scripts available that you can modify and run.

**Comment by shawn-mccorkell** [comment]
Thanks for the detailed explanation, very helpful!
