### ISSUE TITLE
Universal PRON tag.

### ISSUE THREAD

**Issue by Terrilocks** [explosion/spaCy#191]
Hiya,

I was just wondering if there was any reason you deviated from the Universal Tagset by changing PRP and other pronoun tags to NOUN rather than PRON.
In fact I noticed some other changes that are different from Petrov et al.'s original proposal in lang_data/en/tag_map.json too.

Is this intended?

Thanks,
Chris

**Comment by honnibal** [comment]
Hey,

I first used the Google Universal Tags, and then updated to the Stanford Universal ones. I guess this slipped through, I didn't notice this tag was written differently. I'll fix it, thanks.

**Comment by Terrilocks** [comment]
Ok np.

I'd not looked at the Stanford one before, but read it's no longer just a 1:1 mapping from old to new POS tags, but rather relies on additional syntactic context: (https://mailman.stanford.edu/pipermail/java-nlp-user/2014-September/006335.html).

Currently I am just using your POS-tagger, but does this mean I need to parse too to get the syntactic information for the more accurate POS tags?
I see you also put some of the Universal Features in the tag_map.json too. Is there any way to access these for a particular token?

Thanks again and keep up the good work!
Chris

**Comment by honnibal** [comment]
Bear in mind that you can always use the PTB tags, via the `token.tag` and `token.tag_` attribute.

The lack of 1-to-1 mapping is sort of troubling =/. The thing is, the tagger should really be trained to predict fine-grained, language-specific tags. They can be leaned more accurately and they make better features for downstream tasks. I like the idea of supporting the coarse-grained representation. But I don't want to learn a model just to do that.

**Comment by Terrilocks** [comment]
Yup, I have been using the PTB tags as well; e.g. to catch pronouns.

I also like the idea of the coarse-grained tags (and in fact that was one of the reasons I chose spaCy!) but it does seem like a lot of extra effort to get the Stanford Universal tags. Unfortunately, I'm now noticing quite a lot of differences between your current Stanford mapping file and the one on their website (https://universaldependencies.github.io/docs/tagset-conversion/en-penn-uposf.html) which it also warns is "only an approximation".

Tbh, I'd probably just prefer the simpler 1:1 Google Universal tags, even if they aren't quite as good as the Stanford ones.

Chris

**Comment by jli05** [comment]
Would prefer the Stanford ones. They're regularly maintained and updated.

**Comment by Terrilocks** [comment]
So would I if they were easy to implement. 
As it is however, there are problems with the v0.97 Stanford Universal Tags which might not be easy to fix. So we have a choice between the older but more consistent Google tags or the newer but more complicated Stanford tags. 
Ultimately, I don't know how much difference it'll make, but missing a universal PRON tag in the current Stanford version (amongst other things) seemed like a big deal...

**Comment by jli05** [comment]
It seems PRON tag exists in v1.2? I think most people just use PTB but if one crosses over to multi-lingual parsing I personally like much the fact that UD is regularly released though the data is not much yet.

**Comment by bdewilde** [comment]
On (I think) a related note, would you consider also adding the PROPN (proper noun) universal tag? I know that corresponds to NNP or NNPS in PTB, but for other languages and general convenience, it would be great to have in the `.pos` and `.pos_` attributes.

**Comment by honnibal** [comment]
Finally fixed this. Sorry about letting this slip through the cracks for so long!

**Comment by Terrilocks** [comment]
Sorry to rain on your parade, but the tag_map.json still doesn't look like the one on the Stanford website, although you fixed a couple of them:
http://universaldependencies.org/tagset-conversion/en-penn-uposf.html

1. You have an extra pos "", maybe by design
"\"\"": {"pos": "punct", "puncttype": "quot", "punctside": "fin"},
2. NIL doesn't go to anything in spacy
"NIL": {"pos": ""},
It goes to X in Stanford.
3. PDT goes to ADJ in spacy, but DET in Stanford.
4. PRP$ goes to ADJ in spacy, but DET in Stanford.
5. WDT goes to ADJ in spacy, but DET in Stanford.
6. WP goes to NOUN in spacy, but PRON in Stanford.
7. WP$ goes to ADJ in spacy, but DET in Stanford.
8. AFX is mentioned twice in spacy - once going to ADJ, then going to X
9. HYPH is mentioned twice in spacy - both going to PUNCT, but the first has extra detail.
10. There are several other tags on the end of the file not in the Stanford list; SP, ADD, NFP, GW, XX, BES and HVS.

If you make these changes, I'll definitely start using the coarse tags in spacy, but until then, I'm still using my own mapping. 
Also, when you change this file, are they immediately updated in spacy? I know I'll probably have to do more general update, but will that be immediate or do I have to wait for the next release?

**Comment by honnibal** [comment]
Thanks. I keep getting confused here, because the names of these things are very similar and the contents overlap so much. I also keep sliding between talking about what spaCy is *doing currently*, and discussing what we *should* be doing.

Let's set focus on what we should do. Here are some things I think we want:

* We want to learn fine-grained tags in the statistical model
* We want coarse grained tags available in the API
* We want the coarse tags to follow a standard. We don't want *half* a standard.

Here are some smaller considerations:

* We'd like to produce the coarse tags from a deterministic mapping (not a model)
* The Stanford set has better adoption by others.
* The Stanford tags are a bit more complete/useful

As much as I'd like to support the Stanford scheme, I think it's a higher priority to have a simple mapping. So I propose that the policy is we're using the Google scheme. At some point in future I'd like to switch to full universal dependencies support, but for now I think it's better to be clear about the tag mapping.

If we follow this policy, we'll revert the change I just made to the tag map, and avoid using the `PROPN` tag. It's easy to fix the lemmatizer in another way.

Thoughts? @wbwseeker , I know you're advocating for eventual adoption of UD. What are your thoughts on how we should do the coarse grained mapping at the moment? Is the Google Universal Tag Set okay for German?

**Comment by wbwseeker** [comment]
Why don't we just adopt the tag set defined by UD?: http://universaldependencies.org/u/pos/index.html
It is based on the Google Tag Set but was improved and people work on it. I don't understand why the Google Tags are supposed to be simpler than UPOS. It is just less of them, and noone actively works on it anymore because it was superseded by UPOS.

Looking at http://universaldependencies.org/tagset-conversion/en-penn-uposf.html, it just defines a mapping from Penn Treebank Tags to UPOS. I would advocate for using this mapping. (I can understand if we want to wait to adopt the syntactic annotation, because this is still changing. But this isn't the case for the POS tags)

For German, I already use UPOS in the tagmap.json.

We will have to add some tags to deal with stuff that UD doesn't annotate. Like space tokens. But as long as we just add and don't change, this won't matter.

**Comment by Terrilocks** [comment]
I think the issue is that the real UD mapping is not 1:1 and requires additional information, e.g. lemmas.

That said, I do prefer some of the mappings in the approximated UPOS scheme over the Google one, so am now leaning more towards that. Also, I wouldn't think of the approximation as a half standard, but rather a simplified version of a full standard. By the very fact that it's available, there must be some demand for it, right?

**Comment by syllog1sm** [comment]
Okay. UD it is. We'll use the suggested mapping.

@wbwseeker , would you be able to take care of this? I think we need the following:

1. Fix the English `tag_map.json`
2. Fix the data in `spacy/attrs.pyx`, `spacy/attrs.pxd`, `spacy/symbols.pyx`, `spacy/symbols.pxd`
3. Fix the docs for `Token.pos`
4. Fix the explanation in the annotation specs

**Comment by wbwseeker** [comment]
sure, no problem.
