### ISSUE TITLE
Speed up training process

### ISSUE THREAD

**Issue by melalonso** [explosion/spaCy#1923]
Hello!
I've been reading and using spaCy for some days and I can say it's pretty nice and easy to use. Now I'm looking to train a blank model with my data. I have already ran some low size tests and realized (as I though) that it takes a while to complete (obviuosly depending on the amount of data/iterations...).

What I want to do now is train a model using some hundred of thousands of records and for that I'm looking for a way to speed up the process like multithreading or something. 

I wanted to know what would be the advice you can give me for the described task?

Thanks in advance!

## Your Environment

* **Python version:** 2.7.12
* **Platform:** Windows-10-10.0.15063
* **spaCy version:** 2.0.5
* **Models:** en

**Comment by honnibal** [comment]
I'm always interested in making training faster, and currently I'm not very well satisfied by how it parallelises. So I'm not sure I'll have helpful advice.

One thing you'll want to check is that your numpy is linked against a well optimized BLAS library, which provides the linear algebra routines (where all the time is spent). If you've installed spaCy via conda, then by default you should have a numpy linked against the Intel MKL library. However, if you've installed spaCy via pip, you might have numpy linked against a much slower BLAS library.

**Comment by melalonso** [comment]
Nice to know that. I'll install it using conda and give it a try. Thanks @honnibal

**Comment by jamesdunham** [comment]
Thanks for that suggestion.

I learned that in [`spacy.cli.train.train()`](https://github.com/explosion/spaCy/blob/master/spacy/cli/train.py#L122) the full model is written to disk and then read back again between each iteration. I expect there's a good reason for this generally. Is it avoidable under any circumstances?

I noticed it because I had a PhraseMatcher component that was slow to load. Each time it was recreated from its factory (after each iteration, when the model was read from the disk) it would slowly reload its patterns. The quick solution is of course "don't make it do that" -- and then training is fast enough in my case.

In general, say with vector-heavy models, is this save-load step strictly necessary?

```
with nlp.use_params(optimizer.averages):
    nlp.to_disk(epoch_model_path)
    nlp_loaded = util.load_model_from_path(epoch_model_path)
    # do stuff with nlp_loaded instead of nlp
```

**Comment by honnibal** [comment]
@jamesdunham It's just a convenience to help you resume training from different points, and to pick the best epoch. One solution might be to change it to only serialize if the model hits a new best?
