### ISSUE TITLE
Token.set_extension function fails

### ISSUE THREAD

**Issue by kokbe** [explosion/spaCy#1943]
I'm trying to add a custom extension to my Tokens.  The example code fails:

```
Token.set_extension('is_fruit', default=True)
print(Token.has_extension('is_fruit'))
assert Token._.is_fruit
```

## Output
```
False
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-bf9627311e48> in <module>()
      2 Token.set_extension('is_fruit', default=True)
      3 print(Token.has_extension('is_fruit'))
----> 4 assert Token._.is_fruit

AttributeError: 'getset_descriptor' object has no attribute 'is_fruit'
```

## Info about spaCy

* **spaCy version:** 2.0.7
* **Platform:** Darwin-17.4.0-x86_64-i386-64bit
* **Python version:** 3.6.4
* **Jupyter version:** 4.4.0
* **package**:     en_core_web_sm        2.0.0      
* **package**:      en_core_web_lg        2.0.0

**Comment by ines** [comment]
Ah, spaCy should probably show a better error message here and now that I look at it, maybe [the examples](https://spacy.io/usage/processing-pipelines#custom-components-attributes) are a little confusing! 

The problem is that you're trying to retrieve the extension attribute on the *global* `Token` class instead of an individual token. While the attribute is *registered* globally, it only really makes sense to call it on an individual instance, for example:

```python
Token.set_extension('is_fruit', default=True)

doc = nlp(u"a yellow banana")
token = doc[2]
assert token._.is_fruit
```

This is probably even more obvious when using getters that depend on the token text:

```python
is_fruit_getter = lambda token: token.text in ['apple', 'pear', 'banana', 'orange', 'strawberry']
Token.set_extension('is_fruit', getter=is_fruit_getter)

doc = nlp(u"a yellow banana")
assert doc[2]._.is_fruit
assert not doc[1]._.is_fruit
```

**Comment by kokbe** [comment]
Ah, there we are.  Thank you!

**Comment by kokbe** [comment]
Ah, there it is.  Thank you!
