### ISSUE TITLE
Need for AUX lemmatization

### ISSUE THREAD

**Issue by mosynaq** [explosion/spaCy#1944]
## Problem
I'm almost done with basics for Adding Persian to spaCy. But in Persian auxiliary verbs do inflect so they have lemmas too. But since they are irregular, the lemmatization process should be done in exception approach. For this reason, I made a `_auxs_irreg.py` in `lemmatizer` directory of my Persian model directory (I work independently from the official Persian directory in `lang`. I made one for my needs). Although I followed every step for auxiliary lemmatization like verb/adj/noun/adv in English directory in `lang` directory, spaCy does not seem to do anything to lemmatize auxiliary verbs.

```python
#spacy/lang/fa/lemmatizer/_auxs_irreg.py
# coding: utf8
from __future__ import unicode_literals


AUXS_IRREG = {
    "خواهم": ("خواست#خواه",),
    "خواهی": ("خواست#خواه",),
    "خواهد": ("خواست#خواه",),
    "خواهیم": ("خواست#خواه",),
    "خواهید": ("خواست#خواه",),
    "خواهند": ("خواست#خواه",),

}
```
```python
#spacy/lang/fa/lemmatizer/__init__irreg.py
# coding: utf8
from __future__ import unicode_literals

from .lookup import LOOKUP
from ._nouns_irreg import NOUNS_IRREG
from ._verbs_irreg import VERBS_IRREG
from ._auxs_irreg import AUXS_IRREG
from ._lemma_rules import ADJECTIVE_RULES, NOUN_RULES, PUNCT_RULES 

LEMMA_EXC = {'noun': NOUNS_IRREG, 'verb': VERBS_IRREG, "aux": AUXS_IRREG}

LEMMA_RULES = {'adj': ADJECTIVE_RULES, 'noun': NOUN_RULES, 'punct': PUNCT_RULES}

```

```python
# coding: utf8
#spacy/lang/fa/__init__.py
from __future__ import unicode_liter
.
.
.
from .lemmatizer import LEMMA_RULES, LEMMA_EXC
class PersianDefaults(Language.Defaults):
.
.
.

    lemma_exc = LEMMA_EXC
.
.
.
```
## Question
Does spaCy have the ability to lemmatize auxiliary verbs at all? If yes, what is the problem with my work?

## Info about spaCy

* **Python version:** 2.7.12 and 3.5
* **Platform:** Linux-4.13.0-32-generic-x86_64-with-LinuxMint-18.3-sylvia
* **spaCy version:** 2.0.7
* **Models:** en, fa

**Comment by honnibal** [comment]
Hey,

Sorry for not getting back to you on this. I remember seeing your issue at the time and thinking I should make you a nice reply. Unfortunately I couldn't immediately think of a nice answer because the morphology and lemmatization support has not been very satisfying, so there wasn't really a simple way to solve your problem.

I'm now close to merging support for full lexical attributes, and we have a proper lemmatization system for Spanish being implemented. So, this should finally start to work properly soon. Anyway. I'm sure you've since moved on to other things. Sorry again for not getting back to you.
