### ISSUE TITLE
Matcher.pipe should yield matches instead of Doc objects

### ISSUE THREAD

**Issue by meshiguge** [explosion/spaCy#1951]
## Your Environment

* Operating System: Osx 
* Python Version Used: 2.7 
* spaCy Version Used:  2.0.0 
* Environment Information: en 

why the return of matcher.pipe is doc, rather than " A list of (match_id, start, end) tuples"?  
how can I get` (match_id, start, end)`? 
 ```python 
from spacy.matcher import Matcher
matcher = Matcher(nlp.vocab)
for doc in matcher.pipe(texts, batch_size=50, n_threads=4):
    pass
```

**Comment by honnibal** [comment]
You're right, this is inconsistent with the `Matcher.__call__, and not very useful.

You can get the function you want with:

```python

def pipe_matcher(matcher, docs):
    for doc in docs:
        matches = matcher(doc)
        yield matches
```

Or in one line, `doc_matches = (matcher(doc) for doc in docs)`

**Comment by ines** [comment]
I agree, it'd definitely be more consistent if `Matcher.pipe` returned a generator of the matches. So instead of this we can simply `yield self(doc)`.

https://github.com/explosion/spaCy/blob/37b9be2acd2d0573ea5abe42b7730f542ace90e8/spacy/matcher.pyx#L352-L354

The only problem at the moment is that this would break backwards compatibility – so we might not want to introduce the new behaviour as part of a point release.

**Comment by ines** [comment]
Merging this with the master issue #1971!
