### ISSUE TITLE
out-of-vocab word vector

### ISSUE THREAD

**Issue by azarezade** [explosion/spaCy#1995]
I tried to replicate the following example in the documentation 
```
doc1 = nlp(u"The labrador barked.")
doc2 = nlp(u"The labrador swam.")
doc3 = nlp(u"the labrador people live in canada.")

for doc in [doc1, doc2, doc3]:
    labrador = doc[1]
    dog = nlp(u"dog")
    print(labrador.similarity(dog))
``` 
But the results  seems unstable, and random! 
For example when I use `labrador.similarity(nlp(u"fish))` the scores are:
```
0.2871612403191748
0.2555703787943993
0.2287061682301807
```
More importantly, when I used a Persian model (that have word vectors) it return zero for out-of-vocab vector, in any sample sentences!

## Environment
* Operating System:  Mac OS X
* Python Version Used: 3.6
* spaCy Version Used: 2.0.7

**Comment by r-wheeler** [comment]
The out of word vector will always be an N dimensional vector of 0s. That is how OOV is represented. All the behaviors you are listing are the expected behaviors.

**Comment by azarezade** [comment]
But I used the example in [doc](https://spacy.io/usage/vectors-similarity), and there the results for `dog` are:
```
0.56
0.48
0.39
```

**Comment by azarezade** [comment]
@honnibal, @ines: Can you help me with this issue?

**Comment by giannisdaras** [comment]
I reproduced your experiment and from what I can understand your nlp object is not derived from a model shipped with word vectors. 

From the [documentation](https://spacy.io/usage/vectors-similarity):

> To make them compact and fast, spaCy's small models (all packages that end in sm) don't ship with word vectors, and only include context-sensitive tensors. This means you can still use the similarity() methods to compare documents, spans and tokens – but the result won't be as good, and individual tokens won't have any vectors assigned. So in order to use real word vectors, you need to download a larger model.

I got the same results with you when using the en_core_web_sm model (which doesn't have word vectors) so I guess this is the one you loaded in order to get your nlp object. 

However, if you use the en_core_web_lg model, shipped with word vectors, the results will be really good.

Demo code:
```
import spacy
nlp = spacy.load('en_core_web_lg')
nlp_no_vec = spacy.load('en_core_web_sm')
text = "The labrador barked happily"
target_text = "fish"
print(nlp(text)[1].similarity(nlp(target_text)))
print(nlp_no_vec(text)[1].similarity(nlp_no_vec(target_text)))

target_text = "dog"
print(nlp(text)[1].similarity(nlp(target_text)))
print(nlp_no_vec(text)[1].similarity(nlp_no_vec(target_text)))
```

Results:
0.22873752839097639
0.29173092687239494
0.6349026162074578
0.3774825475372302


So, the model shipped with vectors works fine on that task.


Hope it helps :)

**Comment by azarezade** [comment]
thanks @giannisdaras, dose the `en_core_web_lg` model already has "labrador" in its vocabulary?
If yes, do you get the same results with another OOV word like "xyxxyz" instead of "labrador"?

**Comment by honnibal** [comment]
I would guess `en_core_web_lg` would have `"labrador"`, yes. Unknown words will get a 0 vector if a static word vector table is loaded.
