### ISSUE TITLE
Strange Matcher behavior with * quantifier and two rules

### ISSUE THREAD

**Issue by litemotif** [explosion/spaCy#2005]
I'm not sure why these two rules are resulting in a match on the given text. Is this a bug or am I doing something wrong?

```
nlp = spacy.load('en')
doc = nlp("I took out the trash.")
matcher = Matcher(nlp.vocab)
matcher.add("rule1", None, [
	{'TAG': 'VBD'},
	{'LOWER': 'the'},
	{'POS': 'NOUN'}
])
matcher.add("rule2", None, [
	{'TAG': 'VBD'},
	{'IS_ALPHA': True, 'OP': '*'},
	{'LOWER': 'any'},
	{'LOWER': 'words'}
])
matches = matcher(doc)
for (match_id, start, end) in matches:
	span = doc[start:end]
	
	label = doc.vocab.strings[match_id]
	
	print(label)
	print(str(span))
```

The result is a match on rule 1:

```
rule1
took out the trash
```

But rule 1 shouldn't allow the word "out." Removing either rule results in no matches.

## Your Environment
* Operating System: macOS 10.13.3
* Python Version Used: 3.6.4
* spaCy Version Used: 2.0.8

**Comment by ines** [comment]
Thanks for your report – this issue has since been fixed on the [`feature/better-faster-matcher`](https://github.com/explosion/spaCy/tree/feature/better-faster-matcher) branch. It will be included in the upcoming `v2.1.0`, together with various other improvements and bug fixes to the matcher. For more details on this, check out the `Matcher` master issue in #1971.

(Closing this and merging with #1971 to keep things in one place!)
