### ISSUE TITLE
Batch Heuristic:What needs to be passed in def get_batches(train_data, model_type)

### ISSUE THREAD

**Issue by soumya252** [explosion/spaCy#2013]
Hello @honnibal  @ines  ,

I have a Windows system, I am working on python 3 , and spacy 2. RAM is 4GB on my system.
Hence ,whenever I try to run and train my NER model with spacy, python crashes.So for this purpose I was looking into the batch processing method specified on the Spacy documentation pages.

The function for the same which is given below:

```python
def get_batches(train_data, model_type):
    max_batch_sizes = {'tagger': 32, 'parser': 16, 'ner': 16, 'textcat': 64}
    max_batch_size = max_batch_sizes[model_type]
    if len(train_data) < 1000:
        max_batch_size /= 2
    if len(train_data) < 500:
        max_batch_size /= 2
    batch_size = compounding(1, max_batch_size, 1.001)
    batches = minibatch(train_data, size=batch_size)
    return batches
```

I would like to understand what these parameters are ,what needs to be passed
into **get_batches(train_data, model_type)**  ?

I am stuck as to what needs to be passed into model_type.

**Comment by ines** [comment]
Sorry for only getting to this now. If you look at the function, you'll see that the `model_type` argument you're passing in will be looked up in the dictionary `max_batch_sizes`. This means it should be one of the keys of that dictionary: `'tagger'`, `'parser'`, `'ner'` or `'textcat'`.

If you pass in the model type `'ner'`, a maximum batch size of `16` will be used. 

>  I am working on python 3 , and spacy 2. RAM is 4GB on my system.

4GB RAM might not be enough – if it isn't, the compounding batches won't help, either. This strategy mostly exists to improve training results, not to reduce memory usage. However, lowering the batch size in general may help. You should also make sure to stream in your data, e.g. as a generator, instead of reading it in all at once.
