### ISSUE TITLE
Conjugation tag is being lemmatized: also becomes conjurer

### ISSUE THREAD

**Issue by masscognition** [explosion/spaCy#2063]
The word "also" becomes "conjurer" when lemmatized. Obviously the conjugation tag is being lemmatized not the word. Try this:

>>> import spacy
>>> nlp = spacy.load('en')
>>> pdoc = nlp("this is also three times also also")
>>>pdoc = nlp(u"this is also three times also also")
>>>for ii in pdoc: 
>>>      print ii.lemma_

You get:

this
be
conjurer
three
time
conjurer
conjurer

## Your Environment

* Operating System:  Ubunutu 16.04 LTS
* Python Version Used: 2.7.12
* spaCy Version Used: 2.0.3
* Environment Information:

**Comment by DuyguA** [comment]
I'm on Ubuntu 17.04 Zesty and Python 2.7.13. I was unable to reproduce the bug I also tried on my CentOS developer instance, both with Python2 and Python3 and unable to produce this bug.

**Comment by masscognition** [comment]
Hmm. It reproduces every time for me. You have slightly different OS and Python versions, I know it is VERY unlikely this is the cause but....

I will try it with 2.7.13 and see if it reproduce. Thx.

**Comment by DuyguA** [comment]
I think I found the cause.

@ines  , would it be possible to check  lang/en/lookup.py ? 

`also` is in adverbs list, but somehow  in lookup.py its lemma is `conjurer' ? :)

**Comment by ines** [comment]
Thanks a lot for the report and fix! 👍 

Looks like the lemmatization table we're using contained this typo, and it was ported over. Very strange. Since `v2.0.3`, we've also improved the way lemmas are set in English (rules based on POS tags first if a tagger is available, then lookup table). This also explains why the weird behaviour wasn't reproducable in the latest version (where spaCy correctly uses the POS tag to determine the lemma).

**Comment by DuyguA** [comment]
I viewed the file history, I don't have a clue how that line came :)
Yesterday I made a  awk + grep to check other lemmas. Rest of the file looks normal, only this line contains a typo somehow.
