### ISSUE TITLE
CLI Train command throws a error irrespective of giving all the flags and data correctly

### ISSUE THREAD

**Issue by ghost** [explosion/spaCy#2068]
C:\Users\karth>python -m spacy train en "C:\Users\karth\AppData\Local\Programs\Python\Python35\Lib\site-packages\law_md" "E:\Office files\Python\output\sections.json" "E:\Office files\Python\output\output.json" -n 15 -P -T -v "C:\Users\karth\AppData\Local\Programs\Python\Python35\Lib\site-packages\en_vectors_web_lg\en_vectors_web_lg-2.0.0"

dropout_from = 0.2 by default
dropout_to = 0.2 by default
dropout_decay = 0.0 by default
batch_from = 1 by default
batch_to = 16 by default
batch_compound = 1.001 by default
max_doc_len = 5000 by default
beam_width = 1 by default
beam_density = 0.0 by default
learn_rate = 0.001 by default
optimizer_B1 = 0.9 by default
optimizer_B2 = 0.999 by default
optimizer_eps = 1e-08 by default
L2_penalty = 1e-06 by default
grad_norm_clip = 1.0 by default
Traceback (most recent call last):
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\cli\train.py", line 114, in train
    optimizer = nlp.begin_training(lambda: corpus.train_tuples, device=use_gpu)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\language.py", line 465, in begin_training
    **cfg)
  File "nn_parser.pyx", line 829, in spacy.syntax.nn_parser.Parser.begin_training
  File "ner.pyx", line 88, in spacy.syntax.ner.BiluoPushDown.get_actions
ValueError: U--

## Your Environment

* Operating System: Windows-10-10.0.16299-SP0
* Python Version Used: 3.5.4
* spaCy Version Used: 2.0.9
* Environment Information: windows cmd

**Comment by ines** [comment]
Sorry for only getting to this now. Looking at the error message, it seems like there's a problem with one (or more) of your labels:

```
ValueError: U--
```

The relevant code path you're hitting is here:

https://github.com/explosion/spaCy/blob/9e83513004ed1c9509389208aaa611360d46e266/spacy/syntax/ner.pyx#L86-L88

So for some reason, your data ends up producing a `U--` (single-token entity with label `-`). Is it possible that your data contains tokens that are supposed to be marked as outside an entity (`O`), but are labelled as `-` instead?

**Comment by karthik168** [comment]
@ines Thanks for the reply,
As you specified in the above suggeston , i went through the file, and yes there were U tags instead of '-'

**Comment by karthik168** [comment]
This is how my conll file looks:
-DOCSTART- -X- O O
of -X- _ O
their -X- _ O
powers -X- _ O
under -X- _ O
section -X- _ B-LAW
9 -X- _ I-LAW
( -X- _ I-LAW
1-A -X- _ I-LAW
) -X- _ L-LAW
of -X- _ O
the -X- _ O
Madras -X- _ O

-DOCSTART- -X- O O
The -X- _ O
impugned -X- _ O
Act -X- _ O
was -X- _ O
passed -X- _ O
by -X- _ O
the -X- _ O
Provincial -X- _ O
Legisla -X- _ O
- -X- _ O
ture -X- _ O
in -X- _ O
exercise -X- _ O
of -X- _ O
the -X- _ O
power -X- _ O
conferred -X- _ O
upon -X- _ O
it -X- _ O
by -X- _ O
section -X- _ B-LAW
100 -X- _ I-LAW
of -X- _ I-LAW
the -X- _ I-LAW
Government -X- _ I-LAW
of -X- _ I-LAW
India -X- _ I-LAW
Act -X- _ I-LAW
1935 -X- _ L-LAW
, -X- _ O
read -X- _ O
with -X- _ O
Entry -X- _ O
1 -X- _ O

-DOCSTART- -X- O O
Section -X- _ B-LAW
3 -X- _ I-LAW
of -X- _ I-LAW
the -X- _ I-LAW
Finance -X- _ I-LAW
Act -X- _ I-LAW
1950 -X- _ I-LAW
( -X- _ I-LAW
Act -X- _ I-LAW
XXV -X- _ I-LAW
of -X- _ I-LAW
1550 -X- _ I-LAW
) -X- _ L-LAW
made -X- _ O
certain -X- _ O
amendments -X- _ O
in -X- _ O
the -X- _ O
Indian -X- _ O
Income -X- _ O
- -X- _ O
tax -X- _ O
Act -X- _ O
with -X- _ O
effect -X- _ O

**Comment by ines** [comment]
Thanks for updating – looks like you're getting closer to solving this issue. 

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 15428: invalid start byte

Looks like there's a problem with the encoding – does [changing the encoding when opening the file](https://stackoverflow.com/questions/19699367/unicodedecodeerror-utf-8-codec-cant-decode-byte) help? The source of the converter is in [`cli/converters/conllu2json.py`](https://github.com/explosion/spaCy/blob/master/spacy/cli/converters/conllu2json.py) and you might want to look at the following:

```
\conll_ner2json.py", line 26, in read_conll_ner
text = input_path.open('r', encoding='utf-8').read()
```

**Comment by karthik168** [comment]
@ines Thanks for such an early reply 
changing the encoding attribute definitely worked. But in turn its giving a new error
C:\Users\karth>python -m spacy convert "E:\Office files\Python\section.conll" "E:\Office files\Python\Output" -c ner
Traceback (most recent call last):
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\cli\convert.py", line 45, in convert
    n_sents=n_sents, use_morphology=morphology)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\cli\converters\conll_ner2json.py", line 14, in conll_ner2json
    docs = read_conll_ner(input_path)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\cli\converters\conll_ner2json.py", line 40, in read_conll_ner
    words, tags, chunks, iob_ents = zip(*[line.split() for line in lines])
ValueError: not enough values to unpack (expected 4, got 3)

**Comment by ines** [comment]
Try printing the line in question and see if anything looks suspicious here? It's possible that there's one line in your data that's shorter than the others.

Considering the errors are now more around the conversion, it's likely that it comes down to some inconsistency in your data. So you might have to experiment a bit, add a few print statements and debug the data and conversion.

**Comment by KarthikPunyamurthy** [comment]
@ines Thank you for the suggestion given for the conversion, apologies for changing the account
The conversion for nerjson was successful, and the problem was due to the inconsistency in the data 

However the train command throws a error even after giving the right format of data input

The error ;

C:\Users\karth>python -m spacy train en "C:\Users\karth\AppData\Local\Programs\Python\Python35\Lib\site-packages\law2" "E:\Office files\Python\Output\section.json" -n 10
usage: spacy train [-h] [-n 30] [-ns 0] [-pt] [-et] [-g -1] [-v None] [-T]
                   [-P] [-N] [-G] [-V 0.0.0] [-m None]
                   lang output_dir train_data dev_data
spacy train: error: the following arguments are required: dev_data

C:\Users\karth>python -m spacy train en "C:\Users\karth\AppData\Local\Programs\Python\Python35\Lib\site-packages\law2" "E:\Office files\Python\Output\section.json" "E:\Office files\Python\Output\section.json" -n 10
dropout_from = 0.2 by default
dropout_to = 0.2 by default
dropout_decay = 0.0 by default
batch_from = 1 by default
batch_to = 16 by default
batch_compound = 1.001 by default
max_doc_len = 5000 by default
beam_width = 1 by default
beam_density = 0.0 by default
beam_width = 1 by default
beam_density = 0.0 by default
learn_rate = 0.001 by default
optimizer_B1 = 0.9 by default
optimizer_B2 = 0.999 by default
optimizer_eps = 1e-08 by default
L2_penalty = 1e-06 by default
grad_norm_clip = 1.0 by default
embed_size = 7000 by default
token_vector_width = 128 by default
parser_hidden_depth = 1 by default
parser_maxout_pieces = 2 by default
token_vector_width = 128 by default
hidden_width = 200 by default
embed_size = 7000 by default
history_feats = 0 by default
history_width = 0 by default
parser_hidden_depth = 1 by default
parser_maxout_pieces = 2 by default
token_vector_width = 128 by default
hidden_width = 200 by default
embed_size = 7000 by default
history_feats = 0 by default
history_width = 0 by default
Itn.    P.Loss  N.Loss  UAS     NER P.  NER R.  NER F.  Tag %   Token %
  0%|                                                                                         | 0/2976 [00:00<?, ?it/s][(0, 'On', '-X-', 0, 'ROOT', 'O'), (1, 'behalf', '-X-', 1, 'ROOT', 'O'), (2, 'of', '-X-', 2, 'ROOT', 'O'), (3, 'the', '-X-', 3, 'ROOT', 'O'), (4, 'the', '-X-', 4, 'ROOT', 'O'), (5, 'appellant', '-X-', 5, 'ROOT', 'O'), (6, 'it', '-X-', 6, 'ROOT', 'O'), (7, 'was', '-X-', 7, 'ROOT', 'O'), (8, 'pointed', '-X-', 8, 'ROOT', 'O'), (9, 'out', '-X-', 9, 'ROOT', 'O'), (10, 'that', '-X-', 10, 'ROOT', 'O'), (11, 'under', '-X-', 11, 'ROOT', 'O'), (12, 'section', '-X-', 12, 'ROOT', 'B-LAW'), (13, '42"(3', '-X-', 13, 'ROOT', 'I-LAW'), (14, ')', '-X-', 14, 'ROOT', 'I-LAW'), (15, 'of', '-X-', 15, 'ROOT', 'I-LAW'), (16, 'the', '-X-', 16, 'ROOT', 'I-LAW'), (17, 'Indian', '-X-', 17, 'ROOT', 'I-LAW'), (18, 'Income', '-X-', 18, 'ROOT', 'I-LAW'), (19, '-', '-X-', 19, 'ROOT', 'I-LAW'), (20, 'tax', '-X-', 20, 'ROOT', 'I-LAW'), (21, 'Act', '-X-', 21, 'ROOT', 'L-LAW'), (22, 'the', '-X-', 22, 'ROOT', 'O'), (23, 'legis', '-X-', 23, 'ROOT', 'O'), (24, '-', '-X-', 24, 'ROOT', 'O'), (25, 'lature', '-X-', 25, 'ROOT', 'O')]
['On', 'behalf', 'of', 'the', 'the', 'appellant', 'it', 'was', 'pointed', 'out', 'that', 'under', 'section', '42"(3', ')', 'of', 'the', 'Indian', 'Income', '-', 'tax', 'Act', 'the', 'legis', '-', 'lature']
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
['ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT', 'ROOT']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Saving model...
Traceback (most recent call last):
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\cli\train.py", line 131, in train
    drop=next(dropout_rates), losses=losses)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\language.py", line 418, in update
    proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
  File "nn_parser.pyx", line 585, in spacy.syntax.nn_parser.Parser.update
  File "nn_parser.pyx", line 768, in spacy.syntax.nn_parser.Parser.get_batch_loss
  File "arc_eager.pyx", line 548, in spacy.syntax.arc_eager.ArcEager.set_costs
ValueError: Could not find a gold-standard action to supervise thedependency parser. The GoldParse was projective. The transition system has 3 actions. State at failure: __0 __0 On_0 | behalf of

**Comment by KarthikPunyamurthy** [comment]
@ines : I have shown a sample of how my training data looks 
{
    "id":0,
    "paragraphs":[
      {
        "sentences":[
          {
            "tokens":[
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"of"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"their"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"powers"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"under"
              },
              {
                "tag":"-X-",
                "ner":"B-LAW",
                "orth":"section"
              },
              {
                "tag":"-X-",
                "ner":"I-LAW",
                "orth":"9"
              },
              {
                "tag":"-X-",
                "ner":"I-LAW",
                "orth":"("
              },
              {
                "tag":"-X-",
                "ner":"I-LAW",
                "orth":"1-A"
              },
              {
                "tag":"-X-",
                "ner":"L-LAW",
                "orth":")"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"of"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"the"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"Madras"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "id":1,
    "paragraphs":[
      {
        "sentences":[
          {
            "tokens":[
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"The"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"impugned"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"Act"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"was"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"passed"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"by"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"the"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"Provincial"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"Legisla"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"-"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"ture"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"in"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"exercise"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"of"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"the"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"power"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"conferred"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"upon"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"it"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"by"
              },
              {
                "tag":"-X-",
                "ner":"B-LAW",
                "orth":"section"
              },
              {
                "tag":"-X-",
                "ner":"I-LAW",
                "orth":"100"
              },
              {
                "tag":"-X-",
                "ner":"I-LAW",
                "orth":"of"
              },
              {
                "tag":"-X-",
                "ner":"I-LAW",
                "orth":"the"
              },
              {
                "tag":"-X-",
                "ner":"I-LAW",
                "orth":"Government"
              },
              {
                "tag":"-X-",
                "ner":"I-LAW",
                "orth":"of"
              },
              {
                "tag":"-X-",
                "ner":"I-LAW",
                "orth":"India"
              },
              {
                "tag":"-X-",
                "ner":"I-LAW",
                "orth":"Act"
              },
              {
                "tag":"-X-",
                "ner":"L-LAW",
                "orth":"1935"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":","
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"read"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"with"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"Entry"
              },
              {
                "tag":"-X-",
                "ner":"O",
                "orth":"1"
              }
            ]
          }
        ]
      }
    ]
  }

ERROR:

C:\Users\karth>python -m spacy train en "C:\Users\karth\AppData\Local\Programs\Python\Python35\Lib\site-packages\law_md2" "E:\Office files\Python\Output\train.json" "E:\Office files\Python\Output\dev.json" -n 10 -P -T -v "C:\Users\karth\AppData\Local\Programs\Python\Python35\Lib\site-packages\en_vectors_web_lg\en_vectors_web_lg-2.0.0"
dropout_from = 0.2 by default
dropout_to = 0.2 by default
dropout_decay = 0.0 by default
batch_from = 1 by default
batch_to = 16 by default
batch_compound = 1.001 by default
max_doc_len = 5000 by default
Load vectors model C:\Users\karth\AppData\Local\Programs\Python\Python35\Lib\site-packages\en_vectors_web_lg\en_vectors_web_lg-2.0.0
beam_width = 1 by default
beam_density = 0.0 by default
learn_rate = 0.001 by default
optimizer_B1 = 0.9 by default
optimizer_B2 = 0.999 by default
optimizer_eps = 1e-08 by default
L2_penalty = 1e-06 by default
grad_norm_clip = 1.0 by default
parser_hidden_depth = 1 by default
parser_maxout_pieces = 2 by default
token_vector_width = 128 by default
hidden_width = 200 by default
embed_size = 7000 by default
history_feats = 0 by default
history_width = 0 by default
Itn.    P.Loss  N.Loss  UAS     NER P.  NER R.  NER F.  Tag %   Token %
Saving model...
Traceback (most recent call last):
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\cli\train.py", line 133, in train
    drop=next(dropout_rates), losses=losses)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\language.py", line 427, in update
    proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
  File "nn_parser.pyx", line 564, in spacy.syntax.nn_parser.Parser.update
  File "nn_parser.pyx", line 684, in spacy.syntax.nn_parser.Parser._init_gold_batch
  File "transition_system.pyx", line 76, in spacy.syntax.transition_system.TransitionSystem.get_oracle_sequence
  File "transition_system.pyx", line 131, in spacy.syntax.transition_system.TransitionSystem.set_costs
ValueError: [E024] Could not find an optimal move to supervise the parser. Usually, this means the GoldParse was not correct. For example, are all labels added to the model?

**Comment by ines** [comment]
@KarthikPunyamurthy Your data looks alright, at least based on your sample. But of course, it's always possible that there's an invalid annotation somewhere down the line. An easy way to debug this is to set the batch size to 1 and print the individual documents, so you can see which one it fails on.

**Comment by KarthikPunyamurthy** [comment]
@ines I also observed that the in iob2json converter the id value does not increment

line 44 :  docs = [{'id': 0, 'paragraphs': [para]} for para in paragraphs]

**Comment by KarthikPunyamurthy** [comment]
@ines the training is working only when i don't load the vectors_web_lg , when i use the word vectors with the -v flag the python crashes. and i also not able to tweak the hyper_parameters from the CLI.

 1) How do i use the hyper_parameters for the train.py script from CLI.

**Comment by KarthikPunyamurthy** [comment]
@ines The train command is crashing when i load the spacy word vectors using the v- flag.
The use of hyper_parameters is also not happening through the command line.
** It either crashes or either takes 4 mins for each iterartion (I am not using GPU) 
Thanks
