### ISSUE TITLE
Spacy 2.0 - Large Corpus saving custom extensions to np_array using to_array method

### ISSUE THREAD

**Issue by justinkreft** [explosion/spaCy#2072]
I am dealing with a sizably massive corpus (around 8 million blog entries, for a total of ~10 GB), and I'm trying to get as much efficiency as possible.  I love the idea of using Spacy as the data structure for ground truth (so much good stuff here. Props to DEVs). I'll admit that this is probably a S.O question (for good measure, [here](https://stackoverflow.com/questions/49159188/spacy-2-0-large-corpus-saving-custom-extensions-to-np-array-using-to-array-met))

My issue is getting a memory friendly version of this corpus. Saving each doc using `spacy.Doc.to_disk` method or even appending bytes using `spacy.Doc.to_bytes` is prohibitive (just 25K docs is nearly .5GB! So my entire corpus of 8 million documents of raw_text (and metadata) would be increased by nearly ~175 GB from ~10GB raw... obviously sub optimal :) ). 

So, I started looking at persisting only those attributes I care about using the `spacy.Doc.to_array` method, but I also have a lot of of custom extensions that I created using `Matcher()` and an `on_match` callback that sets the extension with `set_extension` method. 

Two part issue: 

 1. Most immediately: is it possible to map the custom extensions using `to_array`? 

and/or 

 2. Is there a better way to persist the corpus in a way that is both memory and storage efficient (Am I going about this the wrong way and is there a better way?

Any insight is welcome.  Cheers!

**Comment by honnibal** [comment]
I'm labelling this enhancement because it points to a development goal we had in v2 that got scrapped: a `Binder` class that serialises a group of documents efficiently.

The biggest bloat you'll be seeing from `doc.to_bytes()` will be the `doc.tensor` attribute. If you set that to `None`, you should save a lot of space.

I do think you should try to use the `doc.to_array()` method, though. You could even look into concatenating the arrays and storing an auxiliary array `lengths`, that lets you split them up into the documents. This will let you store it all in one numpy array, so you can use numpy's array compression stuff.

For your custom attributes, you should think through a minimal representation that you can also add as columns to the array. Remember that you can always hash your strings, and then save the `StringStore` separately.

The library itself is in the worst position to come up with an efficient serialisation format for you, because we don't know anything about the redundancies in your data, or what can be calculated cheaply on deserialisation. So you'll really want to do this yourself.

**Comment by justinkreft** [comment]
@honnibal @ines great. thank you very much. 
I appreciate the positive response the the couple of issues I raised. Re: wanting to do it myself with `to_array` I came to that conclusion. Learned quite a bit in the last few weeks working with Spacy and hoping I can continue to contribute where possible :)

**Comment by ines** [comment]
We just released spaCy v2.2 with the new `DocBin` class for efficient binary serialization of `Doc` objects!

Details: https://spacy.io/usage/saving-loading#docs
API: https://spacy.io/api/docbin
