### ISSUE TITLE
influences of Capital and pre-processing

### ISSUE THREAD

**Issue by meshiguge** [explosion/spaCy#2076]
#### influences of Capital and pre-processing 
  'apple' and 'france' with tag of  'NNP',

```python 
doc = nlp(u'Apple is very good in France .')
for t in doc:
    print (t.text, t.tag_ )
# output 
"""
(u'Apple', u'NNP')
(u'is', u'VBZ')
(u'very', u'RB')
(u'good', u'JJ')
(u'in', u'IN')
(u'France', u'NNP')
(u'.', u'.')

"""

```
 use lowercase pre-processing,   'apple' and 'france' become 'NN',   

```python
doc = nlp(u'Apple is very good in france .')
for t in doc:
    print (t.text, t.tag_ )
""" 
(u'apple', u'NN')
(u'is', u'VBZ')
(u'very', u'RB')
(u'good', u'JJ')
(u'in', u'IN')
(u'france', u'NN')
(u'.', u'.')
"""

```
 what is the algorithm of `part-of-speech` tagging in `spacy`?   is it necessary to `lowercase`() in `pre-processing` before `spacy` ?? 

## Your Environment

* Operating System: osx
* Python Version Used: 2.7
* spaCy Version Used: 2
* Environment Information: en

**Comment by ines** [comment]
No, you definitely shouldn't have to change capitalisation before processing text in spaCy – especially not lowercase. The texts you shared is actually a very good example of why capitalisation matters and how spaCy adjusts its predictions based on it:

In "Apple is very good in France .", spaCy predicts both "Apple" and "France" as proper nouns (and also entities). "Apple" in this context is in fact more likely to be referring to the company than to an apple, since it's singular and doesn't have an article. If the sentence is "Apples are very good in France", spaCy predicts "Apples" as `NNS`, i.e. a plural noun.

To answer your other question – you can find more details on spaCy's model architecture here: https://spacy.io/api/#nn-model
