### ISSUE TITLE
AttributeError: module 'spacy' has no attribute 'load'

### ISSUE THREAD

**Issue by snahil** [explosion/spaCy#2078]
C:\Users\snahilindoria\Desktop>1.py
Traceback (most recent call last):
  File "C:\Users\snahilindoria\Desktop\1.py", line 1, in <module>
    import spacy
  File "C:\Users\snahilindoria\Desktop\spacy.py", line 2, in <module>
    nlp = spacy.load('en')
AttributeError: module 'spacy' has no attribute 'load'
![capture](https://user-images.githubusercontent.com/16596896/37192702-c71850fc-231b-11e8-98c6-a82d7beea98b.PNG)

**Comment by ines** [comment]
I think the problem here is quite simple: The file you're loading is called `spacy.py`, so it's shadowing the `spacy` module ([see here](https://spacy.io/usage/#module-load) for more details).

So if you rename your file to something else, it should all work as expected. As a general rule of thumb, we'd recommend to always choose different names and never call anything else `spacy` when working with spaCy.
