### ISSUE TITLE
Statistical training and modeling noun_chunks in lda2vec

### ISSUE THREAD

**Issue by prabhatravib** [explosion/spaCy#2085]
I am running a lda2vec(written by chris moody) example code. I am getting the below error when I run the preprocess statement:
ValueError: noun_chunks requires the dependency parse, which requires a statistical model to be installed and loaded. For more info, see the documentation:
https://spacy.io/usage/models

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by ines** [comment]
Just had a look at the code (I assume you're using [this one](https://github.com/cemoody/lda2vec)?) and it's slightly old and specifies `spacy>=0.9`, so I'm not sure it's still compatible with one of the more recent versions, or even `v1.x`.

However, the error message mostly means that you need to have a statistical model installed and available, so that spaCy is able to get a dependency parse. In pre-`v1.7.0` spaCy, you should be able to install the English model like this:

```bash
python -m spacy.en.download
```
