### ISSUE TITLE
Getting module error

### ISSUE THREAD

**Issue by jayrodge** [explosion/spaCy#2099]
```from preshed.counter import PreshCounter
```
After using two above lines, I'm getting following error, after downloading with ``` python -m spacy.en.download all```:
```
No name 'PreshCounter' in module 'preshed.counter'
```

What is the issue here?
## Your Environment

* Operating System: Ubuntu 16.04
 Python Version Used: 3.5.4
* spaCy Version Used: 2.0.9
* Environment Information:

**Comment by ines** [comment]
This is very confusing! The `spacy.en.download all` command has been deprecated since v1.7.0, so I'm surprised it doesn't fail earlier? Do you see the same problem if you run:

```bash
python -m spacy download en
```

It's very likely you ended up in a weird system state, or that spaCy and its dependencies didn't compile properly. This sometimes happens, and the best solution is to start off with a fresh environment.
