### ISSUE TITLE
html5lib==1.0b8 is required in the 2.0.9 release but not in git repository

### ISSUE THREAD

**Issue by raphael0202** [explosion/spaCy#2100]
html5lib requirement was dropped in this commit: https://github.com/explosion/spaCy/commit/6bba1db4cc41ef22bcba14046b498572019fba3e#diff-b4ef698db8ca845e5845c4618278f29a

However, we can still find `html5lib==1.0b8` in `setup.py` and `requirements.txt` in the 2.0.9 release.
This version of html5lib is incompatible with Tensorflow 1.5.0, which needs `htm5lib==0.9999999`

## Your Environment

* **Platform:** Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 2.0.9
* **Python version:** 3.5.2

**Comment by ines** [comment]
Ah yeah, I think we just pushed `v2.0.9` from a hotfix branch to offer a solution for the msgpack problem. Because it was quite rushed, we didn't port that particular commit over (to not risk breaking something). `v2.1.0` will defintely include that fix, though, and will drop the `html5lib` dependency 🎉

**Comment by raphael0202** [comment]
Great, thanks for the quick response :+1:
