### ISSUE TITLE
Spacy Text Classifier Multi Label Classification

### ISSUE THREAD

**Issue by kkr78** [explosion/spaCy#2105]
Spacy Text Classifier seems like doesn't support **multi-label classification**. In my use case, I got more than 10 labels. I used the code from this [example](https://github.com/explosion/spacy/blob/master/examples/training/train_textcat.py). I explained below all the various combinations that I tried. Results not even close, most of the times it showed different labels with a completely wrong confidence score. If this is a bug, can it be fixed? If Spacy doesn't support, can you please raise enhancement request?  This is certainly going to help a lot of use cases. I came across two other issues with a similar problem 
[issue1](https://github.com/explosion/spaCy/issues/1562)
[issue2](https://github.com/explosion/spaCy/issues/1763)

I added all the labels before the training started and tried various combinations and none of them worked. 

1. trained the data of each label one at a time
2. trained all the data once
3. added only one label to the cats    **Ex:{'cats': {'ThankYou': True}}**
4. added all the labels to the cats with one label being True and others being False Ex:{'cats': {'ThankYou': True, 'FeedBack': False, 'Approve': False}}

**Sample Data**

**Label 1: Approve** 
approve
change approved
i approve
this change is approved.
i approve these changes

**Label 2: ThankYou**
Thx!
Thank you
Great!

**Label 3: FeedBack**
please see my feedback below
can you submit your feedback

etc upto 13 labels

## Info about spaCy

* **spaCy version:** 2.0.9
* **Platform:** Darwin-17.2.0-x86_64-i386-64bit
* **Python version:** 3.6.4

**Comment by honnibal** [comment]
I've tried to reproduce this and haven't been able to. I did find two significant usability traps in the text categorizer, which I'll get to in a moment. But could you check the code here and see if you see something I'm doing that you're not? https://github.com/explosion/spaCy/blob/7dc76c6ff6b51749f39f3fabecee27417a77b1df/spacy/tests/test_textcat.py

The two usability problems are:

1. Resizing the model after training had begun was allowed, but did the wrong thing. The problem is we only resize the last layer, but the model is actually an ensemble. We don't resize the components of the ensemble. This gave the resized model very bad accuracy. I've disabled resizing after training, and added instructions that you should add all labels before training begins.

2. If you use the text classifier with a `Vocab()` object that has no lexical attributes (e.g. if you just call `Vocab()`, the effect is to silently get no features in the text categorizer. This is super bad, but it's currently hard to detect and raise in the relevant bit of code. I'm thinking about how to prevent this problem, although I doubt it's affected too many users, as it only occurs if you create the `Vocab()` object directly, instead of using a `Language()` class.

**Comment by kkr78** [comment]
I tested test_textcat.py and it seems to be working. I went ahead and incorporated my changes with three labels but it doesn't seem to work. Attached are the files and test case, FYR. can you review and see if I am doing anything wrong?

[TestCase.zip](https://github.com/explosion/spaCy/files/1819776/TestCase.zip)

**Data Trained**

[(a c c e p t e d , {'Approve': 1.0, 'Feedback': 0.0, 'Thankyou': 0.0}), (c h a n g e   a c c e p t e d , {'Approve': 1.0, 'Feedback': 0.0, 'Thankyou': 0.0}), (y e s   i   a p p r o v e   t h e s e   c h a n g e s , {'Approve': 1.0, 'Feedback': 0.0, 'Thankyou': 0.0}), (g o   a h e a d , {'Approve': 1.0, 'Feedback': 0.0, 'Thankyou': 0.0}), (p l e a s e   p r o c e e d   w i t h   c h a n g e , {'Approve': 1.0, 'Feedback': 0.0, 'Thankyou': 0.0}), (t h i s   c h a n g e   i s   a c c e p t a b l e , {'Approve': 1.0, 'Feedback': 0.0, 'Thankyou': 0.0}), (a p p r o v e , {'Approve': 1.0, 'Feedback': 0.0, 'Thankyou': 0.0}), (c a n   y o u   p r o v i de   f e e d b a c k   f o r   t h e   f o l l o w i n g   r e q u e s t s , {'Approve': 0.0, 'Feedback': 1.0, 'Thankyou': 0.0}), (f i n d   d e t a i l s   b e l o w , {'Approve': 0.0, 'Feedback': 1.0, 'Thankyou': 0.0}), (w o n d e r f u l   s e r v i c e , {'Approve': 0.0, 'Feedback': 1.0, 'Thankyou': 0.0}), (T h a n k   y o u , {'Approve': 0.0, 'Feedback': 0.0, 'Thankyou': 1.0}), (T h x ! , {'Approve': 0.0, 'Feedback': 0.0, 'Thankyou': 1.0}), (t h a n k   y o u   s o   m u c h , {'Approve': 0.0, 'Feedback': 0.0, 'Thankyou': 1.0}), (m a n y   t h a n k s , {'Approve': 0.0, 'Feedback': 0.0, 'Thankyou': 1.0})]

**Results**

1) Thx! --> 
{
    "Approve": 0.31740695238113403,
    "Feedback": 0.35897892713546753,
    "Thankyou": 0.8873269557952881
}

2) many many thanks -->
{
    "Approve": 0.6577521562576294,
    "Feedback": 0.027387626469135284,
    "Thankyou": 0.046201158314943314
}
3) wonderful
{
    "Approve": 0.6290720701217651,
    "Feedback": 0.024193428456783295,
    "Thankyou": 0.05534748733043671
}

**Comment by kkr78** [comment]
@honnibal I tried different approaches but couldn't figure out how to do this. will you be able to provide some inputs on this?

**Comment by honnibal** [comment]
@kkr78 I think you have general optimization problems: the model isn't learning well because you're passing in all your data in a single batch each time. Try using the `spacy.util.minibatch` function? Even passing one document per batch should be better than all documents in a single batch.
