### ISSUE TITLE
German Lemmatization & Hyphenation

### ISSUE THREAD

**Issue by uniquer4ven** [explosion/spaCy#2120]
Hi,
I am testing the fairly new German lemmatization as actually I urgently need it to be running really good, also on compound words.
Is there any way (any tweaks and options to the lemmatizing function maybe?) that I get things like these lemmatized correctly:
"unterm Tische sponnen klapperdürre Holzwürmer"
=> unter, der, Tisch, spinnen, klapperdürr, Holzwurm
spaCy: unterm, tischen (although recognized as pos_ "NOUN"), sponnen, klapperdürren, Holzwürmer

If not:
I thought of a function hyphenating it in order to check for the parts to be existent, find the lemma for the last part and put it back together. Is there something like that?
Generally, ist there an hyphenation function?

Many thanks

spaCy 2.0.8
Python 3.6 (Anaconda 5.1.0)
Windows 10

**Comment by ines** [comment]
Sorry for only getting to this now. The German lemmatizer currently only uses a [lookup table](https://github.com/explosion/spaCy/blob/master/spacy/lang/de/lemmatizer.py) – that's fine for some cases, but obviously not as good as a solution that takes part-of-speech tags into account.

You might want to check out #2079, which discusses a solution for implementing a custom lemmatizer in French – either based on spaCy's English lemmatization rules, or by implementing a third-party library via a custom pipeline component.

One quick note on the expected lemmatization / tokenization:

>  => unter, der, Tisch, spinnen, klapperdürr, Holzwurm

spaCy's German tokenization rules currently don't split contractions like "unterm". One reason is that spaCy will never modify the original `ORTH` value of the tokens – so `"unterm"` would have to become `["unter", "m"]`, where the token "m" will have the `NORM` "dem". Those single-letter tokens can easily lead to confusion, which is why we've opted to not produce them for now. But if your treebank or expected tokenization requires contractions to be split, you can easily add your own special case rules:

```python
import spacy
from spacy.symbols import ORTH, NORM, LEMMA

nlp = spacy.load('de')

special_case = [{ORTH: 'unter'}, {ORTH: 'm', NORM: 'dem', LEMMA: 'der'}]
nlp.tokenizer.add_special_case('unterm', special_case)
```

Also:

>  tischen (although recognized as pos_ "NOUN"),

This is bad. I think there might be an issue with how the lexemes are looked up in the lemmatization table – in German, spaCy definitely shouldn't just lowercase the text, as this can easily lead to undesired results like this one. Will look into this!

**Comment by uniquer4ven** [comment]
Hi Ines,
is there any soon-to-begin-plan or even progress going on concerning the Lemmatization of composita, a possible hyphenation function and the Lemmatization of words not included in the lookup table?
That would be fabulous.
Regards

**Comment by uniquer4ven** [comment]
Hi,
a quick reply would be very helpful.
Regards

**Comment by ines** [comment]
Sorry, I missed your previous post. We don't have an immediate plan or timeline yet, but we'd definitely love to move from lookup lemmatization to rule-based or statistical lemmatization in the future. (Shipping the tables with spaCy really adds a lot of bloat and it comes with all kinds of other problems.)

**Comment by ines** [comment]
Merging this with the master issue #2486!
