### ISSUE TITLE
EntityRecognizer API documentation inconsistent with actual API

### ISSUE THREAD

**Issue by jfelectron** [explosion/spaCy#2149]
The API documentation for EntityRecognizer indicates that it is a subclass of Pipe, when in fact it is a subclass of Parser.   There is no apparent way to easily get the validation loss of the NER model. It has a pipe method but many of the other Pipe methods such as predict and set_annotations are not preset. 
Furthermore, there are undocumented methods presumably used in Prodigy such as beam_parse and update_beam. 

https://spacy.io/api/entityrecognizer

## Info about spaCy

* **Python version:** 2.7.13
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **spaCy version:** 2.0.9
* **Models:** en

**Comment by honnibal** [comment]
True points --- sorry for the inconvenience.

**Comment by ankitameht** [comment]
If suitable, I would like to contribute to this documentation.

**Comment by honnibal** [comment]
In v2.1 the `Parser` class now has the missing `predict()` and `set_annotations()` methods.

It's true that it's not a subclass of `Pipe`...There's no real way around this, because we need `Parser` to be a C-extension class. I think if we implement the interface of `Pipe` that's enough? It sucks if we fail an `isinstance` check, so maybe we could note the issue.

`Parser` does also have a number of undocumented methods, used for both Prodigy and internals. These parts of the API are harder to use and subject to change...You're welcome to use them if you don't mind your code potentially breaking in future, and you're okay with not having as much support concerning them.
