### ISSUE TITLE
len(nlp.vocab) is unexpectedly different when using different load methods

### ISSUE THREAD

**Issue by justinkreft** [explosion/spaCy#2153]
When loading a model from disk, the `len(nlp.vocab)` does not appear to remain consistent. Discovered this when messing around with loading/saving models (#2083), and although I discovered that the final method of loading  ( `spacy.load('en').from_disk(cwd + '/spacy_model')` ) is not appropriate from @ines, it is still surprising that the length of the vocab differs on loading.  At her request, I'm opening this issue.

Specifically 1) why does a base 'en' model have less vocab before it is sent `to_disk` and 2) although it is incorrect way of loading, why does the vocab length double when using `spacy.load('en').from_disk(cwd + '/spacy_model')`.

See code to reproduce below. Thanks :)

```
import spacy
from spacy.language import Language
import os
cwd = os.getcwd()

###load nlp1 which is just spacy 'en'
nlp1 = spacy.load('en')
#persist model to_disk
nlp1.to_disk(cwd + '/spacy_model')
#persist model to_bytes
nlp1_bytes = nlp1.to_bytes()

print((
    len(spacy.load('en').vocab), #vocab len 57852
    len(spacy.load(cwd + '/spacy_model').vocab),  #vocab len 57864
    len(spacy.load('en').from_disk(cwd + '/spacy_model').vocab) #vocab len 115240
     ))
# >>> (57852, 57864, 115240)
```

## Environment
python3 -m spacy info

    Info about spaCy

    Python version     3.4.3
    Models             en
    Location           /usr/local/lib/python3.4/dist-packages/spacy
    Platform           Linux-3.13.0-107-generic-x86_64-with-Ubuntu-14.04-trusty
    spaCy version      2.0.8
 python3 -m spacy validate

    Installed models (spaCy v2.0.8)
    /usr/local/lib/python3.4/dist-packages/spacy

    TYPE        NAME                  MODEL                 VERSION             
    package     en-core-web-sm        en_core_web_sm        2.0.0
    link        en                    en_core_web_sm        2.0.0

**Comment by w2wei** [comment]
I can reproduce @justinkreft results. There seem some hidden terms in the vocabulary. I extracted terms in each vocabulary and the sizes are the same. In addition, the three vocabulary sets are identical. According to @ines and spaCy documentation, "In spaCy v2.x, this isn't such a problem anymore, since the StringStore now uses hash values that are consistent across models. See here for more background and examples.", the difference between vocabularies might not affect the model outcomes. 

nlp2 = spacy.load('en')
nlp3 = spacy.load(cwd + '/spacy_model')
nlp4 = spacy.load('en').from_disk(cwd + '/spacy_model')
print(len(nlp2.vocab), len(nlp3.vocab), len(nlp4.vocab))
# 57852 57864 115240

vocab2 = [tok.text for tok in nlp2.vocab]
vocab3 = [tok.text for tok in nlp3.vocab]
vocab4 = [tok.text for tok in nlp4.vocab]
print(len(vocab2), len(vocab3), len(vocab4))
# 57388 57388 57388

assert set(vocab2)==set(vocab3)
assert set(vocab2)==set(vocab4)

**Comment by honnibal** [comment]
Thanks for the report, sorry it took me a while to get to this.

When deserializing, the `vocab` did not check whether a lexeme already existed for the data it was loading back in. We'd just save the lexeme into the hash. The vocab wouldn't actually store a duplicate entry, as the key would be there --- but we'd increment the length counter. We'd also allocate a new `Lexeme` object, so if you kept doing this, you'd waste a bit of memory.
