### ISSUE TITLE
Failure to load a model should be an error or a warning, not a message

### ISSUE THREAD

**Issue by bgbg** [explosion/spaCy#2162]
Sometimes, spacy fails to load a model (for example, see #924 ). In these cases, the user should be able to detect the problem in a non-interactive way. For example, using a try-catch pattern, in case of exceptions, or by catching a warning [[ref](https://docs.python.org/2/library/warnings.html#warnings.catch_warnings)]. Right now, the `load` function prints a warning message using `util.print_msg` which escapes any assertion mechanism. 

There are two ways to address this problem without breaking back compatibility:

* add an optional argument to `load`, so that we can type `scipy.load('en', raise_on_failure=True)`
* change the current call to `util.print_msg` to `warnings.warn`

I think that the first one is safer

**Comment by ines** [comment]
Hi! From your descriptions, it sounds like you're using an older version of spaCy, right? There were various problems and inconsistencies around this in `v1.x`, which we've now fixed and addressed in spaCy `v2.x` – the most important one being `spacy.load` doing too many things at once (loading models, loading language data). This resulted in awkward states where the failure to load a model wasn't exactly a failure, because it'd fall back to only loading the tokenizer. 

In `v2.0`+, `spacy.load` has been improved and is now only intended for loading models. If any of that fails, spaCy will raise the respective errors. Since this is a significant change, we've only introduced this with the major version change. The CLI commands now also exit with the correct codes, so you can run them as part of an automated process – including `spacy validate`, which will exit with `1` if you have incompatible models installed.

(Good timing of your issue btw – I'm just about to publish a PR that includes various improvements to spaCy's error handling system, as well as options to show custom library-specific warnings.)
