### ISSUE TITLE
Using spaCy with pre-defined tokenization

### ISSUE THREAD

**Issue by minghao-wu** [explosion/spaCy#2171]
I tried to create a object with following ways.
```python
nlp = spacy.load("en")
doc1 = Doc(nlp.vocab, words =["This", "is", "a", "sentence", "."])
doc2 = nlp("This is a sentence.")
```
`doc2` works perfectly but `doc1` returns nothing when I `print(doc[0].dep_)` and returns `0` when I `print(doc1[0].dep)`

In my case, I prefer to use the `doc1` as the way to create a `Doc` object since my corpus has been tokenized.

I searched a lot at stackoverflow but found nothing.
Can anyone solve this problem?

Thanks in advance.

I am using 
```
spacy 2.0.10
python 3.6.4
```

**Comment by honnibal** [comment]
Hi,

You can read more about the lifecycle of the Doc through the pipeline here: https://spacy.io/usage/processing-pipelines

The answer to your question is that after you just create the `Doc` object, the pipeline hasn't run over it. That's why the annotations aren't set yet.

Try this:

```python
nlp = spacy.load("en")
nlp.tokenizer = lambda words: Doc(nlp.vocab, words=words)
```

That should let you just use the `nlp()` and `nlp.pipe()` methods. Alternatively you could change the tokenizer factory on the language object, like this:

```python
English = spacy.util.get_lang_class('en')
English.factories['tokenizer'] = lambda nlp, **cfg: lambda Doc(nlp.vocab, words=words)
```

(Sorry about the nested lambdas; just being concise --- I wouldn't write production code this way!)

**Comment by honnibal** [comment]
Btw, be careful when using pre-tokenized text that it actually matches up well against spaCy's tokenization standards. If you have a sample of your raw text, run it through spaCy's tokenizer and compare the outputs. If spaCy's tokenization is very different, the model will perform poorly on the text you've pre-segmented.
