### ISSUE TITLE
Why are we looking for exactly one attribute in case of set_extension on a doc.

### ISSUE THREAD

**Issue by chandan2495** [explosion/spaCy#2177]
https://github.com/explosion/spaCy/blob/0de599b16b0d8b14416bdbb374b3089e4ce0c6ac/spacy/tokens/doc.pyx#L100

**Comment by ines** [comment]
Sorry about the lack of a clearer message here – my PR in #2163 actually addresses this, removes all the random `assert`s and replaces them with proper error messages and more information. (See [here](https://github.com/explosion/spaCy/pull/2163/files#diff-12839294d4cfa46801ac1f6075166f4bL100) and [here](https://github.com/explosion/spaCy/pull/2163/files#diff-e05544161ef9df2b97bc6ee9e9732503R221) for this specific case.)

I also just noticed that the way we're checking the arguments here is bad – you *should* in fact be able to define a `getter` and `setter` – just not any other combinations. Will fix this, thanks! 👍

Some more background on this, also in case others come across this issue later: spaCy supports [three different types](https://spacy.io/usage/processing-pipelines#custom-components-attributes) of extension attributes:
1. Attribute extensions with a default value, e.g. `default=False`.
2. Property extensions with a `getter` and `setter`.
3. Method extensions that make the extension attribute callable using the provided `method`.

When you register an attribute, you'll need to decide which one it should be – for example, you can't mix a `getter` and a `default` value or a `method` and a `getter`, because this would make it impossible for spaCy to know how to retrieve the value and which function to execute.
