### ISSUE TITLE
Guidance on loading embeddings with multi-word phrases

### ISSUE THREAD

**Issue by ELind77** [explosion/spaCy#2192]
Many pre-trained embeddings have multi-word phrases included in the vocabulary.  In particular, I'm interested in using Mikolov's latest work: https://fasttext.cc/docs/en/english-vectors.html).  What is the best way to make sure spacy is able to use learned embeddings for multi-word phrases?  Should I use the matcher/phrases API in some way or do I need to do my own preprocessing?

Eric

**Comment by honnibal** [comment]
Assuming you need the pre-trained models, the order of operations you want is something like:

1. Tokenize as normal
2. Apply the pre-trained pipeline
3. Merge phrases (probably implemented using PhraseMatcher)

You can probably just add a pipeline component to do 3). Remember to use the `sm` model if you're doing this. Otherwise you'll have two sets of pre-trained vectors loaded in one model.

You should be able to load a vectors table with the phrase entries without any particular problem. It's just that the multi-word phrases won't immediately match any tokens, until you merge.

Merging lots of phrase is still slow on long documents. We've now got a `doc.retokenize()` context manager, but we still need to implement bulk merging.

If you don't need to use the pre-trained models, you could pre-process differently. For instance, it might work to simply replace spaces with the non-breaking space character within your multi-word phrases.

spaCy v2.1 will also support statistical recognition of multi-word expressions, jointly with the parsing. All you'll have to do is inform the `GoldParse` object what the gold-standard words should be, using the `words=` keyword argument. The `GoldParse` then calculates an alignment between the ideal tokenization and the tokenization in the `Doc` object it receives. The parser will have transitions which split or merge tokens, which it will learn to predict at the same time it's predicting the parse tree.
