### ISSUE TITLE
Keyerror related to `Language.pipe` after loading `Doc` with the same `Vocab`

### ISSUE THREAD

**Issue by winobes** [explosion/spaCy#2201]
```
import spacy

def annotate():
    nlp = spacy.load('en')

    raw_texts = [u'So Crazy when they play my @SantanaRxcks song', u'This is a test.']
    # raw_texts = [raw_texts[0]]

    docs = []
    for doc in nlp.pipe(raw_texts, batch_size=10000, n_threads=1):
        docs.append(doc)
    # docs = [nlp(text) for text in raw_texts]

    return docs[0].to_bytes()

def load_doc(doc_bytes):
    nlp = spacy.load('en')
    doc = spacy.tokens.Doc(nlp.vocab).from_bytes(doc_bytes)
    for token in doc:
        print(u"{} {} {}".format(token, token.lemma_, token.pos_))

if __name__ == '__main__':
    print("Annotating...")
    doc_bytes = annotate()
    print("Loading...")
    load_doc(doc_bytes)

```
Running this code I get the following error:

```
  File "/home/me/bug.py", line 23, in load_doc
    print(u"{} {} {}".format(token, token.lemma_, token.pos_))
  File "token.pyx", line 746, in spacy.tokens.token.Token.lemma_.__get__
  File "strings.pyx", line 118, in spacy.strings.StringStore.__getitem__
KeyError: 15434898665801592255L
```

In addition to not finding this lemma, the re-loaded `Doc` object doesn't have any `pos_`.

Curiously, the error doesn't occur if the first sentence is the only document (i.e. the first comment) or if the documents are created with `nlp.__call__` (i.e. the second comment).

## Your Environment

* **Python version:** 2.7.12
* **Platform:** Linux-4.10.0-38-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 2.0.10
* **Models:** en, en_core_web_md

**Comment by ines** [comment]
First: We actually *just* came across a bug in `Language.pipe` that would set `Doc.is_tagged` to incorrectly and was likely the cause of the tags not being set correctly. It's already fixed – see 5ecb274764b085bd6fe49fcc573618e430051259.

About the `KeyError`: I think the problem here is that you are using the "same" vocab – but not actually the same instance. The hash values in spaCy v2.x are nice because the same words will always receive the same hashes – but they're not reversible, and since your second `nlp.vocab` has never seen some of the lexemes you're processing, the `StringStore` doesn't have an entry for `15434898665801592255` (see the last example [in this docs section](https://spacy.io/usage/spacy-101#vocab) for more details).

Here's a working proof of concept:

```python
nlp = spacy.load('en')
raw_texts = [u'So Crazy when they play my @SantanaRxcks song', u'This is a test.']
docs = nlp.pipe(raw_texts)
doc = list(docs)[0]
doc_bytes = doc.to_bytes()
new_doc = spacy.tokens.Doc(nlp.vocab).from_bytes(doc_bytes)
print([t.lemma_ for t in new_doc])
# ['so', 'crazy', 'when', '-PRON-', 'play', '-PRON-', '@santanarxck', 'song']
```
