### ISSUE TITLE
import spacy problem in Spyder

### ISSUE THREAD

**Issue by Bellman281** [explosion/spaCy#2218]
I get this error:
import spacy
Traceback (most recent call last):

  File "<ipython-input-9-c080f6458562>", line 1, in <module>
    import spacy

ImportError: No module named spacy

## Your Environment
I updated almost everything! starting from Visual C++ to Conda!

## Info about spaCy

* **spaCy version:** 2.0.11
* **Platform:** Windows-10-10.0.16299-SP0
* **Python version:** 3.6.5

**Comment by ines** [comment]
Sorry about the late reply – I'm merging this with #2273, since the problems seem very similar. It's unlikely to be related to spaCy directly and sounds more like a problem with your environment or `PYTHONPATH` (which can be frustrating sometimes – I feel your pain)! For suggestions, see my comment in #2273.
