### ISSUE TITLE
Test if word is in the vocab

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [explosion/spaCy#2224]
## Your Environment

* Operating System: 
Mac OSX 10.13.1
* Python Version Used: 
Python 3.6.2
* spaCy Version Used: 
2.0.9
* Environment Information: 

Dear all,

I need to know if a word is in the English vocab or not.

```nlp = spacy.load('en')

doc = nlp('I am sflmgmavknsaccasas')

for token in doc:
    print(token in nlp.vocab)
```
Error:
```
TypeError: an integer is required
```

Also, is_oov is broken:
```
for token in doc:
    print(token.is_oov)
```
True
True
True

**Comment by ines** [comment]
```python
for token in doc:
    print(token in nlp.vocab)
```

When you're running the code above, the `token` you're looking up in the vocab is actually a `Token` **object**. Instead, you should check for the token's text or ID:

```python
for token in doc:
    print(token.text in nlp.vocab)
    print(token.orth in nlp.vocab)
```

> Also, is_oov is broken:

I'm pretty sure this is a mistake in the `en_core_web_sm` model and how the vocab entries are set. Sorry about that. This will be fixed with the next model releases.
