### ISSUE TITLE
ValueError: noun_chunks requires the dependency parse, which requires a statistical model to be installed and loaded.

### ISSUE THREAD

**Issue by Aravinviju** [explosion/spaCy#2260]
I am trying to implement chris moodey's LDA2VEC concept from(https://github.com/cemoody/lda2vec). while the pre-processing the data (https://github.com/cemoody/lda2vec/examples/hacker_news/data/preprocess.py), this inturn calls the lda2vec's preprocess module (https://github.com/cemoody/lda2vec/lda2vec/preprocess.py) it gives me the following error,

```
---------------------------------------------------------------------------
**ValueError                                Traceback (most recent call last)
<ipython-input-15-8c616a715db7> in <module>()
      6 texts = features.pop('comment_text').values
      7 tokens, vocab = preprocess.tokenize(texts, max_length, n_threads=4,
----> 8                                     merge=True)

/usr/local/lib/python2.7/dist-packages/lda2vec-0.1-py2.7.egg/lda2vec/preprocess.pyc in tokenize(texts, max_length, skip, attr, merge, nlp, **kwargs)
     74             # from the spaCy blog, an example on how to merge
     75             # noun phrases into single tokens
---> 76             for phrase in doc.noun_chunks:
     77                 # Only keep adjectives and nouns, e.g. "good ideas"
     78                 while len(phrase) > 1 and phrase[0].dep_ not in bad_deps:

doc.pyx in __get__()

ValueError: noun_chunks requires the dependency parse, which requires a statistical model to be installed and loaded. For more info, see the documentation: 
https://spacy.io/usage/models**
------------------------------------------------------------------------------------------------------
```

I tried all the possible solutions for installing/importing and loading the statistical model for English language like:
```
nlp = en_core_web_sm.load()
nlp = spacy.load('en_core_web_sm-2.0.0')
nlp = spacy.load('en_core_web_sm')
nlp = English()
nlp = spacy.load('en')
```

But still i get the same error!

## Your Environment

* **Python version:** 2.7.12
* **Platform:** Linux-4.13.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 2.0.7
* **Models:** en

Any help is appreciated!

**Comment by ines** [comment]
Hmm, I just had a look at that repository and the requirements aren't very strict and only define `spacy>=0.9` – but the code hasn't been updated in 2 years. This means it refers to an older version of spaCy, likely <1.x. 

This also makes it difficult to debug. Very old version of spaCy didn't yet ask the user to load a model explicitly and loaded it automatically if it was available in the data directory. [These two lines](https://github.com/cemoody/lda2vec/blob/b7f4642b750c6e792c07d177bd57ad36e65bb35c/lda2vec/preprocess.py#L67-L68) set `nlp = English()` if the `nlp` argument isn't set when calling the function. Are you sure you're passing it in correctly? 

Doing something like this should work:

```python
import spacy

nlp = spacy.load('en_core_web_sm')
data, vocab = tokenize(texts, max_length, skip=-2, attr=LOWER, merge=False, nlp=nlp)
```

If you're still having issues, it might actually be easier to just rewrite this function from scratch. It's not that complex and if you do it step by step, you'll make sure it's compatible with spaCy 2.x. You could also downgrade to spaCy `v0.100.0` – but I'm not sure that's useful, because you'll have to work with a very outdated library, lots of deprecated code and the model you'll end up with probably won't be that nice, either.
