### ISSUE TITLE
Spacy Parser Returning Blank Columns with Pandas & Multiprocessing

### ISSUE THREAD

**Issue by nitin608** [explosion/spaCy#2263]
Related Question: https://stackoverflow.com/questions/44395656/applying-spacy-parser-to-pandas-dataframe-w-multiprocessing
Related GIT issue: https://github.com/explosion/spaCy/issues/1111

Summary:
I have a short python wrapper function which accepts a pandas dataframe & a function, and applies the function to the dataframe in parallel. If I parse a text with Spacy (using my_pandas_series.apply(nlp)) without parallelizing, I get expected results. When I do it using the multiprocessing wrapper function, I get back a blank column.

This bug is still persistent in spacy 2.0.11. Has the fix been pushed to master?

Your Environment

    Operating System: Linux Mint 18 Sarah
    Python Version Used: 3.5
    spaCy Version Used: 2.0.11
    Environment Information:

**Comment by honnibal** [comment]
I don't really use Pandas myself, so I'm not sure what the problem is. I'm not sure that running the `apply()` function like that is going to give you good performance: you're likely to end up picking and unpickling the model on every instance, which is going to be very slow.

Unfortunately there's no one-size-fits-all approach to multiprocessing, because different functions have different start-up times. Pandas can't know that there's considerable cost to serializing and unserializing a spaCy model, so it can't make good choices around how to parallelise it.

I still don't understand why the result you're getting back is blank. But in general I probably wouldn't recommend the usage you're trying.
