### ISSUE TITLE
spaCy.io docs: better structure, deep links, FAQ

### ISSUE THREAD

**Issue by bittlingmayer** [explosion/spaCy#227]
I had a question that I don't feel belongs in GitHub issues, so I created https://groups.google.com/forum/#!forum/spacy-users.

I hope it's helpful and not a fragmenting fork.

**Comment by honnibal** [comment]
Hey,

Actually the plan's been to use Reddit for this. I hate Google groups, and I think it really discourages people from talking, since every message feels like an imposition.

Our plan is to have a little hook into our Slack channel for Twitter alerts, so that we can reply to tweets in-channel, and have a bot post the question and reply to the subreddit, and then post the link to the Twitter user.

So: please close the Google group, and use this instead: https://www.reddit.com/r/spacynlp

We'll be better about posting to it, and we'll advertise it better. Promise :)

**Comment by bittlingmayer** [comment]
Great, done

I think the main point is to note the subreddit's existence it at spacy.io and https://github.com/honnibal/spaCy/blob/master/README.md.

**Comment by bittlingmayer** [comment]
Also, how do you feel about us adding to https://github.com/honnibal/spaCy/wiki?

Some basic things, like an FAQ, are otherwise sorely missing, but I think burdening you alone with it may not be the most efficient.

**Comment by honnibal** [comment]
I think it's important to be careful about information duplication, so I'm not sure about the reason-for-existence for a FAQ, wiki etc.

What information do you think should be in a FAQ that shouldn't be anywhere else?

**Comment by bittlingmayer** [comment]
Agree that too much duplicate info is hard to maintain and not helpful.  Adding to the README probably makes more sense than inaugurating the wiki.

The question format is just really natural, useful and standard.  "Which human languages are supported?", "Who uses spaCy?"  It also gives you the chance to deal with questions "How much does it cost?"

If you add an FAQ hopefully it means you can replace that info in other places where it occurs with a link to the question in the FAQ, thus limiting duplication.

Also my preference is for deep links to the individual items (like Docs > Spec > Named Entity Recognition) which is probably more natural with separate pages for sections (eg Docs > Spec).

Take it all with a grain of salt :-)

**Comment by honnibal** [comment]
The Docs are being redesigned to allow deep linking and have better structure.

We'll think about the FAQ, since it's true that it's a fairly standard thing.
