### ISSUE TITLE
Cannot Import Spacy after Installation (this time in 64 bit python!)

### ISSUE THREAD

**Issue by AbelTan13** [explosion/spaCy#2273]
Hi,
Earlier I installed spacy using the environment and procedure I wrote down in this earlier issues post:
https://github.com/explosion/spaCy/issues/2265

I realised spacy cannot import since I was running 32 bit Python. 
So I installed 64 bit python (3.6.5), and I tried importing spacy again.

But again, I could not import spacy in python:

Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import spacy
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
>>> 

How do I solve this problem?

**Comment by ines** [comment]
This is difficult to debug without more information, since the problem can have various causes. It's also likely not related to spaCy but rather to the conda environment or your `PYTHONPATH` (which can be quite frustrating sometimes, so I definitely feel your pain). 

For example, you might be executing the wrong Python by accident or the wrong Anaconda environment (and not the one you previously installed spaCy in). This thread has some more background and solutions: https://stackoverflow.com/questions/39449725/python-modul-not-found-after-anaconda-installation (If you search for "ModuleNotFoundError conda", you'll also find other threads and suggestions!)
