### ISSUE TITLE
 No module named spacy.__main__

### ISSUE THREAD

**Issue by JoelDeLeon** [explosion/spaCy#2290]
Help! I have installed and uninstalled spacy countless times but for some reason there is no .exec file in my anaconda3/bin folder. 

When I run anything such as python -m spacy info,

I get this error:

/anaconda3/bin/python: No module named spacy.__main__; 'spacy' is a package and cannot be directly executed

what does this mean?

## Your Environment

* Operating System: Mac 10.12.6
* Python Version Used: Python 3.6.4
* spaCy Version Used: 
* Environment Information:

**Comment by ines** [comment]
In general, the error can mean [many things](https://www.google.com/search?q=No+module+named+__main__+"is+a+package+and+cannot+be+directly+executed") – and it's definitely confusing, because spaCy should ship with a `__main__.py`, that allows executing the package from the command line. Some questions that might help with debugging:

* Are you installing the correct version from conda, i.e. [this one](https://anaconda.org/conda-forge/spacy)?
* What happens if you open the Python interpreter and `import spacy`? Does this cause an error, too?

In some cases, it can also help to start off with a clean (virtual) environment, if you haven't tried that already. You could also try installing spaCy via pip instead of conda, although that's a pretty unsatisfying solution.

**Comment by matanster** [comment]
I encounter the same error, on a freshly installed Ubuntu 16.04 and Anaconda, where spacy was installed with the `conda` command as per the installation instructions shown in the screenshot.

![image](https://user-images.githubusercontent.com/4996067/41507930-c3523ffa-7244-11e8-854e-d1d7d81707b4.png)

`import spacy` works fine.
