### ISSUE TITLE
intents?

### ISSUE THREAD

**Issue by lmessinger** [explosion/spaCy#230]
Hi Mathew/guys

I cannot thank you enough for creating  this project. 
One thing I wondered about is slots and intents. 
I'm wondering what are my best options for Intent detection - is it something I can do with Spacy? any other tools?

Thanks for any lead and again, thanks for this project

**Comment by honnibal** [comment]
Hey,

Ultimately slot and intent detection are going to be a different problem for every user. spaCy makes it easy to extract features from text, for use in other machine learning libraries. But your problem is going to be different from any other --- so you still need to collect data, annotate it, and experiment with machine learning solutions.

**Comment by amn41** [comment]
Hey @lmessinger , am currently working on something which might do what you need. If this is still relevant to you, let me know! Otherwise would love to know about your solution :)

**Comment by lmessinger** [comment]
Hi

I've resorted to use luis.ai. but it doesnt really work well at all, many bugs. Totally unreliable.

I would love to hear about your solution,yes!

many thanks

**Comment by amn41** [comment]
cool! hit me up alan@golastmile.com and we can chat

**Comment by uwol** [comment]
spaCy 2.0 now offers a text categorizer, which works perfectly well for intent classification. 

@honnibal: Thanks for your great work with spaCy 2.0! By adding textcat, you eliminated the need for us to add a tensorflow/keras Bi-LSTM categorizer on top of your spaCy word vectors!

**Comment by ines** [comment]
Update: The new [`train_intent_parser.py` example](https://github.com/explosion/spaCy/blob/master/examples/training/train_intent_parser.py) might also be relevant – it shows how to train spaCy's parser to predict semantic relations instead of syntactic dependencies.

[Custom processing pipelines](https://alpha.spacy.io/usage/processing-pipelines#custom-components) could also be nice approach to add additional semantic information to the `Doc`, `Token` and `Span`.

**Comment by honnibal** [comment]
@uwol Thanks! There's a fair bit more to say about the text classifier -- lots of parameters to potentially tune :). It can also be useful to get the values from the attention layer, so that you can see which words were used for the classification. Finally, for annotating intents, you might find [Prodigy](https://prodi.gy) useful.

**Comment by honnibal** [comment]
With the `TextCategorizer` now fairly stable, I think this can be closed.
