### ISSUE TITLE
lemma of merged spans only has lemma of first token

### ISSUE THREAD

**Issue by ned2** [explosion/spaCy#2303]
When merging tokens, the lemma of the merged token has only the contents of the first token from the original sequence of merged tokens. 

## How to reproduce the behaviour
```python
doc = nlp("I ran 3km yesterday.")
matcher = Matcher(nlp.vocab)
matcher.add('num_km', None, [{'IS_DIGIT':True}, {'LOWER':'km'}])

with doc.retokenize() as retokenizer:
    for match_id, start, end in matcher(doc):
        retokenizer.merge(doc[start:end], attrs={})
        
[token.lemma_ for token in doc]
```
`Out: ['-PRON-', 'run', '3', 'yesterday', '.']`

I was hoping for the lemma of the merged token to be `3km`. Perhaps there's a sensible reason for this though. In which case, what would be the best way to get the full token sequence back in the context of reading off lemmas? ie how do I know when to use the `orth_` instead of the `lemma_`?

## Your Environment

* Operating System: Windows 7
* Python Version Used: 3.6.4
* spaCy Version Used: 2.0.11
* Environment Information:

**Comment by ines** [comment]
When you merge a span, spaCy doesn't just go ahead and merge the lemmas, too, because that can easily have unintended side-effects. Normally, you'd use the merged `Span`'s root – but you but you can also set your own via the attributes.

Here's the simple version using just the span's original text (which already includes the respective whitespace – or not, if a token like `3km` was split but shouldn't be combined with whitespace):

```python
doc = nlp("I ran 3km yesterday.")
span = doc[2:4]
lemma_id = doc.vocab.strings[span.text]  # get ID for "3km"
span.merge(lemma=lemma_id)
[token.lemma_ for token in doc]
# ['-PRON-', 'run', '3km', 'yesterday', '.']
```

Or, using the new retokenizer:

```python
from spacy.attrs import LEMMA

doc = nlp("I ran 3km yesterday.")
span = doc[2:4]
with doc.retokenize() as retokenizer:
   retokenizer.merge(span, attrs={LEMMA: doc.vocab.strings[span.text]})
```

If you want to use the lemmas, this is getting a little messier – and you probably also want to include some checks to ensure you're not actually creating lemmas like `-PRON-be` (it you were ever to merge `it's`). Here's one solution, using the lemma plus the token's `whitespace_` attribute to add whitespace if necessary (except for any trailing characters, because otherwise, the lemma would end up as `3km `):

```python
lemma_text = ''.join([token.lemma_ + token.whitespace_ for token in span]).strip()
```

Another alternative could be to add a [custom attribute](https://spacy.io/usage/processing-pipelines#custom-components-extensions) to all tokens that includes a *list* of all lemmas. For merged spans, you can manually store all span lemmas there – and for all other tokens, the list just includes the regular lemma. 

```python
from spacy.tokens import Token

def get_lemmas(token):
  if token._._lemmas is not None:  # dummy attribute has custom lemmas
    return token._._lemmas
  return [token.lemma_]  # regular token lemma

Token.set_extension('_lemmas', default=None)
Token.set_extension('lemmas', getter=get_lemmas)

doc = nlp("I ran 3km yesterday.")
span = doc[2:4]
span_lemmas = [token.lemma_ for token in span]  # get list of lemmas
span.merge()
span[0]._._lemmas = span_lemmas  # write them to dummy attribute of merged token (!)

[token._.lemmas for token in doc]
# [['-PRON-'], ['run'], ['3', 'km'], ['yesterday'], ['.']]
```

Admittedly, this might be overkill for this use case, and also kinda ugly.

**Comment by ned2** [comment]
Thanks so much for the super detailed response! I figured there might well be potential issues around merging lemmas of merged tokens. 

I ended up going for the option of creating a `token._.lemmas` attribute and while yes it's a little clunky it does the job. Actually the only downside I've come across is that frequently accessing underscore attributes on tokens seems to have a bit of a performance hit. I had a couple of other convenience attributes with `getter=some_func` that I was hitting for every token my pipeline was producing and found that replacing them with a direct call to some_func(token) resulted in enough of a speedup to not use the custom attributes. (would this be worth opening a separate issue for?)

**Comment by ines** [comment]
Custom attributes are definitely most useful to (automatically) attach data to your `Doc` objects. If you only want to compute something and don't need to store it with the `Doc`, using direct function calls is fine.

It makes sense that they can be *slightly* slower – but it shouldn't be significant. So yes, if you have a test case and a speed comparison, that would be helpful. Maybe there is something we can optimise.

I've also always wanted to do a comparison of the different ways of computing a value based on `Doc`/`Token`/`Span` attributes. For example, something like this:

```python
import spacy
from spacy.tokens import Token

def reverse_string(token):
    return token.text[::-1]

nlp = spacy.load('en_core_web_sm')
doc = nlp(u"Hello world, this is a test.")

# test case 1: direct function call (should be fastest)
print([reverse_string(token) for token in doc])

# test case 2: attribute with getter
Token.set_extension('reversed1', getter=reverse_string)
print([token._.reversed1 for token in doc])

# test case 3: writing to attribute
Token.set_extension('reversed2', default=None)
for token in doc:
    token._.reversed2 = reverse_string(token)
print([token._.reversed2 for token in doc])
```
