### ISSUE TITLE
how to create Train data for intent classification in Spacy

### ISSUE THREAD

**Issue by manishprasadthapliyal** [explosion/spaCy#2322]
I came across Spacy example for intent classification. with train data

```python
TRAIN_DATA = [
    ("find a cafe with great wifi", {
        **'heads': [0, 2, 0, 5, 5, 2],  # index of token head**
        'deps': ['ROOT', '-', 'PLACE', '-', 'QUALITY', 'ATTRIBUTE']
    }),
    ("find a hotel near the beach", {
        'heads': [0, 2, 0, 5, 5, 2],
        'deps': ['ROOT', '-', 'PLACE', 'QUALITY', '-', 'ATTRIBUTE']
    })]
```

My question is how are these heads are created. can somebody please explain through one example

**Comment by ines** [comment]
The head is the index of the token's head, i.e. the token it is attached to. [See here](https://en.wikipedia.org/wiki/Head_(linguistics)) for a more detailed explanation of the linguistic definition. If you look at a sentence in a visualizer like [displaCy](https://explosion.ai/demos/displacy), the head is the "root" of the arrow:

![](https://user-images.githubusercontent.com/13643239/39957576-97a759f0-55f5-11e8-927d-aa5091f1d80c.png)

In spaCy, getting the heads looks like this:

```python
doc = nlp("find a cafe with great wifi")
print([t.head.i for t in doc])
# [0, 2, 0, 2, 5, 3]
```

The only difference here is that the **syntactic** dependency parse attaches "wifi" to "with" – which is correct from a grammatical perspective. However, since the example shows training an intent classifier, you can invent your own rules.

In this case, we want attributes related to "cafe" to be attached to it – so the head of "wifi" is `2`: the token "cafe". "cafe" is attached to "find", which is also the root of the sentence, i.e. our intent.

| Word | Head | Index |
| --- | --- | --- |
| find | find | `0` |
| a | cafe |  `2` |
| cafe | find | `0` |
| with | wifi | `5` |
| great | wifi | `5` |
| wifi | cafe | `2` |

It might help to think of it from your application's perspective: What are you trying to extract and how should the tokens be connected to each other? Given a sentence, how would you expect the dependencies to look? What do you need in order to extract the intents and their attributes? The heads let you define those relationships.

**Comment by manishprasadthapliyal** [comment]
Thanks @ines  for the answer. I have one more question how create train set for continuous words in intent classification for example,

**show me the best hotel in New York**
how the word **_New York_** will be labeled in deps?
If i use New and York as Location it is being trained individually not as one entity.
("show me the coolest hostel in New York", {
        'heads': [0, 0, 4, 4, 0, 4, 4,4],
        'deps': ['ROOT', '-', '-', 'QUALITY', 'PLACE', '-', **'LOCATION', 'LOCATION']**
    })
