### ISSUE TITLE
Sentence Detection very slow: taking more than 2 min on 11K documents. 

### ISSUE THREAD

**Issue by saroufimc1** [explosion/spaCy#2323]
Hi, 

I am trying sentence detection on the newsgroups20 training data set (about 11000 documents) and it is quite slow (taking 132 s). 
Is that normal? batch_size and threads or even looping myself over every document is taking about the same time. Is there a way to speed it up? NLTK is much much faster. 

## How to reproduce the behavior
```
import spacy
nlp = spacy.load('en_core_web_sm')
nlp.add_pipe(nlp.create_pipe('sentencizer'))

from sklearn.datasets import fetch_20newsgroups
twenty_train = fetch_20newsgroups(subset='train', categories=None)
X= twenty_train.data

sent = []
for doc in nlp.pipe(X, batch_size=1000, n_threads=3, disable=['parser', 'tagger', 'ner']):
    sent.append([sent.text for sent in doc.sents])
```
## Your Environment
* Operating System: Windows Server 2016
* Python Version Used: 3.5.2 
* spaCy Version Used: 2.0.11

Thank you.

**Comment by honnibal** [comment]
You're running the whole pipeline, including parsing, POS tagging and NER. You can do `nlp = spacy.blank('en')` instead of loading the `en_core_web_sm` if you want to use the rule-based sentence boundary detector. Alternatively you can do `nlp.disable_pipes(['parser', 'tagger', 'entity'])`

**Comment by saroufimc1** [comment]
Hi @honnibal , thank you for your answer.
As you can see in my example above, I already tried disable=['parser', 'tagger', 'ner']. 
I just tried loading nlp = spacy.blank('en') like you suggested but it is still as slow as before (same time or even slower actually!!). 
Could you please try my code above and let me know if you get the same slow behavior? 

Thank you

**Comment by saroufimc1** [comment]
Thanks @honnibal ! When will this fix be part of the package? 
By the way, do you think this is the only explanation for the slow behavior? 
I am on Windows. Am I falling into this issue: https://github.com/explosion/spaCy/issues/2136 ?
I work at Microsoft so I can help push for the changes if they can improve SpaCy performance on Windows.

**Comment by honnibal** [comment]
@saroufimc1 It's unlikely that you'll be hitting the problems in #2136. The pipeline you're running only runs the tokenizer and the sentence boundary detector, so you're not making any matrix multiplications. That said, we'd definitely welcome help getting spaCy and Thinc easy to install and performant on Windows!

My comments above seem to have been a red herring as well. From testing further, it seems I was right the first time and the performance impact of the sentence boundary detector is minimal. I think this might be a Windows-specific issue.

On my machine the code runs in 30-50 seconds  depending on some details such as the model used. NTLK runs in the same range, around 45s.

You can get the 30ish second performance with the following little hack:

```
from spacy.attrs import IS_PUNCT
for attr in list(nlp.vocab.lex_attr_getters.keys()):
    if attr != IS_PUNCT:
        nlp.vocab.lex_attr_getters.pop(attr)
```

This removes the lexical features spaCy would otherwise pre-compute and save in the vocab. On this data, the lexical features seem relatively expensive, because the data has a lot of unseen words in the headers etc. That's why the small model actually runs slightly faster than the blank one: it comes with the most common words pre-computed.

So, what could be going on here? I wonder whether unicode handling is more expensive on Windows?

**Comment by saroufimc1** [comment]
Thank you again for your time @honnibal. I tried your hack on my machine (disabling lexical features), and unfortunately it only improved speed a bit for both  the blank pipeline (about 15 seconds gain)  and  'en_core_web_sm' (without NER, POS and parsing). They are taking about 118 s now. 

So it seems that something else is going on because of Windows... Is there anything else I can try? What is the main difference in the way NLTK vs. SpaCY are handling Unicode? 

Also, I am interested in POS and NER too and I can already see that it is pretty slow on my machine, so it would be great if we can fix https://github.com/explosion/spaCy/issues/2136 on Windows.

**Comment by honnibal** [comment]
Does the problem still occur with `spacy-nightly`?
