### ISSUE TITLE
Revisited: No meaningful message when a language is not supported by doc.noun_chunks (previously #682)

### ISSUE THREAD

**Issue by bverhoeff** [explosion/spaCy#2325]
Unfortunately I'm able to reproduce a previously mentioned error with the following code (and a non-english language model):
`nlp = spacy.load('nl')`
`doc = nlp(u"Zelfrijdende auto's verschuiven de aansprakelijkheid naar de fabrikant")`
`for chunk in doc.noun_chunks:`
    `print(chunk.text, chunk.root.text, chunk.root.dep_,`
            `chunk.root.head.text)`

Error message:
      5 nlp = spacy.load('nl')
      6 doc = nlp(u"Zelfrijdende auto's verschuiven de aansprakelijkheid naar de fabrikant")
----> 7 for chunk in doc.noun_chunks:
      8     print(chunk.text, chunk.root.text, chunk.root.dep_,
      9           chunk.root.head.text)

doc.pyx in __get__()
TypeError: 'NoneType' object is not callable

* **spaCy version:** 2.0.0rc2 (installed nightly after trying with latest stable, which didn't work as well with Dutch model)
* **Platform:** Windows-10-10.0.16299-SP0
* **Python version:** 3.6.5 (jupyter notebook)
* **Models:** en, nl

Seems like a problem in the get-method of property noun_chunks in doc.pyx. In this method, noun_chunks_iterator is called, followed by _get_chunker followed by util.get_lang_class. Unfortunately, I'm not familiar enough with the Spacy-package or with cython to add anything meaningful. However, I would very much like to use the Dutch language model with noun_chunks. Are there any workarounds or am I doing something wrong?

**Comment by ines** [comment]
Thanks! I'll need to have a look at this in detail, but it seems like we're missing a meaningful error message if the `Doc` object has the dependency parse available, but the language doesn't actually have a noun chunks iterator. (Previously, this wasn't a problem, since spaCy offered fewer language models and all supported languages had a noun chunks function).

Noun chunks are generated using a function that's called on the `Doc` or `Span` object. They're usually implemented in `spacy/lang/[lang]/syntax_iterators.py`. There's currently none available for Dutch, but you could see how the [English `noun_chunks`](https://github.com/explosion/spaCy/blob/master/spacy/lang/en/syntax_iterators.py) function performs on Dutch:

```python
import spacy
from spacy.lang.en.syntax_iterators import noun_chunks

nlp = spacy.load('nl')
doc = nlp(u"Some Dutch text with noun phrases here...")
chunks = noun_chunks(doc)
```

You can also copy-paste the `syntax_iterators.py` over to `lang/nl` and adjust the iterator if necessary. To make it available to the language class, you'll have to add it to the Dutch `__init__.py` (you can take inspiration from the other languages here). If you end up experimenting with this and come to a good solution, we'd always appreciate a pull request! 👍

**Comment by bverhoeff** [comment]
Thanks! Uninstalled nightly and reinstalled latest stable. 
Copied English syntax_iterators.py and edited __init__.py like you said,
functionality now works but not very accurate. German version does not make it any better. 
Which means I have to learn spacy myself.. It will take some time before I post a follow up..

**Comment by ines** [comment]
@bverhoeff Yes, that's definitely possible. The model is trained on the [Universal Dependencies](https://github.com/UniversalDependencies) treebank, which is quite small and has its limitations. Because the model is statistical, its performance always depends on the input text – if you're parsing text that's very different from the training corpus, you'll likely see significantly worse results.

If you have some labelled examples, you can always update and post-train the tagger, parser and entity recognizer: https://spacy.io/usage/training

We'd love to offer better support in the future, but it all comes down to licensing and sourcing more and better training data.

> Copied English syntax_iterators.py and edited init.py like you said,
functionality now works but not very accurate. German version does not make it any better.

I'm not that familiar with Dutch grammar, but it's possible you have to adjust some of the rules here. Of course, the results also depend on the tagger and parser. If the accuracy here is bad, you'll also get worse noun chunks.

**Comment by ines** [comment]
Just checked and looks like the initial problem here is already fixed in the latest version. I'm closing this issue, but if you end up getting a `noun_chunks` iterator to work for Dutch (even if it's not 100% perfect), feel free to open a pull request 🙂
