### ISSUE TITLE
compact mode while using displaCy.js

### ISSUE THREAD

**Issue by gurudevrao** [explosion/spaCy#2326]
spaCy documentation suggests to use displaCy.js to render the JSON-formatted output. However I find no option in displaCy.js to render the output in Compact mode. Please can you advise.

**Comment by ines** [comment]
Yes, if you want to use displaCy to render *user input*, we definitely advise to not just render the HTML markup directly, as this makes your app vulnerable. However, if you're in control of the inputs, you can also just run the Python version instead.

The "compact" mode is currently only available in the built-in visualizer. But it only requires pretty minimal changes to the code. If you do want to add it yourself, the relevant difference is here:

https://github.com/explosion/spaCy/blob/b59e3b157f593f5f74981bf9d39deba7bc9a12a4/spacy/displacy/render.py#L114-L126

Instead of drawing a curve, the "compact" mode uses the Cubic Bézier points as path coordinates. As you can see, the main difference here is that the compact path definition leaves out the `C`. displaCy also uses smaller spacings between words and arrows – how narrow you want to draw the visualisation depends on what you're doing, so you might have to experiment a bit to see what works best.

**Comment by gurudevrao** [comment]
Thanks so much. That was so easy.
