### ISSUE TITLE
How do I specify a phrase such that spacy recognises it as one token?

### ISSUE THREAD

**Issue by AbelTan13** [explosion/spaCy#2331]
Hi,

I was working with spacy to parse math problems. I have this particular question:

Say I have this ``pseudo sentence 

``Joanne gave (1/5 * her monthly salary) to his mother.``

I want spacy to treat (1/5 * her monthly salary) as one token. 

How do I format the ``(1/5 * her monthly salary)`` in the text so that spacy recognises it as one token?

I tried:
(_1/5_*_her_monthly_salary_). 

but then it gave the following output:

Joanne PROPN
gave (  VERB
1/5_*_her_monthly_salary)  NUM
to ADP
her ADJ
mother NOUN

as you can see, It gave it as one token, but the bracket was stuck to the ``gave`` to give ``gave (``.
How do I get rid of this stuck?

## Which page or section is this issue related to?
I dont think there is any documentation on spacy to force it to recognize text as one token.

**Comment by ines** [comment]
Modifying the input text by adding or removing characters like "(1/5*her_monthly_salary)" is almost always a bad idea. The statistical model will look at the exact tokens and predict the part-of-speech tags, dependencies and named entities. Adding characters like `_` to your text will have an impact on that, because it will "confuse" the model and likely produce worse predictions.

I'm also not sure why you want to merge the whole phrase into one token? Doesn't this make it harder to process afterwards, if you want to extract more specific information from it (like, the number, the mathematical operators and so on)?

Here's the default tokenization of the sentence, which seems pretty useful in my opinion:

```python
doc = nlp("Joanne gave (1/5 * her monthly salary) to his mother.")
print([t.text for t in doc])
# ['Joanne', 'gave', '(', '1/5', '*', 'her', 'monthly', 'salary', ')', 'to', 'his', 'mother', '.']

span = doc[2:9]  # a slice of the Doc
print(span.text)
# (1/5 * her monthly salary)
```

You *can* call `span.merge()` to merge the span into one token now, but this also means you'll lose a lot of semantic information of the individual tokens (token attributes etc.). Merging can be useful sometimes – but if you want to work with phrases, it's often better to use `Span` objects instead of a single `Token` (which is supposed to be the unit for a single word).

If you haven't seen it already, you might want to look into the [rule-based `Matcher`](https://spacy.io/usage/linguistic-features#rule-based-matching), which allows you to write very specific, token-based rules to extract information from text. For example, you could write a pattern for `[{'LIKE_NUM': True}, {'ORTH': '*'}]`, which will match a number token plus a token * (so possible mathematical references). You can also write more complex patterns that take the sentence's grammatical structure into account – you can find more details and examples in the docs.
