### ISSUE TITLE
How to train the NER to recognise a new entity "SME"?

### ISSUE THREAD

**Issue by avissens** [explosion/spaCy#2332]
I read some useful discussions here about training new entities but wanted to hear your suggestions about a particular task I'm trying to accomplish.

I'd like to introduce a new entity called Subject-matter expert or SME which would recognise persons' names only when mentioned in text together with a company or an institution they represent. I'd like to hear your thoughts about the best way to tackle this. Is it realistic? Could I expect accurate enough results? Thank you!

* **spaCy version:** 2.0.11
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.1
* **Models:** en_core_web_sm

**Comment by ines** [comment]
Of course, it always depends on your data – but it might actually be more efficient to focus on improving the built-in categories of `PERSON` and `ORG` instead of introducing a new one from scratch. After all, your `SME` entity is always a person and whether the label applies is mostly defined by that entity's *relationship* to an `ORG`, right?

Another question to consider: How local is the context and how close to the SME are the companies mentioned? If the mentions are quite far apart, the NER model much less likely to pick up on them and learn anything meaningful. If both occur in the same sentence, training a model is easier – but you might actually be able to get pretty good results using a rule-based approach and taking advantage of the dependency parse. (And if that's not accurate enough, it might be easier to tune the dependency parser on your data.)

**Comment by avissens** [comment]
Ines, thank you very much for your reply. Looking at the data I have I think I can isolate mentions within one (max two) sentence. Could you point me to any examples of how I can construct the relationship between `PERSON` and `ORG`? This might be the best way forward.

**Comment by ines** [comment]
You probably want to check out the section on [navigating the parse tree](https://spacy.io/usage/linguistic-features#navigating) – only that in your case, you'll be navigating the tree based on whether you found a person entity *and* a company entity within the same sentence. Here's a quick example of what's possible, using a made-up sentence:

```python
doc = nlp(u"Alex Smith of Google said something.")

person = list(doc.ents)[0]  # 'Alex Smith'
print(list(person.subtree))
# [Alex, Smith, of, Google]

print([token.dep_ for token in person.subtree])
['compound', 'nsubj', 'prep', 'pobj']
```

Here's another one:

```python
doc = nlp("Google spokesperson Alex Smith said something.")
person = list(doc.ents)[0]  # 'Alex Smith'
# spaCy doesn't actually recognise Google as an entity here, but you can fix that
print(list(person.subtree))
# [Google, spokesperson, Alex, Smith]
```

The [rule-based `Matcher`](https://spacy.io/usage/linguistic-features#rule-based-matching) also lets you match based on a token's `ENT_TYPE` attribute, so you can write pretty sophisticated patterns using the dependency parse and entity types. To test your patterns and see how they match, you can try our [interactive demo](https://explosion.ai/demos/matcher). You could also use the `Matcher` to bootstrap more training examples for your use case – see [here](https://spacy.io/usage/training#training-data) for more details.

**Comment by avissens** [comment]
Thank you very much. I'll try this out.
