### ISSUE TITLE
Using not ready yet a language model

### ISSUE THREAD

**Issue by aristorinjuang** [explosion/spaCy#2358]
## How to reproduce the problem

To use a language model, here is the command: `python -m spacy download en`

But the problem is, I want to use a language model which is not ready yet such as Bahasa Indonesia (id). So, I ran this command, `python -m spacy download id`, then I got this error message:

```bash
Compatibility error
No compatible model found for 'id' (spaCy v2.0.11).
```
We knew that Bahasa Indonesia (id) is still in development.
Any suggestions how to use it even it is not ready yet on production?
I follow this instruction (https://spacy.io/usage/adding-languages) to develop it. Any suggestions how to make it faster as possible until it is ready for production, what things need to be done?

Thanks for the help.

## Your Environment

* Operating System: Linux Ubuntu 18.04 LTS
* Python Version Used: 3.6.4
* spaCy Version Used: 2.0.11

**Comment by ines** [comment]
Yeah, the `spacy download` command is only intended for downloading [existing model packages](https://spacy.io) containing the binary data from our official [models distribution](https://github.com/explosion/spacy-models). We haven't trained an Indonesian model yet, which is why the download fails. However, you can always use the tokenizer out-of-the-box by importing the `Indonesian` class or calling `spacy.blank('id')`.

Just merged your contributions to the language data btw – thanks a lot! If you want to train a model, you can experiment with using the [Indonesian Universal Dependencies corpus](https://github.com/UniversalDependencies/UD_Indonesian-GSD). The only thing that's currently missing from the language data in spaCy is a [tag map](https://spacy.io/usage/adding-languages#tag-map) that maps the part-of-speech tags to the ones used in the treebanks. Once you've added this, you can use `spacy convert` to convert the `.conllu` files to spaCy's format, and then use `spacy train` to train the tagger and parser. [See this example](https://spacy.io/usage/training#spacy-train-cli) of training a Spanish model for more details. Note that the UD corpus is licensed under [CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/3.0/us/) and thus doesn't permit commercial use.
