### ISSUE TITLE
Index error E040

### ISSUE THREAD

**Issue by ajayrfhp** [explosion/spaCy#2363]
## What is index error E040 and why does it occur. 

Got a `IndexError: [E040] Attempt to access token at 8, max length 8.` in the line 
`doc.ents = list(doc.ents) + [span]`

Happened once, havent been able to recreate it. 
```


def __call__(self, doc):
        name_entities = []
        words = nltk.word_tokenize(doc.text)
        index = 0
        while index < len(words):
            if words[index] in self.names:
                start_index = index
                while index + 1 < len(words) and words[index + 1] in self.names:
                    index += 1
                end_index = index
                name_entities.append(
                    [doc.vocab.strings['PERSON'], start_index, end_index])
            index += 1

        for match_id, start, end in name_entities:
            span = Span(doc, start, end, label=match_id)
            doc.ents = list(doc.ents) + [span]
        return doc
```
## Your Environment
* **Platform:** Linux-4.4.0-1054-aws-x86_64-with-Ubuntu-16.04-xenial
* **Models:** en_core_web_lg, en, en_core_web_md
* **Python version:** 3.5.2
* **spaCy version:** 2.0.7

**Comment by ines** [comment]
One reason why we've introduced the error codes is that it hopefully makes them easier to track down in the code – so you can always search for the error code in the repo and see where it is raised. [See here](https://github.com/explosion/spaCy/search?q=E040&unscoped_q=E040) for `E040`.

The most likely explanation is that you have an off-by-one error in your code and the start or end index is incorrect. This means spaCy is trying to create a span using a token at position `8`, but the original `Doc` object only has 8 tokens (so the last token would have index 7).

This might have happened because you're using NLTK to tokenize your text and then passing those token indices back to spaCy. There's no guarantee that the tokenization will match and if it doesn't, you won't be able to create spans based on token indices. Is there a particular reason you're not using spaCy's tokens directly? If you want the text to be tokenized differently, you might want to look into [customising the tokenizer](https://spacy.io/usage/linguistic-features#special-cases) instead.
