### ISSUE TITLE
en model didn't work

### ISSUE THREAD

**Issue by jackie2jet** [explosion/spaCy#2373]
I run the snippet on your official site and It didn't work out
```
import spacy
nlp = spacy.load("en")
doc = nlp(u"this is a sentence.")
for w in doc.ents:
    print(w.tex, w.start_char, w.end_char, w.label)
```
-------------------------------------------------------
```
D:\Anaconda3\python.exe D:/SpacyTest/test_1.py

Process finished with exit code 0
```
as you can see the out put is nothing.

But I did successfully installed the model! so what's the problem here?
![default](https://user-images.githubusercontent.com/3447544/40573677-5edf7b2c-60f7-11e8-9050-c3bba4a8d4f3.png)

## Your Environment

* Operating System:Win 10
* Python Version Used:3.6
* spaCy Version Used:2.0
* Environment Information:anaconda

**Comment by ines** [comment]
The problem here is that you're printing the `doc.ents` (the named entities) of the sentence – but the text "This is a sentence" doesn't have any. That's why you also don't see any output. You can still look at the tokens, part-of-speech tags and dependency labels – but in order to print named entities, spaCy actually has to predict some.

For more details on NER and how the statistical models work, see our spaCy 101 guide: https://spacy.io/usage/spacy-101
