### ISSUE TITLE
error: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by ironside007** [explosion/spaCy#2386]
.... 
building 'murmurhash.mrmr' extension     
error: [WinError 2] The system cannot find the file specified

(whileinstallingspacy)

**Comment by ines** [comment]
Could you post the result of `python -m spacy info` or share more details on your platform, environment and how you installed spaCy (pip, conda, from source)? The error is likely a problem with the compiler, so did you check that you have the correct compiler installed?

**Comment by ironside007** [comment]
>>>python -m spacy info
 O/P"No module named spacy"

I installed it from pip. I use Python 3.6.5 IDLE , Windows 10.

other libraries like nltk etc. run properly, so don't know if the problem's in compiler

**Comment by ines** [comment]
To install spaCy on Windows, you'll need the Visual C++ Build Tools:
https://spacy.io/usage/#source-windows

A quick solution might be to try to install from conda instead, which ships wheels for Windows. This means you won't have to compile spaCy locally.

```bash
conda install -c conda-forge spacy
```

**Comment by ironside007** [comment]
Well with conda I'm getting:

ModuleNotFoundError: No module named 'pycosat'

I installed Visual studio then it shows:

 error: [WinError 3] The system cannot find the path specified:
'C:\\Program Files (x86)\\Microsoft Visual
Studio\\Preview\\Community\\VC\\Tools\\MSVC\\14.14.26428\\PlatformSDK\\lib'

PS:What all the files do i have to download in Visual Studio


and Thanks!



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/29/18,
4:10:51 PM

**Comment by ines** [comment]
> PS:What all the files do i have to download in Visual Studio

You don't need *Visual Studio* – you only need the [Visual C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools). I also find the way these things are named pretty confusing. If you browse through the [`windows` tag](https://github.com/explosion/spaCy/issues?utf8=%E2%9C%93&q=label%3Awindows+is%3Aclosed+is%3Aopen+sort%3Aupdated-desc+), you should also find similar threads around the Windows compiler and how to install the right tool.

> ModuleNotFoundError: No module named 'pycosat'

This sounds like there's something wrong with your conda installation or the dependencies. spaCy doesn't use `pycosat` and I'm not sure which other package it is related to. So maybe you want to try running `conda update --all`?

**Comment by ironside007** [comment]
Build tools direct me to the "Download Visual Studio page"
@screenshot(61.png)

Help me with what do i install.

"conda update --all " gives the same pycosat error.

PS: There's a problem with conda, The Navigator option is not available
even after trying to install/unistall several times.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/29/18,
4:28:54 PM

**Comment by ines** [comment]
I think what Microsoft is trying to tell you here is that you need to download the "
Build Tools for Visual Studio 2017" only – see here: https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017

![](https://user-images.githubusercontent.com/13643239/40656060-848f8864-6343-11e8-852e-d9e3fa3e20e6.png)

Did you try upgrading conda? The issue you describe seems to be common – see [the Google search](https://www.google.com/search?q=conda+ModuleNotFoundError%3A+No+module+named+'pycosat') and [this thread](https://github.com/conda/conda/issues/4320) for example. According to [this thread](https://github.com/conda/conda/issues/4338), the problem was resolved in conda 4.3.5.

Sorry if I can't help you further – you might want to check out some of the solutions described in the threads I linked above. I'm sure there are some suggestions on StackOverflow, too.

**Comment by ironside007** [comment]
I did install it then you have to install the visual studio choosing
different packages and i selected a few amongst them. Then the error
changed to::

 error: [WinError 3] The system cannot find the path specified:
'C:\\Program Files (x86)\\Microsoft Visual
Studio\\Preview\\Community\\VC\\Tools\\MSVC\\14.14.26428\\PlatformSDK\\lib'


Updating conda gives the same error and none of the solutions worked for me.

Well really thanks for your time and see if you could help further
otherwise it's cool

Thanks!
Avneesh


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/29/18,
5:04:46 PM

**Comment by ines** [comment]
Thanks for the update – I'll close this issue because it really sounds like there's some problem with your system and it's not related to spaCy. But fingers crossed – I hope you can find a solution online and get conda and everything else working again. If you do find a solution, feel free to update 👍
