### ISSUE TITLE
Span **attributes not updating

### ISSUE THREAD

**Issue by pmbaumgartner** [explosion/spaCy#2390]
I'm not sure if this is a bug or if I'm misunderstanding how merging spans works. I'm trying to use the Matcher and want to update the stopword attribute of a merged span, but it appears as if the attribute isn't updating.

## How to reproduce the behaviour
The easiest way to reproduce is the editable code example in the docs here: https://spacy.io/usage/linguistic-features#matcher-pipeline (great idea by the way, the interactive docs are a big help)

My understanding is that the following line from that example merges the span into a token and should set the `is_stop` attribute to `True` on the resulting token:

```python
for span in spans:
    span.merge(is_stop=True) # merge (and mark it as a stop word)
```

However, if you make a small edit to that print statement to check if the new merged tokens are stopwords, it appears as if they are not:

```python
doc = nlp(u"Hello<br>world! <br/> This is a test.")
for token in doc:
    print(token.text, token._.bad_html, token.is_stop)
```
```
Hello False False
<br> True False
world False False
! False False
<br/> True False
This False False
is False True
a False True
test False False
. False False
```
## Your Environment

* **spaCy version:** 2.0.11
* **Platform:** Linux-4.9.87-linuxkit-aufs-x86_64-with-debian-9.4
* **Python version:** 3.6.5
* **Models:** en_core_web_lg

**Comment by ines** [comment]
Thanks for the report! I just tested it and you're right – I think the problem here is that the `is_stop` attribute is an attribute on the *lexeme*, the context-insensitive entry in the vocabulary. It's proxied through to the token, but it's not actually a token attribute – so spaCy previously took the position that you may want to overwrite the context-specific attributes of the token you're merging, but not necessarily the lexical attributes of all instances out-of-context.

Here's an example of setting the attribute on the lexeme, which works as expected:

```python
for span in spans:
    span.merge()
    for token in span:
        doc.vocab[token.text].is_stop = True
        token._.bad_html = True
```

It'd probably be more consistent if the merging also allowed lexical attributes. After all, it's a pretty conscious decision the user is making, and if you're marking `<br>` as a stop word, you likely want all instances to be considered a stop word (as opposed to setting a part-of-speech tag, which obviously only applies to the token in context). 

Btw, the upcoming version will officially introduce the new `doc.retokenize()` contextmanager, which allows bulk merging and better performance in the future (because spaCy won't have to rewrite the `Doc`). You can already test it in the previous release (or if you build from `master`, so you can use the improvements described in #2304).

```python
with doc.retokenize() as retokenizer:
    retokenizer.merge(span[start:end], attrs={LEMMA: doc.vocab.strings[lemma_text]})
```

**Comment by pmbaumgartner** [comment]
Perfect! Setting the attribute on the lexeme works for now, and I'm looking forward to trying out `retokenize` in the future. Thanks for the help.
