### ISSUE TITLE
Advice about training NER model - dealing with random words

### ISSUE THREAD

**Issue by avissens** [explosion/spaCy#2402]
Hi, I'm trying to update the standard spacy model based on examples when it got NER tags wrong. It's clear to me how to do it when it confuses ORG or GPE with PERSON but I need advice about some cases (quite a lot actually) when it grabs random words in capital letters (Common, Keen, Ours etc. - I list some examples below) as PERSON. These are not named entities, so how do I 'untrain' it? Will appreciate your help!
Thank you!

*****
Examples:

#text = "Some text before. Common clothes moths and case-bearing clothes moths don't travel very far."
#text = "Bald patches form in carpets, while holes appear in jumpers, curtains, scarves and dresses."
#text = "Speak Welsh, please..."
#text = "Complex Trauma is poorly understood, rarely recognised, and few psychologists are trained to treat it."
#text = 'Happened to mine from the factory shops, again all my fault! Ours did this a few years ago.'
#text = "'Politically fraught' Analysis, by BBC political correspondent Alex Forsyth"
#text = "With no devolved administration in Belfast there is some pressure for the UK Government to act. Keen to avoid that, Downing Street sources have repeatedly said it's an issue to be determined in Northern Ireland."

all_tags = nlp(text)
person_list=[]
for ent in all_tags.ents:
    if ent.label_=="PERSON":
        person_list.append(str(ent))      
print (person_list)

*****
spaCy version: 2.0.11
Platform: Darwin-16.7.0-x86_64-i386-64bit
Python version: 3.6.1
Models: en_core_web_sm

**Comment by ines** [comment]
For texts that don't include entity spans, you should be able to just use an empty list or a list of only the correct entities. The annotations you provide for training the model are considered the "gold standard" – i.e. the "perfect" analysis of the text.  So teaching the model about sentences that *don't* contain any entities is just as important as teaching it about sentences *with* entities.

```python
('Ours did this a few years ago', {'entities': []})
```

In the BILUO format, the example would be represented as a list of `O` tags (for "outside an entity"):

```python
('Ours did this a few years ago', ['O', 'O', 'O', 'O', 'O', 'O', 'O'])
```

To illustrate the BILUO tags, here's a more complex example with only the correct entities labelled, and all other tokens marked as `O`. This is pretty much how spaCy will view the training example when you pass in a list of the two entities present in the sentence:

```
'Politically fraught' Analysis, by BBC political correspondent Alex Forsyth
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'U-ORG', 'O', 'O', 'B-PERSON', 'L-PERSON']
```

When you're updating your model with sentences that have no entities, make sure to also include sentences **with entities** – for example, entities that the model previously got right. Otherwise, you might accidentally teach your model that "nothing is an entity anymore" and cause it to "forget" everything it previously predicted correctly.

**Comment by avissens** [comment]
Got it! Thank you very much!
