### ISSUE TITLE
Contributing to language models

### ISSUE THREAD

**Issue by 91ns** [explosion/spaCy#2404]
is there a way to contribute to the spacy-models repository?

**Comment by honnibal** [comment]
Not easily at the moment, unfortunately.

The problem is that we want to make sure all the models can be reproduced, so that when we release a new version, we can provide updated models. I've been working for a long time on better training automation, which might allow us to offer some facilities to contribute scripts. But for now the process is tied into our other infrastructure, so there's no clean repo to contribute to.

What model are you interested in contributing? Is it something we can train, or does it rely on data that can't be distributed?

**Comment by NourShalabi** [comment]
I've been working on an Arabic language model, it is not optimal yet. But I was wondering as to how such models can be added to spaCy. 
Because then other developers can contribute to the same language model and improve it. The data I've been using was collected from several places, but like I said it isn't optimal yet.

It will be great if you can support this feature.

**Comment by ines** [comment]
Merging this with the master thread in #3056!
