### ISSUE TITLE
Spacy2 add more than 2 new type of entities to Matcher

### ISSUE THREAD

**Issue by vladimircape** [explosion/spaCy#2413]
I want using Matcher add 2 new types of entities
```
def add_event_ent(matcher, doc, i, matches):
    # Get the current match and create tuple of entity label, start and end.
    # Append entity to the doc's entity. (Don't overwrite doc.ents!)
    global EVENT    
    match_id, start, end = matches[i]    
    entity = (EVENT, start, end)    
    doc.ents += (entity,)   

EVENT = nlp.vocab.strings['FUND']
matche.add('FUND1', add_event_ent, *spec)

EVENT = nlp.vocab.strings['COMPANY']
matche.add('COMPANY1', add_event_ent, *spec)
```

Sure ,when matcher find FUND1 , EVENT is  already COMPANY, and this is wrong and i got incorrect type of entity.
What is correct way add several label types for matcher in Spacy2?
 in Spacy 1 it was special parameter **label**, but in Spacy2 there is no

> matcher.add(entity_key=, label=type_entity, attrs={}, specs=spec, on_match=merge_phrases)

**Comment by ines** [comment]
Yeah, the problem here is that you're overwriting the `EVENT` variable and your `add_event_ent` function doesn't actually know which entity type it's adding.

One of the reasons the explicit label argument is deprecated in v2.0 is that it's actually kinda redundant. Each entry added to the matcher has a unique ID, which you can use to trigger logic specific to the matches, like adding entity types. If you use the label name as the match_id, you can simply use that when you create the entity. Here's an example:

```python
def add_event_ent(matcher, doc, i, matches):
    # the match_id will either be FUND or COMPANY
    match_id, start, end = matches[i]
    entity = (match_id, start, end)   
    doc.ents += (entity,)  

matcher.add('FUND', add_event_ent, *spec)
matcher.add('COMPANY', add_event_ent, *spec) 
```

Alternatively, you could also check the string value of the label and add more logic to determine which entity label to add, based on the match. The `match_id` is an integer, so you'll need to look it up in `Doc` or `nlp` object's `vocab.strings` to get its string representation.

Here's another example of the whole thing without an `on_match` callback and iterating over the matches afterwards. This approach means that you'll have all matches already when you add the entities – so your function could filter out duplicates etc:

```python
matcher.add('FUND1', None, *spec)
matcher.add('COMPANY1', None, *spec)

matches = matcher(doc)

for match_id, start, end in matches:
   label = nlp.vocab.strings[match_id]
   if label == 'FUND1':
       # do something here
   else if label == 'COMPANY1':
       # do something else
   # etc.
```

**Comment by vladimircape** [comment]
I also was thinking solution like you,but it's looks not pretty :)

**Comment by ines** [comment]
Really, you think so? The first solution is actually much shorter and straightforward, because you can do everything within the scope of the function and don't have to rely on globals (at least in my opinion – of course, it always depends on personal preference).

The idea behind not having an additional label as part of the matcher arguments is that the `Matcher` shouldn't have to care about *what* you want to do with the matches. Its job is to match stuff in text – but it shouldn't perform any other modifications of the `Doc`.
