### ISSUE TITLE
Test in Japanese features

### ISSUE THREAD

**Issue by himkt** [explosion/spaCy#2417]
Currently, tests about  Japanese tokenizer are skipped
because MeCab is not installed on a server which run test.

So I think we need the Test server which has installed MeCab and UniDic.
@polm What do you think about this?
(I'm not sure whether it is prefer to ask you, sorry for inconvenience ..:bow:)

## Your Environment

* **spaCy version:** 2.0.12.dev0
* **Platform:** Darwin-17.5.0-x86_64-i386-64bit
* **Python version:** 3.6.2

**Comment by polm** [comment]
Good point! I think this came up when I first wrote the tests but it was decided it would be dealt with later.

At one point I tried making a version of mecab+unidic that could be installed using just pip ([mecab-packed](https://github.com/polm/mecab-packed)), partly because it would be easier to set up on the test servers, but unfortunatley I didn't get very far. I think the setuptools documentation was being rewritten at the time or something...

If it's possible to install mecab/unidic on the test machine I'd be glad to help with that.
