### ISSUE TITLE
Quote char font problem

### ISSUE THREAD

**Issue by mehmetilker** [explosion/spaCy#2424]
I get different dependency result with the following sentence.

“My grandfather was laid to rest last Sunday”
"My grandfather was laid to rest last Sunday"

The only difference is quote char font. First one has quote char generally used news articles.

Do we need replace “ with " before sending text to pipeline?

## Your Environment
https://explosion.ai/demos/displacy?text=“My%20grandfather%20was%20laid%20to%20rest%20last%20Sunday”&model=en_core_web_sm&cpu=1&cph=0

**Comment by ines** [comment]
From the model's perspective, `"` and `“` are two different unicode characters – and since once of them is much more frequent in the training data than the other, the way they influence the predictions can also be different.

The parser definitely shouldn't be that sensitive to those differences, though. The [norm exceptions](https://github.com/explosion/spaCy/blob/master/spacy/lang/norm_exceptions.py) (more details [here](https://spacy.io/usage/adding-languages#norm-exceptions)) are trying to solve some of that. Since the token's `NORM` is used as a feature in the model, we can use that attribute to provide a normalised form of a token and tell spaCy that `“` and `"` are the same thing, even if they're fundamentally different unicode characters. This means that they will receive very similar representations, even if one of them is much more common in the training data than the other.

> Do we need replace “ with " before sending text to pipeline?

If you do have control over your input, you can add a pre-processing step that normalises your text and makes it consistent. Another option would be to post-train your model and make it less sensitive to character variations like that. The nice thing here is that it'll be very easy to bootstrap training data – you can extract the correct parses, replace `"` with `“` and [update the model](https://spacy.io/usage/training) with those new examples. (Just make sure to include some of the original examples, too – you don't want your model to "forget" about what it previously got right).

**Comment by mehmetilker** [comment]
I think a safe bet will be adding pre-processing step and converting `“` to `"` since `"` char giving the right dependency result

By the way I see those quote chars on norm exception list but they do not change result.
Is there a setting to activate it?
`
BASE_NORMS = {
    "”": '"',
    "“": '"',
`

**Comment by ines** [comment]
> By the way I see those quote chars on norm exception list but they do not change result.
Is there a setting to activate it?

I need to double-check this, but it's possible that those were added *after* we trained the current models. we're currently training the models for `v2.1`, so it'll be interesting to test it again with the new models and compare the predictions.

**Comment by ines** [comment]
Good news: In the new models we've trained for `v2.1.0`, which take the norm exceptions into account, the following test passes now:

```python
@pytest.mark.parametrize('text', ['My grandfather was laid to rest last Saturday'])
def test_en_parser_norm_exceptions(NLP, text):
    """Test that the parser isn't sensitive to different unicode variations
    that are reset in the new NORM exceptions."""
    text1 = '"{}"'.format(text)
    text2 = '“{}”'.format(text)
    assert [t.dep_ for t in NLP(text1)] == [t.dep_ for t in NLP(text2)]
```

One interesting observation, though: If I change "Saturday" to "Sunday", it doesn't, because the parser's predictions don't match. It's pretty difficult to say why this happens – could be some quirk in the training data, or something completely different. If you come across cases like that, it's usually possible to fix them by updating the parser with more similar examples.
