### ISSUE TITLE
IndexError when trying to access `nbor` of the last token in a document

### ISSUE THREAD

**Issue by savkov** [explosion/spaCy#2428]
## How to reproduce the behaviour
``` python
doc = nlp('I love cats')
doc[-1].nbor()
# raises IndexError
```
## Info about spaCy
* **spaCy version:** 2.0.11
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.2
* **Models:** en, en_core_web_sm

## Question
Shouldn't this return `None`?

**Comment by honnibal** [comment]
Well, it's always raised an `IndexError`. I think returning `None` here is probably worse. You still need to make a conditional check, it's just you'd be checking the output rather than deciding whether to call the function. And if we return `None`, then you can forget to make the output check, and pass `None` forward.
