### ISSUE TITLE
MS Visual C++ 14.0 is required, 14.0 is installed already

### ISSUE THREAD

**Issue by bogga** [explosion/spaCy#2441]
## How to reproduce the problem
I ran `pip install -U spacy`

```bash
building 'murmurhash.mrmr' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "c:\users\abogg\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\abogg\\AppData\\Local\\Temp\\pip-install-p1h5asoi\\murmurhash\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\abogg\AppData\Local\Temp\pip-record-sxt9fhol\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\abogg\AppData\Local\Temp\pip-install-p1h5asoi\murmurhash\
```

## Your Environment

* Operating System: Windows 10 Home 64 bit
* Python Version Used: 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49)
* spaCy Version Used: 2.0.011
* Environment Information: 2005, 2008, 2010, 2012, 2013, 2015, 2017 redistributables of MS Visual C++ installed.

**Comment by ines** [comment]
Sorry about that – the Windows compiler stuff can sometimes be annoying, partly because of how all of those build tools are named. I came across [this thread](https://stackoverflow.com/a/50414582/6400719), which describes the following solution:
> I found the answer! Turns out I was installing 'Microsoft Visual C++ Redistributable for Visual Studio 2017' instead of 'Build Tools for Visual Studio 2017'. Funny how a simple error can cause a lot of headache!

Ironically, the official Visual Studio Landinghub page with the installers doesn't even work anymore? 🤔

![bildschirmfoto 2018-06-13 um 12 27 07](https://user-images.githubusercontent.com/13643239/41346004-8798c61a-6f05-11e8-939d-60f463bc7a62.png)

Another workaround would be to just install spaCy from conda instead. This will ship with wheels and doesn't require you to compile spaCy locally:

```bash
conda install -c conda-forge spacy
```

**Comment by bogga** [comment]
Ok so I fixed this by using conda, but if people want an actual fix you can use the latest Visual Studio Build Tools app, and on the right pane choose the specific "MS Visual C++ 14.0" option. :)

**Comment by ines** [comment]
@bogga Thanks for updating, glad it's all working now! 

(We're currently exploring options for setting up our own infrastructure so we can build all those wheels for pip, but this might take a while. I just wish the compiler stuff was easier on Windows 😢)

**Comment by theslimshaney** [comment]
@bogga could you post a screenshot of the option? Thanks!
