### ISSUE TITLE
different behavior based on tab character

### ISSUE THREAD

**Issue by chandan2495** [explosion/spaCy#2443]
## How to reproduce the behaviour
```python
import spacy
nlp = spacy.load('en_core_web_lg')
doc = nlp(u"""Dewatering pipeline\t$223,000""")
from spacy import displacy
html = displacy.render(doc, style='ent', page=True)
```
![image](https://user-images.githubusercontent.com/6929170/41352921-61c0af42-6f38-11e8-9391-ac5b66e5c99a.png)

```python
import spacy
nlp = spacy.load('en_core_web_lg')
doc = nlp(u"""Dewatering pipeline $223,000""")
from spacy import displacy
html = displacy.render(doc, style='ent', page=True)
```
![image](https://user-images.githubusercontent.com/6929170/41352969-8441892e-6f38-11e8-9da5-86b6a9f96a88.png)

## Your Environment

* Operating System: Windows 7
* Python Version Used: 2.7.12
* spaCy Version Used: 2.0.7
* Environment Information: None

**Comment by ines** [comment]
Hi! Sorry for only getting to this now. The reason this happens is because the entity recognizer is sensitive to the context. To the model, a space and a tab are two different characters

Of course, we do want the model to be less sensitive to this. I just checked your example in one of the new models we've trained for the upcoming `v2.1.0` nightly, and it now works as expected. A possible explanation for this is that the new models now take the norm exceptions into account, which normalise similar tokens to one common form (whitespace, quotes, currency symbols etc). This means that they all receive the same representation, even if one of them was less frequent in the training data. See [my comments here](https://github.com/explosion/spaCy/issues/2424#issuecomment-395694242) for more details and examples.
