### ISSUE TITLE
Default pip/conda installation version is 0.101

### ISSUE THREAD

**Issue by BBCMax** [explosion/spaCy#2462]
I spent a chunk of time struggling to install spaCy earlier - getting the below error:
`No module named spacy.__main__; 'spacy' is a package and cannot be directly executed`

This would appear after an apparently successful install (either through pip or conda) when trying to download models or even run `python -m spacy info`.

After some time I noticed that by default it was installing `spacy-0.101.0`. After explicitly getting conda to install the current latest version of spaCy (2.0.11), I no longer experienced any of these issues. 

Just bringing this to your attention in case it can be rectified, or at least save time for others experiencing similar issues!

**Comment by ines** [comment]
Thanks for looking into this. I always suspected that something like this was the cause of that error, but it's *super* confusing why this would be happening. By default, pip and conda should always install the latest version available 🤔

Is it possible that you had an old version of spaCy installed on your system somewhere, or can you rule that out? And could you share the exact commands you ran to install it from both pip and conda?

**Comment by BBCMax** [comment]
No worries! This is a new laptop, and actually my first time using spaCy too so I can pretty comfortably rule out the presence of any previous spaCy installations.

Find the most recent version of spaCy on conda:
`conda search -f spacy`

Find the most recent version on pip (the only way I know to see available versions of a package on pip is to specify a nonsense version and then it will list all available versions of the specified package):
`pip install spacy==random_words`

Then either run
`conda install spacy=NEWEST_VERSION`
or
`pip install spacy=NEWEST_VERSION`
(in my case I installed 2.0.11)

**Comment by ines** [comment]
This is very mysterious, and after coming across [another similar issue](https://stackoverflow.com/questions/51037475/spacy-language-module-not-downloading), I now have two theories for what might be happening:

1. For a long time, the official Anaconda distribution actually shipped a version `v0.100.0` of spaCy – [see here](https://docs.anaconda.com/search_docs/spacy%200.101.0) in the respective package lists. So if a user has both the conda package manager and the Anaconda distribution installed (which is usually recommended, especially to beginners), spaCy might be resolved to the version that is already installed (i.e. an old one).

2. There might be some dependency installed in the user's environment that isn't compatible with the recent spaCy version. This could be an old version of pretty much anything, even something pretty insignificant. Instead of updating that dependency, the package manager resolves the conflict by downloading the latest version *of spaCy* that's compatible with that package (which happens to be an old one).

It could also be a combination of both, or something entirely different. In any case, I really hope we can get to the bottom of this and find a way to prevent this. It also really sucks that this is an issue that often hits beginners who are just getting started 😞

**Comment by ines** [comment]
Merging this with #2514 because it looks like we're narrowing in on the solution / explanation!
