### ISSUE TITLE
Spanish NER not working 

### ISSUE THREAD

**Issue by martinbel** [explosion/spaCy#2502]
### Environment
* Operating System:
* Python Version Used: Python 3.6.5
* spaCy Version Used: 2.0.11
* Environment Information: Conda env just created with only spacy installed
* Language model Installed: 
python -m spacy download es

```In [1]: import spacy

In [2]: spacy.__version__
Out[2]: '2.0.11'

In [3]: nlp = spacy.load('es')

In [4]: doc = nlp(u'una porqueria el servicio')

In [5]: for ent in doc.ents:
   ...:     print(ent.text, ent.start_char, ent.end_char, ent.label_)
   ...:     
In [6]: ent
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-8c21580f639d> in <module>()
----> 1 ent

NameError: name ent is not defined

In [7]: doc.ents
Out[7]: ()
```

I've tried installing other spanish models having the same result. It works perfectly for english!

**Comment by ines** [comment]
Hi! Not sure if this was part of your question, but the error that occurs in `[6]` is because the variable `ent` is only available *inside* your `for` loop (when you're looping over the entities).

And the reason `doc.ent` is empty is likely because the model doesn't predict any entities in your text. "una porqueria el servicio" means something like "crap service", right? The [Spanish model](https://spacy.io/models/es#es_core_news_sm) was trained on Wikipedia and can predict `PER`, `LOC`, `ORG` and `MISC` – but nothing in your text fits into any of those categories, so the `doc.ents` are empty and the model predicts that there are likely no entities in your text.

(When using a pre-trained model for NER, keep in mind that the predictions are statistical and not always correct, especially if your data is different from the data the model was trained on.)
