### ISSUE TITLE
CLI train stops before finishing

### ISSUE THREAD

**Issue by ValentinCalomme** [explosion/spaCy#2511]
## Bug

I am trying to train an NER model with custom entities using the CLI. Somehow, sometimes (this error is stochastic), the training stops in the middle of the first iteration (typically at 42% in my case)

No error is thrown but because no model is saved, the rest of my code fails. What could potentially halt the training without raising any warnings/errors?

## Info about spaCy

* **spaCy version:** 2.0.11
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.6.4
* **Models:** de

**Comment by ines** [comment]
> What could potentially halt the training without raising any warnings/errors?

That's likely a segmentation fault, i.e. a C-level error. Because of the lack of traceback and details, those can be tricky to debug – but if we can get to the bottom of what the training fails on, we'll likely be able to prevent it in the future. Here are some debugging strategies:

On each update, you could output the training examples to a file. If you set the `buffsize` argument to `1` ([see here](https://stackoverflow.com/questions/3167494/how-often-does-python-flush-to-a-file)), you'll get the last write, and it won't crash with the critical examples waiting to be written.

In the best-case scenario, you'll be able to reproduce the error with a low batch size and it'll consistently fail on the same example(s). This will be super useful for debugging this and figuring out what the problem might be. Maybe you'll also notice something in the data that looks suspicious.

If it always fails on different examples, this could indicate that the problem is related to a combination of the data *and* the weights, which is more difficult.

**Comment by ValentinCalomme** [comment]
How can I write the training examples to a file if I am using the CLI?

I started using the CLI because of #1476. With my data, the python kernel would very often fail, and with the CLI, it wouldn't.

**Comment by ines** [comment]
You'd have to edit the source of `spacy/cli/train.py` and add it there – for example, right before `nlp.update` when it iterates over the batches. You could start with just saving the `doc.text` for each doc and see if something seems weird, and then go from there.

To find the location of your spaCy installation, you can just run this btw:

```bash
python -c "import spacy; print(spacy.__file__)"
```

And yes, training via the CLI is definitely more efficient with larger datasets, because it batches up the examples and uses a lot of [optimisation tips and tricks](https://spacy.io/usage/training#section-tips). `spacy train` is also what we use internally to train spaCy's models.
