### ISSUE TITLE
Pickling a doc with word vectors causes all (vocab) vectors to be serialized for single doc

### ISSUE THREAD

**Issue by sadovnychyi** [explosion/spaCy#2522]
I been using spacy with Apache Beam which uses pickle by default for unknown objects and my job simply stuck because of this – it was generating 600mb of data per short document. It's working fine for model without word vectors. `doc.to_bytes` also working as expected. Shouldn't pickle use `.to_bytes()` as well so it would work by default?

```python
>>> import spacy
>>> nlp = spacy.load('en_core_web_md', disable=['tagger', 'parser', 'ner'])
>>> import pickle
>>> len(pickle.dumps(nlp(u'hello world')))
629615979
```

## Your Environment
* Operating System: macos/debian
* Python Version Used: 2.7.15
* spaCy Version Used: 2.0.11

**Comment by honnibal** [comment]
This is sort of hard to resolve, because if we want unpickling a doc to work, by definition it needs its vocab instance. Can you explicitly convert them to `doc.to_bytes()`?

<slightly grumpy rant>
I haven't seen Apache Beam before, but it seems like it makes the same promises as Spark...The issue here is that this idea of transparently mapping out *any* unit of work over *any* input data to multiple processes is a terrible bad no good idea that simply can't work.

The simple fact is that jobs *aren't* uniform. There's no one-size-fits-all way that jobs should be mapped out to underlying resources. It matters enormously which data is immutable and can be shared, how big things are, how long things take to load, how long things take to process, etc etc.

So, I agree that it's frustrating that these things don't immediately work with spaCy. But I think it's the fault of these tools for making a promise they simply can't keep. In order to get behaviours, you need to manage parallelisation explicitly.
</slightly grumpy rant>

**Comment by sadovnychyi** [comment]
Maybe raising a NotPickableError or something would be better than giving
600mb of data? I can definitely call to_bytes with custom coder, or just
avoid passing spacy docs at all between pipeline steps. My only concern
here is that pickling works while silently consuming lots of resources.

**Comment by honnibal** [comment]
The v2.1 docs now explain these aspects of Pickle. I don't want to remove picklability from the `Doc` object, because it does work well if you don't have the vectors, and it also works okay if you pickle a large collection of `Doc` objects. In future I'd definitely consider having something like a context manager to help with this, to set and unset the vectors from the objects.
