### ISSUE TITLE
SpaCy hangs during test when building for the Anaconda Distribution

### ISSUE THREAD

**Issue by mingwandroid** [explosion/spaCy#2527]
## Your Environment

* Operating System: Linux
* Python Version Used: Any
* spaCy Version Used: 2.0.11
* Environment Information: Anaconda Distribution.

I see:

```
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.6/site-packages/spacy/tests/regression/test_issue912.py . [ 68%]
                                                                         [ 68%]
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.6/site-packages/spacy/tests/regression/test_issue957.py
```

Do I need to install anything else? pytest-timeout for example?

**Comment by honnibal** [comment]
It does look like `pytest-timeout` will turn this test into a failure instead of a hang, which is at least an improvement.

It's pretty troubling though. Why would this hang for your tests, but not in our CI? I think 2.0.11 has been built for conda-forge, so what would be different?

I guess if this is blocking the build, then it's best to patch it to xfail the test. I hope we can get to the bottom of this though.

**Comment by mingwandroid** [comment]
If there are some steps you recommend for diagnosing this further I'm happy to try them out.

**Comment by ines** [comment]
It's possible that this was related to unnecessarily verbose tests, lots of skipped stuff and language classes being instantiated per test function (instead of per session). We've since rewritten the test suite on `develop` and moved the model tests to [`spacy-models`](https://github.com/explosion/spacy-models). I hope this problem is resolved now – if not, feel free to reopen.
