### ISSUE TITLE
Cannot install language model as a package

### ISSUE THREAD

**Issue by katarkor** [explosion/spaCy#2557]
Hi,
I'm working on a model for Norwegian and currently get these results:

    Time               6.10 s         
    Words              36467          
    Words/s            5975           
    TOK                100.00         
    POS                95.28          
    UAS                88.04          
    LAS                85.28          
    NER P              77.99          
    NER R              77.38          
    NER F              77.68  

(how good is good enough for the model btw?)
I wanted to package it and install it, it seemed ok:
running sdist
running egg_info
creating nb_ud_ner.egg-info
writing nb_ud_ner.egg-info/PKG-INFO
writing dependency_links to nb_ud_ner.egg-info/dependency_links.txt
writing requirements to nb_ud_ner.egg-info/requires.txt
writing top-level names to nb_ud_ner.egg-info/top_level.txt
writing manifest file 'nb_ud_ner.egg-info/SOURCES.txt'
reading manifest file 'nb_ud_ner.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'nb_ud_ner.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

running check
warning: check: missing required meta-data: url

creating nb_ud_ner-0.0.0
creating nb_ud_ner-0.0.0/nb_ud_ner
creating nb_ud_ner-0.0.0/nb_ud_ner.egg-info
creating nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0
creating nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/ner
creating nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/parser
creating nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/tagger
creating nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/vocab
copying files to nb_ud_ner-0.0.0...
copying MANIFEST.in -> nb_ud_ner-0.0.0
copying meta.json -> nb_ud_ner-0.0.0
copying setup.py -> nb_ud_ner-0.0.0
copying nb_ud_ner/__init__.py -> nb_ud_ner-0.0.0/nb_ud_ner
copying nb_ud_ner/meta.json -> nb_ud_ner-0.0.0/nb_ud_ner
copying nb_ud_ner.egg-info/PKG-INFO -> nb_ud_ner-0.0.0/nb_ud_ner.egg-info
copying nb_ud_ner.egg-info/SOURCES.txt -> nb_ud_ner-0.0.0/nb_ud_ner.egg-info
copying nb_ud_ner.egg-info/dependency_links.txt -> nb_ud_ner-0.0.0/nb_ud_ner.egg-info
copying nb_ud_ner.egg-info/not-zip-safe -> nb_ud_ner-0.0.0/nb_ud_ner.egg-info
copying nb_ud_ner.egg-info/requires.txt -> nb_ud_ner-0.0.0/nb_ud_ner.egg-info
copying nb_ud_ner.egg-info/top_level.txt -> nb_ud_ner-0.0.0/nb_ud_ner.egg-info
copying nb_ud_ner/nb_ud_ner-0.0.0/accuracy.json -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0
copying nb_ud_ner/nb_ud_ner-0.0.0/meta.json -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0
copying nb_ud_ner/nb_ud_ner-0.0.0/tokenizer -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0
copying nb_ud_ner/nb_ud_ner-0.0.0/ner/cfg -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/ner
copying nb_ud_ner/nb_ud_ner-0.0.0/ner/lower_model -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/ner
copying nb_ud_ner/nb_ud_ner-0.0.0/ner/moves -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/ner
copying nb_ud_ner/nb_ud_ner-0.0.0/ner/tok2vec_model -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/ner
copying nb_ud_ner/nb_ud_ner-0.0.0/ner/upper_model -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/ner
copying nb_ud_ner/nb_ud_ner-0.0.0/parser/cfg -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/parser
copying nb_ud_ner/nb_ud_ner-0.0.0/parser/lower_model -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/parser
copying nb_ud_ner/nb_ud_ner-0.0.0/parser/moves -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/parser
copying nb_ud_ner/nb_ud_ner-0.0.0/parser/tok2vec_model -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/parser
copying nb_ud_ner/nb_ud_ner-0.0.0/parser/upper_model -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/parser
copying nb_ud_ner/nb_ud_ner-0.0.0/tagger/cfg -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/tagger
copying nb_ud_ner/nb_ud_ner-0.0.0/tagger/model -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/tagger
copying nb_ud_ner/nb_ud_ner-0.0.0/tagger/tag_map -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/tagger
copying nb_ud_ner/nb_ud_ner-0.0.0/vocab/key2row -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/vocab
copying nb_ud_ner/nb_ud_ner-0.0.0/vocab/lexemes.bin -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/vocab
copying nb_ud_ner/nb_ud_ner-0.0.0/vocab/strings.json -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/vocab
copying nb_ud_ner/nb_ud_ner-0.0.0/vocab/vectors -> nb_ud_ner-0.0.0/nb_ud_ner/nb_ud_ner-0.0.0/vocab
Writing nb_ud_ner-0.0.0/setup.cfg
creating dist
Creating tar archive
removing 'nb_ud_ner-0.0.0' (and everything under it)

But when I try to load it with:
nlp2 = spacy.load('nb_ud_ner')
I get the error:
Can't find model 'nb_ud_ner'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

I already successfully packaged and installed one model, but was unable to overwrite it or install a new one. How do I solve this?

## Your Environment
* Operating System: macOS High Sierra 10.13.6
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0.11
* Environment Information:

**Comment by ines** [comment]
The packaging all looks good! It looks like spaCy can't find the model in the environment – did you install the `.tar.gz` archive the package command created? It should be in `/dist`. For example:

```python
pip install /path/to/dist/nb_ud_ner-0.0.0.tar.gz
```

If you run `pip list`, `nb_ud_ner` should also show up there.

Alternatively, you can also just load in the model data directly (the same path you exported during training). This is especially useful during development so you don't have to package, install and uninstall packages all the time:

```python
nlp = spacy.load('/path/to/output-model')
```

> I already successfully packaged and installed one model, but was unable to overwrite it or install a new one. How do I solve this?

You can always run `pip uninstall` with the package name, for example `pip uninstall nb_ud_ner`. If you're reinstalling a package that's already installed and the versions are identical, pip might skip it (because it thinks it's the exact same package). You should be able to prevent that by setting the `--ignore-installed` during installation.

> (how good is good enough for the model btw?)

Your results look very good! For comparison, [here](https://spacy.io/models/en) are the accuracy figures of the English model. Of course, the results only show how well the model was able to learn from the training corpus – how useful it'll really be depends on a lot of factors and how well it generalises.

What data did you train the entity recognizer on btw? 🙂

**Comment by katarkor** [comment]
Thanks, it worked :) I made some changes for Norwegian, mostly for the lemmatizer, morph rules and tag map. How do I upload it to spaCy's github without breaking anything?
> What data did you train the entity recognizer on btw? 

> 

I trained it on a dataset that is not published yet (will be published this autumn), but it's similar to this one:
https://github.com/UniversalDependencies/UD_Norwegian-Bokmaal
only it has NER tags in the 10th column. I also created a separate conllu_ner2json.py, which is basically the same as conllu2json.py, but with small changes in order to get the NER tags, convert them to BILUO etc. Should I upload this somewhere? And where do I upload my model?

**Comment by ines** [comment]
> I made some changes for Norwegian, mostly for the lemmatizer, morph rules and tag map. How do I upload it to spaCy's github without breaking anything?

Thanks, that would be great! The easiest way would be to create a [pull request](https://github.com/explosion/spaCy/pulls) from a fork:

1. If you haven't done so already, fork this repo so a copy of it shows up in your account.
2. Commit and publish all your Norwegian changes to your fork.
3. When you [create the pull request](https://github.com/explosion/spaCy/compare), click on "compare across forks" and select your spaCy fork on your profile as the "head fork".
4. You should then see a list of your changes and you'll be able to submit a pull request to suggest the changes for spaCy.
5. All pull requests will be reviewed and merged by us, so you won't have to worry about breaking anything 🙂 When you submit the PR, our Travis / Appveyor CI will also run the spaCy tests against your code, to make sure everything works as expected. If something goes wrong, it will show a message and you can fix the problem, make an update to your fork and the PR will be updated automatically.

>  also created a separate conllu_ner2json.py, which is basically the same as conllu2json.py, but with small changes in order to get the NER tags, convert them to BILUO etc. Should I upload this somewhere?

Yes, that would be cool! Do you think there's a way to extend the `conllu2json.py`, check if NER tags are available and only convert them if they are? Or would this get to messy? If so, it'd be fine to have it as a separate converter. You can add it to the `cli/converters` directory and include it with your pull request.

> And where do I upload my model?

If you want to share your model with others, you could upload it to GitHub. It's possible to add the files to a repository, but I wouldn't usually recommend putting binary data in version control. For our official models, we use Github releases and attach the packaged files to them: https://github.com/explosion/spacy-models/releases

We'd love to be able to ship an official spaCy model for Norwegian – but contributing is a little more difficult here, because we need to be able to easily re-train all models we distribute. For example, if we need to release an update to spaCy that requires retraining, we need to be able to do so ourselves (and it shouldn't be a user's job, just because they were nice and contributed a model). For spaCy v2.1.0, we revamped our internal model training pipeline and infrastructure to make it easier to train the full model family and word vectors. 

This also means that it's now much easier for us to integrate a new model into our training pipeline, especially if we know that it works. So if you'd be interested in contributing your training workflow (corpus, conversion, training commands, hyperparameters, model meta), feel free to get in touch: contact@explosion.ai.

> I trained it on a dataset that is not published yet (will be published this autumn)

That sounds cool! 👍 Do you know what license the dataset will be published with?

**Comment by katarkor** [comment]
> Do you think there's a way to extend the conllu2json.py, check if NER tags are available and only convert them if they are? Or would this get to messy?
> 
I guess I could do that next week, when I'm back from holiday :)

> Do you know what license the dataset will be published with?
>
I don't really know, but I was told I could use the data as long as I included the citations later, when the dataset is officially published. It's a joint work of  Schibsted, Nasjonalbiblioteket (Norway's National Library) and LTG (Language Technology Group) from University of Oslo.

**Comment by ines** [comment]
Sure, take your time and have a nice holiday! 🌴 

I'll keep an eye out for the dataset release then. We'd definitely be interested in exploring it, especially if it has an open-source and/or commercial-friendly license.
