### ISSUE TITLE
Add updated displacy to npm

### ISSUE THREAD

**Issue by maneesht** [explosion/spaCy#2562]
## Feature description

displaCy is available on the NPM repository, but it is not the maintained version of the library. As the current standard is to use some kind of module loader in the front-end world, by updating the version of displaCy on NPM to allow this, many more developers will be able to use this tool.

**Comment by ines** [comment]
Yeah, I agree. I think I originally uploaded it there ages ago because a user wanted to install it from npm, but it was never optimised for that.

displaCy.js hasn't really been updated since we included the built in `displacy` module with spaCy. I've been thinking about rewriting it to make it more modern etc., but I'm not sure yet how I want it to work. It should be as simple as possible and ideally a drop-in solution that doesn't require any specific JS build tools, for users who don't have a background in front-end stuff and just want to include a file. But it should also be useful as a module you can include in more complex web applications.

One idea I had was to standardise on a JSON representation of the rendered output (arcs, words, coordinates, labels etc.) and make the core module generate only that. We could then have a wrapper that transforms this output into DOM elements, another one that creates React elements etc.

**Comment by maneesht** [comment]
I think adding support for a framework/library would be a great idea, so long as it doesn't restrict the user from using a different library. (I.E. I use angular, not React).
I think the first pass would just be to convert the updated version to use node modules and also create a typings file for those of us who would like to use it with TypeScript. 
I might be able to handle both of those things, if you'd like.

**Comment by ines** [comment]
@maneesht 

> I think adding support for a framework/library would be a great idea, so long as it doesn't restrict the user from using a different library. (I.E. I use angular, not React).

Yeah, it'd be great if we could have some kind of intermediate representation of the SVG, which could then either be turned into regular DOM elements, a React component, an Angular component etc. The default app would then be fully standalone, but you could easily build `displacy-angular`, which depends on `displacy`, and so on.

>  I might be able to handle both of those things, if you'd like.

Yes, that'd be really cool! 👍

**Comment by maneesht** [comment]
@ines Would you like me to add those changes to this repository or displacy.js and displacy-ent.js? I read on the spaCy site that displaCy and displaCyENT were "officially" included in the library, so shouldn't they end up here?

**Comment by ines** [comment]
> I read on the spaCy site that displaCy and displaCyENT were "officially" included in the library, so shouldn't they end up here?

For the built-in visualizers, I basically re-wrote displaCy and displaCy ENT in Python – you can find the source [here](https://github.com/explosion/spaCy/tree/master/spacy/displacy). So they're not actually JavaScript and just generate the HTML in Python (and optionally start a simple web server). They're mostly intended for users who quickly want to visualize a parse tree in their browser or Jupyter Notebook, or save out a graphic, without having to think about any front-end stuff.

So the JavaScript modules should probably be a separate project. However, I do think we can potentially combine `displacy.js` and `displacy-ent.js`. If you want, you could start by forking the `displacy.js` repo – I think I set the original repo to "archived" on GitHub so people can see that it's currently not actively maintained. But it should still let you fork the code 🙂

**Comment by ines** [comment]
Sorry this took so long – here you go: https://www.npmjs.com/package/displacy
