### ISSUE TITLE
noun_chunk does not find parser

### ISSUE THREAD

**Issue by alvercau** [explosion/spaCy#2574]
I am trying to get Spacy noun_chunk to work, without success. Here is what I tried with the error messages:

    import spacy

    text = "The Spacy noun chunker doesn't work as expected and illustrated in various examples accross the web."
    nlp_en = spacy.load('en_core_web_sm')
    doc = nlp_en(text)
    ncs = [nc for nc in doc.noun_chunks]

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-230-bebdb397f19f> in <module>()
      4 nlp_en = spacy.load('en_core_web_sm')
      5 doc = nlp_en(text)
    ----> 6 ncs = [nc for nc in doc.noun_chunks]

    <ipython-input-230-bebdb397f19f> in <listcomp>(.0)
      4 nlp_en = spacy.load('en_core_web_sm')
      5 doc = nlp_en(text)
    ----> 6 ncs = [nc for nc in doc.noun_chunks]

    doc.pyx in __get__()

    ValueError: noun_chunks requires the dependency parse, which requires a statistical model to be installed and loaded. For more info, see the documentation: 
    https://spacy.io/usage/models
    
With the Dutch model I get a different error:

    text = "De Spacy noun chunker werkt niet en al zeker niet zoals overal staat in voorbeelden op het internet."
    nlp_nl = spacy.load('nl_core_news_sm')
    doc = nlp_nl(text)
    ncs = [nc for nc in doc.noun_chunks]

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-231-995e8109d484> in <module>()
      4 nlp_en = spacy.load('nl_core_news_sm')
      5 doc = nlp_en(text)
    ----> 6 ncs = [nc for nc in doc.noun_chunks]

    <ipython-input-231-995e8109d484> in <listcomp>(.0)
      4 nlp_en = spacy.load('nl_core_news_sm')
      5 doc = nlp_en(text)
    ----> 6 ncs = [nc for nc in doc.noun_chunks]

    doc.pyx in __get__()

    TypeError: 'NoneType' object is not callable

According to the docs (https://spacy.io/usage/models) both models should contain a parser. I have no idea what's going on here. Am I using the wrong models?

Im using spacy 2.0.9 and python 3.6.2.

## Your Environment

* Operating System: OS
* Python Version Used: 3.6.2
* spaCy Version Used: 2.0.9

**Comment by ines** [comment]
Thanks for the report! This is pretty mysterious indeed and I can't reproduce this 🤔 What does it say when you print `en_nlp.pipe_names`? And could you try upgrading to the latest version, `v2.0.11` and see if that changes anything? 

About the Dutch error: In the latest version `v2.0.11`, spaCy shouldn't fail with such a cryptic message anymore. However, the Dutch language data doesn't have any rules for noun chunks yet (which are calculated based on the dependency parse and POS tags), so the noun chunks will be empty.

**Comment by alvercau** [comment]
I found where the problem might be: if I load en_core_web_sm, I get an empty list in nlp.pipe_names (which is weird because pos and ner works perfectly fine). With en_core_web_md on the other hand, everything works as expected: I get tagger, parser and ner in the pipeline, and the noun chunk works. 
Where can I find the source code for the noun chunks for English? I will need it for Dutch, so I might write the code Spacy-style right away and make it available to everyone. 
Thanks!

**Comment by ines** [comment]
Hmmm, this is still super bizarre and I don't remember ever seeing this problem before. It's possible that you just ended up in a weird system / installation state somehow, so the best suggestion I have would be to reinstall the models and maybe spaCy, or start with a fresh virtual environment. (As a santity check, you could also run `python -m spacy validate`, which will show you if all models are up to date. But if they weren't spaCy, would usually fail much more drastically.)

Here's the noun chunks source (the files are called syntax iterators because we're hoping to have other similar features in the future, like conjuncts etc.):

* English: [`spacy/lang/en/syntax_iterators.py`](https://github.com/explosion/spaCy/blob/master/spacy/lang/en/syntax_iterators.py)
* German: [`spacy/lang/de/syntax_iterators.py`](https://github.com/explosion/spaCy/blob/master/spacy/lang/de/syntax_iterators.py)
* Spanish: [`spacy/lang/es/syntax_iterators.py`](https://github.com/explosion/spaCy/blob/master/spacy/lang/es/syntax_iterators.py)

One of them might even be pretty compatible with Dutch out-of-the-box. The main thing you'd have to check and adjust would be the dependency labels etc., which are different across corpora and languages (the Dutch models are trained on the Universal Dependencies corpus btw).

If you do end up implementing the noun chunks for Dutch, that would be super cool!

**Comment by tolomaus** [comment]
Hi @alvercau I happen to have the same need as you: getting good noun chunks for Dutch :-) Did you already have a go at implementing the Dutch syntax_iterator?

Since you're in Belgium - like me - I wonder if you have experience with the quality of the French noun chunking?

**Comment by alvercau** [comment]
Hi @tolomaus 

I started working on it, but haven't finished it yet due to lack of time. The main issue seems (after very little investigation, so I might be wrong) that the dependency parser for Dutch is not very good. It is easier to adapt the English chunker than the German one though, since the English parser is more similar to the Dutch one than the German one. 
I haven't tried the French chunker yet.

**Comment by honnibal** [comment]
@tolomaus @alvercau Would definitely be interested in syntax iterators for Dutch. Once it's implemented for one Universal Dependencies language, hopefully it will work well for others.

Also, the models for Dutch in the v2.1.0 alpha are a bit better than the previous, although still not very satisfactory.
