### ISSUE TITLE
OSError: Can't find model 'es_core_news_sm'

### ISSUE THREAD

**Issue by Devadath** [explosion/spaCy#2576]
##Problem
 When I tried to load the spanish model using spacy.load("es_core_news_sm"), I am getting this error OSError: Can't find model 'es_core_news_sm'. 

I installed the model using  "python -m spacy download es_core_web_sm" and It was successful.

Successfully installed en-core-web-sm-2.0.0

    Linking successful
    /home/d/.local/lib/python2.7/site-packages/en_core_web_sm -->
    /home/d/.local/lib/python2.7/site-packages/spacy/data/en_core_web_sm

    You can now load the model via spacy.load('en_core_web_sm')

##Error message
```bash
# OSError: Can't find model 'es_core_news_sm'
```

## Your Environment
    Info about spaCy

    Python version     2.7.12         
    Platform           Linux-4.13.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
    spaCy version      2.0.8          
    Location           /home/d/.local/lib/python2.7/site-packages/spacy
    Models             es, en_core_web_sm, es_core_news_sm

**Comment by ines** [comment]
Hi! Just to confirm and make it easier to follow, since two two models have very similar names – the two models you installed were the following:

* `en_core_web_sm` (small **English** model trained on web text)
* `es_core_news_sm` (small **Spanish** model trained on news text)

Could you show the command you ran to load it? And do both models show up correctly when you run `pip list`? From your environment info, it looks like both models exist and are recognised by spaCy, so it's surprising you see that error.

But it's always possible that you're accidentally loading a *different* spaCy in a different environment. If you run `which python` in your terminal, does the result match `/home/d/.local/lib/python2.7`? And does the following work, or do you see an import error?

```python
import es_core_news_sm
nlp = es_core_news_sm.load()
```

**Comment by Devadath** [comment]
@ines 
Thanks Ines, I had python version issues. Sorry for this silly mistake.

**Comment by ines** [comment]
No worries – I think everyone can relate! Glad it's all working now! 👍
