### ISSUE TITLE
Need help to extract entities

### ISSUE THREAD

**Issue by Ssdmc** [explosion/spaCy#2577]
hy , 
In my case i have text like : 
"some text about Article 1 and 2"
i want to extract two entities Article 1 and Article 2 

any one know how to do it  ???

**Comment by ines** [comment]
If your "entities" follow a consistent scheme, a rule-based approach might actually be a better place to start. Instead of using a statistical model, you'd use the `Matcher` to find entities in your text, and then add them to the `doc.ents` property. More info:

* [Documentation: Rule-based matching](https://spacy.io/usage/linguistic-features#section-rule-based-matching)
* [Interactive demo: Rule-based Matcher explorer](https://explosion.ai/demos/matcher)
* [Documentation: Custom pipeline components](https://spacy.io/usage/processing-pipelines#custom-components)

If you want to train the entity recognizer, the terms you want to find should really be 
distinct *categories of things*. For example, `PERSON` or `PRODUCT` – not things that are only really defined by their dependencies and the surrounding context (like "victim" or "crime location").

spaCy's entity recognizer can be updated with more examples – either to detect more examples of an existing category or to add a new custom category. Here are some resources to get you started:

* [spaCy 101: Named entities](https://spacy.io/usage/spacy-101#annotations-ner)
* [Documentation: Training models](https://spacy.io/usage/training)
* [Documentation: Training the named entity recognizer](https://spacy.io/usage/training#section-ner)
* [Documentation: Training tips and advice](https://spacy.io/usage/training#section-tips)

**Comment by Ssdmc** [comment]
thank you Ines , i'll see this docs !
