### ISSUE TITLE
Persistance of custom attribute on Span when copying object

### ISSUE THREAD

**Issue by thomasopsomer** [explosion/spaCy#2581]
## How to reproduce the behaviour

Hello,

I'm often using custom attributes on `Span` that are dicts and I noticed that these custom attributes stay on the span after being copied using the following operation: `span => span.as_doc[:]`. (I'm using this for instance to apply a textcat only on a sentence...)
However custom attribute of types `str`, `list`, `bool` ... doesn't stay attached to the span.
Concretely:

```python
spacy.tokens.Span.set_extension('dict', default={})
spacy.tokens.Span.set_extension('list', default=[])
spacy.tokens.Span.set_extension('bool', default=False)
spacy.tokens.Span.set_extension('string', default="")

span = nlp("Hello world")[:]

span._.dict["a"] = 1
span._.bool = True
span._.string = "kk"
span._.list = ["kk"]

assert span.as_doc()[:]._.dict == {"a": 1}     # ok
assert span.as_doc()[:]._.bool == True        # fail
assert span.as_doc()[:]._.string == "kk"        # fail
assert span.as_doc()[:]._.list == ["kk"]        # fail
```

I don't know what is to be expected. For my use case I would like these custom attribute to be persisted. So if the case of custom attribute of type `dict` is a bug, an option to keep these attributes in the `as_doc` method would be appreciated :)

## Your Environment

* **spaCy version:** 2.0.12
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.2
* **Models:** en, en_core_web_lg, en_core_web_md, fr_core_news_md, fr_core_news_sm, xx_ent_wiki_sm

**Comment by ines** [comment]
> I don't know what is to be expected. For my use case I would like these custom attribute to be persisted.

The `Span.as_doc` method actually creates a *new* `Doc` object (i.e. the parent-level container) and it currently doesn't port over the `Doc.user_data` which contains the custom attributes. The difficulty here is that the span and token views in the user data will all refer to the wrong boundaries and will be difficult to reconcile. So for now, the method won't persist any manually written extension attributes and you'd either have to port them over yourself, or use getters and setters.

We're actually thinking about replacing the `Span.as_doc` method with a `Doc.from_span` classmethod, to make it more clear that it creates a new `Doc` based on an existing `Span` (rather than a 1:1 conversion of a `Span`).

> ```python
> assert span.as_doc()[:]._.dict == {"a": 1}     # ok
> ```

I think what you're experiencing here is a quirk of mutable default argument (in this case, an empty dictionary). spaCy's extension attributes behave the same way as regular Python function arguments: https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html (There's a note on this [in the extension guidelines](https://spacy.io/usage/processing-pipelines#extensions), but maybe it's not prominent enough there and should be moved up.)

Here's an example that illustrates the problem:

```python
def test(value, some_dict={}):
    some_dict[value] = True
    print(some_dict)

test(1)  # {1: True}
test(2)  # {1: True, 2: True}
test(3)  # {1: True, 2: True, 3: True}
```

So instead of just updating the instance, `dict["a"]` is updating the *default dictionary*.  In contrast, this example is consistent with the others:

```python
span = nlp("Hello world")[:]
span._.dict = {'a': 1}
print(span._.dict)  # {'a': 1}
print(span.as_doc()[:]._.dict)  # {}
```

To avoid this problem, it's often better to use a different default value (e.g. `None` and then override that with a dictionary), or getters and setters to manage the state explicitly.

**Comment by thomasopsomer** [comment]
Thanks @ines for the explanation. 
Indeed I realize that I played with fire ^^ I was clearly modifying the default values.
Even if being able to copy custom attribute would be helpful, it's actually more clear to perform computation on copies of Doc or Span and store results in the original objects.

As you said the doc is clear on this points ! I haven't read it for a while :)
