### ISSUE TITLE
Feature: `Span.ents` property similar to Doc.ents

### ISSUE THREAD

**Issue by ohenrik** [explosion/spaCy#2589]
It would be nice with a `Span.ents` property like the one on Doc
https://github.com/explosion/spaCy/blob/master/spacy/tokens/doc.pyx#L411

Calling `sent.as_doc().ents` seems to run the entity matcher again and removes custom attributes like `my_entity._.is_special`.

So at the moment you have to manually sort through Doc.ents based on the sent.start and sent.end properties to get the relevant ents for a given sentence correctly. This is not optimal, and a Sent.ents does seem natural :)

**Comment by ohenrik** [comment]
I can create this and submit a pull request, but any hints or tips on how to implement this in a good way is appreciated :)

**Comment by ines** [comment]
Yes, this makes sense. In general, spaCy tries to avoid additional methods for relationships etc. that are easy to compute using the existing data structures, but harmonising the `Doc` and `Span` interface is always good, so yes to `Span.ents`!

Essentially, a span's entities would be computed like this (`< span.end` is important here, because the end indices are *exclusive*):

```python
span_ents = [ent in span.doc.ents if ent.start >= span.start and ent.end < span.end]
```

**Comment by ohenrik** [comment]
I tested this and it seems like i had to use `=< ent.end` to make it work. Or else the last word would not be included, seemed like.
