### ISSUE TITLE
Deprecated and Beta dependencies

### ISSUE THREAD

**Issue by robjog** [explosion/spaCy#2592]
## Feature description

Hi,

I noticed that some dependencies are deprecated or still in beta : 

msgpack-python is deprecated and encourage people to move to msgpack
Murmurhash is still in beta, but I don't see any release since 2 years, do you plan to move it to release ?

The main issue is that in some company we are not allowed to use dependencies which are tagged as deprecated or in beta for production code.

Thanks in advance.

**Comment by ines** [comment]
Thanks for bringing this up!

The latest version of Thinc, which is required by the new spaCy `v2.0.12`, now depends on `msgpack` instead of `msgpack-python` ([see here](https://github.com/explosion/thinc/blob/master/requirements.txt)). So this should be resolved 🙂

Since `murmurhash` is our own library, we're happy to bump it to `v1.0.0`. After all, it's been in use without changes for 2 years, so that can definitely be considered stable.

**Comment by kevinzen** [comment]
I'm having an issue with `v2.0.12` that I've traced into `thinc`. `pip list` shows me:

    msgpack (0.5.6)
    msgpack-numpy (0.4.3.1)
    murmurhash (0.28.0)
    regex (2017.4.5)
    scikit-learn (0.19.2)
    scipy (1.1.0)
    spacy (2.0.12)
    thinc (6.10.3)

I have code that works fine on my Mac, but fails in production. The stack trace goes into `spacy` and then into `thinc` -- and then django literally crashes. This all worked when I used an earlier version of spacy -- this has only come about since I'm attempting to upgrade to `v2.0.12`.

My requirements.txt file has these lines:

    regex==2017.4.5
    spacy==2.0.12
    scikit-learn==0.19.2
    scipy==1.1.0
    https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz

The last line pulls the `en_core_web_sm` down during deployment. I'm doing this so I can get those models loaded on Heroku during deployment. 

I then load the parser like this:

    import en_core_web_sm
    en_core_web_sm.load()

Again -- this all works on my laptop.

Is there something wrong with how I'm loading? Or is my version of `thinc` out of date? If so, what should my `requirements.txt` file look like?

**Comment by honnibal** [comment]
@robjog I think a policy of not using pre-1.0 versions of libraries isn't really viable. Ultimately spaCy is using matrix multiplication kernels from OpenBLAS, which is currently v0.3.2. numpy uses these kernels as well.

We also won't make any policy of notification if we later adopt a new dependency that's pre-1.0. The 1.0 version simply doesn't mean that much --- different libraries use their version numbers differently. Actually the language spaCy is mostly written in (Cython) doesn't even have a 1.0 release...

**Comment by robjog** [comment]
@honnibal @ines Thanks for your time to answer. It was not really about the version 1.0, but that on https://pypi.org/project/murmurhash/ the project has the following development status : Beta

**Comment by ines** [comment]
@robjog Oh, this was probably never updated. Just fixed it (see [`12ca7e7`](https://github.com/explosion/murmurhash/commit/12ca7e7b4773dd9a95815d1f92683626cbeb062c)), so we'll included that in the next release.
