### ISSUE TITLE
Probabilistic cutoff for NER

### ISSUE THREAD

**Issue by danielbyler** [explosion/spaCy#2601]
## Feature description

When the full neural network NERs are rolled out, can you let the user set the cutoff for what minimum probability something has to be in order to get tagged as a named entity? Right now I am working on a largish set of text (a few million pages) and I really wish I could get rid of some of the less good matches even if that meant leaving some real matches on the table.

**Comment by honnibal** [comment]
For efficiency we normally run the NER in "greedy" mode, where it only produces one analysis for the document. This mode doesn't really give anything interpretable as a probability for each entity. You can get probabilities by running the NER with beam search, and using the total score of an entity in the beam as a probability estimate. We do this in our annotation tool [Prodigy](https://prodi.gy). The code looks like this:

```
ner = nlp.get_pipe('ner')
docs = [nlp.make_doc(text) for text in batch]
beams = ner.beam_parse(docs, beam_width=16)
for beam in beams:
    entities = ner.moves.get_beam_annot(beam)
```

The `entities` variable there should be a dictionary mapping `(start, end, label)` offsets to scores. However, the greedy model hasn't been trained with a global objective, so these scores aren't especially meaningful unless you also perform some iterations of beam training as well. The beam parsing is also expected to be about 16x slower (maybe a little less), as we're evaluating the model once for each state in each beam.

None of these are very satisfying solutions. The best solution is actually to make the model better on your data, rather than to try to get well-calibrated probability estimates and then pick a better precision/recall tradeoff.

You might try doing some error-mining on your texts, to try to common prominent errors to correct. These can be used to apply a rule-based pre- or post-process. You can also update the model using examples from your data.

**Comment by danielbyler** [comment]
Thanks!
