### ISSUE TITLE
Manual sentence boundary setting should work with different custom characters 

### ISSUE THREAD

**Issue by davidefiocco** [explosion/spaCy#2602]
## How to reproduce the behaviour

I tried changing the boundary token in the example on the SpaCy website https://spacy.io/usage/linguistic-features#section-sbd, putting `!!!` instead of `...` as custom sentence boundary. If I run

```
import spacy

text = u"this is a sentence!!!hello!!!and another sentence."

nlp = spacy.load('en_core_web_sm')
doc = nlp(text)
print('Before:', [sent.text for sent in doc.sents])

def set_custom_boundaries(doc):
    for token in doc[:-1]:
        if token.text == '!!!':
            doc[token.i+1].is_sent_start = True
    return doc

nlp.add_pipe(set_custom_boundaries, before='parser')
doc = nlp(text)
print('After:', [sent.text for sent in doc.sents])
```
I get 
```
Before: ['this is a sentence!!!hello!!!and another sentence.']
After: ['this is a sentence!!!hello!!!and another sentence.']
```
Whereas the intended behavior would be
```
Before: ['this is a sentence!!!', 'hello!!!and another sentence.']
After: ['this is a sentence!!!', 'hello!!!', 'and another sentence.']
```
This also happens with other custom tokens such as `@@@` or `~~~`. `---` works fine instead!

## My Environment
The binder container at spacy.io at https://spacy.io/usage/linguistic-features#section-sbd

**Comment by ines** [comment]
> This also happens with other custom tokens such as @@@ or ~~~. --- works fine instead!

It looks like the problem here is that you're comparing `token.text == '!!!'`. However, the string `!!!` isn't split, so the condition will never be true:

```python
doc = nlp(u"this is a sentence!!!hello!!!and another sentence.")
print([token.text for token in doc])
# ['this', 'is', 'a', 'sentence!!!hello!!!and', 'another', 'sentence', '.']
```

To change this behaviour, you can customise the tokenizer infixes and include `!`. Still, in that case, `token.text == '!!!'` wouldn't be true, either, since there wouldn't be a single token with the text `!!!`, and instead, 3 tokens with the text `!`.

Another thing that's worth noting is that `...` and `---` are both tokenizer exceptions, since they commonly represent single punctuation units (`…` and `—`), and usually shouldn't be treated as three characters.

**Comment by davidefiocco** [comment]
Danke Ines, think I got it. The fact that that example gave me in output qualitatively different things with different choices of `token.text` confused me, but it makes more sense now.
