### ISSUE TITLE
Sentence vectors are sensitive to word order

### ISSUE THREAD

**Issue by ellliottt** [explosion/spaCy#2611]
## How to reproduce the behaviour
```
import spacy
nlp = spacy.load('en_core_web_sm')
a = nlp('the test sentence')
b = nlp('the sentence test')
print(a.vector[:4])
print(b.vector[:4])
print(a.similarity(b))
```

Based on the documents, I inferred that sentence vectors would give the average of the word vectors. But this example shows that the vectors are sensitive to word order. How are sentence vectors constructed?

## Your Environment
* **spaCy version:** 2.0.11
* **Platform:** Linux-4.13.0-46-lowlatency-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.5
* **Models:** en

**Comment by honnibal** [comment]
This is a quirk of the `sm` models. We'd like to change this behaviour in v3 --- I think it was a bad idea.

The issue arises because the `.vector` and `.similarity` methods fall back to the contextual vector representations used by the parser, tagger and NER models if the word vectors are not available. This occurs in the `sm` models. I think this behaviour is confusing and generally not  very helpful, so I'm keen to change it in v3.

For now, you can avoid the problem by using an `md` model.
