### ISSUE TITLE
Sentence detection is broken when a second sentence starts with a quotation mark.

### ISSUE THREAD

**Issue by mikpanko** [explosion/spaCy#2619]
## How to reproduce the behaviour
Running sentence boundary detection on the 2 sentences below produces 3 sentences in spaCy:

> Try it now. “Synonyms” behave differently from other metrics.
> --->
> Try it now.
> “
> Synonyms” behave differently from other metrics.

Note that the quotation marks here are unicode values 8220 and 8221.

Running sentence boundary detection on the same 2 sentences with unicode value 34 quotation marks produces 2 sentences but the boundary is still incorrect:

> Try it now. "Synonyms" behave differently from other metrics.
> --->
> Try it now. "
> Synonyms" behave differently from other metrics.

## Your Environment

* Operating System: MacOS High Sierra
* Platform: Darwin-17.7.0-x86_64-i386-64bit
* Python Version Used: 2.7.15
* spaCy Version Used: 2.0.12

**Comment by honnibal** [comment]
Hey,

I've added an example showing how to add some rule-based processing to improve this on your data: https://github.com/explosion/spaCy/blob/master/examples/pipeline/custom_sentence_segmentation.py

It's difficult to make a single statistical model perform well across all texts, because of the different conventions that can be involved. So adding rules for your text will probably be helpful.

**Comment by mikpanko** [comment]
Thank you!
