### ISSUE TITLE
Question on training accuracy

### ISSUE THREAD

**Issue by vivekam101** [explosion/spaCy#2622]
Post training, i do see model folder saved to disk and does the below meta json section in the model folder refer to training cv accuracy? 
***
  "accuracy":{
    "ents_f":85.2975560875,
    "ents_p":84.9664503965,
    "token_acc":99.8698372794,
    "las":89.800872413,
    "tags_acc":97.0403350292,
    "uas":91.7237657538,
    "ents_r":85.6312524451
  },
***
Thanks 

## Which page or section is this issue related to?
https://spacy.io/usage/training

**Comment by ines** [comment]
Yes, those numbers will be added automatically if you run `spacy train`, and they should match the accuracy that was printed after training. The numbers reflect the accuracy of the individual components on the specified evaluation data.

If you just update the model with a few examples using your own script, those numbers won't be changed because spaCy has no way of knowing the accuracy of your new model on the original (or any other) evaluation set. However, if you run your own evaluation, you can always write to `nlp.meta['accuracy']` yourself.

**Comment by vivekam101** [comment]
Thanks ines for the quick reply. One more thing i prepared the dataset in below format
('stringent quality control since including separating cosmetic and food grade talc from industrial grade talc has eliminated this issue but it re', {'entities': [(76, 80, 'CHEMICAL'), (103, 107, 'CHEMICAL')]})

Is there an easy way to convert this to json format so that i can run spacy train from command line? 

Thanks

**Comment by ines** [comment]
For details on how to convert data from different formats, see the converters:
https://spacy.io/api/cli#convert

The upcoming version will also introduce a more straightforward JSON format for training that's hopefully much easier to work with. See #2928 for details.
