### ISSUE TITLE
Inconsistent sentence segmentation if sentence contains quotes

### ISSUE THREAD

**Issue by hoonkai** [explosion/spaCy#2627]
## Your Environment

* Operating System: Ubuntu 17.10
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0.12

I've noticed sentence segmentation can be quite inconsistent for certain constructions. For instance:

```python
raw_text = "Been here and I am loving it."
doc = nlp(raw_text)
sentences = [sent.string.strip() for sent in doc.sents]
print(sentences)
['Been here and I am loving it.']
```

But if
```python
raw_text = "Been here and I'm loving it."
```

two sentences are returned:

```python
['Been here', "and I'm loving it."]
```

Does anyone know why this is the case?

Thanks

**Comment by honnibal** [comment]
Hmm! I can't reproduce this on that specific sentence. Could you run `python -m spacy validate` and `python -m spacy info`? Something might be wrong.

Here's the general answer for sentence boundary detection mistakes, and how to improve them. But I do think something might be wrong on the case you give, since on my machine it's parsing correctly with v2.0.12 on both the `en_core_web_sm` and `en_core_web_md` models.

The sentence boundary detection is done jointly with parsing, so it's influenced by the parser's decisions about how the sentence is structured. Sometimes when the parser makes a mistake, it ends up in a weird state and inserts a sentence boundary.

If you know more about the sentence structure (e.g. you know you can trust punctuation), you can prevent the parser from making sentence segmentations by writing to the `token.is_sent_start` attribute. You would insert a pipeline component to do this, like so:

```python

def prevent_sentence_boundaries(doc):
    for token in doc:
        if not can_be_sentence_start(token):
            token.is_sent_start = False
    return doc

def cant_be_sentence_start(token):
    if token.i == 0:
        return True
    elif token.is_title:
        return True
    elif token.nbor(-1).is_punct:
        return True
    elif token.nbor(-1).is_space:
        return True
    else:
        return False

nlp = spacy.load('en')
nlp.add_pipe(prevent_sentence_boundaries, before='parser')
```

**Comment by honnibal** [comment]
Ah, I should've guessed.

I doubt there's an interesting reason why the example ends up incorrect. Statistical models are just like that sometimes, unfortunately.

The function I gave should work, if you have some heuristics for words which cannot be sentence boundaries.

**Comment by hoonkai** [comment]
I'm now using `md` and I've discovered some other potential inconsistencies:

```python
raw_text = "Loved it!It was excellent."
doc = nlp(raw_text)
sentences = [sent.string.strip() for sent in doc.sents]
print(sentences)

raw_text = "Loved it.It was excellent."
doc = nlp(raw_text)
sentences = [sent.string.strip() for sent in doc.sents]
print(sentences)

['Loved it!It was excellent.']
['Loved it.', 'It was excellent.']
```

I wonder why it fails to split the '!' version.

**Comment by honnibal** [comment]
The `!` version is a tokenization failure, I think.

**Comment by hoonkai** [comment]
> The ! version is a tokenization failure, I thin

Right. But it shouldn't be a failure, right? Is there a custom solution so that `\w\!\w` is treated the same as `\w\.\w`?
