### ISSUE TITLE
`a/DET` has `going to` as its lemma

### ISSUE THREAD

**Issue by kbulygin** [explosion/spaCy#2649]
## How to reproduce the behaviour

While processing a list of words, I've stumbled upon the word `i'ma` (it's probably `I'm a`). The word is divided into three tokens (`i`, `'m`, `a`). The reported lemma of the last token (`going to`) is problematic in several aspects:
- This meaning of `a` is unlikely here.
- The lemma is inconsisted with the guessed POS (`DET`).
- The lemma contains a space.

```python
>>> nlp = spacy.load('en_core_web_sm')
>>> doc = nlp("i'ma")
>>> list(doc)
[i, 'm, a]
>>> [t.lemma_ for t in doc]
['-PRON-', 'be', 'going to']
>>> [t.pos_ for t in doc]
['PRON', 'VERB', 'DET']

>>> nlp = spacy.load('en_core_web_lg')
>>> doc = nlp("i'ma")
>>> list(doc)
[i, 'm, a]
>>> [t.lemma_ for t in doc]
['-PRON-', 'be', 'going to']
>>> [t.pos_ for t in doc]
['PRON', 'VERB', 'DET']
```

## Info about spaCy
* **spaCy version:** 2.0.11
* **Platform:** Linux-3.16.0-4-amd64-x86_64-with-debian-8.8
* **Python version:** 3.6.0
* **Models:** en_core_web_lg, en_core_web_sm

**Comment by ines** [comment]
Thanks for the report – this is a good point!

It looks like "im'a" uses the same tokenizer exception as "imma", which is supposed to handle cases like  "imma let you finish" &rarr; "i am going to let you finish". Because the `ORTH` values of the split tokens always need to match the original string, we end up with tokens `[i, 'm, a]`.

It makes sense that the tagger predicts `DET` for `"a"` (even in cases where this would be incorrect). We'll have to think about how we want to handle that kinda stuff going forward, but for now, I think it'd make the most sense to just remove the pre-set `LEMMA` from that tokenizer exception.

**Comment by kbulygin** [comment]
Thanks for the reply. With cases like "imma = I'm gonna", the behavior starts to make some sense. By the way, the word `ima` (which is likely to be treated as a lowercased initialism) is processed like `i'ma`. Also, `gonna` is processed not as a single token with the lemma `going to`, but as two tokens.

**Comment by plison** [comment]
I also found a similar problem/bug, this time with a completely innocuous sentence, "this is a test":

```python
nlp = spacy.load("en_core_web_md")
for x in nlp("This is a test."):
    print(x.text, x.tag_, x.norm_)
```
gives a very strange result for the normalised form of a/DET:
```
This DT This
is VBZ is
a DT gonna
test NN test
```

**Comment by honnibal** [comment]
See here for the explanation for this weird bug: https://github.com/explosion/spaCy/pull/3029

Thanks for reporting; will be fixed in the next nightly.
