### ISSUE TITLE
Training a Dependency Parser from scratch does not appear to handle sentence boundaries well.

### ISSUE THREAD

**Issue by DeNeutoy** [explosion/spaCy#2652]
## How to reproduce the behaviour

Hey! Thanks for the _awesome_ library.

We have trained a dependency parser on the GENIA 1.0 trees (converted from phrase structure trees using Stanford Core NLP) and then converted to the spacy training format using `spacy convert`. From the spacy docs, it seems like the dependency parser should be identifying sentence boundaries - however, our trained model (which is a good dependency parser, ~ 90 UAS on biomedical data) does not set sentence attributes. Is there some flag which is required to get the dependency parser to do this? 

We've found a workaround by using the `sentencizer`  - perhaps this is now the recommended way to do sentence boundary detection?

## Info about spaCy

* **spaCy version:** 2.0.12
* **Platform:** Darwin-15.6.0-x86_64-i386-64bit
* **Python version:** 3.6.6
* **Models:** en_core_web_sm

**Comment by honnibal** [comment]
Hi @DeNeutoy 

Sorry for the delay getting back to you on this. You need to provide data with multiple sentences per document. The simplest way to do this is to use the `-n ` argument on the `spacy convert` command when you create the data. This will merge adjacent sentences together into one document.

An even better solution is if you can somehow get the raw text. This is better because you can train from real documents, just as you would see during training. Unfortunately the field is terrible about this --- everyone throws away the original text :(.

If you can get the original text, spaCy v2.1.0a1 now comes with a handy utility to generate the training data. The `spacy.gold.docs_to_json` command lets you turn a list of `Doc` objects into the (admittedly annoying) json data format spaCy uses for training. This lets you set up the `Doc` objects using the normal API. For instance, you can create an array of head offsets, and then use the `doc.from_array()` function to create a `Doc` object that has the correct parse.

**Comment by DeNeutoy** [comment]
@honnibal No problem, it wasn't massively urgent - it was for a hackathon project to build a biomedical version of spacy (we got pretty far with it, and it's possible some people internally are going to pick it up and run with it). The other large problem that we ran into is that the parser/NER models have global state for the transition sequences on the `Doc`, which means that you can't have multiple NER models in the same pipeline without doing some serious trickery, because otherwise they clobber each other. Is there an easy way around that too?

I like fixes that just require adding a command line flag though!
