### ISSUE TITLE
Prevent entity recognition on some words

### ISSUE THREAD

**Issue by romikforest** [explosion/spaCy#2660]
I've merged some bad html to tokens and marked them as stop words as written in documentation. I've even placed BadHTMLMerger at the beginning of the pipe.  But now entity recognizer marks some of the as organizations. How can I prevent this behaviour?

spacy 2.0.11, python Python 3.6.6 :: Anaconda custom (64-bit), win 10 64 bit

**Comment by ines** [comment]
Yeah, the model likely hasn't seen very much of this during training, so it now predicts those spans as `ORG`s. The simplest solution would be to just filter the entities, and explicitly remove any spans that you know are definitely not entities. The `doc.ents` are writable, so you could do something as simple as this:

```python
def tidy_up_entities(doc):
    bad_ents = ('<br>', '<br/>')
    doc.ents = [ent for ent in doc.ents if ent.text not in bad_ents]
    return doc
```

If you can narrow down the category and filter based on the token or span text, there's really nothing wrong with a simple rule-based approach. 

If you want to teach the model to stop predicting those spans as entities in the first place, you can also update it with more examples that include your "bad HTML spans", and *don't* have them labelled as entities. The nice thing here is that you can use your existing matcher rules and logic to find suitable sentences. [See here](https://spacy.io/usage/training#section-ner) for more details on how to update the entity recognizer. Since bad HTML is pretty distinct, you might already see pretty good results with only a small number of examples.
