### ISSUE TITLE
stop words and similarity of two documents

### ISSUE THREAD

**Issue by romikforest** [explosion/spaCy#2677]
Hi!
Does spacy look for stop words when it checks similarity of two documents?
I noticed, that stop words are not marked automatically for en_core_web_lg model, but they are marked for sm model (in low case only). So I have added stop words to my vocab manually (as I try to use lg model). I'v added them in three variants: lower, upper and capitalized. Then I compare two obviously similar phrases. But when I add to one of them words form my stop list: 'Please can you', built-in similarity method shows low level of similarity. So to check a similarity of two documents do I have to delete stop words manually ?   
spacy 2.0.11, python Python 3.6.6 :: Anaconda custom (64-bit), win 10 64 bit

**Comment by honnibal** [comment]
No, stop words aren't filtered out by default when creating the document vectors, which are used in the similarity calculation. So changing the stop words shouldn't affect how the model calculates similarity.

Btw, the stop words bugs should finally be fixed in v2.1.0. You can try out an alpha release by running `pip install spacy-nightly`.
