### ISSUE TITLE
Splitting doc to sentences 

### ISSUE THREAD

**Issue by mattkallo** [explosion/spaCy#2708]
Hi,

When I split the below document to sentences, I am getting incorrect sentences. Could you pls check?

"Iterate over the sentences in the document. Sentence spans have no label. To improve accuracy on informal texts, spaCy calculates sentence boundaries from the syntactic dependency parse. If the parser is disabled, the sents iterator will be unavailable."

>     for sent in doc.sents:
>         print(sent.text)

Expected: 
- Iterate over the sentences in the document. 
- Sentence spans have no label. 
- To improve accuracy on informal texts, spaCy calculates sentence boundaries from the syntactic dependency parse.
-  If the parser is disabled, the sents iterator will be unavailable.

What I am getting is as below - 
- Iterate over the sentences in the document.
- Sentence spans have no label. 
- _To improve accuracy on informal texts,_
- _spaCy calculates sentence boundaries from the syntactic dependency parse._
- If the parser is disabled, the sents iterator will be unavailable.

## Info about spaCy

* **Python version:** 2.7.10
* **Platform:** Darwin-17.7.0-x86_64-i386-64bit
* **spaCy version:** 2.0.5
* **Models:** en_glove_cc_300_1m_vectors-1.0.0, en-1.1.0, en_core_web_lg, en, __cache__

(Edited - Changed the question)

**Comment by gavrieltal** [comment]
On the current development master (pulled today, October 1st, 2018) using Python 3.6, I had no problem with the sentencizer.

```
>>> import spacy; from spacy.lang.en import English; nlp = English()
>>> nlp.add_pipe(nlp.create_pipe('sentencizer'))
>>> doc = nlp('Iterate over the sentences in the document. Sentence spans have no label. To improve accuracy on informal texts, spaCy calculates sentence boundaries from the syntactic dependency parse. If the parser is disabled, the sents iterator will be unavailable.')
>>> for sent in doc.sents:
...     print(sent.text)
... 
Iterate over the sentences in the document.
Sentence spans have no label.
To improve accuracy on informal texts, spaCy calculates sentence boundaries from the syntactic dependency parse.
If the parser is disabled, the sents iterator will be unavailable.
>>> 
```

**Comment by ines** [comment]
If you're using a model with a `parser`, sentence boundaries are detected using the dependency parse. This can often produce significantly better results than using other rule-based strategies. But it also means that it can sometimes be incorrect – for example, if the dependency parse is predicted incorrectly by the statistical model.

The `sentencizer` component on the other hand is a hook for custom sentence boundary detection logic and splits on punctuation by default. Since the example sentences here are pretty straightforward (short sentences, all ending in periods), it seems to perform better on these examples. So if you're mostly dealing with texts like this and are fine with a simpler sentence splitting strategy, you could add the `sentencizer` component to your pipeline.

Here's a more detailed example of how to set custom sentence boundaries *before* parsing to both get more accurate `doc.sents` and dependency predictions: https://github.com/explosion/spaCy/blob/master/examples/pipeline/custom_sentence_segmentation.py
