### ISSUE TITLE
Linking: Enable model linking using relative_path_to_model_dir

### ISSUE THREAD

**Issue by singh-abhijeet** [explosion/spaCy#2716]
## Feature description (Options)
1. Linking model directory using relative path should work (Currently only absolute path works, v 1.10.0)
or
2. Give relevant (FAILURE) message when `link` is executed with relative model path as argument (Currently gives success message: `Linking successful`)

## Example
`python -m spacy link language-models/en_core_web_md-1.2.1 en_core_web_md` should append curr_working_dir with relative path (language-models/en_core_web_md-1.2.1) and complete linking procedure.

**Comment by honnibal** [comment]
We need some way to distinguish string-names of the models from paths in the link command. It's not perfect, but at least using absolute paths works and is unambiguous.

**Comment by ines** [comment]
@honnibal I don't think this is really the issue here! Relative paths should work, and there also shouldn't be a conflict, because shortcut links any anything in the data directory will always have precedence over installed packages ([see here](https://github.com/explosion/spaCy/blob/aeba99ab0d9cf3967ef54f3a1c509c9d496ce4b3/spacy/util.py#L110)).

@singh-abhijeet I'm surprised that this *doesn't* currently work as expected, because it should. I think it might be related to how the symlinks are created and that they aren't always resolved correctly?

If you link a valid relative path, spaCy checks if the path exists (which it will) and throws an error it it doesn't. After that, it checks a bunch of stuff related to the destination and then creates a symlink to the relative path. Maybe we do need to resolve the relative path to an absolute path before – but I'm not 100% sure that's really necessary.
