### ISSUE TITLE
Issue with Multi Word NER Model

### ISSUE THREAD

**Issue by surajurao** [explosion/spaCy#2723]
I am trying to train a new NER entity called NEWS_ORGANIZATION for the entity 'New York Times'. The issue I am facing is after generating the model, if I pass an example like 'I live in New York', the model recognizes 'New York' as NEWS_ORGANIZATION. How can I only match entities with exact match? I am following the below example for training the new entity https://github.com/explosion/spaCy/blob/master/examples/training/train_new_entity_type.py

* Operating System: Windows 7
* Python Version Used: Python 3.4
* spaCy Version Used: 2.0.11

**Comment by ines** [comment]
Models are *statistical* and the goal of named entity recognition is to *generalise* based on a few examples. So if you've updated your model with only a few examples of "New York Times" in context, it's possible that your model now guesses that "New York" is also a `NEWS_ORGANIZATION`. Changing spaCy's NER predictions from one scheme to a completely different one requires a lot of examples, so chances are that your training set was way too small to enable to model to learn meaningful things.

If your entity names follow a consistent scheme, a rule-based approach might actually be a better place to start. Instead of using a statistical model, you'd use the `Matcher` to find entities in your text, and then add them to the `doc.ents` property. More info:

* [Documentation: Rule-based matching](https://spacy.io/usage/linguistic-features#section-rule-based-matching)
* [Interactive demo: Rule-based Matcher explorer](https://explosion.ai/demos/matcher)
* [Documentation: Custom pipeline components](https://spacy.io/usage/processing-pipelines#custom-components)
