### ISSUE TITLE
Not getting expected chunk as nsubj from a sentence

### ISSUE THREAD

**Issue by sannithvitta** [explosion/spaCy#2739]
## How to reproduce the behaviour

Code Snippet:
doc = nlp(u"No aspect of life goes untouched by social class.")
			for chunk in doc.noun_chunks:
				print(chunk.text,"-----", chunk.root.dep_)

I am trying to extract the nsubj of a sentence .Few cases I am not getting the expected word chunk as subject. For example
1) "No aspect of life goes untouched by social class." In this I need "life" should be the subject but through spacy noun chunks I am getting "No aspect" as subject.
O/p:No aspect ----- nsubj
life ----- pobj
social class ----- pobj

2) Nature’s gentle touch products are manufactured in Nigeria and South Africa.
In this case I am getting "Nature" as nsubj instead of "Nature’s gentle touch products"
O/p: Nature ----- nsubj
gentle touch products ----- nsubjpass
Nigeria ----- pobj
South Africa ----- conj

Note: In the second example I have noticed that if the apostrophe after "Nature" is of the form " ' " I am getting correct subject but if it is " ’ "  then I am getting Nature as subject. 

May I know what was the problem whether the issue with the parser or any specific condition I am missing.

Thank you in Advance.

## Your Environment

* Operating System: Linux-4.4.0-124-generic-x86_64-with-Ubuntu-16.04-xenial
* Python Version Used: Python 3.5.2
* spaCy Version Used: 2.0.12
* Environment Information: virtual Environment with en_core_web_lg as loaded model.

**Comment by honnibal** [comment]
> "No aspect of life goes untouched by social class." In this I need "life" should be the subject but through spacy noun chunks I am getting "No aspect" as subject.

The model is performing according to the annotation scheme here. The syntactic subject of "untouched" is "aspect" here. "of life" attaches to it as a prepositional phrase. You can check this by comparing with the sentence "aspects of life go untouched by social class" -- the verb agrees with the subject in number.

> Nature’s gentle touch products are manufactured in Nigeria and South Africa.

This is a weird construction, because Nature's Gentle Touch is presumably a named entity functioning as a nominal modifier. This is the sort of thing the model is likely to struggle with. If you know you have certain entities in your data and you can merge them into a single token, you might get better performance in the parser.

In general, the models are statistical, so some inaccuracies are expected. In other cases the decisions in the annotation scheme can be a bit subtle, so even if the parser doesn't do what you expect, it may be because you have the wrong expectation.
