### ISSUE TITLE
Bad similarity results in fr_core_news_md model

### ISSUE THREAD

**Issue by mauryaland** [explosion/spaCy#2773]
## How to reproduce the behaviour

I have noticed that every french word tokens in the model fr_core_news_md-2.0.0 is considered out of vocabulary. Therefore, some token methods such as token.cluster are not giving any information. 

Please, find below comparison between the English model en_core_web_md-2.0.0 and the French one mentioned above:

```python
nlp_en = spacy.load('en_core_web_md')

doc_en = nlp_en('cat dog human eat')

for token_en in doc_en:
    print(token_en.vector_norm, token_en.cluster, 
          token_en.prob, token_en.is_oov)
```
    6.6808186    37        -9.517606735229492    False
    7.0336733    37        -9.035931587219238    False
    6.869779      823      -8.85946273803711      False
    6.9718246    3850    -8.822906494140625    False

```python
nlp_fr = spacy.load('fr_core_news_md')

doc_fr = nlp_fr('chat chien humain manger')

for token_fr in doc_fr:
    print(token_fr.vector_norm, token_fr.cluster, 
          token_fr.prob, token_fr.is_oov)
```
    5.5223203   0  -20.0  True
    17.761232   0  -20.0  True
    7.893892     0  -20.0  True
    5.471738     0  -20.0  True

Moreover, the performance of the token.similarity method seems impacted:

```python
# Similarity between 'cat' and 'dog'
doc_en[0].similarity(doc_en[1])
```
    0.80168545

```python
# Similarity between 'chat' and 'chien'
doc_fr[0].similarity(doc_fr[1])
```
    0.21475194

Another example:

```python
queen, _, king = nlp_en('queen and king')
queen.similarity(king)
```
    0.72526103

```python
reine, _, roi = nlp_fr('reine et roi')
reine.similarity(roi)
```
    0.23454674

I wonder if this behavior is inherent to the model or if there is a bug?

Thank you in advance for your clarifications.

## Your Environment

* **spaCy version:** 2.0.12
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.6.5
* **Models:** en_core_web_md, fr_core_news_md

**Comment by ines** [comment]
The OOV issue should be fixed in the latest nightly models! Thanks for your patience on this.

```python
>>> nlp = spacy.load("fr_core_news_md")
>>> doc = nlp("chat chien humain manger")
>>> [t.is_oov for t in doc]
[False, False, False, False]
```

However, I just tested the similarity queries and I'm getting the same results 🤔 So the good news is, it's not related to the OOV issue. The bad news is... it's something else in the models. I'll rename the issue to reflect this problem and we'll keep investigating this.

**Comment by MariusMez** [comment]
Hi, I'm currently facing same problem with this code using spacy v2.0.18

```
queries = [w for w in word.vocab if w.is_lower == word.is_lower and w.prob >= -15]
by_similarity = sorted(queries, key=lambda w: word.similarity(w), reverse=True)
synonyms = [w.lower_ for w in by_similarity]
```

It's working well with en_core_web_lg:v2.0.0 (latest)
but not with fr_core_news_md:v2.0.0 (latest) unless I switch `w.prob >= -15` with `w.prob >= -20` but in these case it's very long to process

Maybe this issue which seems related can help you: https://github.com/explosion/spaCy/issues/1590 (it doesn't seems the french model has been updated since that time: https://github.com/explosion/spacy-models/releases//tag/fr_core_news_sm-2.0.0)

**Comment by honnibal** [comment]
Merging with #3052 , the model inaccuracies master thread.
