### ISSUE TITLE
Can't create a custom model for detecting "Organizations".

### ISSUE THREAD

**Issue by lakshay1296** [explosion/spaCy#2789]
I can't create a custom model using Spacy. I have used the code given in the official documentations of <a href = "https://spacy.io/usage/training"> Spacy </a> under the <a href = "https://spacy.io/usage/training#example-train-ner">Updating the Named Entity Recognizer</a> section.
I have used the same code, I have just changed the Training data with mine. While testing the model it is creating tokens but not the entities. Any help will be appriciated.

## Your Environment

* Operating System: Windows 10
* Python Version Used: python- 2.7 (Anaconda2)
* spaCy Version Used: 2.0.12
* Environment Information: Pycharm Community 

I have attached the code below.
[Model.txt](https://github.com/explosion/spaCy/files/2406380/Model.txt)

**Comment by ines** [comment]
Did you only use those two examples? And did you start with a blank model? The example is only supposed to be a simple demonstration – in a real-world scenario, you definitely need a lot more training data. The pre-trained English models for instance are trained on tens of thousands of examples. So if you show a completely blank model two instances of an `ORG` entity, it's expected that it won't be able to generalise based on the example. Similarly, by default, the model is also discouraged from simply memorizing the entities, because that's usually not what you want.

If you want to recognise organizations, try starting with the pre-trained `en_core_web_sm` model that already knows a lot about `ORG`, and improve it by adding more data specific to your domain. For more details on training, including tips for how to source training data, see this docs page: https://spacy.io/usage/training
