### ISSUE TITLE
Can't Pickle with Pyspark & spaCy version 2.0.12

### ISSUE THREAD

**Issue by bairathirahul** [explosion/spaCy#2819]
Hi,

I am facing this error  while using the textcat model with Apache Spark

`PicklingError: Can't pickle <cyfunction LinearModel.<lambda> at 0x10487c498>`

**Comment by honnibal** [comment]
This should be fixed in the latest `spacy-nightly`.

Note that pickle isn't necessarily the best way to use spaCy with Spark. You should be careful that you don't incur too much saving and loading overhead. It's often best to put the model in the global scope, so that it's not loaded on each document.
