### ISSUE TITLE
Unable to pickle a Token

### ISSUE THREAD

**Issue by harrybraviner** [explosion/spaCy#2833]
I'm unable to serialize `Token`s. I think this used to work in an earlier version, since I get this exception from a friend's code that used to work fine. I suspect issue #2819 is a manifestation of the same problem, but with Spark wrapping the error message.

## How to reproduce the behavior

```
import spacy, pickle
nlp = spacy.load('en')
doc = nlp("Hello, world")

with open("test_pckl", "wb") as fh:
    pickle.dump(doc[0], fh)
```

## Your Environment

* **spaCy version:** 2.0.12
* **Platform:** Linux-4.10.0-28-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.5
* **Models:** en
* **pickleshare version:** 0.7.5 (also tested with 0.7.4)

**Comment by bennygjohnson** [comment]
Hi, is there any update on this issue? I'm still encountering it in version 2.0.18.

**Comment by ines** [comment]
I think the main problem here is that spaCy doesn't really raise its own helpful error and the default error is kinda cryptic. 

A token is only a view of the `Doc` so it can't really exist on its own. There's also no proper way to restore it, because it always needs the `Doc` and the `Vocab` as its context. So if you were to pickle a `Token`, the resulting data would be huge, because it'd have to include the `Doc` and the `Doc`'s `Vocab`. This is very confusing and there's not really a benefit to serializing a token over serializing the parent `Doc`, because you'd always be pulling in the parent `Doc` anyways.

I'll try to come up with a good error message that gets this across and implement that in `Token.__reduce__`.

**Comment by bennygjohnson** [comment]
OK, thanks for the clarification. That helps.
