### ISSUE TITLE
No result for doc.ents

### ISSUE THREAD

**Issue by vivekbharti31** [explosion/spaCy#2864]
## How to reproduce the behaviour

I am working on spacy en model on windows 10. I am working on jupyter notebook and I am unable to see any results when I run 'doc.ents'. When I am runnning the command 'python -m spacy info --markdown' I am seeing that even after getting a message about successfully linking en model to spacy I am not getting any list of models linked to my spacy.

for ent in doc.ents:
    print ("{} is of entity type {}".format(ent.label_, ent.texxt) )
## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0.12
* Environment Information:

**Comment by ines** [comment]
Well, what text are you analysing? spaCy's pre-trained models are statistical and predict whether a text contains named entities or not. It's totally possible that the model doesn't recognise any entities in your text. Try if any of the examples from the docs and see if they produce the same results. For more details on updating model with more examples to perform better on your data, see the documentation on training: https://spacy.io/usage/training

If you're able to load a model via `spacy.load()` without errors, the model definitely exists in your environment – otherwise, spaCy will raise an error.
