### ISSUE TITLE
Improper tokenization when using Tokenizer() instantiation

### ISSUE THREAD

**Issue by christian-storm** [explosion/spaCy#2874]
In construction 1 in the documentation at https://spacy.io/api/tokenizer a tokenizer instance 
can be created like so:
```python
from spacy.tokenizer import Tokenizer
tokenizer = Tokenizer(nlp.vocab)
```

Even with the additional model load step, the Tokenizer instance doesn't tokenize properly.
## How to reproduce the behaviour
```python
import spacy
from spacy.tokenizer import Tokenizer

nlp = spacy.load('en_core_web_sm')
tok = Tokenizer(nlp.vocab)
print([t.text for t in tok("Nowadays, it's a sentence.")])
print([t.text for t in nlp("Nowadays, it's a sentence.")])
```
['Nowadays,', "it's", 'a', 'sentence.']
['Nowadays', ',', 'it', "'s", 'a', 'sentence', '.']

## Your Environment

* **spaCy version:** 2.0.16
* **Platform:** Darwin-18.0.0-x86_64-i386-64bit
* **Python version:** 3.7.0
* **Models:** en_core_web_md, es_core_news_md, en_core_web_lg, en_core_web_sm

**Comment by ines** [comment]
The problem here is that you're only instantiating the tokenizer with the vocab, but not with any of the rules. That's still valid, but will produce different results than a tokenizer that does have rules defined, like the tokenizer that's constructed by the `English` language class. The [custom tokenization docs](https://spacy.io/usage/linguistic-features#native-tokenizers) have a standalone example of how a `Tokenizer` class can look with the respective rules.
