### ISSUE TITLE
load custom pipelines

### ISSUE THREAD

**Issue by thiagoananias** [explosion/spaCy#2891]
Hello, i'm testing a custom component with the code from the documentation
https://spacy.io/usage/processing-pipelines#custom-components

The animal example

> nlp = spacy.load('en_core_web_sm')
> terms = (u'cat', u'dog', u'tree kangaroo', u'giant sea spider')
> entity_matcher = EntityMatcher(nlp, terms, 'ANIMAL')

The thing is...i want the same behavior of this example, but for an ARTIST list of 1.6M artists.

i've tested with 8.000 thousand names and it was fast to start... but with this huge number it is running in my machine for about 1 hour and it is still starting...

Is there a way to "save" the configuration to load all the names everytime?

thanks!

## Your Environment
* **spaCy version:** 2.0.16
* **Platform:** Darwin-17.7.0-x86_64-i386-64bit
* **Python version:** 3.7.0
* **Models:** en, pt

**Comment by thiagoananias** [comment]
It took 6 hours to just init

**Comment by ines** [comment]
We're working on more efficient serialization of the `PhraseMatcher` (see #1971), which should help with that.

Another thing that previously wasn't 100% clear in the docs and has since been fixed: When creating the patterns on initialization, use `nlp.make_doc` or `nlp.tokenizer.pipe` instead of `nlp`. The patterns only need to be tokenized, so applying the whole pipeline is uneccessarily slow. `tokenizer.pipe` processes the texts as a stream, so this might be even faster.

```python
# Version 1
patterns = [nlp.make_doc(term) for term in terms]

# Version 2
patterns = list(nlp.tokenizer.pipe(terms))
```
