### ISSUE TITLE
Shared representation unclear at training

### ISSUE THREAD

**Issue by einarbmag** [explosion/spaCy#2893]
I currently a bit confused about what the level of shared weights/representation is between the different components (tagger/ner/text classification). Consequently, _I'm not sure whether first training the NER and then training a text classification component is any different from training both at the same time._

 

My confusion stems from @honnibal's recent comment on an issue (https://github.com/explosion/spaCy/issues/2267):

> The update_shared argument is no longer current, as the pipeline now uses independent models for the parser, tagger and entity recognizer. Apologies for the confusion!

 

My understanding was that v2.0 brought a massive reduction in model size mainly due to sharing of weights. I would therefore think that training towards two tasks simultaneously (i.e. multitask training) could yield some improvements. But the above comment makes it a bit unclear. I think the documentation would do well with a clear diagram to explain what the connection is between the different components. Is it currently possible to update the shared weights when training two different components simultaneously?

**Comment by honnibal** [comment]
Sorry for the confusion on this. It's something that's changed a couple of times, because it's an area of active experimentation. I actually think we'll end up with some models that have independent components, and other models that have shared representations.

Currently the v2.0 and v2.1 models don't share any weights between the components. The model size reduction against v1 is achieved by the switch to neural network models. spaCy's models are unusually small in comparison to other neural network libraries, due to the use of hash embeddings. The word vectors table is usually the largest component of the models, but because of the hash embeddings we don't have one row per word --- leading to big savings.

Recent research has focused on pretraining language models for use in multi-task learning. Results demonstrate that these language models benefit from being much wider than our current models. This means we're likely to want at least some models that sacrifice the convenience of independent components for the efficiency gains of calculating a single context representation and using it amongst several components.
