### ISSUE TITLE
Spacy : 2.1.0a1  : Customized NER model which is loaded from disk is not giving any detection of customized entity ?

### ISSUE THREAD

**Issue by prashant334** [explosion/spaCy#2895]
spaCy version      2.1.0a1        
    Location           /home/prashant/.local/lib/python3.6/site-packages/spacy
    Platform           Linux-4.15.0-36-generic-x86_64-with-Ubuntu-18.04-bionic
    Python version     3.6.6          
    Models             en   

@honnibal @ines 

Hi ,
I already went through https://github.com/explosion/spaCy/issues/1337 but....doesn't work.
So after that I am writing this issue

one difference I noticed between en_core_web_sm and to_disk generated model is there is no tagger and parser folder.

When I am evaluating trained model in the same code it shows proper results for customized named entity  recognition. But when I am loading saved model from disk it shows nothing for the same test data that I used after just training to evaluate.

I tried with both technique **from disk()** and **spacy.load()**

Here  I am attaching my generated model in **zip** file.

nlp = spacy.blank('en').from_disk('/home/prashant/sales_agreemt/binary_models/en_CLOSING_DATE_EXTRACTION-0.0.0/en_CLOSING_DATE_EXTRACTION/en_CLOSING_DATE_EXTRACTION-0.0.0/')

[en_CLOSING_DATE_EXTRACTION-0.0.0.zip](https://github.com/explosion/spaCy/files/2541603/en_CLOSING_DATE_EXTRACTION-0.0.0.zip)

#nlp = spacy.load('/home/prashant/sales_agreemt/binary_models/en_CLOSING_DATE_EXTRACTION-0.0.0/en_CLOSING_DATE_EXTRACTION/en_CLOSING_DATE_EXTRACTION-0.0.0/l')

examples : 

with training and testing in same code

testing sample: _The closing of the sale will be on or before July 19 , 2018 , or within 7 days after objections made._

**Results :** closing_date :  July 19 , 2018 

with loading model from disk

testing sample: _The closing of the sale will be on or before July 19 , 2018 , or within 7 days after objections made._

**Results :** closing_date :  **NULL**   

both  Techniques **spacy.load** and **from disk()** failed

nlp = spacy.blank('en').from_disk('/home/prashant/sales_agreemt/binary_models/en_CLOSING_DATE_EXTRACTION-0.0.0/en_CLOSING_DATE_EXTRACTION/en_CLOSING_DATE_EXTRACTION-0.0.0/')
#nlp = spacy.load('/home/prashant/sales_agreemt/binary_models/en_CLOSING_DATE_EXTRACTION-0.0.0/en_CLOSING_DATE_EXTRACTION/en_CLOSING_DATE_EXTRACTION-0.0.0/ner/model')

**Comment by ines** [comment]
I think the problems with your loading logic are the following: 

```python
nlp = spacy.blank('en').from_disk('/home/prashant/sales_agreemt/binary_models/en_CLOSING_DATE_EXTRACTION-0.0.0/en_CLOSING_DATE_EXTRACTION/en_CLOSING_DATE_EXTRACTION-0.0.0/')
```

Here, you're setting up a *blank* English model with only the tokenizer and no pipeline. You're then loading in the binary data via `from_disk`. When you call `nlp.from_disk`, spaCy will iterate over the **components in the pipeline** and if data for them is found in the directory, it will make them available. Since your model is blank and there's no `'ner'` component in the pipeline, the NER weights won't be made available, and your `nlp` object will have no entity recognizer. That's why it doesn't show you any entities either.

```python
nlp = spacy.load('/home/prashant/sales_agreemt/binary_models/en_CLOSING_DATE_EXTRACTION-0.0.0/en_CLOSING_DATE_EXTRACTION/en_CLOSING_DATE_EXTRACTION-0.0.0/ner/model')
```

Here, you're loading a model but you're pointing `spacy.load` to the **subdirectory** containing the NER model weights. `spacy.load` is intended for loading whole model packages, so instead, you should point it to `en_CLOSING_DATE_EXTRACTION-0.0.0`. The `meta.json` in that directory will contain all information spaCy needs to set up the `nlp` object. So double-check that the `"pipeline"` includes `"ner"`.

**Comment by prashant334** [comment]
What is the solution... To have everything work smoothly.

**Comment by ines** [comment]
If you want to use `from_disk`, construct the correct pipeline (e.g. using `nlp.create_pipe` and `nlp.add_pipe`).

If you want to use the simpler `spacy.load`, load the full model directory and make sure the `meta.json` specifies the correct pipeline.

```python
nlp = spacy.load('/home/prashant/sales_agreemt/binary_models/en_CLOSING_DATE_EXTRACTION-0.0.0/en_CLOSING_DATE_EXTRACTION/en_CLOSING_DATE_EXTRACTION-0.0.0')
```

(Also, double-check that that model path is correct? It looks like you saved the model within an existing model directory? This can make things very messy and much harder to figure out mistakes.)
