### ISSUE TITLE
Which version of Spacy should I use in order to take advantage of multiprocessing on CPUs?

### ISSUE THREAD

**Issue by felipheggaliza** [explosion/spaCy#2916]
Hi, which version of Spacy should I use in order to take advantage of multiprocessing?

This is my code:
```
start = time.time()
for doc in nlp.pipe(array_texts, batch_size=args.batchSize, n_threads=args.nThreads):
    result.append(doc.cats)
print('Time Elapsed {} ms'.format((time.time() - start)*1000))

```
array_texts is a numpy array with mutiple texts.

* Operating System: CentOS Linux release 7.4.1708 (Core)
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0.12 (installed using: pip install spacy)
* Environment Information: Anaconda 3
* Hardware: Intel(R) Xeon(R) Platinum 8153 CPU

_Originally posted by @felipheggaliza in https://github.com/explosion/spaCy/issue_comments#issuecomment-437445351_

**Comment by honnibal** [comment]
As of v2.1, the `n_threads` argument of `nlp.pipe()` is deprecated, since we can't release the global interpreter lock in v2.x to take advantage of multi-threading. Instead, you should use multiprocessing to take advantage of multiple CPU cores. Future versions will implement something to make this transparent, but for now you have to do it yourself.
