### ISSUE TITLE
displacy arc labels are place incorrectly in Jupyter notebook

### ISSUE THREAD

**Issue by willprice** [explosion/spaCy#2924]
| Software | Version |
|----------|---------|
| Python   | 3.6.4   |
| notebook | 5.4.1   |
| spacy    | 2.0.16  |

The SVG contents is the same when I copy the HTML from the inspector both in
jupyter and from the `displacy.serve` webpage.

When viewed through `displacy.serve`:

![displacy-serve](https://user-images.githubusercontent.com/966205/48501958-58c53f80-e836-11e8-9a11-af5de1d67a41.png)

And in Jupyter:
![displacy jupyter](https://user-images.githubusercontent.com/966205/48501957-58c53f80-e836-11e8-81f9-87f97eed32b8.png)

The SVG generated is the same, so I suspect some CSS issue is overriding the default, I don't know whether that should be solved within Jupyter, or whether it's spaCy's responsibility to make portable SVGs.  

Generated SVG here: https://gist.github.com/willprice/66d9ff961b693abe19e94d541eaacb99

This happens both in Firefox and Chrome.

I had a poke twiddling CSS rules off and on but couldn't seem to find any rules that affected the placement. Let me know if there's anything I can do providing additional info to help resolve the issue.

Thanks for the awesome library!

**Comment by ines** [comment]
Thanks for the detailed report!

This is very strange indeed... The labels are positioned with the paths using `xlink:href` and the path `id`. Did you render any other displaCy dependency visualizations in your notebook by any chance? Maybe what happened here is that it aligns the labels with the paths from a *previous* SVG, because the path `id`s are identical?

In the method that renders the SVG, we currently use the index of the document to create the unique ID for each SVG ([see here](https://github.com/explosion/spaCy/blob/87ce435affb972f6b1b9dde2cf953212a8e5d825/spacy/displacy/render.py#L41)). This works well with `displacy.serve`, but if you make several calls to `displacy.render` with one `Doc` in a notebook, it'd mean that all SVGs would receive the ID `0`.

If this is the case, we should probably generate a random visualization ID on each call to `displacy.render` – so instead of `"arrow-0-1"` the arcs would then have IDs like `arrow-34039420-1`, which should prevent clashes.

**Comment by willprice** [comment]
Ah! Yes, that could well be the issue. I've got a whole bunch of visualisations in the same notebook, most of which are minor variants (I'm trying to understand the different dependency relations that arise). 

Looking at the label placement I can now see that the text spans are reusing previous positions.

Randomising the ID sounds like a good idea, perhaps use a [UUID](https://docs.python.org/3/library/uuid.html).

Thanks for the super quick response and root causing, impressive!

**Comment by willprice** [comment]
>  this would mean that two identical parses would still receive the same ID, right? So if you render the same doc twice in a notebook (for whatever reason), the IDs would still clash
Would that not be a good thing? If they're the same parse then they'll have the same layout?

**Comment by ines** [comment]
> Would that not be a good thing? If they're the same parse then they'll have the same layout?

I mean, the markup would always be identical – except for the IDs, which will be reflected in the `id` attributes of the SVG. `id` attributes are supposed to be unique and if two paths in two visualizations of your notebook have the same `id`s, that's *technically* considered invalid HTML. So in theory, if you render two identical visualizations on the same page, the IDs clash and the labels in SVG 2 will be rendered using the IDs of SVG 1. This isn't dramatic or visible, because the positions are the same – but it's technically wrong. So I was thinking, if we have to adjust this anyways, we might as well prevent ID clashes completely 🙂

**Comment by willprice** [comment]
Ah yes, that's a good point, I'd not considered that. Thanks again @ines.

**Comment by willprice** [comment]
You might want to increase 999 to something a bit larger, I've run into the bug again ;), although at least rerunning the visualisation fixed it because its stochastic. You could use a uuid for the actual `id` attribute to make this even less common?

**Comment by willprice** [comment]
(I'm happy to make the change if you approve of the method)

**Comment by ines** [comment]
@willprice Ah, sorry, I missed this! And yes, that's a good idea – feel free to submit the PR 👍
