### ISSUE TITLE
Progress Bar for Parallel nlp.pipeline in Jupyter Notebook

### ISSUE THREAD

**Issue by matthaeusheer** [explosion/spaCy#2936]
Hey all!
I could not find any working tool to display a project bar over an nlp pipeline in a Jupyter Notebook.
Some things I tried: tqdm & progress packages, simple printing.
All of those do not run smooth and show weird behaviour, kinda printing everything after the job is done.

    for spacy_doc in nlp.pipe(some_generator, batch_size=10000, n_threads=4):

        for sent in spacy_doc.sents:

            yield ' '.join([token.lemma_ for token in sent])`

* Python version: 2.7.15
* Platform: Darwin-17.5.0-x86_64-i386-64bit
* spaCy version: 2.0.16
* Models: en_core_web_sm, en
* Environment Information: Jupyter Notebook 5.7.0

**Comment by ines** [comment]
I think some of this might be Jupyter-specific. Have you tried this one, which is widget-based and specifically for notebooks?
https://github.com/alexanderkuk/log-progress

Since the stream has no length and the progress indicator doesn't know when it's done, the result would look more like this:

![](https://camo.githubusercontent.com/740df72c1dc842154f947265c050ce11f35b40a3/68747470733a2f2f686162726173746f726167652e6f72672f66696c65732f3731322f3235352f6437372f37313232353564373766643534373362383131336537626663316264383532662e676966)

If you know how many texts you're processing, you could pass this in as the `size` argument (or as `total` in `tqdm`). This should give you a "real" progress bar.
