### ISSUE TITLE
install spacy but not load en model not working

### ISSUE THREAD

**Issue by rjkhan** [explosion/spaCy#2941]
i am using anaconda3 and have install spacy model 

when i run 

`import spacy` it load model 

after that when i run 
`spacy.load('en')`

it show me an error 

**OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
**

anyone can help me please ? 

thanks

**Comment by udaybhaskar4592** [comment]
Open cmd

cd C:\Users\YOUR SYSTEM NAME\AppData\Local\Programs\Python\Python36-32
(or)

go to python idle->properties->open file location
copy the path
go to cmd

cd paste the path

python -m spacy download en

Hope this helps you!

**Comment by ines** [comment]
Yes, a likely explanation is that the model can't be found in your current environment (for example because of the Python path). Some things to check:

* Make sure the model installed and linked correctly. Instead of `spacy.load('en')`, also try `spacy.load('en_core_web_sm')`. If the latter worked, it means the model is installed, but the shortcut link wasn't created.
* Run `pip list` and check if `en-core-web-sm` shows up in your list of installed packages. If not, it means it's not available in the current environment.
* Run `which python` and `which pip` and compare the locations. If you're on Python 3, you sometimes have to explicitly run `python3` and `pip3` to make sure you're using the correct one. (If the model was installed into a different Python environment, e.g. Python 2, it won't be available in Python 3, and vice versa.)
