### ISSUE TITLE
SystemExit:2 running in Jupyter/Colab

### ISSUE THREAD

**Issue by tfitzhardinge** [explosion/spaCy#2960]
Hi 

I have tried to run the Deep_Learning_keras SpaCy example in Google Colab (ie in Jupyter Notebooks) and get the following error. Is there a Jupyter version of the example or fixes with the code that I can make

usage: ipykernel_launcher.py [-h] [-r] [-H 64] [-L 100] [-d 0.5] [-e 0.001]
                             [-i 5] [-b 256] [-n -1]
                             [model_dir] [train_dir] [dev_dir]
ipykernel_launcher.py: error: unrecognized arguments: -f
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

**Comment by ines** [comment]
The problem here is that the example scripts are intended to be standalone Python scripts users can run from the command-line. So we use a library called `plac` to handle the command-line arguments, so you can set parametrs like `--n-iter 10` when you run the script.

However, Jupyter/IPython seems to add its own command line arguments like `-f` when it executes the code in the notebook. So the script complains, because that's not an expected argument.

As a solution, removing all the CLI-related stuff from the script (like `@plac.anotations` and the `if __name__ == '__main__':` block) should do the trick. We should probably add a note about this in the example files, to prevent this type of confusion.

**Comment by tfitzhardinge** [comment]
@Ines Thank you for the solution that removed the error.
