### ISSUE TITLE
can't pickle spacy model

### ISSUE THREAD

**Issue by amineparis** [explosion/spaCy#2962]
model loading takes long time in developement environment, We need to cache it. before caching we need to pickle it, when pickeling I get this message :
```
Traceback (most recent call last):
  File "/data/libs/python/dl/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-54-28ffccf698b6>", line 1, in <module>
    pickle.dumps(nlp)
AttributeError: Can't pickle local object 'FeatureExtracter.<locals>.feature_extracter_fwd'
```

**Comment by honnibal** [comment]
It's true that we need to resolve that pickle error, but a huge % of the time when people want to use pickle it actually won't help them :(. For instance here pickling won't reduce your loading time. In order to unpickle, it has to deserialize the model --- it uses almost exactly the same code as `spacy.load()`, except perhaps a little slower.

**Comment by honnibal** [comment]
This should now be resolved in the latest `spacy-nightly`.
