### ISSUE TITLE
Convert IOB2 format

### ISSUE THREAD

**Issue by IzzyHibbert** [explosion/spaCy#2970]
Hi,
I am approaching Spacy and would like to make a conversion of an existing IOB2 file.
Seems like the convert feature only supports IOB: I founded it as a converter.

I tried to  use a *.iob2 file as input but the result is the following :
    Unknown format
    Can't find converter for iob2

I am using V2.
Converting an IOB2 is possible ?
Thanks

**Comment by ines** [comment]
We don't have an IOB2 converter at the moment, but you might be able to adapt the existing [IOB converter](https://github.com/explosion/spaCy/blob/master/spacy/cli/converters/iob2json.py)? The main difference is that tokens at the beginning always start with `B-` instead of `I-` ([as described here](https://datascience.stackexchange.com/questions/37824/difference-between-iob-and-iob2-format/40041#40041)), right?

If you (or someone else) wants to give it a go, we'd definitely appreciate a pull request 👍

**Comment by gavrieltal** [comment]
I'll try taking a stab at this one.

**Comment by ines** [comment]
@gavrieltal Yay, thanks! 

I'd recommend starting on the `develop` branch, because I've actually refactored a *big* part of the converters to be more maintainable and less messy. The converters are now functions that take the already opened file and return the processed data (instead of doing all the I/O themselves – that's only managed in the top-level `convert` command).

**Comment by gavrieltal** [comment]
I'm actually running into the same issue as #2504. 
```
(.env) gavriel@stockholm:~/Desktop/python/spaCy$ python -m spacy convert iob.iob . -c iob
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gavriel/Desktop/python/spaCy/spacy/__main__.py", line 35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/gavriel/Desktop/python/spaCy/.env/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/gavriel/Desktop/python/spaCy/.env/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/gavriel/Desktop/python/spaCy/spacy/cli/convert.py", line 51, in convert
    n_sents=n_sents, use_morphology=morphology, lang=lang)
  File "/home/gavriel/Desktop/python/spaCy/spacy/cli/converters/iob2json.py", line 16, in iob2json
    sentences = read_iob(file_)
  File "/home/gavriel/Desktop/python/spaCy/spacy/cli/converters/iob2json.py", line 35, in read_iob
    words, iob = zip(*tokens)
ValueError: not enough values to unpack (expected 2, got 1)
```
```
(.env) gavriel@stockholm:~/Desktop/python/spaCy$ cat iob.iob 
Alex I-PER
is O
going O
to O
Los B-LOC
Angeles I-LOC
```

**Comment by ines** [comment]
Just had a quick look, but it seems like the converter expects the word and tag to be separated by a `|` instead of whitespace?

https://github.com/explosion/spaCy/blob/37c7c85a86bb6472d6918dd87c99ea6a2170037f/spacy/cli/converters/iob2json.py#L29-L33

I'm not 100% sure if this is a problem in the converter or a problem in the data. Or whether we need to support both? 

In general, it'd definitely be nice if the converters raised an error in cases like this, before it inevitably fails in `zip`. For example:

```python
if len(tokens[0]) < 2:
   raise ValueError(
       "Can't convert line. Expected word and tag separated by | but got: {}"
       .format(tokens[0])
   )
if len(tokens[0]) == 3:
    # and so on
```

**Comment by gavrieltal** [comment]
Is there an official IOB or IOB2 format specification? Or should we just accommodate whatever's on wikipedia, plus the pipe symbol to avoid breakage?

**Comment by honnibal** [comment]
@gavrieltal There's no official spec as far as I can tell :(. Most of these "historic" data formats don't really have one.

**Comment by gavrieltal** [comment]
I had to `pip install wasabi` to get here:
```
(.env) gavriel@stockholm:~/Desktop/python/spaCy$ cat whatever.iob
Alex|I-PER
is|O
going|O
to|O
Los|B-LOC
Angeles|I-LOC
(.env) gavriel@stockholm:~/Desktop/python/spaCy$ python -m spacy convert whatever.iob .
✔ Generated output file whatever.jsonl
Created 0 documents
(.env) gavriel@stockholm:~/Desktop/python/spaCy$ cat whatever.jsonl 
(.env) gavriel@stockholm:~/Desktop/python/spaCy$ mv whatever.iob whatever.iob2
(.env) gavriel@stockholm:~/Desktop/python/spaCy$ python -m spacy convert whatever.iob2 .

✘ Unknown format
Can't find converter for iob2

```
I know that the necessary change to accommodate different whitespace is to set `tokens = [re.split('[^\w\-]', line.split())]`, but I can't get the development version working, even for just an `iob` file (it's outputting nothing)

**Comment by gavrieltal** [comment]
bump

**Comment by ines** [comment]
Did you re-install all dependencies, e.g. by running `pip install -U -r requirements.txt`? Because it's the development version, the versions of the dependencies it refers to might be changing frequently, so always make sure to reinstall from the requirements and then re-run `setup.py build_ext --inplace` to rebuild the library

Import errors like this usually indicate that something isn't compiled correctly, or that the dependency it's importing from is not the latest version.

**Comment by gavrieltal** [comment]
After a good number of attempts and reinstalls, I actually got it working thanks to your `-U` flag recommendation.

Thanks!

**Comment by ines** [comment]
Glad to hear it worked! I'll close this issue, since we now have a working version of the converter on `master`. If you have time and want to port it over to `develop`, feel free to submit a PR ✨ Otherwise, we're also happy to take care of this!
