### ISSUE TITLE
unable to load the model when using reticulate

### ISSUE THREAD

**Issue by randomgambit** [explosion/spaCy#2982]
Hello the `spaCy` team!

I am coming from https://github.com/quanteda/spacyr/issues/145 and I believe this may be an issue with how spacy loads a model in python.

Here is the issue: I am perfectly able to load my custom model in `spyder`

```
Python 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 17:14:51)
Type "copyright", "credits" or "license" for more information.

IPython 6.5.0 -- An enhanced Interactive Python.

import spacy

nlp = spacy.load('/otherdrive/model/en_core_web_lg-2.0.0/en_core_web_lg/en_core_web_lg-2.0.0')

```

Now doing the same exact thing in R (using `reticulate`) triggers an error when `spacy` apparently cannot load the `en` model (even though I pointed toward a specific folder)
```

library(reticulate)
use_python("/mydrive/anaconda/bin/python")

py_run_string("import spacy")
py_run_string("nlp = spacy.load('/otherdrive/model/en_core_web_lg-2.0.0/en_core_web_lg/en_core_web_lg-2.0.0')")
 ImportError: [E048] Can't import language en from spacy.lang.
```

My sense is that during the loading process, perhaps spacy stores the model in some weird path and this is why using python via reticulate cant find it? It looks like python is trying to load the `en` model (that I havent downloaded!)

What do you think? @honnibal 
Thanks!!!

**Comment by ines** [comment]
Thanks for the report! There's not really an "`en` model" – that's just the shortcut for the `en_core_web_sm` package. What the error means here is that it can't load the `spacy.lang.en` module containing the language data to initialize the language class.

Because some languages now ship with a lot of language data, spaCy lazy-loads the modules only when needed – see here for how this is implemented (including when the erorr is raised):

https://github.com/explosion/spaCy/blob/658f7e0dc8f79132f74bc52d2c3e92fc62fc454f/spacy/util.py#L41-L54

Is it possible that reticulate somehow handles the dynamic imports differently? One thing you could try is edit that file in your spaCy installation, remove the `try`/`except` block and have a look at the original error and traceback. Maybe this gives us better insight into why it fails to import the module?

**Comment by randomgambit** [comment]
@ines thanks! rather that modifying the raw python files, couldnt I just import all the packages needed before loading the model? After all, reticulate allows me to submit python code directly. 

something like

```
> py_run_string("import spacy.lang.en")
Error in py_run_string_impl(code, local, convert) : 
  ImportError: cannot import name 'DependencyParser'
```

which does not work maybe because I need to import other stuff as well?
Thanks!!

**Comment by randomgambit** [comment]
@ines similar issue with another tentative
```

> py_run_string("import importlib")
> py_run_string("module = importlib.import_module('.lang.en', 'spacy') ")
Error in py_run_string_impl(code, local, convert) : 
  ImportError: cannot import name 'DependencyParser'
```

**Comment by ines** [comment]
Hmm, I don't think importing things manually is the solution. Python should take care of all the imports – if a file declares an import like `DependencyParser` and it fails, there's something else going on.

Did you make sure that the spaCy version you're using from R is compiled correctly? `DependencyParser` for example is a Cython module, so if spaCy failed to compile, you'll keep seeing errors like this. And because it's an `ImportError`, it will hit the `except ImportError` and raise that error when importing `lang.en`.

**Comment by randomgambit** [comment]
@ines  I have installed `spacy` using `conda`. How can I check it compiled correctly? sorry for my noobiness. Maybe I should elevate this issue to `reticulate` as well. LOL ! :)

**Comment by ines** [comment]
No worries! If you installed via conda, this shouldn't be a problem – conda ships pre-compiled wheels.

Here's another thing to try and debug: Could you run the following code in both your regular Python intepreter *and* via `reticulate` and compare the result?

```python
import spacy
print(spacy.__file__)
```

**Comment by randomgambit** [comment]
I tried to run
```

py_run_string("import os as os")
py_run_string("os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '/mydrive/anaconda/plugins/platforms'")

```
but the problem remains. Im going to escalate to `reticulate`. Maybe there is some weird setting to be made. Anyway, I think this is also of interest to `spacy` because many people are trying to use it via `spacyr`

**Comment by randomgambit** [comment]
@ines I am hashtagging you in the question above but I am not sure you will receive the notifications. If you want to help, please have a look. thank you!!

**Comment by ines** [comment]
Closing this in favour of the other issue – sounds like this is something more general and not related to spaCy specifically.

**Comment by randomgambit** [comment]
yes you are right. thanks for helping anyway @ines !
