### ISSUE TITLE
changing language defaults does not work properly

### ISSUE THREAD

**Issue by KaNuNSuZoFLu** [explosion/spaCy#3014]
Hi,

i am trying to change the defaults for a specific language model with the code

```
import spacy
from spacy.lang.en import English

English.Defaults.prefixes += tuple([r'^[Xx](?![A-Za-z])'])

nlp = spacy.load('en')

doc = nlp(u'X1')

for token in doc:
	print(token)
```

to split a Character X from numbers. Input should be sth like X1 and the output should be sth like X 1 but it does not work as expected.

```
import re
import spacy
from spacy.lang.en import English

from spacy.tokenizer import Tokenizer

prefix_re = re.compile(r'^[Xx](?![A-Za-z])')

def custom_tokenizer(nlp):
    return Tokenizer(nlp.vocab, prefix_search=prefix_re.search)

nlp = spacy.load('en')
nlp.tokenizer = custom_tokenizer(nlp)
doc = nlp('X1')

for token in doc:
	print(token)
```

it's working like a charm but I don't want my code to be so lang. Isn't it possible to change the prefix by one line? Aim is to make the matcher to recognize "Patterns" One character followed by two digits to be recognized as matches. And I want to add several patterns to tokenize in special cases different from default not just one pattern. I don't know how to add more regular expressions on the prefix. Somewhere I have read that it should work like hat

`English.Defaults.prefixes += tuple([r'^[Xx](?![A-Za-z])'])`

But it does not work for me. Is it possible that I am loading a wrong model after adding the rule? Or what can be the problem?

Can you please help?

## Your Environment

* Operating System: macOS Mojave
* Python Version Used: 3.7.0
* spaCy Version Used: 2.0.18
* Environment Information:

**Comment by honnibal** [comment]
The models load their tokenizer regular expressions from disk, because changing the tokenizer behaviour can adversely affect the model, if the change is too drastic. Your change won't affect the parse quality, but others might. So, models bundle their own tokenizers.

This means that changing the defaults doesn't help you, as you've found --- you need to either change the model on disk and load your custom model, or patch the tokenizer specifically, as you do in your first example.

I suggest you continue with your first approach. Yes, it seems a little inelegant...But I think it's currently the best way.
