### ISSUE TITLE
NER Training  on spark

### ISSUE THREAD

**Issue by yatin-rxlogix** [explosion/spaCy#3015]
## Feature description
Need to train custom entities for NER model using Spark as my Data is huge , Is there any way to use spark to create a NER model

**Comment by honnibal** [comment]
There's no distributed training for the NER or parser at the moment, no. You can use Spark to schedule training jobs, but each job will be single-threaded. Training for the NER model usually runs at about 4000 words per second, and with a batch size of 1000 words, convergence usually only takes less than 100,000 optimisation steps on the data sets I've worked on. This means you should be able to complete each training job in under 10 hours, and the computation should cost less than $1 on current cloud compute prices.

How big is your data set? I suggest you focus on running more experiments in parallel, rather than trying to parallelise one experiment. Even if one training takes a week, that only matters if you expect to run one data point, look at its result, and kick off the next experiment. Simply, don't do that. Just plan out all your experiments and run them together. Then your experimenting takes one week total.
