### ISSUE TITLE
Can we get matching probability of NER label's value ? 

### ISSUE THREAD

**Issue by An4567** [explosion/spaCy#3016]
Hi, 
Can we get probability value for NER label which will determine the matching probability of NER label's value in give text ? 
For example
Text => Apple is looking at buying U.K. startup
ORG => Apple => (0.9 probability )   

Text => I like Apple
ORG => Apple => (0.5 probability ) 

Thanks

**Comment by honnibal** [comment]
The short answer, unfortunately, is "not really". The model is trained with a greedy imitation-learning objective that makes a prediction on each word. You can't really map the token transition scores to entity likelihoods. There's also a beam search model with a global objective, but you're unlikely to get good results from that model unless you retrain.

Some further discussion of the issue here: https://github.com/explosion/spaCy/issues/881
