### ISSUE TITLE
How to train multi-word nouns in pos tagger?

### ISSUE THREAD

**Issue by KavyaGujjala** [explosion/spaCy#3037]
## How to reproduce the behaviour

Using gold standard tokenization for training pos didn't work for multi-word nouns.
Example:[('Levi Strauss', {'words': ['Levi Strauss'], 'tags': ['NNP']})]
How to do this?
## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.6
* spaCy Version Used: 2.0.18
* Environment Information:

**Comment by KavyaGujjala** [comment]
Hi,
Thanks for the reply.
Yes , noun_chunks works for noun phrases. But as I said in the example Is there any possibility to train multi-word nouns (as NNP) like we can train multi word entities is what I'm looking for.
Any way we can do that?

**Comment by ines** [comment]
If you want the model to make better prediction, you can update the part-of-speech tagger with more examples that assign the correct labels to the tokens. For example, `NNP` and `NNP` for "Levi" and "Strauss":

```
("A sentence about Levi Strauss", {"tags": ["DT", "NN", "IN", "NNP", "NNP"]})
```

Make sure to always use *complete texts* with those tokens *in context*. The tagger will predict the part-of-speech tags based on the context, so you need to give it examples with context.

See here for details on training the tagger: https://spacy.io/usage/training#example-train-tagger In your case, you won't need a custom tag map, since the tags you're using are already part of the standard tag map.
