### ISSUE TITLE
using TextCategorizer for binary classification

### ISSUE THREAD

**Issue by ayush1999** [explosion/spaCy#3043]
I want to use TextCategorizer for classifying text data. I already have my training data (X and Y) vectorized using CountVectorizer. The docs (https://spacy.io/api/textcategorizer) state the spacy uses a recurrent network for this purpose. How do I train this network? (similar to `model.fit(X, Y)`).

**Comment by ines** [comment]
spaCy gives you full control over the training loop, so instead of a `fit` method, you can call `nlp.begin_training` to initialize the weights, loop for a given number of iterations and call `nlp.update` for each batch to update the model. Here's an example of how this looks for training the text classifier:

https://github.com/explosion/spaCy/blob/361554f629a6938176cfddbcce368e5d94064ab5/examples/training/train_textcat.py#L58-L74
