### ISSUE TITLE
TypeError: Argument 'string' has incorrect type (expected unicode, got str)

### ISSUE THREAD

**Issue by vjd8866** [explosion/spaCy#3050]
```python
import spacy

nlp = spacy.load('en_core_web_sm')
text = "hello world"
doc = nlp(text)
print doc
for entity in doc.ents:
    print entity.text, entity.label_
```

    Python version     2.7.12         
    Platform           Linux-4.15.0-34-generic-x86_64-with-Ubuntu-16.04-xenial
    spaCy version      2.0.18         
    Location           /home/vijay/.local/lib/python2.7/site-packages/spacy
    Models             en_core_web_sm, en

**Comment by ines** [comment]
Since you're using Python 2, you need to explicitly use unicode strings. For example, by prefixing the string with `u`: `u"hello world"`. Alternatively, you can also add `from __future__ import unicode_literals` at the top of your file.

See here for more details: https://stackoverflow.com/a/38145440/6400719
