### ISSUE TITLE
String Matching/ Lookup

### ISSUE THREAD

**Issue by LastFromtheTop** [explosion/spaCy#3055]
## Feature description
Am looking for best algorithm for address matching. 

The challange is, address we try to match is not exactly same but semantically same
Ex: street = st. or str.
    avenue = av  or ave.
	
Can you please through light on this

**Comment by ines** [comment]
How you design your system really depends on the specifics of your problem and data. So I think it's more of a general strategy question rather than just an algorithmic one.

Training a statistical model (e.g. the named entity recognizer) to predict addresses can be useful if you have some examples of addresses in context and want to be able to *generalize* based on them and find more similar examples that weren't in your initial data. See here for details: https://spacy.io/usage/training

If you have a more or less finite list of addresses, a rule-based approach might be a better and more efficient solution. You could use the rule-based matcher to find different variations of the addresses or match more abstract token patterns (e.g. titlecased token followed by "street", "st." etc). See here for details: https://spacy.io/usage/linguistic-features#rule-based-matching
