### ISSUE TITLE
Dutch language model does not provide lemma

### ISSUE THREAD

**Issue by BramVanroy** [explosion/spaCy#3072]
The issue seems that the Dutch language model does not have lemmata or does not produce them with `.lemma_`. In the snippet below, you can see that instead of printing the lemma, the code just prints the token. Why is that? Is there no Dutch lemmatizer?

EDIT: looking at the [Dutch language model](https://github.com/explosion/spaCy/tree/master/spacy/lang/nl), Dutch simply does not have a lemmatizer. That's a shame, of course. But is there a way to dynamically see if a model has a lemmatizer? E.g. `nlp.has_lemmatizer`? In addition, I have access to a lot of Dutch text and I am willing to run a basic token-to-lemma script and do a pull request. I'm not sure how I should refer to the corpus-sources, though. Can I just include these in `lemmatizer.py` in a comment?

## How to reproduce the behaviour
```
import spacy

nlp = spacy.load('nl')
doc = nlp("De wind waait door de hoge bomen.")

for word in next(doc.sents):
    print(word.lemma_)
```

## Info about spaCy

* **spaCy version:** 2.0.18
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.7.1
* **Models:** en, nl

**Comment by ines** [comment]
Yeah, for Dutch, we currently don't have a lemmatizer.

There's not really an easy way to check this from within spaCy at the moment, because lemmatization depends on several factors. The lemma isn't directly predicted by the model – instead, spaCy supports either rule-based lemmatization, which depends on the part-of-speech tags, or lookup lemmatization based on a table ([see here for details](https://spacy.io/usage/adding-languages#lemmatizer)). Rule-based lemmatization is often more accurate and requires less data, but it's also more complex to create. Ideally, we'd love to transition to rule-based approaches for all languages, and maybe add a statistical component for languages that are more difficult to lemmatize (Finnish, Polish).

But in the meantime, a lookup table is still better than no lemmatization 🙂 For an example of a lookup-based lemmatizer, see the [German language data](https://github.com/explosion/spaCy/tree/master/spacy/lang/de). For an example of rule-based lemmatization, you can check out [the English data](https://github.com/explosion/spaCy/tree/master/spacy/lang/de).

We'd definitely appreciate a pull request for Dutch! (Just make sure that the data you're using has a license that's compatible with spaCy's MIT license. Having a few tests would also be super cool, so we can make sure we don't introduce regressions and make it easier for users to contribute rules later on.)

I'll also think about the attribute idea – it's tricky to check this from within the `Language` class, but the individual subclasses could expose that information (semi hard-coded). It might only be a transitional feature, though, until we implement a more complex solution for having the pipeline expose descriptions for what attributes it sets and where that data comes from.

**Comment by BramVanroy** [comment]
Thanks for the quick reply.

I am willing to spend some time on this around the holidays but can you give me some more information?

- Am I right in assuming that first a look-up is attempted and if that fails the rule-based system kicks in?
- The rule-based systems seems quite restricted (but, indeed, it's better than nothing). Would a regex option be more useful, or what is the reason for using string substitution? Regex would give a lot more options I imagine. Any reason why that's not used?
- I am not familiar with building tests, but I am willing to learn if you give some more details what you would like to see.
