### ISSUE TITLE
train_textcat.py fails on spacy nightly v2.1.0a4

### ISSUE THREAD

**Issue by d5555** [explosion/spaCy#3087]
Spacy v2.1.0a4 fails to run train_textcat.py
https://github.com/explosion/spacy/blob/master/examples/training/train_textcat.py
It doesn't seem to update the model. I get same losses on each iteration. And if I save the model in the end it fails to load with spacy.load(output_dir)

C:\Users\WORK-PC\Desktop>train_textcat.py
Created blank 'en' model
Loading IMDB data...
Using 2000 examples (1600 training, 400 evaluation)
Training the model...
LOSS      P       R       F
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
184.500 0.505   1.000   0.671
This movie sucked {'POSITIVE': 1.0}

* Operating System: Windows 10
* Python Version Used: 3.6
* spaCy Version Used: nightly  v2.1.0a4
* Environment Information:

**Comment by honnibal** [comment]
@d5555 Thanks, this example needs to be updated. The new nightly simplified the textcat architecture, and also switched to mutually exclusive labels by default, since that's what most people usually need.

To adjust the example, we need to have a second class label, `NEGATIVE`, which should have the value 0.0 when `POSITIVE` is 1.0, and vice versa. A pull request for this would be appreciated.

**Comment by jhochmuth** [comment]
Hello, first-timer here.
I have started to do as you requested but I seem to be missing a few things. 

1. So my first question is if I have used the correct format for `update()` for input variable `golds`. It is a tuple (of size batch) of dictionaries. Each dictionary looks like the following example: 
`{'cats': {'POSITIVE': False}, 'neg_cats': {'NEGATIVE': True}}`

2. Next, I am wondering why losses do not seem to be updating correctly still. They do change between each iteration, but they just seem to fluctuate around the same point. 

Here is an example of the first 5 iterations on a sample size of 200 (for speed reasons):
LOSS 	P  	       R  	       F  
20.281	0.500	0.500	0.500
19.907	0.600	0.600	0.600
18.956	0.725	0.725	0.725
19.360	0.775	0.775	0.775
19.461	0.725	0.725	0.725

And the same from the previous version of spaCy:
LOSS 	P  	       R  	       F  
10.490	0.739	0.773	0.756
5.246	1.000	0.682	0.811
2.637	0.889	0.727	0.800
1.350	0.818	0.818	0.818
0.901	0.760	0.864	0.809

Do you have any advice on how

Also, you can see that I haven't completely fixed `evaluate()`. I've only changed the variable `gold` so that it contains a dictionary of both POSITIVE and NEGATIVE categories. Previously, it only contained POSITIVE.
`gold = {**cats[i], **neg_cats[i]}`

Sorry if the solutions to these problems seem obvious to others. Not only am I new to this project, but also to neural networks and NLP.

**Comment by d5555** [comment]
@honnibal ,
so annotation example should look like this:    'cats': {'POSITIVE': 1.0, 'NEGATIVE': 0.0},  or vise versa
We can just change the line 103 in the example on: 
103:     cats = [ { 'POSITIVE': bool(y), 'NEGATIVE': not bool(y) }  for y in labels]
and add label , line 44:   
44:  textcat.add_label('POSITIVE') ; textcat.add_label('NEGATIVE'). 

Now it worked better but I'm still getting the error when trying to load the model: "TypeError: Model() takes exactly 2 positional arguments (1 given)"

Using 2000 examples (1600 training, 400 evaluation)
Training the model...
LOSS 	  P  	  R  	  F  
175.006	0.710	0.710	0.710
123.369	0.767	0.767	0.767
81.370	0.752	0.752	0.752
55.536	0.747	0.747	0.747
36.055	0.737	0.737	0.737
28.354	0.752	0.752	0.752
15.306	0.757	0.757	0.757
14.713	0.785	0.785	0.785
11.793	0.782	0.782	0.782
16.598	0.775	0.775	0.775
6.870	0.770	0.770	0.770
15.929	0.787	0.787	0.787
15.447	0.772	0.772	0.772
6.359	0.787	0.787	0.787
4.872	0.787	0.787	0.787
9.118	0.785	0.785	0.785
1.966	0.785	0.785	0.785
9.083	0.780	0.780	0.780
2.794	0.785	0.785	0.785
6.683	0.775	0.775	0.775
This movie sucked {'POSITIVE': 1.9875681106351767e-39, 'NEGATIVE': 1.0}

Saved model to C:\Users\WORK-PC\Desktop\NewModel1
Loading from C:\Users\WORK-PC\Desktop\NewModel1
Traceback (most recent call last):
  File "C:\Users\WORK-PC\Desktop\train_textcat.py", line 135, in <module>
    plac.call(main)
  File "C:\Python36\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Python36\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Users\WORK-PC\Desktop\train_textcat.py", line 90, in main
    nlp2 = spacy.load(output_dir)
  File "C:\Python36\lib\site-packages\spacy\__init__.py", line 22, in load
    return util.load_model(name, **overrides)
  File "C:\Python36\lib\site-packages\spacy\util.py", line 116, in load_model
    return load_model_from_path(name, **overrides)
  File "C:\Python36\lib\site-packages\spacy\util.py", line 154, in load_model_from_path
    return nlp.from_disk(model_path)
  File "C:\Python36\lib\site-packages\spacy\language.py", line 770, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "C:\Python36\lib\site-packages\spacy\util.py", line 560, in from_disk
    reader(path / key)
  File "C:\Python36\lib\site-packages\spacy\language.py", line 766, in <lambda>
    deserializers[name] = lambda p, proc=proc: proc.from_disk(p, vocab=False)
  File "pipeline.pyx", line 420, in spacy.pipeline.Pipe.from_disk
  File "C:\Python36\lib\site-packages\spacy\util.py", line 560, in from_disk
    reader(path / key)
  File "pipeline.pyx", line 412, in spacy.pipeline.Pipe.from_disk.load_model
  File "pipeline.pyx", line 1131, in spacy.pipeline.TextCategorizer.Model
TypeError: Model() takes exactly 2 positional arguments (1 given)

**Comment by jhochmuth** [comment]
@d5555 That worked much better than the stuff I was doing. So @honnibal  can ignore my first post.

The loading error occurs because the `TextCategorizer.Model()` argument requires an input for argument `nr_class` because the nightly version does not have a default value. Giving `nr_class` a default value of 1 fixes the problem.

**Comment by nukulsharma** [comment]
@jhochmuth  - i am facing the similar issue, do you mind sharing you snippet here. 
```bash
  File "pipeline.pyx", line 420, in spacy.pipeline.Pipe.from_disk.load_model
  File "pipeline.pyx", line 1148, in spacy.pipeline.TextCategorizer.Model
TypeError: Model() takes exactly 2 positional arguments (1 given)


```

**Comment by d5555** [comment]
to make it work I had to change line 1148 in pipeline.pyx  in spacy installer zip file :     `def Model(cls, nr_class=1, width=64, **cfg):`  in class TextCategorizer 
Then install spaCy. Not sure how to make it work without reinstalling spacy as it has to be cyphonized

**Comment by nukulsharma** [comment]
Thanks @d5555.
Not sure, but i couldnt get it working even after it. force reinstallation of Spacy, would override the change. 

pip install spacy-nightly --force

```
    def Model(cls, nr_class=1, **cfg):
```

**Comment by d5555** [comment]
Of course...you need first download spazy zip installer...
https://github.com/explosion/spaCy/archive/v2.1.0a6.dev0.zip
Correct zip file in pipeline.pyx
`pip install path/to/corrected/spacy...zip`

**Comment by nukulsharma** [comment]
Not sure, but i tried the suggested steps:
1. Tried both v2.1.0a5.zip and v2.1.0a6.dev0.zip
2. Modified as suggested
3. pip install <>.zip
4. Getting below error, setuptools and pip are latest. Not sure, what is going wrong here ..

![image](https://user-images.githubusercontent.com/3977272/51076217-8a824780-16bb-11e9-9ba5-ab26f6b36c23.png)

**Comment by d5555** [comment]
I don't  know how it works on Mac .  
Are you able to  pip install <>.zip without modification spacy zip ?  
If yes then probably you modified it wrongly. It has to be modified without unpacking... I used winrar

**Comment by nukulsharma** [comment]
Indeed, i unzipped, modified and zipped it. 
However, for original zip file, i am getting diff. issue.

```
  Cythonizing sources
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hk/0ph5xd612fxfmnysh67y2j9h0000gn/T/pip-req-build-fydymsgr/setup.py", line 270, in <module>
        setup_package()
      File "/private/var/folders/hk/0ph5xd612fxfmnysh67y2j9h0000gn/T/pip-req-build-fydymsgr/setup.py", line 206, in setup_package
        generate_cython(root, "spacy")
      File "/private/var/folders/hk/0ph5xd612fxfmnysh67y2j9h0000gn/T/pip-req-build-fydymsgr/setup.py", line 129, in generate_cython
        raise RuntimeError("Running cythonize failed")
    RuntimeError: Running cythonize failed
    

```

**Comment by ines** [comment]
See #3221!
