### ISSUE TITLE
Spacy time identification now working properly

### ISSUE THREAD

**Issue by Greg3108** [explosion/spaCy#3092]
## Your Environment

* Operating System: Windows
* Python Version Used: 3.7
* spaCy Version Used:
* Environment Information:

While working with spacy time identification, sometimes, it identifies Q1-2017 and sometimes it doesn't. Is there any specific reason which might prevent it from identifying? We are using English - en_core_web_lg (v2.0.0) model (Large).

**Comment by honnibal** [comment]
I don't really have a good explanation for why the statistical model performs inconsistently on this. If you're using `spacy-nightly`, you might try using matcher rules and the new `EntityRuler` component. Rules might perform better on your data than the statistical model.

Otherwise, I'll close this issue to merge it with the predictions master-thread, #3052 . Reports of mispredictions should generally be made there in future.
