### ISSUE TITLE
Spacy release cycle and 2.1 release. 

### ISSUE THREAD

**Issue by buriy** [explosion/spaCy#3114]
Hi guys,

I see Spacy 2.1 is that we need to have *much better* models for Russian and a number of other languages (actually I think almost any language would benefit from it).
Any idea on when do you plan to release it?
I'd like to prepare a set of Russian models for it, but suggesting people using "alpha version" software might not be a good idea, right?

**Comment by honnibal** [comment]
We're pretty close. You can see the project board here: https://github.com/explosion/spaCy/projects/5

Over the Christmas holidays I closed the last issue labelled "bug", so we're definitely keen to get v2.1 out. We'd like to finish the matcher changes before we do though, because these update the API. We'd also like to finish implementing the jsonl training data format.

I hope using `spacy-nightly` in the meantime is a good solution. Yes it's alpha, but it's quite stable, and should pip install easily.

**Comment by buriy** [comment]
Thanks, so is it more about 1-2 weeks, 1-2 months or 3-6 months, given the amount of packaging work you need and the number of beta/other issues?

**Comment by ines** [comment]
We'll hopefully have the stable v2.1 release out within the next couple of weeks (and the release candidate before that) 🙂
