### ISSUE TITLE
implement __add__ for Sentences

### ISSUE THREAD

**Issue by jbrambleDC** [explosion/spaCy#3116]
## Feature description
I would like to implement "sentence windows" by concatenating surrounding sentences. Then later, padding the resultant representation and passing it to our LSTM models for a sequence labeling task. 

This would be much easier to do if I could do something like:
```python
doc = nlp(document_text)
sentences = list(doc.sents)
for i in range(len(sentences) - 1):
    current_sentence = sentences[i] + sentences[i+1]
```

Currently adding two sentences will fail:
```
>>> sents[0] + sents[1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'spacy.tokens.span.Span' and 'spacy.tokens.span.Span'
```

**Comment by jbrambleDC** [comment]
If there is interest in this, I am happy to implement it.

**Comment by honnibal** [comment]
-1, personally

I think `__add__` overloading can easily make things worse rather than better, because it's already hard in Python to know what types you're dealing with. The situation's even worse when we're dealing with tensor representations as well, because in sequences "+" means concatenate, while in tensors it means something more like disjunction. I think the calling code will be much easier to read if you just write a function to do your addition.

Are you sure you want to make a new `Span` object for your use-case, though? It sounds to me like you'd rather want to collect all the sentence spans in your minibatch, create your padded tensor, and then reconcile the information back onto the spans.

**Comment by jbrambleDC** [comment]
This all seems sensible to me. Thanks for chiming in. I am going to go ahead and close this.
