### ISSUE TITLE
Custom tokenizer with token_match does not tokenize prefix/suffix correctly. 

### ISSUE THREAD

**Issue by jorjacman** [explosion/spaCy#3117]
## How to reproduce the behaviour

```
import re
import spacy
from spacy.tokenizer import Tokenizer

nlp = spacy.load('en_core_web_sm')

# tokenize emojis 
emoji_re = re.compile(r':.*?:')

# defaults
rules = nlp.Defaults.tokenizer_exceptions
prefixes = spacy.util.compile_prefix_regex(nlp.Defaults.prefixes).search
suffixes = spacy.util.compile_suffix_regex(nlp.Defaults.suffixes).search
infixes = spacy.util.compile_infix_regex(nlp.Defaults.infixes).finditer

def custom_tokenizer(nlp):
    return Tokenizer(nlp.vocab, 
                     rules=rules,
                     prefix_search=prefixes,
                     suffix_search=suffixes,
                     infix_finditer=infixes,
                     token_match=emoji_re.search)

nlp.tokenizer = custom_tokenizer(nlp)
```
```
utterance = "thanks :grin:! ok"
doc = nlp(utterance)
print([token.text for token in doc])
```

**Actual:**
`['thanks', ':grin:!', 'ok']`

**Expected:** 
`['thanks', ':grin:', '!', 'ok']`

The string found by `token_match` is automatically tokenized even if the match is inexact (in this case, the ! is extra). Is this expected behavior? According to the [docs](https://spacy.io/api/tokenizer), `token_match` is `A boolean function matching strings to be recognized as tokens.`; however, this doesn't specify the requirement of an exact match. 

If this is indeed a bug, I suspect the cause is somewhere around [here](https://github.com/explosion/spaCy/blob/6fe276f85de802ea6e93f26736e8725b3623ea9b/spacy/tokenizer.pyx#L172) in `spaCy/spacy/tokenizer.pyx` under `_split_affixes`, where the splitting breaks after finding a `token_match`. 

## Your Environment
* Operating System: macOS High Sierra
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0.16

**Comment by honnibal** [comment]
I think you're hitting  a bug that should be fixed in `spacy-nightly`. The bug was that when we loaded the expression back, we used `re.search` instead of `re.match`.

**Comment by ines** [comment]
I just tested it using the latest state on `develop` and `nlp = English()` language class and it still produced `['thanks', ':grin:!', 'ok']` for me. So this might actually be related to something else.

**Comment by honnibal** [comment]
Sorry for the confusion on this.

The `token_match` mechanism only matches on whole chunks. It doesn't match inside the prefix/suffix splitting loop. This means you can match `:grin:!` with token match, but you can't match `:grin:` and have `!` split afterwards. Changing this would impact the efficiency quite a lot.

Your best option to handle these is probably to add them as tokenizer exceptions. There are only a few hundred, right? Tokenizer exceptions *do* get handled inside the prefix/suffix splitting loop, because they're only a hash lookup --- so we can afford to check them inside the loop.

Finally, I did also find a bug in the `tokenizer.from_bytes` while investigating this: `token_match` was being read back in with `.search`, not `.match`. I could've sworn I fixed this, but apparently not. So, some good definitely still came from this.
