### ISSUE TITLE
Multiple errors installing with python 3.7 or 2.6: Fatal error LNK1112, Failed building wheel for ujson, thinc and cytoolz

### ISSUE THREAD

**Issue by katherinemunro** [explosion/spaCy#3152]
Hi everyone,

I've had problems installing spacy with Python 3.6 and 2.7. The error messages are sometimes huge so I've simply attached a doc logging the commands and setups I used, cmdline output, system info and links to the stackexchange forums which provided the suggestions I tried. My own knowledge of these things is very limited and I've never heard of wheels.

The latest option I tried is summarized as follows: 

## How to reproduce the problem
Python 2.7 installed and Path includes C:\Python27 and C:\Python27\Scripts. Running Visual Studio 2008. Running CMD as administrator.
>python -m pip install -U virtualenv
>virtualenv .env
>.env\Scripts\activate
(.env) ...>pip install -U spacy
... Gets a huge error which includes messages like 'Fatal error LNK1112' and 'Failed building wheel for ujson, thinc and cytoolz'.
The final error is:
Command "c:\windows\system32\.env\scripts\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\kathe\\appdata\\local\\temp\\pip-install-0izycz\\ujson\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\kathe\appdata\local\temp\pip-record-mc71cs\install-record.txt --single-version-externally-managed --compile --install-headers c:\windows\system32\.env\include\site\python2.7\ujson" failed with error code 1 in c:\users\kathe\appdata\local\temp\pip-install-0izycz\ujson\

## Your Environment
* Operating System: Windows 10
* Python Version Used: 2.6 64 bit
* spaCy Version Used: NA
* Environment Information:
[SpacyInstallLog.docx](https://github.com/explosion/spaCy/files/2753030/SpacyInstallLog.docx)

I'd really appreciate your help!

**Comment by Loghijiaha** [comment]
Check the whl files from https://www.lfd.uci.edu/~gohlke/pythonlibs/#spacy
Get x64 versions: `pip install *****.whl ****.whl ******.whl etc`

thank you

**Comment by katherinemunro** [comment]
> 
> 
> Check the whl files from https://www.lfd.uci.edu/~gohlke/pythonlibs/#spacy
> Get x64 versions: `pip install *****.whl ****.whl ******.whl `
> 
> thank you

@Loghijiaha thanks! Does it matter which of the x64 versions I get? i.e.:

ujson‑1.35‑cp27‑cp27m‑win_amd64.whl
ujson‑1.35‑cp34‑cp34m‑win_amd64.whl
ujson‑1.35‑cp35‑cp35m‑win_amd64.whl
ujson‑1.35‑cp36‑cp36m‑win_amd64.whl
ujson‑1.35‑cp37‑cp37m‑win_amd64.whl

**Comment by Loghijiaha** [comment]
if you  are using Python 2.7, use ujson‑1.35‑cp27‑cp27m‑win_amd64.whl
if you  are using Python 2.7, use ujson‑1.35‑cp37‑cp37m‑win_amd64.whl

**Comment by katherinemunro** [comment]
Thankyou. Sorry for the stupid question but is there a particular place I have to install it? With spacy or with Python for example.

**Comment by ines** [comment]
You can install wheels just like a Python package with `pip install`. For example, `pip install /local/path/to/some/wheel.whl`.

Alternatively, you could also try installing spaCy via `conda`, which provides pre-built wheels for spaCy and all its dependencies: `conda install -c conda-forge spacy`.

To give you a little background on what's going on here:

Like spaCy, some packages use C extensions (meaning that parts of the library are written in C++ or Cython, a C++/Python hybrid). This makes the code very fast, but it also means that it has to be compiled before the user can run it. There are two main ways this can be done:

* Locally by the user who installs the package. This means that you need to have a compiler installed on your machine ([see here](https://spacy.io/usage/#source-ubuntu) for details). 
* By the author of the package, who pre-builds wheels (compiled packages) and uploads them to PyPi (pip). This is more convenient for the user, but it's also a lot of work and quite complex, because wheels are platform-specific. There needs to be a wheel for Windows + Python 2.7, macOS + Python 2.7 and so on, so the library has to be compiled for each of those combinations. We usually need to build about 10-15 different wheels to cover all platforms and Python versions we support.

For spaCy, we now provide pre-built wheels for all of those combinations so you don't have to compile the library locally (this took us a while and our own little library, [`wheelwright`](https://github.com/explosion/wheelwright)). However, not all of our dependencies currently do this, so there are still a few packages you need to compile locally – for example, to install `ujson`.

This likely failed on your system, because you don't have a compiler installed or available – and unfortunately, pip doesn't fail very gracefully here, and Windows also doesn't always make it super easy to set everything up correctly. If you're just getting started, you're probably fine installing the wheels from the link posted above or installing spaCy from `conda`. But if you ever do want to install a compiler, you'll need the [Visual C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/) (not to be confused with Visual Studio, Microsoft Visual C++ or various other things with similar names!).
