### ISSUE TITLE
NER Retrainable Model lowers prediction accuracy 

### ISSUE THREAD

**Issue by yatin-rxlogix** [explosion/spaCy#3201]
Duplicate of #3138 
@honnibal @ines , Kindly look at the issue #3138 it has been closed earlier but mine Problem is still not resolved.

Summary of the Issue:--
In the first model, I have prepared on top of 'blank' model by calling begin_training() & introduced 6 new customized fields in it. On top of this model I build a new model with more data and same fields. But the accuracy on earlier Trained data falls.

As you suggest I can do a mix of two data sets.

But in my use case I would like to add more data from time to time to existing model as my data is huge.
Kindly suggest me some option to do so.

**Comment by svlandeg** [comment]
Perhaps this is a so-called "catastrophic forgetting" problem? 
https://explosion.ai/blog/pseudo-rehearsal-catastrophic-forgetting

So even if you don't want to retrain from scratch, you probably still want to mix in "old" examples during retraining.

**Comment by yatin-rxlogix** [comment]
So, what would be the best Case to retrain model  with new data from time to  time, @honnibal   Can  you  provide some insight into this.

**Comment by ines** [comment]
Some suggestions:

* Are you calling `begin_training` again when you update the model later on? If so, this might be the biggest problem, because you're actually resetting the weights.
* To prevent catastrophic forgetting, make sure to always mix in examples of what the model previously got correct, *plus* your new examples. So basically, show it other examples to "remind it". You can do this by running your existing model over some text, extracting the correct predictions and then adding those to your new training data.

Btw, we're also working on some built-in methods to make this kind of stuff easier in the future. For example, an `nlp.rehearse` method. You can see this in action here – note thart this is **still experimental**! https://github.com/explosion/spaCy/blob/develop/examples/training/rehearsal.py

**Comment by yatin-rxlogix** [comment]
@ines  I am not using nlp.begin_training(), Can you tell me when will  the method  "nlp.rehearse" comes as a part of formal release.
