### ISSUE TITLE
Unable to install spacy-en_core_web_sm with Conda

### ISSUE THREAD

**Issue by schlies** [explosion/spaCy#3226]
## How to reproduce the problem

I did a conda install of Spacy, but I'm unable to install this package:
spacy-en_core_web_sm

The instructions on anaconda.org don't work. I'd like to use the package in Jupyter Notebooks which I'm running from Anaconda.

Command:

$ conda install -c danielfrg spacy-en_core_web_sm

```bash
Error:

Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - spacy-en_core_web_sm

Current channels:

  - https://conda.anaconda.org/danielfrg/osx-64
  - https://conda.anaconda.org/danielfrg/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
```

## Your Environment

* Operating System: macOS Mojave
* Python Version Used: 3 
* spaCy Version Used:
* Environment Information: Anaconda

**Comment by erotavlas** [comment]
You should be able to just use the following at the conda prompt inside your environment

python -m spacy download en_core_web_sm

That's what I do and it works fine in jupyter

**Comment by schlies** [comment]
I’m on a MacBook and not sure what the conda prompt is. But I had already done that directly in the terminal. It downloaded, but it’s only accessible when I run Non-Anaconda Python directly from the terminal. It’s not accessible within the Anaconda environment. 

Dictated via iPhone

**Comment by erotavlas** [comment]
That's because your downloading it outside your conda environment and it gets installed to the python packages folder, not to the one inside your conda  environment folder.  

If you want to run it inside your conda environment, you have to open an Anaconda terminal window and then activate the environment you want to use, and run the above command from inside that.  Also make sure that you have jupyter installed in your conda environment.  You can check by typing

conda list 

If it is not there it will default to the jupyter version that is in the base environment which may not access to the correct packages you want from your environment.  

So if you don't see jupyter package inside your environement, you have to also install that first using 

conda install jupyter

**Comment by schlies** [comment]
I understand, but how do I do this from a MacBook? I am pretty new to this, but I don’t think there is an Anaconda prompt for Mac.  To run Anaconda, I just launch the Anaconda Navigator application. 

From the terminal, I don’t know how to make Anaconda the active environment. 

Yes, Jupyter is installed in Anaconda environment.

Thank you

**Comment by erotavlas** [comment]
From the anaconda navigator you can launch a terminal for your environment

See here for more details
https://docs.anaconda.com/anaconda/user-guide/getting-started/

**Comment by schlies** [comment]
Hello, the Anaconda documentation instructions weren't working for me --
probably because I had multiple Python distributions installed. So the
Python command never launched the Anaconda distribution. But I figured out
the problem. I had to change my bash profile as follows:

export
PATH="$HOME/anaconda3/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:$PATH"

Now when I run Python from the terminal, it's the Anaconda distribution. So
when I type the code you mentioned, it installed the package properly.
Thank you very much!

**Comment by ines** [comment]
I was just going to say, wait, our models can't be installed from a conda channel, because they're only hosted in one place [on GitHub](https://github.com/explosion/spacy-models/releases) and not on pip or conda. But I just saw that this is a package uploaded by a user.

Glad your got your conda environment sorted! (This might also explain why you had problems installing and accessing the models before). 

A few things to note, also in case others come across this thread later:

* As already mentioned above, the official way of downloading and installing spaCy models is via our `spacy download` command:
```bash
python -m spacy download en_core_web_sm
```
* If you can't use this for whatever reason (no permissions, firewall, proxy), the second "official" way is to download and install them [via pip and URL or manually](https://spacy.io/usage/models#download-pip).
* Keep in mind that this conda package is not an official distribution and we do not control the contents. Statistical models are large blobs of binary data that you're executing on your system, so when dowloading them from third parties (or anywhere, really), be cautious. (This has nothing to do with the user who uploaded it btw, more of a general note on downloading pre-trained models.)
* The "single source of truth" for spaCy model compatibility at the moment is our [`compatibility.json`](https://github.com/explosion/spacy-models/tree/master/compatibility.json). This is resolved when you run `spacy download` and used to make sure you're always getting the right version of the model that's compatible with your spaCy installation. If you're downloading the models manually or from somewhere else, make sure to check the compatibility.
