### ISSUE TITLE
"ValueError: exceeds max_bin_len" when saving Prodigy model to disk

### ISSUE THREAD

**Issue by mortenegelund** [explosion/spaCy#3229]
## How to reproduce the behaviour
Initialized Prodigy with clean spaCy model (Danish). Loaded Fasttext vectors (2M entries) into model (through Prodigy). Also loaded annotations into local Prodigy database.

Running this:
prodigy ner.batch-train da_foo da-model-with-vectors --output output-dir --label FOO --eval-split 0.2 --n-iter 10

Training goes just fine, and I get all iterations and a final accuracy score, but then I get this:

```
Correct    65
Incorrect  1
Baseline   0.091
Accuracy   0.985
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/prodigy/__main__.py", line 259, in <module>
    controller = recipe(*args, use_plac=True)
  File "cython_src/prodigy/core.pyx", line 253, in prodigy.core.recipe.recipe_decorator.recipe_proxy
  File "/usr/local/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/usr/local/lib/python3.6/site-packages/prodigy/recipes/ner.py", line 455, in batch_train
    model.from_bytes(best_model)
  File "cython_src/prodigy/models/ner.pyx", line 429, in prodigy.models.ner.EntityRecognizer.from_bytes
  File "/usr/local/lib/python3.6/site-packages/spacy/language.py", line 690, in from_bytes
    msg = util.from_bytes(bytes_data, deserializers, {})
  File "/usr/local/lib/python3.6/site-packages/spacy/util.py", line 490, in from_bytes
    msg = msgpack.loads(bytes_data, raw=False)
  File "/usr/local/lib/python3.6/site-packages/msgpack_numpy.py", line 184, in unpackb
    return _unpackb(packed, **kwargs)
  File "msgpack/_unpacker.pyx", line 200, in msgpack._unpacker.unpackb
ValueError: 2802762136 exceeds max_bin_len(2147483647)
```

## Your Environment
* Operating System: Ubuntu
* Python Version Used: 3.6
* spaCy Version Used: 2.0
* Environment Information: Installed with Prodigy 1.6.1.

Note: I am running with msgpack==0.5.6, but Python still hates me. Any ideas?

I assume the bugreport should go here, since the error occurs in a spaCy dependency.

**Comment by ines** [comment]
Thanks for submitting the report here – this is definitely the right place!

And that error is strange indeed, because it really shouldn't be happening with that version of `msgpack`. As a sanity check and so that we can see the version's of the other dependencies, could you run `pip list` and post the output?

**Comment by mortenegelund** [comment]
Sure, Ines. Here you go! :)

```Package             Version
------------------- ----------
cachetools          3.0.0
certifi             2018.11.29
chardet             3.0.4
cymem               2.0.2
cytoolz             0.9.0.1
dill                0.2.8.2
falcon              1.4.1
hug                 2.4.1
hug-middleware-cors 1.0.0
idna                2.8
jsonschema          2.6.0
mmh3                2.5.1
msgpack             0.5.6
msgpack-numpy       0.4.3.2
murmurhash          1.0.1
numpy               1.15.4
peewee              2.10.2
pip                 19.0.1
plac                0.9.6
preshed             2.0.1
prodigy             1.6.1
python-mimeparse    1.6.0
regex               2018.1.10
requests            2.21.0
setuptools          40.4.3
six                 1.12.0
spacy               2.0.18
thinc               6.12.1
toolz               0.9.0
tqdm                4.29.0
ujson               1.35
urllib3             1.24.1
waitress            1.1.0
wheel               0.32.1
```

**Comment by mortenegelund** [comment]
Python is 3.6.6.

**Comment by honnibal** [comment]
Unfortunately the error does still occur with large vectors with that version of msgpack. For now the simplest solution is actually to prune the vectors when you create them with `spacy init-model`. Adding the argument `--prune-vectors 100000` should do the trick.

In v2.1 we're using our own fork of `msgpack`, so that we can control these things a bit better. This should stop the error from occurring in future. But for now, simply using smaller vector models should give you very similar results, while also being much more convenient. The `--prune-vectors` argument still retains the vocabulary size of the original model, it's just that the rarer vectors are mapped to their nearest neighbours in the ones that are retained. So, if you don't have a vector for something like 'cockerspaniel', hopefully you'll get the vector for `dog` or some other common synonym, which should be close enough.

**Comment by mortenegelund** [comment]
Yup. I also figured that out. If I reduce the vector collection to 1.4M entries it works with some precision loss.

Looking forward to 2.1. Any idea of when this will happen?

**Comment by honnibal** [comment]
Probably within the next couple of weeks. You can already try things out by installing `spacy-nightly`.
