### ISSUE TITLE
training data for japanese blank model

### ISSUE THREAD

**Issue by KavyaGujjala** [explosion/spaCy#3230]
what is the NER training data format for japanese blank model?
Is it same as english language model like
TRAIN_DATA = [
    ("Who is Shaka Khan?", {"entities": [(7, 17, "PERSON")]}),
    ("I like London and Berlin.", {"entities": [(7, 13, "LOC"), (18, 24, "LOC")]}),
]
Can you please give an example with japanese text ?

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.6
* spaCy Version Used: 2.0.18

**Comment by ines** [comment]
I don't know Japanese, so unfortunately, I cannot give you a Japanese example. But in order to train an entity recognizer, you need texts and the entities in the text. How you format this initially is kinda up to you – as long as you call `nlp.update` correctly with the texts and annotations.

The relevant part in the docs starts here: https://spacy.io/usage/training#training-simple-style

If you're using an existing corpus, you might want to convert it to JSON and use `spacy train` with the following format: https://spacy.io/api/annotation#json-input
