### ISSUE TITLE
How can I extend model with new entity if it's not a simple word?

### ISSUE THREAD

**Issue by rafaleo** [explosion/spaCy#3249]
## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

How to add custom entities which are quantities but may occur with some other values like for example `1x`, `2x`, etc. I have a sentence:
```
nlp = spacy.load('en_core_web_md')
sent = "CONVERSION OF HOTEL INTO 16NO MANAGED FLATS".lower()
sent = nlp(sent)

for ent in sent.ents:
    print(ent.text, ent.label_)
```
and spacy doesn't recognize it as entity. But when I separate `16 NO` with then `16` is `nummod` and `no` is `det`. How can I add a pattern like `nNO` or `\d+NO` to the model to get from `16NO` one tokens like `quantmod`?

**Comment by ines** [comment]
Instead of training a new entity type, you might want to start by writing some match patterns. This will let you find tokens based on their attributes and relationships, e.g. part-of-speech tags or dependency labels. See here for the relevant docs: https://spacy.io/usage/linguistic-features#section-rule-based-matching

And just for completeness, here are the relevant docs for NER training if you do decide to experiment with this: https://spacy.io/usage/training#section-ner
