### ISSUE TITLE
Is there a way to extract LASTNAME, FIRSTNAME patterns as a single PERSON entity?

### ISSUE THREAD

**Issue by mrxiaohe** [explosion/spaCy#3260]
I am trying to use spaCy to extract person entities from a large body of documents. One of the scenarios that I've encountered is that when a name is in the format of LastName, First name (e.g., Doe, John), the last name and the first name are treated as two separate person entities (see example below). I wonder if there is a way such that both names can be treated as one single entity. Thanks!

```
doc = nlp("Name: Doe, John")
for ent in doc.ents:
    print(ent.text, ent.label_)

#Doe PERSON
#John PERSON
```

**Comment by ines** [comment]
> when a name is in the format of LastName, First name (e.g., Doe, John), the last name and the first name are treated as two separate person entities

This is likely because that construction is quite rare in regular written sentences and news/web text, which is what the pre-trained English model was trained on.

> I wonder if there is a way such that both names can be treated as one single entity.

One solution would be to use the [rule-based `Matcher`](https://spacy.io/usage/linguistic-features#section-rule-based-matching) to find those tokens and then merge the resulting `Span` objects. For instance, a match pattern could look like this:

```python
[{"ENT_TYPE": "PERSON"}, {"ORTH": ","}, {"ENT_TYPE": "PERSON"}]
```

The pattern describes three tokens: a token with the entity type `PERSON`, a token with the exact text value `,` and another token with the entity type `PERSON`. To make this more elegant, you could also wrap your logic in a [custom pipeline component](https://spacy.io/usage/processing-pipelines#section-custom-components) that runs automatically at the end of your pipeline.

The more involved solution would be to [update the model](https://spacy.io/usage/training#section-ner) with more examples of those names in context where "Doe, John" is labelled as a person entity. You'd need a good amount of examples, though, and also make sure that your data includes examples of all other entity types you're looking for, to prevent the model from overfitting on the new data. So for this use case, I'm not sure that'll be worth it – especially considering that the pre-trained model already predicts the names correctly as separate entities.
