### ISSUE TITLE
Incorportaing an external model to Spacy 

### ISSUE THREAD

**Issue by iamyihwa** [explosion/spaCy#3262]
## Your Environment

* Operating System: Mac
* Python Version Used: 3.7
* spaCy Version Used: '2.0.18'
* Environment Information:

Hello, 
I am trying to add external model (NER) to the spacy. 
This model is trained with PyTorch and is an external model to Spacy. 
I was thinking of labeling each token with the result of this model. 
Below is the approach I took. 
 
I wanted to replace tokens in doc with the NER entities that I wanted to assign to. 
So I have walked through each word in the token in the doc and replaced the values of each of these variables below. 
```
nlp_new = spacy.load('es', disable = ['ner'])
text = u'Soy de Corea. Corea es en Asia.'
doc = nlp_new(text)

doc = es_deeplearning_ner(doc, text)
for token in doc:
    print(token.text, token.ent_type_)
```

My first approach was this and this gave a result: 
```
Soy 
de 
Corea B-LOC
. 
Corea B-LOC
es 
en 
Asia B-LOC
.
```

However I noticed that the result didn't display correctly on the displacy, and the NER notation in spacy, was to separate the B,I, values. So then I checked all the variables in token, that referred to entity. 

Also by checking each variable on different sentences, I could see the possible values of each variable was: 
token.ent_id_ (token.ent_id): 0 
token.ent_iob: 1  (I), 2 (O),  3 (B) 
token.ent_iob_: B, I, O 
token.ent_type: 383, 0, 7654241940133152407, 4317129024397789502, 381
token.ent_type_: LOC, '', MISC, PER, ORG

So what I have done was to assign the values to each variable with the values returned from the model in following way.  For example: 
```
token.ent_type_ = 383 
token.ent_type = 'LOC'
token.ent_iob = 3
token.ent_iob_ = 'B'
```

Additionally, I have also realized that to display them with displacy, I need to replace their properties in doc. 
(changing doc.ents property)

However I have seen some errors that say that some of the variables cannot be assigned. 

> attribute 'ent_iob' , 'ent_iob_' of 'spacy.tokens.token.Token' objects is not writable

I have found a post ([this](https://github.com/explosion/spaCy/issues/2676) and[ documentation](https://github.com/explosion/spaCy/blob/b7916fffcf891cec0090fefe2512925c265af66f/website/usage/_linguistic-features/_named-entities.jade) that seemed relevant. 

However none of these seemed very clear to me..

**Comment by ines** [comment]
Really cool to see someone working on integrating a PyTorch model – definitely keep us updated on how you go 👍

> However I have seen some errors that say that some of the variables cannot be assigned.
> > attribute 'ent_iob' , 'ent_iob_' of 'spacy.tokens.token.Token' objects is not writable

Instead of writing to the tokens directly, you can use the [`Doc.from_array`](https://spacy.io/api/doc#from_array) method and provide the `ENT_TYPE` and `ENT_IOB` attributes as a numpy array.  Here's an example of this in the [`spacy-stanfordnlp`](https://github.com/explosion/spacy-stanfordnlp) wrapper. It doesn't set entity type attributes, but the principle is the same ([source here](https://github.com/explosion/spacy-stanfordnlp/blob/62aa27c5ef78ba7fcc4a463b6437689e6a1eef40/spacy_stanfordnlp/language.py#L127-L129)):

```python
attrs = [POS, TAG, DEP, HEAD]
array = numpy.array(list(zip(pos, tags, deps, heads)), dtype="uint64")
doc = Doc(self.vocab, words=words, spaces=spaces).from_array(attrs, array)
```

That said, you might find it **much easier** to create spans for each entity and add them to the `doc.ents`. Everything else will then be taken care of automatically.

If your PyTorch model outputs the token indices, this will be super straightforward because you can create `Span` objects from them directly:

```python
from spacy.tokens import Span

def add_entities(doc):
    new_ents = []
    for start_idx, end_idx, label in entities_predicted_by_your_model:
        new_ents.append(Span(doc, start_idx, end_idx, label=label))
    doc.ents = new_ents

nlp.add_pipe(add_entities)  # add to pipeline so it runs automatically
```

If you only have the character offsets, you can use the [`Doc.char_span`](https://spacy.io/api/doc#char_span) method to create a `Span` object from a character span in the `Doc`.

```python
for start_char, end_char, label in entities_predicted_by_your_model:
    span = doc.char_span(start_char, end_char, label=label)
    # etc.
```

There's also a [`gold.offsets_from_biluo_tags`](https://spacy.io/api/goldparse#offsets_from_biluo_tags) helper that takes BILUO tags and returns character offsets if your model only produces the token-based tags.

**Comment by iamyihwa** [comment]
Hi @ines Thanks for your kind reply! Sorry it took too long to respond from my side.
Yes I will try with the second method  involving Span. I am new to spacy architecture, and as you said the one involving Span seems easier! 
Will surely let you know how things go! 
Thanks @ines again for the help!

**Comment by iamyihwa** [comment]
Hi @ines 
I have ran into a couple of problems, 

(1) when I used this, label had to be integer, so I made a mapping, based on the token values I found for each entity type. 
`
 new_ents.append(Span(doc, start_idx, end_idx, label = label))
`
`ner_stoi = {'LOC': 383, 'MISC': 7654241940133152407, 'PER':4317129024397789502, 'ORG': 381 }

#token.ent_type: 383, 0, 7654241940133152407, 4317129024397789502, 381
#token.ent_type_: LOC, '', MISC, PER, ORG `

(2) Also the length of sentence is not the same as the length of Doc? 
I gave a sentence below. 
text = 'Soy de Corea. Corea es en Asia.'

These are the predicted entities. 
![image](https://user-images.githubusercontent.com/12494156/53395635-9cd1ef80-39a2-11e9-8e44-2f76c5380f68.png)

However I get an error below. 
![image](https://user-images.githubusercontent.com/12494156/53395621-917ec400-39a2-11e9-9b3b-81895cb8ce35.png)

Any ideas?

I thought my counting of locations were correct by outputting some values from the doc, and the indexing is correct - or the same as what I had predicted. ( You will see inconsistency in the first sentence, that in spacy, the first entity was not found. However the indexing of entities in the second sentence correspond to the indices I put in. ) 
![image](https://user-images.githubusercontent.com/12494156/53395736-d99de680-39a2-11e9-8a63-dc87dab4529d.png)

**Comment by iamyihwa** [comment]
I just solved it @ines ! Don't worry about it !  
In the documenation for doc (language.py) it  is written that doc is  acting based on tokenizer. 
So by correcting in in the unit of words instead by characters solved the problem! :-) 
Also the integer mapping seems to work, it is displayed correctly with the right entities in the visualizer!
