### ISSUE TITLE
Custom lemma ignored in tokenizer special case (spacy 2.1)

### ISSUE THREAD

**Issue by thomasopsomer** [explosion/spaCy#3268]
## How to reproduce the behaviour

Hello,

I'm still looking into spacy 2.1 and finding some new bugs :) There is a lemmatization issue when special case specify the lemma of a token, see below:

```python
import spacy
from spacy.attrs import *

nlp = spacy.load("en")

# default
nlp("data")[0].lemma_ == "datum" 

# with custom rule, we still get 'datum' :/
nlp.tokenizer.add_special_case("data", [{ORTH: u'data', LEMMA: u'data', POS: u'NOUN'}])
nlp("data")[0].lemma_ == "data"    # fail

# However custom lemma is used if the lemmatizer doesn't now how to lemmatize
nlp.tokenizer.add_special_case("kk", [{ORTH: u'kk', LEMMA: u'KK', POS: u'NOUN'}])
nlp("kk")[0].lemma_ == "KK"    # ok :)


```

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by honnibal** [comment]
Hmm. How did it behave in v2.0?

In `morphology.pyx` we can change the `assign_tag_id` function, so that we don't overwrite preset lemmas:

```
if token.lemma == 0:
    token.lemma = analysis.lemma
```

I'm a bit wary of this, though. Will this consistently do what we want? It feels like the sort of lemmatization change we've gone back and forth on a couple of times. For what its worth, the code on `master` also seems to clobber the lemma, so if the behaviour has changed between v2.0 and v2.1, I'm wondering why.

**Comment by thomasopsomer** [comment]
In 2.0, it behaves "as expected" ^^, meaning the lemma special cases are respected by the lemmatizer. The sample code I put above doesn't fail in 2.0 but does in 2.1.
