### ISSUE TITLE
Improvement ideas for examples (minor)

### ISSUE THREAD

**Issue by DarrenCook** [explosion/spaCy#3270]
## Which page or section is this issue related to?

https://spacy.io/usage/processing-pipelines#component-example1

This example would be much more useful if it *replaced* the current sentence segmenter, instead of running in addition to it. For instance, if you change `sbd_component()` to do nothing, the output is identical. I.e. surely the main use-case is because you don't like the way sentences are currently segmented, and you want to override that default behaviour.

It would also be good if it used a test string that behaved differently with the custom component compared to the built-in default. E.g. "This is a sentence(?) this is still part of it." currently gets split in two; it'd be interesting to see how to write a component that keeps that as one sentence.

(BTW, it took me a while to find a semi-realistic example - the default is very clever, isn't it. When I tried "This is a sentence(?) but this is still part of it." then it did keep it as one sentence!)

-----

Also, the first example code at https://spacy.io/usage/processing-pipelines#custom-components
The output is identical if you change:

    nlp.add_pipe(my_component, name='print_info', first=True)

to either of:

    nlp.add_pipe(my_component, name='print_info')
    nlp.add_pipe(my_component, name='print_info', last=True)

Maybe it just needs an extra bit of explanation to say that "The tokenizer has already run by the start of the pipeline, which is why you have access to tokens even if you put your custom code first."

**Comment by ines** [comment]
Thanks for the detailed feedback, really appreciate it! Just tried the example and you're right, it's really not very useful to illustrate the idea.

Here's one example that works and shows how to set custom sentence starts to prevent the parser from splitting "sentence-like" fragments and only split on a different character:

```python
import spacy

def sbd_component(doc):
    for i, token in enumerate(doc[:-2]):
        # Define sentence start if pipe + titlecase token
        if token.text == '|' and doc[i+1].is_title:
            doc[i+1].is_sent_start = True
        else:
            doc[i+1].is_sent_start = False
    return doc

nlp = spacy.load('en_core_web_sm')
nlp.add_pipe(sbd_component, before='parser')  # insert before the parser
doc = nlp(u"This is. A sentence. | This is. Another sentence.")
for sent in doc.sents:
    print(sent.text)
```

If you print `[token.dep_ for token in doc]` with and without the `sbd_component`, you'll also see the effect the sentence boundaries have on the parser: If they're set beforehand using your custom logic, the parser will take those into account and produce an analysis that is compatible with the sentence boundaries (two sentences with one root each vs. four sentences with one root each).

It also shows that setting the sentence start to `False` explicitly tells the parser to "stay away from it". If we didn't do this, it would default to `None` (missing value), so the parser would still have a go at them and assign the other boundaries in between.

> Maybe it just needs an extra bit of explanation to say that "The tokenizer has already run by the start of the pipeline, which is why you have access to tokens even if you put your custom code first."

Yes, good point! Maybe we could also modify the component and include the part-of-speech tags:

```python
def my_component(doc):
    print("After tokenization, this doc has %s tokens." % len(doc))
    print("The part-of-speech tags are:", [token.pos_ for token in doc])
    if len(doc) < 10:
        print("This is a pretty short document.")
    return doc
```

If you put this component first in the pipeline, the part-of-speech tags will be empty, because the tagger hasn't run. If you put it last in the pipeline or explicitly after the tagger, the part-of-speech tags are available. This might help illustrate the idea of the pipeline components being applied in order.

(On a related note, adding more prompts like "try changing this and see what happens" to the interactive code examples might be a nice idea? We could do this for selected examples like that and as an aside on the right.)
