### ISSUE TITLE
match_id from Matcher in v2.1.0a7 doesn't alway works for StringStore

### ISSUE THREAD

**Issue by tomkomt** [explosion/spaCy#3291]
Hello,

I have this weird behaviour. I am using spacy-nightly v2.1.0a7 with Python3 running following code:

> import spacy
> from spacy.tokens import Token, Doc, Span
> from spacy.matcher import Matcher, PhraseMatcher
> 
> def main():
>     pipeline = spacy.load('en', disable=['ner'])
>     
>     matcher = Matcher(pipeline.vocab)
>     pattern = [
>         {'ORTH': 'I'},
>         {'ORTH': 'have'},
>         {'_': {'Extension_1': 'True'}, 'OP':'*'}
>     ]
>     patterns = []
>     patterns.append(pattern)
>     matcher.add('1234ABCD', None, *patterns)
> 
>     doc = pipeline(u"I have issues issues issues issues")
> 
>     Token.set_extension('Extension_1', default=False)
>     Doc.set_extension('Extension_1', default=[])
>     [token._.set('Extension_1', 'True') for token in Span(doc, 2, 3)]
>     [token._.set('Extension_1', 'True') for token in Span(doc, 3, 4)]
>     [token._.set('Extension_1', 'True') for token in Span(doc, 4, 5)]
>     [token._.set('Extension_1', 'True') for token in Span(doc, 5, 6)]
> 
>     matches = matcher(doc)
>     for match_id, start, end in matches:
>         try:
>             span = Span(doc, start, end, label=match_id)
>             print(span.text)
>         except (ValueError, KeyError) as error:
>             print(error)
>             pass
> main()

(Sorry, code wrapper doesn't work properly with this bit)

It will produce following results:

> I have
I have issues
I have issues issues
I have issues issues issues
[E084] Error assigning label ID 5764616307934706824 to span: not in StringStore.

However, if I don't try to fetch Span, but print doc[start:end], it works. Unfortunately it's not a solution for following actions, like span.merge and etc.

Expected result:
> I have
I have issues
I have issues issues
I have issues issues issues
I have issues issues issues issues

If you replace pattern `{'_': {'Extension_1': 'True'}, 'OP':'*'}` with `{'ORTH':'issues', 'OP':'*'}`, you will get an expected result.

spacy version: spacy-nightly v2.1.0a7
python: Python 3.7.2 64-bit
OS: macOS High Sierra 10.13.6

**Comment by ines** [comment]
Thanks for the report! I think what you're experiencing here is similar to another problem that was reported in #1971, which I've outlined in this (xfailing) test:

https://github.com/explosion/spaCy/blob/3b667787a932efdf2179bb8eb8a1654517e9a3e6/spacy/tests/regression/test_issue1971.py#L9-L25

Basically, the `Matcher` seems to create "ghost matches" that don't actually have the true match ID, which is why looking it up in the string store fails. I'll merge this issue with #1971 – I suspect there might be one or two bugs in the new match patterns implementation that pretty much account for all of the reported problematic cases.

**Comment by tomkomt** [comment]
Ok, thank you

**Comment by tomkomt** [comment]
@ines Is there any kind of workaround when I have this ghost match? How reliable it would be to use the last working match Id, for example?
