### ISSUE TITLE
UnboundLocalError: local variable 'ner' referenced before assignment in spaCy

### ISSUE THREAD

**Issue by ali4friends71** [explosion/spaCy#3292]
UnboundLocalError: local variable 'ner' referenced before assignment in spaCy
![p1](https://user-images.githubusercontent.com/40916262/53007318-027f2280-345d-11e9-8235-4d061c1f7d43.jpg)
The error is coming when I'm loading my existing NLP model !!
This is my code
![screenshot from 2019-02-19 15-44-28](https://user-images.githubusercontent.com/40916262/53007481-57bb3400-345d-11e9-8e64-cf2fccdde0d4.png)
![screenshot from 2019-02-19 15-44-37](https://user-images.githubusercontent.com/40916262/53007487-5b4ebb00-345d-11e9-8da4-b61a9ca00afb.png)
![screenshot from 2019-02-19 15-44-43](https://user-images.githubusercontent.com/40916262/53007493-5e49ab80-345d-11e9-80f7-04eb13678237.png)
Can anyone please help me what to do now ??
The error is not coming when I'm creating a new model but it is popping up when I'm loading my existing model.

**Comment by ines** [comment]
This is a general Python error and has nothing to do with spaCy. The code path on line 49 defines the variable `ner`, but it's only hit when your model *doesn't yet* have a component `ner`. If it does, that block is skipped and the variable `ner` is undefined. So you have to define it – for example, `ner = nlp.get_pipe('ner')`.

Btw, some tips for the future: This issue tracker is really intended for bug reports and feature requests. For specific questions about your code and general Python issues, Stack Overflow is a better place to ask.

Also, if possible, try copy-pasting the relevant code instead of taking screenshots. Screenshots are hard to read and inaccessible for people with screen readers. And if someone wants to try it out, they can't copy-paste anything. If other people have to first type ~90 lines of code (!) by hand (!) to try out your code, you're muss less likely to get a reply.

**Comment by ali4friends71** [comment]
Thanks for reply and sorry for this type or issue.
I figured out this issue and it was a python code issue which I solved yesterday itself.
Sure I will post the code directly next time.
Thanks
