### ISSUE TITLE
Hi, I need to read address in multiple lines as below

### ISSUE THREAD

**Issue by vgramu** [explosion/spaCy#3298]
## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

**Comment by vgramu** [comment]
Hi,
I am trying to read address from document by creating a pattern and extracting that address using matcher function.  Please see below for address format and the code. Help me how I extract this address from text document.
The address is like this

1211 Deerwood Road

Houston, TX 77057


And the code is
# Match Patterns

from spacy.matcher import Matcher
matcher = Matcher(nlp.vocab)

pattern = [
    {'IS_DIGIT': True},
    {'IS_ALPHA': True,'OP':'+'},
    {'REGEX':'\n\n\n'},
   # {'ORTH': {'REGEX': '\\n'}},
    {'IS_ALPHA': True, 'OP':'+'},
    {'IS_PUNCT': True,'OP':'?'},
    {'IS_ALPHA': True, 'OP':'+'},
   {'IS_DIGIT': True}
 ]
matcher.add('ADDRESS_PATTERN', None, pattern)
matches = matcher(doc)
print(len(matches))
for match_id, start, end in matches:
    # Get the matched span
    matched_span = doc[start:end]
    print(matched_span.text)

**Comment by ines** [comment]
This issue tracker is mostly for bug reports and feature requests – if you need help with your specific code, Stack Overflow might be a better place to task questions.

Some tips to help you debug your patterns:
* `REGEX` is only available in `spacy-nightly`, not yet in the stable version.
* If you want to use the nightly, note that it's still an alpha release and not stable. The `REGEX` operator also isn't supported as a top-level property – it always needs to refer to a token attribute like `ORTH` or `LOWER`.
* Double-check how spaCy tokenizes the text and make sure your patterns match the tokenization and that every dict describes one token.
* Newline tokens can also be matched using `'IS_SPACE': True`.
* You might find it easier to match the whole `doc.text` against a regular expression instead of writing token patterns. See here for details: https://spacy.io/usage/linguistic-features#regex
