### ISSUE TITLE
Named Entity Disambiguation/Linking

### ISSUE THREAD

**Issue by yatin-rxlogix** [explosion/spaCy#3299]
I am  Using Spacy NER, Currently facing a problem of  Named Entity Disambiguation/Entity Linking. In my problem a text can be one of two entities. E.g. Text "fever" can be DESCRIPTION or INDICATION.
The Accuracy is very bad in resolving this.
Can somebody tell how to solve this problem.  Is this the problem more of Entity linking then NER.
Is any Entity Linking available in Spacy as well?

**Comment by honnibal** [comment]
If you're getting really bad accuracy on this distinction, it can be an indication that your annotations aren't consistent, or that the distinction is too subtle for the model to learn from the local context. Have you checked that your annotators agree clearly on these cases? If so, you should have a look at whether the information they're using to make the distinction is in the local context as well, or if they need outside information.

I doubt "entity linking" would solve your problem in this case. Entity linking is really about resolving real-world entities to a knowledge base, so that you know things like which "George Bush" the article is talking about.

I suspect the most likely problem is that your annotation scheme needs to change. It's not obvious to me what the difference is between a "description" and an "indication", so it might not be obvious to your annotators --- or indeed, there might be no clear distinction between the categories at all. It's hard to define an annotation scheme that "carves reality at the joints" --- that separates the instances clearly into the annotation categories.

**Comment by yatin-rxlogix** [comment]
The DESC &  IND  are my own custom Entities. The problem is same word (Entity Text) can be DESC or IND as I have shown below in the examples. 
In terms of population Numbers DESC is 90% of total population & IND is 10% of total population.

Precision, Recall is good with **DESC** but not fine with **IND**.

IS skewed data the reason behind this?
I have used External Word Vectors also, Pasted Code below?

Can u suggest some ways to improve F1-score

**Examples**:--
1)
Text:-- Company Narrative:  36 year old female started NuvaRing Sep-Oct 04 for endometriosis.
Entity Text:-- endometriosis
Entity Type:-- IND
------
2)
Text:-- 24APR 2008 Office visit (OV): Pt was seen and diagnosed with endometriosis.
Entity Text:-- endometriosis
Entity Type:-- DESC

3)
Text:-- In October 2004, the patient experienced endometriosis and was hospitalized.
Entity Text:-- endometriosis
Entity Type:-- DESC

4)
Text:-- She informed that her mother has endometriosis.
Entity Text:-- endometriosis
Entity Type:-- DESC


**Code using Word Vectors**:--
    dropout = decaying(0.6, 0.2, 1e-2)
    other_pipes = [pipe for pipe in nlp.pipe_names if pipe != 'ner']
    with nlp.disable_pipes(*other_pipes):  # only train NER
        optimizer = nlp.begin_training(lambda: [], use_gpu=True, device=0)
			  with open(vectors_loc, 'rb') as file_:
        		header = file_.readline()
        		nr_row, nr_dim = header.split()
        		nlp.vocab.reset_vectors(width=int(nr_dim))
        		for line in file_:
        		    line = line.rstrip().decode('utf8')
        		    pieces = line.rsplit(' ', int(nr_dim))
        		    word = pieces[0]
        		    vector = numpy.asarray([float(v) for v in pieces[1:]], dtype='f')
        		    nlp.vocab.set_vector(word, vector)  # add the vectors to the vocab

**Comment by honnibal** [comment]
> Can u suggest some ways to improve F1-score

I think you should change your annotation scheme. I can't see any distinction between 1 and 2 --- they seem to be of the same semantic type. It's not really surprising that the model can't distinguish them.
