### ISSUE TITLE
"Linking successful" reported spuriously

### ISSUE THREAD

**Issue by jnothman** [explosion/spaCy#3307]
Students of mine using Windows were hit by issues (in the latest Anaconda spaCy) along the lines of #3113 and #934. Running `download` results in the message "Linking successful", even though @ines [commented](https://github.com/explosion/spaCy/issues/934#issuecomment-290013935) in 2017:

> As noted by "the symlink simply wasn't created in the first place. (And the success message shouldn't have been displayed, because clearly, it wasn't successful. Hm.)"

It seems a try-except is not sufficient to check linking success. Please check it before reporting success.

**Comment by honnibal** [comment]
Thanks, will look into this.

In the meantime, if they specify the model name explicitly (e.g. `"en_core_web_sm"` rather than using a shortcut like `"en"`), things should work reliably.

**Comment by jnothman** [comment]
It doesn't still need to be linked into spacy/data? Okay

**Comment by ines** [comment]
No, spaCy models are Python packages and `spacy.load` will resolve in the following order: 1. custom shortcut name (symlink), 2. installed packages, 3. path to model data. So if you `pip install` the model package [manually](https://spacy.io/usage/models#download-pip), `spacy.load('en_core_web_sm')` will still work fine. You can even do the following:

```python
import en_core_web_sm
nlp = en_core_web_sm.load()
```

(I actually often prefer this syntax, because it's more explicit.)
