### ISSUE TITLE
Russian tests not working on my system with pymorphy2 0.8

### ISSUE THREAD

**Issue by svlandeg** [explosion/spaCy#3327]
## How to reproduce the behaviour
Run the Russian tests in `spacy/tests/lang/ru` with `pymorphy2==0.8`

## Analysis
PR https://github.com/explosion/spaCy/pull/3241 changed 
> RussianLemmatizer._morph = MorphAnalyzer()

to

> RussianLemmatizer._morph = MorphAnalyzer(lang=pymorphy2_lang)

in https://github.com/explosion/spaCy/blob/develop/spacy/lang/ru/lemmatizer.py#L23

This seems problematic on my system as `MorphAnalyzer` does not seem to have a `lang` argument in `pymorphy2==0.8` which is the version of the package mentioned in the `ImportError` message in that same class. As a consequence, the Russian tests fail.

I think the spacy unit tests may not be checking this when `pymorphy2` is not installed: 
![image](https://user-images.githubusercontent.com/8796347/53323063-7007d480-38dd-11e9-95b0-e7c62ddd35fe.png)

@juliamakogon : do you have any idea why this trips up on my system? Which version of `pymorphy2` do you have installed and do the tests work for you?

## Your Environment

* **spaCy version:** 2.1.0a9.dev2
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.6.7

**Comment by ines** [comment]
Thanks for the report!

> I think the spacy unit tests may not be checking this when `pymorphy2` is not installed:

We currently use `pytest`'s `importorskip` functionality to skip the tests for a given language if its dependency isn't installed. (That's because the language-specific dependencies aren't part of spaCy's core dependencies, so we can't run those tests by default.)

We should definitely consider adding `pymorphy2` to the `extras_require` with the respective version pin. This lets us keep track of which version is supposed to be compatible, and lets users install language-specific dependencies with spaCy as `pip install spacy[ru]` etc. See here for an example: 55bb570f51dff3966d1704558d646610a01b7887

**Comment by juliamakogon** [comment]
Hello! Thanks for the report. The problem is that for Russian language it's
enough to install pymorphy2==0.8, but to support Ukrainian you need to
install pymorpy2 from github with
   pip install git+https://github.com/kmike/pymorphy2.git
Or if you plan to use Ukrainian:
   pip install git+https://github.com/kmike/pymorphy2.git pymorphy2-dicts-uk
I think I should fix this cloning RussianLemmatizer to UkrainianLemmatizer
and reverting RussianLemmatizer to previous version, so both versions of
pymorpy2 will work.

пн, 25 лют. 2019 о 10:41 Ines Montani <notifications@github.com> пише:

**Comment by svlandeg** [comment]
Ah, so the latest `pymorphy2` version from github supports the `lang` argument but has not yet been released?

**Comment by juliamakogon** [comment]
Yes, and a new version exists for at least a year.

**Comment by svlandeg** [comment]
Ok, that's a little unfortunate. 

Anyway, as an additional headsup, your changes were merged into the `develop` branch where we made some changes to the tokenization rules. In short, the test `test_uk_tokenizer_splits_double_end_quote` in `spacy/tests/lang/uk/test_tokenizer.py` will have to be removed or annotated with `@pytest.mark.xfail` as the tokenizer currently oversegments double punctuation like `''`

**Comment by juliamakogon** [comment]
I made a pull request to fix this issue:
https://github.com/explosion/spaCy/pull/3329

пн, 25 лют. 2019 о 11:23 Sofie <notifications@github.com> пише:
