### ISSUE TITLE
What is the best approach to reset custom extensions?

### ISSUE THREAD

**Issue by tomkomt** [explosion/spaCy#3334]
Hello,

today we found out an interesting behaviour of spaCy.
We used the same text/doc in two runs of spaCy pipeline and we saw that annotations in custom extensions of Doc are doubled.

Let me show you a simple example:
```python
import spacy
from spacy.matcher import Matcher, PhraseMatcher
from spacy.tokens import Span, Doc

def main():
    pipeline = spacy.load('en', disable=['ner'])

    Doc.set_extension('SomeLabel', default=[])
    
    matcher = Matcher(pipeline.vocab)

    pattern = [
        {'ORTH': 'I'},
        {'ORTH': 'have'},
        {'ORTH': 'Troubles'}
    ]
    patterns = []
    patterns.append(pattern)
    matcher.add('1234ABCD', None, *patterns)

    text = u"I have Troubles"
    doc = pipeline(text)

    def do_match(doc, pipeline, run_no):
        matches = matcher(doc)
        for match_id, start, end in matches:
            span = Span(doc, start, end, label=match_id)
            doc._.get('SomeLabel').append(
                {"start": span.start_char, "end": span.end_char, "text": span.text}
            )
            
            print('--- Annotations '+ run_no + ' ---')
            for anno in doc._.get('SomeLabel'):
                print(anno)

    do_match(doc, pipeline, 'Run 1')
    do_match(doc, pipeline, 'Run 2')
main()
```

Result from that is:

> --- Annotations Run 1 ---
{'start': 0, 'end': 15, 'text': 'I have Troubles'}
--- Annotations Run 2 ---
{'start': 0, 'end': 15, 'text': 'I have Troubles'}
{'start': 0, 'end': 15, 'text': 'I have Troubles'}

We assumed that each run will be independent and we expected something more like
> --- Annotations Run 1 ---
{'start': 0, 'end': 15, 'text': 'I have Troubles'}
--- Annotations Run 2 ---
{'start': 0, 'end': 15, 'text': 'I have Troubles'}

So, my question is what is the best approach to reset extensions?
At this moment, we use this workaround:
```python
def clear_doc_extensions(label):
    if Doc.has_extension(label):
        Doc.remove_extension(label)
        Doc.set_extension(label, default=[])
```

**Comment by ines** [comment]
The problem here is that default arguments in extensions behave just like **default function arguments in Python**. Default function arguments are evaluated once and if they're mutable and you're mutating them (e.g. by appending to a list), you're actually mutating the default argument for all future calls. See here for more details and an explanation: https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments

> Python’s default arguments are evaluated once when the function is defined, not each time the function is called (like it is in say, Ruby). This means that if you use a mutable default argument and mutate it, you will and have mutated that object for all future calls to the function as well.

Also see my comment in #2581 and this section in the processing pipelines docs: https://spacy.io/usage/processing-pipelines#extensions

> When using mutable values like dictionaries or lists as the default argument, keep in mind that they behave just like mutable default arguments in Python functions. This can easily cause unintended results, like the same value being set on all objects instead of only one particular instance. In most cases, it's better to use getters and setters, and only set the default for boolean or string values.

So ideally, you should avoid mutating the list directly with `.append` and instead, overwrite it with an updated list. #3036 discusses a potential approach to prevent mutable default function arguments, but it'd mean introducing another keyword argument.

**Comment by tomkomt** [comment]
@ines Thank you. I made a fix for that. Your link to python guide helped. I would not expect to see something like that in Python, but I guess they have a reason for such features.
