### ISSUE TITLE
Adding a NER from different model to existing pipeline

### ISSUE THREAD

**Issue by suvinks** [explosion/spaCy#3337]
I found Issue #1752 which is similar to what am asking but it is a closed thread with no real solutions.

I am trying to train new entities for spacy NER. i tried adding my new entity to existing spacy 'en' model. However, this affected the prediction model for both 'en' and my new entity.

I therefore created a blank model and trained the entity recognition. This works well. However it is capable of predicting only the ones i have trained for and not the regular spacy entity recognition.

Say I trained 'horses' as ANIMAL entity.

For a given text

```
txt ='Did you know that George bought those horses for 10000 dollars?'
am expecting the following entities to be recognized
```

George - PERSON
horses - ANIMAL
10000 dollars - MONEY.
With my current setup it only recognized horses.

```
nlp = spacy.load('en')
hsnlp = spacy.load('models/spacy/animal/')
nlp.add_pipe(hsnlp.pipeline[-1][-1], 'hsner')

nlp.pipe_names
```
this gives

----------------------
`['tagger', 'parser', 'ner', 'hsner']`
----------------------
However when I try to execute

`doc = nlp(txt)  *<-- Gives me kernel error and stops working*`
Please let me know how to create a pipeline for NER in spacy effectively. Am using spacy 2.0.18

## Your Environment

* **spaCy version:** 2.0.18
* **Platform:** Linux-4.15.0-43-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.7.0
* **Models:** en

**Comment by chkoar** [comment]
Maybe related to #3239. You could try the upcoming `v2.1.x` which is currently available as `spacy-nightly`

**Comment by ines** [comment]
Yes, I'm pretty sure the problem you're seeing here is related to the interaction of the existing entities and the new ones set by your `hsner` component. When the `Doc` passes through the pipeline, `ner` will set entity tags. `hsner` will then *also* set entity tags while assuming that it's the first to do so.

When you have time, could you try your workflow again in the latest `spacy-nighly`? (You'll have to retrain your models to make them compatible, though). We fixed various issues that could cause segfaults in the named entity recognizer if entity tags were pre-defined, so I'd be curious to hear how your code behaves in the new version.

This issue is also relevant: #2920 We definitely want to make it easier to add multiple model components of the same type to a single pipeline. It just needs some changes to the pipeline architecture and the way components are defined and serialized.

**Comment by suvinks** [comment]
I did try spacy-nightly. It is not throwing an error now when I run it through the pipeline. However, it is not predicting anything from the second NER.
All the predictions are from default NER. Another thing I noticed is that the trained model was far less accurate when it was loaded from the disk and used. The code I used is similar to the one below
[](https://github.com/explosion/spacy/blob/master/examples/training/train_new_entity_type.py)

The prediction issue is happening for multi-word combinations like "out of station". If I trained it for AVAILABILITY entity (for example sake) the immediate prediction after training predicts it as AVAILABILITY. 
However, the next lines save and reload the model and do prediction again. That time the prediction splits that to (out, of, station) and only station is predicted as AVAILABILITY. 'out' and 'of' is predicted something else.

The above prediction issue is not happening with the current stable spacy version. Only happening with the nightly build.

Do let me know if you need more details

Thanks
Suvin

**Comment by suvinks** [comment]
https://github.com/explosion/spacy/blob/master/examples/training/train_new_entity_type.py

**Comment by suvinks** [comment]
Any update team?

**Comment by ines** [comment]
> I did try spacy-nightly. It is not throwing an error now when I run it through the pipeline. However, it is not predicting anything from the second NER.

Did you retrain your model with the latest version?
