### ISSUE TITLE
Japanese stop words are not loaded when initializing the language

### ISSUE THREAD

**Issue by BLKSerene** [explosion/spaCy#3346]
Hi, I'm trying to get the stop words of all languages supported by spaCy programmatically, and it seems to me there's an inconsistency with the Japanese language.

```
>>> import importlib
>>> spacy_lang = importlib.import_module('spacy.lang.en') # Use string literals here to loop over all languages supported by spaCy
>>> stop_words = spacy_lang.STOP_WORDS # English and other languages OK
>>> spacy_lang = importlib.import_module('spacy.lang.ja')
>>> stop_words = spacy_lang.STOP_WORDS # Fail
Traceback (most recent call last):
  File "<pyshell#18>", line 1, in <module>
    stop_words = spacy_lang.STOP_WORDS
AttributeError: module 'spacy.lang.ja' has no attribute 'STOP_WORDS'
```
This one works for the Japanese language:
```
>>> import importlib
>>> spacy_stop_words = importlib.import_module('spacy.lang.ja.stop_words') # Iterate over all languages
>>> stop_words = spacy_stop_words.STOP_WORDS
```
And I've found another way to do this (not working for the Japanese language currently):
```
>>> import spacy
>>> nlp = spacy.blank('en')
>>> stop_words = nlp.Defaults.stop_words
```

I'm not sure which one would be the best way to fetch all lists of stop words, I suppose that the last one would have a little overhead while loading the blank model? And is there a nicer way to retrieve the lists directly?

* Operating System: Windows 10 64-bit
* Python Version Used: 3.7.2 64-bit
* spaCy Version Used: 2.1.0a10

**Comment by ines** [comment]
Thanks for the report! (And for your other reports yesterday – so glad we were able to fix those and improve our tests 👍) 

Looks like the stop words aren't currently exposed in the `JapaneseDefaults`. In fact, they're not even imported in `ja/__init__.py`, even though they exist. That's why importing `spacy.lang.ja.stop_words` works, but `Japanese.Defaults.stop_words` doesn't.

> I'm not sure which one would be the best way to fetch all lists of stop words, I suppose that the last one would have a little overhead while loading the blank model? And is there a nicer way to retrieve the lists directly?

Yes, I think the second approach is probably more elegant because you're using spaCy's API objects instead of just the module / file structure. (In theory, if `stop_words.py` is ever renamed internally, your code will stop working, even if `Defaults.stop_words` still exists.)

Language data in spaCy is lazy-loaded so it's only imported when it's needed, so you do have to load the language class first before you can access its attributes like stop words etc.
