### ISSUE TITLE
Submitting pre-trained NER models for other languages

### ISSUE THREAD

**Issue by shanalikhan** [explosion/spaCy#3351]
There are only some language models available officially provided by spacy.
https://spacy.io/models/#available-models

Can we submit PR to add NER or any other pre-trained models into official spacy for other languages ?
What are the steps to follow to add pre-trained models for some language into spacy, provide the language data is already part of spacy.

**Comment by honnibal** [comment]
We should set up a process for pull requests to the https://github.com/explosion/spacy-models repo, but we'll need pull requests of the data, not the model. We don't want to have official models we can't retrain, because then as soon as we have to make a change to the library that breaks model compatibility, we would have to drop support for the model.

**Comment by ines** [comment]
Also see #2404, #2935 and #3056 for more details. Merging this with the master issue!
