### ISSUE TITLE
Visualizer displays pos instead of tag

### ISSUE THREAD

**Issue by bongbang** [explosion/spaCy#3357]
In the documentation, each token in the [`dep` visualizer](https://spacy.io/usage/visualizers#section-dep)'s output marked with its `tag`. For example, "This is a sentence." is annotated as follows.

    DT VBZ DT NN

In my Jupyter notebook, the `pos` is used instead of the `tag`.

    DET VERB DET NOUN

## How to reproduce the behaviour
```
import spacy
nlp = spacy.load('en_core_web_sm')
from spacy import displacy
displacy.render(nlp('This is a sentence.'), jupyter=True, style='dep')
```

## Your Environment

* Operating System: [It's a [Kaggle kernel](https://www.kaggle.com/docs/kernels). Shouldn't matter anyway.]
* Python Version Used: 3.6
* spaCy Version Used: 2.0.18
* Environment Information:

**Comment by ines** [comment]
Thanks for the report and good point. I think the default used to be `Token.tag`, but it was changed to `Token.pos`, since those tags will be consistent across languages. Some languages also define very cryptic fine-grained tags which can be kinda confusing. You can still get the fine-grained tags by setting `'fine_grained': True` in the [visualizer options](https://spacy.io/api/top-level#options-dep).

We should definitely update the examples. Just checked the [alpha docs](https://spacy.netlify.com/usage/visualizers) and since I only copied over the graphics, they still show the wrong tags.
