### ISSUE TITLE
spacy.tokenizer.Tokenizer.__call__ TypeError: __call__() got an unexpected keyword argument 'prefix_search'

### ISSUE THREAD

**Issue by dcordobar94** [explosion/spaCy#3395]
Hi
I'm working with the Spanish language and I want to avoid that you don't separate _Dr./Dra._ in two tokens ('_Dr./Dra_' and '.'). After many tests with tokenizer.add_special_case without solution I had tried the following:
`   
    hyphen_re = re.compile(r'Dr\.\/Dra\.')

    prefix_re = spacy.util.compile_prefix_regex(nlp.Defaults.prefixes)
    infix_re = spacy.util.compile_infix_regex(nlp.Defaults.infixes)
    suffix_re = spacy.util.compile_suffix_regex(nlp.Defaults.suffixes)
    nlp.tokenizer = nlp.tokenizer(nlp.vocab, prefix_search=prefix_re.search,
                                  infix_finditer=infix_re.finditer,
                                  suffix_search=suffix_re.search, token_match=hyphen_re.match)
`

but it gives the following error:
`
File "tokenizer.pyx", line 71, in spacy.tokenizer.Tokenizer.__call__
TypeError: __call__() got an unexpected keyword argument 'prefix_search'
`

I have tried several things without success. Any ideas how I could do it?

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.7
* spaCy Version Used: 2.0.18
* Environment Information:

**Comment by ines** [comment]
I think you just have a small typo in your code: The `Tokenizer` is **initialized** with the vocab, regular expressions etc. ([see here](https://spacy.io/api/tokenizer#init)) – but your code is actually *calling* the already initialized tokenizer with those arguments.

Instead, the second `nlp.tokenizer` should just be `Tokenizer`, because you want to create a new one and replace the old one with it:

```python
from spacy.tokenizer import Tokenizer

nlp.tokenizer = Tokenizer(nlp.vocab, prefix_search=prefix_re.search,
                          infix_finditer=infix_re.finditer,
                          suffix_search=suffix_re.search, token_match=hyphen_re.match)
```

> I want to avoid that you don't separate Dr./Dra. in two tokens ('Dr./Dra' and '.'). 

Btw, another solution could be to add an infix rule to split on `/` if it follows a `.` and then add a special case rule for `Dra.`. This will give you `["Dr.", "/", "Dra."]`, which seesm more consistent? If needed, you can always match it and merge it into a single span later on.

**Comment by dcordobar94** [comment]
It was that!! Thank you very much.

*Btw, another solution could be to add an infix rule to split on / if it
> follows a . and then add a special case rule for Dra.. This will give
> you ["Dr.", "/", "Dra."], which seesm more consistent? If needed, you can
> always match it and merge it into a single span later on. *


It's not a bad idea, would even be more correct, but really this division
isn't influential in my analysis and it's a bit more complicate for me.
Thank you again!
