### ISSUE TITLE
pip3 install spacy produces an OOM (out of memory) and fails (python 3.5.3-1, debian stretch)

### ISSUE THREAD

**Issue by tonikasch** [explosion/spaCy#3396]
## How to reproduce the behaviour
`# apt-get install make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev python3.5 python3.5-dev`
`# pip3 install -U spacy`
`Killed`

## Your Environment
* debian stretch in Spanish
* python 3.5.3-1+deb9u1 from distribution
* spaCy: latest

**Comment by tonikasch** [comment]
Installed python 3.7 from debian-testing repository and the error is gone.

**Comment by tonikasch** [comment]
This ticket is not resolved!!!

The bug is still present in pip3 with spaCy 2.x and python 3.5.3-1+deb9u1 from debian stretch.

**Comment by honnibal** [comment]
Sorry, misread.

How much memory is available on the machine? I wonder whether it's just that you're not finding a wheel installation for the 3.5 build (not sure why). Could it just be that you're running out of memory during compilation?

**Comment by tonikasch** [comment]
The machine has 2 GB of RAM memory.

I have tried to install wheel both as pip3 install -U wheel and by
installing python3-wheel debian package (apt-get).

I am able to install spaCy in that schema by building from source.

Shall I try to reproduce this bug in a clean debian stretch install?

Regards

**Comment by honnibal** [comment]
I think 2gb memory is probably just not enough memory. Parts of spaCy's Cython make use of C++ classes, and some of the code ends up in header files due to implementation details. This means the compilation can be expensive. If there's a spaCy wheel, you don't have to compile, but for whatever reason it seems to not be finding a wheel install file it judges as suitable for your environment. This means you end up compiling the code, which causes you to run out of memory.

**Comment by tonikasch** [comment]
Sorry for the re-open.

It is just the python version (3.5)

With python in 3.7, the install with pip3 runs on that 2-GB-RAM machine
with no problem.

Regards
