### ISSUE TITLE
GPU Memory Allocation

### ISSUE THREAD

**Issue by vamsitharun** [explosion/spaCy#3397]
I am using a 1GB GPU and trying to train an NER Spacy Model.
The training is working fine with CPU code.

For GPU this is the error
`CURANDError: CURAND_STATUS_ALLOCATION_FAILED`

Is this because of low GPU memory?
Is there a parameter to fix the memory allocated to GPU?

> ### **YOUR ENVIRONMENT**

Windows 10
CUDA Version 10.0
Spacy '2.0.18'
Python 3.6.5

cupy==5.3.0
thinc==6.12.1
thinc-gpu-ops==0.0.4

**Comment by honnibal** [comment]
Yes, it's due to low GPU memory. You can try to reduce the batch size, and make sure you're not using pretrained word vectors. You should also try updating to v2.1.

GPU training really isn't that much faster. With a powerful GPU it's about 2-3 times faster. With a small batch size and an older card you might not see much benefit. I would suggest sticking to CPU.
