### ISSUE TITLE
Hug auto reloading breaks

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#3398]
I use `hug==2.4.1` for creating an API to my `spaCy` model. Using the development runner (default) then everything is reloaded on change in source code. This is obviously a neat feature but it breaks with spaCy.

    Traceback (most recent call last):
    ...
        Token.set_extension("mecab_tag", default=None)
      File "token.pyx", line 52, in spacy.tokens.token.Token.set_extension
    ValueError: [E090] Extension 'mecab_tag' already exists on Token. To overwrite the existing extension, set `force=True` on `Token.set_extension`.

I am aware that maybe I should submit this bug in `hug` rather than `spaCy` but I am not sure?

## Info about spaCy

* **spaCy version:** 2.1.0a12
* **Platform:** Linux-4.15.0-46-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.7
* **Models:** en

**Comment by ines** [comment]
Thanks for the report. I don't think this really a problem with `hug` – it's just a side-effect of reloading a module without starting a new session.

`spacy.lang.ja` sets an extension attribute in the global scope, which is kinda unideal. In general, I don't think extension attributes should really be used internally. 

I've changed it to write to the `Doc.user_data` directly for now – if a user wants the `token._.mecab` attribute, they can add it themselves with a getter:

```python
get_mecab_tag = lambda token: token.doc.user_data["mecab_tags"][token.i]
Token.set_extension('mecab_tag', getter=get_mecab_tag)
```

**Comment by mr-bjerre** [comment]
Great. That is some quick fixing ! Just out of interest, what is mecab tags?

**Comment by ines** [comment]
MeCab is a [library for Japanese NLP](https://en.wikipedia.org/wiki/MeCab), which spaCy's `Japanese` class currently uses. (Using spaCy for Japanese requires MeCab to already be installed.) In addition to the tokenization, it also outputs part-of-speech tags. The fine-grained tags can be added to the `Token.tag`, since that's writable. The `Token.pos` follows a pre-defined scheme and isn't writable – it gets populated automatically via the `tag_map`. So there's no clear answer for where to put the coarse-grained tags produced by Mecab, which is why the extension attribute was used.
