### ISSUE TITLE
Incorrect lemma from lemmatizer

### ISSUE THREAD

**Issue by petro-zdebskyi** [explosion/spaCy#3444]
**Right:**
`[w.lemma_ for w in nlp('funnier')]` -> `['funny']` 

**Wrong:**
`[w.lemma_ for w in nlp('faster')]` ->`['faster']`

I think for word _faster_ lemma should be _fast_

**Comment by petro-zdebskyi** [comment]
This is also works in unexpected way: `nlp('data')[0].lemma_` -> `'datum'`

**Comment by DuyguA** [comment]
Hellos,
Lemma of an adverb is itself %99 of the time. However, some short adverbs can go comparative or superlative just as in your example, `fast -> faster`. I'll make a small refinement.

`Data` is **plural** of `datum` in Latin. `Data` is treated plural in grammatically correct sentences. However, in written and spoken English  it's used as `singular`. Honestly I don't know if should mark `data` as plural, then a catastrophe may arise due to practical issues.
