### ISSUE TITLE
Unable to install Spacy and getting this error Solving environment: ...working... failed

### ISSUE THREAD

**Issue by ShabiRaza** [explosion/spaCy#3452]
I am new to use the spaCy and I need to install it for NLP project, can some body help me to do it

I have tried all the steps from Juputer notebook and from Cmd prompt as well but getting below error:

## Solving environment: ...working... failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/r/win-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/r/win-64/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'tls_process_server_certificate\', \'certificate verify failed\')])")))'))

My Python version is 3.7.1

**Comment by ines** [comment]
> CondaHTTPError: HTTP 000 CONNECTION FAILED for url repo.anaconda.com/pkgs/r/win-64/repodata.json.bz2

This really sounds like an issue with conda and/or your network rather than spaCy. It seems to already fail when requesting the package index (?), before it's even getting started. Are you behind a proxy?

I've searched for the error online and found this thread (among lots of others) – maybe the suggestions here help? https://stackoverflow.com/questions/51083435/anaconda-condahttperror-sslerror

Once you sort out your conda installation and the connection, you should be able to download the latest spaCy version. It's now [available on `conda-forge`](https://anaconda.org/conda-forge/spacy). If you're behind a proxy, you might also want to look into [downloading the models manually](https://spacy.io/usage/models#download-manual), in case you come across SSL errors here, too.
