### ISSUE TITLE
Cuda installation doesn't seem to work

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#3461]
pip install -U spacy[cuda]

yields 

    zsh: no matches found: spacy[cuda]

Am I missing something here?

**Comment by ines** [comment]
Pretty sure this happens because `zsh` interprets the square brackets as its globbing syntax. Try putting `spacy[cuda]` in quotes, like this:

```bash
pip install -U 'spacy[cuda]'
```

Also see here for details and for how to make `zsh stop doing this: https://stackoverflow.com/questions/30539798/zsh-no-matches-found-requestssecurity/30539963

**Comment by mr-bjerre** [comment]
Gosh yes. Thanks !
