### ISSUE TITLE
Adding a preprocessor to the pipeline

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#3463]
I am not sure if this is already possible somehow? Imagine I have my own custom object `report` and I'd like to run `nlp(report)` for instance. I was thinking that this might be possible with a preprocessor looking something like

    class Preprocessor:
    
        def __init__(self, nlp, **cfg):
            self.nlp = nlp
    
        def __call__(self, report):
            return '. '.join([
                report.title,
                BeautifulSoup(report.body[:3000], 'lxml').get_text(),
            ])

and then adding that component as the first thing in the `pipeline` but I was wrong. How do you suggest to add a preprocesser? Would be cool with something similar to [`sklearn.pipeline.Pipeline`](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html).

I should say that I use `prodigy` as well so I'd like to use the same preprocessing there obviously.

**Comment by ines** [comment]
One thing all pipeline components have in common is that they **take a `Doc` object and return a `Doc` object**. Otherwise, it wouldn't really be possible to construct a pipeline, because you'd always have to keep track of whether a component takes text or a `Doc`, and whether it returns text or a `Doc`.

Before the pipeline is applied, the tokenizer takes the text and turns it into a `Doc` object. So you can either apply your pre-processing *before* you even pass your text to spaCy, or do it within a custom tokenizer.

Untested, but if you modify your code slightly, you should be able to use it to wrap the tokenizer like this:

```python
class Preprocessor:
   	def __init__(self, nlp, **cfg):
        self.tokenizer = nlp.tokenizer

    def __call__(self, report):
        result = '. '.join([
            report.title,
            BeautifulSoup(report.body[:3000], 'lxml').get_text(),
        ])
        return self.tokenizer(result)
```

```python
nlp = spacy.load("en_core_web_sm")
nlp.tokenizer = Preprocessor(nlp.tokenizer)
```

That said, it's true that the process around customising the tokenizer within a model currently isn't very smooth. There's definitely an argument for having a model package own its preprocessing steps and define and construct them in a similar way as it's currently done for the pipeline and pipeline components.

**Comment by mr-bjerre** [comment]
Ah yes should have returned `Doc` obviously. But this way I can't [factorize](https://github.com/explosion/spaCy/pull/2348) my model to use a specific preprocessor, right?

**Comment by ines** [comment]
> But this way I can't factorize my model to use a specific preprocessor, right?

No, but you could still ship your custom tokenizer in your model package's `__init__.py`. Alternatively, the entry points are available for language classes as well, like `English` or `German`. So you could also make your preprocessor a custom language subclass, like `HtmlEnglish` or something like that.

> `TypeError: object of type 'Report' has no len()`

Ah, I think I didn't read your code correctly. Your custom tokenizer and the `nlp` object should receive raw text – but you're passing int the `Report` object. So whatever creates that `Report` should ideally happen *within* the `__call__` method. Or you should pass in `report.body[:3000]` instead, which I assume is raw text?

**Comment by mr-bjerre** [comment]
Damn okay. Well the preprocessing is really stitching together elements from my `Report` object. I suppose I'll have to do it independently of `spaCy`. Should I formalize this into a feature request?
