### ISSUE TITLE
Weird behavior on noun chunk grouping on verb change

### ISSUE THREAD

**Issue by MasterButler** [explosion/spaCy#3467]
## How to reproduce the behaviour

I don't think this is normal behavior because the noun chunk grouping changes when I change a single verb.

I don't know the other scenarios that can reproduce this error, but at least I am able to consistently reproduce the error using the following example:

Input:
```
startingSentence = 'The quick brown fox swims over the lazy dog.'

nlp = spacy.load('en')
doc = nlp(startingSentence)
noun_chunks = doc.noun_chunks

for chunk in noun_chunks:
    print("New chunk:", chunk)
    for c in chunk:
        print("\t",c)

sentences = list(doc.sents)
sentence = sentences[0]
```
Output (Proper behavior):
```
New chunk: The quick brown fox swims
	 The
	 quick
	 brown
	 fox
	 swims
New chunk: the lazy dog
	 the
	 lazy
	 dog
```

Now for another case:
Input
```
startingSentence = 'The quick brown fox jumps over the lazy dog.'

nlp = spacy.load('en')
doc = nlp(startingSentence)
noun_chunks = doc.noun_chunks

for chunk in noun_chunks:
    print("New chunk:", chunk)
    for c in chunk:
        print("\t",c)

sentences = list(doc.sents)
sentence = sentences[0]
```
Output (Improper Behavior)
```
New chunk: the lazy dog
	 the
	 lazy
	 dog
```
## Your Environment

* Operating System: Windows 10 Education
* Python Version Used: 3.7.1
* spaCy Version Used: 2.1.0

**Comment by ines** [comment]
I just tested your example and it looks like this is caused by an incorrectly predicted part-of-speech tag. Under the hood, the tags and dependency parse are used to calculate the noun chunks. Here, the tagger incorrectly predicts "swims" as a plural noun:

<img width="794" alt="Screenshot 2019-03-23 at 10 50 45" src="https://user-images.githubusercontent.com/13643239/54864605-cd1a6d00-4d59-11e9-8ba9-0e22f6097750.png">

For corparison, here's the same example using a different tense, which is predicted correctly:

<img width="984" alt="Screenshot 2019-03-23 at 10 55 34" src="https://user-images.githubusercontent.com/13643239/54864661-824d2500-4d5a-11e9-99fb-4c7d548b3e00.png">

The sentence might seem very simple and like a weird example to mess up like this – but it's possible that the small model just doesn't generalise very well here. The choice of present tense in that particular construction isn't actually very common in English. Plus, "the quick brown fox" is an artificial phrase and there likely weren't many similar phrases in the training corpus.

I just tried the larger model `en_core_web_lg` and that one seems to get it right:

<img width="811" alt="Screenshot 2019-03-23 at 11 05 24" src="https://user-images.githubusercontent.com/13643239/54864731-a65d3600-4d5b-11e9-8c66-25e782f14e82.png">

```python
nlp = spacy.load("en_core_web_lg")
doc = nlp("The quick brown fox swims")
print([chunk.text for chunk in doc.noun_chunks])                                 
# ['The quick brown fox']
```

(Merging this issue with #3052!)
