### ISSUE TITLE
en_core_web_lg confuses 'May' (person) with 'may' (aux verb)

### ISSUE THREAD

**Issue by fersarr** [explosion/spaCy#3477]
This might also be another one for the master thread #3052 (Inaccurate pre-trained model predictions master thread):

The large english model (`en_core_web_lg`) is getting confused when the person is 'May' (as in Theresa May, for example). It is confusing it with `'may'`, the auxiliary verb. The funny thing here is that the medium model (`en_core_web_md`) is handling it just fine:

![Screen Shot 2019-03-24 at 8 50 17 PM](https://user-images.githubusercontent.com/3913371/54885661-b7e73080-4e76-11e9-9889-ec944be275f5.png)
![Screen Shot 2019-03-24 at 8 50 28 PM](https://user-images.githubusercontent.com/3913371/54885662-b7e73080-4e76-11e9-8733-bc8ad0d8b216.png)

**Comment by ines** [comment]
Yes, I'll merge this with #3052. The thing to keep in mind here is that: 

a) It's a very tricky and slightly ambiguous example, especially since there's no other relevant context in the sentence.
b) The English models were trained on the OntoNotes 5 corpus, which is considered fairly recent and modern. However, it's still from ~2005, with a lot of the texts being significantly older. Nobody talked about Theresa May back then and the model has likely never seen a reference to an actual person "May". So in one configuration, it generalises in a way that happens to be right, and in another one, it doesn't.
