### ISSUE TITLE
ValueError: [T001] Max length currently 10 for phrase matching.

### ISSUE THREAD

**Issue by keshavkumar08** [explosion/spaCy#3493]
I have a list of approximately 100 keywords and I need to search them in a huge corpus of over 0.1 million documents.

I don't want an exact match, for example, if the keyword is Growth Fund, I am expecting all the matches like growth funds, growth fund of America etc.

I have tried using PhraseMatcher but it gives a **ValueError: [T001] Max length currently 10 for phrase matching.**
```python
import spacy
from spacy.matcher import PhraseMatcher

full_funds_list_flat = "<list of 100+ Keywords>"


nlp = spacy.load('en_core_web_sm')
keyword_patterns = [nlp(text) for text in full_funds_list_flat]
matcher = PhraseMatcher(nlp.vocab)
matcher.add('KEYWORD', None, *keyword_patterns)
```

Any other suggestions on way of implementing this would be appreciated.

## Environment details

* **spaCy version:** 2.0.18
* **Platform:** Linux-4.15.0-30-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.5

**Comment by ines** [comment]
Two suggestions:

1. The latest version, `v2.1`, doesn't have a limit of 10 tokens anymore. So if you use that, the error should go away.
2. If your phrases are that long, changes are that the `PhraseMatcher` might not be the best solution because you have to cover a lot of very specific cases and it's easy to miss out on some variations. You might want to also look into the regular `Matcher`, which will allow you to write more general token-based rules: https://spacy.io/usage/rule-based-matching#matcher

**Comment by keshavkumar08** [comment]
> Two suggestions:
> 
> 1. The latest version, `v2.1`, doesn't have a limit of 10 tokens anymore. So if you use that, the error should go away.
> 2. If your phrases are that long, changes are that the `PhraseMatcher` might not be the best solution because you have to cover a lot of very specific cases and it's easy to miss out on some variations. You might want to also look into the regular `Matcher`, which will allow you to write more general token-based rules: https://spacy.io/usage/rule-based-matching#matcher

Thanks a lot!!
