### ISSUE TITLE
Installation Error Code 1

### ISSUE THREAD

**Issue by CMartin86** [explosion/spaCy#3497]
So, I'm completely new to this, but am trying to get Python and Spacy working - and Spacy isn't installing and shows the below error (which is still Greek to me..)

Any solution or advice would be amazing - I can't find the issue in the existing literature at Spacy.

```bash
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/wc/6xg4n7qs143668sp7kh5tg400000gn/T/pip-install-o15P2T/pathlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/wc/6xg4n7qs143668sp7kh5tg400000gn/T/pip-record-zJNd27/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/wc/6xg4n7qs143668sp7kh5tg400000gn/T/pip-install-o15P2T/pathlib/

```

## Your Environment
High Sierra 10.13.3
Python 3.7.3 (ALTHOUGH, when I query it in the control terminal, it says version 2.7... but I downloaded it this week)

**Comment by ines** [comment]
Hi! This might explain what's going on:

> Python 3.7.3 (ALTHOUGH, when I query it in the control terminal, it says version 2.7... but I downloaded it this week)

It's possible that you do have 3.7 installed, but when you run `python` or `pip` on the command line, it's actually running a *different executable*, Python 2.7. What happens when you type `python3` and `pip3`?

Also, if you're new to Python environment stuff, you might want to consider using a virtual environment. This will basically create an environment directory within your project directory and put the Python executable and all packages you install _in there_, instead of installing it all into your system Python. (If you're familiar with the JS/Node ecosystem, it's kinda like the `node_modules`.)

It does mean that you end up with more files, but it makes it so much easier to keep things separate, and it prevents one random thing you install from messing up your entire environment for everything else.

```bash
# This will create a new virtual environment in a directory .env
# You can also call it something else, like env or spacy-env or whatever
python3 -m venv .env
# Activate virtual environment
source .env/bin/activate
```

Depending on your terminal/shell, you might see something like `(.env)` in front of the command line prompt. Now everything you `pip install` (or `pip3 install`) will be installed into that environment directory. If something goes wrong, you can just remove `.env` and start again.

**Comment by CMartin86** [comment]
Thank you so so much for the quick and incredibly helpful response!

the env. allowed it to install succesfully, 
and weirdly when I typed Python3, I see:
"(.env) MacBook-Air-de-Paola:dataproc paolaascencio$ python3
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) "

But when I install things (pip), it reminds me that Python 2.7 runs out end of year and I need to upgrade...

Anyway... I'm sure it's 3.7.3... 

Now- Spacy:
- The environment set-up well 
- I believe Spacy installed without problems within it.
- From IDLE, when importing Spacy, it has an error which can't find the Module.
-> I assumed this is because IDLE/python is not operated from within the environment.
-> I uninstalled Python, got into the env, reinstalled, then installed again Spacy etc.

Still problem is it can't find the module >_<
(I even saved the working .py in the same folder just to be sure)
  File "/Users/paolaascencio/.env/bin/SPACYTEST1.py", line 1, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'

which python =
(.env) MacBook-Air-de-Paola:~ paolaascencio$ which python
/Users/paolaascencio/.env/bin/python

Spacy=
/Users/paolaascencio/.env/lib/python3.7/site-packages/en_core_web_sm -->
/Users/paolaascencio/.env/lib/python3.7/site-packages/spacy/data/en
You can now load the model via spacy.load('en')
Successfully installed es-core-news-sm-2.1.0
✔ Download and installation successful
You can now load the model via spacy.load('es_core_news_sm')
✔ Linking successful

No idea what could be missing still..

**Comment by honnibal** [comment]
> But when I install things (pip), it reminds me that Python 2.7 runs out end of year and I need to upgrade...

I think that probably means you're running the wrong pip. Misery, I know :(.

Try `python -m pip`. It resolves the path a bit more consistently than just `pip`.

**Comment by BreakBB** [comment]
You should make sure that `python -V` and/or `pip -V` point to your Python 3.7.3 installation. Most likely they don't.

Instead try to run `python3 -m pip install spacy` or `pip3 install spacy`. This makes sure the Python 3 installation is used.
