### ISSUE TITLE
TypeError: argument of type 'spacy.tokens.token.Token' is not iterable

### ISSUE THREAD

**Issue by podarrazvan** [explosion/spaCy#3537]
I need to check if the subject of the sentence exist in a list, but I have some problems with this error and I don't understand how can I fix it. I tried to change my spaCy version, but nothing... 

My code:

```
def __init__(self, user_input):
    personal_words = ["I", "ME", "US"]
    er = ["YOU"]
    pos = pop(user_input)
    for token in pos:
        if token.dep == nsubj:
            subject = token
            print(subject)
            if any(item in subject for item in personal_words):
                personal()
            elif any(item in subject for item in er):
                era()
            else:
                n_personal()
```

* Operating System:
Windows
* Python Version Used:
3.7.2
* spaCy Version Used:
2.0.18

**Comment by ines** [comment]
Errors like this usually indicate that your code assumes that an object isn't what you think it is. This ususally isn't a problem with spaCy. In your code, I'm pretty sure the problem is here:

> `item in subject`

The membership operator `in` needs a **sequence** – e.g. `"a" in ["a", "b", "c"]. But in your code `subject` is a `Token` object. If you want to check whether the token text matches a string, you actually want to be checking `token.text == string`.

**Comment by podarrazvan** [comment]
How can I change the token in a string? I tried this:
subject = untokenize.untokenize(token)
TypeError: 'spacy.tokens.token.Token' object is not iterable
.join():
AttributeError: 'spacy.tokens.token.Token' object has no attribute 'join'
And MosesDetokeniz
