### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by HarshavardhanG513** [explosion/spaCy#3562]
My training code for ner works when the data is in the program itself. I was trying to make it easier to use by making it read the data from a txt file. I copied the exact same training data onto the txt file and read it into a list.

But then it the throws the above error. How can i solve this?

My code for reading file into a list:
def readData(path):
    file = open(path, "r")
    TRAIN_DATA= file.readlines()
    file.close()
    return TRAIN_DATA

Example of my data:
("We require an accountant with at least 5 years of experience.", {"entities":[ (14, 24, 'JOB'), (39, 46, 'DATE') ]}),

The part thats throwing the error:
    texts = [text for text, annotation in batch]

Thanks in Advance

Environment:
spaCy version    2.1.3
Location         C:\Users\Harsha\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy
Platform         Windows-10-10.0.17763-SP0
Python version   3.7.3

**Comment by HarshavardhanG513** [comment]
my sample dataset:
[jobs.txt](https://github.com/explosion/spaCy/files/3058376/jobs.txt)

**Comment by ines** [comment]
The problem is that you're writing a Python list to raw text and then reading it back in line by line as raw text. That's not going to work. Instead, you want to be storing your data in a different format, like JSON. This thread is a good place to start: https://stackoverflow.com/questions/12309269/how-do-i-write-json-data-to-a-file 

You might also want to look into other tutorials on working with different data structures in Python – this should help you debug problems like this in your code in the future.

Please also note that this issue tracker is intended for **bug reports** and discussion related *specifically* to the spaCy core library. We're not able to answer general usage questions around programming in Python.
