### ISSUE TITLE
Empy pipeline when loading converted word vectors

### ISSUE THREAD

**Issue by afergadis** [explosion/spaCy#3585]
Following the process for converting and loading word vectors as described in 
[Converting word vectors for use in spaCy](https://spacy.io/usage/vectors-similarity#converting), for English word2vec file, gives a model with empty pipeline.

```
In [1]: import spacy
In [2]: nlp_en = spacy.load("en_vectors_custom_lg")
in [3]: nlp_en.pipe_names
Out[3]: []
```

The model has the `tokenizer` as I can get the tokens, but also I need sentence splitting and the `tagger`. For the sentence splitting I was able to add `sentencizer` 
```
In [4]: nlp_en.add_pipe(nlp_en.create_pipe('sentencizer'))
In [5]: nlp_en.pipe_names
Out[5]: ['sbd']
In [6]: doc = nlp_en('It is raining. Take an umbrella.')
In [7]: [s for s in doc.sents]
Out[7]: [It is raining., Take an umbrella.]
```
but I can't make the `tagger` work.
```
In [8]: from spacy.pipeline import Tagger
In [9]: tagger = Tagger(nlp_en.vocab)
In [10]: nlp_en.add_pipe(tagger, name='tagger')
In [11]: doc = nlp_en('It is raining. Take an umbrella.')
pipeline.pyx in spacy.pipeline.Tagger.__call__()
pipeline.pyx in spacy.pipeline.Tagger.predict()
AttributeError: 'bool' object has no attribute 'tok2vec'
```

Is it possible using this process to have the `tagger` work with my model? If no, what other option do I have to:

- add words to the vocabulary that might be missing
- assign custom vectors for the words in the vocabulary that I do have vectors

## Info about spaCy
* **spaCy version:** 2.0.18
* **Platform:** Linux-4.15.0-47-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.6.7
* **Models:** en, en_core_web_lg, de

**Comment by ines** [comment]
> Following the process for converting and loading word vectors as described in
Converting word vectors for use in spaCy, for English word2vec file, gives a model with empty pipeline.

This is expected, because you're initializing a new model from scratch, based on the English language data. Pipeline components like the tagger, parser and entity recognizer need binary data – either from a pre-trained model, or trained yourself.

> Is it possible using this process to have the tagger work with my model?

The problem in your example is that you're just adding a blank component with no data (model weights). The tagger component can assign tags – but if you actually want it to make predictions, you also need the trained statistical weights.

So you can either train a tagger yourself (probably not what you want), or use the tagger and weights from the pre-trained `en_core_web_sm` model. It needs to be the `sm` model, though and not `md` or `lg`, which were trained with the existing word vectors. If you replaced those vectors with your custom ones, you'd potentially see really bad results, since the weights don't match anymore.

So you could do something like this:

```python
base_nlp = spacy.load("en_core_web_sm")
tagger = base_nlp.get_pipe("tagger")

nlp_en.add_pipe(tagger)
nlp_en.to_disk("/path/to/custom/model")
```

**Comment by afergadis** [comment]
This is really helpful. Thank you!
