### ISSUE TITLE
spacy downgrade after prodigy wheel installed

### ISSUE THREAD

**Issue by ronaldoviber** [explosion/spaCy#3604]
when i load the prodigy wheel the installed spacy 2.1.3 was downgraded to 2.0.18
the result is the not-working of my current scripts. Also the prodigy.json stays empty.

```
----------------------
Successfully built peewee toolz ujson dill regex cytoolz wrapt
Installing collected packages: peewee, msgpack, msgpack-numpy, dill, toolz, cytoolz, wrapt, thinc, regex, ujson, spacy, pyjwt, cachetools, prodigy
  Found existing installation: thinc 7.0.4
    Uninstalling thinc-7.0.4:
      Successfully uninstalled thinc-7.0.4
  Found existing installation: spacy 2.1.3
    Uninstalling spacy-2.1.3:
      Successfully uninstalled spacy-2.1.3
Successfully installed cachetools-3.1.0 cytoolz-0.9.0.1 dill-0.2.9 msgpack-0.5.6 msgpack-numpy-0.4.3.2 peewee-2.10.2 prodigy-1.7.1 pyjwt-1.7.1 regex-2018.1.10 spacy-2.0.18 thinc-6.12.1 toolz-0.9.0 ujson-1.35 wrapt-1.10.11
--------------------------
```

Operating System: Debian 9.8
Python Version Used: 3.5.3
spaCy Version Used: before prodigy wheel: 2.1.3
prodigy: 1.7.1

**Comment by ines** [comment]
This is currently expected – the latest version of Prodigy depends on spaCy v2.0.x, so if you install the Prodigy wheel into an environment running spaCy v2.1.x, it'll be downgraded to match the wheel.

We're currently working on the next Prodigy version that will include support for spaCy v2.1.x. Since this version also requires new models and means that all users have to retrain their models, we want to make sure it all works well before we tell all our Prodigy user to upgrade and retrain. There were also a number of bugs in v2.1.x we wanted to fix before the Prodigy upgrade. Here's the thread on Prodigy + spaCy v2.1: https://support.prodi.gy/t/support-for-spacy-v2-1/1318

**Comment by ronaldoviber** [comment]
> *We have a build of Prodigy that works with v2.1*

is it possible to get the working version?

I just start with prodigy and since one year i work with spacy (successfully!). I get issues with my scripts while downgrading spacy and in this current environment it makes no sense to integrate prodigy to do this work again when a new version releases.

I'm sitting between the chairs...
