### ISSUE TITLE
Can't override an existing named entity

### ISSUE THREAD

**Issue by jmugan** [explosion/spaCy#3608]
I get the error `ValueError: [E103] Trying to set conflicting doc.ents: '(5, 7, 'PERSON')' and '(5, 7, 'PRESIDENT')'. A token can only be part of one entity, so make sure the entities you're setting don't overlap.`

Related to issue https://github.com/explosion/spaCy/issues/2550, which was closed and locked. This worked in the previous versions of spaCy.

Is there anything I can do to get around this error? Pass in a flag or something?

## How to reproduce the behaviour
Take the example under processing pipelines https://spacy.io/usage/processing-pipelines and try to relabel Barack Obama as a president, as shown below.
```
import spacy
from spacy.matcher import PhraseMatcher
from spacy.tokens import Span

class EntityMatcher(object):
    name = "entity_matcher"

    def __init__(self, nlp, terms, label):
        patterns = [nlp.make_doc(text) for text in terms]
        self.matcher = PhraseMatcher(nlp.vocab)
        self.matcher.add(label, None, *patterns)

    def __call__(self, doc):
        matches = self.matcher(doc)
        for match_id, start, end in matches:
            span = Span(doc, start, end, label=match_id)
            doc.ents = list(doc.ents) + [span]
        return doc

nlp = spacy.load("en_core_web_sm")
terms = (u"cat", u"dog", u"tree kangaroo", u"giant sea spider", u"Barack Obama")
entity_matcher = EntityMatcher(nlp, terms, "PRESIDENT")

nlp.add_pipe(entity_matcher, after="ner")

print(nlp.pipe_names)  # The components in the pipeline

doc = nlp(u"This is a text about Barack Obama and a tree kangaroo")
print([(ent.text, ent.label_) for ent in doc.ents])
```

## Info about spaCy

* **Models:** en_core_web_sm, en
* **Platform:** Darwin-18.5.0-x86_64-i386-64bit
* **Python version:** 3.5.6
* **spaCy version:** 2.1.3

**Comment by ines** [comment]
Yes, this is expected behaviour – one token can only be part of an entity and in previous versions, spaCy would just quietly swallow existing entity annotations, which was kind of a bug. If you want to set entities with `start` / `end` tokens that overlap with existing entities, you'll need to remove those first.

You can see an implementation of this here in the `EntityRuler`:

https://github.com/explosion/spaCy/blob/f2f2df6e78cfe042d11c85dfa30a698b6063e1c4/spacy/pipeline/entityruler.py#L81-L93

You might actually want to check out the `EntityRuler` component, which includes an `overwrite` flag and was designed for turning rule matches into named entities: https://spacy.io/usage/rule-based-matching#entityruler

Also, for completeness: If your use case needs more of a general-purpose "span container" with overlapping spans, the `doc.ents` might just not be the right choice, because they resolve to single token labels. Instead, you could use a [custom extension attribute](https://spacy.io/usage/processing-pipelines#custom-components-attributes) like `doc._.custom_overlapping_spans` that defaults to an empty list, and then append spans to it.

**Comment by jmugan** [comment]
Thank you for the quick response. I was able to use your suggestion to modify the example to do what I wanted
```
import spacy
from spacy.matcher import PhraseMatcher
from spacy.tokens import Span

class EntityMatcher(object):
    name = "entity_matcher"

    def __init__(self, nlp, terms, label):
        patterns = [nlp.make_doc(text) for text in terms]
        self.matcher = PhraseMatcher(nlp.vocab)
        self.matcher.add(label, None, *patterns)

    def __call__(self, doc):
        matches = self.matcher(doc)
        seen_tokens = set()
        new_entities = []
        entities = doc.ents
        for match_id, start, end in matches:
        #    span = Span(doc, start, end, label=match_id)
        #    doc.ents = list(doc.ents) + [span]
            if any(t.ent_type for t in doc[start:end]): # and not self.overwrite:
                continue
            # check for end - 1 here because boundaries are inclusive
            if start not in seen_tokens and end - 1 not in seen_tokens:
                new_entities.append(Span(doc, start, end, label=match_id))
                entities = [
                    e for e in entities if not (e.start < end and e.end > start)
                ]
                seen_tokens.update(range(start, end))

        doc.ents = tuple(entities) + tuple(new_entities)
        return doc

nlp = spacy.load("en_core_web_sm")
terms = (u"cat", u"dog", u"tree kangaroo", u"giant sea spider", u"Barack Obama")
#terms = ('Barack Obama',)
entity_matcher = EntityMatcher(nlp, terms, "PRESIDENT")

nlp.add_pipe(entity_matcher, after="ner")

print(nlp.pipe_names)  # The components in the pipeline

doc = nlp(u"This is a text about Barack Obama and a tree kangaroo")
print([(ent.text, ent.label_) for ent in doc.ents])
```
