### ISSUE TITLE
Incorrect Broadcast input array shape error when trying to use Pretraining  

### ISSUE THREAD

**Issue by pratikdk** [explosion/spaCy#3616]
## Environment

* Operating System: Cent OS
* Python Version Used: 3.7.3
* spaCy Version Used: 2.1.3
* Environment Information: Anaconda Jupyter Lab

I am trying to use spacy's 'pretrain' feature for a NER task, so here is what i tried doing(I am still trying to use it), 

**Step 1:**  I started by initializing the model with 'en_core_web_lg' next i saved this model to disk, and tested its NER capability on few lines to see if it recognizes the tags in those test lines.(Made  a note of ignored tags)

**Step 2:** Next I created a .jsonl file with new data to train on (about 20 new lines, I wanted to see the model's capability given new data around an entity(ignored tags found earlier) will it be able to correctly identify tags after doing transfer learning). So using this .jsonl and the model I saved earlier file I used 'spacy pretrain' command to train, this created a token2vec .bin file for me (model999.bin).

**Step 3:** Next I created a function which takes location of earlier saved model(model saved in step 1) and location of token2vec (model999.bin file obtained in step 2). Inside the function it loads the model>creates/gets pipe>disables rest of the files>uses (pipe_name).model.tok2vec.from_bytes(file_.read()) to read from model999.bin and broadcast the learned vectors to base model.

**But when I run this function, I get this error:**
`ValueError: could not broadcast input array from shape (96,3,384) into shape (96,3,480)`
(I have uploaded the entire notebook here: [https://github.com/pratikdk/ner_test/blob/master/base_model_contextual_TF.ipynb]).

**In order to pretrain I used this function**
`python -m spacy pretrain ub.jsonl model_saves w2s`

**Here are the 20 lines I tried training on top of the base model**
[https://github.com/pratikdk/ner_test/blob/master/ub.jsonl]

**What am I doing wrong here exactly? Please can you also point the fix, I am sure many would need insight on this.**

**Comment by honnibal** [comment]
I think the reason your code doesn't execute is that you didn't pass the `--use-vectors` argument to `spacy pretrain`. But I think pretraining also isn't the right approach for what you're trying to do.

The `--use-vectors` argument is necessary if you want the word model to include features from the GloVe vectors. That's what the `en_core_web_lg` and `en_core_web_md` models do. You need to pretrain with the same network structure you'll use at training and runtime, so if you want to use those features at runtime, you need to use them in pretraining.

The deeper thing though is that it doesn't make sense to try to use `pretrain` if you also want to use the weights from `en_core_web_lg`. Probably the best way to think of it is, you can initialise the `tok2vec` weights one of three ways:

1. Randomly. This is what happens when you call `.begin_training()`: you get random weights.
2. Loaded from an existing NER/parsing/tagging/etc model. This is what happens when you call `spacy.load()`
3. Loaded from `pretrain`, which uses a language model objective.

You only get to have one copy of the `tok2vec` weights. You can either load them from `spacy pretrain`, or load them from `en_core_web_lg`. If you load `en_core_web_lg` and then change out the tok2vec weights, the model will perform terribly, as the higher layers will be getting inputs they weren't trained with.

**Comment by pratikdk** [comment]
Thanks a lot for answering my question that definitely solved the issue, Also since you suggested that my approach being not the correct way to use pretrain for NER task, can you suggest a possible flow if you could use pretrain for NER task, how would your approach be given that you already have base weights (say from en_core_web_lg) and now you want the weights to adapt new vocab(entity) as well, since in my case for a test case it wasn't recognizing Uber(as an Organisation), with weights from en_core_web_lg, so I tried using the flow I mentioned on top so that the vector I obtained (after pretraining with 20 lines which had mentions of Uber over en_core_web_lg) can gain some contextual knowledge of the placing of the word Uber. 
**Please can you base your approach over the NER task or if possible point me to some blogs/articles, which you have come forward before, It will be very insightful for me.**
