### ISSUE TITLE
Multi-language model incorrectly splits named entities by minus character

### ISSUE THREAD

**Issue by evrial** [explosion/spaCy#3629]
## How to reproduce the behaviour
```
In [1]: import spacy 
   ...:  
   ...: nlp = spacy.load("en_core_web_sm") 
   ...: doc = nlp("Rasmus Luckow-Nielsen is a good man") 
   ...:  
   ...: for ent in doc.ents: 
   ...:     print(ent.text, ent.start_char, ent.end_char, ent.label_) 
   ...:                                                                                                                                                                           
/Users/evrial/anaconda3/envs/gay/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)
Rasmus Luckow-Nielsen 0 21 PERSON

In [2]: import spacy 
   ...:  
   ...: nlp = spacy.load("xx_ent_wiki_sm") 
   ...: doc = nlp("Rasmus Luckow-Nielsen is a good man") 
   ...:  
   ...: for ent in doc.ents: 
   ...:     print(ent.text, ent.start_char, ent.end_char, ent.label_) 
   ...:                                                                                                                                                                           
Rasmus Luckow 0 13 LOC
Nielsen 14 21 LOC
```

## Info about spaCy

* **spaCy version:** 2.1.3
* **Platform:** Darwin-18.5.0-x86_64-i386-64bit
* **Python version:** 3.7.1

**Comment by ines** [comment]
I was a bit confused at first, because I initially read it as the model outputting entities without `-` characters. 

But I think the main difference here is that the `xx` model predicts the token sequence  `['Rasmus', 'Luckow', '-', 'Nielsen']` as `['B-LOC', 'L-LOC', 'O', 'U-PER']`, whereas the English model predicts it as `['B-PERSON', 'I-PERSON', 'I-PERSON', 'L-PERSON']`, which is correct in this case.

It's definitely expected that the pre-trained English model will perform better overall compared to the multi-language model trained on only Wikipedia entities. I'll merge this with #3052.

**Comment by evrial** [comment]
No this is tokenization issue because in this model any kind of word with minus splits like two words.
