### ISSUE TITLE
German stopwords

### ISSUE THREAD

**Issue by bobbyrenwick** [explosion/spaCy#364]
Hey, it would be great if you could add `spacy.de.STOPWORDS` to match `spacy.en.STOPWORDS`.

**Comment by honnibal** [comment]
Good point! Forgot about these.

In the meantime you can set your own as follows:

    import spacy
    
    de_nlp = spacy.load('de')
    for stopword in my_stop_words:
        lexeme = nlp.vocab[stopword]
        lexeme.is_stop = True

The attribute will be inherited by all tokens, because all tokens of a given type receive a reference to that type. So when you write to the lexical type via the vocab, all tokens will see the updated attribute.

**Comment by bobbyrenwick** [comment]
Thanks for the workaround!

**Comment by ines** [comment]
[Fixed!](https://github.com/explosion/spaCy/blob/master/spacy/de/language_data.py)
