### ISSUE TITLE
token.deep_ for ROOT

### ISSUE THREAD

**Issue by podarrazvan** [explosion/spaCy#3650]
If I want to find the root of a text with token.deep_, I need to do something like this

```
                for token in pos:
                    if str(token.pos) == str(ROOT):
                        root = token
```

But to do this, first I have to import ROOT from spacy.symbols where exist only root, not ROOT, and if I use " if str(token.pos) == str(root): " will not work
                        root = token

**Comment by ines** [comment]
You definitely don't want to be calling `str` around a symbols or integer attributes. If you want strings, that's what the underscore attributes like `token.dep_` or `token.pos_` are for. And if you want to compare integer IDs, you should compare them directly.

The reason your code won't work is because `"ROOT"` is a dependency label and not a part-of-speech tag. If you want the root of a sentence, you want to be looking at the `.dep_` attribute:

```python
doc = nlp("Hello world")
for token in doc:
    if token.dep_ == "ROOT":
        print(token.text)
```
