### ISSUE TITLE
POS Tagging shows different results in spacy online pos tagger and in code

### ISSUE THREAD

**Issue by aarthirangan** [explosion/spaCy#3671]
## How to reproduce the behaviour
nlp = spacy.load("en_core_web_sm")
print(nlp.meta['version'])
nerval = nlp("face intense")
for token in nerval:
    print(token.pos_)

gives me the output

2.1.0
VERB
ADJ

while spacy online pos tagger when given the same phrase "face intense" classifies "face" as a NOUN. while the code using en_core_web_sm model classifies it as a verb. I want to get NOUN as result.

## Info about spaCy

* **spaCy version:** 2.1.3
* **Platform:** Windows-10-10.0.15063-SP0
* **Python version:** 3.7.0
* **en_core_web_sm model version : 2.1.0 (as printed above)
Im using PyCharm IDE. 

Please clarify

TIA

**Comment by ines** [comment]
By the online POS tagger, you mean the displaCy demo, right? https://explosion.ai/demos/displacy If so, that'd explain what's going on: In your code, you're using spaCy v2.1 and the 2.1 models. The displaCy demo we're hosting currently still uses the 2.0 models (see the versions in the dropdown).

Specific predictions can differ across models and versions – especially for your case, where you're only processing a single phrase `"face intense"` instead of a sentence and also a pretty ambiguous phrase (to be honest, I don't think I understand what it's supposed to mean?). 

Part-of-speech tags are predicted based on the **context**. Whether something is a verb or a noun depends on the context of that word within a sentence. The text you're processing has no context, so what the mode predicts is completely arbitrary.

**Comment by niloct** [comment]
+1, in pt language. displacy tagged an preposition correctly with ADP but the current spacy lib tagged it as VERB. Installing spacy v.2.0.18 solved the problem here too.
