### ISSUE TITLE
spacy.explain('acl') does not work.

### ISSUE THREAD

**Issue by ldorigo** [explosion/spaCy#3679]
## How to reproduce the behaviour

```python
spacy.explain('acl')
```

## Your Environment

* **spaCy version:** 2.1.3
* **Platform:** Darwin-18.5.0-x86_64-i386-64bit
* **Python version:** 3.6.8
* **Models:** en

For some reason spacy doesn't want to tell me what 'acl' stands for :-) 

Cheers!

**Comment by ines** [comment]
Thanks for the report – looks like that label isn't in the glossary yet (which `spacy.explain` refers to under the hood). Source is here: https://github.com/explosion/spaCy/blob/master/spacy/glossary.py

See the docs for the definition of `acl`: https://github.com/explosion/spaCy/blob/master/website/docs/api/annotation.md#syntactic-dependency-parsing-dependency-parsing

> clausal modifier of noun (adjectival clause)

If you (or someone else) wants to submit a PR to `glossary.py`, that'd be cool. Otherwise, I can also take care of this later 🙂

**Comment by ldorigo** [comment]
I added it along with any other (english) dependency tags that were not in the glossary

**Comment by ines** [comment]
@ldorigo This is great, thanks 🙏 Happy to merge that, so feel free to submit a pull request to this repo from your fork.
