### ISSUE TITLE
Adapting extracting entity relations example

### ISSUE THREAD

**Issue by maximeboun** [explosion/spaCy#3681]
Hi, Since Span.merge() is now deprecated, I'm trying to adapt my code and use Doc.retokenize(). However, I can't quite get the same result as with span.merge(). I get an error: `ValueError: [E102] Can't merge non-disjoint spans. 'a' is already part of tokens to merge.`

Here's the code to reproduce: 
```
TEXTS = [
    '2017 vs. 2016\nWe have achieved record revenue two years in a row, with 2017 revenue of $62.8 billion, up $3.4 billion, or 6%, from 2016. After\nadjusting for the Q2 2017 divestiture of ISecG, revenue grew 9% from 2016. The increase in revenue was primarily driven by strong\nperformance across our data-centric businesses, which collectively grew 16% year over year after adjusting for ISecG. We saw revenue\ngrowth across our DCG, IOTG, NSG, and PSG businesses, and 2017 revenue includes $210 million from our Mobileye business. The\nincrease in revenue was partially offset by $1.6 billion from the divestiture of ISecG and by a change to the Intel Inside® program in\n2017. \n'
    ,
    "Revenue exceeded twelve billion dollars, with a loss of $1b."
]
def extract_currency_relations(doc):
    # merge entities and noun chunks into one token
    spans = list(doc.ents) + list(doc.noun_chunks)

    with doc.retokenize() as retokenizer:
        for span in spans:
            retokenizer.merge(span)

    relations = []
    for money in filter(lambda w: w.ent_type_ == "MONEY", doc):
        if money.dep_ in ("attr", "dobj"):
            subject = [w for w in money.head.lefts if w.dep_ == "nsubj"]
            if subject:
                subject = subject[0]
                relations.append((subject, money))
        elif money.dep_ == "pobj" and money.head.dep_ == "prep":
            relations.append((money.head.head, money))
    return relations


print("Processing %d texts" % len(TEXTS))

for text in TEXTS:
    doc = nlp(text)
    relations = extract_currency_relations(doc)
    for r1, r2 in relations:
        print("{:<10}\t{}\t{}".format(r1.text, r2.ent_type_, r2.text))

```

Could you look into this?
I really appreciate your help!

**Comment by ines** [comment]
Ah, sorry – I just realised we hadn't updated [that example](https://github.com/explosion/spaCy/blob/master/examples/information_extraction/entity_relations.py) yet.

The reason you're seeing this error is that the `spans` contain duplicates – "the prior year" is both a noun chunk and an entity, so it appears twice:

```
[$9.4 million, the prior year, $2.7 million, Net income, the prior year]
```

Previously, `span.merge` would just quietly ignore overlapping spans and only one of the conflicting merges would succeed. This was kind of a bug, because it was hiding the fact that the spans couldn't actually be merged. The new `Retokenizer` now actually raises an error. (In this case, the spans aren't just overlapping, but actually identical – so arguably, the `Retokenizer` should just ignore them.)

I wrote a little helper function `filter_spans` that takes a list of spans and filters out overlaps and duplicates. I think we should also ship this with spaCy, e.g. in `spacy.util`.

```python
def filter_spans(spans, prefer_longest=True):
    # Filter a sequence of spans so they don't contain overlaps
    get_sort_key = lambda span: (span.end - span.start, span.start)
    sorted_spans = sorted(spans, key=get_sort_key, reverse=prefer_longest)
    result = []
    seen_tokens = set()
    for span in spans:
        if span.start not in seen_tokens and span.end - 1 not in seen_tokens:
            result.append(span)
            seen_tokens.update(range(span.start, span.end))
    return result
```

In your `extract_currency_relations` function, you can now do the following:

```diff
def extract_currency_relations(doc):
    # merge entities and noun chunks into one token
    spans = list(doc.ents) + list(doc.noun_chunks)
+   spans = filter_spans(spans)

    with doc.retokenize() as retokenizer:
        for span in spans:
            retokenizer.merge(span)
```

**Comment by maximeboun** [comment]
I might be wrong, but shoudn't it be `for span in sorted_spans :` instead of `for span in spans:` ?

**Comment by ines** [comment]
Oh yes, you're right! Sorry, this was a typo, thanks for pointing this out. Fixing! (In the example case in `spacy/examples`, it didn't really make a difference because there were no overlaps of different lengths. But without the sorting, the preference for long/short spans wouldn't actually work.)
