### ISSUE TITLE
Loading multiple NER models in one pipeline

### ISSUE THREAD

**Issue by kaushik88** [explosion/spaCy#3691]
## How to reproduce the behaviour

I trained a new NER model (similar to the train_new_entity_type.py [here](https://github.com/explosion/spaCy/blob/master/examples/training/train_new_entity_type.py)) from a blank model. Now I want to use this model along with the en_core_web_md model.

I now load the 2 NERs this way - 

```
nlp = spacy.load('en_core_web_md')
doc = nlp("Do you like horses?")
ner = nlp.create_pipe("ner")
ner.from_disk("{}/ner".format(model_dir), exclude=['vocab', 'tagger', 'parser'])
nlp.add_pipe(ner, "new_ner")
print(nlp.pipeline)  # prints both ner models
for ent in doc.ents:
    print(ent.label_, ent.text) # doesn't recognize ANIMAL entities
```

This doesn't recognize the new entities. This is similar to the issue described in [3337](https://github.com/explosion/spaCy/issues/3337#issuecomment-468061378).

## Info about spaCy

* **spaCy version:** 2.1.3
* **Platform:** Darwin-18.2.0-x86_64-i386-64bit
* **Python version:** 3.6.5

**Comment by ines** [comment]
I think the problem here is that you've trained an NER component on a very small and brittle example set (the horses) and a blank base model without word vectors. You're then trying to use it in a pre-trained model *with* word vectors. So it's not surprising that it doesn't predict any entities here. Ideally, you want to train with the same base language and the same vectors.

Loading multiple models of the same type in one pipeline is currently not supported out of the box. It's also a more complex question, because there's no easy answer for how the entity tags on the tokens should be set. Should the secopnd model overwrite the predictions of the first? By default, spaCy would likely raise an error in this scenario. For more details on this, check out the open enhancement issue in #2920.
