### ISSUE TITLE
Lemma of the term "cause"

### ISSUE THREAD

**Issue by aafreenrah** [explosion/spaCy#3733]
Spacy returns "**because**" as the lemma form of "**cause**".
There is no definition like this. How this will be possible.

* Operating System: windows 10
* Python Version Used: 3.6.8
* spaCy Version Used: 2.0.18

**Comment by ines** [comment]
If I remember correctly, this could potentially be related a problem in a previous version, due to how lemmas were assigned via the tokenizer exceptions. I've tried it with the latest version and can't reproduce the problem. So could you try again with 2.1.4? If the problem still occurs, feel free to reopen and include a reproducible example.
