### ISSUE TITLE
Tokenization fails to split by symbols

### ISSUE THREAD

**Issue by dkarmon** [explosion/spaCy#3763]
Hi,
I'm would like to tokenize sentences with special symbols (><=). However, the default behavior of spacy en_core_web_sm seem to produce unexpected results.
for instance, 
```
doc = nlp("score should be >=3 ")
for token in doc:
    print(token.text)
```

The expected behavior would be:
```
score
should
be
>
=
3

```
but the output is 
```
score
should
be
>
=3
```

How do you recommend fixing it? I tried customizing the tokenizer and add to prefix_search a pattern, but it doesn't seem to work.
Please advise

**Comment by andremarco** [comment]
The same happens for example in Italian where there is a huge use of ' symbol. The sentence "l'operaio è stato allontanato" is tokenized as:
- l'operaio
- è 
- stato
- cacciato

instead of
- l
- operaio 
- è 
- stato 
- cacciato

**Comment by ines** [comment]
There'll always be trade-offs when it comes to tokenization and spaCy will likely never be able to handle every expected use case out-of-the-box. (Even what's expected isn't always so black and white – for instance, I would have probably expected `">=3"` to be split into `[">=", "3"]`?)

We're always happy to accept pull requests to the global or language-specific punctuation rules, especially for additional segmentation. The only thing that's important is that the existing tests pass, and that the tokenization rules do not require variable-width lookbehinds.

> How do you recommend fixing it? I tried customizing the tokenizer and add to prefix_search a pattern, but it doesn't seem to work.

You probably want to add a prefix rule to split `=` before numbers. Alternatively, you can also write match patterns to capture cases like this and then use the `Retokenizer` to split the tokens: https://spacy.io/usage/linguistic-features#retokenization

@andremarco The problem with your expected tokenization here is that this version will never be true: spaCy's tokenization is *non-destructive*, so no information is discarded and the the string values of the tokens plus whitespace always needs to add up to the original text. This means that the first token would have to be `l'` instead of `l`.

For now, you could probably write a rule that handles the `l'` prefix in Italian and splits it using the `Retokenizer`. Also, if there's a more general-purpose solution you want to suggest that's compatible with the current tests, feel free to submit a PR.
