### ISSUE TITLE
When I run train_new_entity_type.py, it appears “ModuleNotFoundError: No module named 'spacy.symbols'”，but I have installed the spacy in windows system？Can you tell me what I should do? 

### ISSUE THREAD

**Issue by Arrcil** [explosion/spaCy#3791]
## Your Environment

* Operating System: Windows7 
* Python Version Used: 3.7
* spaCy Version Used: 2.1.4
* Environment Information: Anaconda

**Comment by Arrcil** [comment]
When I run train_new_entity_type.py, it appears “ModuleNotFoundError: No module named 'spacy.symbols'”，but I have installed the spacy in windows system？Can you tell me what I should do?

**Comment by ines** [comment]
This usually happens if spaCy didn't install or compile correctly. `spacy.symbols` is the first compiled module it encounters, so it happens to fail here.

Try double-checking our conda environment, make sure that everything installed correctly (if you installed via `pip`, maybe try installing via `conda`). Also double-check that you're running the script in the correct environment.
