### ISSUE TITLE
Failing to match pattern with optional tokens

### ISSUE THREAD

**Issue by Impelon** [explosion/spaCy#3792]
## How to reproduce the behaviour

Suppose I have this program:
``` python
import spacy
from spacy.matcher import Matcher

nlp = spacy.load('en_core_web_lg')
matcher = Matcher(nlp.vocab)

doc = nlp("This is example. This is an example. This is also an example.")
pattern = [{"LOWER": "is"}, {"OPT": "*"}, {"LOWER": "example"}]
matcher.add("test", None, pattern)

matcher(doc)
```
I would expect this to match three times in the given text, since any token between the first and last pattern should be optional. Unfortunately it only matches "is an example" from the second sentence. I also tried these patterns, which also do not produce the result I need:

```
patternA = [{"LOWER": "is"}, {}, {"LOWER": "example"}] # same as above
patternB = [{"LOWER": "is"}, {"LOWER": "example"}] #only matches in the first sentence
patternC = [{"LOWER": "is"}, {"OPT": "*", "IS_ACSII": True}, {"LOWER": "example"}] # same as patternA
```

## Info about spaCy

* **spaCy version:** 2.1.4
* **Platform:** Linux-4.15.0-50-generic-x86_64-with-elementary-5.0-juno
* **Python version:** 3.6.7

**Comment by ines** [comment]
Hi, I think you might have a small typo in your example: it says `"OPT"` instead of `"OP"` (for "operator", [see here](https://spacy.io/usage/rule-based-matching#quantifiers)).

When I change that, the pattern produces the following results:

```
is example,
is an example,
is example. This is an example,
is also an example,
is an example. This is also an example,
is example. This is an example. This is also an example
``` 

I'd say that this is expected behaviour here, because the matcher will match across the whole `doc`, and you're looking for "is" and "example" with zero or more tokens in between. So the matcher will give you all possible combinations of tokens where this condition is true.

**Comment by Impelon** [comment]
You are absolutely right, 
sorry for wasting your time, and thanks for the quick help!
