### ISSUE TITLE
biluo_tags_from_offsets is giving inconsistent output

### ISSUE THREAD

**Issue by Aki58** [explosion/spaCy#3805]
## How to reproduce the behaviour
I am getting inconsistent output while using function biluo_tags_from_offsets. In the result i am getting an extra tag.
```python
from spacy.gold import biluo_tags_from_offsets
import spacy
nlp = spacy.blank('en')
doc = nlp(u"Can you provide me the details of my last transaction")
entities = [(37, 41, "ordinal")]
tags = biluo_tags_from_offsets(doc, entities)
print(doc)
print(tags)
```
 I am getting output:
```
Can you provide me the details of my last transaction
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'U-ordinal', 'O']
```
instead of:
```
Can you provide me the details of my last transaction
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'U-ordinal', 'O']
```

## Your Environment

* Operating System: Ubuntu 18.04
* Python Version Used: 3.6.7
* spaCy Version Used: 2.0.17
* Environment Information: Allennlp environment in anaconda

**Comment by ines** [comment]
Hmm, I just tested it in the latest version (v2.1.4) and I can't reproduce it. When I try your example, I'm getting a `doc` with 10 tokens and 10 tags:

```python
print(len(doc), [t.text for t in doc])                                             
# 10 ['Can', 'you', 'provide', 'me', 'the', 'details', 'of', 'my', 'last', 'transaction']

print(len(tags), tags)
# 10 ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'U-ordinal', 'O']
```

And the span described by the offsets correctly maps to the token "last":

```python
print(doc.text[37:41])
# 'last'
```

Just noticed that you're on an older version of spaCy, so it's possible that we previously had a bug here that was since fixed. Can you try again with the latest version and see if it's fixed for you?

**Comment by Aki58** [comment]
I think there was some problem with data 
```
11 ['Can', 'you', 'provide', 'me', '\xa0', 'the', 'details', 'of', 'my', 'last', 'transaction']
11 ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'U-ordinal', 'O']
```
after backspace before "the" and adding space it worked. although ''\xa0" this was not showing in orignal data
