### ISSUE TITLE
Adding a component with a customized tokenizer

### ISSUE THREAD

**Issue by moh55m55** [explosion/spaCy#3812]
Hello,
I want to use a customized tokenizer but also want to add a custom_sentencizer component. Any idea ? 
Something like this: 

```
import spacy
from spacy.tokens import Doc, Span, Token

class WhitespaceTokenizer(object):
    def __init__(self, vocab):
        self.vocab = vocab

    def __call__(self, text):
        words = text.split()
        # All tokens 'own' a subsequent space character in this tokenizer
        spaces = [True] * len(words)
        return Doc(self.vocab, words=words, spaces=spaces)
    
def custom_sentencizer(doc):
    for i, token in enumerate(doc[:-2]):
        # Define sentence start if pipe + titlecase token
        if token.text == "\n":
            doc[i+1].is_sent_start = True
        else:
            # Explicitly set sentence start to False otherwise, to tell
            # the parser to leave those tokens alone
            doc[i+1].is_sent_start = False
    return doc

nlp = spacy.load("en_core_web_sm")
#nlp.tokenizer = WhitespaceTokenizer(nlp.vocab)
#nlp.add_pipe(custom_sentencizer, before="parser") 
doc=nlp("some text")
```

**Comment by BreakBB** [comment]
What exactly is your problem? Any error message? Have you had a look at [the docs](https://spacy.io/usage/linguistic-features#tokenization) about creating a custom tokenizer?

**Comment by moh55m55** [comment]
The problem when adding the WhitespaceTokenizer, the "\n" character got lost; thus custom_sentencizer was not able to detect the sentences boundaries sine it relies on "\n" character.

**Comment by BreakBB** [comment]
I am not sure what you're trying to achive with yout `WhitespaceTokenizer`, but if you simply want spaCy to tokenize the sentences on whitespace characters (instead of all single tokens like punctuations), you can use a default instance of the `Tokenizer`.

`nlp.tokenizer = Tokenizer(nlp.vocab)` will split on whitespaces and keep those as token.

With that your `custom_sentencizer` will work as expected on texts with "\n".
