### ISSUE TITLE
en_core_web_sm Installation Issue

### ISSUE THREAD

**Issue by sohilsshah91** [explosion/spaCy#3816]
Hi,

I am facing an issue with the en_core_web_Sm installation. I had spacy running before with 2.0.12 version with this library. However, to get access to more functionality I updated the spacy library and then faced issues with respect to reinstalling en_core_Web_sm language package. Now I am getting errors like 'No module named spacy.tokens' while doing python -m spacy download en_core_web_sm. I have faced this kind of error before too while installing or updating the library. Even downgrading is not helping. 

Please let me know what should be the steps
* Operating System: Windows 10
* Python Version Used: 3.6.7
* spaCy Version Used: 2.1.4
* Environment Information: virtual as well as local. Also trying to install using conda

**Comment by ines** [comment]
It sounds like the problem is that spaCy didn't install and/or compile correctly. So when you run the `spacy download` command, it tries to load the library and fails. If you upgraded in the same environment, you probably ended up in a messy state and now your installation is broken.

Try reinstalling spaCy in a clean (virtual) environment from scratch.
