### ISSUE TITLE
Sentence Tokenization

### ISSUE THREAD

**Issue by ndvbd** [explosion/spaCy#3824]
Spacy is great, but I see a problem which looks very simple - I think I do something wrong.
When I try to parse this sentence

`Do they want it?I think they do.`

The text is not break into 2 sentences around the quotation mark. I probably miss some parameter?

**Comment by ines** [comment]
The problem here is that the tokenizer doesn't split `it?I` into two tokens:

```python
doc = nlp("Do they want it?I think they do.")                                      
print([token.text for token in doc])                                                  
# ['Do', 'they', 'want', 'it?I', 'think', 'they', 'do', '.']
```

So when the dependency parser (the default way that spaCy segments sentences) tries to determine where the sentence boundaries are, it doesn't find any. See here for details on how to customise the tokenization and sentence segmentation:

* https://spacy.io/usage/linguistic-features#native-tokenizers
* https://spacy.io/usage/linguistic-features#sbd

**Comment by ndvbd** [comment]
Hi @ines, what kind of solutions are possible?
How can the tokenizer be improved to split words, for example, like CoreNLP?
