### ISSUE TITLE
Getting [Errno 24] Too many open files ../en_core_web_sm/meta.json

### ISSUE THREAD

**Issue by gaurav-ml1** [explosion/spaCy#3834]
Hi,
I am using **spaCy** in my project and It was working very well but after some time I got an error on server. 

 **[Errno 24] Too many open files:** '/home/ubuntu/webapp/venv/lib/python3.6/site-packages/en_core_web_sm/meta.json.

Can anybody suggest me a better solution ?

**Comment by BreakBB** [comment]
From what I know, your error has nothing specific to do with spaCy but is a simple error from the OS that the limit of concurrently open files was reached.
I have found [this answer](http://stackoverflow.com/questions/6774724/why-python-has-limit-for-count-of-file-handles#6774995) on stackoverflow, which allows you to see (on Linux) what the limit is:

`ulimit -n`

and if you have root permisson you can increase the limit with:

`ulimit -n 2048`

But most likely somewhere the opening and closing from files is not handled correctly so the limit is reached in the first place.

**Comment by gaurav-ml1** [comment]
Thanks for response but I have checked my code no any file handled in wrong way.

ulimit -n 2048

Not resolved.

**Comment by ines** [comment]
It's possible that somewhere, something isn't closed properly – this doesn't have to be in your code, it could be in any dependency. It's just tricky to debug, because it all happens on your system.

You could try logging all open files, as described in this thread: https://stackoverflow.com/questions/2023608/check-what-files-are-open-in-python

Run the following when your server starts, and then call `print_open_files()` periodically, until it dies. You should then see all files that are open.

```python
import io
import sys
import builtins
import traceback
from functools import wraps


def opener(old_open):
    @wraps(old_open)
    def tracking_open(*args, **kw):
        file = old_open(*args, **kw)

        old_close = file.close
        @wraps(old_close)
        def close():
            old_close()
            open_files.remove(file)
        file.close = close
        file.stack = traceback.extract_stack()

        open_files.add(file)
        return file
    return tracking_open


def print_open_files():
    print(f'### {len(open_files)} OPEN FILES: [{", ".join(f.name for f in open_files)}]', file=sys.stderr)
    for file in open_files:
        print(f'Open file {file.name}:\n{"".join(traceback.format_list(file.stack))}', file=sys.stderr)


open_files = set()
io.open = opener(io.open)
builtins.open = opener(builtins.open)
```

Another thing to check: How are you loading the `en_core_web_sm` model? Are you loading it once, or every time you make a request? Considering it eventually fails on loading the model meta, it seems like you might be loading the model a lot, instead of once and then keeping it in memory?
