### ISSUE TITLE
What is spacy's versioning philosophy?

### ISSUE THREAD

**Issue by ELind77** [explosion/spaCy#3845]
What is spacy's versioning philosophy? The models have notes in the README on how to interpret versioning but there's no equivalent for the library. While I understand that semantic versioning is the expectation here, I'm not clear on what the definition of a "backwards compatible bugfix" (patch update) is with respect to an NLP library. For example, in the 2.1.4 notes there is a bugfix that modifies the stopword list (issue #3530). For consumers that expect a particular parsing behavior (e.g. a model trained on spacy output) such a change could lead to an unexpected result. So is that really backwards-compatible from the perspective of a user?

Also, minor version updates in spacy sometimes require new models, which also doesn't seem backwards compatible.  

-- Eric

**Comment by honnibal** [comment]
The versioning philosophy is basically "SemVer, with some hand-waving". I think SemVer always has some amount of hand-waving, because even small changes are potentially "breaking" (e.g. renaming the variable name in a single-argument function). If you label every change as breaking, then you increment the major version all the time, which is really just like only having one version number.

We do have some additional constraints. If a new release will require new models to be trained, it should increment the minor version at least. Some hand-waving is involved here as well, since changes to the stop list or tokenization rules might cause some amount of train/test skew.
