### ISSUE TITLE
spacy.gold.docs_to_json method returning negative "head" values

### ISSUE THREAD

**Issue by rshahrabani** [explosion/spaCy#3846]
using the method spacy.gold.docs_to_json returns a negative value in some of the head objects:

{"id": 4, "orth": "million", "tag": "CD", "head": -3, "dep": "attr", "ner": "L-MONEY"}, 

Not sure if this is a bug, if not, what does that negative number pertain to? (does it refer to the id field?)

Thanks,

## Your Environment
* **spaCy version:** 2.1.4
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.7.3
* **Models:** en

**Comment by ines** [comment]
Yes, this is expected behaviour. The `head` value is the token index **relative** to the current token – e.g. `-1` for the previous token. Just like the tokens, the heads are zero-indexed. So to get the index / `id` of the head token, you can do `id + head`.

(For comparison, The CoNLL format typically annotates heads as `1`-indexed absolute indices with `0` indicating the root.)
