### ISSUE TITLE
displacy span rendering enhancement

### ISSUE THREAD

**Issue by yanaiela** [explosion/spaCy#3850]
## Feature description

Adding a customized html display option into the `render` function

Hi!
I have a usecase where I want to add a hover into the EntityRenderer spans in displacy.
For the meantime, I just copied the code and hard-coded into it the component I needed but I thought this might be useful for other people as well, and with other customized html options.
Therefore, I'll present here the implementation idea on changing the code before a PR, and I'd be happy to get a feedback if you think this would be a useful feature / how to make it more generic.

So the idea is to add into the `options` argument another dictionary parameter. This dictionary would consist of additional html code that would be inserted into the html place-holders. The keys of the additional dictionary are additional html code and their values are elements that can be inserted into the keys, is necessary. When that dictionary is not empty, the html place-holders - `TPL_ENT` and `TPL_ENT_RTL` would add these additional components.

How does this sound?
Also, I'm not sure if this is useful for the `DependencyRenderer`, let me know if you think it is.

**Comment by ines** [comment]
Thanks for raising this – it's definitely something I've thought about before! I wonder if we could maybe just add an option to replace the templates used for the page, container and spans. That would allow full customisation, without the awkwardness of just inserting HTML fragments into the templates (and the error potential here).

Another, slightly more complex solution would be to change the rendering slightly and use templating functions instead of just template strings. So there would be a function along the lines of `get_entity_span_html` that'd take the text and label as an argument and return a string. The advantage here is that it'd let you compute something with those values and include it in your template – for instance, you could look up the labels in a dictionary and display their descriptions in hover, and stuff like that. But I'm not sure if that's woth the added complexity.

**Comment by yanaiela** [comment]
That's a great idea.
I guess the first one is more customized right?
The issue with the second solution is that in a few days/weeks/months someone else would need a different visualization.

Maybe the solution is to combine the two?

Have a function (e.g. get_entity_span_html) that gets the text, label and an html template, where this template can be a prepared template (like the one that exists now) or a completely new one, which will provide the user complete freedom.

**Comment by ines** [comment]
> Have a function (e.g. get_entity_span_html) that gets the text, label and an html template, where this template can be a prepared template (like the one that exists now) or a completely new one, which will provide the user complete freedom.

Ah yeah, sorry if this was confusing in my description. The idea here would be that you could override those getter functions with your own. Your function would need to take the same arguments and has to return a string of markup – everything else is up to you.

**Comment by yanaiela** [comment]
I'm starting to work on this. Do you think it make sense to have a customizable html template for each one of the templates in the templates.py file?

**Comment by ines** [comment]
@yanaiela I think it would be good if the individual HTML templates (at least the most important ones) could be overwritten via an argument on initialization. So `html_template_ents` (or something like that) would default to the existing `TPL_ENT`. But a user could also choose to plug in their own.
