### ISSUE TITLE
Unexpected response from Index Head

### ISSUE THREAD

**Issue by sepidehamiri** [explosion/spaCy#3852]
I had a problem with defining index of token head, and I read [this issue](https://github.com/explosion/spaCy/issues/2322). But I get an unexpected response from Index head. Instead of getting this [0, 2, 0, 2, 5, 3] I getting this: [0, 1, 2, 3, 4, 5]

## How to reproduce the behaviour
```
from spacy.lang.en import English

nlp = English()
doc = nlp("find a cafe with great wifi")
print([t.head.i for t in doc])
# [0, 1, 2, 3, 4, 5]
```

## Your Environment

* Operating System: Ubuntu 18.04
* Python Version Used: Python 3.6
* spaCy Version Used: spaCy version    2.1.4 
* Environment Information:

**Comment by ines** [comment]
The problem here is that you're using only the `English` language class and no statistical model that can predict the dependencies (i.e. with the dependency parser). So there's no information about how the tokens are attached to each other, so each token is attached to itself.

If you use a statistical models, the heads are available:

```python
import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("find a cafe with great wifi")
print([t.head.i for t in doc])
# [0, 2, 0, 2, 5, 3]
```
