### ISSUE TITLE
append the noun_chunk generator object

### ISSUE THREAD

**Issue by Fourthought** [explosion/spaCy#3856]
## Feature description
Is there a way to append the doc.noun_chunk generator object in the way its possible to append the doc.ents tuple?

I can see the doc.ents can be appended with doc.ents += (new_entity,), but I've been unable to recreate with itertools.chain() for doc.noun_chunks.

The new noun_chunks are based on patterns identified by the pattern matcher. 

## Reproducing example code

```python
doc = nlp('the enemy of America is')

print(*doc.noun_chunks)
>> the enemy
>> America

pattern = [
    [{'POS': 'DET', 'OP' : '?'}, {'LEMMA' : 'enemy'}, {'LEMMA' : 'of'}, {'POS' : 'DET', 'OP' : '?' }, {'POS' : 'PROPN', 'OP' : '+'}]
]

matcher2 = Matcher(nlp.vocab)
matcher2.add('OUTGROUP', None, *pattern)

matches = matcher(doc)

for match_id, start, end in matcher(doc):
    print(test_doc[start:end])
>> the enemy of America
>> enemy of America
```

in this case, would it be possible to add 'the enemy of America' to doc.noun_chunks?

**Comment by ines** [comment]
The `doc.noun_chunks` iterator is read-only, because it's computed by a getter function that uses the tokens' dependencies and part-of-speech tags. See [`lang/en/syntax_iterators.py`](https://github.com/explosion/spaCy/blob/master/spacy/lang/en/syntax_iterators.py) for an example of this.

However, you could use a [custom extension attribute](https://spacy.io/usage/processing-pipelines#custom-components-attributes) to create your own custom noun chunks property on the `Doc`, and then make it return 

```python
from spacy.tokens import Doc

def get_custom_noun_chunks(doc):
    default_noun_chunks = list(doc.noun_chunks)
    # Add your logic with the matcher etc. here
    custom_noun_chunks = get_your_custom_chunks(doc)
    return default_noun_chunks + custom_noun_chunks

Doc.set_extension("custom_noun_chunks", getter=get_custom_noun_chunks)
```

You can then access `doc._.custom_noun_chunks` and it should return a list of the combined spans.

**Comment by Fourthought** [comment]
Great, thank you Ines
