### ISSUE TITLE
spacy.symbols still contains deprecated(?) 'iobj', but no 'dative'

### ISSUE THREAD

**Issue by doctorcolossus** [explosion/spaCy#3858]
Is there any way to test a token's dependency besides comparing with its string value?
I seem to be able to import other dependency symbols, e.g. advmod, dobj, nsubj, pobj, prep.
There seems to be no dative though.

Also, other dependencies seem to evaluate to integers in the lower-400s.
However, tokens parsed as dative have a dependency value of 3965108062993911700. That seems strange, but maybe it's intended. I don't know. I don't want to test against that, since I'm not sure how that number is generated and I can't be sure if it will change in future releases.

Thanks for spaCy and for your attention.

## How to reproduce the behaviour
>>> from spacy.symbols import dative
ImportError: cannot import name 'dative' from 'spacy.symbols' (/usr/lib/python3.7/site-packages/spacy/symbols.cpython-37m-x86_64-linux-gnu.so)

## Your Environment

* Operating System: Arch Linux
* Python Version Used: 3.7.3
* spaCy Version Used: 2.1.3

**Comment by honnibal** [comment]
You should be able to use the `spacy.strings.get_string_id()` function to get the integer representation of any string.

Some strings are noted in the enum lists, which don't support 64-bit values. These are the strings which have low consecutive values like 400. Other strings have values like 3965108062993911700 because this is the 64-bit hash, using the Murmurhash 3 algorith. It's probably ugly to hard-code that constant, but you can expect it to stay stable at least. I would call into the `spacy.strings.get_string_id()` function and define it as a global if you need to.
