### ISSUE TITLE
Issue with matcher.pyx

### ISSUE THREAD

**Issue by VijayrajS** [explosion/spaCy#3863]
## How to reproduce the behaviour
<details>

~~~~
import spacy
from spacy.matcher import Matcher

nlp = spacy.load('en_core_web_sm')
matcher = Matcher(nlp.vocab)

resume_text = "I am XYZ"
nlp_text = nlp(resume_text)

pattern = [{'POS': 'PROPN'}, {'POS': 'PROPN'}]
matcher.add('NAME', None, *pattern)
matches = matcher(nlp_text)
~~~~

</details>

Gives the error
<details>

~~~~
    matcher.add("NAME", *pattern)
  File "matcher.pyx", line 112, in spacy.matcher.matcher.Matcher.add
  File "matcher.pyx", line 568, in spacy.matcher.matcher._preprocess_pattern
  File "matcher.pyx", line 747, in spacy.matcher.matcher._get_operators
AttributeError: 'str' object has no attribute 'items'
~~~~

</details>

## Environment
* **spaCy version:** 2.1.4
* **Platform:** Darwin-18.6.0-x86_64-i386-64bit
* **Python version:** 3.6.8
* **spaCy installation:** /anaconda3/envs/NLTKenv/lib/python3.6/site-packages/spacy

**Comment by ines** [comment]
The problem here is that you're spreading a single pattern in as the `patterns` argument (instead of a list of patterns). Instead, just pass in `pattern`:

```diff
- matcher.add('NAME', None, *pattern)
+ matcher.add('NAME', None, pattern)
```

You should also be able to set `validate=True` when you initialize the `Matcher` to get more feedback on whether the pattern you're passing in is valid.
