### ISSUE TITLE
Custom sentence segmentation not serialized on some cases

### ISSUE THREAD

**Issue by clippered** [explosion/spaCy#3875]
## How to reproduce the behaviour
This is from https://spacy.io/usage/linguistic-features#sbd-custom with minor modifications noted below
```
import spacy 

# NOTE: add a space at the start
text = u" this is a sentence...hello...and another sentence."

nlp = spacy.load("en_core_web_sm")
doc = nlp(text)
print("Before:", [sent.text for sent in doc.sents])

def set_custom_boundaries(doc):
    # NOTE: set token1 to sent_start=True
    doc[1].is_sent_start = True
    for token in doc[:-1]:
        if token.text == "...":
            doc[token.i+1].is_sent_start = True
    return doc

nlp.add_pipe(set_custom_boundaries, before="parser")
doc = nlp(text)
print("After 1:", [sent.text for sent in doc.sents])

# print serialized/deserialized doc
new_doc = spacy.tokens.Doc(nlp.vocab).from_bytes(doc.to_bytes(exclude=['tensor']), exclude=['tensor'])
print("After 2:", [sent.text for sent in new_doc.sents])
```

## Your Environment

* Operating System: macOS Mojave 10.14.5
* Python Version Used: Python 3.7.1
* spaCy Version Used: spaCy 2.1.4

The output was:
```
Before: [' this is a sentence...', 'hello...', 'and another sentence.']
After 1: [' ', 'this is a sentence...', 'hello...', 'and another sentence.']
After 2: [' this is a sentence...', 'hello...', 'and another sentence.']
```
I was expecting that `After 1` and `After 2` are the same.

**Comment by BreakBB** [comment]
The problem lies in [this](https://github.com/explosion/spaCy/blob/c833d9b31487fec9a5edb9c4a7566f8b5de17213/spacy/tokens/doc.pyx#L857) condition. Meaning if the `is_parsed` field of the doc is `True` then the `sent_start` attribute is ignored for serialization.

If you set it explicit to `False` you can get the expected output:

```python
import spacy

# NOTE: add a space at the start
text = u" this is a sentence...hello...and another sentence."

nlp = spacy.load("en_core_web_sm")
doc = nlp(text)
print("Before:", [sent.text for sent in doc.sents])

def set_custom_boundaries(doc):
    # NOTE: set token1 to sent_start=True
    doc[1].is_sent_start = True
    for token in doc[:-1]:
        if token.text == "...":
            doc[token.i+1].is_sent_start = True
    return doc

nlp.add_pipe(set_custom_boundaries, before="parser")
doc = nlp(text)
print("After 1:", [sent.text for sent in doc.sents])

# Set 'is_parsed' to False to serialize the 'sent_start' attributes
doc.is_parsed = False

# print serialized/deserialized doc
new_doc = spacy.tokens.Doc(nlp.vocab).from_bytes(doc.to_bytes(exclude=['tensor']), exclude=['tensor'])
print("After 2:", [sent.text for sent in new_doc.sents])
```

**Comment by clippered** [comment]
Thanks, I'll try this out in a tomorrow and let you know how it goes.

**Comment by clippered** [comment]
@BreakBB It means that the dependency parser needs to be run on `new_doc` right? This is because `HEAD` and `DEP` were not serialized in `doc`.

**Comment by BreakBB** [comment]
It means the exact opposite: The dependency parser must not run for the creation of the first `doc`, because otherwise `HEAD` and `DEP` will be serialized instead of your wanted `SENT_START`.

You can disable the parser pipeline like this:

```python
with nlp.disable_pipes("parser"):
    doc = nlp(text)
    print("After 1:", [sent.text for sent in doc.sents])
```

**Comment by clippered** [comment]
Then do you thnk `HEAD` and `DEP` are missing some information on where the sentences start because when they are serialized and deserialized, then will not have the same information as before.

**Comment by BreakBB** [comment]
O wait. Ye you're totally right. `HEAD` should contain all the information needed, including the `sent_start` attribute.

But I found two inconsistencies:
1. For the space token at the beginning (`doc[0]`) `is_sent_start == True`, but `sent_start == False`. And when reading the `new_doc` from bytes then `new_doc[0]` is fine, but the second token `new_doc[1]` is not recognized as sentence start (`is_sent_start == None` and `sent_start == 0`) anymore. The latter causes your problem.

2. For all the other tokens of `doc` `sent_start` is an integer with either 1 or 0 instead of a boolean.

I don't think #2869 is related to this and the problem seems to lie deep inside the code somewhere (couldn't find a place).

**Comment by clippered** [comment]
Hmm... so `SENT_START` is a bit confusing to be serialized then. Are they integers `-1, 0, 1` or nullable boolean `False, None, True`. if `HEAD` can keep sentence start information, then it might solve it. Thanks for looking into this, let me know how it goes.

**Comment by BreakBB** [comment]
Even though the docs for [token attributes](https://spacy.io/api/token#attributes) say:

> head | Token | The syntactic parent, or “governor”, of this token.

It seems more like it would be a simple reference to `self` (or maybe I am understanding the docs wrong). So yes, `HEAD` should contain all attributes of a token.

> Hmm... so SENT_START is a bit confusing to be serialized then.

Well we should not have to worry about the serialization, since we have the `to_bytes` and `from_bytes` functions. I don't think I can help much more here, so we have to wait for a response from the spaCy team.

**Comment by honnibal** [comment]
@clippered Sorry for the delay getting back to you on this, and thanks @BreakBB for the help.

You've hit kind of an interesting edge-case here, as you're forcing the parser to make a segmentation that our rules would otherwise prevent. 

We have some rules in the parser which mean spaces normally attach within the same sentence, to avoid having sentences which consist entirely of whitespace. However, the rules don't consider an interaction between preset sentence boundaries and the whitespace tokens, which is what you're doing here. The unexpected combination means that when we deserialize the parse and recalculate he sentence start (which is normally predictable given the parse tree), we end up with an inconsistent result.

So, this is basically a bug that I would mark as fairly low priority. Is it important to you that the whitespace gets marked as a distinct sentence?

**Comment by clippered** [comment]
Thanks @honnibal for your response. Keep this low priority for now, because I have a workaround for this. I include the start and end offsets of the sentences during serialization and read this back on deserialization.

**Comment by svlandeg** [comment]
It looks like this has been fixed in spaCy v3:
```
Before: [' this is a sentence...hello...and another sentence.']
After 1: [' ', 'this is a sentence...', 'hello...', 'and another sentence.']
After 2: [' ', 'this is a sentence...', 'hello...', 'and another sentence.']
```
So I'll go ahead and close this :-)
