### ISSUE TITLE
Matcher to validate two tokens

### ISSUE THREAD

**Issue by alteest** [explosion/spaCy#3878]
It seems that this is not a bug, may be feature request.
I have an issue with usage Match to validate 'want' or 'would like' in phrase.
With single token I can just use 'ORTH' : {'IN': ['word1', 'word2']}, but in my case it's impossible because 'would like' is two tokens. I understand it.
Is there a possibility to describe somehow rule to validate my example.

* Operating System: Ubuntu 16.04
* Python Version Used: 3.6.8
* spaCy Version Used: 2.1.3

**Comment by cchderrick** [comment]
I think you will need 2 patterns for this specific task:
```
matcher.add("some_label",[{'ORTH' : 'want'}])  # matching one token
matcher.add("some_label",[{'ORTH' : 'would'},{'ORTH' : 'like'}]) # matching two tokens
```
You might want to consider [PhraseMatcher](https://spacy.io/api/phrasematcher) as well

**Comment by alteest** [comment]
No, may be it was not clear but I want something like {'ORTH': {'IN': ['want', 'would like']}}

**Comment by BreakBB** [comment]
@alteest So you just want a different syntax for a feature that is already supported as @cchderrick already stated, correct?

**Comment by alteest** [comment]
Well may be it will work, but I in his example is require to build two rules and apply it to on matcher, but I want to use one rule (regarding current design of my application). I want only ONE rule with will validate next sentences in one rule:

I want ...
I would like ...

and I want to know is it possible to somehow implement it in one rule like : [{'ORTH': 'I'}, {'ORTH': {'IN': ['want', 'would like']}}]?

**Comment by ines** [comment]
Each dictionary in the match patterns represents **one token**. So `['want', 'would like']` wouldn't work out-of-the-box, because the matcher will never encounter a single token whose text value is `"would like"` (since it'd always be split into two tokens).

In cases where it makes sense, you could consider merging the tokens into one (using `doc.retokenize`) before you match. Just double-check that this doesn't mess up the dependency attachments.

But it might be much easier and more maintainable to just write two matcher rules in that case, similar to the suggestion above.
