### ISSUE TITLE
Displacy.serve() serialising doc.user_data attribute fails if it contains a set as a value

### ISSUE THREAD

**Issue by wutangclancee** [explosion/spaCy#3882]
## How to reproduce the behaviour

```python
import spacy

nlp = spacy.load('en_core_web_sm')
test_doc = nlp('This is a test doc!')

#Set a value in user_data to a set
test_doc.user_data['test_data'] = set()

spacy.displacy.serve(test_doc, style='dep')
```

The serialisation of the user_data attribute fails when attempting to dump a set. I assume this is because the set datatype is not part of standard JSON notation.

Are only simple datatypes allowed in the user_data attribute? 

Thanks, Michael

## Error
```
TypeError: can not serialise 'set' object
```

## Your Environment
* **spaCy version:** 2.1.4
* **Platform:** Darwin-18.6.0-x86_64-i386-64bit
* **Python version:** 3.6.8

**Comment by ines** [comment]
Thanks for the report! In general, the data placed in `doc.user_data` should be JSON-serializable if you want to call `doc.to_bytes` to serialize the `Doc`. Otherwise, you'll see this error.

However, I do think `displacy` should work around this and exclude the `user_data` when it makes a copy of the `Doc` internally, since we do not actually need it here.
