### ISSUE TITLE
EntityRuler returns unexpected entity

### ISSUE THREAD

**Issue by ccoppa** [explosion/spaCy#3887]
## How to reproduce the behaviour
I tried different ways to define the patterns, but none gave me the expected output. I'm not sure how the output ended up combining both defined entities together with an extra token "for".
```
import spacy
from spacy.pipeline import EntityRuler

patterns1 = [ {"label": "ORG", "pattern": "XYZ Company"}, 
{"label": "XYZ_PRODUCT", "pattern": "Fitness Services"}
 ]

patterns2 = [ {"label": "ORG", "pattern": [{"ORTH": "XYZ"},{"ORTH": "Company"}]}, 
{"label": "XYZ_PRODUCT", "pattern": [{"ORTH": "Fitness"},{"ORTH":"Services"}]}
 ]

patterns3 = [ {"label": "ORG", "pattern": [{"lower": "xyz company"}]}, 
{"label": "XYZ_PRODUCT", "pattern": [{"lower": "fitness services"}]}
 ]

patterns4 = [{"label": "ORG", "pattern": [{"lower": "xyz"},{"lower": "company"}]}, 
{"label": "XYZ_PRODUCT", "pattern": [{"lower": "fitness"},{"lower":"services"}]}
 ]

patterns5 = [{"label": "ORG", "pattern": [{"lower": {"IN": ["xyz company"]}}]}, 
{"label": "XYZ_PRODUCT", "pattern": [{"lower":{"IN": ["fitness services"]}}]}
 ]


patterns = [patterns1,patterns2,patterns3,patterns4,patterns5]

for i in range(0,len(patterns)):
  nlp = spacy.load("en_core_web_sm")
  ruler = EntityRuler(nlp, overwrite=True)
  ruler.add_patterns(patterns[i])
  nlp.add_pipe(ruler, after="ner")
  doc = nlp(u"I joined XYZ Company for Fitness Services")
  print([(ent.text, ent.label_) for ent in doc.ents])
```
## Output
```
[('XYZ Company for Fitness Services', 'ORG')]
[('XYZ Company for Fitness Services', 'ORG')]
[('XYZ Company for Fitness Services', 'ORG')]
[('XYZ Company for Fitness Services', 'ORG')]
[('XYZ Company for Fitness Services', 'ORG')]
```
Also tried using ```overwrite=False``` got different output but still not solving the issue completely. Some got the XYZ_PRODUCT CORRECT but all got the ORG entity span wrong. 
Ideally, I'd hope format like pattern5 to work as I want to use `lower` and `IN` for data processing and scalibility.

```
for i in range(0,len(patterns)):
  nlp = spacy.load("en_core_web_sm")
  ruler = EntityRuler(nlp, overwrite=False)
  ruler.add_patterns(patterns[i])
  nlp.add_pipe(ruler, before="ner")
  doc = nlp(u"I joined XYZ Company for Fitness Services")
  print([(ent.text, ent.label_) for ent in doc.ents])
```

## Output
```
[('XYZ Company for', 'ORG'), ('Fitness Services', 'XYZ_PRODUCT')]
[('XYZ Company for', 'ORG'), ('Fitness Services', 'XYZ_PRODUCT')]
[('XYZ Company for Fitness Services', 'ORG')]
[('XYZ Company for', 'ORG'), ('Fitness Services', 'XYZ_PRODUCT')]
[('XYZ Company for Fitness Services', 'ORG')]
```

## Your Environment

* Operating System: macOS Mojave 10.14.5
* Python Version Used: Python 3.7.1
* spaCy Version Used: spaCy 2.1.4

**Comment by ines** [comment]
I think one underlying problem in many of your patterns is that many of them don't actually match. If you're using token-based patterns, keep in mind that each dictionary represents **one token**. So `"IN": ["xyz company"]` will never be true, because there will never be one token whose lowercase form matches `"xyz company"` – only two tokens, `"xyz"` and `"company"`. So you could either add a pre-processing step that merges those names into single tokens, or write your patterns in a way that each dictionary represents one token.

Another thing you're seeing are side-effects of the model, which is also recognizing entities in your text. If you just run the following, you'll see that the model already labels `'XYZ Company for Fitness Services'` as an `ORG`:

```python
nlp = spacy.load("en_core_web_sm")
doc = nlp(u"I joined XYZ Company for Fitness Services")
print([(ent.text, ent.label_) for ent in doc.ents])
```

If you test your entity ruler patterns with a blank model without a statistical named entity recognizer, you'll also see the problems and the patterns that don't match:

```python
for i in range(0, len(patterns)):
  nlp = spacy.blank("en")
  ruler = EntityRuler(nlp)
  ruler.add_patterns(patterns[i])
  nlp.add_pipe(ruler)
  doc = nlp(u"I joined XYZ Company for Fitness Services")
  print([(ent.text, ent.label_) for ent in doc.ents])
```

```
[('XYZ Company', 'ORG'), ('Fitness Services', 'XYZ_PRODUCT')]
[('XYZ Company', 'ORG'), ('Fitness Services', 'XYZ_PRODUCT')]
[]
[('XYZ Company', 'ORG'), ('Fitness Services', 'XYZ_PRODUCT')]
[]
```

Finally, one problem that does seem to occur here: It seems like `overwrite=True` doesn't work as expected if the span it's overwriting has the same entity labels 🤔 Instead of removing the "XYZ Company for Fitness Services" (`ORG`) and replacing it with "XYZ Company" (`ORG`) and "Fitness Services" (`XYZ_PRODUCT`), it produces "XYZ Company" (`ORG`). Could be an off-by-one error, or something related to the token-based tags. I'll write a test for this and probably open a separate issue.
