### ISSUE TITLE
Span.sent is None for single-token Docs

### ISSUE THREAD

**Issue by juliamakogon** [explosion/spaCy#3907]
## How to reproduce the behaviour
The code below works with longer text like "John Doe goes," but fails when the entity and the sentence coincide.

```
    nlp_en = spacy.blank(language)
    sentencizer = nlp_en.create_pipe("sentencizer")
    nlp_en.add_pipe(sentencizer)

    doc = nlp_en("John Doe")
    doc_ents = []
    taghash = nlp_en.vocab.strings.add('PERSON')
    doc_ents.append(Span(doc, 0, 2, label=taghash))
    merge_ents = nlp_en.create_pipe("merge_entities")
    doc.ents = doc_ents
    for ent in doc.ents:
        print(ent, '*', ent.sent) # John Doe * John Doe
        assert ent is not None
        assert ent.sent is not None
    doc = merge_ents(doc)
    for ent in doc.ents:
        print(ent, '*', ent.sent) # John Doe * None
        assert ent is not None
        assert ent.sent is not None
```

## Your Environment

* **spaCy version:** 2.1.4
* **Platform:** Linux-4.15.0-54-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.6.7
* **Models:** en, en_core_web_md, xx

**Comment by ines** [comment]
I think the underlying issue here is that you end up with a single-word `Doc`. With the current implementation, the `Token.is_sent_start` property defaults to `True` if it's the very first token in a `Doc`. But if there's only one token, spaCy is unable to tell if sentence boundaries have been set or not.

We do want to change this in the future, but for now, you kind of have to accept that if your `Doc` only contains one token, sentence boundaries will appear as unset.

**Comment by juliamakogon** [comment]
Hello, Ines, thanks for your reply. I hope sometime in the future the problem will be solved. It's a typical situation to have one-word sentences for some parts of documents in our dataset.  For now, I will keep in mind this issue.

**Comment by ines** [comment]
Merging this with #3934!
