### ISSUE TITLE
different results  for NER of spcay when using in DJANGO and terminal 

### ISSUE THREAD

**Issue by sandeep-adireddi** [explosion/spaCy#3913]
i am using spacy for date recognition in my project. when i am using spacy ner in terminal it gives me a different results from when i use it in my project python file i attached images so u can understand by problem better

## Your Environment

* Operating System:  ubuntu 18.04
* Python Version Used: 3.6
* spaCy Version Used: 2.1.4
* Environment Information: django
![results from django python file](https://user-images.githubusercontent.com/16081707/60756142-a0901580-a017-11e9-9c13-c5bb8001a9ef.JPG)
![results from terminal](https://user-images.githubusercontent.com/16081707/60756143-a0901580-a017-11e9-9cf4-6eecfc89f212.JPG)

**Comment by SandeepNaidu** [comment]
It's got to do with the environment you are running it in. I think when you invoke it in python interpreter it might be using one python env where the language model link 'en' is pointing to something different than when you run it in django. You need to make sure both the runtimes are using the same python env. Better print the python version and path in both instances and check.

**Comment by sandeep-adireddi** [comment]
i am using same python version python 3.6.7 for both django and and in terminal and path is also same

**Comment by BreakBB** [comment]
I agree with @SandeepNaidu that this issue is related to the environment you're using.

How did you include spaCy in django? Are you using the same code lines as in your terminal test? I see for your terminal test you're explicit using the "en_core_web_lg" model. You have to make sure that the same models get loaded both times.

**Comment by sandeep-adireddi** [comment]
i am using the same code but in my project it runs in a forloop processing tweets in list one by one. i copy pasted the same code from my django application to verify our comment. but both showed different results

**Comment by SandeepNaidu** [comment]
Can you give absolute path to the language model and then try again in both instances?
From documentation 

> import spacy
nlp = spacy.load("en_core_web_sm")           # load model package "en_core_web_sm"
nlp = spacy.load("/path/to/en_core_web_sm")  # load package from a directory
nlp = spacy.load("en")                       # load model with shortcut link "en"
doc = nlp(u"This is a sentence.")

Also try spacy.info()

> Tip: Preview model info
You can use the info command or spacy.info() method to print a model’s meta data before loading it. Each Language object with a loaded model also exposes the model’s meta data as the attribute meta. For example, nlp.meta['version'] will return the model’s version.

Reference: https://spacy.io/usage/models

**Comment by sandeep-adireddi** [comment]
here is the nlp.meta and spacy.info details
![info_from_django](https://user-images.githubusercontent.com/16081707/61027915-fd534d80-a3d4-11e9-9815-2529f0d9e083.JPG)
![info_from_terminal](https://user-images.githubusercontent.com/16081707/61027916-fdebe400-a3d4-11e9-8a85-69fd2d9f6f0e.JPG)

**Comment by svlandeg** [comment]
Hi @sandeep-adireddi, and sorry for the very late follow-up.

When I look at your original two screenshots, what strikes me is that the offsets start to be slightly different halfway through your document: `Cordillera` is found at position `191-201` in one, and at position `189-199`. So if your environment & model are exactly the same (as they seem to be from your last post), there are probably slight difference because of underlying differing text encodings or something.
