### ISSUE TITLE
Missing remove method in PhraseMatcher

### ISSUE THREAD

**Issue by bayethiernodiop** [explosion/spaCy#3922]
## Feature description
In Matcher it is possible to remove an added pattern by calling the remove method but that's not possible with the PhraseMatcher. Any tips

**Comment by honnibal** [comment]
I agree this would make sense.

A note for someone implementing this: We'd just want to remove the entry from the final-check dictionary. We wouldn't want to try to remove the "possible B", "possible I", etc entries, as otherwise we'd have to iterate all of the phrases to ensure no other phrases need to mark those tokens.

**Comment by yash1994** [comment]
I've implemented remove method for PhraseMatcher using a dictionary variable to maintain ent_ids of removed pattern and used this dictionary to remove matched patterns in final-check (accept_match method) as you've mentioned above.
`if ent_id == 0 or ent_id in self._removed:
            return None
        else:
            return ent_id`
