### ISSUE TITLE
Trying to load a model in the same script that downloaded it raises OSError

### ISSUE THREAD

**Issue by louismartin** [explosion/spaCy#3923]
Hi,

When downloading a model using `spacy.cli.download` and then directly using `spacy.load` (in the same interpreter), it raises an OSError because `spacy.utils.is_package` returns False: https://github.com/explosion/spaCy/blob/a7fd42d937d405088803da3fb3b301cc81cea719/spacy/util.py#L133-L134 
We currently need to start a new interpreter for the list of packages to be updated with the newly installed model.
Is this the expected behaviour?
Is there a way to download a model at run time and using it directly? (I'd like my package to download the model lazily only when needed and without having to execute the script twice).

Thanks,

## How to reproduce the behaviour
```bash
$ pip uninstall -y en_core_web_sm; python -c "import spacy; spacy.cli.download('en_core_web_sm'); spacy.load('en_core_web_sm')"

OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

## Your Environment

* Operating System: Ubuntu 18.04
* Python Version Used: 3.7.3
* spaCy Version Used: 2.1.3
* Environment Information:

**Comment by ines** [comment]
The underlying cause here is the default behaviour of setuptools: if you're checking `pkg_resources`, an installed package won't show up if it was installed in the same session. This is the case for all Python packages, so it also occurs if you install the models. So in order to check if a package is installed, you'd have to reload.

One workaround for this would be to get the path of the installed package and create a symlink after installation, which can be loaded without problems. For more details and code, see my comment here: https://github.com/explosion/spaCy/issues/3435#issuecomment-474580269

In my comment, I also explain why we chose not to make this the default behaviour anymore... but I wonder if we could potentially improve the `is_package` check and maybe add something like a `try`/`except` around `importlib.import_module` (or spaCy's `util.get_package_path`) as a last resort before returning `False`. It's not very elegant, but it should catch cases like this.

**Comment by louismartin** [comment]
Thanks for the quick answer, I think I'll link the package manually for now as a workaround.
Thanks a lot
