### ISSUE TITLE
install fails PEP 517 , thinc --- need fix quickly for project deadline --- switching back to NLTK for now

### ISSUE THREAD

**Issue by SumeetSandhu** [explosion/spaCy#3955]
I have a 2015 MacBook Pro running Mojave 10.14.5
Python 2.7.16
pip 19.1.1
gcc version 5.1.0

I tried upgrading to the latest spaCy with different options eg --no-use-pep517 , --no-binary etc. They didn't work and removed old spaCy - installing with no options didn't work.
Error message excerpts look like:

Building wheels for collected packages: spacy
  Building wheel for spacy (PEP 517) ... error
<-----long list of errors------------------------------------------>
  gcc: error: unrecognized command line option ‘-stdlib=libc++’
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for spacy
  Running setup.py clean for spacy
Failed to build spacy
Building wheels for collected packages: thinc
  Building wheel for thinc (setup.py) ... error
<-----another long list of errors------------------------------------------>
  gcc: error: unrecognized command line option ‘-stdlib=libc++’
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for thinc
  Running setup.py clean for thinc
Failed to build thinc
ERROR: Could not build wheels for spacy which use PEP 517 and cannot be installed directly

**Comment by ines** [comment]
Hi! Adding things like "quick fix needed" to titles really isn't helpful. We do our best to answer issues, but we can't offer to fix people's individual Python problems just to meet their project deadlines. Your issue was posted only 10 days ago (!) and was very hard to understand because it's not formatted well and also didn't follow our issue template. This makes it more difficult to answer.

If you [google the underlying error message](https://www.google.com/search?q=gcc%3A+error%3A+unrecognized+command+line+option+%E2%80%98-stdlib%3Dlibc%2B%2B%E2%80%99), you'll find that this is not a problem with spaCy itself, but with your compiler. We have our [own complex setup](https://github.com/explosion/wheelwright) to provide pre-compiled Python wheels for most operating systems and platforms. Unfortunately, we aren't able to provide wheels for ([almost end-of-life](https://pythonclock.org/)) Python 2.7 on Mac anymore. So you have to compile it yourself locally. This can sometimes lead to problems, which we cannot always prevent.

If NLTK has all you need and you're on a tight deadline and don't have time to look into your Python setup, it seems like a much better option anyways. So I'm glad you were able to keep working 🙂
