### ISSUE TITLE
Weird error when using regex in EntityRuler

### ISSUE THREAD

**Issue by talbaumel** [explosion/spaCy#3977]
## How to reproduce the behaviour
```
import spacy 
from spacy.pipeline import EntityRuler


nlp = spacy.load("en_core_web_sm")
ruler = EntityRuler(nlp)
patterns = [{"label": "EMAIL", 
             "pattern":[{"REGEX": r"([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)"}]},
            {"label": "PHONE", 
             "pattern":[{"REGEX": r"(\d{3}[-\.\s]??\d{3}[-\.\s]??\d*|\(\d{3}\)\s*\d{3}[-\.\s]??\d*|\d{3}[-\.\s]??\d*)"}]}]
ruler.add_patterns(patterns)
nlp.add_pipe(ruler)

doc = nlp(u"mymail@mail.com abcd abcd 111111111")
print([(ent.text, ent.label_) for ent in doc.ents])

```
Returns:
`[('mymail@mail.com', 'PHONE'), ('abcd', 'PHONE'), ('abcd', 'PHONE'), ('111111111', 'EMAIL')]`

The regexs work fine when using re.findall
## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.7.1
* spaCy Version Used: 2.1.3
* Environment Information:

**Comment by ines** [comment]
I think the problem here is that you're missing the **top-level token attribute** you're trying to match your regex on – for example: `{"TEXT": {"REGEX": "..."}}` (also [see here](https://spacy.io/usage/rule-based-matching#regex)). In your example, the `REGEX` key is ignored because it's not a token attribute, so the pattern is interpreted as "any token".

If I change that, the output looks as expected:

```
[('mymail@mail.com', 'EMAIL'), ('111111111', 'DATE')]
```

If you're ever unsure, you can also add your patterns to the `Matcher` and set `validate=True`. This should flag issues like this.

Btw, spaCy already has a built-in `LIKE_EMAIL` token attribute – so if you don't need a special regex here, you could also change the email pattern to `[{"LIKE_EMAIL": True}]`.

**Comment by talbaumel** [comment]
Thanks! Is it possible to change the priority of the EntityRuler? so "111111111" will be classified as PHONE instead of DATE?
