### ISSUE TITLE
Use the same pipeline multiple times

### ISSUE THREAD

**Issue by RonRademaker** [explosion/spaCy#3985]
Hi,

Is it possible to use the same pipeline multiple times, I got a few different text classification tasks so I'd like to train different textcat pipelines for each task and merge them into one model.

**Comment by ines** [comment]
Sorry for only getting to this now! If you want to add multiple instances of the same component to the pipeline, there are two things to consider:

1. The naming. When calling `nlp.add_pipe`, you should assign a distinct name to the second component, and also add the new name to the [`Language.factories`](https://spacy.io/usage/processing-pipelines#custom-components-factories) so spaCy knows how to initialize the component. 
2. How the annotations are set. For named entities, this is a bit trickier – see #2920 for more details. But from looking at the implementation of spaCy's text classifier, it seems like the component never actually *overwrites* the `doc.cats` dict and just adds to it. So having two components write to the `doc.cats` should be no problem (assuming they predict different labels – otherwise, the second component will overwrite the first component's scores).

So an approach like this should work:

```python
Language.factories["textcat2"] = Language.factories["textcat"]

textcat1 = nlp.create_pipe("textcat")
textcat2 = nlp.create_pipe("textcat2")
nlp.add_pipe(textcat1)
nlp.add_pipe(textcat2)
```
