### ISSUE TITLE
Make Doc.to_json function include Span & Token custom attribute

### ISSUE THREAD

**Issue by Mardelor** [explosion/spaCy#3987]
## Feature description
`Doc.to_json` function now takes only `Doc` custom attribute, and no `Span` or `Token` custom attribute. It could be more convenient and generic if there was `Span.to_json` and `Token.to_json` methods to render all attribute in `Doc.to_json`, including custom attribute.

Is it possible ?

**Comment by ines** [comment]
Including custom extension attributes on the tokens in `Doc.to_json` makes sense, yes – if `underscore=True` and of course given the values are JSON-serializable. 

Including span attributes in there is a bit trickier – you obviously wouldn't want to generate a span for every possible combination of tokens. There's also no way for spaCy to know what the span attributes "mean" and when you intend to use them. For instance, do you typically access them for named entity spans, sentence spans or just... other random spans in general? Maybe a generic `Span.to_json` would make more sense here 🤔

**Comment by Mardelor** [comment]
Hello @ines,
Thank you for the quick answer. What do you mean by a generic `Span.to_json` ? Would it be parameters pointing to span's attributes ?

**Comment by polm** [comment]
A lot of things have changed since this issue came up, so I'm going to go ahead and close it. We didn't add token or span extensions to the `to_json` output, but in spaCy v3 we've transitioned from the JSON format to the [binary format][] as the primary format for training data. In general it should be easier to use and less finicky than the JSON. 

[binary format]: https://spacy.io/api/data-formats#binary-training
