### ISSUE TITLE
Vocab.__contains__ not working as expected

### ISSUE THREAD

**Issue by BreakBB** [explosion/spaCy#3988]
## How to reproduce the behaviour
While testing for #3986 I encountered some unexpected behaviour. It seems that [Vocab.__contains__](https://spacy.io/api/vocab#contains) might be broken or maybe the docs are outdated?

```python
import spacy
nlp = spacy.load("en_core_web_sm")

if u"September" in nlp.vocab.strings:
    print("September in StringStore")  # Working as expected

dog = nlp.vocab.strings[u"dog"]
assert dog not in nlp.vocab  # Working as expected

september = nlp.vocab.strings[u"September"]
assert september in nlp.vocab  # AssertionError
```

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.7.3
* spaCy Version Used: 2.1.6

**Comment by svlandeg** [comment]
I think this is caused by the fact that there are no vectors initialized in the `en_core_web_sm` model. If you try the same with `en_core_web_md` (and remove the "dog not in ..." bit) you'll see that it does work.

I think this may be caused by the call to `self._by_orth` in https://github.com/explosion/spaCy/blob/master/spacy/vocab.pyx#L199 ... but then I'm still not sure whether it's a feature or a bug :-)

**Comment by honnibal** [comment]
I'm not 100% sure I follow the example.

It's possible for a word to be in the `StringStore` but not the `Vocab`. This can happen in cases like `September` for the small model, if we use `September` in some special way -- for instance if we have it in a list for one of the token attributes or something.

Does that answer the question, or is there something else that's wrong here?

**Comment by BreakBB** [comment]
The example above is just madeup.

I had a look at the example of [Vocab.__contains__](https://spacy.io/api/vocab#contains) and therefore thought whenever a word is in the `StringStore` is will be part of the `Vocab` as well and the other way around. Since you stated this is not always true there is no problem here. Thanks for the clarification.
