### ISSUE TITLE
Include API documentation in package

### ISSUE THREAD

**Issue by donpellegrino** [explosion/spaCy#4018]
For the use case of Python development in an air gapped environment, it would be useful if the API documentation was accessible via the built-in Python help() system. For example, running help(spacy.tokens.Span) in the interpreter gives the following:

```
Help on class Span in module spacy.tokens.span:

class Span(builtins.object)
 |  A slice from a Doc object.
 |  
 |  DOCS: https://spacy.io/api/span
 |  
 |  Methods defined here:
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
...
```

The online API documentation at https://spacy.io/api/span contains additional information and a number of useful examples. However, if connectivity to https://spacy.io is not available then the information cannot be used. Placing the information in the class documentation would make it easier to include with the packaged module. It would also make access to it more consistent with other Python packages that use the help() system.

Alternatively, the package might deploy the HTML API documentation within the /share directory for virtual environments. This would be less ideal since it would be separate from the help() system, however it would help ensure it is included with local installations of the package.

## Which page or section is this issue related to?
https://spacy.io/api/span

## Test System
spacy PyPI package Version: 2.1.6 with Python 3.6.8.

**Comment by ines** [comment]
Hi! We tried to find the best compromise for including all relevant information like the API signature in the docstrings, while also not making them add too much bloat to the codebase. That's why the docstrings for individual methods etc. contain the description, signature (arguments, types, return values) and maybe a simple example, an then point to the website for more in-depth documentation, usage examples and further links.

So if you want to check what a method does, what arguments it takes and what it returns, the docstrings / `help()` system has you covered (which it definitely should IMO and is also probably the general expectation). If you look at the [`Span` class](https://github.com/explosion/spaCy/blob/master/spacy/tokens/span.pyx#L35), the main difference is really mostly the usage examples and reference links. We do think that's an okay compromise.

We also provide the website [in this repo](https://github.com/explosion/spaCy/tree/master/website), so in the meantime you can always clone it and run it locally if you need to.
