### ISSUE TITLE
Using Matcher() in conjunction with regex returns strings longer than what the regex is supposed to match

### ISSUE THREAD

**Issue by mrxiaohe** [explosion/spaCy#4044]
## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.7
* spaCy Version Used: 2.1.4
* Environment Information:

I am trying to capture some number sequences. Below is the code I use:

```
from spacy.lang.en import English
from spacy.matcher import Matcher
from spacy.tokens import Span

nlp = English()
matcher = Matcher(nlp.vocab)

def add_event_ent(matcher, doc, i, matches):
    match_id, start, end = matches[i]
    entity = Span(doc, start, end, label="EVENT")
    ents = [ent for ent in doc.ents if ent.label_ != 'NumberSequence']
    doc.ents += (entity,)
    print(entity.text)

#pattern = [{"ORTH": "Google"}, {"ORTH": "I"}, {"ORTH": "/"}, {"ORTH": "O"}]
pattern = [{'ORTH': {"REGEX": r"\d{3}"}},
           {"ORTH": "-"}, 
           {'ORTH': {"REGEX": r"\d{4}"}}, 
           {"ORTH": "-"}, 
           {'ORTH': {"REGEX": r"\d{4}"}}]

matcher.add("NumberSequence", add_event_ent, pattern)
doc = nlp(u"123-3433-2234; -123-3433-2234; 123-3433-2234-")
matches = matcher(doc)
```

The actual regex pattern I use is more complicated than what's shown above, but i am using a simplified regex for the sake of simplicity. The regex above returns the following matches., Crucially, I only want the first one to be matched. I wonder if there is a way to achieve that. Thanks. 

**123-3433-2234
-123-3433-2234
123-3433-2234-**

**Comment by BreakBB** [comment]
You want to have a look at [Matching on other token attributes](https://spacy.io/usage/rule-based-matching#phrasematcher-attrs) using the [PhraseMatcher](https://spacy.io/usage/rule-based-matching#phrasematcher).

You can use `attr="SHAPE"` to setup the matcher looking for shapes instead of explicit tokens.

With this your code will change to something like this:

```python
from spacy.lang.en import English
from spacy.matcher import PhraseMatcher
from spacy.tokens.span import Span

nlp = English()
matcher = PhraseMatcher(nlp.vocab, attr="SHAPE")


def add_event_ent(matcher, doc, i, matches):
    match_id, start, end = matches[i]
    entity = Span(doc, start, end, label="EVENT")
    ents = [ent for ent in doc.ents if ent.label_ != 'NumberSequence']
    doc.ents += (entity,)
    print(entity.text)


matcher.add("NumberSequence", add_event_ent, nlp(u"123-3433-2234"))
doc = nlp(u"123-3433-2234; -123-3433-2234; 123-3433-2234-; 543-2222-1234; 2222-111-1111; 123-4567-8910-; 999-1111-7777")
matches = matcher(doc)


# 123-3433-2234
# 543-2222-1234
# 999-1111-7777
```

**Comment by ines** [comment]
Yeah, I do think in your case, you're slightly overcomplicating things here because you now have to pay attention to the tokenization of the number sequence *and* the regular expressions. I think it'd be much easier if you either tried to express your logic with token attributes like `SHAPE` or `IS_DIGIT`, or move to a regex-only approach where you match your regular expressions the `doc.text`, get the start and end offsets of the match and then call `doc.char_span` to create the entity spans from the character offsets.
