### ISSUE TITLE
Using model en-1.1.0 in Spacy 2

### ISSUE THREAD

**Issue by yuvalkry-si** [explosion/spaCy#4053]
Hello,

 I am migrating to Python 3 and would like to use the latest spacy with model en-1.1.0 .

 As explained in https://pypi.org/project/spacy/ ("Support for older versions")
 I unpacked en-1.1.0.tar.gz into spacy/data . I then used

  spacy.blank("en").from_disk('.../lib/python3.7/site-packages/spacy/data/en-1.1.0')

 (This is a conda environment)

 and got error messages - that "__init.py__" was missing.

 I this possible at all to use this model?
 If not, which of the new models supercedes it?

  Thanks,
           Yuval

  spacy validate
## Info about spaCy

* **spaCy version:** 2.1.6
* **Platform:** Linux-3.10.0-327.3.1.el7.x86_64-x86_64-with-centos-7.2.1511-Core
* **Python version:** 3.7.3
* **Models:** en-1.1.0

(

**Comment by ines** [comment]
Sorry, if this was confusing – the "support for older versions" is referring to **older versions of spaCy** and **the old models**.

The linear models for v1.x are not compatible with spaCy v2.x, which now uses neural network models. In general, model compatibility is very strict because pretty much every update to the architecture requires training new weights.

But of course you can still *use* the old models if you install a compatible version of spaCy v1.x.
