### ISSUE TITLE
Invalid syntax in "/spacy/lang/ko/__init__.py" when calling spacy.blank("ko") for Korean

### ISSUE THREAD

**Issue by veer-bains** [explosion/spaCy#4068]
## How to reproduce the behaviour
calling
`spacy.blank("ko")`
produces the following traceback:
`File "/usr/lib64/python2.7/site-packages/spacy/__init__.py", line 31, in blank
    LangClass = util.get_lang_class(name)
  File "/usr/lib64/python2.7/site-packages/spacy/util.py", line 70, in get_lang_class
    module = importlib.import_module(".lang.%s" % lang, "spacy")
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
File "/usr/lib64/python2.7/site-packages/spacy/lang/ko/__init__.py", line 28

    surface: str

           ^

SyntaxError: invalid syntax`

The same script has worked fine for me with other languages, and the same format of data(english, german, chinese, spanish, and a few others), so perhaps this may not be an error on my side.
## Your Environment

* Operating System: CentOS ("Linux-3.10.0-957.21.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core")
* Python Version Used: 2.7
* spaCy Version Used: 2.1.6
* Environment Information: NIL (running script directly from terminal)

**Comment by ines** [comment]
Thanks for the report – looks like the problem here are the type annotations on the named tuple. There is a condition for Python 2.7 and 3.5, but I guess 2.7 just sees this as a syntax error and fails regardless 😞

Are you able to upgrade to Python 3? If so, that'd be the easiest workaround for now.

Relevant source is here btw: https://github.com/explosion/spaCy/blob/master/spacy/lang/ko/__init__.py

It might make sense to rewrite the code so it doesn't use a named tuple, if possible. That means we could remove all the Python version handling and compatibility hacks here. (We will drop 2.7 and 3.5 eventually, but for now, we do have to support both.)

**Comment by veer-bains** [comment]
A lot of my team's code is dependent on Python 2.7 actually, because converting to Python 3 would actually generate pretty much the same kind of errors we're seeing here haha. 
I guess if we must though, then we must. I'll pass the information along to my team. Thanks for the help!

**Comment by ines** [comment]
@veer-bains Yeah, I totally understand that! The other alternative would be to build spaCy from source and remove the non-2.7 code in that file. (Or maybe someone on your team even has some time to fix it and submit a PR 🙂 This way, we can definitely make sure to ship the fix in the next release.)

**Comment by veer-bains** [comment]
@ines Will do my best!
