### ISSUE TITLE
Improve handling of unsupported Matcher attributes

### ISSUE THREAD

**Issue by adrianeboyd** [explosion/spaCy#4070]
## Feature description

I decided to separate this from #4069 (see also #4063 ) since it's not quite the same issue.

With Matcher, it's very confusing that "bad" parts of patterns (e.g., with attributes that aren't supported) are silently discarded and end up matching every token rather than no token.

`{'ASDF': True}` shouldn't be equivalent to `{}`.

How slow is validation? Would it make sense to make `validate=True` the default? Are there simpler checks that could be added for when attributes are discarded that don't require full validation so that you could provide warnings or errors in these cases?

I think that less confusing default behavior would be:

* `{'ASDF': True}` matches nothing
* there are always warnings or errors when it is known that patterns will match nothing due to this kind of problem

**Comment by ines** [comment]
Yes, I agree! 👍

> How slow is validation? Would it make sense to make validate=True the default? Are there simpler checks that could be added for when attributes are discarded that don't require full validation so that you could provide warnings or errors in these cases?

Yes, we should probably just consider implementing simpler checks for just the key names and whether they map to a valid attribute or not. 

The current validation uses `jsonschema`, which we've made an optional dependency (we didn't want it to drag in too many other dependencies down the tree). JSON schema validation is nice because it lets you write pretty complex constraints and gives you helpful and detailed error messages. It's also cross-Python compatible. (Once we drop 2.7 and 3.5, we could probably implement something similar using native Python type hints and make that enabled by default.)
