### ISSUE TITLE
Missing sentencizer when loading custom word vectors 

### ISSUE THREAD

**Issue by ilyaivensky** [explosion/spaCy#4073]
I am trying to load `nlp` with fasttext vectors. I have initialized Spacy as it is suggested on https://spacy.io/usage/vectors-similarity and loaded `nlp` with the same path which I provided to  `spacy init-model`. I successfully loaded vectors, but I was not able to iterate sentences since sentence boundaries were not set. The same code with Spacy native model works fine. 
Is there missing information in instructions on how to load custom vectors or an issue with the code?

## Your Environment

* Operating System: osx 10.13.6
* Python Version Used: 3.6.8
* spaCy Version Used: 2.1.6
* Environment Information:

**Comment by ines** [comment]
The `sentencizer` is an optional component for rule-based sentence segmentation. If you're creating a new model directory using `init-model`, it's not added by default (because maybe you want to add a dependency parser later on that sets sentence boundaries, or use some other approach). So if you want to use it, you'll have to add it yourself:

```python
nlp = spacy.load("/path/to/model")
sentencizer = nlp.create_pipe("sentencizer")
nlp.add_pipe(sentencizer)
nlp.to_disk("/path/to/new_model")
```
