### ISSUE TITLE
Quality of models in lower case

### ISSUE THREAD

**Issue by BramVanroy** [explosion/spaCy#4086]
I was doing some tests and found that the quality of spaCy's output drastically decreases when the input is not cased. Especially for named entity recognition that is true. For instance, when you try the sentence:

> I saw Obama and Trump shaking hands.

Cased, there aren't issues (even though Trump is marked NORP). But lower-cased, the model doesn't recognize any named entities. [See here](https://explosion.ai/demos/displacy-ent?text=i%20saw%20obama%20and%20trump%20shaking%20hands.&model=en_core_web_sm&ents=person%2Corg%2Cgpe%2Cloc%2Cproduct%2Cnorp%2Cdate%2Cper%2Cmisc). 

This begs the question: is spaCy only trained on cased data? If so, it might be useful to make this more explicit in the documentation.

**Comment by ines** [comment]
We do list the sources that the models were trained on in the [models directory](https://spacy.io/models) so you can always check the corpora that were used. I don't know the exact distribution, but it makes sense that most corpora mainly consist of properly cased text, since they're news and web text. We don't do any significant preprocessing or data augmentation, otherwise we'd obviously mention that in the model details.

For many use cases using a model that was trained on properly cased text is useful, because especially in English, it gives the model a lot of clues that you can benefit from. If you do want models that are less sensitive to casing, you can always update them with more examples. Creating that data is pretty straightforward if you have labelled examples: just lowercase them and mix them in with the rest of the data.

**Comment by BramVanroy** [comment]
Okay, thanks for the reply. I was thinking about it in terms of BERT models where they have specific pretrained uncased models, which I think is nice. Of course casing in itself provides good markers (i.e. features) to distinguish, but it is not robust at all. For instance, parsing social media posts and what not will perform quite poorly, then. If I ever have the time, I might retrain the models on lower-cased data.
