### ISSUE TITLE
How is the overall F Score of an NER Model calculated?

### ISSUE THREAD

**Issue by iCHAIT** [explosion/spaCy#4094]
I trained a custom NER model with 6 Entities and later tested it on an unseen sample.

This is the code I am using to evaluate my model on some unseen examples - 

```python
def evaluate(ner_model, examples):

    scorer = Scorer()
    for input_, annot in examples:
        doc_gold_text = ner_model.make_doc(input_)
        gold = GoldParse(doc_gold_text, entities=annot.get('entities'))
        pred_value = ner_model(input_)
        scorer.score(pred_value, gold)
    return scorer.scores
```

And here is the result I get - 

```json
{
    "uas": 0.0, "las": 0.0,
    "ents_p": 90.66397423978736,
    "ents_r": 90.26112736858471,
    "ents_f": 90.46210231583312,
    "ents_per_type": {
                        "ENTITY1": {
                                        "p": 90.15041861869855,
                                        "r": 88.68202816927871,
                                        "f": 89.4101949283755
                                   },
                        "ENTITY2":    {
                                        "p": 82.64149214221386,
                                        "r": 85.28465990316725,
                                        "f": 83.94227421270608
                                   },
                        "ENTITY3": {
                                        "p": 98.7231590403657,
                                        "r": 98.44665796656699,
                                        "f": 98.5847146278393
                                    }, 
                        "ENTITY4": {
                                        "p": 89.59285008653282,
                                        "r": 88.74727538604445,
                                        "f": 89.16805814934497
                                    }, 
                        "ENTITY5": {
                                        "p": 72.83978334689753,
                                        "r": 75.61103504529963,
                                        "f": 74.199542595769
                                    }, 
                        "ENTITY6":{
                                        "p": 88.18408901672848,
                                        "r": 88.07075899606895,
                                        "f": 88.12738757139074}
                                    },
    "tags_acc": 0.0,
    "token_acc": 100.0
}
```
I want to understand how is the overall F Score of the model calculated? I thought that the overall F score may be the average of all individual entity F Score, but that is not the case. See screenshot below - 

<img width="978" alt="Screenshot 2019-08-07 at 10 37 44 AM" src="https://user-images.githubusercontent.com/8472314/62590721-ddde1080-b8ff-11e9-83cc-5b1fcf8f7ed9.png">

Can someone help me better understand how is the overall F Score getting calculated?

## Info about spaCy

* **spaCy version:** 2.1.6
* **Platform:** Darwin-18.5.0-x86_64-i386-64bit
* **Python version:** 3.7.3
* **Models:** en

**Comment by adrianeboyd** [comment]
The overall f-score is calculated by looking at the sets of entities found in the gold annotation and in the predicted document, where each entity is treated as a tuple of `(ent_type, start, end)`. For a predicted entity to be counted as correct it has to be a perfect match with a tuple from the gold annotation. There are no partial matches or weighting.

You can count the true positives (entity tuples in both sets), false positives (entity tuples only in the predicted document), false negatives (entity tuples only in the gold annotation) and calculate the precision, recall, and f-score from those values.

It basically looks like this underneath:

```
gold = set([('A', 1, 2), ('B', 5, 7), ('C', 10, 14)])
pred = set([('B', 1, 2), ('B', 5, 7), ('C', 11, 14), ('D', 16, 17)])
```

In this example, there's 1 true positive, 3 false positives, and 2 false negatives.

For the per-type score for `'B'` it would look like this:

```
gold = set([('B', 5, 7)])
pred = set([('B', 1, 2), ('B', 5, 7)])
```

Once you understand that entities are represented as this kind of tuple underneath, the rest is pretty straightforward. You can see how the TP / FP / FN are counted from these sets in https://github.com/explosion/spaCy/blob/master/spacy/scorer.py#L17:

```
    def score_set(self, cand, gold):
        self.tp += len(cand.intersection(gold))
        self.fp += len(cand - gold)
        self.fn += len(gold - cand)
```

Those counts are used to calculate precision, recall, and f-score.

If you have all the raw per-type TP / FP / FN counts you can add them up and calculate the overall f-score, but you can't calculate the overall f-score from the per-type f-scores alone.

I think there should be some better documentation about this for `Scorer` on the website, since it's not as obvious a metric as something like tagging accuracy.

(I think you're already aware that the ent_per_types results are buggy in 2.1.6? You can use `scorer.py` from master until the next release.)

**Comment by iCHAIT** [comment]
Thank you for the detailed explanation @adrianeboyd . Makes sense 👍 

> (I think you're already aware that the ent_per_types results are buggy in 2.1.6? You can use scorer.py from master until the next release.)

Yeah, that is what I am doing right now :)
