### ISSUE TITLE
Really minor documentation issue - custom_ner_model not available

### ISSUE THREAD

**Issue by sharonwoo** [explosion/spaCy#4104]
Hello, I'm new to Spacy and trying it out. Really enjoyable stuff, thanks. Spotted one small thing working through the docs: 

#### Which page or section is this issue related to?
URL: https://spacy.io/usage/linguistic-features

In the ```NAMED ENTITY EXAMPLE```, this line 

```nlp = spacy.load("custom_ner_model")```

doesn't work for me. Replacing it with the standard model "en_core_web_sm" works perfectly fine.

If I try to install it with ```python -m spacy download custom_ner_model```, I get the error message ```✘ No compatible model found for 'custom_ner_model' (spaCy v2.1.4).```

**Comment by ines** [comment]
Ah, sorry if this was confusing. The `custom_ner_model` in the example was supposed to mean a fictional model you've trained yourself or any model that predicts entities.

The reason we did it this way was so we could also use a "fictional" example – otherwise, the example visualization may be out-of-date (since the exact model's predictions can change in future versions). But I agree that it's not ideal and we should probably just find an example that we know the model will pretty much always get right.
