### ISSUE TITLE
Adding patterns to EntityRuler and deserializing EntityRuler very slow

### ISSUE THREAD

**Issue by jdprusa** [explosion/spaCy#4119]
Adding a large number of patterns to the EntityRuler, or loading a saved EntityRuler that has a large number of patterns is extremely slow. 

This is easily reproduced with:

`nlp = spacy.load('en_core_web_sm')`
`entityruler = EntityRuler(nlp)`
`patterns = [{"label": "TEST", "pattern": str(i)} for i in range(100000)]`
`entityruler .add_patterns(patterns)`

and

`nlp = spacy.load('en_core_web_sm')`
`patterns = [nlp.make_doc(str(i)) for i in range(1000000)]`
`phrasematcher= PhraseMatcher(nlp.vocab)`
`phrasematcher.add("TEST", None, *patterns)`

the EntityRuler code takes around 10 minutes to execute on an m5.4xlarge AWS SageMaker Notebook instance, while the PhraseMatcher code takes 20 seconds. Changing `nlp.make_doc(str(i))` to `nlp(str(i))` slows the PhraseMatcher down to the speed of the EntityRuler.

Looking through the code for the EntityRuler, it employs the PhraseMatcher and should be similar in speed, but is using `nlp(pattern)` with the full nlp pipeline (tagger, parser, ner)  instead of using `nlp.make_doc(pattern)` as recommended for the PhraseMatcher in https://spacy.io/usage/rule-based-matching#phrasematcher

Since EntityRuler uses `add_patterns()` when deserializing this also slows down `from_bytes()` and `from_disk()` by a considerable amount. 

This is fortunately an easy fix, just change the offending line 
**Current Line 187** in https://github.com/explosion/spaCy/blob/master/spacy/pipeline/entityruler.py:
`self.phrase_patterns[label].append(self.nlp(pattern)) `
**Updated Line 187:**
`self.phrase_patterns[label].append(self.nlp.make_doc(pattern)) `

This puts pattern adding and loading times in line with the PhraseMatcher as expected and doesn't appear to break anything.
 
## Your Environment
- **spaCy version:** 2.1.8
- **Platform:** Amazon Linux AMI 2018.03
- **Python version:** 3.6.5

**Comment by adrianeboyd** [comment]
This will break the EntityRuler if the `phrase_matcher_attr` is set to a value that requires more processing than tokenization. `LEMMA`, `POS`, `TAG`, and `DEP` are supported by the PhraseMatcher. (I can't imagine a sensible entity `DEP` pattern, but I'm sure there are some creative patterns out there.)

Could it make sense to use `nlp.make_doc()` except for `phrase_matcher_attr in (LEMMA, POS, TAG, DEP)` or am I missing something this might break?

**Comment by svlandeg** [comment]
Perhaps it makes sense to define it the other way around: which attributes are we 100% sure that they only need the tokenizer, and then use `nlp.make_doc()`, and do `nlp()` by default in all other cases. Then if we extend to other attributes in the future, it won't break?

**Comment by adrianeboyd** [comment]
That list seems a lot longer / more unstable, but I could see it either way.

Maybe there's a way to handle the problem for both PhraseMatcher and EntityRuler in the same way, too? See: https://github.com/explosion/spaCy/pull/4105/commits/823fdc874e6237451ecb147e8644ab2168967c5f#diff-8661aff253083aa633bece2518b64430R132

**Comment by ines** [comment]
On a semi-related note, this issue here is also caused by a side-effect of calling the entire pipeline (via `nlp`) *within* a pipeline component: #4042

> which attributes are we 100% sure that they only need the tokenizer, and then use `nlp.make_doc()`

That list does seem longer indeed, but probably more predictable? In theory (!) we cannot assume anything, though, and the user may have components in their pipeline that alter the tokenization (merging etc.) and affect the patterns. (It's always been kinda unclear how to handle this, though, and if I remember correctly, there are various places in the code base where spaCy does make the assumption that `make_doc` creates the final intended tokenization.)

In any case, we should probably rewrite the `add_patterns` logic to sort and validate the incoming patterns *first* and create the `Doc` objects in batches using `nlp.pipe`. That'll likely make it much faster already and it should be possible to implement.

Next, we could consider the following:
* Have the user pass in pipeline component names to disable when creating the phrase patterns. **Pros:** Full control, easy to serialize with the entity ruler component config. **Cons:** Not very intuitive, not something the user necessarily thinks about, yt another config option with a potentially weird name.
* Try to guess which components may not be needed based on the attributes and the pipeline and disable as much as possible. **Pros:** Better default because the user doesn't have to do anything. **Cons:** Tedious and not very reliable – additions like #3943 may help in the future, though.

**Comment by bollampa** [comment]
any updates on this issue?

**Comment by ines** [comment]
@bollampa You can already work around this by disabling the pipeline components you don't need when adding the patterns. It's just that the `EntityRuler` doesn't have a mechanism built-in to do this out-of-the-box.

```python
disabled = nlp.disable_pipes("tagger", "parser", "ner")
ruler = EntityRuler(nlp)
 entityruler .add_patterns(patterns)
disabled.restore()
```

**Comment by chingan-tsc** [comment]
> @bollampa You can already work around this by disabling the pipeline components you don't need when adding the patterns. It's just that the `EntityRuler` doesn't have a mechanism built-in to do this out-of-the-box.
I am having the same issue except I am already using the `xx` model and I am trying to "enhance" it using EntityRuler and I realized I cannot use this trick. Is there a way to speed things up in my case?

**Comment by ines** [comment]
> I am having the same issue except I am already using the xx model and I am trying to "enhance" it using EntityRuler and I realized I cannot use this trick. 

The solution should work fine, even with the xx model? The model only has the `ner` component, so that's the only one you need to disable. Or are you saying that you need the `ner` component to run because your patterns depend on it?

**Comment by bollampa** [comment]
@ines Yes, that is my issue as well. My patterns depend on the ner model.

**Comment by chingan-tsc** [comment]
> > I am having the same issue except I am already using the xx model and I am trying to "enhance" it using EntityRuler and I realized I cannot use this trick.
> 
> The solution should work fine, even with the xx model? The model only has the `ner` component, so that's the only one you need to disable. Or are you saying that you need the `ner` component to run because your patterns depend on it?

Correct me if I am wrong, I have the following code:
```python
nlp = spacy.load('xx') # Loads the xx model
nlp = nlp.disable_pipes("ner") # Disable NER component
ruler = EntityRuler(nlp, overwrite_ents=True).from_disk("./patterns.jsonl") # Adds my own rule that is stored in a JSONL
nlp.add_pipe(ruler) # Add it as a pipeline
nlp.restore() # Restore the disabled pipeline
```
But it keep throwing an `AttributeError: 'DisabledPipes' object has no attribute 'vocab'` error.

**Comment by adrianeboyd** [comment]
`disable_pipes()` returns `DisabledPipes` not modified `nlp` component. Try:

```
disabled = nlp.disable_pipes("ner") # Disable NER component
...
disabled.restore()
```

**Comment by chingan-tsc** [comment]
> `disable_pipes()` returns `DisabledPipes` not modified `nlp` component. Try:
> 
> ```
> disabled = nlp.disable_pipes("ner") # Disable NER component
> ...
> disabled.restore()
> ```

Hmm doesn't work. Now its throwing 
```
ValueError: [E008] Some current components would be lost when restoring previous pipeline state. If you added
		components after calling `nlp.disable_pipes()`, you should remove them explicitly with `nlp.remove_pipe()`
		before the pipeline is restored. Names of the new components: ['entity_ruler']
```

**Comment by ines** [comment]
From the eror message, it sounds like you're trying to restore the pipeline *after* you've added the entity ruler to the pipeline. This isn't going to work, because as the error message says, you'll end up with incosnsitent state.

Disabling the component is only needed to initialize the entity ruler and add the patterns, though, so you can restore the pipeline right after that (as shown in the code I posted above).

**Comment by Joozty** [comment]
Any update on this? 🙂 I have many (7M) patterns in EntityRuler and when I try to load my model it's a neverending story 😢

**Comment by svlandeg** [comment]
Have you tried temporarily disabling the other components like Ines outlined in one of the replies above?

**Comment by Joozty** [comment]
Not really since I have an issue with [deserialization](nlp_dir). My patterns are stored already in the model directory and when I try to load it via `nlp.load(<model_dir>)` it takes quite a bit of time (15min). I wouldn't mind really. The bigger problem with me is when I try to process text via `nlp(<text>)`. it takes minutes to process small documents. 

Is it just simply because I have too many patterns and spaCy cannot cope with it?

**Comment by Joozty** [comment]
> The bigger problem for me is when I try to process text via nlp(<text>). It takes minutes to process small document.

Should I create a minimal working example or perhaps create a new bug report for this particular issue?

**Comment by Joozty** [comment]
@svlandeg @ines Any luck with this issue? I am unable to train my model because of this slowness.


I created for you a simple example:

```python
import spacy
import time

nlp = spacy.load("en_core_web_md",  exclude=["tok2vec", "tagger", "parser", "tagger", "attribute_ruler", "lemmatizer", "ner"])

# text with 91words / 571 characters
text = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
ruler = nlp.add_pipe("entity_ruler")
patterns = []

for word in nlp.vocab.strings:
    pattern = [
        {"LOWER": word}
    ]

    patterns.append({
        "label": "THING",
        "pattern": pattern
    })

ruler.add_patterns(patterns)
start = time.time()
nlp(text)
print("Processing 91 words took: ", time.time() - start)


# average wiki article https://wikicount.net/
start = time.time()
nlp(text * 15)
print(f"Processing {91 * 15} words took: ", time.time() - start)


start = time.time()
nlp(text * 50)
print(f"Processing {91 * 50} words took: ", time.time() - start)
```

Output
```bash
Processing 91 words took:  1.9626801013946533
Processing 1365 words took:  26.29333734512329
Processing 4550 words took:  83.97859406471252
```


It's getting even slower when you have rules with multi-words.

With a little bit of profiling, I was able to find a bottleneck here. It's a [Matcher](https://github.com/explosion/spaCy/blob/master/spacy/matcher/matcher.pyx#L199)


Thanks a lot for helping me in this matter

**Comment by adrianeboyd** [comment]
Having the `Matcher` run time basically scale with the length of the document is not unexpected given how the algorithm works underneath. It's set up to be able to compare detailed linguistic annotation for each token, so it's basically comparing each token to each pattern underneath.

If you're only matching on `LOWER` (or another single attribute), you could consider using phrase patterns instead of token patterns with `EntityRuler(phrase_matcher_attr="LOWER"), so it's using `PhraseMatcher` instead of `Matcher` underneath, which scales better for large numbers of patterns.

You can see some timing examples here, and read further down the thread for more comparisons:

https://github.com/explosion/spaCy/pull/4309#issuecomment-533172866

In the end the exact numbers depend a lot on what the patterns and texts look like, so you could try it out for your task and see if it's suitable. It's possible that with a huge number of patterns, spacy's built-in matchers are not going to be the best tool.

**Comment by Joozty** [comment]
@adrianeboyd Thanks a lot it makes sense. It's much faster now. I am just encountering memory issue (regardless of `phrase_matcher_attr` value). Is it also intended behaviour? This issue is kind of prevents me to run the code in multiple processes.


import spacy
import time
import resource
import sys
nlp = spacy.load("en_core_web_md",  exclude=["tok2vec", "tagger", "parser", "tagger", "attribute_ruler", "lemmatizer", "ner"])

ruler = nlp.add_pipe("entity_ruler")
patterns = []

for word in nlp.vocab.strings:
    pattern = [
        {"LOWER": word}
    ]

    patterns.append({
        "label": "THING",
        "pattern": pattern
    })

ruler.add_patterns(patterns)
start = time.time()
print(sys.getsizeof((patterns))) # 6MB
del ruler
del patterns
print(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss) # 1.2GB memory

**Comment by Joozty** [comment]
Anything I could help with to solve this issue?

**Comment by polm** [comment]
@Joozty In your example code, the way you're adding the patterns will cause the Matcher to be used instead of the PhraseMatcher. To use the PhraseMatcher your patterns needs to be a string, not a list of dicts. As mentioned using the PhraseMatcher may scale better. 

With 7M patterns though I'm just not sure the matchers will work well, they weren't designed with that many patterns in mind. What are your patterns? Are they personal names, names of corporations, or something else? 7M is more than the number of articles on English Wikipedia, I'm confused as to what they could be.

**Comment by Joozty** [comment]
@polm thanks that's really helpful.  I managed to solve this issue by using [flashtext](https://github.com/vi3k6i5/flashtext). Will try to migrate back

About the 7M patterns - I am working on wikification and I consider a pattern every alias/link on Wikipedia, hence that amount of patterns. However I already slightly decreased the number of patterns down because it was not possible to recognise all of them in feasible time...

**Comment by polm** [comment]
If you already have something that works there's no need to migrate. The matcher wasn't designed with that many patterns in mind and I'm not sure it would work well even with PhraseMatcher if you have millions of patterns. 

> About the 7M patterns - I am working on wikification and I consider a pattern every alias/link on Wikipedia

I guess that explains why you have so many patterns, though I have never heard of someone doing wikification that way. Usually the mention detector would be a typical statistical NER/sequence labelling component. I guess you've seen it but the [Entity Linker](https://spacy.io/api/entitylinker) is a general-case tool for problems like wikification, and is designed with the expectation you'll use it on named entities.

**Comment by polm** [comment]
For the record, while the EntityRuler still isn't intended for use with extremely large vocabularies, slowness was likely exacerbated by the issue reported in https://github.com/explosion/spaCy/issues/8216. A fix for that is already pending and should be released soon.
