### ISSUE TITLE
Help with REGEX

### ISSUE THREAD

**Issue by hanymorcos** [explosion/spaCy#4125]
I'm having a hard time getting a REGEX to work. Can I get some input?

## How to reproduce the behaviour
        patterns = [{"TEXT"   : {"REGEX": r"^\d{3}[ -]?\d{2}[ -]?\d{4}$"}} ]
        nlp = spacy.load("en_core_web_sm")
        matcher = Matcher(nlp.vocab)
        matcher.add("SSN", None, patterns)
        doc =nlp(u"343-22-2322")
        entities = []
        matches = matcher(doc)
        print (matches)

## Your Environment
* **spaCy version:** 2.1.8
* **Platform:** Darwin-18.6.0-x86_64-i386-64bit
* **Python version:** 3.7.4

**Comment by BreakBB** [comment]
It would be great if you explain what you expect to match with that regex and what you get instead.

**Comment by hanymorcos** [comment]
I expect a match for 343-22-2322. My regular expression is for 3 digit (dash/space) 2 digit (dash/space) 4 digit. I tried removing ^ and $ and still it's not matching.

**Comment by hanymorcos** [comment]
I get nothing back. I'm trying NLTK currently. I have much harder regular expressions.

**Comment by ines** [comment]
The problem is that the `doc` you're matching on is 3 tokens: `[t.text for t in doc]` returns `['343', '-', '22', '-', '2322']`. However, your regex only describes **one token** with that value, so it never matches. [See the docs for details](https://spacy.io/usage/rule-based-matching#adding-patterns).

So you either want to rewrite your rules to reflect the tokenization with one dict per token, or just not use the matcher at all, run your regular expression on the `doc.text` and then use `doc.char_span` to create spans from the matches (if you need them).

Btw, for usage questions and stuff like "what's wrong with my code", it's usually better to post [on Stack Overflow](https://stackoverflow.com/tags/spacy) instead. We try to keep this issue tracker focussed on bug reports and enhancement issues.
