### ISSUE TITLE
Interactive Course - Incorrect Code

### ISSUE THREAD

**Issue by yhscherber** [explosion/spaCy#4136]
## Which page or section is this issue related to?

In Chapter 2, section "Data Structures Best Practices", Part 2, the solution is not a general solution and would not work for strings which end in a Proper Noun. To fix this, I used this code instead:

``` python
import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("Berlin is a nice city")

length = len(doc)

for token in doc:
  if token.i + 1 < length:
    nextToken = doc[token.i + 1]
    if token.pos_ == 'PROPN':
      if nextToken.pos_ == 'VERB':
        print("Found proper noun before a verb:", token.text)

```

**Comment by ines** [comment]
Yes, you're right – I think I ended up cutting a few things here to make the example a bit simpler. Especially since it's a rewriting exercise, which is already a bit more challenging than just a normal "fill in the blanks" example.

I think it'd make sense to mention that there are still things that should be improved and that you'd need to explicitly check `if token.i + 1 < length`. I'll add that to the success message.
