### ISSUE TITLE
Vocab for init-model

### ISSUE THREAD

**Issue by kennyjoseph** [explosion/spaCy#4137]
I think its worth noting in the init-model documentation that if you just start  with a word2vec vector file, the vocabulary will still depend on spacy's vocabulary (or at least, thats what it looks like in the code).   It took me a while to figure out why the word "cop", which was in my file, didn't have a vector loaded in (because it wasn't ever created by init-model)

## Which page or section is this issue related to?

https://spacy.io/api/cli#init-model

**Comment by ines** [comment]
Thanks and sorry for only getting to this now. 

This is correct – in order to populate the vocab, you need a vocabulary file. Just loading in word vectors will only add the vectors, not populate the vocab. I've just added some more clarification to the docs, including a previously missing note that you can use the `id` value in the vocabulary file to reference the row in the vectors table.

**Comment by kennyjoseph** [comment]
Thanks! Much appreciated on the clarification.
