### ISSUE TITLE
Matcher won't match pattern with Negate operator

### ISSUE THREAD

**Issue by yash1994** [explosion/spaCy#4152]
## How to reproduce the behavior

```python
import spacy
from spacy.matcher import Matcher
nlp = spacy.load('en_core_web_sm')
matcher = Matcher(nlp.vocab)

pattern_1 = [{"LOWER": "hello"},{"IS_PUNCT": True, "OP": "!"}]
pattern_2 = [{"LOWER": "hello"},{"IS_PUNCT": True, "OP": "?"}]
pattern_3 = [{"LOWER": "hello"},{"IS_PUNCT": True}]

matcher.add("pattern_1", None, pattern_1)
matcher.add("pattern_2", None, pattern_2)
matcher.add("pattern_3", None, pattern_3)

doc = nlp(u'Hello! Hello')
matches = matcher(doc)
for match_id, start, end in matches:
	string_id = nlp.vocab.strings[match_id]  # Get string representation
	span = doc[start:end]  # The matched span
	print(match_id, string_id, start, end, span.text)
```
## Actual Output
```
15719126060659784350 pattern_2 0 2 Hello!
13375652922493068680 pattern_3 0 2 Hello!
15719126060659784350 pattern_2 2 3 Hello
```
## Expected Ouput
```
-------------------- pattern_1 2 3 Hello
15719126060659784350 pattern_2 0 2 Hello!
13375652922493068680 pattern_3 0 2 Hello!
15719126060659784350 pattern_2 2 3 Hello
```

## Your Environment

* Operating System: Ubuntu 18.04.1 LTS
* Python Version Used: Python 3.6.7
* spaCy Version Used: 2.1.8

**Comment by adrianeboyd** [comment]
The meaning of `{"IS_PUNCT": True, "OP": "!"}` is "match a single token that is not punct" rather than "match a single token that is not punct or match zero tokens at the beginning or end of a document". I don't think that there is currently any way to do what you want here where "!" could also match where no token is present.

See the discussion in #3695, which is a duplicate of this issue. In particular, see the suggestions in https://github.com/explosion/spaCy/issues/3695#issuecomment-491510035.

**Comment by yash1994** [comment]
Thanks for your help. I understood so there has to be a token on which negate operation can work. Closing the issue
