### ISSUE TITLE
Memory Issues, Please Advice.

### ISSUE THREAD

**Issue by webscent** [explosion/spaCy#417]
I am trying to run Spacy with limited memory.

Could some kindly advice on how to run spacy with limited functions.

I only require, pos tagging and dependency parsing from spacy.

Thanks.

**Comment by techiev2** [comment]
@lovedecay 

We are currently running a Spacy instance (Stock Ubuntu server image) on a 512MB box and swapping out the rest of the memory requirements (8GB of swap with an increased vm.swappiness switch).

Fwiw, our tests seem to indicate restricting the features during spacy init seems to be less efficient in terms of processing time compared to default init with just the language.

Can you update on what other particular concerns you have so that we can have the discussion going towards a solution to the situation?
