### ISSUE TITLE
Spacy NER Evaluation is being incorrect

### ISSUE THREAD

**Issue by mmanishh** [explosion/spaCy#4181]
Here is my test data and NER parsed data from Spacy NER. I have been training with my own NER for address parsing. Since the test data and parsed data are 100% accurate why is the score i.. Precision , Recall and F-score only 60 ? 

**Test Data:**
 `[('ACEH', [(0, 4, 'province')]), ('SUMATERA UTARA', [(0, 14, 'province')]), ('SUMATERA BARAT', [(0, 14, 'province')]), ('RIAU', [(0, 4, 'province')]), ('JAMBI', [(0, 5, 'province')])]
`

**Parsed Data**
` [{'province': (0, 4)}, {'province': (0, 14)}, {'province': (0, 14)}, {'province': (0, 4)}, {'province': (0, 5)}]
`

**Evaluation Result:**
 `{'uas': 0.0, 'las': 0.0, 'ents_p': 60.0, 'ents_r': 60.0, 'ents_f': 60.0, 'tags_acc': 0.0, 'token_acc': 100.0}`

Is there any other way to evaluate Spacy NER model?

## Info about spaCy

* **spaCy version:** 2.1.4
* **Platform:** Linux-5.0.0-25-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.7.3

**Comment by adrianeboyd** [comment]
Thanks for the report. Could you provide more details about your evaluation code so it's possible to see how the parsed data and evaluation are generated?

**Comment by mmanishh** [comment]
I have been using spacy's evaluation code to evaluate the model. Here is the code
```
def evaluate(ner_model, examples):
    """
    Params
    ner_model : Spacy ner model
    examples : test data to evaluate on
    Returns
    scores : dict containing precision, reacall and f-score
    count : count of total test_data that was evaluate on
    """
    scorer = Scorer()
    count_error_data = 0
    for input_, annot in examples:
        try:
            doc_gold_text = ner_model.make_doc(input_)
            gold = GoldParse(doc_gold_text, entities=annot)
            pred_value = ner_model(input_)
            scorer.score(pred_value, gold)
            
        except ValueError as e:
            count_error_data +=1
            pass
    return scorer.scores, len(examples)-count_error_data
```

**Comment by mmanishh** [comment]
Parsed address or data is generated from this code :
```
def parse_address(addr,model=nlp):
    doc = model(addr.lower())
    result = {}
    # Find named entities, phrases and concepts
    for ent in doc.ents:
        start, end = ent.start_char, ent.end_char
        result[ent.label_] = addr[start:end]
        
    return result
```

**Comment by adrianeboyd** [comment]
> Parsed address or data is generated from this code :
> 
> ```
> def parse_address(addr,model=nlp):
>     doc = model(addr.lower())
>     result = {}
>     # Find named entities, phrases and concepts
>     for ent in doc.ents:
>         start, end = ent.start_char, ent.end_char
>         result[ent.label_] = addr[start:end]
>         
>     return result
> ```

This function doesn't return the same format as the parsed data you have quoted in your first message. Are you sure the entities are being labeled as you think?

If any part of the entity is incorrect (start, end, or label), it gets counted as incorrect by the scorer. The scorer is pretty simple and has been tested quite a bit for NER evaluation, so I'd look more carefully at the raw output to double-check which spans the model is labeling.

Other notes:

- Unless you only have access to lowercase data, I wouldn't recommend `addr.lower()`. Since NER is sensitive to capitalization, it'd be best to use mixed case data for training and testing if it's available.
- NER is intended for entities in context (with surrounding text), so your test cases aren't the kind of data an NER model is intended to work well for. If you have known lists of entities that you would like to match, try the `EntityRuler` instead.

**Comment by mmanishh** [comment]
@adrianeboyd The evaluation function doesn't have to do anything with the parse_address function , does it ? The parse_address function is implemented to show how model i.e NER parsed the given input. I think it is doing accurately. However when evaluating through the evaluation function , It gives only 60 score.

Here is parsed data output:
```
[{'province': 'ACEH'}, {'province': 'SUMATERA UTARA'}, {'province': 'SUMATERA BARAT'}, {'province': 'RIAU'}, {'province': 'JAMBI'}]
```

Test data : 
```
[('ACEH', [(0, 4, 'province')]), ('SUMATERA UTARA', [(0, 14, 'province')]), ('SUMATERA BARAT', [(0, 14, 'province')]), ('RIAU', [(0, 4, 'province')]), ('JAMBI', [(0, 5, 'province')])]
```

Also, I am using NER to actually parse the addressing using context i.e the address is full length address which includes street address, house no.,district, village, province. I am using only one tag i.e province for testing purpose.

**Comment by mmanishh** [comment]
Does the evaluation function of spacy or the Scorer class parses the NER tags in some other way than implemented in parse_address function ? How does it judge the model? I think it will judge by comparing start and end index and label for NER tag ?

**Comment by adrianeboyd** [comment]
You're right that the `parse_address()` function isn't directly related, but the main point is that you need to inspect the documents that you're passing to the Scorer more carefully in order to figure out what's going on.

The `parse_address()` and `evaluate()` functions aren't necessary doing the same thing. Are you sure that the `lower()` in isn't making a difference? Within `evaluate()`, compare:

```
ner_model(input_)
```

vs.

```
parse_address(input_,model=ner_model)
```

Here's how the NER Scorer works (upgrade to 2.1.8 if you need the per-type evaluation): https://github.com/explosion/spaCy/issues/4094#issuecomment-518995164

**Comment by mmanishh** [comment]
@adrianeboyd  Great Thanks! addr.lower() was making the difference.
