### ISSUE TITLE
Tokenize on $ seems to give issues

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#4212]
I am trying to tokenize `US$50` into `['US', '$', '50']` but there seems to be an issue or I am misunderstanding something!?

```python
import spacy.util
import spacy.lang.en

nlp = spacy.lang.en.English()

infixes = nlp.Defaults.infixes + (
    r"(?<=\S)\$",
)
nlp.tokenizer.infix_finditer = spacy.util.compile_infix_regex(infixes).finditer

assert [t.text for t in nlp('US$50')] == ['US', '$', '50']  # fails
```

E.g. replacing `$` with `X` works as expected

```python
infixes = nlp.Defaults.infixes + (
    r"(?<=\S)X", 
)
nlp.tokenizer.infix_finditer = spacy.util.compile_infix_regex(infixes).finditer

assert [t.text for t in nlp('USX50')] == ['US', 'X', '50']  # passes
```

* **spaCy version:** 2.1.8
* **Platform:** Linux-5.0.0-25-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.7.3

**Comment by mr-bjerre** [comment]
Just noticed another strange thing.

I have a custom component that uses the `PhraseMatcher` on the `LOWER` attribute. It only works if I `nlp.add_pipe` **before** I change the tokenizer. If I set `nlp.tokenizer.prefix_search`, `nlp.tokenizer.infix_finditer`, `tokenizer.suffix_search` before `nlp.add_pipe` then it does not work as expected. How come?

**Comment by adrianeboyd** [comment]
Currency symbols are matched by the prefix and suffix regexes, so that's where the interaction is. You might have to modify more than just the infixes to get the tokenization that you want.

I think what should matter for `PhraseMatcher` is the tokenization in docs that you pass to `add()`. I remember that having a pipeline component call `nlp` has led to some weird interactions in other places and maybe you've come across another one? See #4042. More details about the component would be helpful so it's possible to reproduce the error.

**Comment by mr-bjerre** [comment]
Well I'll have to disagree on the currency symbols. This is failing too

```python
suffixes = nlp.Defaults.suffixes + (r"\$",)
nlp.tokenizer.suffix_search = spacy.util.compile_suffix_regex(suffixes).search

assert [t.text for t in nlp('US$')] == ['US', '$']  # fails
```

Let me see if I can boil my other finding down to a simple example

**Comment by mr-bjerre** [comment]
Located the other issue.

Working example

```python
import spacy.util
import spacy.lang.en
import spacy.matcher

nlp = spacy.lang.en.English()
suffixes = nlp.Defaults.suffixes + (r"Q1",)
nlp.tokenizer.suffix_search = spacy.util.compile_suffix_regex(suffixes).search

matcher = spacy.matcher.PhraseMatcher(nlp.vocab, attr='LOWER')
matcher.add("Q1", None, nlp('q1'))

infixes = nlp.Defaults.infixes + (r"(?<=[a-zA-Z])\d",)
nlp.tokenizer.infix_finditer = spacy.util.compile_infix_regex(infixes).finditer

doc = nlp('You should find 2018Q1 as a token')
assert [t.text for t in doc] == ['You', 'should', 'find', '2018', 'Q1', 'as', 'a', 'token']  # passes
assert len(matcher(doc)) == 1  # passes
```

Breaking example where the `infixes` are set **before** the phrase matcher.

```python
import spacy.util
import spacy.lang.en
import spacy.matcher

nlp = spacy.lang.en.English()
suffixes = nlp.Defaults.suffixes + (r"Q1",)
nlp.tokenizer.suffix_search = spacy.util.compile_suffix_regex(suffixes).search

infixes = nlp.Defaults.infixes + (r"(?<=[a-zA-Z])\d",)
nlp.tokenizer.infix_finditer = spacy.util.compile_infix_regex(infixes).finditer

matcher = spacy.matcher.PhraseMatcher(nlp.vocab, attr='LOWER')
matcher.add("Q1", None, nlp('q1'))

doc = nlp('You should find 2018Q1 as a token')
assert [t.text for t in doc] == ['You', 'should', 'find', '2018', 'Q1', 'as', 'a', 'token']  # passes
assert len(matcher(doc)) == 1  # fails
```

**Comment by adrianeboyd** [comment]
It's not always sufficient to add new regexes with the tokenizer. Sometimes you need to edit/remove existing patterns to get the results that you want. See a full example with infixes: https://stackoverflow.com/a/57304882/461847.

Look at all the patterns used in prefixes and suffixes in https://github.com/explosion/spaCy/blob/master/spacy/lang/punctuation.py and https://github.com/explosion/spaCy/blob/master/spacy/lang/char_classes.py. The reason your attempts aren't working is that `US$` is being matched as a prefix.

For the PhraseMatcher issue, inspect the tokenization at the point where you add the pattern to the matcher. Your new infix pattern splits 'q1' into ['q', '1'] but not `2018Q1` into `['2018', 'Q', '1'], which is why it doesn't match.

**Comment by mr-bjerre** [comment]
Ah makes sense. I forgot that when I add patterns on the phrase Matcher then I actually tokenize those. 

Both questions perfectly answered. Thanks a bunch !
