### ISSUE TITLE
split span

### ISSUE THREAD

**Issue by sr33kant** [explosion/spaCy#4214]
## Your Environment

* Operating System:windows
* Python Version Used:3.6
* spaCy Version Used:2.0.18
* Environment Information: 
mdl=spacy.load('en_core_web_sm')
txt=mdl('Our reported interest expense for the years ended December 31 ,2016 , 2015 and 2014 includes non - cash interest related to the accounting for convertible securities of $ 8.1 million , $ 7.9 million and $ 7.1 million , respectively .')
print( [(e.text, e.start_char, e.end_char, e.label_) for e in txt.ents])
[('the years ended December 31 ,2016 , 2015 and 2014', 34, 83, 'DATE'), ('$ 8.1 million', 169, 182, 'MONEY'), ('$ 7.9 million', 185, 198, 'MONEY'), ('$ 7.1 million', 203, 216, 'MONEY')]
would have preferred to get three date entities as opposed to one. From documentation its not clear how to add a regex to split the span so it outputs three dates while not affecting other entity spans in the same sentence.

**Comment by adrianeboyd** [comment]
If you want to edit the predicted entities, you need to remove the existing entity and add the new ones, since entities aren't allowed to overlap. If your regex patterns work with Matcher, you could consider using an EntityRuler with `overwrite_ents=True`, but otherwise it's not to hard to do with hand-crafted rules. See Ines's explanation in a similar issue: https://github.com/explosion/spaCy/issues/3608#issuecomment-484179345
