### ISSUE TITLE
Tips on how to increase GPU utilization

### ISSUE THREAD

**Issue by H20Watermelon** [explosion/spaCy#4220]
## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.7
* spaCy Version Used: 2.1.8

The documents I work with are typically on the larger side (Articles, emails/email threads). When I do the following:

```
results = []
for doc in nlp.pipe(docs, batch_size = 100, as_tuples = True):
    doc, docid = doc
    results.append([docid, doc])

```
The GPU utilization rate is around 3% - 7%. I wonder if there is any suggestion/tips on how I can increase GPU utilization Also as a side note, my GPU's memory is 16 Gb, so this limits how big the batch size can be -- I tried 200 docs, but it was clearly too big as I got an cupy out of memory error.

**Comment by honnibal** [comment]
Maybe try sorting your documents by descending length?

The issue is that if you have a document with say, 10k tokens and the other documents in the batch have 500 tokens, the parser and NER models will have to iterate over the words of your long document in a batch size of 1. Normally this isn't *that* slow, but it could be hurting you a bit.
