### ISSUE TITLE
Email-like text tokenized wrongly

### ISSUE THREAD

**Issue by yarongon** [explosion/spaCy#4225]
## Problem description
Tokens are merged (or didn't split, to begin with) when email-like text is parsed, however, the `like_email` flag is false.

## How to reproduce the behavior
```python
import spacy

nlp = spacy.load("en", disable=["parser", "tagger", "ner"])
resume_text = "a,b@mail"  # text that does not look like an email address
doc = nlp(resume_text)
print([t.text for t in doc]) # => ['a', ',', 'b@mail'], 3 tokens

resume_text = "a,b@mail.com"  # Text that looks more like an email address 
doc = nlp(resume_text)
print([t.text for t in doc])  # => ['a,b@mail.com'], 1 token, and `like_email` is False. AFAIK is should still be 3 tokens
```

## Info about spaCy
* **spaCy version:** 2.1.3
* **Platform:** Darwin-18.7.0-x86_64-i386-64bit
* **Python version:** 3.6.8
* **Models:** en

**Comment by adrianeboyd** [comment]
The URL token exception regex is a little more accepting in the username part than the like_email regex, which leads to this tokenization without like_email.

Since this isn't a valid email address, I don't think the like_email regex should change. I'm not sure there's a whole lot of benefit in modifying the URL regex, which is already pretty complicated. Do you have particular use cases where this behavior is causing problems for you?

The behavior is affected by the same caching problem as in #4238, so this may not work as expected, but with a clean pipeline (that you haven't called on any text yet), you can disable the URL pattern like this:

```
nlp = spacy.load('en')
nlp.tokenizer.token_match = None
print([t.text for in nlp("a,b@gmail.com")])
# ['a', ',', 'b@gmail.com']
```

You'll get weird tokens out of URLs, though, and maybe some email addresses.

You can also customize the URL_PATTERN if you'd like. See how it's set up here and then assign it the modified `re.compile().match` to `nlp.tokenizer.token_match`:

https://github.com/explosion/spaCy/blob/232a029de68e7e238dfb066a74185ae78c75da49/spacy/lang/tokenizer_exceptions.py#L9-L54

**Comment by yarongon** [comment]
I suspected it has something to do with the tokenizer exceptions... thanks! your code
```python
nlp.tokenizer.token_match = None
```
did the trick, but of course, I'll have to check deeper. Again, thank you!

My use case is texts with personal information, where people write their phone number, some character, and their email address. For example: `(555)-123-1234|my@email.com`
```python
text = "(555)-123-1234|my@email.com"
doc = nlp(text)
print([t.text for t in doc]) # => ['(', '555)-123-1234|my@email.com'] oy vey....
```

**Comment by adrianeboyd** [comment]
That looks more like you want to add custom infixes. It can get tricky with things like:

```
Phone:555-1234
Time:9:30am
```

So if not matching URLs solves the problem and doesn't cause problems in your texts elsewhere, then that is probably the simplest solution.
