### ISSUE TITLE
Spanish is making abbreviations as the end of a sentence

### ISSUE THREAD

**Issue by sontek** [explosion/spaCy#4254]
## How to reproduce the behaviour

```
>>> import spacy
>>> nlp = spacy.load('es')
>>> sentence = "¿Podría hacer el favor de comunicarme con Washington, EE. UU. ?"
>>> doc = nlp(sentence)
>>> len(list(doc.sents))
3
```

## Info about spaCy

* **spaCy version:** 2.1.8
* **Platform:** Darwin-18.0.0-x86_64-i386-64bit
* **Python version:** 3.6.7
* **Models:** es

* Operating System: OSX
* Python Version Used: Python3.6

**Comment by ines** [comment]
Merging this with #3052. It's less useful to have these reports and test cases as separate issues – they're typically not immediately actionable, because these things come down to the statistical models. (In this case, the parser, which is used for sentence segmentation – you can always replace it with the rule-based `sentencizer` if that works better for your data.)

Maybe inaccuracies here point to a deeper problem, maybe they're just something that has to be accepted because of the training data that's available and the fact that models are statistical. (Even if a model is 90% accurate, every 10th prediction it makes will be wrong.)
