### ISSUE TITLE
Best strategy to use nlp object inside a custom component

### ISSUE THREAD

**Issue by chkoar** [explosion/spaCy#4283]
Let's say that I take an existing model and I add a custom component that classifies spans. So, my custom component take as parameter the `nlp` object itself because I need it to make some preprocessing (again) in the span. Like this I could fall in an infinite loop. What is the best strategy to handle this kind of problem? (You can assume that I need features from the pipeline and cannot use just the `make_doc`)

A solution I found is to deep copy the `nlp` object. Is there a better strategy that I am not aware of?

**Comment by ines** [comment]
This is an interesting question and kind of related to the conceptual problem we came across in #4042 (and that we still don't have a perfect answer for).

What exactly are you doing in your pipeline component and how are you using the `nlp` object there? Maybe there is a way to avoid the double processing? It _is_ pretty unideal and can potentially lead to more problems down the line and will make it difficult to process things efficiently (since you won't really be able to process anything in batches within your pipeline component).

> Like this I could fall in an infinite loop. What is the best strategy to handle this kind of problem?

One advantage you do have in your pipeline component is that you know its name (unless you override that when you add it). So you can at least disable the component itself when using the `nlp` object in your component to prevent an infinite loop:

```python
with nlp.disable_pipes("your_pipeline_component"):
    # do something here
```

**Comment by chkoar** [comment]
@ines thanks.
> One advantage you do have in your pipeline component is that you know its name (unless you override that when you add it).

That was probably the best idea to work around. In the case you are using class-based custom components you don't even need to set the name. 
```python
class CustomComponent(object):
    def __init__(self, nlp):
        self.nlp = nlp

    def __call__(self, doc):
        with nlp.disable_pipes(self.__class__.__name__):
            # custom logic extracting some text
            redoc = self.nlp(text)
            # further processing setting custom token or span attrs in the doc
        return doc
```
