### ISSUE TITLE
Error in spacy.load() while sharing my model folder with others in my team

### ISSUE THREAD

**Issue by santoshboina** [explosion/spaCy#4296]
Created a custom spacy ner on new entities and saved model using nlp.to_disk() and tested it on my local machine by spacy.load ('path to model') which worked succesfully.

When i tried to share my model folder (contains pipeline named folders,meta.json and vocab) with others and throws error for others when they try to run spacy.load('path to model')
**Can't find model custommodel**

Note: We both are using same version of Spacy 2.1.8 and python 3.7.3

**Comment by svlandeg** [comment]
When you say you _share_ your model folder, what does that mean exactly? Did you share it over an internal network or did you somehow distribute a full copy of your folder to them? In both cases, each person will need to adjust the code  `spacy.load(model_path)` to the exact `model_path` on their systems. Before trying to call `spacy.load`, could they print the contents of the `model_path` directory on their system, to verify whether the problem is with spaCy, or with the file naming?

Also on a related note, it might be interesting for you to consider packaging your custom model as a Python package, see the docs [here](https://spacy.io/usage/saving-loading#models-generating).

**Comment by santoshboina** [comment]
Thank you, I have created a package of my model which resolved my issue.
