### ISSUE TITLE
Extract recurrent patterns using rule-based matching

### ISSUE THREAD

**Issue by prateekjoshi565** [explosion/spaCy#4301]
## Extract recurrent patterns using rule-based matching: Rule-based matching. 

I want to extract the pattern "X such as Y1, Y2,..., Yn-1, and Yn." from a sentence. X is a hypernym and Yi is a hyponym.

Let's take an example:

```
doc = nlp("GDP in developing countries such as Vietnam, Indonesia and Bangladesh will continue growing at a high rate.")

# Matcher class object
matcher = Matcher(nlp.vocab)

#define the pattern
pattern = [{'DEP':'amod', 'OP':"?"},
           {'POS':'NOUN'},
           {'LOWER': 'such'},
           {'LOWER': 'as'},
           {'POS': 'PROPN'}]

matcher.add("matching_1", None, pattern)
matches = matcher(doc)
span = doc[matches[0][1]:matches[0][2]]
span.text
```
**Output:** 'developing countries such as Vietnam'

The desired output is 'developing countries such as Vietnam, Indonesia and Bangladesh'. How to perform this task using spaCy? 

Thanks in advance.

**Comment by Abhishek-P** [comment]
I can see a slightly convoluted way to get this done.
1. Custom component to add an attribute indicating token/span as Hypernym
2. Custom component to add an attribute indicating token/span as Hyponym

Now you will need to match whether a Hyponym and Hypernym are correlated which can be done using a common key i.e Hypernimiity Key 

But you may not be able to make it universal. But you will be able to create a pattern for each of the Hypernymity Set

With 1 and 2 in the pipeline, tokens for simplicity should be something like this

Token["text" : "countries", "hypernimity" : "GENERIC", "hypernimity_key" : "COUNTRY"]
Token["text": "Vietnam ", "hypernimity":" "SPECIFIC", "hypernimity_key" : "COUNTRY"]

It may become more complicated for span
Now you can write the pattern as 
`pattern = [{'DEP':'amod', 'OP':"?"}, 
{'POS':'NOUN', "hypernimity" : "GENERIC", "hypernimity_key" : "COUNTRY"},
  {'LOWER': 'such'},
  {'LOWER': 'as'},
  {'POS': 'PROPN', "hypernimity": "SPECIFIC", "hypermity_key" : "COUNTRY"}]`

The need to have a specific hypernimity_key for matching this is making this patten only applicable for one hypernymy

If you have huge hypernimity source - it can be used to build a more generic set of 2 components and recurrent patterns for the same

**Comment by adrianeboyd** [comment]
Hi, this kind of question is probably a better fit for StackOverflow than the bug/issue tracker here.

There's no way to define this pattern as a single pattern with the kinds of pattern that the Matcher supports, since you can't group tokens or apply operators kind of like `(({'POS': 'PROPN'}, {'ORTH': ",", 'OP': '?'}) 'OP': '*')`. You might be able to combine a few patterns and then search for adjacent match spans sort of like: `NOUN_SUCH_AS_PNOUN PNOUN_MEDIAL* AND_PNOUN_FINAL?`

For this kind of pattern, it could also make more sense to search the dependency tree, where this phrase forms a nice subtree. There is a new-ish, undocumented `DependencyMatcher` you could try out. Copied from [my answer about DependencyMatcher on SO](https://stackoverflow.com/a/57678915/461847):

> I kind of hesitate to recommend something that doesn't have any documentation yet, but if you're adventurous, you could try out the relatively new DependencyMatcher. Check out the examples in the test suite to get an idea of how it works:
>
> https://github.com/explosion/spaCy/blob/bae0455f91c375681868f3f21a9de84136f9a561/spacy/tests/matcher/test_matcher_api.py#L271-L346
>
> The operators are similar to:
>
> https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/semgraph/semgrex/SemgrexPattern.html
>
> From looking at the relevant issues in github, it might not be very efficient yet and I wouldn't be
surprised if you ran into a bug or two, so test things carefully before relying on it for anything crucial.
