### ISSUE TITLE
csv to spacy format

### ISSUE THREAD

**Issue by zakarianamikaz** [explosion/spaCy#4318]
how can i convert a CSV NER file (BIO) to spacy json format 

## Your Environment

* Operating System:
* Python Version Used:3.7
* spaCy Version Used:2.0
* Environment Information:

**Comment by svlandeg** [comment]
Hi @zakarianamikaz, I assume you want to train an NER with your custom data? As it's not clear how your CSV file is structured or what it's origin is, it's difficult to give a precise answer, but you'll have to parse it into a format that spaCy understands. Note that spaCy uses the [BILUO](https://spacy.io/api/annotation#biluo) format for training an NER (not BIO), because that is more learnable. You can find more information [here](https://spacy.io/api/annotation#json-input).

If you have a standard format such as a `.conllu` or `.iob` file, you can also try out the command line utily [`convert`](https://spacy.io/api/cli#convert). You can check [this directory](https://github.com/explosion/spaCy/tree/master/examples/training/ner_example_data) to see example IOB data it can convert.

**Comment by zakarianamikaz** [comment]
yes that what i want to do move from BIO to BILUO thanks
