### ISSUE TITLE
Failure with huge texts due to unbounded memory usage by get_lca_matrix.

### ISSUE THREAD

**Issue by alvaroabascar** [explosion/spaCy#4329]
The current implementation of `get_lca_matrix` was done by myself, so apologies for the following bug: on really big texts, `get_lca_matrix` produces a matrix with size (len(doc), len(doc)). This means RAM consumption will be O(n*n) and unbounded, which can produce MemoryError (it has happened to me with an abnormal text in a production environment).

I think we should modify the function, maybe using a sparse matrix to avoid this problem.

## How to reproduce the behaviour

1. Run `top` or `htop` in a terminal.
2. Run the following python code.
```python
import spacy
nlp = spacy.load('en')
text = 'word ' * 100000
nlp(text)
```
3. See how your computer explodes.

## Your Environment
Spacy 2.0.17, linux.

**Comment by honnibal** [comment]
I think your `get_lca_matrix` function is innocent here! We're not calling it in the default pipeline are we?

The memory usage of the v2 models can be quite high on long documents, I'm still a bit puzzled as to exactly why. We've since added warnings around this, and improved the memory usage slightly. You might find a better behaviour on v2.1.

**Comment by honnibal** [comment]
I don't think it's a good priority to be honest. If the text is long you can just call the function on a sentence rather than the doc.
