### ISSUE TITLE
Incorrect lemma for plural of lens

### ISSUE THREAD

**Issue by ewaldatsensentia** [explosion/spaCy#4332]
SpaCy thinks the lemma of "lenses" is "lense" (not even a word in English.)

import spacy
nlp =  spacy.load('en_core_web_md')
doc = nlp("lenses")
print(doc[0].lemma_)
# lense

## Your Environment
spaCy version 2.1.8
Windows-10-10.0.18362-SP0
Python 3.7.3

**Comment by ines** [comment]
Thanks, looks like this was caused by an incorrect lookup lemma. Fixed this so it can be included next time we package the models.

(Btw, one quick note, also in case others come across this issue later: When testing lemmas in languages that also ship with rule-based lemmatizers, always try to process a full sentence/text to make sure that the tokens receive the correct part-of-speech tags. If you only process a single word, the model may predict a random incorrect tag, potentially causing worse lemmatization results.)
