### ISSUE TITLE
Spanish parsing lower case "no." doesn't work. "No." does for tokenizing

### ISSUE THREAD

**Issue by sontek** [explosion/spaCy#4340]
## How to reproduce the behaviour

With lower case:
```
>>> import spacy
>>> nlp = spacy.load('es')
>>> sentence = "no."
>>> doc = nlp(sentence)
>>> for token in doc:
...     print(token.text, token.lemma_, token.pos_)
...
no. no. ADJ
>>>
```

with uppercase:

```
>>> sentence = "No."
>>> doc = nlp(sentence)
>>> for token in doc:
...     print(token.text, token.lemma_, token.pos_)
...
No No ADV
. . PUNCT
```

I don't expect punctuation to ever be included in my tokens.

## Info about spaCy

* **spaCy version:** 2.1.8
* **Platform:** Darwin-18.0.0-x86_64-i386-64bit
* **Python version:** 3.6.7
* **Models:** es

* Operating System: OSX
* Python Version Used: 3.6

**Comment by adrianeboyd** [comment]
Thanks for your report!

It looks you're seeing this behavior because "no." has been added as an exception as an abbreviation:

https://github.com/explosion/spaCy/blob/9cbaf9b965619d8ae1f24e395a030ee6f98b8213/spacy/lang/es/tokenizer_exceptions.py#L53

If you want to remove this exception or you just don't want any punctuation in your tokens, you'll have to customize the tokenizer. The docs are here: https://spacy.io/usage/linguistic-features#tokenization. And here's a complete example for changing the behavior around `-` in English, just as an example of how you can modify the tokenizer: https://stackoverflow.com/a/58112065/461847

If you run into more problems, here's the best place to post language- or model-specific issues:

https://github.com/explosion/spaCy/issues/3052
