### ISSUE TITLE
Spacy Entity Rule doesn't work for cardinal (Social Security number)

### ISSUE THREAD

**Issue by sgsmittal** [explosion/spaCy#4347]
I have used Entity Rule to add new label for social security number. I even set overwrite_ents=true but it still does't recognize

I verified regular expression is correct. not sure what else I need to do I tried before="ner" but same result

text = "My name is ddex and I leave on 605 W Clinton Street. My social security 690-96-4032"

nlp = spacy.load("en_core_web_sm")

ruler = EntityRuler(nlp, overwrite_ents=True)

ruler.add_patterns([{"label": "SSN", "pattern": [{"TEXT": {"REGEX": r"\d{3}[^\w]\d{2}[^\w]\d{4}"}}]}])

nlp.add_pipe(ruler)

doc = nlp(text)

for ent in doc.ents: print("{} {}".format(ent.text, ent.label_))

**Comment by ines** [comment]
A dict in the match pattern describes **one token**. However, the string you want to match is five tokens:

```python
print([token.text for token in nlp("690-96-4032")])
# ['690', '-', '96', '-', '4032']
```

So you'll need to rewrite your pattern to match the sequence of five tokens instead of a single token. You might also want to experiment with using token features like `shape`. See the docs for details: https://spacy.io/usage/rule-based-matching
