### ISSUE TITLE
Span object can not be serialized 

### ISSUE THREAD

**Issue by moh55m55** [explosion/spaCy#4358]
Hello, 
I am using spacy to process collection of documents with adding many customized components to the pipe. But when i tried to save the Spacy documents (result) to disk, i got this. Not sure where that error comes from. any idea? 
```

~/anaconda3/envs/background/lib/python3.6/site-packages/srsly/_msgpack_api.py in msgpack_dumps(data)
     14     RETURNS (bytes): The serialized bytes.
     15     """
---> 16     return msgpack.dumps(data, use_bin_type=True)
     17 
     18 

~/anaconda3/envs/background/lib/python3.6/site-packages/srsly/msgpack/__init__.py in packb(o, **kwargs)
     38     Pack an object and return the packed bytes.
     39     """
---> 40     return Packer(**kwargs).pack(o)
     41 
     42 

_packer.pyx in srsly.msgpack._packer.Packer.pack()

_packer.pyx in srsly.msgpack._packer.Packer.pack()

_packer.pyx in srsly.msgpack._packer.Packer.pack()

_packer.pyx in srsly.msgpack._packer.Packer._pack()

_packer.pyx in srsly.msgpack._packer.Packer._pack()

_packer.pyx in srsly.msgpack._packer.Packer._pack()

_packer.pyx in srsly.msgpack._packer.Packer._pack()

TypeError: can not serialize 'spacy.tokens.span.Span' object

```

**Comment by ines** [comment]
It looks like the problem here is that you're trying to serialize extension attributes (or other data somewhere) with contents that are not JSON/msgpack-serializable (e.g. `Span` objects). It's like calling `json.dumps` on `[Span, Span, Span]`, which is not going to work.

Instead of using the spans, try storing just the character/token offsets and the label if needed. `[4, 5, "LABEL"]` can be serialized without problems, and you can always create a `Span` object for it again in your code (e.g. via a different extension attribute).
