### ISSUE TITLE
2.2 release: IS_ALPHA unsupported in Matcher

### ISSUE THREAD

**Issue by kwhumphreys** [explosion/spaCy#4363]
`IS_ALPHA` reported as unsupported by Matcher, but it's still listed at https://github.com/explosion/spaCy/blob/master/spacy/matcher/_schemas.py#L113

## How to reproduce the behaviour
```
   matcher.add("RULE1", None, [{'IS_APLHA': True, 'IS_DIGIT': False, 'IS_PUNCT': False}, {}])
  File "matcher.pyx", line 118, in spacy.matcher.matcher.Matcher.add
  File "matcher.pyx", line 619, in spacy.matcher.matcher._preprocess_pattern
  File "matcher.pyx", line 639, in spacy.matcher.matcher._get_attr_values
ValueError: [E152] The attribute IS_APLHA is not supported for token patterns. Please use the option validate=True with Matcher, PhraseMatcher, or EntityRuler for more details.
```
## Your Environment
* **spaCy version:** 2.2.0
* **Platform:** Darwin-18.7.0-x86_64-i386-64bit
* **Python version:** 3.6.5

**Comment by ines** [comment]
I was super worried here for a second – but I think you have a typo in your pattern: IS_A**PLH**A instead of IS_ALPHA. I totally didn't see it either at first 😅

So this is definitely a side-effect of the `Matcher` being stricter in v2.2 and reporting better errors (instead of just silently ignoring properties). I might add a quick note about this to the release notes.

**Comment by kwhumphreys** [comment]
thanks for reading the error message more carefully than me! :-)
