### ISSUE TITLE
An error while training the dependency parser

### ISSUE THREAD

**Issue by ryszardtuora** [explosion/spaCy#4402]
Ever since the 2.2 update I've been having trouble training parser models. Training both taggers and NER is fine, but with parsers I get an error:

<pre>Training pipeline: [&apos;parser&apos;]
Starting with blank model &apos;pl&apos;
Loading vector from model &apos;vocab_kgr_100_handpruned22&apos;
Counting training words (limit=0)

Itn  Dep Loss    UAS     LAS    Token %  CPU WPS
---  ---------  ------  ------  -------  -------
<font color="#4E9A06">✔ Saved model to output directory</font>                                                                                                             
base_parser_22/model-final
⠴ Creating best model...
Traceback (most recent call last):
  File &quot;/home/rtuora/.local/lib/python3.6/site-packages/spacy/cli/train.py&quot;, line 356, in train
    for batch in util.minibatch_by_words(train_docs, size=batch_sizes):
  File &quot;/home/rtuora/.local/lib/python3.6/site-packages/spacy/util.py&quot;, line 569, in minibatch_by_words
    doc, gold = next(items)
  File &quot;gold.pyx&quot;, line 222, in train_docs
  File &quot;gold.pyx&quot;, line 240, in iter_gold_docs
  File &quot;gold.pyx&quot;, line 258, in spacy.gold.GoldCorpus._make_docs
ValueError: need more than 0 values to unpack

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &quot;/usr/lib/python3.6/runpy.py&quot;, line 193, in _run_module_as_main
    &quot;__main__&quot;, mod_spec)
  File &quot;/usr/lib/python3.6/runpy.py&quot;, line 85, in _run_code
    exec(code, run_globals)
  File &quot;/home/rtuora/.local/lib/python3.6/site-packages/spacy/__main__.py&quot;, line 35, in &lt;module&gt;
    plac.call(commands[command], sys.argv[1:])
  File &quot;/home/rtuora/.local/lib/python3.6/site-packages/plac_core.py&quot;, line 328, in call
    cmd, result = parser.consume(arglist)
  File &quot;/home/rtuora/.local/lib/python3.6/site-packages/plac_core.py&quot;, line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File &quot;/home/rtuora/.local/lib/python3.6/site-packages/spacy/cli/train.py&quot;, line 486, in train
    best_model_path = _collate_best_model(meta, output_path, nlp.pipe_names)
  File &quot;/home/rtuora/.local/lib/python3.6/site-packages/spacy/cli/train.py&quot;, line 554, in _collate_best_model
    path2str(best_component_src / component), path2str(best_dest / component)
TypeError: unsupported operand type(s) for /: &apos;NoneType&apos; and &apos;str&apos;
</pre>

## How to reproduce the behaviour

I've converted the data with spaCy 2.2 converter. I run the train command with this input:
`nice -n 19 python3 -m spacy train pl base_parser_22 LFG22/pl_lfg-ud-train.json LFG22/pl_lfg-ud-dev.json --pipeline parser --vectors vocab_kgr_100_handpruned22 --n-iter 50 --n-early-stopping 10 -G`

I've tried this with other treebanks and the error persists. I do not recall encountering anything like it in the previous version.

## Your Environment
* **spaCy version:** 2.2.1
* **Platform:** Linux-4.15.0-58-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.8

**Comment by honnibal** [comment]
Thanks for the report, I've hit this as well.

See #4392 . We're still working on the fix, because my patch in that PR currently breaks the textcat CLI stuff added in v2.2

**Comment by adrianeboyd** [comment]
`-G` keeps the original tokenization rather than trying to align spacy's rule-based tokenization with the provided tokenization. A model trained with `-G` would not work as well with the built-in tokenization, so you'd probably want to provide the external tokenization when building a `Doc` and call the other spacy pipeline components a little differently.

If you want to build the other tokenizer into the spacy pipeline so you can just call `nlp()` as before, you would need to modify `Polish` to define a tokenizer that loads and calls the third-party tokenizer. You can look at some of the languages that require more complicated word segmentation and rely on external libraries like `ja` for an example of how this can be done.

If you think it wouldn't be too complicated to improve spacy's tokenizer, we would be happy to get contributions in this area! It looks like the Polish tokenizer has a lot of exceptions for abbreviations but otherwise isn't very different from English at this point in terms of other punctuation.
