### ISSUE TITLE
sentence segmentation at '/'

### ISSUE THREAD

**Issue by frank-lin-liu** [explosion/spaCy#4405]
## How to reproduce the behaviour

code example:

for sent in doc.sents:
    print(sent)

Sentences are split at '/' rather than '.' by default if '/' is included in a sentence.

## Your Environment

* Operating System: Windows-7-6.1.7601-SP1
* Python Version Used: 3.68
* spaCy Version Used: 2.2.1
*models: en
* Environment Information:

**Comment by svlandeg** [comment]
Hi, thanks for the report. Could you provide a little more info? Which English model are you using, and can you give some example text and the output where you notice this?

**Comment by frank-lin-liu** [comment]
Hi Sofie,

Thanks for your quick reply. I use nlp=spacy.load('en_core_web_sm'). Do you mean this English model?

A sentence I use is "

The room temperature values of conductivity, mobility and hole carrier concentration of the films annealed at 500 °C were determined as ∼5.1 × 10-4 (Ω cm)-1, 1.22 cm2/V s and 2.6 × 1015 cm-3, respectively."


The sentence is split at "/" rather than "." at the end.


Kind regards,

Xiaolei  Liu




------------------------------------------------------------------------------------------------------------------------------------------------

Sent: Wednesday, 9 October 2019 4:42 PM
To: explosion/spaCy <spaCy@noreply.github.com>
Cc: xiaolei <frank_lin_liu@hotmail.com>; Author <author@noreply.github.com>
Subject: Re: [explosion/spaCy] sentence segmentation at '/' (#4405)


Hi, thanks for the report. Could you provide a little more info? Which English model are you using, and can you give some example text and the output where you notice this?

**Comment by svlandeg** [comment]
Ok thanks! What happens behind the scenes is that this model uses the parser to understand the grammatical relations in the sentence, and does a prediction on where to best cut off the sentence. In this specific case, you're right that it does so at "/", but this is by no means the default behaviour (you can check by adding more sentences with "." and more "/" in the sentence, it usually does get it right).

Unfortunately, statistical models will always make _some_ mistakes... 

Options you could try is test with larger models such as `en_core_web_md` or `en_core_web_lg`, or otherwise use the component [`sentencizer`](https://spacy.io/api/sentencizer). The latter one is a bit more simple in design, but perhaps more suitable for your use-case.

Merging with Issue #3052.
