### ISSUE TITLE
Data preparation - how should we handle duplicate sentences?

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#4419]
Hello,
Although I can run an experiment to see which way performs better, I wanted to hear from the developers regarding if there is a recommended approach to deal with duplicate sentences in the training data.

I'm doing NER on medical reports.  After sentencizing a report, its possible that eventually I'll encounter numerous sentences that are identical to each other with the exact same string.  Even though all reports in my training set are different, there are sections of text which are identical

Currently I'm checking for these duplicate sentences (the ones without any entities) before adding them to my training set and keeping only one instance, but I wanted to know if that's ok or should I just use everything even if the training set would contain sentences that are duplicates.?

**Comment by svlandeg** [comment]
Hi,

These kind of general Machine Learning / NLP questions are probably better asked at StackOverflow, as we try to keep this issue tracker more specific to issues and bugs within spaCy.

That said, I think you should indeed run the experiments and see whether filtering has an effect. Either way I don't see how removing duplicate sentences **without** entities would make a difference. One thing to note is that, if you have duplicate sentences **with** entities across your training and evaluation set, your performance numbers may be artificially high because you're evaluating on exactly the same case you saw during training.
