### ISSUE TITLE
Adding new lemma rule to existing language

### ISSUE THREAD

**Issue by pdimiel** [explosion/spaCy#4428]
Hi everyone.

I am trying to add new lemma rules in existing languages and would like to know if this is possible.

I have tried as an example to add the rule form nouns 
windowz -> window
bedz -> bed

I looked in to how lemma_rules are declared in the language lemmatizer files and tried the following:

`nlp = spacy.load(model)`
`nlp.vocab.morphology.lemmatizer.rules["noun"].append(["z", ""])`

Running some tests I noticed that when the model is an english model, the rule does not work for cases where the actual lemma exists in the language vocabulary like:
"I have broken some windowz"  
windowz tag=NN, lemma=windowz

but works for cases where the resulting lemma does not exists in the language vocabulary like:
"I have broken some mmmz"  
mmmz tag=NNS, lemma=mmm

And switching to the Greek model but using an english word works (as long as the pos tag is set correctly):

"Έσπασα κάποια windowz"
windowz tag=NOUN, lemma=window

Could you tell me if I am using the correct approach to add a lemmatizer rule?

If yes, why is the rule activated only in some cases?

**Comment by ines** [comment]
v2.2 now uses the new `Lookups` API to store lookup tables and dictionaries, such as the lemmatization rules, that allows convenient access via the shared vocab and modifications at runtime.

I've shared an example here: https://github.com/explosion/spaCy/issues/4426#issuecomment-540621940 In order to modify the `lemma_rules` at runtime, you can call `nlp.vocab.lookups.get_table("lemma_rules")`, which returns a dict-like table that you can write to. 

(If you're using a version lower than v2.2, overwriting rules at runtime by writing to the lemmatizer attributes may produce unintended results, since that type of usage wasn't officially supported yet.)
