### ISSUE TITLE
spaCy existing model is forgetting the old entity types after training

### ISSUE THREAD

**Issue by georgenv** [explosion/spaCy#4436]
Hi, 

I'm trying to train an existing NER model for a new set of entities, but after training it is forgetting the old entity types and remembering only the new ones. Anyone could help me, please?

I have followed the tutorial from spaCy documentation: https://spacy.io/usage/training#ner

Setup:
Operating System: Ubuntu 18.04
Python Version Used: 3.7.4
spaCy Version Used: 2.2.1

Regards,
George

**Comment by svlandeg** [comment]
If you are retraining your NER model on a new set of entities, you have to ensure that the old ones are not forgotten by feeding the model also examples from your old types during the retraining. Otherwise, the model will be automatically tune itself to the new types only. This is refered to as the  “catastrophic forgetting” problem and you can read more about it here: https://explosion.ai/blog/pseudo-rehearsal-catastrophic-forgetting.
