### ISSUE TITLE
Serialize PhraseMatcher for faster performance

### ISSUE THREAD

**Issue by tnmcneil** [explosion/spaCy#4445]
Not sure if this is something that exists already or if this is a request but -
The PhraseMatcher is obviously very fast at finding matches in a document which is great. However loading up the matcher takes quite a bit of time.  since I am loading up the same patterns every time I am wondering if there is a way to serialize the matcher or save it after loading it once so that reloading is faster. I am creating the phrasematcher from a gazetteer with ~26k lines and it takes ~3 minutes to do so.

Operating System: Mac OS
Python Version Used: 3.5.1
spaCy Version Used: 2.1.6

**Comment by adrianeboyd** [comment]
You should be able to pickle a PhraseMatcher. I'm not exactly sure how much faster it will be since unpickling basically starts again from the stored docs, but at least you shouldn't have to rerun the whole NLP pipeline for each phrase.

In 2.1 there is a bug where the `attr` setting is lost on pickling, so it won't work correctly for anything other than "ORTH". This is fixed in 2.2, which has a completely different PhraseMatcher, which may also have slightly different behavior in terms of speed of unpickling vs. recreating.
