### ISSUE TITLE
Tokenizer: add_special_case not working when special token not separated by whitespace

### ISSUE THREAD

**Issue by nsaef** [explosion/spaCy#4451]
Hi! I'm trying to add special cases to the tokenizer, but they're only applied if the special tokens are separated by whitespace.

## Code example:
```
import spacy
from spacy.symbols import ORTH, LEMMA, POS, DEP

nlp = spacy.load("en_core_web_sm")

word = "<TITLE>"
rule = [{ORTH: word}]
nlp.tokenizer.add_special_case(word, rule)

word = "</TITLE>"
rule = [{ORTH: word}]
nlp.tokenizer.add_special_case(word, rule)

result = [t.text for t in nlp("<TITLE>Hello World</TITLE>")]
```
Expected result: `['<TITLE>', 'Hello', 'World', '</TITLE>']`
Actual result: `['<', 'TITLE', '>', 'Hello', 'World</TITLE', '>']`

This, however, works:

```
result = [t.text for t in nlp("<TITLE> Hello World </TITLE>")]
>> ['<TITLE>', 'Hello', 'World', '<TITLE>']
```

This bug seems to have come up in the past already (#1061) and crept back in? At least the linked issue is what pointed me in the right direction.

## Environment
* **spaCy version:** 2.2.1
* **Platform:** Windows-10-10.0.17763-SP0
* **Python version:** 3.7.4
* **Models:** en

**Comment by svlandeg** [comment]
Hi @nsaef, thanks for the report!

I don't think Issue #1061 crept back in, because there is a regression test in place (which isn't failing), and also that issue is more about trailing punctuation such as `!` that should not interfer with the special case (compare e.g. the string `<TITLE>!`, this works fine with your pattern).

In your specific use-case, the substring you want to match (`<TITLE>`) is actually part of a larger token, because there is (as you pointed out) no whitespace between that match and the other alphanumeric characters. In this case, I don't think the special tokenizer case will work as you'd intend it to. From the [docs](https://spacy.io/usage/linguistic-features#special-cases): 

> The special case doesn’t have to match an entire whitespace-delimited substring. The tokenizer will incrementally split off punctuation, and keep looking up the remaining substring.

I'm not 100% certain - but I think what you're seeing is a feature, not a bug 😬

**Comment by adrianeboyd** [comment]
The default tokenizer is not going to split `<TITLE>Hello` into `'<TITLE>', 'Hello'` so the special case isn't able to match, since special cases can only refer to whole tokens, not partial tokens. It's not just whitespace, though, since the tokenizer can handle prefixes and suffixes like `"` and `!` to some extent.

However, since `>` and `</` can be infixes, I don't think there's an easy way to do this with spacy currently. You could potentially define the whole tags as prefixes and suffixes, but I think you're still going to have problems with cases like `<TAG>a</TAG><TAG2>b</TAG2>`, so I wouldn't really recommend this.

This should get easier when this PR I've been working on is merged: https://github.com/explosion/spaCy/pull/4259 (You would define `'<', '>', '</'` as prefixes/infixes/suffixes and then for your limited tag vocabulary, use special cases to recombine `'<' 'TAG' '>'` into one token. Even then, you would need to train your own models because the provided models are only trained on plain text and won't handle these cases well.)

**Comment by nsaef** [comment]
Thanks to both of you! For the moment, I settled on introducing whitespaces via regex so the special tokenization rule is applied afterwards. I'll keep in mind the prefix/infix/suffix solution if that approach doesn't work anymore.
