### ISSUE TITLE
docs_to_json output

### ISSUE THREAD

**Issue by akornilo** [explosion/spaCy#4452]
The output of the `spacy.gold.docs_to_json` format is inconsistent with the function description. The function says that it `RETURNS (list): The data in spaCy's JSON format.`. In reality, the function combines all the documents into one big json. 

Either the description or the function itself needs to be adjusted. I think that it should do the later - because that would be in line with the input for the training functions. I am not sure how the ids should be handled.

## Which page or section is this issue related to?
https://github.com/explosion/spaCy/blob/master/spacy/gold.pyx#L740

**Comment by svlandeg** [comment]
Thanks for the report, good catch! 

It used to be so that the output was a list, but this was rewritten, see [here](https://github.com/explosion/spaCy/pull/3419/files#diff-74efcfe2a206cfbaa90445ffc47c4a61). So the best fix is probably to adjust the inline documentation you referred to as well as the [API documentation](https://github.com/explosion/spaCy/blob/master/website/docs/api/goldparse.md#golddocs_to_json-docs_to_json-tagfunction). Doyou want to go ahead and create a PR for this doc change?

**Comment by akornilo** [comment]
I can make a PR .. but I still find it confusing - whats the reasoning behind storing multiple Docs as a single "doc"?

**Comment by adrianeboyd** [comment]
The docs should definitely be clarified here, but in effect it's more of a naming issue than anything: currently the things called "paragraphs" in the training format are treated as documents during training.

I thought this was confusing, too. Some relevant background is here, where I made a similar suggestion:

https://github.com/explosion/spaCy/pull/4013

**Comment by svlandeg** [comment]
Fixed by  #4456
