### ISSUE TITLE
Entity Extraction with Knowledge Bases and RDF triples (Wikidata, Freebase)

### ISSUE THREAD

**Issue by AmoghM** [explosion/spaCy#4460]
Spacy already has a NER but it doesn't link with KBs due to which the NER looks erroneous. NER are also restricted with generic classes like PERSON, ORG, LOCATION. An extension with wiki data, freebase and DBPedia KBs can help in a natural extension of them.
Current NER result:
Input: `I like watching Harry Potter`
Output: `Harry Potter (PERSON)`

Proposed NER result:
Output: `Harry Potter (book/movie)`

P.S: Examples like `I like watching Netlfix` find Netflix as `PERSON` tag. It would have been disambiguated correctly with the use mentioned KBs.

Therefore, I think Spacy should have this feature to be superior in entity extractions.

**Comment by svlandeg** [comment]
We have started working on a Named Entity Linking algorithm a few months ago, the infrastructure is already there but we're still improving the models & data (see https://spacy.io/usage/linguistic-features#entity-linking).

Currently, it's set up so that NER happens before NEL, but I definitely see your point that information could also flow from the NEL step back to NER.

**Comment by AmoghM** [comment]
Thanks for pointing me to the entity linking module. I happened to find this https://github.com/explosion/spaCy/tree/master/bin/wiki_entity_linking which looks very promising.
Generally, entity extraction is followed by entity linking. Should we keep the same pipeline but add a disambiguation module as well? Given the context and KB entity, we resolve the NER result.
@svlandeg What do you think?

**Comment by svlandeg** [comment]
That's how it's set up: the NEL algorithm does disambiguation based on the information it gets from the NER algo, the context and the candidates in the KB.
