### ISSUE TITLE
Sentence boundary detection is not trained for Vietnamese Universal Dependencies

### ISSUE THREAD

**Issue by trungtv** [explosion/spaCy#4477]
I have developed a spacy model for vietnamese language ([vi_spacy](https://github.com/trungtv/vi_spacy)) in which the dependency parser is trained with [data in the following format](https://raw.githubusercontent.com/trungtv/vi_spacy/master/language_data/vi_vtb-ud-test.json). 
I observed that sentence boundary detection is not available as It is said to be within the dependency parser. 
Could you have any recommendation for my problem?
## How to reproduce the behaviour

Install [vi_spacy](https://github.com/trungtv/vi_spacy)
```
import spacy
nlp = spacy.load('vi_spacy_model')
doc = nlp('Cộng đồng xử lý ngôn ngữ tự nhiên. Trời đẹp quá.')
for token in doc:
    print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_,
            token.shape_, token.is_alpha, token.is_stop, token.is_sent_start)
=== output ===
Cộng_đồng Cộng_đồng X N nsubj xxxxxxxxx False False True
xử_lý xử_lý X V ROOT xxxxx False True None
ngôn_ngữ ngôn_ngữ X N obj xxxxxxxx False False None
tự_nhiên tự_nhiên X A amod xxxxxxxx False False None
. . X . punct . False False None
Trời Trời X N nsubj xxxx True False None
đẹp đẹp X A parataxis xxx True False None
quá quá X R advmod xxx True True None
. . X . punct . False False None
```
## Your Environment

* Operating System: Mac OS
* Python Version Used: 3.6
* spaCy Version Used:  2.1.4
* Environment Information: Anaconda

**Comment by adrianeboyd** [comment]
When you convert the UD data, use the option `-n` with `spacy convert` with something like `-n 10` so that every 10 sentences are joined together into a paragraph. If the parser only sees single sentences in each paragraph during training, it doesn't learn how to split sentences.

This has come up several times recently and I wonder whether we should change the default value for `spacy convert` or let the individual converters set the default value if it's not provided as an option to the main script. On the one hand, a value like `10` is kind of arbitrary and some users might be surprised if this is the default, but on the other hand, this is a non-obvious problem for users that we'd like to avoid.

**Comment by ines** [comment]
> I wonder whether we should change the default value for spacy convert or let the individual converters set the default value if it's not provided as an option to the main script.

Yeah, or maybe we could at least show a warning? I also noticed that the [current docs](https://spacy.io/api/cli#convert) for the `--n-sents` option aren't very clear and potentially confusing, so adding a sentence there that explains what the number actually means might help, too.
