### ISSUE TITLE
I need a MultiLevelTextCategorizer.

### ISSUE THREAD

**Issue by Astral1020** [explosion/spaCy#4515]
text = "Dumplings are delicious."
    nlp.load("xxx")
    doc = nlp(text)
    -----------------
    doc.cats = {
                    "Shopping": {"score": 0.01},
                    "Food": {"score":0.99, "child": {"Chinese Food": {"score": 0.99}, "British Cuisine": {"score": 0.01}}
                }
What I am doing:
    Add multiple textcat pipelines first. (https://github.com/Astral1020/MultiLevelTextCategorizer)
Issue:
    If I call spacy.load(), I got an exception:
    KeyError: "[E002] Can't find factory for 'ROOT'. This usually happens when spaCy calls `nlp.create_pipe` with a component name that's not built in - for example, when constructing the pipeline from a model's meta.json. If you're using a custom component, you can write to `Language.factories['ROOT']` or remove it from the model meta and add it via `nlp.add_pipe` instead."

**Comment by adrianeboyd** [comment]
I'm not sure that spacy is currently the best choice for implementing hierarchical text classification and it might be worthwhile to look at other libraries. Currently `doc.cats` only supports a simple 1-level dictionary of labels/scores.

I think that you can currently add multiple `textcat` models to a pipeline as long as they don't try to write to the same labels. (It shouldn't crash, but labels might get overwritten otherwise.) There is some work in progress (see #4514) to make it possible to handle saving/loading and other aspects of more configurable pipelines, so the overall task might not be 100% straightforward at this point.
