### ISSUE TITLE
NER for the Beatles

### ISSUE THREAD

**Issue by joagr** [explosion/spaCy#452]
For this sentence from Wikipedia: "Born and raised in Liverpool, Lennon became involved in the skiffle craze as a teenager; his first band, the Quarrymen, evolved into the Beatles in 1960."
The named entity list has these: Liverpool, Lennon, first, Quarrymen, and 1960.
But Beatles is not there. The POS for Beatles is PROPN, so it seems surprising that it's not recognized as a named entity.
Is there anything in Spacy I can tweak for this?

**Comment by jgontrum** [comment]
I have struggled with similar NER problems in the last week.
For me, the issues mostly have been tagging capitalised words as PERSON or ORGANISATION, while not all persons at the beginning of the sentence are recognised. And sometimes the NER tag just does not make sense at all.

My advice for now: If you want a reliable named entity recogniser, don't use spaCy.

**Comment by syllog1sm** [comment]
@joagr The `Matcher` class provides rule-based NER.

```python
import spacy
from spacy.symbols import *

nlp = spacy.load('en')

beatles_token_pattern = {ORTH: 'Beatles', POS: PROPN}
beatles_phrase_pattern = [beatles_token_pattern] # List here to support multi-word matches
beatles_pattern [beatles_phrase_pattern] # Support multiple patterns for same entity
nlp.matcher.add('Beatles_(band)', 'ORG', {}, beatles_pattern)
```

Currently the code does less than the API suggests: the entity key is not really used, and there's space to attach attributes (the `{}` arg) in the API, but this isn't taken advantage of in the current implementation.

@jgontrum There have been a lot of delays in my plans, due to a variety of factors. I hope to be able to say more about this within the next few weeks.

**Comment by jgontrum** [comment]
@syllog1sm Thanks! I can collect and share some examples where the NER does not work correctly, if you like.
