### ISSUE TITLE
[conllu converter] Support raw_text field

### ISSUE THREAD

**Issue by tamuhey** [explosion/spaCy#4523]
`spacy convert` miss the information of raw text, it is often shown `# text = ` comment line in conllu format. (e.g. https://github.com/UniversalDependencies/UD_English-EWT/blob/master/en_ewt-ud-dev.conllu)

I found the unused variable `raw_text` in the below line, but why isn't it used?
https://github.com/explosion/spaCy/blob/d2da1171140c5afdb770d7d5ec610dd9aea42476/spacy/cli/converters/conllu2json.py#L25

**Comment by adrianeboyd** [comment]
There's no reason it couldn't be incorporated into the converter. I think the converter has just focused on the required non-comment fields so far.

It would also potentially be useful to use the `newpar` comments to group sentences into paragraphs, but I'm not sure they're used frequently or consistently enough for it to be a worthwhile extension.

**Comment by tamuhey** [comment]
It is important for non-spaced languages (e.g. Chinese, Japanese) to keep raw text information.
I think the converter should be able to handle this, or it should be noted that the space information is lost when processing these languages.

**Comment by adrianeboyd** [comment]
I know that the basic handling for spaced languages is through `SpaceAfter=No`. What is the equivalent that would be necessary for non-spaced languages? What information do you need to store to know how to recreate a (near-)equivalent to the original text?

**Comment by tamuhey** [comment]
`SpaceAfter=No` is also used in Japanese.
https://github.com/UniversalDependencies/UD_Japanese-GSD/blob/770731d01a6b412076ae0463de628b3b0a7526cc/ja_gsd-ud-dev.conllu#L3

But this filed is assumed to store NER labels, and check it in the following line.
https://github.com/explosion/spaCy/blob/d2da1171140c5afdb770d7d5ec610dd9aea42476/spacy/cli/converters/conllu2json.py#L28

**Comment by adrianeboyd** [comment]
The comment is incorrect in that function, since it's actually used to check column 6. (And I'm not even sure which CoNLL format has NER in either column 6 or 10 to be honest. There are so many variants. We should probably mainly try to support CoNLL-U.)

Is `SpaceAfter` enough information to basically reconstruct a Japanese text for realistic tokenization/segmentation purposes or not? I am not surprised that `SpaceAfter=Yes` is very rare, of course, but is there other information that is missing if you only rely on `SpaceAfter`?

Chinese seems to have `SpaceAfter=No` in all the UD corpora, so I'm trying to figure out what information is in the raw text that is not in `"".join(tokens)`. (I'm trying to train a Chinese model and I'm not sure if I'm losing anything major if I don't maintain the "raw" field.)

**Comment by tamuhey** [comment]
> Is SpaceAfter enough information to basically reconstruct a Japanese text for realistic tokenization/segmentation purposes or not?
Yes. 

> I am not surprised that SpaceAfter=Yes is very rare, of course, but is there other information that is missing if you only rely on SpaceAfter?
If `# text = ...` filed exists, it is the information to reconstruct text, but there is no other. 
I think almost all tokens in Japanese have `SpaceAfter=No`, too

**Comment by tamuhey** [comment]
I think supporting this can be too complicated, so spaCy should provide APIs to make it easy to customize `convert` function.

**Comment by adrianeboyd** [comment]
I was trying to think about whether it makes sense to support `SpaceAfter=No` instead of `#text` since I think that might be easier to parse.

The CLI options are translated fairly directly into the converter function arguments, so it shouldn't be too hard to write/adapt a converter, either integrated into the CLI or called directly. (And I think a general-purpose API for parsing various linguistic data formats would be pretty complicated in the end.)

**Comment by svlandeg** [comment]
Correct me if I'm wrong - but I think this got addressed by PR #4715. Tentavily closing :-)
