### ISSUE TITLE
char_span not returning spans in some cases

### ISSUE THREAD

**Issue by omri374** [explosion/spaCy#4531]
## How to reproduce the behaviour
Weird behavior when calling char_span to create JSON for training. 

When the entity is 'Graematter Inc':

```
text = 'He offered to map it for Graematter Inc.'
entities =[(25, 39, 'ORG')]
import spacy
from spacy.lang.en import English
nlp = English()
doc = nlp(text)
[doc.char_span(start_idx, end_idx, label=label) for start_idx, end_idx, label in entities]
# returns [None]
```

Whereas when the entity is 'Graematter Int':

```
text = 'He offered to map it for Graematter Int.'
entities =[(25, 39, 'ORG')]
from spacy.lang.en import English
nlp = English()
doc = nlp(text)
[doc.char_span(start_idx, end_idx, label=label) for start_idx, end_idx, label in entities]
# returns [Graematter Int]
```

I get different results.
I'm not sure what's causing the difference here. Note that the period at the end of the sentence is not a part of the entity.

## Info about spaCy

* **spaCy version:** 2.2.1
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.4

**Comment by ines** [comment]
The `Doc.char_span` method returns `None` if the character span doesn't map to valid tokens. [See here](https://spacy.io/api/doc#char_span):

> Create a Span object from the slice doc.text[start:end]. Returns None if the character indices don’t map to a valid span.

In your example, the difference is the tokenization: "Inc." is a tokenizer exception, so it doesn't get split into two tokens. This typically makes sense, because the `.` is part of the abbreviation. "Int." on the other hand gets split as `["Int", "."]`. So "Graematter Int" is a valid sequence of tokens, whereas "Graematter Inc" isn't (because "Inc" isn't its own token, it's the full "Inc."). So you can either change the tokenization rules or adjust your character offset annotations.
