### ISSUE TITLE
Tokenizer fails to split period following diacritics

### ISSUE THREAD

**Issue by jeanm** [explosion/spaCy#4559]
While playing with the Italian tokeniser, I have noticed the following odd behaviours:
1. The use of Unicode combining diacritical marks throws off the tokeniser. Consider the following example, which is handled *correctly*:
   ```python
   from spacy.lang.it import Italian
   nlp = Italian()
   nlp.add_pipe(nlp.create_pipe('sentencizer'))

   # ['LATIN SMALL LETTER E WITH GRAVE', 'FULL STOP']
   original = "è."
   list(next(nlp(original).sents))  # Yields: [è, .]  – OK!
   ```

   Now if I apply NFD normalisation to my original string, the string still _looks_ the same (`è.`), but it's actually made up of three characters: <code>E + ` + .</code>. This breaks the tokeniser:
   ```python
   import unicodedata
   
   # ['LATIN SMALL LETTER E', 'COMBINING GRAVE ACCENT', 'FULL STOP']
   normalised = unicodedata.normalize("NFD", original)
   list(next(nlp(normalised).sents))  # Yields: [è.]  – WRONG!
   ```

   I haven't dug into the code, but I imagine what might be happening is that `COMBINING GRAVE ACCENT` does not count as a word character, which must end up confusing some tokenisation rule.
2. Some letters with diacritics are just never split up from the punctuation that follows:
    ```python
    # OK
    list(next(nlp("è.").sents))  # [è, .]
    list(next(nlp("â.").sents))  # [â, .]
    list(next(nlp("æ.").sents))  # [æ, .]
    list(next(nlp("ç.").sents))  # [ç, .]
    list(next(nlp("ñ.").sents))  # [ñ, .]

    # WRONG!
    list(next(nlp("ä.").sents))  # [ä.]
    list(next(nlp("È.").sents))  # [È.]
    list(next(nlp("Ó.").sents))  # [Ó.]
    list(next(nlp("Â.").sents))  # [Â.]
    list(next(nlp("Æ.").sents))  # [Æ.]
    list(next(nlp("Ç.").sents))  # [Ç.]
    list(next(nlp("Ñ.").sents))  # [Ñ.]
    list(next(nlp("Ä.").sents))  # [Ä.]
    ```

    Note that none of these examples here in point 2 are using combining diacritics, i.e. `len(_) == 2` for all strings above. Again, I haven't delved into the code but I imagine the problem is that certain characters aren't being recognised as letters.

## Info about spaCy

* **spaCy version:** 2.2.2.dev4
* **Platform:** Darwin-18.7.0-x86_64-i386-64bit
* **Python version:** 3.7.3

**Comment by svlandeg** [comment]
Thanks for the report!

>     I imagine the problem is that certain characters aren't being recognised as letters.

You're right that the tokenizer is not splitting off the dot in some of these cases. For the lowercase symbols, there are actually specifically tokenizer exceptions that prevent the tokenizer from doing so, including a specific case for `ä`, see [here](https://github.com/explosion/spaCy/blob/master/spacy/lang/tokenizer_exceptions.py#L98). 

For **single capital letters**, the default is not to split the dot off, because they could be tokens like `O. J. Simpson` where you want to keep the abbreviations together. What you'll see is that it does it "correctly" for longer strings like `ÄÓ`. So it's not the diacritics that are the problem. This is actually default tokenization behaviour.

If you want to work around this, you can overwrite the `tokenizer_exceptions` for your use-case, and you could also adjust the [suffix rules](https://github.com/explosion/spaCy/blob/master/spacy/lang/punctuation.py#L19) - but beware that this may break other examples in your document. It's virtually impossible to get this right 100% of the time.

For more information on how these rules work in spaCy, see [here](https://spacy.io/usage/spacy-101#annotations-token) and [here](https://spacy.io/usage/linguistic-features#tokenization).
