### ISSUE TITLE
nb: missing morph_rules and reproducability of official model

### ISSUE THREAD

**Issue by jarib** [explosion/spaCy#4585]
Great to see `nb_core_news_sm` released! 

I would really like a model with word vectors, so I've picked up my work from #3082 (and https://github.com/jarib/spacy-nb) to build Norwegian Bokmål models of various sizes against spacy 2.2.2. 

I've noticed two things:

#### Reproducability

The released `nb_core_news_sm` model gives much better accuracy scores than the `sm` model I build myself from what is presumably the same data source. I haven't found any code that shows how you preprocess the data from [NorNE](https://github.com/lgtoslo/norne). Is it proprietary? Do you use the train/dev/test split that they provide? How many iterations do you run?

|  		| jarib/spacy-nb sm | nb_core_news_sm |
| -- | -- | -- |
| TOK       | 100.00       		| 100.00 		  |
| POS       | 94.03        		| 95.70           |
| UAS       | 88.51        		| 89.31           |
| LAS       | 85.37        		| 86.72           |
| NER P     | 71.90        		| 83.69          |
| NER R     | 70.53        		| 83.45           |
| NER F     | 71.21        		| 83.57           |

#### Outdated morph_rules

The NorNE data has been updated (improved) since I last used the data. It now uses 30 POS tags that are missing from [`nb/morph_rules.py`](https://github.com/explosion/spaCy/blob/3ec231f7e14422de3ba2efafe363cde37a45215e/spacy/lang/nb/morph_rules.py). You can see the output of `spacy debug-data` [here](https://gist.github.com/jarib/9e808042f6a044075606713d52aab282). If I run `debug-data` against the older version of NorNE it has no errors.

What would be the best approach to fix this? Looking at `nb/morph_rules.py` it seems to do things differently from other languages (e.g. `en`).

**Comment by adrianeboyd** [comment]
Our models are using the older version, which looks like UD v1 instead of UD v2. I'm not sure what additional modifications were made to NorNE related to this comment:

https://github.com/explosion/spaCy/blob/828ef27a3206a969a56a6dbe47fa38d6e9a1a621/spacy/lang/nb/tag_map.py#L8-L13

As far as I'm aware none of the data is proprietary, so I'd be happy to send you the exact datasets, but I need to figure out a good place to upload them. Unfortunately spacy's internal format makes it hard to keep track of the alignment to the original corpus, so I don't have as much metadata there as I'd like.

The only custom internal change was to group sentences in paragraphs with 1-10 sentences each (randomly chosen) so that the parser would learn to detect sentence boundaries. (In other corpora we've typically just grouped 10 sentences into each paragraph. I haven't found the time yet, but I'd like to do experiments to see if varying the length makes much of a difference once you go beyond one sentence per paragraph.)

We use `spacy train` to train models internally and I think the non-default parameters for this model were:

```
spacy train -ovl 0.3 -n 30
```

It was pointed out in #4417 yesterday that NorNE does actually include Nynorsk NER, so it could make sense to support both Norwegian Bokmål and Norwegian Nynorsk in a future version of spacy using the updated NorNE data. I'd like to track down the details related to the tag_map comment before considering updating our internal data.

**Comment by jarib** [comment]
Thanks for looking into this! 

My script to convert the NorNE data is [here](https://github.com/jarib/spacy-nb/blob/master/tools/download.norne.sh). I use `spacy convert -n 10` to get sentence segmentation working. I'm curious why you chose to group them randomly specifically for `nb`. If that has proven useful it should probably be an option in `spacy convert` as well?

The original Norwegian Dependency Treebank data (also part of the NorNE repo) is grouped into documents, but seems like the boundaries are lost in the translation to UD. I'm not sure if it's possible to retain that information in the UD format. If you know of a language that does this, let me know and we can look into it.

I'll retry my traning with `-ovl 0.3`. Great if you want to share the exact datasets so that I can try them as well.

**Comment by jarib** [comment]
`-ovl 0.3` made my scores worse 🤷‍♂ 

| |  `-ovl 0.3 -n 30` | `-n 30` | 
| -- | -- | -- |
| Time      | 4.82 s | 4.50 s | 
| Words     | 29779  | 29779 | 
| Words/s   | 6172   | 6622 | 
| TOK       | 100.00 | 100.00 | 
| POS       | 93.80  | 94.09 | 
| UAS       | 88.47  | 88.73 | 
| LAS       | 85.40  | 85.58 |
| NER P     | 71.18  | 71.63 |
| NER R     | 66.67  | 69.44 |
| NER F     | 68.85  | 70.52 | 
| Textcat   | 0.00   | 0.00 |

**Comment by adrianeboyd** [comment]
I was hoping to actually see whether varying paragraph length made a difference before adding it to `spacy convert`, but if it turns out to help, it could definitely end up as an option.

I would expect `-ovl 0.3` to make the scores slightly worse on extremely similar test data, but better on noisier data from other genres, especially informal texts without standard capitalization.

So far, `-ovl` swaps some punctuation like ASCII vs. unicode symbols (quotes were a problem for models with training data from one normalized corpus that only used one type of quote symbol) and makes some percentage of sentences lowercase.

In general, the data augmentation settings are pretty new and we're still experimenting. For a few languages where we can find additional / dissimilar test data, we have some unit tests to make sure the changes don't decrease performance, but it's hard to find enough test data, especially data that can be used for commercial purposes.

**Comment by jarib** [comment]
Just to prevent this issue from auto-closing, it's still not clear to me:

a. How you achieve your scores for the official `sm` model. Using the suggested settings does not help me. Did you re-split data? 

b. What would be the correct fix for `morph_rules` to avoid the POS errors https://gist.github.com/jarib/9e808042f6a044075606713d52aab282 with the latest NorNE data.

**Comment by adrianeboyd** [comment]
a. Sorry, for not getting back to you! I'll send you a link with the data we're currently using. There can be minor differences in performance when training on different machines, so it won't necessarily be 100% identical, but it should be very close if you use the `spacy train` command above.

b. You need to add the missing tags to `spacy/lang/nb/tag_map.py`.

**Comment by jarib** [comment]
Thanks! I'll try both.

**Comment by jarib** [comment]
Indeed, the data you sent me brings me close:

```
Time      4.51 s
Words     38512
Words/s   8537
TOK       100.00
POS       95.65
UAS       89.52
LAS       86.82
NER P     84.15
NER R     83.82
NER F     83.99
Textcat   0.00```

I've also [created a PR](https://github.com/explosion/spaCy/pull/4711) with the `tag_map` update. Seems like there should be a more clever way to do that, though.

Now both the data you sent me and the latest NorNE data passes the `spacy debug-data` test.
