### ISSUE TITLE
different model declaration sequences give different results

### ISSUE THREAD

**Issue by Khanifsaleh** [explosion/spaCy#4595]
I make class object that load ner spacy model and I have three NER Spacy models in various languages ​​(lang A, B, C). When I call the class with this sequences:

`obj_ner = {"A": class_obj(lang="A"), "B":class_obj(lang="B"), "C": class_obj(lang="C")}`
and predict ner labels for A language sentence, it give different results when I call the class with another sequences:
 
`obj_ner = {"B":class_obj(lang="B"), "C": class_obj(lang="C"), "A": class_obj(lang="A")}`

## Your Environment
* Operating System: Ubuntu 18.04
* Python Version Used: 3.7
* spaCy Version Used: 2.2.1

**Comment by adrianeboyd** [comment]
If you run two NER models on the same text, the second model will not overwrite any entities added by the first model, so maybe that is the source of the differences?

If that's not the problem you're having, could you try to provide a minimal example with an example text and actual vs. desired output to show what's going on? If you have custom models or confidential data, you could create an example using NER models from languages supported by spacy.

**Comment by Khanifsaleh** [comment]
So sorry for slowly resp, 
Previously, I used embedding from fasttext [https://fasttext.cc/docs/en/crawl-vectors.html] which I had pruned into 10000. But, spacy 2.2.1 couldn't prune a vector, there an error. So, I used spaCy 2.1.4 to prune the fasttext. Then train it using spaCy 2.2.1.

No, I didn't run many models for the same text. Each text has a language attribute that corresponds to the model.  

The following is an example output for language A:
Text : Agus Yatim, 37, warga binaan di Lapas Kelas IIB Singaraja, kedapatan melakukan aksi percobaan bunuh diri di dalam lapas, Jumat (1/11) pukul 09.30 Wita.

Prediction when model A is declared at the beginning:
[('GPE', ['Yatim']), ('FACILITY', ['Lapas Kelas', 'lapas']), ('DATE', ['Jumat']), ('CARDINAL', ['1/11']), ('TIME', ['pukul 09.30 Wita'])]

Prediction when model A is declared at the end:
[('PERSON', ['Agus Yatim']), ('FACILITY', ['Lapas Kelas IIB Singaraja', 'lapas']), ('DATE', ['Jumat (1/11)']), ('TIME', ['pukul 09.30 Wita'])]

**Comment by svlandeg** [comment]
Hi @Khanifsaleh. That does look like your models are predicting conflicting annotations for the same set of tokens, e.g. `Yatim` vs. `Agus Yatim`. As @adrianeboyd mentioned, the order of your NER models matters because the second won't overwrite the first, which is why you're seeing different results.

Having multiple components with the same name/behaviour in the pipeline is not supported out-of-the-box right now, because it's not always easy to decide what's the best way to resolve these kind of "conflicts".

Merging this topic with the open Issue #2920, where strategies for having multiple NER's in the pipeline are discussed in more detail.
