### ISSUE TITLE
SpaCy should warn when pipelines aren't enabled

### ISSUE THREAD

**Issue by erip** [explosion/spaCy#4625]
## How to reproduce the behaviour

```python
import random

from spacy.gold import GoldParse

random.seed(42)

# Ensures that only models without a pipeline pass to the training logic
assert len(list(nlp.pipeline)) == 0

optimizer = nlp.begin_training()
for itn in range(100):
    random.shuffle(train_data)
    docs = []
    golds = []
    for raw_text, tokenizations, pos, ner in train_data:
        doc = nlp.make_doc(raw_text)
        gold = GoldParse(doc, words=tokenizations, tags=pos, entities=ner)
        docs.append(doc)
        golds.append(gold)
    nlp.update(docs, golds, drop=0.5, sgd=optimizer)
```

This will train "completely", but won't yield a usable model because the tagging and entity recognizer pipelines haven't been added. It may be wise to log a warning if a kwarg corresponding to a non-existent component is passed  to `nlp.update` via `GoldParse`.

## Info about spaCy

* **spaCy version:** 2.2.2
* **Platform:** Darwin-18.7.0-x86_64-i386-64bit
* **Python version:** 3.6.7

**Comment by svlandeg** [comment]
Hi @erip , I'm not sure I fully understand your point, sorry. Also the code snippet is not functional, as `nlp` is not defined in it.

Do you mean that `nlp.update()` should throw a warning when you pass gold annotations that include for instance pos tags, but the `tagger` is not actually part of the pipeline?

**Comment by erip** [comment]
Right.

**Comment by svlandeg** [comment]
Ok, I see your point. So you would want a warning mechanism against a programming error when you're running `update` on an `nlp` pipeline that hasn't got the correct components. It wouldn't be extremely trivial because you'd need to inspect each component that is in the pipeline and what kind of data they consume. In theory this is possible with the new component decorators (cf Issue #3943). But you could easily have two different components that require the same type of training input data, and then you could never detect automatically if the second one is missing. But it should be possible to catch straightforward mistakes such as an empty pipeline that gets trained ...
