### ISSUE TITLE
statistical nlp support

### ISSUE THREAD

**Issue by choltz95** [explosion/spaCy#463]
Are there any plans to support statistical approaches to NLP?

machine translation
n-gram models
stochastic grammars & parsing
word senses

**Comment by syllog1sm** [comment]
I'm not sure what you mean. spaCy's parser is statistical, in the sense that it's backed by a machine learning model. You can't get a probability distribution over hypothesised parses at the moment, though.

**Comment by choltz95** [comment]
For example, NLTK has implementations of ibm models 1-5 for word alignment since 2015 and I guess there will be support for topic modeling soon, but is quite slow. I was wondering if spaCy has any plans to expand functionality beyond tokenization, parsing and pos tagging.

**Comment by syllog1sm** [comment]
The philosophy has basically been to provide things that have a high degree of synergy from being in the same library, either because that lets you manage all the different levels of representation together, or because the statistical models are interdependent.

For something like IBM models 1-5, I think it's more sensible for there to be a distinct library, that focusses on word alignment. When I want to train topic models, I use Gensim.

**Comment by choltz95** [comment]
Okay. Thanks for the note.
