### ISSUE TITLE
missing space treatment around punctuation & digits

### ISSUE THREAD

**Issue by DSLituiev** [explosion/spaCy#4634]
## Feature description
I am trying to clean / normalize a text with potential missing spaces around punctuation, like:
`word,digit` or `digit/digit`. 
I could not find any documentation how to tweak it with the current default tokenizer. 

```
import spacy
nlp = spacy.load("en_core_web_sm")

[(x, x.pos_) for x in nlp('fibrous type,5 mm in diameter,partially resected')]

# [(fibrous, 'ADJ'),
#  (type,5, 'PROPN'),
#  (mm, 'PROPN'),
#  (in, 'ADP'),
#  (diameter, 'NOUN'),
#  (,, 'PUNCT'),
#  (partially, 'ADV'),
#  (resected, 'VERB')]
```
This also relates to the problem of inconsistent tokenization of `/` in fractions:

```
[(x, x.pos_) for x in nlp('0/1 lymph nodes, 1/2 full')]
# [(0/1, 'PUNCT'),
#  (lymph, 'PROPN'),
#  (nodes, 'PROPN'),
#  (,, 'PUNCT'),
#  (1/2, 'NUM'),
#  (full, 'ADJ')]
```

**Comment by adrianeboyd** [comment]
The tokenizer looks at each string separated by whitespace, e.g. `type,5`, and decides how to split it using prefix, suffix, and infix patterns. You can add patterns as shown here: https://spacy.io/usage/linguistic-features#native-tokenizer-additions

And here's an example I wrote for how to remove an infix pattern: https://stackoverflow.com/a/58112065/461847

The tokenization of fractions looks consistent in your example, do you mean the POS labels? Statistical models like the tagger will have some level of error, but this would be an easy pattern to detect and fix in postprocessing with a Matcher or other custom component.

You also might want to try the scispacy models, which are trained on biomedical text rather than news/web text.
