### ISSUE TITLE
doc1.similarity(doc2)

### ISSUE THREAD

**Issue by asif-khan17** [explosion/spaCy#4647]
## Your Environment

* Operating System: windows 10
* Python Version Used: 3.7.0
* spaCy Version Used:1.7+
* Environment Information:

Hi I am new to sapcy, I want to develop a model which gives me the text similarity based on the intent.For example "I like cats" and "I hate cats" should be very dissimilar but when I am using "similarity" it gives me very high similarity.

**Comment by adrianeboyd** [comment]
Similarity between word vectors is often not directly interpretable, but it's a lot closer to the idea: do these words occur in the same context? In a lot of ways, "like" and "hate" are used in very similar contexts and it's common for antonyms to have similar vectors.

Maybe you're thinking about something more along the lines of sentiment analysis / text classification than text similarity? An introduction to spacy's `TextCategorizer` is here: https://spacy.io/usage/training#textcat (once you move past toy examples the [train CLI](https://spacy.io/api/cli#train) is recommended instead of this script) and an older example using spacy with keras is here: https://spacy.io/usage/examples#keras
