### ISSUE TITLE
ADD some exceptions to TOKENIZER_EXCEPTIONS in spanish

### ISSUE THREAD

**Issue by rbague5** [explosion/spaCy#4653]
Need to add more abbreviation exceptions in Spanish because when tokenizing sentences isn't 100% accurate, those are the abbreviations:

abbreviations = ['sra.', 'dª.', 'dña.', 'sras.', 'sres.', 'sr.', 'excmos.', 'excmo.', 'excma.', 'excmas', 'ilma.', 'ilmas.','ilmo.', 'ilmos.', 'art.', 'arts.', 'núm.', 'cp.', 'c.p.', 's.l.', 'rcud.', 'rcuds.', 'rec.','Sra.', 'Dª.', 'Dña.', 'Sras.', 'Sres.', 'sr.', 'Excmo.', 'Excmos.', 'Excma.', 'Excmas', 'Ilma.', 'Ilmas.','Ilmo.', 'Ilmos.', 'Art.', 'Arts.', 'Núm.', 'CP.', 'C.P.', 'S.L.', 'Rcud.', 'Rcuds.', 'Rec.']

## Your Environment
* **spaCy version:** 2.2.1
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.4
* **Models:** es

**Comment by adrianeboyd** [comment]
Hi, thanks for your contribution! A number of these are rare enough that I don't think it makes sense to add them to a general-purpose list of exceptions, but you can always use `nlp.tokenizer.add_special_case()` to customize the tokenizer for your tasks: https://spacy.io/usage/linguistic-features#special-cases

Looking at a reference list (https://www.rae.es/diccionario-panhispanico-de-dudas/apendices/abreviaturas, please correct me if this is not a good source since my Spanish is a bit rusty), I think it could make sense to add:

```
art.
arts.
cp.
D.
D.ª
Dña.
Núm.
Sras.
Sres.
S.L.
```

What do you think?

**Comment by rbague5** [comment]
Hi,
Thanks for your fast reply!
That reference list is the perfect source for spanish and the examples you said are good to add. But maybe need to add the lowercase/uppercase example or it doesn't matter? For example: art/Art.

Is there any way to pass a list to `nlp.tokenizer.add_special_case()` for not tokenizing? I need to tokenize texts in sentences to treat them and the example of `.add_special_case()` that is in the webpage isn't really usefull for me I think. 
Can you please give me an example of the code needed to not tokenize a text where appears 'art.' ?
The sentence can be: 

> En el art. 15 de la Constitucion Española...


Thanks!

**Comment by adrianeboyd** [comment]
You just pass one token dict as the desired tokenization, which is the same thing that happens in the last line here:

https://github.com/explosion/spaCy/blob/5adcb352e9b27acea60c6b60613c55c41a702ae8/spacy/lang/es/tokenizer_exceptions.py#L39-L66

```
nlp.tokenizer.add_special_case("art.", [{"ORTH": "art."}])
```

**Comment by rbague5** [comment]
Thanks! It worked 👍 

Feel free to contact me if you need some help with Spanish
