### ISSUE TITLE
Support for attrs like Gender and Case in Greek in POS Tagging

### ISSUE THREAD

**Issue by george-roussos** [explosion/spaCy#4655]
Hi! Is there any method that takes there of this? NLP Cube does it but it's not that reliable with Greek and SpaCy has been very good at predicting POS labels for me.

**Comment by adrianeboyd** [comment]
Not out-of-the-box, no. A separate statistical model for morphological features is planned, but not available yet.

In order to have access to morphological features in the meanwhile, some languages have models that combine the POS tag and morphological features into one large tag. It makes the tagset a lot bigger, so the tag accuracy may go down a bit, but it can be useful to have the extra information.

A lot of spacy's UD-based models were trained with the combined tags, but Greek was developed separately and it looks like it's just using the fine-grained tags from the UD corpus. You could train your own model with the combined tags fairly easily, though, if this is something you need.

You can convert a UD corpus for training with the combined tags with the command:

```
spacy convert -n 10 -m ud-treebank.conllu .
```

I was curious so I evaluated the plain POS tag accuracy for a tagger trained with the combined tags for UD Greek, and if you just evaluate on the plain tags, the accuracy only goes down 0.5% for a model trained with the larger tagset. The accuracy of combined tag+morph is ~88%, which isn't too terrible for a tagset with 358 tags (and the relatively small size of the corpus), and maybe the common morph features are fairly accurate even if some of the rare ones aren't as good.
