### ISSUE TITLE
Tag problem after update

### ISSUE THREAD

**Issue by gbochikubo** [explosion/spaCy#4661]
Hi, i'm having a problem trying to update an existing spacy model. First I am just reading a file where the phrases I will use for training are stored and allocating the phrases in TRAIN_DATA [], then I take the tags contained in the test_texte phrase just for testing and the feedback is:

Apesar ADV advmod
de ADP mark
estar VERB cop
doente ADJ advcl
, PUNCT punct
Maria PROPN nsubj
foi VERB ROOT
para ADP case
a DET det
escola NOUN obl
hoje ADV advmod

After that I just perform the model update. The problem is when I try to get the tags after the model update most of the tags are coming with an X and this was not supposed to happen, this is the return after the update with the same phrase above:

Apesar ADV advmod
de ADP mark
estar X cop
doente X advcl
, X punct
Maria PROPN nsubj
foi X ROOT
para ADP case
a X det
escola NOUN obl
hoje ADV advmod

I'm not understanding why this is happening, this is my code:

```
from __future__ import unicode_literals, print_function
import plac
import random
from pathlib import Path
import spacy
from spacy.util import minibatch, compounding
import csv
from spacy.symbols import ADJ, ADV, INTJ, NOUN, PROPN, VERB, ADP, AUX, CCONJ,DET, NUM, PRON, SCONJ, PUNCT, SYM, X 

TRAIN_DATA = []
nlp = spacy.load('pt_core_news_sm')

with open('../Docs/Sentencas.csv', 'r',encoding='utf8') as data_file:
    lines = data_file.readlines()
    i = 0
    while i < (len(lines)-1):
        tokens = lines[i].split("***")
        i += 1
        tags = lines[i].split("***")
        i += 1
        TRAIN_DATA.append(("{}".format(' '.join(tokens[:-1])), {"tags": tags[:-1]}))

optimizer = nlp.begin_training()
test_text = "Apesar de estar doente, Maria foi para a escola hoje"
doc3 = nlp(test_text)
for token in doc3:
    print(token.text, token.pos_, token.dep_)  

for i in range(20):
    print("Epoch ", i)
    random.shuffle(TRAIN_DATA)
    for text, annotations in TRAIN_DATA:
        try:
            nlp.update([text], [annotations], sgd=optimizer)
        except:
            print("Error on ", text, annotations)

doc3 = nlp(test_text)
for token in doc3:
    print(token.text, token.pos_, token.dep_)  

```

## Your Environment

* Operating System: Windows
* Python Version Used: 3.7.5
* spaCy Version Used: 2.1.9
* Environment Information:

**Comment by adrianeboyd** [comment]
The critical part here is probably your training data, which I suspect has UD POS tags instead of the same fine-grained tags as the current Portuguese model.

When you're training a tagger, the model is learning the `tag` feature not the `pos` feature. Spacy uses a mapping in `spacy/lang/pt/tag_map.py` to map from `tag` to `pos` and when it comes across tags that aren't in `tag_map` while training, it maps them to `X`.

The current Portuguese tag map comes from an old version of `UD_Portuguese-Bosque` (v1.3, I think) with complicated fine-grained tags including a lot of morphological features, and it looks pretty noisy with nearly 5000 tags. Unfortunately, if you want to update the existing model, you'll need to tag your data with these tags:

https://github.com/explosion/spaCy/blob/74b951fe616062c2acd96b79e233882627bcb7de/spacy/lang/pt/tag_map.py

If you have enough data, you could also start with a blank `pt` model instead of `pt_core_news_sm` and just add your new tags to the existing tag map:

```
nlp = spacy.blank('pt')
```

If you do want to use the UD data as a base and extend it with your data, I would recommend starting with a new conversion of the most recent version of `UD-Portuguese-Bosque` , creating a new `tag_map`, and training a new model from scratch. I can provide an outline of how to do this if you're interested. There are CLI commands to handle the conversion and the training without much additional effort beyond creating the tag map.

I hope to update the Portuguese model for a future version of spacy (maybe v3.0?) with cleaner data from newer versions of the UD corpora, but I can't make any promises about when this might be available.

**Comment by gbochikubo** [comment]
Thank you, i guess the problem is really the training data. Can you give me any tips on how to use the UD data as a base and extend it with my data, and how to do the conversion of the most recent version of UD-Portuguese-Bosque, also how to do the tag_map  ? I am trying to train a model to deal with the informal phenomena of the Portuguese language, I believe it will be a very useful contribution to the community.

**Comment by adrianeboyd** [comment]
Hi, here's the basic outline: https://github.com/explosion/spaCy/issues/3052#issuecomment-557461382

UD subtokens are also a problem for Portuguese, and slightly more of a problem than for French because of how pronoun clitics have been annotated. Be aware that with the current converter you always get token sequences like `de o` instead of `do` and `faltou lhes` instead of `faltou-lhes`.

I'm working a converter option that uses the merged version instead of the subtoken version, but it's also still in progress.
