### ISSUE TITLE
conll2json: Underscore not allowed in head column

### ISSUE THREAD

**Issue by HendricButz** [explosion/spaCy#4665]
I got a conllU file, from my university, where the head column is filled with _. 
Processing such file with the cli.convert method will result in a int cast error in 
https://github.com/explosion/spaCy/blob/master/spacy/cli/converters/conllu2json.py line 73 
in the read_conllx method (head = (int(head) - 1) if head != "0" else id_).

In the format documentation on https://universaldependencies.org/format.html
there is stated that: the allowed values for head are the same as for id (so _ should not be allowed)
"7. HEAD: Head of the current word, which is either a value of ID or zero (0)."

But some lines later, underscore "_" is only forbidden for the id column.
"Underscore (_) is used to denote unspecified values in all fields except ID. Note that no format-level distinction is made for the rare cases where the FORM or LEMMA is the literal underscore – processing in such cases is application-dependent. Further, in UD treebanks the UPOS, HEAD, and DEPREL columns are not allowed to be left unspecified."

So, the university guys who gave me the problematic conll file insits on beeing right in allowing _ in the head column and asked me to write a bug report here.

**Comment by adrianeboyd** [comment]
Hi, I think this comes down to a difference between the CoNLL-U specification and what is valid for UD treebanks. We've mainly had CoNLL-X/U parsing data and UD treebanks in mind when developing the converter.

Would you like a submit a PR that makes the deps+heads optional? I think it would need a similar check to the `has_ner_tags` check in order to skip those columns in the output. (The converter allows some non-standard NER tags in the MISC column and if NER tags aren't found, no NER tags are included in the converted output.)

As an alternative, it would also be simple to put dummy HEAD/DEP values in your data (and remember not to use the converted data to train a parser, of course).

**Comment by onlyanegg** [comment]
@adrianeboyd, I took at crack at this today. I'm super new here, I'm not sure if this is still needed, and I'm not sure if this is the right solution.

It's interesting. In the CoNLL-U documentation, I see that underscores (representing unspecified values) are not supposed to be allowed in the HEAD field, so it seems strange to allow them.

> Underscore (_) is used to denote unspecified values in all fields except ID. Note that no format-level distinction is made for the rare cases where the FORM or LEMMA is the literal underscore – processing in such cases is application-dependent. Further, in UD treebanks the UPOS, HEAD, and DEPREL columns are not allowed to be left unspecified.

Also, I didn't think using a check similar to `has_ner_tags` would work in this situation since the exception was raised before that check was made. Instead I modified the assignment conditional in the `read_conllx` function.
