### ISSUE TITLE
BERT Model (German) does not work in multiprocessing mode

### ISSUE THREAD

**Issue by engrsfi** [explosion/spaCy#4667]
The BERT model for the German language works fine if I use it in the main process or use it in a multi-threaded way. However, as soon as, I use the model in a multi-processing mode, it gets stuck at the model inference time.

Normal usage which works fine:

```
import spacy

# Load model (German language)
bert_model = spacy.load('de_trf_bertbasecased_lg')

# Run model 
result = bert_model("This is just a test input")
```

Usage in multiprocessing mode which does not work:

```
import spacy

bert_model = None

def worker(text):
    # Load model (German language)
    if not bert_model:
       bert_model = spacy.load('de_trf_bertbasecased_lg')

    # Run model 
    result = bert_model(text) #It just gets stuck here.

from multiprocessing import Pool

list_of_text_strings = ["this is test 1", "this is test 2", "this is test 3"]

with Pool(2) as p:
    p.map(worker, list_of_text_strings)

```

In the multiprocessing model, the model loading statement is executed but then it gets stuck at inference time. Any ideas what is going wrong here? Is it a bug or am I doing something really wrong? or could it be that its a problem only with German-language Bert?

## Your Environment
* **spaCy version:** 2.2.2
* **Platform:** Darwin-18.7.0-x86_64-i386-64bit
* **Python version:** 3.6.9

**Comment by engrsfi** [comment]
@adrianeboyd  shouldn't it be labeled as a bug too?

**Comment by adrianeboyd** [comment]
It would be better if it were, of course, but I am not sure whether it's intended to be thread-safe.

**Comment by engrsfi** [comment]
It works fine with multi-threaded mode but it does not work in a sub-process. I am using it in separate processes so ideally, it should easily work in a sub-process where I load an individual model.

**Comment by adrianeboyd** [comment]
Sorry, I misread!

This looks like a deadlock related to threads in the subprocesses that may come from pytorch. In my tests on linux, it looks related to libgomp and this is a relevant issue: https://github.com/pytorch/pytorch/issues/17199

One option that seems to work for me (from the linked issue above) is:

```
import torch

torch.set_num_threads(1)
bert_model = spacy.load('en_trf_robertabase_lg')

def worker(text):
    result = bert_model(text)
```

Be aware that multiprocessing may not be helpful in the end because of the overhead of dealing with copying the model data. Depending on your setup, a single `bert_model.pipe(texts)` can be faster than using multiprocessing. In both cases, you want your worker to get a batch of texts and use `.pipe()`, since this will be much faster.

**Comment by engrsfi** [comment]
This option seems to work for me now.

I have both IO/CPU intensive pipeline with thousands of files being read from the disk and being processed with Bert so multi-processing seemed a better option. However, I will compare it with the pipe version to see which one works better. Thanks for the suggestions.
