### ISSUE TITLE
Error when using offsets_from_biluo_tags 

### ISSUE THREAD

**Issue by Niels-Dekker** [explosion/spaCy#4684]
I am trying to convert IOB tags from another NER model to the spaCy Span format.

Consider the following example sentence:

`The merger of Hema and Bijenkorf B.V. takes place on monday the 10th of august.`

The IOB output from my model looks like this:
`['O', 'O', 'O', 'B-ORG', 'O', 'B-ORG', 'I-ORG', 'I-ORG', 'I-ORG', 'I-ORG', 'O', 'O', 'O', 'O', 'B-DATE', 'I-DATE', 'I-DATE', 'I-DATE', 'O']`

I can correctly transform this to BILUO using spacy.gold's `iob_to_biluo`:
`['O', 'O', 'O', 'U-ORG', 'O', 'B-ORG', 'I-ORG', 'I-ORG', 'I-ORG', 'L-ORG', 'O', 'O', 'O', 'O', 'B-DATE', 'I-DATE', 'I-DATE', 'L-DATE', 'O']`

I used to be able to use `offsets_from_biluo_tags` to transform this to the required offsets. However, when used now, I get:

`IndexError: [E035] Error creating span with start 14 and end 18 for Doc of length 16.`

I suspect that it has to do with the periods in 'B.V.', because running the same steps for this text works just fine:

`The merger of Hema and Bijenkorf takes place on monday the 10th of august.`

This issue breaks both the `offsets_from_biluo_tags` and the `spans_from_biluo_tags` from spacy.gold.

## Info about spaCy

* **spaCy version:** 2.2.2
* **Platform:** Darwin-18.6.0-x86_64-i386-64bit
* **Python version:** 3.7.0

**Comment by adrianeboyd** [comment]
This kind of conversion will only work if both models are working with the same tokenization. Spacy (with the default English tokenizer) tokenizes `B.V.` as one token and it looks like the other model has four tokens.

Some options:

* work with character rather than token offsets from the other model
* initialize a spacy `Doc` with the tokens from the other model (be aware that the rest of spacy's default models won't work as well on this `Doc` due to tokenization differences)
* tokenize the text with spacy, tag it with the other model (which likewise may not work as well)

**Comment by Niels-Dekker** [comment]
This explains a lot. Thank you for your quick response!
