### ISSUE TITLE
Different/random dependency tag depending on runtime

### ISSUE THREAD

**Issue by f11r** [explosion/spaCy#4689]
## How to reproduce the behaviour

Running
```
python -c "import de_core_news_sm; nlp = de_core_news_sm.load(); d = nlp('Dies ist ein Test Text .'); print([t.dep_ for t in d])"
```
gives `['sb', 'ROOT', 'nk', 'pnc', 'pd', 'punct']`, while running
```
ipython -c "import de_core_news_sm; nlp = de_core_news_sm.load(); d = nlp('Dies ist ein Test Text .'); print([t.dep_ for t in d])"
```
gives `['sb', 'ROOT', 'nk', 'nk', 'pd', 'punct']`. The only difference is `python` vs `ipython`. In `py.test` I've randomly run into both variants of this parse.

## Info about spaCy

* **spaCy version:** 2.2.2
* **Platform:** Linux-4.19.81-x86_64-with-glibc2.10
* **Python version:** 3.7.3
* **ipython version:** 7.5.0
* **de_core_news_sm version:** 2.2.5

**Comment by adrianeboyd** [comment]
I can't reproduce this exactly. I do see different behavior between different versions of the v2.2 de model, but not with python/ipython from the same venv. With 2.2.0 I get `nk` and with 2.2.5 `pnc`.

Because of the somewhat non-standard nature of the test sentence and the way noun phrases are annotated in TIGER, I'm not surprised that the model might produce either one of these labels, but it is weird if the same exact environment / model produces different results with python vs. ipython.

**Comment by ines** [comment]
I also use `ipython` and tried it in my environment, but wasn't able to reproduce this.

> The only difference is python vs ipython. In py.test I've randomly run into both variants of this parse.

Did you check `which ipython` and `which python` to make sure they're both referring to the same Python environment? (If you're in a virtual environment that doesn't have `ipython` installed, but your system Python does, it might fall back to the system Python and execute that environment instead, which might have a different version.) Another thing you could add to your test is `print(de_core_news_sm.__version)`.

**Comment by f11r** [comment]
After installing in a fresh environment the problem has disappeared for me as well. I haven't been able to find what is wrong with my other environment but this is not a spacy problem.

Sorry for causing a fuss.
