### ISSUE TITLE
Cannot install spacy 1.9.0 with python 3.7

### ISSUE THREAD

**Issue by Shawn-Guo-CN** [explosion/spaCy#4699]
It seems that Spacy 1.9.0 doesn't support being installed with python 3.7?

## Your Environment

* Operating System: Ubuntu 18.04
* Python Version Used: 3.7.5
* spaCy Version Used: 1.9.0
* Environment Information: new conda environment

**Comment by honnibal** [comment]
This might just be an incompatibility in the Cython files. Does it work if you try building from source?

**Comment by ines** [comment]
spaCy v1.9 was released in July 2017: https://github.com/explosion/spaCy/releases/tag/v1.9.0
Python 3.7 was released in June 2018: https://www.python.org/downloads/release/python-370/

While the version should *in theory* be compatible with 3.7 because Python 3.6 code is forwards-compatible, it's possible that it pins to versions of dependencies that are not. Or if you're installing from conda, the package likely only ships with wheels for 3.6 and below, since 3.7 didn't exist at the time of the release. So the easiest solution would be to build the tag from source.
