### ISSUE TITLE
Chaining models or specifying priorities for overlapping entities?

### ISSUE THREAD

**Issue by bulutsuzku** [explosion/spaCy#4718]
## Which page or section is this issue related to?
https://spacy.io/usage/training

Hello,

I am a newbie with spaCy, currently trying to understand the terminologies and workflow - BTW I find sometimes the spaCy documentation introduces NLP jargon and tasks assuming the reader already knows the subject - 

I wrote this question in scispaCy issues, with no answers so far, which made me think it could be more relevant to spaCy too: I tried scispaCy with a NER task using en_ner_bionlp13cg_md. Unfortunately it recognizes entities in a wrong way i.e.: "Americas" as ORGANISM, "Columbus" as CANCER, etc. so this is my question:

Could I chain different models?
Like using both en_ner_bionlp13cg_md and en_ner_bc5cdr_md?

If yes, how do I specify "priority"? For example: I would like to prioritize on geopolitical entities using model A but for gene names use model B?
Does this make sense?

Is this what the "pipeline" concept refers to?

Thank you for reading.

**Comment by adrianeboyd** [comment]
The "pipeline" concept mainly means that models are applied individually in a specific sequence. If you have a pipeline like `tokenizer -> model1 -> model2`, model1 finishes completely before model2 sees the document and model2 doesn't have any influence on what model1 does. model2 can see any labels that model1 added, but model2 can't change model1's behavior and has to cope with any errors that might come from model1. Similarly, model1 doesn't know anything about the models that might come later in the pipeline.

spacy's NER models are designed to respect any existing entities, so if a document already has some entities labeled, an NER model will only add new labels, not overwrite or modify existing labels. (Basically an NER model can turn `O` into `B-PER` or `I-PER`, but won't modify any `B-` or `I-` tags.)

There's no built-in way to pick and choose which labels a model can apply from the set it's been trained on. If you want to combine models like this, one option is to run the first model, remove the entity spans for labels you know it does poorly on, then run the second model. You could write a short pipeline component that is added in the pipeline between model1 and model2 to do this: https://spacy.io/usage/processing-pipelines#custom-components

Be aware that the models might behave differently when there are existing entities, since being restricted to working around the existing entities can change their predictions. If both models annotate some of the same entity types, it's possible this could lead to poorer performance, but I don't really know. To double-check, you could run each model separately on clean copies of the document and compare the results.
