### ISSUE TITLE
Display Custom Attributes in the Named Entity Recogniser

### ISSUE THREAD

**Issue by Fourthought** [explosion/spaCy#4730]
## Feature description
The Named Entity Recogniser is great for displaying named entities, what would also be great is the ability to also display custom attributes along with the named entities.

Using the token based matching structures, initialistion might go from:
- displacy.serve(doc, style="ent")
to:
custom_attributes = [{"_" : {"ATTRIBUTE1" : "VALUE"}, {"_" : {"ATTRIBUTE2" : "VALUE"}]
- displacy.serve(doc, style="ent", custom = custom_attributes)

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
Displacy is a custom component so this suggestion should be possible.

**Comment by ines** [comment]
Hi! Supporting this is a bit difficult, because spaCy can't know what your custom attributes "mean". They could be anything, so it'll always be difficult to render them in a general-purpose way that makes sense. Depending on what the attributes are, it can also easily clog up the visualization.

One thing you could do as a workaround is add the values to the span labels, e.g. `f"{ent.label_} ({ent._.custom_attr})"` or something. If you don't want to modify the `Doc` in place, you could also [pass in a dict](https://spacy.io/usage/visualizers#manual-usage) instead.
