### ISSUE TITLE
make_doc() rejects subtypes of str

### ISSUE THREAD

**Issue by MaxG87** [explosion/spaCy#4731]
## How to reproduce the behaviour
Please consider the following minimal working example (`mwe.py`).

```python
#!/usr/bin/python

import spacy


class MyString(str):
    pass


nlp = spacy.load('en_core_web_sm')
my_str = MyString('Lets crash spaCy for no reason.')
doc = nlp(my_str)
```

If I execute mwe.py, I get the following error message:

```
Traceback (most recent call last):
  File "/home/mgoerner/mwe.py", line 12, in <module>
    doc = nlp(my_str)
  File "/home/mgoerner/.miniconda3/envs/minerva/lib/python3.8/site-packages/spacy/language.py", line 427, in __call__
    doc = self.make_doc(text)
  File "/home/mgoerner/.miniconda3/envs/minerva/lib/python3.8/site-packages/spacy/language.py", line 453, in make_doc
    return self.tokenizer(text)
TypeError: Argument 'string' has incorrect type (expected str, got MyString)
```

However, I consider this to be incorrect. MyString is a proper subtype of 'str' and thus should be accepted as well.

## Info about spaCy

* **spaCy version:** 2.2.3
* **Platform:** Linux-5.3.0-050300-generic-x86_64-with-glibc2.10
* **Python version:** 3.8.0

**Comment by honnibal** [comment]
This is expected behaviour and can't really be fixed.

The tokenizer is implemented as a C extension, so the actual nature of the input matters. It's not enough to merely be a subclass or obey the interface, it needs to have the same memory layout as well.

I understand this is different from most Python code, so I'm sorry if it was confusing.
