### ISSUE TITLE
Disabled pipes interim save to disc

### ISSUE THREAD

**Issue by pythonBerg** [explosion/spaCy#4743]
This is a feature suggestion that is perhaps only requested due to my ignorance...

When running training for either textcat or ner, other pipes are disabled. The sample code suggests using "with" clause so that they are enabled before save.

When running long training program, saves are applied frequently. These saves appear to change meta.json to reflect only the pipe being trained since others have been disabled. This seems to be cleaned up at the end with the save outside the "with" clause.

Should a long program fail or be canceled within the "with" clause, it is possible that other trained pipes could be lost if manual edit to meta.json is not completed before next training run...

Does this make sense? Users have the ability to both disable and remove pipes. Shouldn't a save always reflect pipes that exist, even if they've been disabled? What am I missing?

**Comment by ines** [comment]
Hi! I hope I understand the question correctly. But you can think about the `disable_pipes` as a "temporary remove". The idea is to explicitly allow things like this:

```python
with nlp.disable_pipes(["parser", "tagger"]):
    nlp.to_disk("./model-without-parser-tagger")
nlp.to_disk("./model-with-all-components")
```

Instead of a `with` block, you can also call the method, receive a `disabled` object and restore the `nlp` object by calling `disabled.restore()` ([see here](https://spacy.io/api/language#disable_pipes)).

> This seems to be cleaned up at the end with the save outside the "with" clause.
>  
> Should a long program fail or be canceled within the "with" clause, it is possible that other trained pipes could be lost if manual edit to meta.json is not completed before next training run...

The training examples use `disable_pipes` to make sure you're never actually updating other unintended components, only the one you're interested in.

At the end of it, we're saving the whole `nlp` object to give you a nice updated model. But it really doesn't matter, because none of the disabled components have changed. You could also just remove them entirely, only save out the trained component and then put the components back together afterwards.

If your program dies before restoring the disabled components, and you only have the non-disabled component saved, you do "lose" the other components. But you didn't actually lose any state if none of the other components have changed. They'll be the same as whatever you've loaded in at the beginning.

(Manually editing the meta wouldn't make a difference here btw – it only reflects what's in the pipeline, and if no component is there, its data won't be serialized either, and you'd just end up with a broken model with a meta that describes components that aren't there.)
