### ISSUE TITLE
Inaccurate pretrained model: conjugation adjectives [de-core-news-md][spaCy 2.18]

### ISSUE THREAD

**Issue by yano27** [explosion/spaCy#4753]
## How to reproduce the behaviour

Hello,

I'm trying to extract a list of adjectives from a sentence into a span.
Simple setence such as "Die Farbe sollte rot, blau oder schwarz sein" can be extracted properly. I gained my wished result which is "rot, blau, oder schwarz" as the new tag/span (by using spaCy dep_ and children_)
![python_2019-12-03_14-17-24](https://user-images.githubusercontent.com/33882480/70060294-89634d00-15e2-11ea-96c5-6c1b36c599b7.png)

But it's not working as I expected, when I added a subclause into it "Die Farbe sollte rot, blau oder schwarz sein, aber nicht grau oder braun"
![python_2019-12-03_14-18-12](https://user-images.githubusercontent.com/33882480/70060300-8bc5a700-15e2-11ea-88b5-844812cbd96e.png)
The word "rot" and "blau" have the same dependency, which is "pd".
I use "pd" in my code as an indicator of the (new) span starts token, because of it  I gain "rot" and "blau oder schwarz" as seperated span.

I would like to know which approach should I use fix change the word "blau" dependency into "cj", should I trained the model using what it said on this website https://spacy.io/usage/training? Thanks in advance.

P.S : I try also following examples..
"Die Stadt sollte in Karlsruhe, Berlin oder Stuttgart sein, aber nicht in London oder Manchester": accurately extracted
"Das System sollte schnell, einfach und robust sein, aber nicht teuer oder komplex":  inaccurate extracted
So maybe the issues is only for adjectives..

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.6
* spaCy Version Used: 2.1.8
* model Version Used: de-core-news-md 2.1.0
* Environment Information: Django, VisualStudio

**Comment by adrianeboyd** [comment]
Coordination is hard (for any parser, not just spacy) and spacy's German models are trained on newspaper text, which may not have many sentences with this kind of structure. The German training data is a dependency conversion from a phrase structure treebank and coordination may be hard to convert correctly in all cases, so that's another complicating factor.

I think you are unlikely to get 100% perfect parses for cases like these, so it would be better to focus on making your method for extracting phrases more robust to errors like this. You can either try to identify errors like this and fix the dependency parse in postprocessing or you can extend your extraction patterns to handle this kind of input.

**Comment by yano27** [comment]
Okay thanks for your quick feedbacks

**Comment by ines** [comment]
Merging this with #3052!
