### ISSUE TITLE
Why is not doc[0].is_sent_start = True by default when you add a sentencizer

### ISSUE THREAD

**Issue by joanPlepi** [explosion/spaCy#4765]
## How to reproduce the behaviour
```
from spacy.tokenizer import Tokenizer
from spacy.pipeline import Sentencizer
from spacy.lang.de import German
nlp = German()
nlp.add_pipe(Tokenizer(nlp.vocab))
nlp.add_pipe(Sentencizer())
print(nlp.pipeline) # for debugging
doc = nlp.make_doc("Er beteiligte sich in zahlreichen Gremien und Kreisen und hatte 1908 entscheidenden Anteil an der Gründung der Gesellschaft der Bücherfreunde zu Hamburg. Während des Ersten Weltkriegs diente Münzel als Hauptmann der Landwehr.")
for sent in doc.sents:
    print(sent) 
```
I am trying to use spacy for the german language, however I am getting an error when I try to access to sentences and is not clear to me why as I have alread added the Sentencizer component.

> ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: nlp.add_pipe(nlp.create_pipe('sentencizer')) Alternatively, add the dependency parser, or set sentence boundaries by setting doc[i].is_sent_start.

I even tried to add the sentencizer using the code below, but I still have the same bug. 

`nlp.add_pipe(nlp.create_pipe("sentencizer"))`

## Your Environment

* Operating System: Ubuntu 18.04
* Python Version Used: 3.7.0
* spaCy Version Used: 2.2.3
* Environment Information:

**Comment by joanPlepi** [comment]
> What I do not understand, why isn't `doc[0].is_sent_start = True ` by default?

**Comment by adrianeboyd** [comment]
A couple things here more related to general spacy usage:

The following command sets up a pipeline with a tokenizer, so you don't need to add it manually:

```
nlp = German()
```

Next, add the sentencizer:

```
nlp.add_pipe(nlp.create_pipe("sentencizer"))
```

Then, call `nlp()` instead of `nlp.make_doc()`. `nlp.make_doc()` just applies the tokenizer, not any other components like the sentencizer:

```
doc = nlp("Er beteiligte sich in zahlreichen Gremien und Kreisen und hatte 1908 entscheidenden Anteil an der Gründung der Gesellschaft der Bücherfreunde zu Hamburg. Während des Ersten Weltkriegs diente Münzel als Hauptmann der Landwehr.")
assert len(list(doc.sents)) == 2
```

`doc[0].is_sent_start` is `True` by default for all documents. When `doc.sents` checks for sentences it looks to see if sentence boundaries have been set beyond the first token, either through the sentencizer, the parser, or other components.  (Sentences boundaries can come from several different components and if you try really hard, you can find a few weird edge cases in how this is currently detected, but this kind of text isn't one of them.)
