### ISSUE TITLE
After updated, verb pos tagging seems to yield inconsistent results

### ISSUE THREAD

**Issue by carlos-takeapps** [explosion/spaCy#4776]
Given this code...

import spacy

```
nlp = spacy.load("en_core_web_sm")
doc = nlp("Apple is one of the most profitable companies in the world.")
for token in doc:
    print(token.text, token.pos_, token.dep_)
```

the result is

Apple PROPN nsubj
**is AUX ROOT**
one NUM attr
of ADP prep
the DET det
most ADV advmod
profitable ADJ amod
companies NOUN pobj
in ADP prep
the DET det
world NOUN pobj
. PUNCT punct

I would have expected the word is to be VERB ROOT as in

```
nlp = spacy.load("en_core_web_sm")
doc = nlp("Apple stands among the most profitable companies in the world.")
for token in doc:
    print(token.text, token.pos_, token.dep_)
```

Apple PROPN nsubj
**stands VERB ROOT**
among ADP prep
the DET det
most ADV advmod
profitable ADJ amod
companies NOUN pobj
in ADP prep
the DET det
world NOUN pobj
. PUNCT punct

**Comment by adrianeboyd** [comment]
I'm not sure what update you mean, but there might have been changes in the last year for how fine-grained tags (`token.tag_`) are mapped to UD POS tags (`token.pos_`) in order to have spacy's UD tags be closer to UD v2. You're right that according the UD v2 guidelines (at least as best as I can tell, they're often not as detailed as I'd like, and they conflict with what you find in actual UD corpora), "is" should be `VERB` here.

Spacy is doing the best it can with the training data it has (OntoNotes, which has PTB tags, not UD tags) and since PTB always uses `VBZ` for "is", the tagger doesn't have enough information to map it to the right UD POS tag in all cases. Since there isn't enough information, "is/VBZ" is mapped to its most frequent corresponding UD POS tag, which is `AUX`.

If you need to, you can typically distinguish uses of "is" by looking at the dependency parse, since aux-"is" isn't the root of the sentence/clause and copula-"is" would be. Try comparing the parses of sentence like "The tree is tall." vs. "The tree is growing tall." (And remember that there's a statistical model behind the parser so you can't expect 100% accuracy on all parses. Distinctions like adjective vs. past participle can be tricky.)
