### ISSUE TITLE
Missing `doc.is_sentenced` in `Sentencizer` requirements

### ISSUE THREAD

**Issue by tamuhey** [explosion/spaCy#4797]
https://github.com/explosion/spaCy/blob/38e1bc19f4a1c28e27938f46bb3805df4919fedc/spacy/pipeline/pipes.pyx#L1423

I think this line should be 

```python
@component("sentencizer", assigns=["token.is_sent_start", "doc.sents", "doc.is_sentenced"])
```

**Comment by tamuhey** [comment]
I found this when I was implementing the following code:

```python
@spacy.component("foo",requires=("doc.is_sentenced",))
def foo(doc):
    return doc
```

Should I use `doc.sents` instead of `doc.is_sentenced` in `requires`?

**Comment by adrianeboyd** [comment]
My guess would be that `is_sentenced` isn't here because it's (currently) always derived, so it's not something that a component assigns. Given that, though, I'm not sure whether it makes sense to say `doc.sents` for these components, either, but I know that one of the main ideas behind the component decorators is to make it easier for users to understand what's going on when they're building pipelines, and they'd usually be accessing `doc.sents` and not `token.is_sent_start`.

I guess if you say `doc.sents` it makes just as much sense to say `doc.is_sentenced`? But I'm not really sure?

**Comment by tamuhey** [comment]
> I guess if you say doc.sents it makes just as much sense to say doc.is_sentenced? But I'm not really sure?
Exactly yes.

**Comment by ines** [comment]
I think what makes `doc.is_sentenced` different is that it's just a boolean flag. It's pretty much always set. 

`requires=("doc.is_sentenced",)` is tricky, because a user would expect this to mean that the component requires `doc.is_sentenced` to be `True` (not just that it's set, because that'd always be the case). This is quite different from the way the `@component` annotations are currently interpreted. We could consider making an exception for these types of boolean attributes – I just hope it doesn't become confusing again, or make people think that you can also require certain values of the other attributes.

**Comment by tamuhey** [comment]
Thanks, I agree with you. I thin should use `doc.sents`.
