### ISSUE TITLE
Compatibility with allennlp 

### ISSUE THREAD

**Issue by moh55m55** [explosion/spaCy#4803]
Hello, 
I installed spacy==2.1.9 and the corresponding en model from : 
[https://pypi.org/project/spacy/2.1.9/](url)

and the reason is just to be compatible with allennlp. 

however, I got this error : 
```
nlp = spacy.load("en_core_web_lg")
```
```
  File "/Users/aldawsari/opt/miniconda3/envs/background/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/Users/aldawsari/opt/miniconda3/envs/background/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (spacy 2.1.9 (/Users/aldawsari/opt/miniconda3/envs/background/lib/python3.6/site-packages), Requirement.parse('spacy<2.3.0,>=2.2.1'))
```
any idea? 

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by adrianeboyd** [comment]
Hmm, I'm not sure where this version conflict is coming from (`spacy-transformers`? something else related to a mixture of `conda` and `pip` packages?), but if you use a new virtual environment, `pip install allennlp` should install a compatible version of spacy with no problems.

If you want to use `allennlp` with spacy v2.2, it looks like you'll need to install it from source because there hasn't been a release since they bumped up the requirement.

**Comment by moh55m55** [comment]
You are right. pip allennlp causes the problem, so installing allennlp from source solves the problem. Thanks

**Comment by adrianeboyd** [comment]
Good to hear, thanks!
