### ISSUE TITLE
Why Spacy always recognising apple as an Organisation

### ISSUE THREAD

**Issue by vkancharla5** [explosion/spaCy#4805]
* Operating System: Windows
* Python Version Used: 3.7.4
* spaCy Version Used: 2.2.1
* Environment Information: Ipython notebook

In named entity recognition Spacy always recognizing apple as an organization, never recognizing as a fruit.
I tried the below code: 

 import spacy
nlp=spacy.load('en_core_web_lg')

doc= nlp(u'Apple is my favourite fruit , it\'s cost around \u20B9 10 in India')
for token in doc:
    print(token,end='|')
print('\n....')

for ent in doc.ents:
    print(ent.text+'-'+ent.label_+'-'+str(spacy.explain(ent.label_)))

![2019-12-13 21_31_42-Window](https://user-images.githubusercontent.com/30368689/70815859-4bd99d80-1df4-11ea-9156-6293b427f50f.png)

Why Spacy is not recognizing apple as fruit and ₹10 as monetary value.
Please help me on this.
Regards,
Venkat

**Comment by svlandeg** [comment]
The NER models have relatively high [accuracy](https://spacy.io/usage/facts-figures#spacy-models) overal, but unfortunately there will always be cases that are wrongly predicted, such as in the example sentence you mentioned. It is highly likely that during training, the NER model encountered more cases of "Apple" being an organisation rather than a fruit. 

If you want to remedy this, you can either use a [rule-based approach](https://spacy.io/usage/rule-based-matching) for your specific use-case (if feasible), or [retrain](https://spacy.io/usage/training#example-train-ner) the NER with more specific examples - but do watch out for the problem of [catastrophic forgetting](https://explosion.ai/blog/pseudo-rehearsal-catastrophic-forgetting).

Thanks for the report - merging this example with the master thread Issue #3052.
