### ISSUE TITLE
embedded xml tags

### ISSUE THREAD

**Issue by moh55m55** [explosion/spaCy#4807]
Hello all, 
I am just wondering if anyone has an idea of how to tokenize the below text without considering the xml elements but keeping the attribute values using set_extension for the corresponding token. For example,  I want to save the attribute values (i.e. tid,  type,etc) for "now" token. Any suggestion? 

e.g. parsing the below text and not considering the xml element as a token
```
 The Navy has changed its account of the attack on the USS Cole in Yemen.
 Officials <TIMEX3 tid="t1" type="DATE" value="PRESENT_REF" temporalFunction="true" anchorTimeID="t0">now</TIMEX3> say the ship was hit <TIMEX3 tid="t2" type="DURATION" value="PT2H">nearly two hours </TIMEX3>after it had docked.
 Initially the Navy said the explosion occurred while several boats were helping
 the ship to tie up. The change raises new questions about how the attackers
 were able to get past the Navy security.
```

, but saving the attributes values as well: 
```
Token.set_extension('tid',force=True, default=None)
Token.set_extension('type',force=True, default=None )
now._.tid="t1"
now._.type=Date
```

**Comment by moh55m55** [comment]
UPDATE: 
I thought of using a matcher and then doc. retokenize (). something like this :
```
pattern = [
            {'TEXT': '<'}, {'TEXT': 'TIMEX3'},{'OP': '*'},{'TEXT':'/TIMEX3'},{'TEXT': '>'}
          ]
```
but I ended up having more repeated matches : like like this: 
 ```
< TIMEX3 tid="t1" type="DATE" value="PRESENT_REF" temporalFunction="true" anchorTimeID="t0" > now < /TIMEX3 >
****
< TIMEX3 tid="t2" type="DURATION" value="PT2H" > nearly two hours  < /TIMEX3 >
****
< TIMEX3 tid="t1" type="DATE" value="PRESENT_REF" temporalFunction="true" anchorTimeID="t0" > now < /TIMEX3 >  say the ship was hit  < TIMEX3 tid="t2" type="DURATION" value="PT2H" > nearly two hours  < /TIMEX3 >
****
```
and the reason is that {'OP': '*'} includes embaded TIMEX3. 

 Any idea?

**Comment by adrianeboyd** [comment]
This is a use case that isn't supported well by spacy out-of-the-box. Spacy assumes that it is getting plain text input and doesn't have any mechanism to have spans of characters like XML tags be ignored or treated differently while it's tokenizing or processing the text. It's better to remove the XML tags from the data in preprocessing and store the information in an alternate format.

I think a good way to do this would be to convert the XML annotation to standoff annotation, e.g., a table with the information that characters 45-50 are `tid="t1" type="DATE" value="PRESENT_REF" temporalFunction="true" anchorTimeID="t0"`, characters 100-110 are `tid="t2" type="DURATION" value="PT2H"`, etc. After spacy has tokenized the plain text, you can look up the information from your table and set the custom extension values. `doc.char_span()` is a useful function for getting the relevant span with one or more tokens from the character offsets.

I wouldn't recommend the approach with `Matcher` because you generally don't want to try to parse XML with regular expressions and even you have a very limited set of non-nested tags, `"OP": "*"` always finds all possible matches so it will be very slow.
