### ISSUE TITLE
Phrasematcher not always matching (overlapping) patterns

### ISSUE THREAD

**Issue by carschno** [explosion/spaCy#4814]
## How to reproduce the behaviour

```
def _matcher(spacy_model: Language) -> PhraseMatcher:
    known_entities: Dict[str, Set[str]] = {
        "PERSON": {"Mr. G.B.H. Smith:, "G.B.H. Smith", "Smith", ...},
        "ORG":  {...},
        "LOC":  {...},
    }
    matcher: PhraseMatcher = PhraseMatcher(spacy_model.vocab, attr="TEXT")
    for ne_type, entities in known_entities.items():
        patterns = spacy_model.tokenizer.pipe(entities)
        matcher.add(ne_type, patterns)
    return matcher

matcher = _matcher(spacy_model)

docs = [spacy_model("This is Mr. G.B.H. Smith"), ...]
for doc in docs:
            entities = [
                Span(sent, match_start, match_end, match_id)
                for match_id, match_start, match_end in matcher(sent)
            ]
```
At this point, I've set a pdb breakpoint because the results were unexpected in some cases (no matches):

```
ipdb> doc
Document name
This is Mr. G.B.H. Smith
ipdb> matcher(spacy_model(doc.text))
[(380, 5, 8), (380, 6, 8), (380, 7, 8)]
ipdb> matcher(doc)
[]
```
`matcher(doc)` (the last call) is expected to have the same output as the one before.

This is reproducible for this particular example, but hard to find out which patterns are affected exactly.

Note that I had to anonymize the example name.

## Your Environment

* **spaCy version:** 2.2.3
* **Platform:** Linux-4.15.0-72-generic-x86_64-with
* **Python version:** 3.6.9
* ~~Operating System: Ubuntu Linux 18.04.3~~
* Operating System: Alpine 3.10.3 (running in Docker)

**Comment by adrianeboyd** [comment]
Thanks for the report! This isn't quite a complete test case so I'm not totally sure what might be going on.

Is there any chance that `doc` has been processed with a different model than you're using to add the phrases to `PhraseMatcher`? If the tokenization is different `PhraseMatcher` won't be able to find the matches.

This works as expected for me:

```
import spacy
from spacy.language import Language
from spacy.matcher import PhraseMatcher
from spacy.tokens import Span

spacy_model = spacy.load('en')

def _matcher(spacy_model: Language) -> PhraseMatcher:
    known_entities: Dict[str, Set[str]] = {
        "PERSON": {"Mr. G.B.H. Smith", "G.B.H. Smith", "Smith"},
        "ORG": {},
        "LOC": {},
    }
    matcher: PhraseMatcher = PhraseMatcher(spacy_model.vocab, attr="TEXT")
    for ne_type, entities in known_entities.items():
        patterns = spacy_model.tokenizer.pipe(entities)
        matcher.add(ne_type, patterns)
    return matcher

matcher = _matcher(spacy_model)

docs = [spacy_model("This is Mr. G.B.H. Smith")]
for doc in docs:
            entities = [
                Span(doc, match_start, match_end, match_id)
                for match_id, match_start, match_end in matcher(doc)
            ]
print(entities)
# [Mr. G.B.H. Smith, G.B.H. Smith, Smith]
```

**Comment by carschno** [comment]
Sorry for the incompleteness; you are right, but as I said, the issue is very hard to generalize, even though I can replicate it for the specific document.

Indeed, there are two models in use in this context, one with an updated NER model, and one 'off-the-shelve'. Even though only one _should_ be used for processing, I was looking into this as a potential error source.

However, when I create a new document with either of the models, the exact same `PhraseMatcher` instance matches as expected on both of them.

Given the vagueness of the issue, I see that this is not necessarily a bug in Spacy, and definitely not one that would be easy to fix. But maybe it would be good to look into this and possibly add some checks that might make it easier to detect errors on the user side.

**Comment by adrianeboyd** [comment]
I agree that it would be nice to have warnings or errors, but it's difficult because a `Doc` doesn't keep track of which tokenizer was used to create it and `PhraseMatcher` doesn't keep track of much beyond the individual tokens from the provided doc patterns, either. (If you're interested in working on it: I can imagine a solution where each `Doc` stores a hash related to the tokenizer state and `PhraseMatcher` prints warnings when it notices different tokenizers in use.)

There still could be some kind of bug here (please post a full example if you find one!), but I think it's more likely that the reason is differing tokenizations, since a string like "G.B.H." is especially likely to have more than one possible tokenization.

**Comment by carschno** [comment]
One more background, just for the possibility it helps:
As mentioned I use two Spacy models in this context, `base_model` and `spacy_model`.

What is weird, and made me think that this was a possible bug in Spacy, was that the matcher matches as expected if I process the same text with any of the two:

```
[...]
matcher = _matcher(spacy_model)

docs = [spacy_model("This is Mr. G.B.H. Smith")]
for doc in docs:
            entities = [
                Span(doc, match_start, match_end, match_id)
                for match_id, match_start, match_end in matcher(doc)
            ] # <- this is the initial code form above, matches nothing
```
However, these work as expected subsequently:
```
matcher(spacy_model(doc.text))
```
and
```
matcher(base_model(doc.text))
```
both return the three expected matches. Therefore, I ruled out issues with tokenization variations. But still, this needs more investigation.

I will try to look into your suggested solution and create a merge request when I have time.

**Comment by carschno** [comment]
@adrianeboyd Would you have a more specific pointer (in the code) to what you mean by 'the state of the tokenizer'?

After diving into the code a bit, my best idea so far has been to store a hash of the `Tokenizer` instance used when creating the `Doc` instance. I tend to prefer a more generalised version and rather store a hash of the `Language` instance, in order to cover other properties such as the vocabulary.

However, none of these would explicitly refer to a state.
Also, I found the initial matter even more confusing now because I understand that the document is supposed to be used as-is when passed into the PhraseMatcher, so that I don't understand how it could have different tokenizations.

Furthermore, I'm wondering if this could be related to the vocabulary rather than the tokenization. However, I am not clear which role the vocabulary actually plays in this context (tokenization and matching).

**Comment by adrianeboyd** [comment]
(Sorry for the delayed response, I just realized this got left as a draft by mistake...)

In case there is a bug on our end, it's hard to know what might be going on without a minimal example that we can run or more information about the models and your script.

I'd recommend comparing the tokenization directly between the models or seeing if you get different results if you explicitly set the tokenizer to be the same for both models. Here is one way to do this (not the most concise way, but the tokenizer properties are straightforward and this avoids vocab-related issues):

```
nlp1 = spacy.load("model1")
nlp2 = spacy.load("model2")
nlp2.tokenizer.prefix_search = nlp1.tokenizer.prefix_search
nlp2.tokenizer.suffix_search = nlp1.tokenizer.suffix_search
nlp2.tokenizer.infix_finditer = nlp1.tokenizer.infix_finditer
nlp2.tokenizer.token_match = nlp1.tokenizer.token_match
nlp2.tokenizer.rules = nlp1.tokenizer.rules
```

If you do want to compare some value related to the tokenizer, I'd recommend `Tokenizer.to_bytes(exclude=["vocab"])`. You don't want the vocab included because it will vary depending on which texts you've processed so far. The tokenizer settings should be captured by all the remaining properties included in `to_bytes()`.

The vocabulary shouldn't matter much for the `PhraseMatcher`, which just stores the hashes of the attributes underneath, and the same attribute should always map to the same hash. If you're using the `TEXT` attribute and `nlp.tokenizer.pipe()`, the only part of the model that should matter is the tokenizer.

When you use the a model with `nlp.pipe()` and more pipeline components, the final tokenization might not only be due to the tokenizer if you have other pipeline components like `merge_entities` or `merge_noun_chunks`.

**Comment by carschno** [comment]
Turns out this was indeed a bug well hidden in my code. Thanks for the pointers anyway!
