### ISSUE TITLE
UserWarning: [W008] Evaluating Doc.similarity based on empty vectors occurs despite using language models that have vectors

### ISSUE THREAD

**Issue by venkarafa** [explosion/spaCy#4817]
I am trying to find similar words between one list of words with the the other through the .similarity function. 

Also, after reading one suggestion to not use smaller language models like 'en_core_web_sm' for similarity purpose,  I started to use "en_core_web_lg" and "en_vectors_web_lg". 

The warning "UserWarning: [W008] Evaluating Doc.similarity based on empty vectors."  occurs despite using language models "en_core_web_lg" and "en_vectors_web_lg". I have successfully suppressed the warning by setting the environment variable ['SPACY_WARNING_IGNORE'] = 'W008'.  But intermittently the variable setting seems to be ignored and the code takes longer time to render the results.

Can this issue be resolved pls ?

## How to reproduce the behaviour

```
import en_vectors_web_lg
nlp = en_vectors_web_lg.load()
listx =['HSBC', 'JP Morgan',......] #500 words lists
listy = ['Currency','Blockchain'.......] #1000 words lists
s_words = []
for token1 in listy:
    list_to_sort = [] 
    for token2 in listx:    
        list_to_sort.append((token1, token2,nlp(str(token1)).similarity(nlp(str(token2)))))
        sorted_list = sorted(list_to_sort, key = itemgetter(2), reverse=True)[0][:2]
        s_words.append(sorted_list)

```
## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.7
* spaCy Version Used: 2.2.3
* IDE: spyder

**Comment by ines** [comment]
Even if a model includes word vectors in general, it doesn't mean that it necessarily has vectors available for every word that you want to query. (For instance, it's totally possible that vectors trained on data from a few years ago may not have a vector for a word like "blockchain" because it was a lot less common and maybe didn't make the frequency cutoff.)

So when you see that warning, it means that you're looking up the similarity of a token that the model doesn't have a vector for. That vector will be zero, so the similarity comparison is likely not going to be useful. To skip those words and/or find them, you can check [`Token.has_vector`](https://spacy.io/api/token#has_vector) before you make the similarity comparison.

**Comment by venkarafa** [comment]
Thank you for your response @ines . Should not the vector representations of words persist over time? I mean for certain industries like fintech, blockchain is an important word. Same holds true for other words in other domains as well. What is the frequency cutoff being referred to ? Could you please point me to the source so that I can read more about this frequency cut off.

Thanks
Venkat

**Comment by rowhitswami** [comment]
Check for  `issue.vector_norm` to avoid checking similarity for empty vectors.

__Example:__
```
if (query_2.vector_norm):
    query_1.similarity(query_2)
```
