### ISSUE TITLE
NotImplementedError: cannot instantiate 'WindowsPath' on your system

### ISSUE THREAD

**Issue by ValentinCalomme** [explosion/spaCy#4818]
I am training a SpaCy text categorizer on my Windows machine as part of an ML pipeline. Once training is over, the whole pipeline is pickled and then persisted. When the pipeline needs to be loaded, it is unpickled. This works perfectly fine on my machine, the `nlp` object is pickled and unpickled without any issues.

However, when I try to unpickle the same pickle file within an Alpine Docker container, I get the following error when trying to unpickle my ML pipeline:

``` 
     return pickle.loads(state)
   File "/usr/local/lib/python3.7/pathlib.py", line 1013, in __new__
     % (cls.__name__,))
 NotImplementedError: cannot instantiate 'WindowsPath' on your system
```

I am guessing that this is because SpaCy must be serializing path information in a platform specific fashion?

I don't recall having this issue when using `from_disk` and `to_disk.` Why am I not using these functions? I'd like to have my entire ML pipeline within a single binary file.

Is this a bug? Are there workarounds? Or am I just not using SpaCy correctly?

## Your Environment

* **spaCy version:** 2.2.3
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.5

**Comment by honnibal** [comment]
Thanks for the report, that's an annoying problem! I would've hoped the pathing would be smarter.

As a workaround, could you use `nlp.to_bytes()` and write that out instead? In general my advice to any Python programmer would be to avoid Pickle whenever possible. Personally I try to use it approximately never. This does make it difficult to use various multiprocessing utilities, but what I tend to do is pass in the serialised versions of all of the arguments, and then deserialise in the child process. This may seem unintuitive because the serialisation looks like extra overhead, but it's no slower than pickling and unpickling would be, in most cases.
