### ISSUE TITLE
Tokenizer doesn't split on '//'

### ISSUE THREAD

**Issue by mapadofu** [explosion/spaCy#4820]
>>> import spacy
    >>> nlp = spacy.load('en_core_web_md')
    >>> doc = nlp("These//are//not//split   this/is")

My expected behavior is that all of the words would be split from one another.

## Info about spaCy

* **spaCy version:** 2.2.3
* **Platform:** Linux-4.4.0-169-generic-x86_64-with-Ubuntu-16.04-xenial
* **Python version:** 3.6.9

**Comment by adrianeboyd** [comment]
Hi, the tokenizer is designed to be easy to customize if you come across cases that aren't handled like you want. You can add `//` as an infix if you'd like so it's always split. See the examples in this section: 
https://spacy.io/usage/linguistic-features#native-tokenizer-additions

For infixes, the last two lines if you're adding a pattern (infix uses `finditer` instead of `search`):

```
infix_regex = util.compile_infix_regex(infixes)
nlp.tokenizer.infix_finditer = infix_regex.finditer
```
