### ISSUE TITLE
Multi-language model doesn't support doc.sents

### ISSUE THREAD

**Issue by m-marina** [explosion/spaCy#4837]
When I try:
```
import spacy
nlp = spacy.load("xx_ent_wiki_sm")
text = "..."
doc = nlp(text)
for sent in doc.sents:
    print(sent)
```
Output: ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: nlp.add_pipe(nlp.create_pipe('sentencizer')) Alternatively, add the dependency parser, or set sentence boundaries by setting doc[i].is_sent_start.

But if I add `nlp.add_pipe(nlp.create_pipe('sentencizer'))` -  it works.

If we compare the English-language model (en_core_web_sm), it divides the text into sentences without adding 'sentencizer' component.
The question is how to do the same for the Multi-language model?

## Environment

* Operating System: Ubuntu 18.04
* Python Version: 3.6
* spaCy Version: 2.2.3

**Comment by svlandeg** [comment]
Hi @m-marina, the [xx model](https://spacy.io/models/xx) assigns named entities, but does not have a parser pre-trained because that would not be straightforward for a multi-language setting. The [english models](https://spacy.io/models/en) do have a parser which also sets the sentence boundaries.

Currently the best way to get those sentences for `xx` is indeed using adding the `sentencizer` as described.
