### ISSUE TITLE
EntityRuler does not match an entity for pancreas

### ISSUE THREAD

**Issue by ewaldatsensentia** [explosion/spaCy#4855]
## How to reproduce the behaviour
import spacy
from spacy import displacy
from spacy.pipeline import EntityRuler
nlp =  spacy.load('en_core_web_md')
ruler = EntityRuler(nlp, validate=True, overwrite_ents=True)
patterns = [{"label":"ORGAN", "pattern":[{"LEMMA":"heart"}]},
            {"label":"ORGAN", "pattern":[{"LEMMA":"pancreas"}]},
            {"label":"ORGAN", "pattern":[{"LEMMA":"stomach"}]}]
ruler.add_patterns(patterns)
nlp.add_pipe(ruler, after="ner")
text = "This affects the heart, stomach, and pancreas only."
doc = nlp(text) 
displacy.render(doc, style="ent", jupyter=True)
# This affects the heart ORGAN , stomach ORGAN , and pancreas only.

It doesn't find pancreas as an ORGAN.
Oddly, if you remove the last comma, it works.  If you remove the "only" it works.  If you interchange "pancreas" and "stomach" it works.  That is:
text = "This affects the heart, stomach, and pancreas."
doc = nlp(text) 
displacy.render(doc, style="ent", jupyter=True)
# This affects the heart ORGAN , stomach ORGAN , and pancreas ORGAN .

The lemma of the token in the working phrases for "pancreas" is "pancreas" and for the bug it is "pancrea".  That isn't a real word.

## Your Environment
* **spaCy version:** 2.2.1
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.3

**Comment by adrianeboyd** [comment]
The lemmatizer depends on the statistical tagger model, which will make a small number of mistakes. I think what's going on here is that sometimes "pancreas" is being tagged incorrectly as a plural noun. When it's tagged as a plural noun, a lemmatizer rule thinks it's a typical English noun and removes the final "s".

One option might be to search for `{"LOWER": "pancreas"} since you know the lemma may be incorrect.

I would suggest trying the [scispacy models](https://allenai.github.io/scispacy/), since their taggers should perform better on biomedical text than the default spacy models, which are trained on web/newspaper text.

**Comment by svlandeg** [comment]
Merging with Issue #3052 to better keep track of such inaccurate predictions by the trained models !
