### ISSUE TITLE
Underscores are tagged as NOUN or PROPN

### ISSUE THREAD

**Issue by james-daily** [explosion/spaCy#4869]
## How to reproduce the behaviour

```
import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp("This _ is missing _.")
print([(t, t.pos_) for t in doc])

# outputs [(This, 'DET'), (_, 'PROPN'), (is, 'AUX'), (missing, 'VERB'), (_, 'PROPN'), (., 'PUNCT')]
```

With `en_core_web_lg` you get the same result, just with NOUN instead of PROPN.  The result is  the same regardless of the part of speech of the word or words it's replacing in the sentence.  It also tags strings of underscores as several proper nouns or nouns in a row (e.g. `"The _______ is on _____ table."`)

## Your Environment
* **spaCy version:** 2.2.3
* **Platform:** Darwin-17.7.0-x86_64-i386-64bit
* **Python version:** 3.7.2
* **Models:** en

**Comment by james-daily** [comment]
The problem doesn't occur in `de_core_news_sm` or `de_core_news_md`.  It's arguable whether `X` is the correct tag versus `SYM` or `PUNCT`, but that may be an artifact of the training data.  Underscores are probably rare-to-nonexistent in news.

```
import spacy
nlp = spacy.load("de_core_news_sm")
doc = nlp("In _ Satz _ Wörter.")
print([(t, t.pos_) for t in doc])
# [(In, 'ADP'), (_, 'X'), (Satz, 'NOUN'), (_, 'X'), (Wörter, 'NOUN'), (., 'PUNCT')]
```

**Comment by adrianeboyd** [comment]
Yes, this comes from the training data. The German training data (TIGER) has a few underscores while the English training data (OntoNotes) doesn't.

If you have underscores in your English texts, you'll have to work around this because the default model has no idea how to tag underscores. You could postprocess the annotation to correct the tags on underscores or extend the tagger model (a handful of examples would be probably be enough to get underscore to be tagged as  `XX`/`X` or `SYM`/`SYM`).

**Comment by svlandeg** [comment]
Merging with the master Issue #3052 !
