### ISSUE TITLE
Illegal Characters

### ISSUE THREAD

**Issue by davidbren** [explosion/spaCy#4894]
We OCR'd a number of images, the OCR was fairly noisy so we ended up with some exotic characters. These characters were causing the NER to fail during training 
I suppose it was due to the fact that some of the noisey characters were not part of the english language character set

nlp = spacy.blank('en') 

In our initial approach we tried replacing all non word characters with  spaces using some simple regex
ocrCleanedText=str(re.sub(r"(?!\/)\W","",ocrCleanedText))

However this causes an issue where we introduced spaces at the start & end of entities 
which causes the training to fail. We can work around this but it seems to be a wrong approach to process with. 

I am beginning to look at ASCII conversion type methods now but I would like to know what would you recommend as a gold standard approach ?

Are there any helper method in spaCy that would allow us to identify any non English characters set ?

## Your Environment
* Operating System: RHEL 7
* Python Version Used: 3.7
* spaCy Version Used: 2.1.8
* Environment Information:

**Comment by adrianeboyd** [comment]
By "fail during training" you're referring to having annotations skipped because of misaligned tokenization as in #3140? Or what behavior / error are you seeing?

The NER model does have restrictions on whitespace, but otherwise it shouldn't care what characters are included in any particular token.

An approach that requires less modification to your existing data and annotation might be to modify the tokenizer to split more non-Latin characters off as prefixes and suffixes so your annotation spans can be aligned with token boundaries during training / evaluation?
