### ISSUE TITLE
Morphologizer/char_embed docs?

### ISSUE THREAD

**Issue by buriy** [explosion/spaCy#4913]
Morphologizer/char_embed docs? I'm eager to try it!

## Which page or section is this issue related to?
Training? Architecture?

**Comment by adrianeboyd** [comment]
I've also been working on getting a working `Morphologizer` and while the code in the repo is maybe 95% complete, it still has more than a few rough edges and it's undocumented for good reason. A lot of major updates are in progress for thinc and spacy so I'm not sure whether it makes sense for you to try it just yet.

For right now, the `tagger` is surprisingly good at large tagsets (try `spacy convert -m` for a UD corpus). What I would suggest with v2.2:

* modify the tagger to add an env/cfg option to use `char_embed` instead of `subword_features` (in `build_tagger_model`, passing the option to `Tok2Vec`; this is so you can experiment without breaking existing v2.2 tagger models)
* potentially increase `nC` for `CharacterEmbed` (currently in `spacy/ml/_legacy_tok2vec.py`; if it's 8, it means the first 4 and last 4 bytes from the UTF-8 encoded token string are used as features)
* experiment with hyperparameters like `token_vector_width` and `embed_size` (see: https://spacy.io/api/cli#train-hyperparams)

And be aware that you can't currently use a GPU with a model using `char_embed` due to a bug in thinc.

**Comment by buriy** [comment]
Thanks a lot. Real use tricks are very important to me because currently in Spacy we have no documented optimal pipeline for this task.
Well, tagger is actually awful for morphology-rich languages, even with large UD datasets. I can get 93% POS for Russian instead of 98% for solutions that use char + word embeddings (see UDPipe 2 results, for example, https://www.aclweb.org/anthology/K18-2020.pdf at page 7, they report almost 99% for POS, also you might look at https://github.com/IlyaGusev/rnnmorph and https://github.com/chomechome/maru ).
Similarly, I have 5-10% worse DEP quality than I could get otherwise with better features.
I haven't tried the vectors trick yet, but adding vectors naively will take a lot of memory and won't help much for OOV (see ).
For a naive solution, we'll need 5M vectors taking 2 GB, and will still have OOV errors sometimes.
So I'm going to try your aliasing trick to store one vector per lemma (for 500K lemmas).
( You might take a look at #4815 for my approaches so far, you also explained the options recently for Serbian at #4760 )
I see that the final solution for Russian could use just these 2 components:
 - vectors for lemmas (using some {word->lemma} dict, in pymorphy2 we have a trie that keep this dict for 5M words in under 20 MB!)
 - vectors for char-ngrams to deal with syntax parsing and OOV (right now we use 1-char prefix + 3-char suffixes, in pymorphy2, instead, a fixed list of 50 prefixes and 5-char suffixes is used).
(And ideally if we could train such vectors automatically in this way from the downstream tasks.)
