### ISSUE TITLE
Loading a model under mod_wsgi hangs

### ISSUE THREAD

**Issue by Edison-SK** [explosion/spaCy#4922]
I am unable to use spacy integrated into a web service:

import spacy
import en_core_web_sm                                                                
nlp = en_core_web_sm.load()

The last statement hangs and apache returns timeout.

My environment is:

* Operating System: OpenSuSE Leap 15.1
* Python Version Used: 3.6.9
* spaCy Version Used: 2.2.3
* Environment Information:
apache, mod_wsgi, cherrypy, 
apache configuration is set to 1 process and 1 thread

I can use spacy in a traditional python script without any problems.

**Comment by svlandeg** [comment]
Hi @Edison-SK, sorry for the late reply, but these kind of issues can be difficult to debug for us as it's not clear whether the problem lies with spaCy or with your specific infrastructure, and we can't easily test this. Perhaps you would get more help for these type of issues on Stackoverflow?

Anyway I was googling a bit and found [this topic](https://serverfault.com/a/514251) where they advise to work in the Python main interpreter. Perhaps that works for you?
