### ISSUE TITLE
Beam Density

### ISSUE THREAD

**Issue by davidbren** [explosion/spaCy#4928]
Can you let us know what the default beam density is ? I can't seem to find it in the documentation

Environment
* **spaCy version:** 2.1.8
* **Platform:** Linux-3.10.0-1062.el7.x86_64-x86_64-with-redhat-7.7-Maipo
* **Python version:** 3.7.0

**Comment by honnibal** [comment]
You're best off checking the code, in `spacy.syntax.nn_parser.Parser`. I think the default is `0.001`, but because it's a fairly experimental feature there may be inconsistencies, and you could end up hitting a place where a different default gets inserted.

How are you finding the beam parsing by the way? In my experiments I've not really found an accuracy improvement from it, and it can be very slow on long sequences, due to a lot of copying operations.

**Comment by davidbren** [comment]
Thanks for the reply I just checked there & density is 0.0 by default. 
Primarily I was using the beam feature to get the probabilities back which is working ok. 

I am currently debugging OOM (Out of Memories) errors during training & one of my theories was that it was due to me changing the beam settings but it doesn't seem to be. 
The other theory I have is that it's due to upgrading from spaCy 2.0.18 to 2.1.18.  It's the same code & training data as I used in 2.0.18. I suppose I could roll back & test it

**Comment by svlandeg** [comment]
Hi @davidbren, I just want to point out that @adrianeboyd recently fixed some memory issue with `beam_parse()` in PR https://github.com/explosion/spaCy/pull/4686. Those changes need to be coordinated with an updated version of `thinc`. I think we don't have these incorporated into an official release yet, but we're currently working on new major releases of both `thinc` and `spacy`. In the meantime, you can also build the main branches of these two repo's from source.

Assuming the original question was addressed, I'm closing this issue, but feel free to open a new one if you run into any more issues!
