### ISSUE TITLE
How to train completely new entities instead of pre-trained entities using Spacy NER model?

### ISSUE THREAD

**Issue by deepakiim** [explosion/spaCy#4929]
How do I do transfer learning i.e. take pre-trained Spacy NER model and make it learn new entities specific to my use case?

For this, I have 100 new annotated training samples. The new retrained model should only predict the new entities and not any of the existing entities in the pre-trained spacy model. Just adding/updating new entities to existing models and ignoring the old entities during prediction doesn't make sense.

This official example describes how to add new entities to existing pre-trained entities but that's not what I want. I also have very few examples i.e. 100 to completely built a new NER model from scratch.

Edit: I want to identify all account numbers in an unstructured document.

Example ("I would like to change address corresponding to my account 12345. Kindly let me know how to do it. " [34, 39, 'accountnumber'])

**Comment by svlandeg** [comment]
I added an answer to the discussion that has already started on [StackOverflow](https://stackoverflow.com/questions/59827781/how-to-train-completely-new-entities-instead-of-pre-trained-entities-using-spacy/59844116#59844116), so I'm closing this issue here to avoid duplication. In general, using StackOverflow for generic usage questions is prefered, as it helps us to focus this tracker on bugs/feature requests, but also because there's a larger community that can help on SO.
