### ISSUE TITLE
Underscore name spacing problem and pipeline reset feature request.

### ISSUE THREAD

**Issue by JohnStuartRutledge** [explosion/spaCy#4954]
## Context
I work at a language learning company and am using SpaCy to build out a large suite of digital learning tools. Many of these tools allow the users (teachers in our case) to select options which load different language models and toggle on/off dozens of custom extensions. Many of these extensions are language specific and are process/memory intensive (e.g. some make external API calls or are designed to work on documents under 1000 words or less). Within the span of 5min it is not uncommon for teachers to switch between language models and toggle on/off multiple custom extensions, many of which are incompatible with each other (e.g. potential named entity collisions, etc).

Before committing to costly architectural changes we would like to push the limit on the number of languages/users we can support for each machine sitting behind our load-balancer. I.e., we would like to be able to support dozens of teachers working with various language model/extension combos on the same box simultaneously.

### Problem
The problem concerns the global nature of the `Underscore` object and is demonstrated below.
```python
import en_core_web_sm
import es_core_news_sm

from spacy.tokens.underscore import Underscore

from myapp.custom_pipes.en import EnglishOnlyExtension
from myapp.custom_pipes.es import SpanishOnlyExtension

en_nlp = en_core_web_sm.load()
es_nlp = es_core_news_sm.load()

custom_en_ext = EnglishOnlyExtension(en_nlp)
custom_es_ext = SpanishOnlyExtension(es_nlp)
en_nlp.add_pipe(custom_en_ext)
es_nlp.add_pipe(custom_es_ext)

en_doc = en_nlp('Hello friend.')
es_doc = es_nlp('Hola amigo.')

# the fact these 2 assertions fail cause us all kinds of problems.
assert en_doc.has_extension('custom_es_ext') is False
assert es_doc.has_extension('custom_en_ext') is False
```

### Question
Do you have any suggestions or elegant workarounds for how to deal the problems caused by the lack of name-spacing on the `Underscore` object?

### Feature Request
What do you think of adding some sort of `nlp.reset()` feature that sets the model and all its extensions back to the "factory default"? Currently In my application I have been storing the initial state of the pipeline on load in the `nlp.meta['pipeline_default']` so that I can easily reset without having to reload the model.

```python
def toy_example_of_reset_logic(nlp):
    # remove all custom pipes added after the initial load event
    for name in nlp.pipe_names:
        if name not in nlp.meta['default_pipe_names']:
            nlp.remove_pipe(name)

    # clear out all custom extensions
    Underscore.doc_extensions = {}
    Underscore.span_extensions = {}
    Underscore.token_extensions = {}
    return nlp
```

**Comment by svlandeg** [comment]
Hi @JohnStuartRutledge, that's an interesting use-case! 

I don't think there's currently much you can do to work around the global nature of the custom extension attributes. I think if I were you, I would probably put them into some sort of naming hierarchy, like `en-custom-label` and `es-custom-label` and check their "validness" using the prefix that should match the `lang` attribute of your `nlp` pipeline. You can also set this `lang` value in a custom attribute on the `doc` level. Then you probably want to "reroute" `has_extension` calls so that they can be checked by your custom validator, that checks the custom `lang` attribute and matches it to the prefixed name of your extension attribute. I realise it's not ideal and would require some coordinating of naming etc, but I can't think of a better workaround right now.

With respect to the resetting of custom pipes: there is not really a "factory default" of a pipeline, other than the empty one. I think your solution of storing the original names in `nlp.meta` makes sense. If it is a model loaded from file, you would find that information naturally in the `meta.json` as well. Why do you want to have this resetting function instead of just reloading the model, because of speed issues ? 

I think it might be a little tricky to reliably provide this resetting functionality as part of the library, because you don't know what other code may have changed the existing "default" components, and having a function called `reset` would trigger the expectation that everything is reset to the initial state, which may not be true. For instance some runtime setting could be changed on some standard component, and to check all of this the `reset` function would end up having to read its initial setting back in from file anyway.

**Comment by JohnStuartRutledge** [comment]
@svlandeg Gotcha, thank you for the suggestion.

> Why do you want to have this resetting function instead of just reloading the model, because of speed issues?

Correct, I noticed a significant speed improvement when I dynamically adjust the loaded model vs the fresh reload approach.

> having a function called reset would trigger the expectation that everything is reset to the initial state, which may not be true.

That makes sense. Do you think there would be any community interest if I started a pull request to address the global extension problem? Alternatively, I could make a pull to amend the `Underscore` documentation with a warning.

**Comment by svlandeg** [comment]
How would you propose to solve the global extension problem in a generic way ?

**Comment by JohnStuartRutledge** [comment]
No proposal as yet, and from what I can tell it would likely involve a significant refactor. However, It looks like i'm going to be working closely with SpaCy for the next few years so I thought I would check first to gage interest in such a a feature. I would like to help contribute where I can.

**Comment by svlandeg** [comment]
Sorry for the late follow-up - we've been discussing this a bit internally. 

The extension attributes really are meant to behave like actual Python attributes. In that sense, it's expected that all `Doc` objects will have the same set of attributes. So to support this use-case, it's probably best to add some sort of namespacing to your custom attribute names., like we discussed.

**Comment by JohnStuartRutledge** [comment]
No worries. Name-spacing it is! Thanks again for taking the feature request under consideration.
