### ISSUE TITLE
en command in model doesn't work

### ISSUE THREAD

**Issue by vipul2001** [explosion/spaCy#4962]
While using command
python -m spacy download en
the package 'en_core_web_sm' automatically comes into the picture and get installed
Is it better to use en_core_web_sm instead of en for models?

**Comment by adrianeboyd** [comment]
Underneath `en` is just a symlink for `en_core_web_sm`, so both will load the exact same model. In general, we'd recommend using the full name because it's less confusing.

(Also, the symlinks cause some issues internally and we're planning on getting rid of them in v3, so it's good to get in the habit of using the full names. I think all the docs have already been updated to use full model names everywhere.)
