### ISSUE TITLE
Training Data Structure OOM issues

### ISSUE THREAD

**Issue by davidbren** [explosion/spaCy#4978]
Hi 
I am hitting Out of Memory issues on training. I am training a NER on a custom training set & I think it may be the way I have formatted my training data 

Currently I have 1 big string per document, each document can be large. The docs are form based in many cases so its not free flowing english

[
["Entire Document String 1 ", {entities:[[]]},
["Entire Document String 2 ", {entities:[[]]}
]

If I reformat my training data to be in sentences should I expect an improvement in speed when training & an end to Out of memory issues ? 

Is it enough to have all sentences from all docs in this flat type format or should I have them nested 
per document ?

Flat 
[
 ["Sentence" , {entities:[[]]}.
 ["Sentence" , {entities:[[]]}.
 ["Sentence" , {entities:[[]]}.
 ["Sentence" , {entities:[[]]}
 ]

Nested
[
Doc 1[
 ["Sentence" , {entities:[[]]}.
 ["Sentence" , {entities:[[]]}.
 ["Sentence" , {entities:[[]]}.
 ["Sentence" , {entities:[[]]}.
 ],
Doc 2[
 ["Sentence" , {entities:[[]]}.
 ["Sentence" , {entities:[[]]}.
 ["Sentence" , {entities:[[]]}.
 ["Sentence" , {entities:[[]]}.
 ]
]

What is the best approach ? 

## Your Environment
* Python Version Used: 3.6
* spaCy Version Used: 2.2.3
* Environment Information: RHEL 7

**Comment by adrianeboyd** [comment]
Hi, can you provide more information about where you are running out of memory while training? How big is your training data? How many documents, how many tokens, how many tokens in the largest documents?

Long documents can cause out-of-memory problems for the NER model and since entities don't go over sentence boundaries, the NER performance won't be affected much by splitting documents into smaller chunks. We typically use paragraph-ish chunks as "documents" for most things internally and train larger models without problems (as an example, `xx_ent_wiki_sm` has 18839763 tokens in the training data).

**Comment by davidbren** [comment]
Thanks for the quick reply. 
The training set consists of 10k docs of varying lengths, avg 10 pages but can be anything up to 30 pages. I don't know exactly where it fails.

Do you think paragraphs\sections will help speed up training ?
For sections that don't contain any entities would you recommend including these ? 
What format should the sections be in within the JSON file ? 
I was going to convert to sentences first using a simple split(\n). Then pass 6 sentences to another function to search for entities. Does this sound reasonable to you or have you any recommendations ?

Ines posted a response before saying that the context is fairly localized, is there any rule of thumb here. Each entity should have a max of 10 token left & 10 token right etc ?

https://support.prodi.gy/t/command-ner-batch-train-returns-memoryerror/1919/5

**Comment by adrianeboyd** [comment]
That does sound like document length is the problem. During training there isn't any awareness of document structure beyond a single unit called "document", and spacy's training is designed to work well with "documents" that are about a paragraph long, since the tagger/parser/NER models rely on fairly local context to make decisions.

The documents are shuffled and grouped into batches for training, so a flat structure is fine. If you've used spacy's JSON training format, the sections called "paragraphs" are actually what are shuffled and grouped underneath, not the longer documents.

If you have some information about the document structure, it makes sense to use things like paragraph breaks or section headings to split the text into shorter segments. If not, things like `\n\n` or sentence boundaries are a good choice. Splitting your texts into documents that are about a page long is probably also fine, just check that you're not splitting a page in the middle of an entity.

Your training data should look like the data that you want to process with your model, so if you'll see sections without entities in your future data, you want to include these in your training data, too. In terms of context, I think a good rule of thumb is to have at least a sentence-ish amount of context, preferably a few sentences to a paragraph.

**Comment by davidbren** [comment]
That's really useful thanks for that. 
I am thinking that I will define a paragraph as being 150 tokens. 
I could either 

A) take 75 to the left of the entity & 75 to the right OR
B) take 150 tokens then search for the entities within this 

With option A I think I will bias the model as it will learn that the entity is always at position 76 ?
What do you think ?

**Comment by adrianeboyd** [comment]
You won't be able to split your future data into only those sections with an entity exactly in the middle, so it doesn't make sense to have your training data look like option A. I would try training with all your data, just split up into smaller "documents" in a way that you can also reliably split future data (paragraphs, pages, groups of 10 sentences, groups of 150 tokens, ...).

The NER model can handle texts with `\n` in it with no problems. The only thing it doesn't support is entities that start or end with whitespace.

JSON libraries should handle newline escaping, so you shouldn't need to modify your texts:

```
>>> import json
>>> json.dumps("asdf\n")
'"asdf\\n"'
>>> json.loads(json.dumps("asdf\n"))
'asdf\n'
```

**Comment by davidbren** [comment]
I get your point but I will have to ensure that whatever sections I do make don't split entities. So at prediction time I will not have this information either ?

**Comment by davidbren** [comment]
I have split the training data using \n. Each example will contain x no of lines. 
So a training doc will 
[
   ["lines 1 -5", {"entities": []}],
   ["lines 6 -10", {"entities": [person, place, thing etc]}],
   etc etc ...
]
At prediction time I am simply going to break my incoming doc into the same format without the entities. Does this seem correct to you ?

[
   ["lines 1 -5"],
   ["lines 6 -10"],
]

**Comment by davidbren** [comment]
The above will not work during the prediction loop the model throws an error 
Expecting a string but receiving a list !

    for input_ in testData:
        pred_value = ner_model(input_)

So it seems that I will have to send each section to the model for prediction ? 
Then compile the results. 
Then in my case I need to keep track of the returned positions so that I know where they occur within the whole document ! 
Is this correct ? If so it will be pretty painful ..

**Comment by svlandeg** [comment]
You will indeed need to track the original offsets of the sentences/paragraphs in the original docs...

**Comment by svlandeg** [comment]
Sorry, hit "close and comment" instead of "comment". Let us know if you still run into issues!
