### ISSUE TITLE
Is there a way to search for similar words faster using the similarity function ?

### ISSUE THREAD

**Issue by venkarafa** [explosion/spaCy#4986]
This is not specifically an issue or a bug. I am just looking for help in terms of optimizing the code.
I am trying to find similar words between one list of words with the the other through the .similarity function. The issue is that it takes a lot of time to render the results (~1 sec) if I look for say 5 similar words. I understand that there are ways like ANNOY or FAISS but perhaps one loses out on little bit of accuracy in both. Hence I would like to know if there are ways to speed up finding similar words through the existing similarity function itself ? It would be great if anyone can provide examples of multiprocessing or multithreading the below code (if that helps in speeding up)

## How to reproduce the behaviour
```
import en_vectors_web_lg
nlp = en_vectors_web_lg.load()
listx =['HSBC', 'JP Morgan',......] #500 words lists
listy = ['Currency','Blockchain'.......] #1000 words lists
s_words = []
for token1 in listy:
    list_to_sort = [] 
    for token2 in listx:    
        list_to_sort.append((token1, token2,nlp(str(token1)).similarity(nlp(str(token2)))))
        sorted_list = sorted(list_to_sort, key = itemgetter(2), reverse=True)[0][:2]
        s_words.append(sorted_list)
```

## Your Environment
Operating System: Windows 10
Python Version Used: 3.7
spaCy Version Used: 2.2.3

**Comment by adrianeboyd** [comment]
Preprocess all your strings once initially with `nlp()` or `list(nlp.pipe())` to work with lists of docs instead of calling `nlp()` repeatedly for the same text. (The indentation of the last two lines doesn't look right, either.)

It should be relatively easy to use multiprocessing to speed this up because the calculations within `.similarity()` are all independent, but there aren't any built-in methods in spacy to handle this for you. The libraries you mention sound like good options for larger data sizes, since this still isn't going to scale well.

**Comment by venkarafa** [comment]
Thank you @adrianeboyd .
