### ISSUE TITLE
Strange behavior with pre-tokenized text

### ISSUE THREAD

**Issue by interlark** [explosion/spaCy#5002]
I work with pre-tokenized text and noticed that Spacy can't get lemma for some words while with non-pretokenized text it can. For example:
```python3
import spacy

nlp = spacy.load('en_core_web_sm')
for token in nlp("I'd like to visit Paris"):
  print(token.text, token.lemma_)

nlp.tokenizer = nlp.tokenizer.tokens_from_list
for token in nlp(["I", "'d", "like", "to", "visit", "Paris"]):
  print(token.text, token.lemma_)
```

```text
I -PRON-
'd would
like like
to to
visit visit
Paris Paris

I -PRON-
'd 'd
like like
to to
visit visit
Paris Paris
```
On this example you can see that with pre-tokenized text **would** lemma is missing.

Tested on Linux with python3, spacy==2.2.3

**Comment by adrianeboyd** [comment]
This is because the lemma is being set by a tokenizer exception, so if you don't run the tokenizer, it doesn't get set in the same way.

You can see all the features that are set by tokenizer exceptions here: https://github.com/explosion/spaCy/blob/v2.2.3/spacy/lang/en/tokenizer_exceptions.py

In general, we've realized it wasn't a good idea to let the tokenizer set anything beyond tokens (just `orth` and sometimes also `norm`), so this will be moved to a better spot in the pipeline in the future.
