### ISSUE TITLE
Broken french import: cannot import FrenchLemmatizer with 2.2.3

### ISSUE THREAD

**Issue by smagnan** [explosion/spaCy#5023]
## How to reproduce the behaviour
I recently updated my spacy with `pip3 install -U spacy`, I didn't try to replicate the problem on an other machine yet since I have none available.

After the update (and fr model download), I can't import the french language from spacy (Lang/fr). Other languages work fine (I tried en, de etc...)

## Your Environment
* Operating System: Ubuntu 18.04
* Python Version Used: 3.6
* spaCy Version Used: 2.2.3

## Issue
Error: `ImportError: [E048] Can't import language fr from spacy.lang: cannot import name 'FrenchLemmatizer'`

First I have a "lemmatizer" folder in lang/fr that I can't find on GitHub (where there is only a lemmatizer.py file)

After the install the content of the `__init__.py` file in that folder is as follows:

```
# coding: utf8
from __future__ import unicode_literals

from .lookup import LOOKUP
from ._adjectives import ADJECTIVES
from ._adjectives_irreg import ADJECTIVES_IRREG
from ._adp_irreg import ADP_IRREG
from ._adverbs import ADVERBS
from ._auxiliary_verbs_irreg import AUXILIARY_VERBS_IRREG
from ._cconj_irreg import CCONJ_IRREG
from ._dets_irreg import DETS_IRREG
from ._lemma_rules import ADJECTIVE_RULES, NOUN_RULES, VERB_RULES
from ._nouns import NOUNS
from ._nouns_irreg import NOUNS_IRREG
from ._pronouns_irreg import PRONOUNS_IRREG
from ._sconj_irreg import SCONJ_IRREG
from ._verbs import VERBS
from ._verbs_irreg import VERBS_IRREG


LEMMA_INDEX = {'adj': ADJECTIVES, 'adv': ADVERBS, 'noun': NOUNS, 'verb': VERBS}

LEMMA_EXC = {'adj': ADJECTIVES_IRREG, 'adp': ADP_IRREG, 'aux': AUXILIARY_VERBS_IRREG,
             'cconj': CCONJ_IRREG, 'det': DETS_IRREG, 'noun': NOUNS_IRREG, 'verb': VERBS_IRREG, 
             'pron': PRONOUNS_IRREG, 'sconj': SCONJ_IRREG}

LEMMA_RULES = {'adj': ADJECTIVE_RULES, 'noun': NOUN_RULES, 'verb': VERB_RULES}
```

I don't know if it is an issue with the package via pip but the different structure seems to be what makes the import fail.
This code is different from anything that I can find on GitHub on any branches right now.

Not sure if a bug or install issue (I tried re-installing spacy but the file still seems incorrect, can't import the Lemmatizer. No issues with spacy <2.2)

`python3 spacy download fr` runs and links fine, just the Lemmatizer import is broken

**Comment by adrianeboyd** [comment]
Hi, this is usually because there are some files from the older version that didn't get cleaned up correctly during the upgrade. Can you try uninstalling spacy completely with `pip3` and then reinstalling? Right after uninstalling, you can double-check that the `spacy` directory where you found `lang/fr`before has been removed completely, and then reinstall.

Your downloaded models will still be installed, but the symlinks for the shortcut names like `en` and `fr` will be missing. You can run `spacy validate` to see what's installed and run `spacy link fr_core_new_sm fr` to recreate them for any individual models.

**Comment by smagnan** [comment]
Seems like this is what happened, some files were not cleaned when upgrading spacy. I already tried uninstalling and re-installing spacy before but it still did not clean the files. So I ended up uninstalling, cleaning the files manually and re-installing spacy, and spacy was installed correctly to 2.2.3. I assumed that when uninstalling pip would always delete the folder and its content, but apparently not.

My only issue is that, whenever I download a lang model, the command tries to re-install lots of packages and spacy, and then I segfaults: Example:

```
Successfully installed blis-0.4.1 catalogue-1.0.0 [...] zipp-3.0.0
✔ Download and installation successful
You can now load the model via spacy.load('fr_core_news_sm')
[1]    22564 segmentation fault (core dumped)  python3 -m spacy download fr
```

which means the models always gets downloaded but linking doesn't happen, so I always end up doing a manual linking (as you mentioned, `spacy link fr_core_new_sm fr` etc...). I thought that fixing my spacy install would solve this issue too, hoping it was just a corrupt install causing all the issues, but apparently not. My guess is that a package that spacy uses is currently installed with a version spacy is not compatible with (this happened to me already, with the `catalog` package that I had to downgrade from 2.0.0 to 1.0.0).

Anyway, this is a different issue so I will mark the current issue as resolved.

**Comment by adrianeboyd** [comment]
It's not ideal, but sometimes our best advice is to try everything in a new virtual environment because uninstalls and upgrades with `pip` don't always clean up everything as well as you'd hope.

You might also see if your issue looks similar to #4838. (We would strongly recommend using a virtual environment, though. If something only works with `sudo` there's something more serious wrong with your virtual environment and/or python installation.)
