### ISSUE TITLE
AttributeError: type object 'cupy.core.core.Indexer' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by jeromemassot** [explosion/spaCy#5031]
Hi Explosion team and contributors,

Sorry to bother you but the old issue with cupy is still present on my machine, despite an update of the Spacy environment.

## How to reproduce the problem
import spacy

## Error message
cupy\core\carray.pxi in init cupy.core.core()
AttributeError: type object 'cupy.core.core.Indexer' has no attribute '__reduce_cython__'

## Your Environment
* Operating System: WIN10
* Python Version Used: Python 3.6.5 Anaconda. Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
* spaCy Version Used: spacy==2.2.3
* Environment Information: cuda 10.0

I really need to work with a full spacy install in my local computer and not using any container solution. Is there any solution to by-pass this issue with cupy?

Thanks a lot

Best regards

Jerome

**Comment by adrianeboyd** [comment]
Hi, from similar bug reports, this is often because the CUDA version for cupy doesn't match the installed CUDA version. Check the installed CUDA version with `nvcc --version` and then install the matching version with `pip install spacy[cuda100]` or `pip install spacy cupy-cuda100`.

It could help to check which version of `cupy-cuda` is currently installed with `pip list` and run `pip uninstall cupy-cudaXXX cupy` first to clean up older versions.

If you're still having problems, it's often helpful to try this in a new clean virtual environment because upgrades and uninstalls with `pip` sometimes leave stale files/packages.
