### ISSUE TITLE
Bad sentence splitting

### ISSUE THREAD

**Issue by darabos** [explosion/spaCy#5052]
## How to reproduce the behaviour

```python
import spacy
nlp = spacy.load('en_core_web_sm')
for s in nlp('Say "A major second from D we find E".').sents:
  print(s)
for s in nlp('B follows A. Then comes C.').sents:
  print(s)
```

The output is surprising:
```
Say "A major second from D
we find E".
B follows A. Then comes C.
```

Why does it split the first string? Why does it not split the second string?

## Your Environment
* **spaCy version:** 2.1.4
* **Platform:** Linux-4.19.0-8-amd64-x86_64-with-debian-10.3
* **Python version:** 3.7.0

**Comment by darabos** [comment]
I don't know much about spaCy, but the second case seems simpler. The tokenizer just marks `A.` as a single token. This happens with other letters too. (Is there a way to prevent this?)

But I have no idea about the first one. The tokenization looks good. And small changes to the text make the issue go away. (Other letters instead of `D` don't do it. Doesn't happen with a lowercase `A`. Doesn't happen if I remove `major`.)

**Comment by adrianeboyd** [comment]
`spacy` is a little unusual because it uses the dependency parser to set sentence boundaries. The parser is sensitive to the exact form of each token, which is why minor changes to the text produce different sentence boundaries. Your texts are also pretty different from its training corpus (mostly newspaper-type text), so it may not perform well. Unfortunately, the only way to modify the parser's behavior is to update it with new examples, which need to be full dependency parses, which is not feasible for most use cases.

As an alternative, you could try the `sentencizer`, which does very simple rule-based sentence segmentation. (In spacy v3 there will be a new statistical component that just does sentence splitting, so you'll be able to train it with a list of sentences.)

To change the tokenization, you have to modify the rule-based tokenizer, which involves several regular expressions and a list of exceptions. In v2.2.3 there's a new `tokenizer.explain()` method that makes it easier to debug:

```
>>> from spacy.lang.en import English
>>> nlp = English()
>>> nlp.tokenizer.explain("A.")
[('TOKEN', 'A.')]
>>> nlp.tokenizer.explain("a.")
[('SPECIAL-1', 'a.')]
```

`A.` is because `.` is only split off as a suffix in certain cases determined by the tokenizer suffix patterns. The default is `A.` because this is often something like a middle initial in a name. In contrast, `a.` is a tokenizer exception. More details: https://spacy.io/usage/linguistic-features#tokenization

**Comment by darabos** [comment]
Thanks for the detailed answer, very helpful! In my case I'd be fine with just splitting sentences on periods. I can do that with `text.split('.')`. But then I want to parse those sentences with spaCy. Is there a way to tell it to not do any further sentence splits?

**Comment by adrianeboyd** [comment]
You can use the `sentencizer` and provide ['.'] as the only punctuation it should split on: https://spacy.io/api/sentencizer

**Comment by darabos** [comment]
I'm noticing some regression from spaCy 2.1.x to 2.2.x too. Not for my pervious examples, but for `What is the color of the ball I hold?`:

```python
>>> import spacy
>>> spacy.__version__
'2.1.9'
>>> nlp = spacy.load('en_core_web_sm')
>>> for s in nlp('What is the color of the ball I hold?').sents:
...   print(s)
... 
What is the color of the ball I hold?
```

```python
>>> import spacy
>>> spacy.__version__
'2.2.3'
>>> nlp = spacy.load('en_core_web_sm')
>>> for s in nlp('What is the color of the ball I hold?').sents:
...   print(s)
... 
What is the color of the ball
I hold?
```

**Comment by darabos** [comment]
A workaround, in case it's useful for someone:
```python
import spacy
def simplesplitter(doc):
  ended = True
  for t in doc:
    t.is_sent_start = ended
    ended = t.tag_ == '.'
  return doc
nlp = spacy.load('en_core_web_sm', disable=['parser'])
nlp.add_pipe(simplesplitter)
```
(I never wrote a custom component before, so it took a bit to figure it out. It's a super nice API though!)

**Comment by adrianeboyd** [comment]
Thanks for sharing your solution!
