### ISSUE TITLE
PhraseMatcher cannot find all single character tokens

### ISSUE THREAD

**Issue by heyalistair** [explosion/spaCy#5054]
## How to reproduce the behavior
```
import spacy
from spacy.matcher import PhraseMatcher

nlp = spacy.load('en_core_web_sm')
matcher = PhraseMatcher(nlp.vocab)
terms = ["Hi", "H"]
# Only run nlp.make_doc to speed things up
patterns = [nlp.make_doc(text) for text in terms]
matcher.add("TerminologyList", None, *patterns)

doc = nlp("This will be found: Hi. This will not be found: H.")
matches = matcher(doc)
for match_id, start, end in matches:
    span = doc[start:end]
    print(span.text)
```

Expected output:
```
Hi
H
```

Actual output:
```
Hi
```
The `H` is not found.

Other of examples of test sentences I have tried:
`Testing single character matches: H.` -> `H` is **not** found.
`Testing single character matches: 'H'.` -> `H` is found.
`Testing single character matches: (H).` -> `H` is found.
`Testing H single character matches.` -> `H` is found.
`Testing H, single character matches.` -> `H` is found.
`Testing H. single character matches.` -> `H` is **not** found.
`Testing Hi. single character matches.` -> `Hi` is found.

Seems to have trouble when the single character is followed by a period.

## Your Environment
I'm running this from the Binder on the website.

**Comment by adrianeboyd** [comment]
In order to be fast, the `PhraseMatcher` is searching over tokens rather than individual characters or strings. You can see what the `PhraseMatcher` is going to look for by looking at the tokens in `patterns`:

```
for pattern_doc in patterns:
    print([t.text for t in pattern_doc]
```

Similarly, you can inspect the tokens in your test sentences to see if these texts are tokenized the same way. If the sequence of tokens in the pattern and in your test sentence aren't identical, the `PhraseMatcher` is not going to match them.

The main issue here is that `H.` is tokenized as a single token by the default tokenizer because it's often an abbreviation like a middle initial in a name. If you need to, you can customize the tokenizer for your task: https://spacy.io/usage/linguistic-features#tokenization

**Comment by heyalistair** [comment]
Makes sense! I like it. Thanks for this explanation.

(Feel free to close this issue.)
