### ISSUE TITLE
Upgrades for spacy 1.x

### ISSUE THREAD

**Issue by chrisjbryant** [explosion/spaCy#5068]
I just wanted to ask if there are any plans to upgrade spacy 1 with any of the features introduced in spacy 2; e.g. improvements to the lemmatiser and custom token attributes.

I mainly use spacy for the POS tagger, but can't justify moving to spacy 2 for such small gains at such a significant cost to speed (cf. [your benchmarks](https://spacy.io/usage/facts-figures#spacy-models), which are consistent with my own experiments).

While I know spacy 2 is your focus, it would be great if there were occasional updates to spacy 1, since I'm sure some of the changes are backwards compatible.

**Comment by honnibal** [comment]
Hi Chris,

It's too hard to port the changes back, because there are too many differences from V1, especially with the stateful stringstore. What we'd be doing instead is porting the v1 model to work with v3: we can have a linear model that works like the v1 model, and should be similar in speed, but working with the new version.
