### ISSUE TITLE
keyError when looking up a hash in vocab.strings from spacy.matcher.PhraseMatcher

### ISSUE THREAD

**Issue by IamVinaySharma** [explosion/spaCy#5069]
I got a `KeyError` when looking up a hash in `vocab.strings` from `PhraseMatcher match id` with `en_core_web_sm.`

##Steps to replicate:
1. Add all the patterns to PhraseMatcher object.
2. Serialise PhraseMatcher object using pickle.
3. deserialise PhraseMatcher object and get match_id.
4. try to access nlp.vocab.strings[match_id]

Current Behaviour:
```
KeyError: "[E018] Can't retrieve string for hash '1799008774848867813'. This usually refers to an issue with the `Vocab` or `StringStore`."
```
Expected Behaviour:
Name of matcher/string_id should be returned.

## Your Environment

* Python Version Used: 3.6
* spaCy Version Used: 2.2.3
* Models: en_core_web_sm

**Comment by adrianeboyd** [comment]
Hmm, I couldn't replicate this easily. Could you provide a minimal example script that shows all the steps that lead to this error?

Looking at step 4 above, one thing that might be the issue is that you need to look up the match id in the `PhraseMatcher`'s vocab and not the vocab from another `nlp` pipeline that's been loaded separately:

```
pickled_pm = pickle.dumps(original_phrasematcher)
phrasematcher = pickle.loads(pickled_pm)
print(phrasematcher.vocab.strings[match_id])
```

**Comment by IamVinaySharma** [comment]
Thanks @adrianeboyd , your suggestion is correct, need to use `phrasematcher.vocab.strings[match_id]`.
