### ISSUE TITLE
Allow extra args/kwargs in make_doc()

### ISSUE THREAD

**Issue by eddie-scio** [explosion/spaCy#5074]
## Feature description
I have a use case where I want a single instance of a model ([`Language`](https://spacy.io/api/language#attributes)) to be called with varying tokenization behavior.  Unfortunately, `make_doc` has a fixed signature which only takes a unicode text -- if it were more flexible, then I could propagate my `args / kwargs` to the underlying custom `Tokenizer` I have.  Let me know if that makes sense -- I'm open to any existing way to make this work (aside from smuggling my args into the unicode `text` arg and splitting them out on the other side).

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

Probably not?

**Comment by adrianeboyd** [comment]
Yes, this is a situation without a particularly elegant solution right now. A `Language` pipeline is only set up to start with a tokenizer and the main problem is that you can't easily call the remainder of the pipeline in one step on an existing `Doc`.

What you can currently do: tokenize the document outside of the pipeline, create the document with the `Doc` constructor (https://spacy.io/api/doc#init), and call the pipeline components individually:

```
doc = Doc(nlp.vocab, words=["The", "words", ...], spaces=[True, True, ...])
nlp.tagger(doc)
nlp.parser(doc)
nlp.ner(doc)
nlp.get_pipe("my_custom_component")(doc)
```

For better performance, you want to use `nlp.pipe()`, which would look similar:

```
nlp.tagger.pipe(docs)
nlp.parser.pipe(docs)
nlp.ner.pipe(docs)
```

There are ways that you could use a pipeline that just contains a spacy tokenizer for the first step and avoid creating the `Doc` by hand (since it sounds like you've already written tokenizers), but it involves some extra steps to sync the vocab/strings between the tokenizer pipeline and the model pipeline.

**Comment by eddie-scio** [comment]
Got it, that makes sense.  My tokenizer is already calling the `Doc` constructor in its `__call__` implementation, so I can just factor that out of the pipeline and replace all my calls to `my_language._model(s)` and `my_language._model.pipe(s_list)` with the individual component calls.  That's a fine workaround for now, thank you for the suggestion and quick reply!

**Comment by eddie-scio** [comment]
One follow-up -- should I expect a performance decrease if the tokenizer is no longer part of the efficient batch `.pipe`?

**Comment by adrianeboyd** [comment]
No, the tokenizer isn't affected by batching. The batching with `.pipe()` only makes a difference for the statistical models.

If you want to see, here's where `Language.pipe()` just calls `make_doc()` before applying the pipeline components (this is the simple version without multiprocessing):

https://github.com/explosion/spaCy/blob/2281c4708cc3dfa68ffcdff5554c18d8fae0c9de/spacy/language.py#L801-L805

Also, both `nlp()` and `nlp.pipe()` return the doc/docs, but all the annotations are done in place (no new `Doc`s are created at any point), so you can say `nlp.tagger(doc)` or `doc = nlp.tagger(doc)` and the final result for that individual `doc` is the same.

**Comment by eddie-scio** [comment]
Awesome, thank you so much!

**Comment by eddie-scio** [comment]
Is there an easy way I can use `n_process=-1` in the `component.pipe()` interface other than re-implementing what's done [here](https://github.com/explosion/spaCy/blob/2281c4708cc3dfa68ffcdff5554c18d8fae0c9de/spacy/language.py#L837)?

**Comment by adrianeboyd** [comment]
Hmm, I think you'd be limited to using it at the component level, so `nlp.tagger.pipe(texts, n_process=-1)`. With larger batch sizes, maybe the overall performance could be similar, although the multiprocessing overhead may still overwhelm everything else, I'm not sure?
