### ISSUE TITLE
It should be clearer that Vectors.from_glove doesn't use the binary glove creates

### ISSUE THREAD

**Issue by hoagy-davis-digges** [explosion/spaCy#5086]
Glove generates a vectors.bin file and a vocab.txt file. It is not clear from the documentation that the files expected by the Vectors.from_glove method are different formats to the ones glove creates.

# Which page or section is this issue related to?
https://spacy.io/api/vectors#from_glove

**Comment by adrianeboyd** [comment]
You're right that this isn't able to load the format produced by glove. I'm not entirely sure at this point, but I think this is older code that may be intended to read an internal numpy binary format rather than the one produced by glove.

Instead of this method, I'd recommend using `spacy init-model` to load vectors from a text file:

https://spacy.io/api/cli#init-model

You'll need to make sure the dimensions are provided in the first line (`-write-header 1` option with glove). This will create and save a spacy model that you can load with `spacy.load()` that contains the vectors as part of the vocab (`nlp.vocab.vectors`).
