### ISSUE TITLE
How do you get the mapping from the POS tag/NER tag to 64Int in to_array function

### ISSUE THREAD

**Issue by Lee-zix** [explosion/spaCy#5090]
Dear authors,
    Great Program! I am confused that how to get the mapping function from pos_(str) to pos(int), or a specific LEMMA to an int index. I just want to revise some values in the array from spacy according to my own tools. But I do not know how to generate the value(int) of the array from my own result(string). Where are the details of generating array from a spacy doc in the to_array() function?

**Comment by adrianeboyd** [comment]
This is handled by the `StringStore`: https://spacy.io/api/stringstore

You can generate the integer hash for any string through the `StringStore` in your pipeline:

```
hash = nlp.vocab.strings[string]
```

This generates the hash without adding it to the `StringStore`.

If you're modifying the array generated with `Doc.to_array()`, you'll want to add all the new strings to the `StringStore` instead of just looking them up, otherwise you'll get errors when you try to inspect `.pos_` or `.lemma_` for the reloaded document. To add a string (which also returns the hash), use:

```
hash = nlp.vocab.strings.add(string)
```

As long as you've added a string a some point, you can do the reverse lookup with:

```
nlp.vocab.strings[hash]
```

**Comment by svlandeg** [comment]
Assuming @adrianeboyd 's answer was sufficient, I'll go ahead and close this. Let us know if you run into specific problems though!

**Comment by Lee-zix** [comment]
Thanks very much for your timely reply!! It is exactly the answer what i want!!
