### ISSUE TITLE
Doc extension call Getter function every time when try to read attribute

### ISSUE THREAD

**Issue by vbaidin** [explosion/spaCy#5104]
## How to reproduce the behaviour

I supposed that getter function called once when a document is created to set an attribute value, but if it is called every time, It is too time-consuming and inefficient. 

## Your Environment

* Operating System: win10
* Python Version Used: 3.7
* spaCy Version Used: last version
* Environment Information:

**Comment by adrianeboyd** [comment]
Yes, if the custom extension has a getter, it will be called every time the extension is accessed. The return value is not cached or stored in any way.

In order to keep the custom extensions as flexible as possible (you could potentially have a getter with dynamic results), I think caching / storing is going to be left up to the user here. You could store the value in a second extension attribute so that you only access the time-consuming getter one time if the stored value is unset, or you could add some form of caching to the getter itself, if that makes more sense for your task.
