### ISSUE TITLE
Unable to create custom Spacy model w/ Ontonotes that matches en_core_web_lg f-score

### ISSUE THREAD

**Issue by zredlined** [explosion/spaCy#5149]
Hello- I am trying to recreate the en_core_web_lg model https://github.com/explosion/spacy-models/releases//tag/en_core_web_lg-2.2.5 model by following the steps in the model description and assets folder including:

* ontonotes 5 converted to Spacy JSONL training format (complete, using 80/10/10 split)
* commoncrawl glove vectors 684830 keys, 684831 unique vectors (300 dimensions)
* parser, tagger, ner pipeline

and training using the spacy train CLI. The documentation lists a entity recognition F-score of 86.55, but the highest that I've been able to achieve is in the low 60's. **Any tips on how I can recreate the same performance that you have been able to achieve for the spacy provided en_core_web_lg model?**

Here is a sample record from my converted training set:
https://gist.github.com/zredlined/2840f74b1d7b7d05880a3a77c67c5ad8

## Your Environment
* Operating System: tested OS x and Ubuntu Linux
* Python Version Used: 3.7.5
* spaCy Version Used: 2.2.4
* Environment Information: Tested training w/CPU and GPU

Training command: 
`python -m spacy train en ./model ./onto_train.jsonl ./onto_eval.jsonl --n-iter 100 -g -1 -ne 4 -v ./en_vectors_web_lg/en_vectors_web_lg-2.1.0/`

First epochs
```
Itn  Tag Loss    Tag %    Dep Loss    UAS     LAS    NER Loss   NER P   NER R   NER F   Token %  CPU WPS
---  ---------  --------  ---------  ------  ------  ---------  ------  ------  ------  -------  -------
  1    698.317    97.701    791.601   0.000   0.000  173926.793  71.153  44.440  54.710   97.498     8685
  2      0.000    97.701    160.631   0.000   0.000  109753.953  72.673  45.349  55.848   97.498     9241
  3      0.000    97.701    130.575   0.000   0.000  102265.300  74.405  45.466  56.443   97.498     9201
  4      0.000    97.701    111.546   0.000   0.000  95595.284  76.709  45.701  57.277   97.498     9028
  5      0.000    97.701    114.769   0.000   0.000  92700.300  76.888  45.818  57.419   97.498     9244
  6      0.000    97.701     76.018   0.000   0.000  90099.216  77.653  45.728  57.560   97.498     9205
  7      0.000    97.701     96.365   0.000   0.000  87273.231  77.592  45.783  57.587   97.498     8927
  8      0.000    97.701     57.753   0.000   0.000  84875.610  77.551  45.818  57.603   97.498     9122
  9      0.000    97.701     62.508   0.000   0.000  83909.007  78.195  45.859  57.813   97.498     9274
 10      0.000    97.701     77.553   0.000   0.000  80663.197  77.919  45.976  57.830   97.498     9115
```

There appears to be a significant delta between the Recall in my test and explosion's model- might be a hint as to what's going on.

**Spacy/explosion en_core_web_lg model performance** from https://github.com/explosion/spacy-models/releases//tag/en_core_web_lg-2.2.5
ENTS_F | 86.55
ENTS_P | 86.74
ENTS_R | 86.36

**Comment by adrianeboyd** [comment]
How did you create your train/eval split? If you haven't, try sampling evenly from the individual OntoNotes subdirectories like bc/bn/mz/etc. because they vary a lot in genre and performance will also vary a lot between them. You don't have to keep everything into one huge file, either:`spacy train` can use a directory as the `train_path` and it will recursively find all `.json` files in that directory.

A quick count of the number of tokens from each subdirectory for our internal version:

```
  29962 ./dev/bc.json
  25274 ./dev/bn.json
  15422 ./dev/mz.json
 147923 ./dev/nw.json
  25206 ./dev/pt.json
  11467 ./dev/tc.json
  36348 ./dev/wb.json
  35952 ./test/bc.json
  26423 ./test/bn.json
  17875 ./test/mz.json
  60745 ./test/nw.json
  25883 ./test/pt.json
  10976 ./test/tc.json
  38487 ./test/wb.json
 173321 ./train/bc.json
 206924 ./train/bn.json
 164222 ./train/mz.json
 877680 ./train/nw.json
 297049 ./train/pt.json
  92020 ./train/tc.json
 286043 ./train/wb.json
```

All our model training and evaluation just use the train+dev subcorpora, so the current `en_core_web` models use ~80% of OntoNotes for training and ~10% for evaluation. To speed up your training, you can use `spacy train -p ner` to just train the `ner` component if the other annotation isn't available.

The only thing that looks unusual in your sample data is the `orth` value, where we wouldn't have any trailing whitespace. When `spacy train` loads the training corpus, it has an alignment step to align the `orth` values with the `raw` text, so you don't need the whitespace in `orth`. If this did cause problems with vectors (I don't think it does, but it could be that a vector for `"word"` is available but not `"word "`), the performance without vectors should look like `en_core_web_sm`, and this is pretty different. I've never tried training models with extra whitespace in `orth` and I'm not 100% what the side effects are.

(As an aside, we are planning to update the training format for v3 and that will include the whitespace at the end of the token text so that `raw` can be removed completely. Then there's no duplicated text content or need to perform an alignment.)
