### ISSUE TITLE
Minimal installation footprint 

### ISSUE THREAD

**Issue by Adblu** [explosion/spaCy#5158]
Hi. 
I am building a software which uses spacy. One of the requirements I have is to make it serverless on lambda. 

The question is, is it possible to install spacy with bare minimum size of library ? 
For example I can compile numpy and scipy with 
`CFLAGS="-g0 -Wl,--strip-all -I/usr/include:/usr/local/include -L/usr/lib:/usr/local/lib" `
which allows to decrease size of the libraries. 
How about spacy ?

**Comment by honnibal** [comment]
Hi Adblu,

You might be able to reduce the binary sizes that way, I'm not sure. You should be able to set the cflags in a similar way for spaCy, although you might have to edit the setup.py. Ultimately it will be up to you to experiment with this --- it's not a use-case we support directly, because in most cases the size of the data is large enough that the binary sizes aren't a priority.
