### ISSUE TITLE
How can I get the accuracy at each iteration?

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#5165]
version: spacy 2.2.4

Using the spacy training script provided here https://github.com/explosion/spaCy/blob/master/examples/training/train_ner.py

In addition to the already provided loss that is being output at each iteration, how can we output other metrics like accuracy, precision etc.

Thanks

**Comment by adrianeboyd** [comment]
Use the `spacy train` CLI instead of this script. The example script is mainly intended as a short demo and `spacy train` provides better defaults and a lot more options. (We use `spacy train` internally to train all provided models.)

Basic method for converting data from the `TRAIN_DATA` format in the example script:

```
import spacy
import srsly
from spacy.gold import docs_to_json, biluo_tags_from_offsets, spans_from_biluo_tags

TRAIN_DATA = [
    ("Who is Shaka Khan?", {"entities": [(7, 17, "PERSON")]}),
    ("I like London and Berlin.", {"entities": [(7, 13, "LOC"), (18, 24, "LOC")]}),
]

# parser needed for sentence boundaries, otherwise use sentencizer
nlp = spacy.load('en_core_web_sm', disable=["tagger", "ner"]) 

docs = []
for text, annot in TRAIN_DATA:
    doc = nlp(text)
    tags = biluo_tags_from_offsets(doc, annot['entities'])
    entities = spans_from_biluo_tags(doc, tags)
    doc.ents = entities
    docs.append(doc)

srsly.write_json("spacy_format.json", [docs_to_json(docs)])
```

(Originally written at https://stackoverflow.com/a/59209377/461847 with some other potentially useful notes in the comments.)

Check `tags` for misaligned entity spans (`-` instead of `BILUO` if the character offsets don't line up with token boundaries).
