### ISSUE TITLE
OSError: [E050] Can't find model 'nl_core_news_sm' 

### ISSUE THREAD

**Issue by NielsRogge** [explosion/spaCy#5183]
Everytime I install the Dutch model in Google Colab by running
    
     !pip install -U spacy`
     !python -m spacy download nl_core_news_sm`

I get the message 

     ✔ Download and installation successful
     You can now load the model via spacy.load('nl_core_news_sm')`

which is good! ... however, when I then run

    import spacy
    nlp = spacy.load('nl_core_news_sm')

I get

`OSError: [E050] Can't find model 'nl_core_news_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.`

This is annoying, because I need to restart my runtime, run again from top to bottom and then it works (for some reason). For the English model however, there are no installation problems. Is this a bug or does this have to do with Google Colab?

**Comment by ines** [comment]
Hmm, this is strange, especially if you're using the latest version of spaCy 🤔 This addition to the `download` command should work around the problem of the listing of installed packages not refreshing:

https://github.com/explosion/spaCy/blob/5f2afa047927675795f9cd11f4c5d2a520dd68cf/spacy/cli/download.py#L77-L81

> For the English model however, there are no installation problems. Is this a bug or does this have to do with Google Colab?

If I remember correctly, Google Colab comes preinstalled with spaCy and the English models. So that's likely why the package is detected as available, because it was already there before.

**Comment by NielsRogge** [comment]
> This addition to the `download` command should work around the problem of the listing of installed packages not refreshing:

Unfortunately, this doesn't seem to work in Google Colab. Only restarting the runtime enables spaCy to recognize the downloaded Dutch model.

**Comment by svlandeg** [comment]
I've had similar trouble in Jupyter notebook where I needed to restart the kernel before an installation would be properly visible and usable. I'm not sure this is a problem with spaCy though.

@NielsRogge : another workaround I was thinking off, is to just load the `nl_core_news_sm` model in a once-off script, and store it to a directory you can access from within your Google Colab script with `nlp.to_disk('my_local_copy')`. Then afterwards, you could just run `nlp=spacy.load('my_local_copy')` and you hopefully shouldn't have these linking/installations problems anymore.
