### ISSUE TITLE
DocBin.to_bytes fails with a "ValueError: bytes object is too large"

### ISSUE THREAD

**Issue by kuppulur** [explosion/spaCy#5219]
## How to reproduce the behaviour

I am trying to train a sense2vec model from scratch on a corpus which has around 5 million sentences (lines/docs). As the first step is to parse it and create a .spacy file, I ran the parse script on this corpus and the code crashes at ```doc_bin_bytes = doc_bin.to_bytes()``` with a value error saying the bytes object is too large. Can somebody help me with this issue? Thanks

## Your Environment

* Operating System: Ubuntu 16.04.6 LTS
* Python Version Used: 3.5.2
* spaCy Version Used: 2.2.4
* Environment Information:

**Comment by svlandeg** [comment]
Do I understand it correctly that each line is parsed as a separate `Doc`? So you have 5M `Doc`s in one `DocBin`? Can you paste the entire error trace?

**Comment by kuppulur** [comment]
@svlandeg yes that is correct. Please find the error trace below.
<img width="825" alt="spacy error" src="https://user-images.githubusercontent.com/3698879/77939157-9419b000-726b-11ea-998d-e660188517c9.png">

**Comment by kuppulur** [comment]
@svlandeg any pointers on this issue? Thanks

**Comment by svlandeg** [comment]
Apologies for the late follow-up. 

This seems related to Issue https://github.com/explosion/sense2vec/issues/102, which was addressed in PR https://github.com/explosion/sense2vec/pull/103.
So basically what you want to do in your code, is to use & store several doc_bin objects, instead of just one. Hope that works for you!
