### ISSUE TITLE
Consistency of stop-word lists across languages

### ISSUE THREAD

**Issue by gthb** [explosion/spaCy#5247]
I just noticed that the stopword lists for languages inconsistently include or don't include the words for “yes” and “no” (e.g. English and Icelandic and Danish and Japanese don't have them, German and Swedish and Norwegian and Russian and French and Polish do).

The way I noticed this (no surprise) is that I had an application where my entity linker matched the word “yes” in English data just fine, but didn't match the word “да” in the corresponding Russian data — and that's because the app asked the entity linker _not_ to find it, because it's a stopword in Russian.

This made me realize that Spacy doesn't have any guidelines aimed at making stopword lists _consistent_ among languages in Spacy.

Of course no general stopword list is going to be ideal for every particular task, and no set of stopword lists is going to be perfectly consistent across languages.

But would there still be some value in a minimal consistency rule/guideline? Something along the lines of:

> if word W1 in language L1 and word W2 in language L2 are quite nearly identical in meaning and common usage, then _either_ both languages' stop-word lists should include them, _or_ both should exclude them

**Comment by adrianeboyd** [comment]
The stop word lists are from a variety of sources / contributors and I don't think we have the resources to ensure this kind of consistency across languages. In most cases, like you mention, you'll want to customize the stop word lists for a particular task anyway. I think it's best to see spacy's stop word lists as a potentially helpful starting point, but that's all.

**Comment by gthb** [comment]
Sure, I don't mean some big harmonization effort to _ensure_ consistency, I just mean documenting some simple guidelines (but a bit more concrete than what's there already) for language contributors to follow, to _encourage and aid_ consistency.

**Comment by svlandeg** [comment]
But that assumes that language contributors are also fluent in other languages, right? If we would want to add this proposed solution of checking consistency between 2 languages, we'd need to consolidate the current lists first, because otherwise what should I do with the Dutch "yes" if English has it and French doesn't?

I agree with @adrianeboyd that the whole thing will be very difficult to manage / enforce.

But to be honest I've also wondered about these stop lists. It's fine to have them in a specific application, tailored towards your use-case. But right now the different lists in the different languages seem kind of arbitrary...

**Comment by adrianeboyd** [comment]
They are very arbitrary. I wouldn't mind if the mechanisms were there but the default lists were empty, so that users might be more aware that they do need to think about the details for each given task, especially whether separate treatment of stop words is useful at all. But I know users are used to having the provided lists available and it's not a major burden to keep distributing the lists in the form that we currently have.

**Comment by svlandeg** [comment]
Yea, I agree. I think we can tentavily close this for now. The current solution is not ideal, but there's no practical way to ensure consistency, and people have gotten used to having these lists...

Meanwhile @gthb : feel free to propose specific changes to the stopword lists in a PR, ofcourse! If you find for instance that "yes" is never a stopword unless in Russian, you could change it. Or you could just create your own application-specific stopword list, which is probably the best solution for you.
