### ISSUE TITLE
NER model 

### ISSUE THREAD

**Issue by Victorine-d** [explosion/spaCy#5274]
Hi ! 
(sorry for my english I'm french :) ) 

So, I use Spacy to create a model capable of recognizing quotes in a text. I have about 30,000 example quotes. I trained a model (to start I put 4,000 datas and 4,000 iterations) but when I test it on a text, it says that all sentences are quotes while no ... it does not happen to find the quotes. 

I don't know it comes from my data (I just put a quote and not a sentence)
I use the program of spacy.
I do not know how to do. Any ideas ?

**Comment by erotavlas** [comment]
Can you provide an example of a quote and a non-quote?

**Comment by Victorine-d** [comment]
Yes : Knaurs Lexikon der Technik, Droemersche Verlagsanstalt, Munchen 1988, p. 1010
or US 789789 A are the quotes. 
But my model says that : Preferred polyols are also described in US 5,538,531 is a quote also that just : US 5,538,531 is a quote.

**Comment by svlandeg** [comment]
> I don't know it comes from my data (I just put a quote and not a sentence)

I think this may be the problem: you have to feed full sentences to the training algorithm, with the boundaries of the quote entities specified. The [documentation](https://spacy.io/usage/training#example-train-ner) has some more information. Your training data should look something like this:
```
TRAIN_DATA = [
    ("Who is Shaka Khan?", {"entities": [(7, 17, "PERSON")]}),
    ("I like London and Berlin.", {"entities": [(7, 13, "LOC"), (18, 24, "LOC")]}),
]
```

**Comment by abinpaul1** [comment]
> Yes : Knaurs Lexikon der Technik, Droemersche Verlagsanstalt, Munchen 1988, p. 1010
> or US 789789 A are the quotes.
> But my model says that : Preferred polyols are also described in US 5,538,531 is a quote also that just : US 5,538,531 is a quote.

**Quoting the spaCy documentation**
If you’re using an existing model, make sure to mix in examples of other entity types that spaCy correctly recognized before. Otherwise, your model might learn the new type, but “forget” what it previously knew. This is also referred to as the “catastrophic forgetting” problem.

If you try to train a model with examples of just one single new entity type. It will adjust its weights to always predict it as the new entity type. Because just think about it, because based on your training data, the model would see a 100% accuracy if it classifies everything it gets as the new entity (QUOTES in your case).

**Comment by svlandeg** [comment]
@Victorine-d : Let us know if the problem persists after implementing these comments & suggestions!
