### ISSUE TITLE
Every Token Returned as a Sentence by Parser (CLI Train)

### ISSUE THREAD

**Issue by umarbutler** [explosion/spaCy#5291]
## How to reproduce the behaviour
I have a corpus that looks like this (using an example I made):
```
[{
	"id" : 1,
	"paragraphs" : [
		{
			"raw" : "ذهب عمر إلى السوق وسمع رجل",
			"sentences" : [{
				"tokens" : [{"id": 1, "ner": "O", "orth": "ذهب"}, {"id": 2, "ner": "U-RAWINAME", "orth": "عمر"}, {"id": 3, "ner": "O", "orth": "إلى"}, {"id": 4, "ner": "O", "orth": "السوق"}]
			},
			{
				"tokens" : [{"id": 5, "ner": "O", "orth": "وسمع"}, {"id": 6, "ner": "O", "orth": "رجل"}]
			}],
			"cats" : [{
				"label" : "khabar",
				"value" : 0
			},
			{
				"label" : "athar",
				"value" : 1
			}]
		}
	]
}]
```
I using the following command to train a parser (amongst other things) on this corpus:

> python3 -m spacy train ar models/test dataset/traintest.json dataset/evaltest.json --n-iter 100 --pipeline ner,parser,textcat --parser-multitasks dep --textcat-positive-label khabar --use-gpu 0

Then when I load the model and call doc.sents, every single token is recognised as an individual sentence. What I expect, however, is for only two sentences to be identified: "ذهب عمر إلى السوق" and "وسمع رجل".

I have tried using the aforementioned command with and without the ' --parser-multitasks dep' argument, with no change in output.

Is there's something I'm missing here? According to the docs, the parser also performs sentence segmentation. While I don't have any 'dep' attributes in my annotations, I didn't think that should affect sentence segmentation? If I do need dep labels and heads, should I identify the starting words of each sentence and make those words the heads of every other token in a given sentence?

## Your Environment

* Operating System: Windows 10 && Ubuntu 18.04
* Python Version Used: 3.6.9
* spaCy Version Used: 2.2.4
* Environment Information:

**Comment by adrianeboyd** [comment]
The parser does rely on information from the full dependency trees to set sentence boundaries. If it doesn't have dependency information, it assumes that each individual word is the root of a sentence, which is why you see this behavior. I don't think that it will work extremely well to have the first word of each sentence as the root, but it's possible it might work well enough as long as there are indicators like punctuation or capitalization near sentence boundaries.

If you haven't already, you could also try the "sentencizer" component, which is a very simple rule-based sentence splitter that splits on characters like `'.', '?', '!'`. I've tried to add sentence-final symbols for many character sets based on unicode categories, but if some are missing for your data you can initialize it with custom characters, too.

In spacy v3 there will be a "SentenceRecognizer" component that can predict sentence boundaries just from the sentence annotations in this format. The basics should be working on the "develop" branch, but things are still going to be a bit unstable there as we work out the final details for v3.

**Comment by umarbutler** [comment]
@adrianeboyd The problem is that the data I'm working with needs to be segmented into two distinct parts. Every doc has the same structure in terms of segmentation. The docs expected to be processed will also have this same structure. I guess one option would be to create a NER tagger for the word which splits the parts (probably not the best option, but it might work). Alternatively, I can do what I planned with dependency annotations. What would you suggest?

I couldn't use the "sentencizer" component because it's not actual a character that indicates a split, but a token. And that token could be in the first part, as well as the second part, so context is necessary to figure out whether it's actually splitting the parts.

If dep and ner annotations don't work, the final option is for me to just split the parts at the last occurrence of a ent. Ents are supposed to only be present in the first part, but sometimes they are identified in the second part, in which case, it would result in a wrong segmentation (which is why I was hoping to use spaCy to learn to segment the two parts of the text).

**Comment by adrianeboyd** [comment]
The sentencizer actually splits on full tokens not characters, but all the default tokens are single characters. If you have a custom token like `"__BREAK__"` (just as an example), the sentencizer would always treat that token as the end of a sentence, which sounds like it wouldn't be what you want anyway, though.

Depending on how hard it is to identify the context around the sentence break, you might be able to use a `Matcher` with a callback function that sets sentence boundaries by setting `Token.is_sent_start`.

The other option would be to use a tagger to do this, which is basically what the `SentenceRecognizer` in v3 does. If you're not otherwise training a tagger in your pipeline, you could use the `"tag"` feature in the training format to do this with a tagger. Then post-process the tags to use the sentence start tag to set `Token.is_sent_start`. I'd suggest two tags, one for sentence start and one for all other tokens. You have create up a fake tag map to map the tags to UPOS, but otherwise this is pretty easy to do with the current training format in v2.

**Comment by umarbutler** [comment]
@adrianeboyd Thanks for the suggestions! I'm not currently using a tagger, so I can do that. Would you suggest having four tags (beginPart1, inPart1, beginPart2, inPart2), or two tags, one of which is only used for Part2 (beginPart2, inPart), or two tags, both of which are used for both parts (beginPart, inPart).

Side question, what exactly is the difference between training via cli with two pipelines (ner, tagger) versus using --entity-multitasks?

Thanks again,
Umar
