### ISSUE TITLE
Create Doc object using char_span with start idx as whitespace

### ISSUE THREAD

**Issue by nipunsadvilkar** [explosion/spaCy#5295]
This is in continuation with https://github.com/nipunsadvilkar/pySBD/issues/55#issuecomment-579862408 where we want to get `Doc` object using `doc.char_span` method but since whitespace is not treated as a token we get `None` in return.

## Reproduce
```python
text = 'She turned to him, "This is great." She held the book out to show him.'
nlp = spacy.blank("en")
doc = nlp(text)
print([(token.idx, token.text) for token in doc])
```
> [(0, 'She'), (4, 'turned'), (11, 'to'), (14, 'him'), (17, ','), (19, '"'), (20, 'This'), (25, 'is'), (28, 'great'), (33, '.'), **(34, '"'), (36, 'She')**, (40, 'held'), (45, 'the'), (49, 'book'), (54, 'out'), (58, 'to'), (61, 'show'), (66, 'him'), (69, '.')]

Notice idx 35 is whitespace but not present as a token in the above output.

`pysbd` give char_span including that whitespace in the `text` case two spans - 
```
TextSpan(sent='She turned to him, "This is great."', start=0, end=35)
TextSpan(sent='She held the book out to show him.', start=35, end=69)
```
when we try to create doc objects with above start and end values. Second value returns None and when I exclude whitespace idx as a start, I get the `Doc` object.
```python
doc.char_span(0, 35)                                                                                                                              
# She turned to him, "This is great."

doc.char_span(35, 69)
# None

doc.char_span(36, 69)                                                                                                                             
# She held the book out to show him
```

Need help in finding workaround to fix this and get `Doc` object including whitespace at the start?

## Your Environment

* **spaCy version:** 2.1.9
* **Platform:** Darwin-18.0.0-x86_64-i386-64bit
* **Python version:** 3.6.8

**Comment by adrianeboyd** [comment]
Because of the way documents are represented internally (as a series of tokens that each have a boolean flag that represents whether they're followed by a single space), this is going to be fairly difficult to support, at least if you're using spacy's default tokenizers.

In order to create a document from a span with a leading whitespace, you would have to modify the document to create a space token that was previously just a boolean flag on the previous token and not a token on its own.

You could potentially construct a document where this boolean flag is false for all tokens and each space is its own token:

```
from spacy.tokens import Doc
from spacy.lang.en import English

nlp = English()
words = ['She', ' ', 'turned', ' ', 'to', ' ', 'him']
spaces = [False] * len(words)
doc = Doc(nlp.vocab, words=words, spaces=spaces)
assert doc.char_span(3, 10).text == " turned"
```

So it's theoretically possible, but this isn't easy to integrate into an existing spacy pipeline that is using the normal doc representation with `spaces`.

For this to work well in a default spacy pipeline, I think you would need to adjust the char spans so they fall on token boundaries. I'm not sure how frequently you run into this problem with the pybsd spacy component, but in this particular case it seems to be related to sentences that end with quotes?

```
>>> seg.segment("This is a sentence. Here is another.")
[TextSpan(sent='This is a sentence.', start=0, end=19), TextSpan(sent='Here is another.', start=20, end=36)]
>>> seg.segment("This is a sentence.\" Here is another.")
[TextSpan(sent='This is a sentence.', start=0, end=19), TextSpan(sent='" Here is another.', start=19, end=37)]
```

**Comment by nipunsadvilkar** [comment]
Got it. Thanks for the inputs 👍
