### ISSUE TITLE
What is the F1-score of your trained NEL model on dev data？

### ISSUE THREAD

**Issue by whuFSN** [explosion/spaCy#5297]
Thank you very much for your open source tools!
What is the F1-score of your trained NEL model？How to evaluate its performance on own articles like non-Wikipedia articles? Is there a demo page to show NEL tools' performance?
## Your Environment

* Operating System:
* Python Version Used:3.6
* spaCy Version Used:2.2.5
* Environment Information:

**Comment by umarbutler** [comment]
I haven't used the NEL pipleline before, however, I'd suspect the scores should be in the model's meta.json. Would you mind posting that file for the MEL model you've trained?

**Comment by whuFSN** [comment]
I haven't finished training the NEL model because of its long training time. So I'm interested in official NEL model's performance.

**Comment by umarbutler** [comment]
Have you trained a model for at least a single iteration? If so, there should be a meta.json file in the folder for any given iteration (i.e. if you trained a model called MODEL using cli, there would be a folder called model0, model1, etc.. in that folder. Each folder would contain a meta.json).

Official benchmarks are available here: https://spacy.io/usage/facts-figures. Looking at that page, however, I can't seem to find any benchmarks on NEL. This is probably because the NEL pipeline is still quite new and is probably still under development.

**Comment by svlandeg** [comment]
Hi @whuFSN : we don't have a single pretrained NEL model yet, as the algorithms are still under development. This is also the reason why we're not distributing one yet. Measuring the accuracy is actually a bit of a challenge: Wikipedia data is highly biased in its annotations, and we feel that measuring performance on it does not really reflect generalizability of the model.

I recently trained an NEL algorithm on 165K Wikipedia articles using [this code](https://github.com/explosion/spaCy/tree/master/bin/wiki_entity_linking), and manually annotated a set of news articles with Prodigy. The evaluation set contained 360 links (which is not too much). 

This was the performance I got:
![image](https://user-images.githubusercontent.com/8796347/79116680-711dee80-7d89-11ea-8597-cd8f74716129.png)

The "prior probability" baseline is very strong, it indicates how likely a mention resolves to a certain ID, WITHOUT taking into account any context (i.e. any mention of "Obama" is most likely to be the former US president, even though surely there are many more Obama's in the world). If we combine the EL algorithm (which looks at context of the sentence) with the prior probability, we see a bump in performance from 67% to 71%.

Because not every entity of the world could ever realistically be included in a knowledge base, your upper bound is always less than 100%. In this evaluation, about 15% of entities in the news could not be resolved to the KB (think e.g. about random local people who are mentioned in the news exactly once, and you wouldn't even be able to find them on Google).

@whuFSN : to reduce the training time, look at [this thread](https://github.com/explosion/spaCy/issues/5261#issuecomment-609722954) with some advice I wrote to increase speed.

@umarbutler : the current CLI train scripts do not yet support the NEL task, so there is no `meta.json` when you train them. For a simple example on how to train a NEL algorithm, see [this script](https://github.com/explosion/spaCy/blob/master/examples/training/train_entity_linker.py).
