### ISSUE TITLE
spaCy gold docs example throws error

### ISSUE THREAD

**Issue by koaning** [explosion/spaCy#5298]
## How to reproduce the behaviour
I copied the code found [here](https://spacy.io/api/goldparse#docs_to_json). 

```python
from spacy.gold import docs_to_json

doc = nlp("I like London")
json_data = docs_to_json([doc])
```

When I run this (with spaCy v2.2.3) then I get this error; 

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
 in 
      2 print(spacy.__version__)
      3 doc = nlp("I like London")
----> 4 json_data = docs_to_json([doc])

gold.pyx in spacy.gold.docs_to_json()

doc.pyx in sents()

ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: nlp.add_pipe(nlp.create_pipe('sentencizer')) Alternatively, add the dependency parser, or set sentence boundaries by setting doc[i].is_sent_start.
```

Included a screenshot below;
![image](https://user-images.githubusercontent.com/1019791/79117796-60bb4300-7d8c-11ea-8c61-6d5d63f92b15.png)

## Your Environment

```
## Info about spaCy

* **spaCy version:** 2.2.3
* **Platform:** Darwin-19.3.0-x86_64-i386-64bit
* **Python version:** 3.7.3
```

**Comment by koaning** [comment]
d0h! nevermind. 

Accidentally used an empty `English` model. #mybad.

**Comment by svlandeg** [comment]
The code in the API documentation does not define the `nlp` object, because we try to keep the code as concise as possible there to focus on the actual methods we want to explain.

Your post doesn't include how you defined `nlp` but I'm guessing it's a blank model. So you'll have to follow the instructions in the error message, and make sure there's a component that can set sentences.
