### ISSUE TITLE
Is It Possible to Resume Training Via CLI?

### ISSUE THREAD

**Issue by umarbutler** [explosion/spaCy#5304]
I was training models with CLI train and then my PC crashed. I wasn't able to complete the 100 iterations I wanted (it stopped at model 26). Is it possible to resume training for models after the model it trained last (through the CLI)?

**Comment by adrianeboyd** [comment]
This is possible, but hasn't been implemented, especially saving the full configuration so that it's harder to resume incorrectly. (This will get easier with spacy v3.)

If you're careful to keep the same settings, I think you should be able to start the next round with the last good saved model as the base model using the `-b` option.
