### ISSUE TITLE
Cannot import compound dependency

### ISSUE THREAD

**Issue by pcoenen** [explosion/spaCy#5345]
The compound dependency cannot be imported:

`from spacy.symbols import compound`

Leads to the following error:

`ImportError: cannot import name 'compound'`

## Info about spaCy
* **spaCy version:** 2.2.4
* **Platform:** Linux-4.15.0-76-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.6.7

**Comment by adrianeboyd** [comment]
Hmm, I'm not sure why it's missing from the UD deps in `symbols`. The hard-coded symbols were more important for the v1 version of the vocab/stringstore and it's not as important for v2.

If a symbol isn't hard-coded, the internal hash is the same as for any other string, so you can look it up with `nlp.vocab.strings["compound"]`. If you have a parsed `Doc`, `token.dep` for `compound` should be the same as `nlp.vocab.strings["compound"]`. (This is true for the hard-coded symbols, too, since the strings lookups checks for hard-coded values first before calculating the hash value.)

What's the context where you want to import `compound`?

**Comment by pcoenen** [comment]
So I'm going over the nouns and check if they have a compound or not. Normally I import these symbols so I can do checks like `token.pos == Noun` or `token.dep == compound`. To prevent doing the slower `token.dep_ == 'compound'` comparison.  I could also look up the hash and use it like `token.dep == hash_value` but I'm not sure if the hash value depends on the language model? So it would be nice if I can import `compound` in the same uniform way as I import `NOUN` and `VERB` and `conj` etc...

**Comment by adrianeboyd** [comment]
The hash value is always the same for the same string, so you can safely look up `nlp.vocab.strings["compound"]` once and save the value to compare with `token.dep`.
