### ISSUE TITLE
NER not working for mid-word tagged sentences

### ISSUE THREAD

**Issue by deathg0d** [explosion/spaCy#5363]
## How to reproduce the behaviour
I am using this code: [link](https://github.com/explosion/spaCy/blob/master/examples/training/train_ner.py), to train for NER. My pre-tagged dataset however is for Nepali language and a tag can end midword. For example in a sentence:

चालकलाई प्रहरीले पक्राउ गरेर मुद्दा चलाउने **डिपो** प्रमुख **यादव**ले जानकारी दिए ।

Whole words can be tagged like **डिपो**. And sometimes only partial words can be tagged - **यादव** is tagged but not ले. I believe this cannot be done in prodigy (at least in the demos, whole words are tagged)? The tagging was done in some other platform. I thought Spacy would not even allow this tag data as input, but it did without throwing errors. I was able to train the data. While using the trained model I found an issue though. Spacy performs well on whole words. In the above example, it has no problem recognizing डिपो but it cannot recognize यादव when यादव appears combined with other characters like यादवले.

## Your Environment
Google Colab

**Comment by adrianeboyd** [comment]
Underneath spacy is tagging whole words with BILUO tags and the NER model doesn't support partial words. Currently when the training data is loaded, it silently ignores annotations that don't correspond to whole words from the tokenizer, converting those annotations to `-` internally, which means that the model basically skips these tokens while training (as opposed to `O`, which is explicitly not an entity). 

This is confusing for users and we need to add warnings here (see #5007), but in a way that doesn't produce an overwhelming number of warnings. I should take another looking at the warnings system and that PR since we removed some of spacy's internal warnings management to make it easier to manage things with python's warnings control.

**Comment by deathg0d** [comment]
Ok thank you for the clarification. Just a question, do you know of any other library that supports this?

**Comment by adrianeboyd** [comment]
I know that there is research on character-based NER tagging (in particular for languages like Chinese where word segmentation is an issue), but I don't know of any libraries to recommend here, sorry!

**Comment by svlandeg** [comment]
I guess we can close this as the warnings are a work-in-progress, and I think the issues with the original use-case have been addressed.
