### ISSUE TITLE
Calling `doc.vector` with Spacy models with no vectors produce zero length vectors for empty strings

### ISSUE THREAD

**Issue by ned2** [explosion/spaCy#5471]
I noticed this in our dev environment with dummy data that used the `en_core_web_sm` rather than our custom model that has a set of vectors. 

```
nlp = spacy.load("en_core_web_sm")
len(nlp("hello").vector)
>>> 96

len(nlp("").vector)
>>> 0
```

Whereas doing the same for the `en_core_web_lg` model produces a doc vector of length 300 for both examples. 

This inconsistent lengths causes us some grief from TensorFlow which took a little while to track down. I think this might happen whenever the vector length is zero. If I drop the vectors from the en_core_web_lg model like below, the new model exhibits the same behaviour:

```python
import spacy
from spacy.lang.en import English

nlp = spacy.load("en_core_web_lg")
nlp.vocab = English.Defaults.create_vocab()
nlp.to_disk("lg_no_vectors")
nlp = spacy.load("lg_no_vectors")
len(nlp("").vector)
>>> 0
```

## Info about spaCy

* **spaCy version:** 2.2.4
* **Platform:** Linux-5.3.0-1017-aws-x86_64-with-glibc2.27
* **Python version:** 3.8.2

**Comment by adrianeboyd** [comment]
I see why that could cause some grief.

The vector property uses the tensor property as a backup if there aren't any vectors, but empty documents don't get a tensor (no real processing is done for empty docs) and the empty doc itself doesn't really have access to what the tensor width would have been used for a non-empty doc, either.

It also turns out (I'm surprised I hadn't noticed before!) that only the `tagger` sets the tensor, not the `parser` or `ner`, so custom pipelines may necessarily not end up with tensors, either. (I'm not even sure whether this is the intended behavior.)

The v2 config is a bit buried (this will all be in an explicit config in v3), but you can get the tensor width from something like `nlp.get_pipe("tagger").model.tok2vec.nO`, or also just from inspecting a non-empty document.

Because it's using the shape of the vectors data array underneath when it returns the tensor-as-vector property, I can suggest a hack to get it to return the same length for empty docs:

```
import spacy
from thinc.neural.util import get_array_module

nlp = spacy.load("en_core_web_sm")

tensor_width = nlp.get_pipe("tagger").model.tok2vec.nO # or tensor_width = len(nlp("a").vector)
assert nlp.vocab.vectors.data.shape == (0, 0) # don't do this to a non-empty vector table!

xp = get_array_module(nlp.vocab.vectors.data)
nlp.vocab.vectors.data = xp.zeros((0, tensor_width), dtype="f")

assert len(nlp("").vector) == 96
assert len(nlp("a").vector) == 96
```

This is clearly hacky, but I'm not sure there's a good general-purpose solution here. (Tongue-in-cheek: don't process empty documents? don't rely on the vector property for models without vectors?)

**Comment by ned2** [comment]
Thanks for the workaround!

We ended up opting for a workaround at the pre-processing level, adding a null character for empty texts, which is is potentially a useful source of information for our categorisation model anyway.

**Comment by honnibal** [comment]
> The vector property uses the tensor property as a backup

This is one of the mistakes I regret the most :(. It's a really dumb default that just confuses things.

> only the tagger sets the tensor, not the parser or ner, so custom pipelines may necessarily not end up with tensors, either. (I'm not even sure whether this is the intended behavior.)

This is an accident, the intention was for everything to set the tensor. But this was also a dumb default: setting the tensor causes problems because it's a big chunk of data most people don't need, so we end up with consistency questions when we go to serialize.

For v3, I think we should turn this stuff off by default, and let users add callbacks to the components that will perform additional `set_annotations` work if they want it.
