### ISSUE TITLE
doc.ents is inconsistent when running on similar data

### ISSUE THREAD

**Issue by JayThibs** [explosion/spaCy#5483]
## How to reproduce the behaviour
I have a dataframe with a column called "titleFinal". It's the title of a table in a PDF. My current goal is to pull entities from the table titles and then later use them for analysis. I plan on training a model over my data (by creating a list of entities), but so far I've used the base NER. Unfortunately, when I look at what doc.ents extracts, it doesn't seem consistent at all and I'm not sure if I did something wrong or the model is simply extracting entities poorly.

For example, the first row gives me the following entities:

TABLE 3 SUMMARY OF AQUATICS FIELD WORK -> [(TABLE, 3)]

The next few tables have a similar title, yet "TABLE" is not recognized. I get this instead:

TABLE 4 SUMMARY OF WATERCOURSE CROSSINGS -> [(4)]

These inconsistencies happen quite frequently throughout the list of entities so I'm wondering what I can do to resolve this. Is this expected?

Unfortunately, I can't share the dataset yet, but here's the code I'm currently using:

```
nlp = spacy.load("en_core_web_sm") # small model for development

tokens = []
lemma = []
ents = []

for doc in nlp.pipe(df['titleFinal'].astype('unicode').values, batch_size=50,
                        n_threads=3):
    if doc.is_parsed:
        tokens.append([n.text for n in doc])
        lemma.append([n.lemma_ for n in doc])
        ents.append([e for e in doc.ents])
    else:
        # We want to make sure that the lists of parsed results have the
        # same number of entries of the original Dataframe, so add some blanks in case the parse fails
        tokens.append(None)
        lemma.append(None)
        ents.append(None)

df['titleFinal_tokens'] = tokens
df['titleFinal_lemma'] = lemma
df['titleFinal_ents'] = ents
```

## Info about spaCy

* **spaCy version:** 2.2.4
* **Platform:** Linux-4.19.104+-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.9
* **Models:** en

**Comment by JayThibs** [comment]
So, I just tried with the large model, and it seems to be doing a much better job. I'm not seeing as many inconsistencies. However, they are still there. For example:

Table 21-9 Cumulative Effects Initial Screening -> [(21)]
Table 21-18 Cumulative Effects Initial Screening – Human Occupancy and Resources -> [(21), (Cumulative, Effects, Initial, Screening, –, Human, Occupancy, and, Resources)]

And other similar inconsistencies. Is my approach wrong? Should I not be using:

``
for doc in nlp.pipe(df['titleFinal'].astype('unicode').values, batch_size=50,
                        n_threads=3):
``?

**Comment by adrianeboyd** [comment]
I think this is mainly due to a big style/genre difference between the training data used for the provided models and your texts. The training data for the provided models is mainly newspaper text (full sentences with standard capitalization, some headlines with headline caps), so short phrases and titles in all caps look very different and there's not the same kind of context around the entities that you'd find in longer sentences.

The performance of the statistical models will be less predictable as the data looks less and less like the training data. I don't think the provided English models are going to be a good match for your task. You might want to train your own NER model or consider using a combination of statistical and rule-base methods (like the `Matcher` or `PhraseMatcher`) if you have phrases like `Table NN-NN` that can be matched with simple patterns.

**Comment by JayThibs** [comment]
@adrianeboyd Thank you for responding! This is what I expected. It's unfortunate, but it is what it is. What you've suggested is what I've started doing instead. I've started to create a Matcher for the text. Ultimately, I will try to get what I can out of the Matcher and then maybe do some transfer learning to see if that can help as well.
