### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (96, 3, 480), (96, 3, 384)

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#5510]
spacy version 2.2.4

Ran pretraining first

`python -m spacy pretrain rawtext_preprocessed.jsonl "spacy_word2vecmodel_1.0.0.6" models --n-iter 1000 --use-vectors`

Then tried to train a new model using that pretrained model

`python -m spacy train en withpretrain finaltrain.json finaltest.json --base-model "ML Models\NER_spacy_baseModel\Release\1.0.0.1" --vectors "ML Models\Word2Vec\spacy_word2vec\1.0.0.6\spacy_word2vecmodel_1.0.0.6" --n-iter 100 --use-gpu 0 --init-tok2vec "ML Models\NER_spacy_pretrainModel\development\1.0.0.1\model999.bin"
`

And I get this exception 

```
Training pipeline: ['tagger', 'parser', 'ner']
Using GPU: 0
Starting with base model 'ML
Models\NER_spacy_baseModel\Release\1.0.0.1'
Adding component to base model 'tagger'
Extending component from base model 'parser'
Adding component to base model 'ner'
Loading vector from model 'ML
Models\Word2Vec\spacy_word2vec\1.0.0.6\spacy_word2vecmodel_1.0.0.6'
Counting training words (limit=0)
Traceback (most recent call last):
  File "D:\Anaconda\envs\spacy\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda\envs\spacy\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\spacy\lib\site-packages\spacy\__main__.py", line 33, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "D:\Anaconda\envs\spacy\lib\site-packages\plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "D:\Anaconda\envs\spacy\lib\site-packages\plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "D:\Anaconda\envs\spacy\lib\site-packages\spacy\cli\train.py", line 290, in train
    components = _load_pretrained_tok2vec(nlp, init_tok2vec)
  File "D:\Anaconda\envs\spacy\lib\site-packages\spacy\cli\train.py", line 637, in _load_pretrained_tok2vec
    component.tok2vec.from_bytes(weights_data)
  File "D:\Anaconda\envs\spacy\lib\site-packages\thinc\neural\_classes\model.py", line 396, in from_bytes
    copy_array(dest, param[b"value"])
  File "D:\Anaconda\envs\spacy\lib\site-packages\thinc\neural\util.py", line 148, in copy_array
    cupy.copyto(dst, src)
  File "D:\Anaconda\envs\spacy\lib\site-packages\cupy\manipulation\basic.py", line 62, in copyto
    core.elementwise_copy(src, dst)
  File "cupy\core\_kernel.pyx", line 1001, in cupy.core._kernel.ufunc.__call__
  File "cupy\core\internal.pyx", line 352, in cupy.core.internal._broadcast_core
ValueError: operands could not be broadcast together with shapes (96, 3, 480), (96, 3, 384)
```

**Comment by svlandeg** [comment]
In general, this type of error means that there is some architecture incompatibility between your `pretrain` and `train` commands: weights are being loaded into a neural network that has the wrong dimensions. (and yes we definitely need to improve the error message! we're working on that).

Let me have a look at your two commands:

```
python -m spacy pretrain rawtext_preprocessed.jsonl "spacy_word2vecmodel_1.0.0.6" models --n-iter 1000 --use-vectors
```

This would store the result of the pretrained tok2vec layer in a directory called `models`, right ? And `spacy_word2vecmodel_1.0.0.6` refers to an NLP pipeline with vectors you trained before. These vectors will be used to learn from (by `pretrain`) and because of `--use-vectors` they are also used as `Static Vectors` in your Tok2Vec layer, so you need to specify them with `-v` in your `train` command with `--vectors`

```
python -m spacy train en withpretrain finaltrain.json finaltest.json --base-model "ML Models\NER_spacy_baseModel\Release\1.0.0.1" --vectors "ML Models\Word2Vec\spacy_word2vec\1.0.0.6\spacy_word2vecmodel_1.0.0.6" --n-iter 100 --use-gpu 0 --init-tok2vec "ML Models\NER_spacy_pretrainModel\development\1.0.0.1\model999.bin" 
```
Assuming the `spacy_word2vecmodel_1.0.0.6` is the same as above, that's fine. But your `init_tok2vec` should refer to a model within the `models` dir (i.e. the output dir of the `pretrain` command). 

But what are you using the `base-model` for? If any of the components in the base-model have a pretrained Tok2Vec component, it will be overwritten by the Tok2Vec layer you just pretrained. I'm guessing that one of the base components indeed does have a Tok2Vec layer with a slightly different architecture than your pretrained one, and upon overwriting it, the above error is thrown.

If you adjust your command by removing this base model, and making sure the correct pretrained Tok2Vec model is passed, does it work then?

**Comment by erotavlas** [comment]
@svlandeg  
My base model is constructed using the instructions provided in #5420 in order to preserve my custom tokenization rules & preserve the sentencizer based on the parser

So I did that first, along with generating a pretrain model.
Then those two models get applied in the `python -m spacy train` command

I later got around the issue by specifying --pipeline option with only 'ner'  and the error went away.

I don't know if my steps are correct for all this and if the error was a warning that I'm doing something wrong in one of the intermediate steps..  The model seems to work though.

**Comment by svlandeg** [comment]
Good to hear the model works!

If your base model contained a tagger/parser, that would have been the reason for the error. You can't really combine a pretrained base model (`--base-model`) with a pretrained tok2vec layer (`--init-tok2vec`), because the pretrained components of the base model would get partly overwritten. I'll assume your base model doesn't have an NER component? In that case indeed it makes sense to `train` on just the `ner` component.

We've added an additional check for this in the script, to throw a custom warning that will identify the problem more easily in the future: https://github.com/explosion/spaCy/pull/5518
