### ISSUE TITLE
Why Lemma (apples) is "appl", It should be "apple"

### ISSUE THREAD

**Issue by ValeriiBaidin** [explosion/spaCy#5528]
Why Lemma (apples) is "appl", It should be "apple"

**Comment by adrianeboyd** [comment]
Hi, I can't replicate this with the English lookup lemmatizer or the rule-based lemmatizer in spacy v2.2.4. Can you provide more information about the version of spacy (`spacy info --markdown`) and models (`spacy validate`) along with a minimal working example that shows how you're calling the lemmatizer?

**Comment by ValeriiBaidin** [comment]
> Hi, I can't replicate this with the English lookup lemmatizer or the rule-based lemmatizer in spacy v2.2.4. Can you provide more information about the version of spacy (`spacy info --markdown`) and models (`spacy validate`) along with a minimal working example that shows how you're calling the lemmatizer?

Yes, not all string gives the errors

The next code gives lemma for apple "appl"
```

doc=nlp("she apples he")
doc[1].lemma_ 
```

**Comment by adrianeboyd** [comment]
Can you provide the spacy version and model version information mentioned above? Which model are you loading in your example?

The rule-based lemmatizer depends on the POS and `appl` is returned as a possible lemma for `apples/VERB`. I remember a minor problem in an older version of spacy where the order of the returned lemmas wasn't predictable, so maybe this is related to what's going on.

The tagger isn't going to work well for lists of words like `she apples he` vs. more standard full sentences like `She eats apples with him.` since it's trained on newspaper text and it's not clear what the POS should be is a list of words vs. a full sentence.
