### ISSUE TITLE
WikiNER test set

### ISSUE THREAD

**Issue by CatarinaPC** [explosion/spaCy#5552]
How exactly are the results for NER obtained, for example for the French NER models? How is the WikiNER dataset split to be used for both train and test?

I would like to know this not only for result replication reasons, but also for having a consistent evaluation of other models, using the same test set.

**Comment by adrianeboyd** [comment]
Hi, I'm afraid we don't have good internal documentation about how the data was converted and split. I'd suggest converting the data yourself with `spacy convert -n 10 -c iob` to have your own consistent train and test sets.

It looks like our internal conversion uses the line breaks in the wikiner data to set paragraph breaks rather than using `-n 10`, but the `spacy convert` converter for this doesn't support it directly. It might not be to hard to add though, here's the current version of converter: https://github.com/explosion/spaCy/blob/6d712f3e06e228cc12140f054c2915627be53c2d/spacy/cli/converters/iob2json.py

For French, as an example, here are the token counts for the splits (60/20/20):

```
 689875 dev
 741563 test
2068257 train
```

For the spacy v2.2 and v2.3 provided models, the only additional parameter beyond the default `spacy train` settings is `-ovl 0.3`.

Keep an eye on the overall maximum document length (you might want to reduce `-n 10` to a lower value), since there are some extremely long sentences in the data that can lead to memory problems while training. Since NER relies on a relatively small token window, it's not as important as for the parser to see longer documents with many sentence breaks.

We can think about potentially providing some of our internal converted corpora where the licenses allow it, but we don't currently have a good way to maintain this kind of repository.
