### ISSUE TITLE
in German model, lemma "ich" improper

### ISSUE THREAD

**Issue by LeoK987** [explosion/spaCy#5556]
All these words are lemmanized as 'ich':
'es', 'ihm', 'ihnen', 'sie', 'er', 'wir', 'ihn', 'ich'

## How to reproduce the behaviour
nlp = spacy.load('de_core_news_sm')
doc = nlp("es")
print(doc[0].lemma_)

## Info about spaCy

* **spaCy version:** 2.2.4
* **Platform:** Linux-5.4.0-33-generic-x86_64-with-Ubuntu-20.04-focal
* **Python version:** 3.7.7

**Comment by adrianeboyd** [comment]
The German lookup lemmatizer lists are not great, to be honest. Guadalupe Romero has been working on a better rule-based lemmatizer for German that we hope to include in spacy v3.

There are a number of possible choices for pronoun lemmas, see the related issue #3296. You can customize the entries in the current lookup table stored in the model (under `nlp.vocab.lookups.get_table("lemma_lookup")`. Then save the model to disk (with `nlp.to_disk()`) in order to distribute a model with the pronoun lemmas that you would prefer.

It's still limited by the fact that it's a simple token-based lookup (no context, no POS, no morph), so ambiguous words like `ihr` can't be handled correctly in all cases.
