### ISSUE TITLE
doc.sents doesn't work for some docs restored from persisted DocBin

### ISSUE THREAD

**Issue by cuckookernel** [explosion/spaCy#5578]
## How to reproduce the behaviour

```
import en_core_web_sm
from spacy.tokens import DocBin

nlp = en_core_web_sm.load()

doc_bin = DocBin({'SENT_START': 1})
print( doc_bin.attrs )  # 65, 80

text = "This is a test"
doc = nlp( text )
print( [word.is_sent_start for word in doc] )
sents = list(doc.sents)
print( len(sents), list( doc.sents ) )

doc_bin.add( doc )

with open("doc_bin.bin", "wb") as f_out:
    f_out.write( doc_bin.to_bytes() )
``` 

Now restart python.

```
import en_core_web_sm
from spacy.tokens import DocBin

nlp = en_core_web_sm.load()

doc_bin = DocBin({'SENT_START': 1})
print( doc_bin.attrs )  # 65, 80

with open("doc_bin.bin", "rb") as f_in:
    doc_bin_bytes = f_in.read( )

doc_bin = doc_bin.from_bytes( doc_bin_bytes )
print( doc_bin.attrs )  # 65, 60  OK

docs = list( doc_bin.get_docs( nlp.vocab ) )

print( docs ) # ['This is a test'] 

list( docs[0].sents )
```
Last line produces an exception; 

```
Traceback (most recent call last):
  File "/home/teo/miniconda3/envs/bokeh2/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-d8d16426a9ed>", line 20, in <module>
    list( docs[0].sents )
  File "doc.pyx", line 612, in sents
ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: nlp.add_pipe(nlp.create_pipe('sentencizer')) Alternatively, add the dependency parser, or set sentence boundaries by setting doc[i].is_sent_start.
```

## Info about spaCy

* **spaCy version:** 2.2.0
* **Platform:** Linux-5.0.0-32-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.7.6

* Environment Information:

**Comment by adrianeboyd** [comment]
Hi, this is a confusing edge case for documents containing one sentence related to how sentence boundaries are created and stored by different components, which isn't as consistent as it could be. This needs to be documented better for v2.2 and also made more consistent in the future (see #4775 for some discussion).

The short version: in your example above, which includes a `parser` in the pipeline that's assigning the sentence boundaries, if you store `HEAD` in your `DocBin`, instead of `SENT_START`, it should work as expected.

The longer version, in case you're interested or someone comes across the same issue in the future:

In the `core` models, the sentence boundaries are added by the parser based on the dependency trees, and the `parser` only marks the sentence-initial tokens. In the first script, `doc.sents` knows that the doc was parsed through `doc.is_parsed` and knows that there must be sentence boundaries.

When you only export `SENT_START` in `DocBin`, the reloaded docs don't think they were parsed, so when you have one sentence, it can't tell the difference between one sentence and a document without sentence boundaries, since the first token is always the start of a sentence by default and the parser only marks the sentence-initial tokens.

You can't store both because you might end up with conflicting boundaries, so if the parser has assigned the sentence boundaries `HEAD` is the best choice. If you used the `sentencizer` instead, then use `SENT_START`, which works because the `sentencizer` marks all tokens rather than just the sentence-initial ones. Non-initial tokens are marked as `False` rather than `None`, so `doc.sents` knows that sentence boundaries are there beyond the first token.

**Comment by cuckookernel** [comment]
Thanks for the thorough answer. However I discovered that I need *BOTH*  the HEAD and DEP attributes for this to work as expected.... Does that make sense?  Is there some documentation mapping components of the model pipeline to  attributes one has to turn on in order to recover what the information that the language model has set on a document?

**Comment by adrianeboyd** [comment]
`HEAD` is what you need if you just want sentence boundaries.

The idea with `DocBin` is that you only want to store the attributes you need from the `Doc`. Pipelines are very configurable and you might have custom components, so we let you decide what you need to include.

For the provided `core` models, the main attributes would be:

```
["TAG", "POS", "LEMMA", "HEAD", "DEP", "ENT_IOB", "ENT_TYPE"]
```

We've also started trying to make it easier to analyze which components require / assign individual attributes in a pipeline (the info is added manually in component decorators, not derived from the code, and it's still in development; you can see that`token.head` is missing from the parser section below), but the basics look like this:

```python
from spacy.analysis import print_summary
nlp = spacy.load("en_core_web_sm")
print_summary(nlp)
```

```none
============================= Pipeline Overview =============================

#   Component   Requires   Assigns               Retokenizes
-   ---------   --------   -------------------   -----------
0   tagger                 token.tag             False      
                           token.pos                        
                           token.lemma                      
                                                            
1   parser                 token.dep             False      
                           token.is_sent_start              
                           doc.sents                        
                                                            
2   ner                    doc.ents              False      
                           token.ent_iob                    
                           token.ent_type 
```

**Comment by svlandeg** [comment]
Merging this with Issue #4775 as the immediate problem is resolved, and the remainder of the conversation can be centralised there.
