### ISSUE TITLE
Using glove.6B.100d.txt embedding in spacy getting zero lex.rank

### ISSUE THREAD

**Issue by vijay-arya** [explosion/spaCy#5602]
## How to reproduce the behaviour

`python -m spacy init-model en spacy.glove.model --vectors-loc glove.6B.100d.txt`

(glove.6B.100d.txt is in word2vec format with 400000 100 in the first line. )

spacy.glove.model/vocab has following files: 
5468549  key2row
38430528  lexemes.bin
5485216  strings.json
160000128  vectors

`import spacy `
`nlp = spacy.load("en_core_web_md")`

`from spacy.vocab import Vocab`
`vocab = Vocab().from_disk('./spacy.glove.model/vocab')`

`nlp.vocab = vocab`

`print(len(nlp.vocab.strings)) `
`print(nlp.vocab.vectors.shape) `

gives 
407174 
(400000, 100)

However the problem is that:
`V=nlp.vocab`
`max_rank = max(lex.rank for lex in V if lex.has_vector)`
`print(max_rank) `

gives 0 

I just want to use the 100d glove embeddings within spacy in combination with  the regular "tagger", "parser", "ner" models that come with en_core_web_md.

Is this possible? Am I doing something wrong.

**Comment by adrianeboyd** [comment]
Answered on StackOverflow since it's more of a usage question: https://stackoverflow.com/a/62445307/461847

Answer copied below for reference:

The tagger/parser/ner models are trained with the included word vectors as features, so if you replace them with different vectors you are going to break all those components.

You can use new vectors to train a new model, but replacing the vectors in a model with trained components is not going to work well. The tagger/parser/ner components will most likely provide nonsense results.

If you want 100d vectors instead of 300d vectors to save space, you can resize the vectors, which will truncate each entry to first 100 dimensions. The performance will go down a bit as a result.

```
import spacy
nlp = spacy.load("en_core_web_md")
assert nlp.vocab.vectors.shape == (20000, 300)
nlp.vocab.vectors.resize((20000, 100))
```

**Comment by vijay-arya** [comment]
Thanks! @adrianeboyd
