### ISSUE TITLE
Differences in dependency trees built by models of different versions

### ISSUE THREAD

**Issue by gnegrelli** [explosion/spaCy#5642]
Hello!

I trained a tagger/parser for portuguese using spaCy 2.1.8 and got a consistent model (let's call it model A), but, when I upgraded to spaCy 2.2, I discovered it didn't work the same way in the newer version. I trained a new model (model B) for this version using the exact same corpus and got metrics (tokenizer, tags, uas and las) relatively close to the ones presented by model A, as show in the table below.

| metric | model A<br>(spaCy 2.1.8) | model B<br>(spaCy 2.2) |
|:-:|:-:|:-:|
| tokenizer | 98.55 | 98.35 |
| tags | 94.71 | 96.98 |
| uas | 85.76 | 85.48 |
| las | 82.52 | 82.12 |

However, when the models are used to annotate the same sentence, they give different results. For example, in the sentence `[...] ou seja será necessários dois planetas para suprir a demanda [...]`, model A builds the following dependency tree:

![Batelada](https://user-images.githubusercontent.com/44068014/85617946-6e1b6600-b636-11ea-8307-21c2c7dab4c9.png)

In the meantime, model B builds a slightly different tree, as shown below. 

![Quarentena](https://user-images.githubusercontent.com/44068014/85617959-72e01a00-b636-11ea-9267-142100b6f533.png)

I know there is a difference in how models apply lemmas from spaCy 2.1 to 2.2, but is there any other changes that could affect the model behaviour? How can two models trained with the exact same corpus and with similar metrics can diverge while constructing dependency trees?

**Comment by guiemi** [comment]
I'm facing the very same problem here guys. I'm stuck in spaCy 2.1 because of this weird trees behavior

**Comment by mileenawins** [comment]
Hi everyone! Same here... I noticed the lemmatization difference between models but it wasn't a big matter, but then I realized some sentence structures were different and some rules with dependencies didn't work so well anymore.

**Comment by svlandeg** [comment]
Hi @gnegrelli, sorry for the late follow-up. It's good to see the overal statistics of both your models, which seem to imply that model B (spaCy 2.2) has pretty much similar accuracies than the previous one. Thanks for the detailed analysis!

>How can two models trained with the exact same corpus and with similar metrics can diverge while constructing dependency trees?

Training a machine learning model is never a deterministic process... The model may have taken a turn somewhere and ended up in a slightly different optimum. It might be that one sentence in the new model is now broken, while another sentence is fixed.

@guiemi 
> I'm stuck in spaCy 2.1 because of that weird trees behavior

What exactly do you mean by this? Do you seem some kind of structural pattern that is wrong in the dependency parse? Or just some cases that have changed since the previous release?

It's difficult to judge the performance of the new models just by one example, and the overal stats seem fine. So we would need to establish some kind of structural error that has been introduced. I'm not sure we can do anything about this otherwise - as the models are bound to make slightly different predictions each time they get retrained (as other details in the library might have changed, too).
