### ISSUE TITLE
German sentence splitter handles direct speech indicators incorrectly

### ISSUE THREAD

**Issue by fotisj** [explosion/spaCy#5657]
The sentence splitter of the small German model cannot handle the typical indicators of direct speech in German print (»«) correctly, but attaches them falsely to the previous or next sentence

## How to reproduce the behaviour

    nlp` = spacy.load("de_core_news_sm")
    t = "»Hallo«, sagte Tom. »Schau mal, was ich hier habe.«"
    doc = nlp(t)
    for s in doc.sents: print(s)
    > »Hallo«, sagte Tom. »
    > Schau mal, was ich hier habe.
    > «

It works correctly with the medium and the large model. 
[EDIT: I was wrong. The medium and large model just make a different mistake: they put the character into a new sentence just for itself. But only sometimes. This seems similar to this issue #3942 ]

Workaround: replace »« with the English „“ in the raw text.

## Your Environment
copy-paste the result here.-->
* Operating System: Windows-10-10.0.19041-SP0
* Python Version Used: 3.7.6
* spaCy Version Used: 2.3.0

**Comment by adrianeboyd** [comment]
We have some data augmentation to add variations of quote symbols like `" / "` and  `„ / “`, but the pair `» / «` is tricky because they're used the other way around in Switzerland, so we add both kinds of variants and this is probably confusing for the parser. I think the data augmentation helps to some extent so that they're identified as punctuation, since the underlying training corpus doesn't contain `» / «` at all (it actually only contains ` `` / ''` as directed double quotes, which is part of why we wanted to augment with more modern alternatives), but its performance here is still not going to be great for this particular case.

Your workaround is a good approach given how the current model is configured and trained right now.

What could be useful is to add whether there's a following space token as a feature to the parser models, since this would help disambiguate them. Adding new features will get much easier in the upcoming spacy v3 and we should consider adding this feature to the tagger and parser models.
