### ISSUE TITLE
CLI training argument defaults are not listed in the table

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#5672]
## Which page or section is this issue related to?
https://spacy.io/api/cli#train

It would be useful if a column was added for easy lookup, what the default values are set for each of the command line arguments (much like they are provided for the hyperparameters table in the following section)  In particular the options for the network architecture

**Comment by svlandeg** [comment]
I agree with you that that could be a useful addition to the docs, but I'm not sure it's worth our time/effort to still make those updates for spaCy 2.x. 

In the upcoming v.3, the code will avoid setting arbitrary default values for hyperparameters as much as possible, and instead they will need to be specified in a config file. So that should address the issue of not knowing exactly which kind of parameters & values make up the model architecture.

**Comment by erotavlas** [comment]
@svlandeg when do you anticipate v3 being released?

**Comment by svlandeg** [comment]
We're hoping to get an alpha release up in the coming weeks :)
