### ISSUE TITLE
Spacy 2.0.18 getting killed

### ISSUE THREAD

**Issue by AnikaTabassum** [explosion/spaCy#5673]
I have a vps where the operating system is **Centos 7.8kvm with a 2GB RAM**
i am a **python3** virtual environment. i need to install spacy of version 2.0.18. but everytime i try to install with 
**pip install spacy==2.0.18 --no-cache-dir**
it returns message killed

 if i give command dmesg it returns

**[56520.909649] Out of memory: Kill process 6591 (pip) score 746 or sacrifice child
[56520.909651] Killed process 6591 (pip), UID 0, total-vm:2719456kB, anon-rss:1867756kB, file-rss:0kB, shmem-rss:0kB**

i have tried creating swapfile. it did not help. 
but if i try to install **spacy 2.3.0** it gets installed. but i specifically need the version 2.0.18. So that's a problem for me

**Comment by adrianeboyd** [comment]
What's the exact version of python that are you using? If it's python3.8, then there aren't prebuilt wheels for spacy 2.0.18, since it was released quite a while before python3.8 was published.

`pip` may be trying to compile spacy and all its dependencies from scratch, whereas for 2.3.0, it can just install a prebuilt wheel for python3.8, which takes less memory.

**Comment by AnikaTabassum** [comment]
No I have python3.6.8
Thanks i have solved the issue. 
Previously I had swap file of 1GB, now I increased it of 2GB. 
Thanks a lot!
