### ISSUE TITLE
UserWarning: [W030] Some entities could not be aligned in the text ...

### ISSUE THREAD

**Issue by visionscaper** [explosion/spaCy#5727]
Since upgrading to the latest Spacy 2.3.0 (I think from 2.2.4, but am not sure, I repeatedly get the following warning, always related to the same character `('-')`:

```
lib/python3.7/site-packages/spacy/language.py:479: UserWarning: [W030] Some entities could not be aligned in the text ... Use `spacy.gold.biluo_tags_from_offsets(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  gold = GoldParse(doc, **gold)
```

What does this warning mean? When does it occur?

## Info about spaCy

* **spaCy version:** 2.3.0
* **Platform:** Linux-4.15.0-101-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.7.4

**Comment by adrianeboyd** [comment]
Yes, this warning was added in v2.3.0. In v2.2 misaligned entities were silently ignored while training, which can potentially be pretty confusing for users. It occurs when the character offsets that you provide for an entity don't line up with a token boundary. An exaggerated example:

```
text = "Susan went to Switzerland."
entities = [(0, 3, "PERSON")]
```

`Susan` as an entity should be `[(0, 5, "PERSON")]` and the character span `text[0:3]` doesn't correspond to a token produced by the tokenizer. A lot of the real-life cases you might run into are related to punctuation like periods after abbreviations, currency symbols, and quotes where you NER annotation tokenization doesn't line up with spacy's tokenization.

The error message is trying to explain that misaligned entities will show up as `'-'` when you run `spacy.gold.biluo_tags_from_offsets(nlp.make_doc(text), entities)`. I will think about how to clarify the error message, I see that it's confusing.

We also updated the warnings configuration to make it easier to control how warnings are shown in v2.3.0. You can see one example of how to filter warnings here (check out the possibilities for `warnings.filterwarnings` in the python `warnings` documentation):

https://github.com/explosion/spaCy/blob/3d8372155190cee60c2ed29728fb88cc9546c92d/examples/training/train_ner.py#L62-L65

**Comment by amaarora** [comment]
@adrianeboyd I am trying to create a custom parser with new entities like `unit_number`, `street_range` etc 

I still get the same error and don't understand why? Could you please help and guide me what I am doing wrong?

![image](https://user-images.githubusercontent.com/41290559/87220779-494f1e80-c3aa-11ea-87f8-92a8b005dab7.png)

**Comment by amaarora** [comment]
![image](https://user-images.githubusercontent.com/41290559/87220935-8e278500-c3ab-11ea-8899-15044c9edabe.png)
Just sharing another example for reference.

**Comment by svlandeg** [comment]
Hi @amaarora, this warning occurs when your "gold" entity offsets do not align with token boundaries as set by `nlp.make_doc`.

In your last example, you see for instance that `STREET` ("Alawa Crescent") could be aligned as the second (`B-STREET`) and third (`L-STREET`) token, but the first token ("Unit4,1") was kept as 1 token by the tokenizer and got 3 different entity types assigned to it (`PROPERTY_TYPE`, `UNIT_NUMBER` and `STREET_RANGE`) which resulted in a `-` instead because one token can only refer to one entity.

You have three options:
- Ignore these warnings, but note that your model won't be able to learn from misaligned entities
- Perform pre-processing on your input texts to ensure proper punctuation & white spaces: `Unit 4, 1 Alawa Crescent ...`
- Adjust your [tokenizer](https://spacy.io/usage/linguistic-features#tokenization) so that it manages to work better on your specific text, domain and use-case.

**Comment by mandar-avhad** [comment]
I'm getting the same warnings. Instead of ignoring those entities for training, how to consider those in it?

**Comment by polm** [comment]
Like [Sofie mentioned](https://github.com/explosion/spaCy/issues/5727#issuecomment-657497023), you would need to fix your annotations to match the tokenizer output. This would be a preprocessing step (or an alternate tokenizer implementation) and the complexity and details would depend on how complicated the issues with your annotations are.

**Comment by mandar-avhad** [comment]
> Like [Sofie mentioned](https://github.com/explosion/spaCy/issues/5727#issuecomment-657497023), you would need to fix your annotations to match the tokenizer output. This would be a preprocessing step (or an alternate tokenizer implementation) and the complexity and details would depend on how complicated the issues with your annotations are.

Could you please suggest an approach on how to clean or fix this misalignment of annotations so that I can use these entities too for my training? I don't want this warning/error or  "-"

**Comment by polm** [comment]
It totally depends on your annotations and what the problem with them is. Without knowing anything about your annotations I can't give any better advice that what's upthread.

You need to look at your annotations and see if there's a pattern. Maybe your tokenizer deals with some kinds of punctuation differently, in which case you should look at the [tokenizer special case docs](https://spacy.io/usage/linguistic-features#special-cases), or the general tokenizer docs linked above.

**Comment by Julia-Penfield** [comment]
Hello @svlandeg,
Thank you for the support. On your answer from Jul 13, 2020, it says one token can only refer to one entity. My problem seem to be the other way around. 

Two examples of my entities:

first example: 'titraver (edta)' - ignore the meaning of it.
second example: '1-(2-hydroxy-5-(trifluoromethyl)phenyl)ethanone' - it's a chemical.

I am getting the [W030] warning. 

My question is, can one entity refer to multiple tokens?

**Comment by polm** [comment]
> My question is, can one entity refer to multiple tokens? If no, how should I construct my training set for multi-token entities?

It's completely normal for a single entity to refer to multiple tokens, that should not cause problems. This warning indicates something weird with your annotations or tokenization. In your case you have very strange punctuation so it's probably related to that, but I would need to see the whole sentence and annotations to say more.

As a note for your and anyone who reads this issue in the future, if you need help with a specific case, please provide this information:

- the raw text of a sentence that causes the warning
- spaCy's tokenization of that sentence
- your annotations that cause the issue

To repeat Adriane's example of the kind of problem that causes this warning:

    text = "Susan went to Switzerland."
    entities = [(0, 3, "PERSON")]

"Sus" in "Susan" cannot be meaningfully assigned to an entity, because you can't have an entity on half a token. If you are getting this warning you need to look at your annotations and tokenization to figure out why it is happening, because your misaligned annotations are unusable.
