### ISSUE TITLE
Vector for token '789012' is Vector Null and highly differs from token '123456'

### ISSUE THREAD

**Issue by oliviercwa** [explosion/spaCy#5763]
## How to reproduce the behaviour

```
nlp = spacy.load('en_core_web_md')
doc1 = nlp('123456')
doc1 = nlp('714562')
```

Result: doc1 has a vector which is not Null, but doc2 vector is null ==> their similarity is very low.

Expected: Similar vector and high similarity

## Your Environment
* Operating System: Windows 10
* Python Version Used: Spacy v 2.1.9
* Environment Information:

**Comment by adrianeboyd** [comment]
Remember that this is a vector for the string `"123456"`, which could be a telephone number or postal code or fake password (who knows without context), so the vector is related to where this string token was seen in context, nothing about properties like whether it's a number. If you check, 3-digit numbers probably have very different vectors from other numbers just because of their use in area codes.

It probably doesn't make sense to compare vectors for numbers (especially larger less frequent numbers) or to compare vectors when one word has a vector and the other doesn't. `"123456"` has a vector because it was one of the ~600K most frequent tokens in texts used to train the vectors and `"789012"` wasn't frequent enough, so it gets a default 0-vector. You can check whether a token has a vector with `doc[0].has_vector`.
