### ISSUE TITLE
Matching and adding new entities since the latest release(s)

### ISSUE THREAD

**Issue by mattmcgrattan** [explosion/spaCy#577]
It's not clear from the tutorial around rule-based matching how you add entities to the core parser?

The model shown in:

https://github.com/explosion/spaCy/blob/master/examples/matcher_example.py

worked for me until the last few updates. But now, does not. 

The model shown in:

https://spacy.io/docs/tutorials/rule-based-matcher

also works for me, but seems -- looking at matcher.pyx -- to show a separate matcher which doesn't load the existing entities. 

I don't want to just match the custom items I've added. I want to get the entities that the default '.ents' expose, and the new ones I've added.

If I do:

nlp = spacy.load('en')
nlp.matcher.add(FOO)

[where FOO is the usual format with the lists of dictionaries]

that no longer works, but if I do nlp.match.add_entity and nlp.matcher.add_pattern, ditto.

**Comment by honnibal** [comment]
Does something like this solve the problem?

`doc.ents = doc.ents + matched_ents`

**Comment by mattmcgrattan** [comment]
Hah. I hadn't quite thought of it that way. 

Thanks!

It solves the problem with adding new matches, but not eliminating false positives. Does updating the gazetteer file still work?

**Comment by honnibal** [comment]
Hmm.

Come to think of it, the gazetteer entries will no longer be automatically annotated as named entities. Probably the entity recognizer class should be modified to use the gazetteer itself. This could be considered a bug in 1.0 at the moment.

A bit of background here: the new perspective on the `Matcher` class is that the action of matching the patterns should never have been coupled to acting on the matches. It's perfectly reasonable to want matches that overlap, and it's perfectly reasonable to want to resolve the matches in some complicated, arbitrary way.

Because the previous `Matcher` tried to add the matches as named entity spans, it had to come up with policies about whether to prefer shortest match, longest match, first match, last ending match...It's impossible to craft a policy that's satisfying for these things. That's why the matcher now takes a callback instead.

**Comment by mattmcgrattan** [comment]
OK, I think that makes sense. As a general rule then, when added large numbers of new entities (instances of the existing classes of entities), use the Matcher and combine with whatever comes out of the built in entity recognizer? Removing false positives manually (via the same kind of process)?

**Comment by honnibal** [comment]
Ah, I just reread your question.

Are you trying to tell the system, "hey, this phrase isn't an entity?"

You could run the NER, and then use the match results to filter the entities, yes.

**Comment by mattmcgrattan** [comment]
Yeah, either 'this phrase isn't an entity' or 'this phrase isn't an entity of that type'. Running NER on UK material, for example, because (I presume) of how the NER system is trained, it misidentifies a lot of place names as people, and vice versa.

But yeah, I think I can use some combination of the two to filter/enrich.

**Comment by honnibal** [comment]
Great.

There's more docs up about the matcher now, and more docs coming soon about the entity recognition. Closing this.
