### ISSUE TITLE
Unexpected behavior when using EntityRuler patterns with a misnamed/miscased/empty object

### ISSUE THREAD

**Issue by snosrap** [explosion/spaCy#5870]
I was able to recreate the "bug" described here: https://support.prodi.gy/t/regex-operator-in-the-patterns-file/1008/9 using the spaCy code below.

Basically, when a developer mistakenly uses the lowercase "regex" as a key (instead of the correct "REGEX" key), the patterns matcher will match all tokens in a document. Obviously, the main answer here is -- "don't do that". But I guess I'd expect spaCy/Prodigy to throw an error (or flag none of the tokens, rather than all of them).

## How to reproduce the behaviour
```
import spacy
from spacy.pipeline import EntityRuler

nlp = spacy.load("en_core_web_sm", disable=['ner'])
ruler = EntityRuler(nlp)
ruler.add_patterns([{"label":"AC","pattern":[{"text":{"regex":"^abc$"}}]}]) # subtle BUG: "regex" should be "REGEX" (uppercase)
nlp.add_pipe(ruler)

doc = nlp("My favorite word is abc.") # only "abc" should match

for ent in doc.ents:
    print(ent, ent.label_) # Note that *every* token matches
```

Output:
```
My AC
favorite AC
word AC
is AC
abc AC
. AC
```

Note that the offending line behaves the same way in the following circumstances:
* `ruler.add_patterns([{"label":"AC","pattern":[{"text":{"regex":"^abc$"}}]}])`
* `ruler.add_patterns([{"label":"AC","pattern":[{"text":{"random_nonsense":"^abc$"}}]}])`
* `ruler.add_patterns([{"label":"AC","pattern":[{"text":{}}]}])`

## Your Environment

* Operating System: windows 10
* Python Version Used: Python 3.7.8
* spaCy Version Used: 2.3.0
* Environment Information:

**Comment by adrianeboyd** [comment]
The best general advice here is to initialize `EntityRuler` with `validate=True` while developing patterns to do a full validation against a pattern schema, which catches this issue. The validation is a bit stricter than the `Matcher` internally, for instance, it also doesn't allow lowercase `"text"` although this does work in the `Matcher` with validation disabled.

The full validation is turned off by default because it can slow things down. If the load/init time doesn't matter for your application, then you can also just leave enabled if it's helpful. It shouldn't affect the matching time, just the init time.

I agree that silently discarding unrecognized attributes is very frustrating from a user perspective. I'll see if we can detect this a bit more sensibly in the `validate=False` case. We don't want to change the overall behavior of the `Matcher`, but I think a warning might be okay.

**Comment by snosrap** [comment]
Ah, `validate=True` is a great feature, thanks for letting me know!

I totally agree with keeping the behavior of `Matcher` the same -- a warning seems like a good solution.
