### ISSUE TITLE
Cannot deploy on Heroku using Flask

### ISSUE THREAD

**Issue by arditoibryan** [explosion/spaCy#5884]
In the code I am using:

`spacy.load('en_core_web_sm')`

It runs this error:
`OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.`

Also tried installing:
```
spacy==2.0.18
https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.0.0/en_core_web_md-2.0.0.tar.gz#egg=en_core_web_md==2.0.0
```

```
import spacy
import en_core_web_md
nlp = en_core_web_md.load()
```
Problem still occurs

Tried to put the model in the static folder but it does not recognize it. Are there any workarounds? Thank you

**Comment by adrianeboyd** [comment]
It's probably best to figure out why the model package install isn't working with `pip`, since those requirements look fine. (The download is failing, it's not being installed in the right environment, etc. ?)

Possible workarounds: you can download the `.tar.gz` file from that link and install it directly with `pip` from a local path, or if you download and unpack the file, the model itself is a subdirectory and you can load it from the full path with `spacy.load()` instead of using the package name.

**Comment by arditoibryan** [comment]
I am using Google Colab for Flask simulations before deployment. I was able to download the directory and open it by just directing the folder:
```
#WORKING
import spacy
nlp = spacy.load('/content/static/en_core_web_sm-2.2.5')
nlp('ciao')
```

However, I tried to open it with flask using:
```
import spacy
nlp = spacy.load(url_for('static', filename='en_core_web_sm-2.2.5'))
print(nlp(';ciao'))
```

![image](https://user-images.githubusercontent.com/63985091/89524836-88c02d80-d7e5-11ea-8f97-c4231f7405c4.png)
When opening the app on the browser it runs error: maybe I have to connect the path in a different way?
Thank you

**Comment by svlandeg** [comment]
Good to see that it works to run `spacy.load` on your downloaded folder. I guess the missing piece is now, how to connect to your static files from flask. I haven't really used flask much lately, and this isn't really a spacy-specific issue, so you'll have to focus on documentation for flask on how to access such files/folders. Perhaps [this SO post](https://stackoverflow.com/questions/20646822/how-to-serve-static-files-in-flask) is useful?
