### ISSUE TITLE
Training a model with the simple training method adds '_SP' tags to the TAG_MAP used resulting in misaligned tagging.

### ISSUE THREAD

**Issue by GruffPrys** [explosion/spaCy#5926]
For, more details and the workaround suggested by @honnibal., see:

https://support.prodi.gy/t/problem-creating-a-new-language-to-serve-as-a-base-model-for-further-improvement-in-prodigy/3296

Possibly related to https://github.com/explosion/spaCy/issues/5648 @adrianeboyd 

## Your Environment

* Operating System: Ubuntu 18
* Python Version Used: 3.6
* spaCy Version Used: 2.3.2
* Environment Information:

**Comment by adrianeboyd** [comment]
It's probably related to the simple training method, which we don't use internally so it doesn't get tested as well. I will take a look...

(I think removing `_SP` from the tag map may cause bugs when your text actually contains space characters, but I'm not entirely sure off the top of my head whether it will raise an error or just do something weird.)

**Comment by adrianeboyd** [comment]
Let's see, I realized I'm not sure what you mean by "simple training method". This example tagger training script here uses what's frequently called something like "simple training method" within spacy:

https://github.com/explosion/spaCy/blob/b10c7bc56ed74ae205f5e136c6dae59d70b27925/examples/training/train_tagger.py

Is this what you mean? Or do you mean `prodigy train`?

I tested both and I can't immediately replicate this problem either with this script or with `prodigy train`. How does this compare in terms of how you're adding labels and training? What does your tag map look like? (You can also send me a link or code snippet separately at `adriane@explosion.ai`.)

If you remove the space mappings you will get errors if your texts contain space tokens, so I wouldn't really recommend that, maybe only if you're 100% sure you're preprocessing your texts so that you don't have space tokens. The error would look like this:

```
  File "morphology.pyx", line 301, in spacy.morphology.Morphology.assign_tag_id
KeyError: 6893682062797376370
```

And it's also possible there's some TAG vs. POS weirdness in prodigy or maybe `_SP` vs. `SPACE` when you're using UPOS tags but with the tagger. What are the exact commands you're using with prodigy to annotate and to train?
