### ISSUE TITLE
Clarification on --textcat-multilabel flag for spacy train and exclusive_classes in TextCategorizer 

### ISSUE THREAD

**Issue by cerealrunner** [explosion/spaCy#5964]
Based on the on the command line `spacy train` documentation, it appears that including the `--textcat-multilabel` flag implies the labels **are not** mutually exclusive. In other words, to the extent one has to consciously include this flag, the default behavior under `spacy train` is that the categories **are** mutually exclusive. Did I read this correctly?

On the other hand, based on my reading the of documentation for the `TextCategorizer`, the default for `exclusive_classes` is `False`. In other words, the default behavior under the `TextCategorizer` is that the labels **are not** mutually exclusive. Did I read this correctly?

If I read both documentations correctly, might it not make better sense if the default is always, say labels are mutually exclusive, rather than having different defaults based on what one uses?

## Which page or section is this issue related to?
[`spacy train`](https://spacy.io/api/cli#train)
[`TextCategorizer`](https://spacy.io/api/textcategorizer)

**Comment by svlandeg** [comment]
Your interpretations are correct. In the `TextCategorizer`, `exclusive_classes` is set to `False` by default as that seems like a more reasonble default than assuming the opposite. On the other hand, the `train` script takes a boolean flag `textcat_multilabel` which is negated and used as `exclusive_classes`. This boolean flag is `False` by default because of the intrinsic nature of such flags for a CLI command.

In the upcoming spaCy v.3, these kind of "hidden defaults" will no longer be present for the various ML models in the code base. Everything will be set specifically in the config file, so hopefully this will be much more transparent and intuitive.

**Comment by cerealrunner** [comment]
Thank you for the quick clarification!
