### ISSUE TITLE
Over-allocation of NNP tags in all databases sm, md and lg

### ISSUE THREAD

**Issue by marcustarrant** [explosion/spaCy#6006]
Hi,

I am using the latest version of spacy and the databases (2 wks old).

For some reason "gold mine"

is tagged as gold propn nnp compound
and mine propn NNP root.

The compound and root are correct but this is not a proper noun.

Also same issue with fruits.  "apple" and "orange".

just wondering how I can get nouns to be recognised correctly as NN

**Comment by adrianeboyd** [comment]
What kind of context do your texts have around the terms "gold mine", "apple", and "orange"? If you're analyzing nouns without any context (`nlp("apple")`) it's expected that you'll see some variation between `NN` and `NNP` with the v2.3 `en_core_web_*` models. However, if you analyze those nouns in a full sentence, the results will typically be much more accurate: `nlp("I ate an apple")` vs. `nlp("apple announced a new smart watch")`.

We want the provided models to work relatively well for formal and informal texts, including texts without formal capitalization.  If you're not relying on capitalization, a lot of nouns are ambiguous, especially out of context. `apple` is a textbook example for this kind of ambiguity: `apple` vs. `she ate an apple` vs. `ms. apple gave an interview to cnn` vs. `my cousin got an apple watch for her birthday`.

The training data for the English tagger is mainly formal newspaper-ish text, but we added some data augmentation in spacy v2.2+ that lowercases some of the texts during training to improve the accuracy on more informal texts. As a result, informal texts are tagged a bit more accurately, but short texts with formal capitalization may have worse performance than in the models provided for v2.1 or earlier versions. Also since we mostly have newspaper texts, we have a lot more training examples where `apple` is a company than a fruit, so the tagger will probably prefer `NNP` for `apple` in more cases than for `orange`.

Here is some relevant discussion in #3052, which is a good place to report issues like this related to the statistical models:

https://github.com/explosion/spaCy/issues/3052#issuecomment-545749206
https://github.com/explosion/spaCy/issues/3052#issuecomment-584863055

**Comment by marcustarrant** [comment]
Adriane,

 

Thanks indeed for your response.  It now makes a little more sense.  Newspaper content is much more likely to refer to apple the company than an apple to eat.

 

The challenge with what we are trying to do is that there is no surrounding context.  Just the one word.

 

For now, we have elected to use a combination of NLTK and Spacy to get around over-allocation of nnp.  We are processing all lower-case results with NLTK and all with uppercase in Spacy.

 

In the longer-run we may need to train or build our own Spacy model.

 

Kind Regards

 

Marcus Tarrant

Managing Director

 



Simply content created from virtual conversation...That's HyperQuestions®

 

See our Whitepaper on Services Virtualisation (Created using HyperQuestions...of course.)  <https://www.linkedin.com/pulse/how-can-services-virtualisation-transform-businesses-marcus-tarrant/> See here

 

Head Office:

www.hyperquestion.com

PH: Australia (Head Office)  +61 3 9005 9710

132 Cremorne St, Richmond Vic, Australia

**Comment by adrianeboyd** [comment]
There are so many ambiguous words that it's probably not going to be that useful to run a statistical tagger on one word. (What is the part-of-speech of `can`?)

Instead of spacy's tagger, other resources that use word lists and dictionaries might be more useful / consistent. (Then the question is something more like: what are all the frequent / possible parts-of-speech for `can`?)

**Comment by marcustarrant** [comment]
Thanks Adriane,

 

I better understand the limitations.  I was planning to use the tagging as NNP to determine that a noun was uncountable (eg if it is a company or place then there is only one of them and hence it is referred to as “What is New York”, however it is an object eg Car, then the phrasing would be What is a car?

 

Rather than analysing content we are generating original content so I understand our challenges are a little different to what most NLP tools are designed to do (interpret existing content)

 

By using NLTK together with Spacy we have been able to achieve around 96% accuracy in phrasing questions from topics provided by users which is good enough for now.

 

There are a number of features we would find handy in Spacy that don’t exist, such as countable noun, article selection, etc, so we have been able to bring together different solutions such as inflect to address our broader needs.

 

Thanks again for your response and I am sure we will have many, many more uses for the tagging and Entity Recognition functions.

 

 

Kind Regards

 

Marcus Tarrant

Managing Director

 



Simply content created from virtual conversation...That's HyperQuestions®

 

See our Whitepaper on Services Virtualisation (Created using HyperQuestions...of course.)  <https://www.linkedin.com/pulse/how-can-services-virtualisation-transform-businesses-marcus-tarrant/> See here

 

Head Office:

www.hyperquestion.com

PH: Australia (Head Office)  +61 3 9005 9710

132 Cremorne St, Richmond Vic, Australia
