### ISSUE TITLE
Update NER model on the fly

### ISSUE THREAD

**Issue by JuanFF** [explosion/spaCy#6009]
Hello!

I have these 2 questions on custom NER training:

1. I am writing a custom NER following the example training loop from [here](https://spacy.io/usage/training).

Is it the right way to update my NER model _every time_ I provide a new annotation? Is there a simpler alternative?

I am annotating a corpus line by line. For each new line annotation, I want to update the NER model to see how it improves in the following lines.

2. Does it make sense to provide training examples without annotated entities? For example:

`("Uber blew through $1 million a week", {"entities": []}) `

Thanks a lot!

**Comment by adrianeboyd** [comment]
> Hello!
> 
> I have these 2 questions on custom NER training:
> 
>     1. I am writing a custom NER following the example training loop from [here](https://spacy.io/usage/training).
> 
> 
> Is it the right way to update my NER model _every time_ I provide a new annotation? Is there a simpler alternative?
> 
> I am annotating a corpus line by line. For each new line annotation, I want to update the NER model to see how it improves in the following lines.

You can update after each example, but over time the model will start to forget earlier examples ("catastrophic forgetting") and the difference you see in performance plus one example is probably not going to be informative enough vs. the time it takes to relabel all the following lines each time. In general, you probably want to update the model with batches that include new examples mixed in with previous examples.
 
>     2. Does it make sense to provide training examples without annotated entities? For example:
> 
> 
> `("Uber blew through $1 million a week", {"entities": []}) `

It depends on what you're trying to do. It does make sense to include examples that don't have any entities. The model will learn that `O` is the right entity label for these tokens.

If you have a model that's learned `ORG` for `Uber` and you give it examples like this, it will eventually start to forget that `Uber` is an `ORG` and label it as `O` instead. If you're starting with a model with `ORG` and it turns out you don't want `ORG` at all, you're probably better off starting with a blank model with your custom entity types.

In general, be sure you keep the problems related to "catastrophic forgetting" in mind: https://spacy.io/usage/training#ner

And see the tips here: https://spacy.io/usage/training#tips

Once you move beyond experimenting with small demo examples, we would recommend switching to using the [`spacy train` CLI](https://spacy.io/api/cli#train).

**Comment by JuanFF** [comment]
Thanks for your clear and in-depth explanation.
Yes, I have many text lines that will never have any entities, so I will include them as `0 `examples for NER.

**Comment by JuanFF** [comment]
@adrianeboyd Hi! Please, let me post one more question about NER training. The following case is quite common in my data set

"I sent you one (email)1 because my (email)2 is not working"

I need to label both entity types (1 and 2). Here, I suppose that I should provide more contexts as training (I sent you one message, I have sent you a voice note, etc.) I than more mentions to the same entity (email). Am I right?
I would like to know if NER is rather focused on context, mention or (probably) both.

Thanks a lot!

**Comment by svlandeg** [comment]
It's a combination of both, so it's probably best to provide instances of the same string in different contexts, as well as different (but semantically similar) strings in the same context.
