### ISSUE TITLE
IndexError: list index out of range while training parser

### ISSUE THREAD

**Issue by ksjae** [explosion/spaCy#6015]
```
Training pipeline: ['parser']
Starting with blank model 'ko'
Counting training words (limit=0)
Traceback (most recent call last):   
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ksjae/.local/lib/python3.7/site-packages/spacy/__main__.py", line 
35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/ksjae/.local/lib/python3.7/site-packages/plac_core.py", line 328, 
in call
    cmd, result = parser.consume(arglist)
  File "/home/ksjae/.local/lib/python3.7/site-packages/plac_core.py", line 207, 
in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/ksjae/.local/lib/python3.7/site-packages/spacy/cli/train.py", line
 213, in train
 optimizer = nlp.begin_training(lambda: corpus.train_tuples, device=use_gpu)
  File "/home/ksjae/.local/lib/python3.7/site-packages/spacy/language.py", line 583, in begin_training
    **kwargs
  File "nn_parser.pyx", line 576, in spacy.syntax.nn_parser.Parser.begin_training
  File "arc_eager.pyx", line 346, in spacy.syntax.arc_eager.ArcEager.get_actions
  File "nonproj.pyx", line 123, in spacy.syntax.nonproj.projectivize
  File "nonproj.pyx", line 172, in spacy.syntax.nonproj._get_smallest_nonproj_arc
  File "nonproj.pyx", line 58, in spacy.syntax.nonproj.is_nonproj_arc
  File "nonproj.pyx", line 26, in ancestors
IndexError: list index out of range  
```
## How to reproduce the behaviour
Training code as-is from document
```
python3 -m spacy train ko model KNLI-spacy.json KNLI-spacy-dev.json -p parser 
```
Use this json file **EDIT: These are faulty but remained in place,
 use [Corpus.zip](https://github.com/explosion/spaCy/files/5200286/Corpus.zip) for newest ones**
[https://1drv.ms/u/s!Aq0-1ykl7mZBqWCbqo6cq4X1amma?e=1eBExo](url) for KNLI-spacy.json
[https://1drv.ms/u/s!Aq0-1ykl7mZBqWGLptXC0Ba5nGFK?e=suX2RJ](url) for KNLI-spacy-dev.json

## Your Environment

* **spaCy version:** 2.1.9
* **Platform:** Linux-4.4.0-178-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.7.7

**Comment by ksjae** [comment]
Problem persists with debug-data
```
python3 -m spacy debug-data ko KNLI-spacy.json KNLI-spacy-dev.json --verbose
```
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ksjae/ai-text-adventure/lib/python3.7/site-packages/spacy/__main__
.py", line 35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/ksjae/ai-text-adventure/lib/python3.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/ksjae/ai-text-adventure/lib/python3.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/ksjae/ai-text-adventure/lib/python3.7/site-packages/spacy/cli/debug_data.py", line 83, in debug_data
    train_docs = list(corpus.train_docs(nlp))
  File "gold.pyx", line 222, in train_docs
  File "gold.pyx", line 243, in iter_gold_docs
  File "gold.pyx", line 266, in spacy.gold.GoldCorpus._make_golds
  File "gold.pyx", line 541, in spacy.gold.GoldParse.from_annot_tuples
  File "gold.pyx", line 621, in spacy.gold.GoldParse.__init__
  File "nonproj.pyx", line 123, in spacy.syntax.nonproj.projectivize
  File "nonproj.pyx", line 172, in spacy.syntax.nonproj._get_smallest_nonproj_arc
  File "nonproj.pyx", line 58, in spacy.syntax.nonproj.is_nonproj_arc
  File "nonproj.pyx", line 26, in ancestors
IndexError: list index out of range
```

**Comment by adrianeboyd** [comment]
Hi, the problem is that the heads haven't been converted correctly for spacy's training format. The heads should be **relative** to the current token, not absolute IDs. The root should have head `0` and all other tokens should have heads relative to their position, so a head of `-2` would mean the head is two words to the left, `1` would mean one word to the right, etc.

The data loader should fail with a more useful error in this case, though. I'll take a look to see how this could be improved.

**Comment by ksjae** [comment]
Thanks, solved the issue!
However, how can I see the entire list of offenses from ```python3 -m spacy debug-data --verbose```?

**Comment by ksjae** [comment]
Here's the modified-fixed JSON file.
It gives 
```
✘ Training data cannot be loaded: [E069] Invalid gold-standard parse
tree. Found cycle between word IDs: {0, 1, 2, 17, 21} (tokens: '이상화는' '이상 
화는'
'이상화는' '수' '있었다.') in the document starting with tokens: 이상화는 “새로 
운 환경에서 만난 다른 나라
선수들로부터 많은 걸 배울 수 있었다..
```
though... Can anyone help me solve this?
[아카이브.zip](https://github.com/explosion/spaCy/files/5186123/default.zip)
Attached is the json file zip.

**Comment by ksjae** [comment]
I'm not sure about the corpus being 100% error-free, but I'm quite sure that it's high quality(It's distributed by the 'National Institute' of Korean Language, so I believe it should (at least) guarantee some quality.

[The original file is available here.](https://incheonedu-my.sharepoint.com/:u:/g/personal/---_o365_ice_go_kr/EXeeGGfLIyJKn6WyJlOVmPIBAUxkSgUCL_Z_-EP0Nkaplg?e=5P6Uk6)
The documentation should be a single .pdf file. It's Korean, but this is the guideline for the original file :

<img width="905" alt="image" src="https://user-images.githubusercontent.com/17930170/92537752-e37ef600-f277-11ea-8bbf-a13540c62ee1.png">

I don't know about word segmentation alignment, how can I check?

**Comment by adrianeboyd** [comment]
It can be high quality and still not have trees that are in the right format for spacy, or there can be errors in the conversion. I think both problems are showing up in this example:

* conversion error: the root isn't converted to a head of `0` in the spacy training format
* (potential?) corpus error: the tree has two roots

For training with spacy, you need a single token with a head of `0` (a root) in each sentence. Looking at the original for that example, that tree seems to have two roots (two nodes with a head of `-1`, which I'm guessing means root from all the examples I've seen -- sorry that I can't really read the documentation in more detail).

To check the segmentation (you can temporarily convert without `head` and `dep` to create a file you can load):

```
spacy evaluate blank:ko file.json
```

The `TOK` in the output is the tokenization evaluation. In spacy v2 it's not the more typical F1 score used for word segmentation, it's just `# correct tokens / # predicted tokens`. For most languages in our provided models (Chinese is the exception), the default tokenizers are well over 99% for our training corpora. If many tokens are misaligned, it's hard for any of the models to train well because they ignore misaligned data. There are a lot of factors and it's hard to give an exact number, but if it's under ~95%, it's probably a good idea to improve the tokenization before trying to train models.

**Comment by ksjae** [comment]
I'm getting ```FileNotFoundError: [Errno 2] No such file or directory: 'ko/vocab/lexemes.bin'``` when I try to make a blank model, save, and run ```spacy evaluate ./model file.json```.
spaCy can't find model blank:ko with ```spacy evaluate blank:ko file.json``` 

I'll contact National Institute of Korean Language later today and get a proper documentation.

**Comment by adrianeboyd** [comment]
Ah, the `blank:ko` option was just added in spacy v2.3. I'd recommend upgrading if you don't have a particular reason to be using v2.1. The most recent release (v2.3.2) has an important fix for the Korean tokenizer to make it much faster.

The `lexemes.bin` error is typically related to using models from v2.3 with v2.0-v2.2. The models aren't compatible across minor versions, so you need to retrain models when switching between v2.1, v2.2, and v2.3.

To create a blank model (this is the right idea to run this evaluation in earlier versions), you should be able to do:

```python
import spacy
nlp = spacy.blank("ko")
nlp.to_disk("/path/to/ko_blank_model")
```

Before v2.3.2 the tokenizer will be extremely slow if you try to run this evaluation on the provided corpus, which has each sentence in a separate document.

**Comment by ksjae** [comment]
Yeah, was using v2.1 because of custom pipelines(neuralconf). Think I solved the corpus problem, changed root (-1) to 0 and changed ```head``` to relative. 

Now getting this though :(
```
✘ Training data cannot be loaded: [E186] '['드라마', '정도', '전', '은',
'이성계', '와', '함께', '왕', '(', '王', ')', '씨', '의', '고려', '왕조', '를', '무너뜨리', '고',
'새로운', '이', '(', '李', ')', '씨', '왕조', '를', '건국', '한', '조선', '시대', '개국', '공신',
'정도', '전', '의', '이야기', '를', '담', '고', '있', '다', '.']' and '['드라마', '정도전은',
'이성계와', '함께', '왕(王)', '씨의', '고려왕조를', '무너뜨리고', '새로운', '이(李)', '씨', '왕조를', '건국한',
'조선시대', '개국공신', '정도전의', '이야기를', '담고', '있다.']' are different texts.
```

**Comment by adrianeboyd** [comment]
That particular error is weird because the texts don't actually look like they're different. If you still see this error with v2.3, attach the example sentence as JSON here and I can have a look.

Looking at that example, I think you're going to run into major problems training because of the differences in word segmentation. You might want to try the experimental `-T` option with `spacy train`, which will let the parser retokenize to merge the oversegmented spacy tokens to look more like the corpus gold tokens. If you do this, be sure the parser is the last component in your pipeline.

Or maybe there are better options with mecab / natto-py to get segmentation closer to this corpus?

**Comment by ksjae** [comment]
Well...
1) I get ```ValueError: [E021] Could not find a gold-standard action to supervise the dependency parser. The GoldParse was projective. The transition system has 20 actions. State at failure```... for few(~30?)lines from the corpus. Think it'll be useful if these errors can be skipped.
2) I'll try the ```-T``` option as soon as I fix lines from the corpus.
3) ```Or maybe there are better options with mecab / natto-py to get segmentation closer to this corpus?```  I don't know whether there's an option, if you can mention someone with me cab knowledge, that'd be great.

**Comment by ksjae** [comment]
Oh, and here's a sample json
[KNLI-c-dev.zip](https://github.com/explosion/spaCy/files/5205779/KNLI-c-dev.zip)

**Comment by adrianeboyd** [comment]
I think those kinds of errors are caused by the poor word alignment. I'm afraid I don't know much about Korean word segmentation tools. Maybe there's documentation for the corpus that describes the tools that they used? You may need to implement a custom `KoreanTokenizer` in order to train from this particular corpus with spacy.

For the GPU, you probably just need to install `cuda-cupy101`. spacy doesn't use pytorch at all. See: https://spacy.io/usage#gpu

**Comment by ksjae** [comment]
Training right now, and there's something weird -> using train(), the training progress bar goes over 100% until it shows error.
<img width="732" alt="image" src="https://user-images.githubusercontent.com/17930170/92884857-35c54000-f44d-11ea-9494-9c1d5bc7a0ac.png">

Oh, and you're right. Tokenization accuracy is hitting a miserable 32%.

**Comment by ksjae** [comment]
Trying to pretrain, and I'm getting this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ksjae/ai-text-adventure/lib/python3.7/site-packages/spacy/__main__.py", line 33, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/ksjae/ai-text-adventure/lib/python3.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/ksjae/ai-text-adventure/lib/python3.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/ksjae/ai-text-adventure/lib/python3.7/site-packages/spacy/cli/pretrain.py", line 237, in pretrain
    model, docs, optimizer, objective=loss_func, drop=dropout
  File "/home/ksjae/ai-text-adventure/lib/python3.7/site-packages/spacy/cli/pretrain.py", line 264, in make_update
    predictions, backprop = model.begin_update(docs, drop=drop)
  File "/home/ksjae/ai-text-adventure/lib/python3.7/site-packages/spacy/_ml.py", line 837, in mlm_forward
    mask, docs = _apply_mask(docs, random_words, mask_prob=mask_prob)
  File "/home/ksjae/ai-text-adventure/lib/python3.7/site-packages/spacy/_ml.py", line 884, in _apply_mask
    word = _replace_word(token.text, random_words)
  File "/home/ksjae/ai-text-adventure/lib/python3.7/site-packages/spacy/_ml.py", line 904, in _replace_word
    return random_words.next()
  File "/home/ksjae/ai-text-adventure/lib/python3.7/site-packages/spacy/_ml.py", line 865, in next
    numpy.random.choice(len(self.words), 10000, p=self.probs)
  File "mtrand.pyx", line 901, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken
```
Also, how can I use custom tokenizer with ```spacy train```?

**Comment by adrianeboyd** [comment]
Yeah, the parser isn't going to be able to train decently if only 32% of the words align. I wouldn't try training unless the alignment is much better.

You can provide a custom tokenizer with the `--base-model` option. You configure a blank model with right tokenizer configuration and save it the same way as the blank model above. For spacy v2 you'll need a custom spacy install with the new or modified tokenizer class in order to be able to save and load the model.

**Comment by tisbuet** [comment]
> Hi, the problem is that the heads haven't been converted correctly for spacy's training format. The heads should be **relative** to the current token, not absolute IDs. The root should have head `0` and all other tokens should have heads relative to their position, so a head of `-2` would mean the head is two words to the left, `1` would mean one word to the right, etc.
> 
> The data loader should fail with a more useful error in this case, though. I'll take a look to see how this could be improved.

It works, thanks
