### ISSUE TITLE
Incremental sentence reading from file ?

### ISSUE THREAD

**Issue by vsraptor** [explosion/spaCy#6033]
## Feature description

Incremental sentence reading from file ... one sentence at a time ...

-----

I ended using chained buffers : line buffer feeds a sentence buffer.. and then the iterator consumes the sentence buffer.
Also I use spacy to detect sentence boundaries. The bad thing is I had to do it twice...

    import re
    import spacy
    from collections import deque
    from spacy.lang.en.stop_words import STOP_WORDS
    
    
    
    class Corpus(object):
    
    	nlp = spacy.load("en_core_web_sm")
    
    	def __init__(self, fname, kind='sentence', lemmas=True, stop_words=True, filter_punct=True):

    		self.fname = fname
    		self.file = open(fname,'r')
    
    		self.kind = kind
    		self.filter_punct = filter_punct
    		self.stop_words = stop_words
    		self.lemmas = lemmas
    
    		self.last_sent = ''
    		self.sents_buf = deque()
    		self.line_buf = deque()
    		self.closed = False
    
    
    	def __iter__(self): return self
    
    	def __next__(self):
    
    		if self.kind == 'line' :
    			if len(self.line_buf) == 0 and self.buffer_lines() is False : raise StopIteration
    			else : return self.line_buf.popleft()
    
    		if self.kind == 'sentence' :
    			if len(self.sents_buf) == 0 and self.buffer_sents() is False : raise StopIteration
    			else : return self.sents_buf.popleft()
    
    	def buffer_lines(self):
    		if self.closed : return False
    		i = 0
    		while i < 10 :
    			i += 1
    			line = self.file.readline()
    			if line == '' :
    				self.file.close()
    				self.closed = True
    				self.line_buf.append('*') # add end marker, so last line is processed
    				say('> closing file ....')
    				return True
    			self.line_buf.append(line)
    		return True
    		
    
    	def buffer_sents(self):
    		i = 0
    		while i < 10 :
    			i += 1
    			full = True
    			if len(self.line_buf) == 0 :	full = self.buffer_lines()
    
    			if full :
    				line = self.line_buf.popleft()
    				if not re.match(r'^\s*$', line) :
    					txt = self.last_sent + line #prepend 
    					sents = [ s.text for s in list(Corpus.nlp(txt).sents) ]
    					self.last_sent = sents.pop() #pull the first .. to prepend later
    					self.sents_buf.extend(sents)			
    			else : 
    				if len(self.sents_buf) == 0 : return False
    
    		return True

**Comment by adrianeboyd** [comment]
Hi, I'm not sure I understand what you're trying to ask here? Is there a particular problem you're running into related to spacy?

**Comment by vsraptor** [comment]
I'm trying to read a text file ONE SENTENCE at a time, instead of one line at  a time.

Spacy support reading ONE SENTENCE if we use a String, but if the text is big it is not feasible to put it in a string.

**Comment by adrianeboyd** [comment]
Hmm, spacy just isn't really set up to do this kind of incremental analysis. A `Doc` is initialized with its complete text before spacy does any further analysis like parsing and identifying sentence boundaries. Before you can access `doc.sents`, the full text has already been analyzed using the pipeline.

If you want to use spacy and your text is very long, you may need to identify some other kinds of boundaries (blank lines, section headings, basically anything that's not likely to break an entity or sentence in the middle) to chunk the text into smaller pieces for analysis. If it's not possible to identify boundaries that aren't going to break sentences or entities, one alternative is to process chunks that overlap slightly so that you don't miss any annotations. It's a bit of additional processing to reconcile the annotation from the overlapping segments, but it might be better than trying to find the best paragraphs or sections in advance.

For the built-in pipeline components, the models are using relatively local features, so chunks that are at least paragraph-sized make sense. Longer is fine as long as you're not running out of memory (and there is some overhead in creating each `Doc` object, so tons of small paragraphs may not be the best choice), but it's not usually going to improve the overall analysis to provide a text that's two pages long rather than one paragraph.

**Comment by vsraptor** [comment]
> kinds of boundaries

so i need **paragraph** detector which is not bound to spacy !! this way I can buffer at paragraph level and will not need to parse the lines twice ..

Any idea on project that detects paragraphs ?

**Comment by adrianeboyd** [comment]
I can imagine a tool that streams a text word-by-word or line-by-line and does incremental processing, but spacy just hasn't been designed to process texts in that way.

For spacy, you do need some way to segment very long texts. If your documents don't have any internal structure like headings or blank lines or `<p>` tags, I'm not sure what else to suggest. I've seen people use the slightly overlapping text chunks option for for NER: if you know an entity won't be longer than something like 10 tokens, you just need enough overlap to catch cases where an entity might have gotten split across your text chunks.

The current default max length for a pipeline in a core model (tagger + parser + ner) is 1 million characters, but depending on the components in your pipeline and how much memory you have, you can often increase this. The notes on this:

```
        max_length (int) :
            Maximum number of characters in a single text. The current v2 models
            may run out memory on extremely long texts, due to large internal
            allocations. You should segment these texts into meaningful units,
            e.g. paragraphs, subsections etc, before passing them to spaCy.
            Default maximum length is 1,000,000 characters (1mb). As a rule of
            thumb, if all pipeline components are enabled, spaCy's default
            models currently requires roughly 1GB of temporary memory per
            100,000 characters in one text.
```
