### ISSUE TITLE
Token.dep returns unexpected value for 'ROOT'

### ISSUE THREAD

**Issue by pglendenning** [explosion/spaCy#607]
The dependency integer id should match English().vocab.strings["depname-in-lower-case"]. This is true for all dependency names 'nsubj' (id=393), 'nsubjpass' (id=394) etc.. except for 'root'.  English().vocab.string["root"] returns 410 but when I look at an actually parse tree, the ROOT token's dependency id is  English().vocab.string["ROOT"] (53503).

## Environment
Operating System: Mac OSX 10.10.5
Python Version Used: 2.7.12 (anaconda)
spaCy Version Used: 1.1.2
Environment Information: Using home brew (not sure this matters)

**Comment by honnibal** [comment]
This happened for historical reasons, and my current take on it is that it's not worth the backwards incompatibility to fix. I'm in two minds about which is better anyway.

It's useful to have the label for the root dependency hard-coded. This dependency is special, because it isn't a dependency between a pair of tokens. We also can't have a null label here, because we need the null value 0 to mean that the label is missing.

This means that the root label isn't read from the dependency treebank — it's hard-coded. I think it's reasonable to have it cased differently to reflect that. I'm open to arguments on this point.

The historical reason was actually that the first versions of spaCy used the Penn2Malt converter, which upper-cases its labels. Then when the new model was shipped, the ROOT label kept its value.

Incidentally: the dependency labels were supposed to have contiguous integer IDs. It's a bug that they don't, but I can't fix it without rebuilding the model, and making everyone redownload it. So I'm waiting until I'm ready to make an actual upgrade to the model before I fix this.

**Comment by pglendenning** [comment]
I don't have a strong opinion here provided its documented and remains consistent across releases. So if you say the vocab string for the root dependency is uppercase and will always be uppercase then I think thats fine. If labels change then provided I download the new model it should also be fine since I get the id's from vocab.strings[].
