### ISSUE TITLE
issues with named entity ruler regex pattern matching?

### ISSUE THREAD

**Issue by kaykhancheckpoint** [explosion/spaCy#6070]
I am using spacy entity ruler to build a custom ner for my domain. https://spacy.io/usage/rule-based-matching#entityruler

I have some text and i want to extract entities from the text, however the words **could** contain a `#` or an `@` at the begining. Rather than creating a new pattern for each ive tried to give the regex pattern matcher a try.

https://repl.it/repls/WrithingHideousJavabeans

**Code**:

    from spacy.lang.en import English
    from spacy.pipeline import EntityRuler
    
    
    team_words = [{
      'id': '111',
      'name': "fnatic"
    },{
      'id': '222',
      'name': "100 thieves"
    }]
    
    team_patterns = [{
      'label': 'TEAM',
      'pattern': [{'TEXT': {'REGEX': f"^(#|@?){w['name']}"}}], 
      'id': w['id']
    } for w in team_words]
    
    # { 'label': 'TEAM',  'pattern': "100 thieves",  'id': '222' }
    
    nlp = English()
    ruler = EntityRuler(nlp)
    patterns = team_patterns
    
    ruler.add_patterns(patterns)
    nlp.add_pipe(ruler)
    
    
    # expect it to match 100 thieves but it does not
    doc = nlp("text text text 100 thieves text text text")
    print([(ent.text, ent.label_, ent.ent_id_) for ent in doc.ents])
    
    ## working however the # in #fnatic is not present in the ent.text output
    doc = nlp("text text text #fnatic @fnatic fnatic text text text")
    print([(ent.text, ent.label_, ent.ent_id_) for ent in doc.ents])
    
    ## expect it not to match but it does
    doc = nlp("text text text fnatichello text text text")
    print([(ent.text, ent.label_, ent.ent_id_) for ent in doc.ents])
    

**output**

    []
    [('fnatic', 'TEAM', '111'), ('@fnatic', 'TEAM', '111'), ('fnatic', 'TEAM', '111')]
    [('fnatichello', 'TEAM', '111')]

I have 3 problems with the result of the above code.

 1. 100 thieves is simply not being matched when using the pattern text regex. I've tried to add a backslash to escape the " " but that did not work. It seems like its having a problem with the space? However if you do a simple pattern match it will work.

 2. This one is mostly correct, it identifies all 3 words as entities. However the ent.text for `#fnatic` seems to be missing the hashtag.

 3. I believe this is an issue with my regex, i need it to stop after my word e.g `fnatic` the word should end there. So this one should not match.

**Comment by adrianeboyd** [comment]
For `Matcher` patterns, each token dict like `{"REGEX": "blah"}` corresponds to one individual token in the doc. The `REGEX` pattern with `100 X` doesn't work because this text is two tokens (`100` and `X`) underneath. You'd need to write the pattern so that the tokenization corresponds between the pattern and doc. See the notes here (in particular the first red warning infobox): https://spacy.io/usage/rule-based-matching#matcher

It's not 100% the case (there are exceptions, for instance you can merge two tokens so that the text contains a space), but in most cases if you have whitespace in a `Matcher` pattern for `ORTH` or `REGEX`, it's not going to work as expected because it's actually two or more tokens underneath.

With `#` and `@`, check carefully whether these are separated into individual tokens for your text. The two symbols may be handled differently by the tokenizer. I think for English, `@` isn't split off at the beginning of word but `#` is. If it's important for your texts, you may want to modify some of the tokenizer settings to have these tokenized in a way that makes sense for your task/patterns, since a small change to the tokenizer could make your patterns simpler. More info here: https://spacy.io/usage/linguistic-features#tokenization
