### ISSUE TITLE
Lemmatization problem of "Installing => Instal": Rule-based (with Exceptions) vs Look-up

### ISSUE THREAD

**Issue by jshin49** [explosion/spaCy#6075]
## How to reproduce the behaviour
I was running the following test code

```python
import spacy

nlp = spacy.load("en_core_web_sm")

doc = nlp("installing reinstalling installation installations installs reinstallations")

for tok in doc:
    print(tok.text, '->', tok.lemma_)
```

and the outputs are 
```bash
installing -> instal
reinstalling -> reinstall
installation -> installation
installations -> installation
installs -> install
reinstallations -> reinstallation
```

I was investigating this problem in-depth and realized there are weird behaviors in the [lemmatizer.py L46-47](https://github.com/explosion/spaCy/blob/a26f864ed3c227fab1d2a506e27cb4b5b5d831d2/spacy/lemmatizer.py#L46-L47)

Here, we can see that the "lemma_lookup" table (which is loaded from [spacy-lookups-data](https://github.com/explosion/spacy-lookups-data/blob/master/spacy_lookups_data/data/en_lemma_lookup.json)), is always disabled when using the pre-trained model (en_core_web_sm).

In the end, the code will call `self.lemmatize`, which then invokes an [exception rule ](https://github.com/explosion/spacy-lookups-data/blob/24da7d9c42432cefe26261a2b2ebc8ba259ed915/spacy_lookups_data/data/en_lemma_exc.json#L4526) which makes "instal" as the correct lemma (which is British version of install).

I can follow the logic, but I'm not sure if this is expected behavior. As there are over 40k lookup entries available for the pre-trained model, I'm not sure why rules should overrule the lookup. Shouldn't the logic be more like

1. We try to look up in the table first.
2. If failed, move on to the rule-based approach.

In code, maybe something like,
```python
if string in lookup_table:
    return [lookup_table[string, string]]
```

## Your Environment
* **spaCy version:** 2.3.2
* **Platform:** Linux-4.15.0-106-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.7.8

**Comment by adrianeboyd** [comment]
Yeah, the lemmatizer configuration in v2 models is confusing. It's trying to provide the best lemmas it can without requiring the user to manage any settings, but because it's not an explicit component in the pipeline, it's hard for users who want more fine-grained control to modify its behavior. By default, the lemmatizer switches from lookup lemmas to rule-based lemmas as soon as there's a tagger in the pipeline that provides `token.pos`. Switching entirely to rule-based lemmas is the intended behavior.

The main reason is that the lookup table doesn't use any additional context like POS, so it's hard to know whether there are ambiguous cases that it's handled poorly. But this is a just a choice and a particular lookup table might be a better first choice in some instances. Some languages have custom lemmatizers that refer to both the rules and lookups tables (French does, I think). It will be much easier to customize the lemmatizer in spacy v3, which is coming very soon.

If you want to change the results in your v2 model for individual cases like `instal`, you can modify the table in `nlp.vocab.lookups.get_table("lemma_exc")` to edit the lemmas for `installed` and `installing`. If you save the model with `nlp.to_disk`, it will save the modified tables so you can reload this as a custom model. I think the rule-based tables and the lookup tables come from different sources that aren't consistent in terms of which spelling is prioritized.
