### ISSUE TITLE
Changing one digit in a date changes NER result

### ISSUE THREAD

**Issue by oliviercwa** [explosion/spaCy#6077]
## How to reproduce the behaviour
```python
nlp = spacy.load("en_core_web_md")
a = nlp('This document is dated as of 08/14/2014')
b = nlp('This document is dated as of 07/14/2014')
print([x for x in a.ents])
```
Result: [08/14/2014]
```python
print([x for x in b.ents])
```
Result: []

Expected: Sentences are identical and the date changes by just one digit so I would expect spacy to detect them in both cases.

I understand the model may not have seen 07/14/2014 but this makes the entire date extraction (NER) questionable. 

Any suggestion to overcome such problem?

## Your Environment
* Operating System: Windows
* Python Version Used: 3.7.4
* spaCy Version Used: 2.1.9
* Environment Information:

**Comment by adrianeboyd** [comment]
This is just kind of the nature of statistical models, since the training data obviously can't contain every possible date. OntoNotes also doesn't contain many dates in this format, mainly dates that would appear in running newspaper text like `fifty years` and `1983` and `October 1, 2003`. The evaluation for `DATE` from `en_core_web_md` shows that even for dev data from the same corpus, some dates are missed and misclassified:

```
    "DATE":{
        "p":85.1393188854,
        "r":86.2669919833,
        "f":85.6994459834
      }
```

For the best overall NER performance, it's often best to combine rule-based and statistical models, especially for things like dates where it's easy to write regexes that will identify the majority of instances. The statistical model can be more useful to identify cases where the dates don't quite match a known format, like the name of month was spelled or abbreviated in a non-standard way.

On the other hand, since `en_core_web_md` isn't trained on many dates in this format, it might also be easy to update it with more examples so it recognizes this shape better as a date.

**Comment by oliviercwa** [comment]
Thank you Adriane for your answer.

Do you have any tutorial on how to retrain en_core_web_md with the original data set plus some additional custom data?

**Comment by adrianeboyd** [comment]
Here's the basic tutorial: https://spacy.io/usage/training#ner
