### ISSUE TITLE
Bad performance of POS tagger for Swedish

### ISSUE THREAD

**Issue by Nuccy90** [explosion/spaCy#6101]
Hi, I am experimenting with Swedish models hoping to contribute to the community. I have trained a tagger and parser model with Fasttext vectors using two UD treebanks, Talbanken and LinES. The UAS and LAS scores are comparable to those for similar languages (Danish and Norwegian), whereas the POS tagger performs much worse, with about 79.00 accuracy vs. 94-95.00 for the other Scandinavian languages. 

I am wondering whether this is an issue related to the language data available for Swedish, for example the quality of the tokenizer and the absence of lemmatization rules, or if it has to do with the word vectors and/or the training. Does anyone have a similar experience or any idea how to fix this?

**Comment by adrianeboyd** [comment]
The tagger is training on the `XPOS` column instead of the `UPOS` column for the Swedish corpora, which look like they have fine-grained tagsets with 100+ tags (different in each corpus). You can't really compare this to the results for Danish and Norwegian, which train the tagger directly on the `UPOS` tags instead because there are no values in the `XPOS` column. 

spacy's CoNLL-U converter uses the UPOS column as a backup for `tag` if the XPOS column isn't set. You can look at the `"tag"` values in the JSON file for each conversion to see which tags it's training/evaluating on.

**Comment by Nuccy90** [comment]
Thank you, that explains it!
