### ISSUE TITLE
Error when dealing with overlapping named-entities?

### ISSUE THREAD

**Issue by John-8704** [explosion/spaCy#6120]
I'm currently working on a NER model where the dataset has many overlapping entities like this below example,
`
("I like London and BerlinGermany.", {"entities": [(7, 13, "LOC"), (18, 24, "LOC"), (24, 31, "LOC")]}`

`18:24 is Berlin and 24:31 is Germany`

How can I deal with these cases? I want a model that can work in these type of situation also. I couldn't find any documentation in spacy docs page regarding this problem.

Any help is really appreciated.

**Comment by adrianeboyd** [comment]
A `Doc` in spacy can only represent one entity label per token and the built-in NER model can only predict one label per token (like `B-LOC` or `I-LOC`). This restriction is very common for NER annotation and NER models and makes it possible to implement very fast models.

One option is to develop multiple NER models that handle different types of entities or levels or nesting and then save the entity spans in custom extensions, but you won't be able to see both on the `doc` tokens at the same time. A brief sketch of how you might do this:

```
# nlp_ner1 labels "city", nlp_ner2 labels "city country"

# apply the first model
doc = nlp_ner1(text)
# save the entities on a custom extension
doc._.custom_ents += doc.ents

# reset ents, apply the second model
doc.ents = ()
doc = nlp_ner2(text)
# save the new entities
doc._.custom_ents += doc.ents

# do something with doc._.custom_ents
```

You'll run into additional problems here related to tokenization, since the default tokenizer is not going to split `BerlinGermany` into two tokens, so you can't label `Berlin` as an entity. You can only label whole tokens as part of an entity, so you'll want to adjust your tokenizer or preprocess your data.

**Comment by John-8704** [comment]
> A `Doc` in spacy can only represent one entity label per token and the built-in NER model can only predict one label per token (like `B-LOC` or `I-LOC`). This restriction is very common for NER annotation and NER models and makes it possible to implement very fast models.
> 
> One option is to develop multiple NER models that handle different types of entities or levels or nesting and then save the entity spans in custom extensions, but you won't be able to see both on the `doc` tokens at the same time. A brief sketch of how you might do this:
> 
> ```
> # nlp_ner1 labels "city", nlp_ner2 labels "city country"
> 
> # apply the first model
> doc = nlp_ner1(text)
> # save the entities on a custom extension
> doc._.custom_ents += doc.ents
> 
> # reset ents, apply the second model
> doc.ents = ()
> doc = nlp_ner2(text)
> # save the new entities
> doc._.custom_ents += doc.ents
> 
> # do something with doc._.custom_ents
> ```
> 
> You'll run into additional problems here related to tokenization, since the default tokenizer is not going to split `BerlinGermany` into two tokens, so you can't label `Berlin` as an entity. You can only label whole tokens as part of an entity, so you'll want to adjust your tokenizer or preprocess your data.

So, you are saying there's no way to train and predict overlapping entities.

**Comment by adrianeboyd** [comment]
That's just a more elegant suggestion for how to configure the pipeline to move the predicted entities into a custom extension. My suggestion just shows how to you could do this by hand for a single doc. The basic idea is the same: apply multiple models and move the entities into a custom extension after each model so that you can save overlapping spans, since you can't save them on `doc.ents`.

If you want to try out this option, you'll have to decide how to convert your data into multiple training sets that each contain non-overlapping entities.

**Comment by John-8704** [comment]
@adrianeboyd That is also complicated because how can I create multiple training sets that can contain non-overlapping entities unless I manually do it. I guess, for now it's not possible. Thank for helping out.
