### ISSUE TITLE
SpaCy stts-Tag for VVIMP in German

### ISSUE THREAD

**Issue by Fxlix** [explosion/spaCy#6136]
Heyho explosions, 
I'm having trouble receiving the correct stts-Tags, when analyzing German Sentences with imperative Verbs. 
They are all tagged as VVINF even with "!" as a sentence boundary, which should be a good indicator for imperatives in German. 

I tried many different Sentences but never received VVIMP, so maybe this is a bug, instead of inaccuracy. 

Best Regards,
Fx

## Your Environment

* Operating System: Debian10
* Python Version Used: 3.7.3
* spaCy Version Used: 2.3.2 German Model "de_core_news_lg"

**Comment by adrianeboyd** [comment]
This is a side effect of the training data, which is all newspaper text. There are just so few imperatives that the model doesn't really learn to identify them correctly. Questions and imperatives are a problem for a lot of the pretrained models because of the kinds of written texts that are often used in linguistic corpora.

**Comment by Fxlix** [comment]
Thank you for your answer. Then this Issue can be closed. 
Have a nice weekend.
