### ISSUE TITLE
Found uppercase lemma

### ISSUE THREAD

**Issue by scribu** [explosion/spaCy#6171]
## How to reproduce the behaviour

```python
import spacy

nlp = spacy.load('en_core_web_md')
doc = nlp('Need wordpress')

print(doc[0].lemma_)
```

I get `Need`, instead of `need`.

## Your Environment
* **spaCy version:** 2.3.2
* **Platform:** Darwin-19.6.0-x86_64-i386-64bit
* **Python version:** 3.7.4

Similar to #3551 which I thought was fixed in spaCy 2.1.

**Comment by adrianeboyd** [comment]
This is a different problem from #3551. The lemmatizer depends on the POS tags, which are not always 100%, especially for short texts without much context, and even more so if those texts don't look like the training data (mostly newspaper text).

If the POS tag is `PROPN` (proper noun), as it is here for `"Need"`, then the lemmatizer leaves it as uppercase. The English rule-based lemmatizer doesn't lowercase all results.

**Comment by scribu** [comment]
So you're saying it's working as expected?

**Comment by adrianeboyd** [comment]
It's not the expected behavior overall (the statistical tagger model makes a mistake here), but it's the expected behavior for the lemmatizer given this POS tag for this word.

spacy's provided models will typically be less accurate on short texts and texts that don't look like edited newspaper text. You would already get better results for a full sentence like `"They need wordpress."` than `"Need wordpress"`.

**Comment by scribu** [comment]
That makes sense. Thanks for the clarification!

Not sure if there's anything actionable here then, except training a better model. 🤷

**Comment by svlandeg** [comment]
I'm afraid so. It is often a good idea to (re)train a model on your specific corpus, as the properties of English text can vary quite a bit between sources. FYI, here's a link to the relevant docs section: https://spacy.io/usage/training#example-train-tagger

I'll close this issue as there's no actionable follow-up item anymore, but feel free to create a new one if you would run into problems!
