### ISSUE TITLE
Custom Lemmatization on Proper Nouns

### ISSUE THREAD

**Issue by eaporetsky** [explosion/spaCy#6254]
## How to reproduce the behaviour
I am trying to add custom lemmatization on proper nouns but there is not really any good documentation on how to extend the lemmatizer with your own, I am  using `en_core_web_md`. For example:
```
doc = nlp("ceos")
doc[0].lemma_ # 'ceos'
doc[0].pos_ # 'PROPN'
```

However I am expecting that `doc[0].lemma_` to be `ceo`. 

I've tried 
```
table = nlp.vocab.lookups.get_table("lemma_exc")
table["noun"]["ceos"] = ["ceo"]
```

```
nlp.vocab.lookups.get_table('lemma_rules')["propn"] = [["s", ""]]
```

But am still not able to add the word properly. Can someone point me in the right direction to adding custom lemmatization?

## Your Environment
* **spaCy version:** 2.3.0
* **Platform:** Darwin-19.6.0-x86_64-i386-64bit
* **Python version:** 3.7.7

**Comment by eaporetsky** [comment]
Would the best bet to train the POS tagger to properly recognize them as nouns?

**Comment by adrianeboyd** [comment]
The lemmatizer is hard to customize in v2 and the PROPN/NOUN distinction (which the tagger understandably has trouble with) causes difficulties.

My first guess is that you're not seeing your updates because you're running into the internal lemmatizer cache. Try making these modifications right after loading the model (before you've processed any texts)?

For `ceos/NOUN` you shouldn't need to add any extra rules, so maybe you meant `ceos/PROPN` in the first attempt that's modifying the exception table? The second suggestion for `propn` in the rules does look correct if you want to remove the final `s`.

Depending on what you need in your final results, if you don't care about the proper/common noun distinction and you want all proper nouns to be lemmatized like nouns, then you can modify the fine-grained tag and the lemma will be recalculated:

```python
import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp("ceos")
assert doc[0].lemma_ == "ceos"
assert doc[0].tag_ == "NNP"
doc[0].tag_ = "NNS"
assert doc[0].lemma_ == "ceo"
```

For the purposes of lemmatization, the `NN` / `NNS` distinction doesn't matter. They're both converted to `NOUN`, which is what the lemmatizer looks at.

**Comment by eaporetsky** [comment]
Hey @adrianeboyd, thanks for your response. 
It does seem that the internal lemmatizer cache does cause the issue above, and making the rule before processing any text 
does fix it. Are there any docs on the internal cache? That being said: is it still worth it to train the tagger better over adding these slightly hacky rules?

**Comment by adrianeboyd** [comment]
Unfortunately there's not a lot of good documentation on the v2 lemmatizer internals. The rule-based lemmatizer is kind of a hidden part of the tagger. The basic idea is that the pipeline tries to provide the best lemmas given the components it has (lookup lemmas without a tagger, rule-based lemmas with a tagger), but there are no user settings beyond the lemmatization tables to manage its behavior. The cache is hidden in the `Morphology` (under `nlp.vocab.morphology`) and keyed on `(token.tag, token.orth)`, so if it's seen this combination before, it doesn't recalculate the lemma. I don't think there's a python method to clear to disable the cache, which is frustrating.

In terms of what to do next, I'm not sure exactly what you need for your task? Updating or retraining the tagger would be a pretty major step and difficult to do well unless you're training a model from scratch with a large corpus. It depends on whether you care about the common/proper noun distinction or you just have individual words where you want to modify the results.

* You could copy all the `NOUN` rules and exceptions to `PROPN` to get the same results for both with the lemmatizer.

* If you want to get rid of the common/proper distinction through the tags, one option is to add a small pipeline component after the tagger that converts `NNP` to `NN` and `NNPS` to `NNS`.

* If you only have individual words that you want to modify, then lemmatizer exceptions might be the best option.

If you want to do a lot of lemmatizer customization, we'd recommend taking a look at the new v3 `spacy-nightly` release (https://nightly.spacy.io), where the lemmatizer is now a standalone component in the pipeline and much easier to extend and customize. Here, the default cache is a simple python dict that's much easier for custom lemmatizers to use and manage.
