### ISSUE TITLE
Spacy 2.3 biluo_tags_from_offsets: "Misaligned entities ('-') will be ignored during training" but then spacy convert raises an exception.

### ISSUE THREAD

**Issue by buriy** [explosion/spaCy#6267]
## How to reproduce the behaviour
I think you can take this example https://github.com/explosion/spaCy/issues/5727#issuecomment-655509687 and try to convert it with `spacy convert` tool.
Or take this one .conllu file:
```
1 asd _ _ _ _ _ _ _ -
```
You'll get "`ValueError: [E177] Ill-formed IOB input detected: -`"  at
```
File "gold.pyx", line 570, in spacy.gold.iob_to_biluo
File "gold.pyx", line 592, in spacy.gold._consume_ent
```

## Your Environment

* spaCy Version Used: 2.3.2

**Comment by adrianeboyd** [comment]
The `spacy convert` utility is completely separate from `spacy train`. This warning message means that `spacy train` ignores annotation that looks like `"ner": "-"` while training, so if your conversion (whether with `spacy convert` or your own script) produces `"-"` NER annotations, these will be ignored during training.

`spacy convert` has some regexes that try to identify various non-standardized formats for NER tags in the MISC column for use with some of the corpora used for the pretrained models. The NER regex detection is not particularly robust, so you may run into unexpected behavior if you have data that looks similar to IOB tags in the MISC column. In that case, if you just want to convert the rest of the CoNLL-U data, preprocess to remove everything except `SpaceAfter=No` from the MISC column. (Well, `SpaceAfter=No` is only used by the v3.0+ converter, but it's the main detail from the MISC column that the converter might use aside from NER annotation.)

I can't reproduce this error for this conllu example with v2.3.2, though? I get:

```json
[
  {
    "id":0,
    "paragraphs":[
      {
        "sentences":[
          {
            "tokens":[
              {
                "id":0,
                "orth":"asd",
                "tag":"_",
                "head":0,
                "dep":"_"
              }
            ]
          }
        ]
      }
    ]
  }
]
```

There's no `"ner"` entry because it doesn't think it found NER annotation in the MISC column.

**Comment by buriy** [comment]
Ah right, you need some entries with NER too.
This one reproduces the error for me:
```
1 asd _ _ _ _ _ _ _ O
2 def _ _ _ _ _ _ _ -
```

[test.conllu.txt](https://github.com/explosion/spaCy/files/5399843/test.conllu.txt)

**Comment by adrianeboyd** [comment]
Ah, you're trying to provide missing annotation labels in the CoNLL-U for use with the converter? The `-` for missing annotation is just supported when reading from the JSON training format. I don't think any of the NER format converters support that.

You should be able to provide your annotation with the original tokenization and the aligned NER labels. Then `spacy train` will handle any misalignments internally while training and you don't need to provide them like this. If you don't have the raw texts (or it's fine if it treats all your tokens as space-separated), then you should be able to convert the data from CoNLL-U without any extra steps. You could also skip the CoNLL-U step and just write the JSON format with BILUO tags directly. It would just look like this without raw texts (example from the wikipedia NER data for German; you can skip `"tag"`, this was just easy to copy):

[{
"id": 6149,
"paragraphs": [{
"sentences": [{
"tokens": [
{"tag": "APPR","ner": "O","orth": "Auf"},
{"tag": "NE","ner": "B-LOC","orth": "Trinidad"},
{"tag": "KON","ner": "I-LOC","orth": "und"},
{"tag": "NE","ner": "L-LOC","orth": "Tobago"},
{"tag": "KON","ner": "O","orth": "und"},
{"tag": "APPR","ner": "O","orth": "auf"},
{"tag": "NE","ner": "U-LOC","orth": "Kuba"},
{"tag": "VAFIN","ner": "O","orth": "wurde"},
{"tag": "ART","ner": "O","orth": "die"},
{"tag": "NN","ner": "O","orth": "Art"},
{"tag": "ADJD","ner": "O","orth": "wahrscheinlich"},
{"tag": "VVPP","ner": "O","orth": "eingeschleppt"},
{"tag": "$.","ner": "O","orth": "."}
]
}]
}]
}]
```

If you have the raw texts, then add them at the paragraph level.

If you really really want to go through the intermediate CoNLL-U step and you want to have the original raw text, it gets slightly tricker, but it's still doable. The main tricky part is that the v2.3 converter doesn't handle `SpaceAfter=No` yet, so you want to use the v3 converter instead, however it now outputs `.spacy` / `DocBin` instead of JSON. Let's see, I think you can do this:

With `spacy-nightly` (or in the future v3.0.0+):

```bash
spacy convert -n 10 data.conllu .
```

Convert to JSON (also with `spacy-nightly`):

```python
import spacy
import srsly
from spacy.tokens import DocBin
from spacy.training.gold_io import docs_to_json

nlp = spacy.blank("xx") # the lang doesn't matter, we just need a vocab
db = DocBin().from_disk("data.spacy")
docs = db.get_docs(nlp.vocab)
srsly.write_json("data.json", [docs_to_json(docs)])
```

Double-check with the v2.3 `spacy debug-data` that everything turned out correctly. There will be a few extra fields in the JSON file, but they shouldn't interfere with training.

**Comment by buriy** [comment]
@adrianeboyd 
I want to go with CONLLU which is a portable format so I can feed it to several packages and train all libraries at once, and I can do a comparison between different libraries quality.
Thus preparing CONLLU files is important for me.
I also want the same format to work for spacy 2.3 and spacy 3.0.
So far I ended up with this generator + a fixer from CONLLU "Tag=O|SpaceAfter=No" to "O" for spacy 2.3 (because apparently spacy 3.0 can handle the correct format): https://github.com/buriy/spacy-ru/blob/v2.3/training/fix_conllu.py .
Also, what SpaceAfter does do? I mean, what does it change in Spacy behavior? Does it only change the Doc() text output, or are predictions different?

**Comment by adrianeboyd** [comment]
Since the `-` is really a spacy-internal label, not something we expect to find in external datasets, I don't think it makes sense to support it in general in `spacy convert`.

If you're using v3 in your comparison anyway, I think it would be easiest to just use the v3 converter to produce both the `.spacy` and the `.json` files for your comparison (with the short script above). I actually used an early version of v3 converter for all the internal UD training corpora for the v2.3 models.

If you don't have the `raw` text in the JSON file for spacy v2.3, the training takes the provided tokens as the gold tokens, so if there's much of a mismatch between how the actual tokenizer tokenizes and the gold tokens, the model will not perform as well in the end on actual texts. If you evaluate using `spacy evaluate`, the evaluation on JSON files without `raw` texts will look inflated, too.

So I can understand a bit more why you might want to provide input like this to produce an accurate comparison, but you'll need to customize the converter to either handle the `-` values or include the raw texts. If your data is clean, adding support for the `# text = ` comment might be simpler than adding `SpaceAfter=No` handling. `SpaceAfter=No` just aligns really well with how spacy represents the tokens internally and I didn't want to add error handling for cases where the `# text` doesn't align with the tokens.
