### ISSUE TITLE
sentence segmentation bug in spacy-nightly?

### ISSUE THREAD

**Issue by gregorleban** [explosion/spaCy#6270]
## How to reproduce the behaviour
spacyCNN = spacy.load("en_core_web_sm")
doc = spacyCNN("Anti-Semitism has been weaponized. That is, the Zionists, within and without Israel, are using the charge of anti-Semitism as a weapon to silence those who are critical of the Israeli state. In wielding this weapon, Zionist organizations and the media outlets they control or influence have released a flood of slander and libel. The charge of anti-Semitism is leveled at anyone who opposes Israel's inherently racist policies and is supportive of Palestinian human rights. And, where the Zionists have sufficient political influence, as is the case in so much of the United States, they are making every effort to encourage laws that make criticism of Israel illegal because, they claim, it is ipso facto anti-Semitic. ")

for sent in doc.sents:
    print(sent)

0: Anti-Semitism has been weaponized.
1: That is, the Zionists, within and without Israel, are using the charge of anti-Semitism as a weapon to silence those who are critical of the Israeli state.
2: In wielding this weapon, )Zionist organizations and the media outlets they control or influence have released a flood of slander and libel.
3: The charge of anti-Semitism is leveled at anyone who opposes Israel's inherently racist policies and is supportive of Palestinian human rights.
4: And, where the Zionists have sufficient political influence, as is the case in so much of the United States, they are making every effort to encourage laws that make criticism of Israel illegal
5: because, they claim, it is ipso facto anti-Semitic.

Problem is that the last sentence is split on "because". I would understand if there would be some full stop or some exclamation mark, but to make a sentence split on "because" seems like an issue. Is this the problem of the model or a bug in the code?

## Your Environment
- **spaCy version:** 3.0.0rc1
- **Platform:** Windows-10-10.0.18362-SP0
- **Python version:** 3.6.5
- **Pipelines:** en_core_web_sm (3.0.0a0)

**Comment by adrianeboyd** [comment]
The parser is designed to be able to split sentences where there isn't punctuation so that it can handle things like headlines or informal text without punctuation, so the overall behavior isn't a bug in the code. However, this is probably a slight issue with the 3.0.0a0 models, though, since the `SHAPE` feature was accidentally left out and it may mean that capitalization isn't as strong a cue as before. We'll have 3.0.0a1 models published soon and you can see if it's still an issue?

As an alternate suggestion, if you just need sentence boundaries and not parses, you can try disabling the `parser` and enabling the `senter`, which is a new component that just does statistical sentence segmentation. The `senter` relies more strongly on local token features (like punctuation) as a cue, so it would be less likely to split the sentence here.

```python
import spacy
nlp = spacy.load("en_core_web_sm")
nlp.disable_pipe("parser")
nlp.enable_pipe("senter")
```
