### ISSUE TITLE
Training NER for new entities

### ISSUE THREAD

**Issue by Grinnbob** [explosion/spaCy#6288]
I'm trying to Training spacy via the command-line interface. Here is an example https://spacy.io/usage/training#spacy-train-cli : 

git clone https://github.com/UniversalDependencies/UD_Spanish-AnCora
mkdir ancora-json
python -m spacy convert UD_Spanish-AnCora/es_ancora-ud-train.conllu ancora-json
python -m spacy convert UD_Spanish-AnCora/es_ancora-ud-dev.conllu ancora-json
mkdir models
python -m spacy train es models ancora-json/es_ancora-ud-train.json ancora-json/es_ancora-ud-dev.json

My questions:
1. What should I clone instead of https://github.com/UniversalDependencies/UD_Spanish-AnCora? I wanna try en_core_web_trf for NER.
2. What should I convert instead of lines above?
3. Should I place my train and dev data in ancora-json/es_ancora-ud-train.json ancora-json/es_ancora-ud-dev.json ? And what is dev data?
4. How to make predict with trained model?

**Comment by adrianeboyd** [comment]
Be sure to refer to the nightly docs for spacy v3 for now: https://nightly.spacy.io

With the transformers pipelines, it's difficult to train from corpora that only contain information for some of the components (e.g., one corpus with dependency parses and another corpus with NER), so for just NER you'll want to start with a brand new transformers pipeline instead of trying to add a component to `es_dep_news_trf`. (I think you mean `es` instead of `en_core_web_trf`?)

The UD Spanish AnCora corpus does not contain entity annotation, so you'll need to find another corpus that provides entity annotation (we use WikiNER for the provided Spanish pipelines other than the transformer one).

Some examples of how to get started are here (choose GPU to get the transformers pipeline): https://nightly.spacy.io/usage/training#quickstart

If you have previously converted corpora to JSON with spacy v2, you'll need to convert them again with `python -m spacy convert` using spacy v3, since v3 uses a new output format (`DocBin` with the `.spacy` file ending instead of JSON). The convert commands should be the same as in v2: https://nightly.spacy.io/api/cli#convert
