### ISSUE TITLE
Spacy 2.1.9 not detecting sentences correctly

### ISSUE THREAD

**Issue by abhishekrnath** [explosion/spaCy#6289]
## How to reproduce the behaviour
```
import spacy

nlp = spacy.load('en_core_web_sm')
sentence = '29 Nov 2021 . 30 Nov 2021 . 29 Nov 2021 . '
doc = nlp(sentence)
for word in doc.sents:
    print(word.text)

```
### Expected Result
29 Nov 2021 .
30 Nov 2021 .
29 Nov 2021 .
### Actual Result
29
Nov 2021 .   
30 Nov 2021 .
29
Nov 2021 . 
## Your Environment
* **spaCy version:** 2.1.9
* **Platform:** Windows-10
* **Python version:** 3.6.8

**Comment by grohman** [comment]
Not sure if I need to open another issue, but I wanted to mention that there is a similar problem with `en_core_web_lg` and a text like `Test (something) - this is one sentence test.` - it will split into two sentences.

**Comment by abhishekrnath** [comment]
@grohman Can you give me that issue number?

**Comment by adrianeboyd** [comment]
Unlike many other sentence segmentation tools, the provided models in spacy use the parser to predict sentence boundaries so that it can handle things like headlines and informal texts without punctuation better. As a result, the parser is pretty good at splitting on phrase boundaries, but if your texts don't look like the training data (which is mostly newspaper text), the results may not be as good.

If you want to split sentences on particular punctuation symbols instead, take a look at the `sentencizer`: https://spacy.io/usage/linguistic-features#sbd-component

If you want to try out the upcoming spacy v3 (currently as `spacy-nightly`, see https://nightly.spacy.io) the provided models have a new `senter` component that just predicts sentence boundaries. It's disabled by default, you need to disable the parser and enable it to see it in action:

```python
# with spacy v3!
nlp = spacy.load("en_core_web_sm")
nlp.disable_pipe("parser")
nlp.enable_pipe("senter")
```

Since you only have to provide training data with sentence boundaries rather than full dependency parses, it's much easier to train a new model from scratch or update it with examples from your data to improve the performance.

In general, these kinds of issues with predictions are related to the statistical models and issue #3052 is a good place to report them, thanks!

**Comment by abhishekrnath** [comment]
Thanks @adrianeboyd 
The `sentencizer` served the purpose.
```
sentencizer = nlp.create_pipe("sentencizer")
nlp.add_pipe(sentencizer)
```
Here is the output:

29 Nov 2021 .
30 Nov 2021 .
29 Nov 2021 .

**Comment by svlandeg** [comment]
Perfect, I'll go ahead and close this issue then :-)
