### ISSUE TITLE
die Grundform von "habe" stimmt nicht // The base form is not correct: lemma(habe) = habe?

### ISSUE THREAD

**Issue by fannieywf** [explosion/spaCy#6306]
## How to reproduce the behaviour

> import spacy
> import de_core_news_lg
> nlp = de_core_news_lg.load()
> 
> test = nlp.tokenizer('Das habe ich ständig im Kopf.') 
> for t in test:
>     print(t, t.lemma_)
> [output] Das der
> [output] habe habe
> [output] ich ich
> [output] ständig ständig
> [output] im im
> [output] Kopf Kopf
> 
> test = nlp.tokenizer('Ich habe etwas') 
> for t in test:
>     print(t, t.lemma_)
> [output] Ich Ich
> [output] habe habe
> [output] etwas etwas

Expected lemma(habe) = haben. In the above cases lemma(habe) = habe.

## Your Environment

* Operating System: macOS Catalina v10.15.7
* Python Version Used: 3.7.6
* spaCy Version Used:2.3.0
* Environment Information:

**Comment by adrianeboyd** [comment]
The quality of the German lookup lemmas list is not great, to be honest, and it looks like "habe" is missing, which is a pretty unexpected gap.

As a workaround, you can add it with:

```python
import spacy
nlp = spacy.load("de_core_news_sm")
nlp.vocab.lookups.get_table("lemma_lookup")["habe"] = "haben"
```

There's an internal lemmatizer cache, so you need to make this change right after loading the model (before processing any texts), or you won't see the change because lemma from the cache will be used instead of the lookup table.
