### ISSUE TITLE
Generate different possible parse trees for a given sentence

### ISSUE THREAD

**Issue by vkorotchenko-homex** [explosion/spaCy#6314]
I was wondering if it possible to generate different possible parse trees for a given sentence?

**Comment by adrianeboyd** [comment]
Hi, you can use a beam search to return multiple parses. This functionality is in spacy mainly to support prodigy (it's not used at all by default in spacy) so unfortunately there isn't much documentation for spacy users about this. You can find more details if you search for "beam search" on the prodigy forum (look for Matt's replies): https://support.prodi.gy/search?q=beam%20search . Here's the most detailed explanation: https://support.prodi.gy/t/accessing-probabilities-in-ner/94/2

The basics would look like this:

```python
beam_width = 4
beam_density = 0.0

docs = list(nlp.pipe(texts, disable=["parser"]))
beams = nlp.get_pipe("parser").beam_parse(docs, beam_width=beam_width, beam_density=beam_density)

for doc, beam in zip(docs, beams):
    for score, parse in nlp.get_pipe("parser").moves.get_beam_parses(beam):
        # do something
        pass
```

I'm pretty sure this will return the raw results from the parser, so be aware that the parses will be missing a number of postprocessing steps that would otherwise be run before you see the final parse tree in a spacy `Doc` (deprojectivization, subtoken merging).

**Comment by mwilliamson-homex** [comment]
Thanks for the explanation, I think I got something working with Spacy 2. Is the expectation that this will continue to work in Spacy 3, or is there a different approach that should be used?

**Comment by adrianeboyd** [comment]
This is used by prodigy, so there will definitely be support in v3, but it's still in progress right now.
