### ISSUE TITLE
Surprisingly low scores for parsing polish

### ISSUE THREAD

**Issue by ryszardtuora** [explosion/spaCy#6334]
Hello,

I've been trying to compare various models for polish, and noticed that parsing performance is rather lacking, and definitely below the scores posted on your website. It might very well be some mistake on my part, but I've tried evaluating the parser both by using official CONLLU evaluation script, and by using built-in evaluator for spaCy (after converting data to json). Scores for the current version of PDB treebank are:

**UAS**: 76.46%
**LAS**: 68.68%

by using the spaCy evaluator I obtain the following:
**UAS**: 79.55%
**LAS**: 60.47%

Curiously, the results for the LFG treebank are significantly better, but still below the scores you report:
**UAS**: 89.29%
**LAS**: 71.66

It is not really clear to me which version of the Dependency treebank you've used. Back when I was cooperating with you on training the models, I've reccomended using the newest version of PDB, but the website mentions SZ which is its "ancestor". If this is correct, was there any reason for choosing the older version?

I'm using spaCy 2.3.2, on Python 3.6.9, with Linux Mint 19.3.

**Comment by adrianeboyd** [comment]
Yeah, this is frustrating. The details about the sources are here (at least with a version for UD Polish SZ) and in the model `meta.json`:

https://spacy.io/models/pl

The problem is the resource licenses. The other resources are GPL 3.0 but UD Polish PDB has been released under CC BY-NC-SA 4.0. We want to release a model under a single license (which is always the most restrictive license of all the training corpora) and these two licenses are not compatible, so we don't want to combine components with incompatible licenses in a single model. We also don't want to manage too many different models, like separate parser and NER models for Polish.

If you want to train a parser using UD Polish PDB, there's a new project for the upcoming spacy v3 that shows how to do this for any UD corpus (see the first inline info box): https://nightly.spacy.io/usage/projects . You can also run UD v2.5 benchmarks for spacy models (evaluating using CoNLL shared task eval script) with the `benchmarks/ud_benchmark` project: https://github.com/explosion/projects/tree/v3/benchmarks/ud_benchmark

The `spacy-nightly` models for Polish are also currently using the SZ data for the tagger instead of the NKJP corpus, since our current training pipeline is configured for joint tagger/morphologizer/parser training and it's hard to train from partially annotated data from multiple sources. We plan to have this resolved for the final v3 release, but just so you don't wonder what's going on in case case you try the newer models and notice that the tagset has changed.

**Comment by ryszardtuora** [comment]
I see. If i recall correctly, PDB should be available under GPL aswell, via dual-licensing (if that makes sense at all, I'm not well versed in these issues). I'll try to clear this up.

By the way, if I can help in any way in upgrading the models to spacy 3.0 please let me know. There are some transformers available for Polish, so it would be very exciting to have a transformer based.

Also, I'm very glad that spaCy is going to support morphology in the 3.0 update. This is a big step for NLP in Polish. I've experimented a little bit with the nightly version, and the results seem promising. It would also make our own project about inflection generation, compatible with the officially supported spaCy models.

**Comment by adrianeboyd** [comment]
If it is dual licensed (in particular `UD_Polish-PDB` or an equivalent resource with UD annotation), that would good news, and we could release the model with a PDB parser under a GPL 3.0 license. Do you know where the documentation is for this?

Right now we recommend `dkleczek/bert-base-polish-cased-v1` for Polish in the quickstart. Does this seem like a reasonable recommendation?

**Comment by michal-gh** [comment]
Hello,


I just checked the license of the `UD_Polish_PDB` at [http://git.nlp.ipipan.waw.pl/alina/PDBUD/blob/master/LICENSE.txt](url)
and it is indeed dual licensed: 
"The Polish PDB-UD treebank is dual-licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0) and GNU General Public License (GPL v.3)."
`NKJP1M-UD` based on NKJP data is licensed under GPL v3.

There is also another Polish BERT model: [https://github.com/sdadas/polish-roberta](url), licensed under LGPL v3. This model is trained on a larger dataset than `dkleczek/bert-base-polish-cased-v1`, but I haven't used it.

**Comment by adrianeboyd** [comment]
@michal-gh Thanks, that's just the kind of documentation I was looking for! We'll see if we can switch to UD Polish PDB v2.5 for the v3.1 Polish models, since I do think the performance will be a lot better.

For the quickstart, it's easiest to refer to models in the huggingface model repo, so I don't think we want to switch to this one right now, but we can keep in mind for the future, or as a recommendation outside of the quickstart.
