### ISSUE TITLE
ANNOYING Vietnamese custom tokenizer

### ISSUE THREAD

**Issue by catcd** [explosion/spaCy#6370]
I do not want to use pyvi in my project, I write my custom tokenizer and set default pyvi to False. BUT, why this ANNOYING code re-tokenize our tokenized text????
```
def make_doc(self, text):
    if self.Defaults.use_pyvi:
    	....
    else:
        ...
        for token in self.tokenizer(text):
            words.extend(list(token.text))
            spaces.extend([False] * len(token.text))
            spaces[-1] = bool(token.whitespace_)
        return Doc(self.vocab, words=words, spaces=spaces)
```
PLEASE remove these lines, and just return what our tokenizer return!!!!!

**Comment by adrianeboyd** [comment]
Hi, please don't use all caps, it feels like you're yelling at us.

If you want to use a custom tokenizer, you should implement a new tokenizer class as described here: https://spacy.io/usage/linguistic-features#custom-tokenizer

Although you can usually leave `nlp.make_doc` as-is because it just calls `nlp.tokenizer` by default, for Vietnamese you need to override both `make_doc` and `tokenizer` to get around the defaults mentioned above.

Try something like this:

```python
import spacy
from spacy.lang.vi import Vietnamese
from spacy.tokens import Doc
from spacy.util import DummyTokenizer

class WhitespaceTokenizer(DummyTokenizer):
    def __init__(self, vocab):
        self.vocab = vocab

    def __call__(self, text):
        words = text.split(' ')
        # All tokens 'own' a subsequent space character in this tokenizer
        spaces = [True] * len(words)
        return Doc(self.vocab, words=words, spaces=spaces)

nlp = Vietnamese()
ws_tokenizer = WhitespaceTokenizer(nlp.vocab)
nlp.make_doc = ws_tokenizer
nlp.tokenizer = ws_tokenizer
print([t.text for t in nlp("this is a test")])
```

The Vietnamese tokenizer should be modified to look more like Chinese or Japanese so this is easier in the future. PRs are welcome if you're interested in working on improving the defaults above or adding alternate tokenizers for Vietnamese.

If you want to add an alternative, it would probably be easiest to start with spacy v3 (currently in the `develop` branch) and take a look at the `ChineseTokenizer` as an example for how to set up the alternatives + serialization (just for the config settings, unless you also have models like for `pkuseg`, in which case the serialization may require a little more work).
