### ISSUE TITLE
Spacy convert output dir

### ISSUE THREAD

**Issue by yw2903** [explosion/spaCy#6380]
The following example command encounters error:
```python -m spacy convert /home/weiy/prodiy_training/Atomize_prodigy.jsonl ./output.spacy```

![image](https://user-images.githubusercontent.com/46970976/98864005-40915680-2437-11eb-9bed-c53e0a549694.png)

So should I create .spacy object before converting?
## Your Environment

* Operating System: Azure
* Python Version Used: 3.7
* spaCy Version Used: 3.0.0rc2

**Comment by svlandeg** [comment]
That second positional argument should be a directory, not a file ;-)
(full docs here: https://nightly.spacy.io/api/cli#convert)

**Comment by yw2903** [comment]
Thanks. I changed to an outpur dir. However, I got this error. So I'm unable to convert the jsonl dataset I used for spacy 2.3 training?

``` func = CONVERTERS[converter]
KeyError: 'jsonl'```

**Comment by adrianeboyd** [comment]
The v2 `jsonl` converter could only convert limited types of NER annotation from prodigy, so it's been removed in v3 in favor of `prodigy data-to-spacy`.

If you still have access to your data in prodigy, you can use the `prodigy data-to-spacy` command instead, which supports more annotation types than the `jsonl` converter. `prodigy data-to-spacy` is still set up to work with v2, so it produces a `.json` file that you need to convert to `.spacy` with the v3 `spacy convert` command.

You can also use spacy v2 converter to convert your current `.jsonl` to `.json` and then convert that with the v3 converter if you want to work from the `.jsonl` rather than from the prodigy databases.

**Comment by yw2903** [comment]
Thanks. When I initiate the annotation, I usually use the following command:

```prodigy ner.manual random blank:en  ./prodigy_training/random.jsonl --label RANDOM```

Should I still prepare my training set in Jsonl format?

**Comment by adrianeboyd** [comment]
After doing your annotation in prodigy, you want to do something like this to export the NER annotation from the dataset `random` to spacy v2 training `.json`:

```bash
prodigy data-to-spacy -l en --ner random random.json
```

You can include multiple prodigy datasets or combine different types of annotation with `data-to-spacy`: https://prodi.gy/docs/recipes#data-to-spacy

Then with spacy v3:

```bash
spacy convert random.json .
```

This will save `random.spacy` as the corpus to use as train/dev.

You can also use the `--eval-split` option with `prodigy data-to-spacy` to generate separate train and dev files by splitting the dataset.

(spacy v2 already has the functionality to create the same `.spacy` format, so it might be useful to add an option to `data-to-spacy` to output the v3 `.spacy` format instead of `.json` in the spacy v2-based version of prodigy.)
