### ISSUE TITLE
Re-Training Spacy Sentencerecognizer

### ISSUE THREAD

**Issue by roelvanderburg** [explosion/spaCy#6382]
I was trying to retrain the Spacy SentenceRecognizer (https://nightly.spacy.io/api/sentencerecognizer) 
I have a training file containing a list of Dutch sentences separated by line breaks .
But I have several issues:

1.  Initialising the sentence model does not work via the add_pipe or create_pip methods. (Only from class)

```
# Construction via add_pipe with default model
senter = nlp.add_pipe("senter")

# Construction via create_pipe with custom model
config = {"model": {"@architectures": "my_senter"}}
senter = nlp.add_pipe("senter", config=config)

# Construction from class
from spacy.pipeline import SentenceRecognizer
senter = SentenceRecognizer(nlp.vocab, model)

```
2. I have a hard time figuring out how to convert the input into something trainable. The documentation hints at transforming the sentences into Example objects  (https://nightly.spacy.io/api/example). However I have no idea how to proceed with this. 

## Your Environment -- Info about spaCy

* **spaCy version:** spacy-nightly             3.0.0rc2                  dev_0    <develop>
* **Platform:** Darwin-19.6.0-x86_64-i386-64bit
* **Python version:** 3.7.6

**Comment by adrianeboyd** [comment]
I assume you're using `spacy-nightly` (v3.0.0rc2) and not v2.2.0 as in the info above?

If you're training a new model from from scratch, the easiest way is to use `spacy init config` and `spacy train`:

```bash
spacy init config config.cfg -p senter -l nl
```

```bash
spacy train config.cfg --paths.train train.spacy --paths.dev dev.spacy -o output_dir
```

This reads the training data from `DocBin` files as described here: https://nightly.spacy.io/usage/training#data

One very nice change in spacy v3 is that you can just create `Doc` objects with your desired annotation to use as training data. The `Doc` objects should be saved in a `DocBin` with the file ending `.spacy`.

Unless you expect your input data to have one sentence per line (in which case you wouldn't need this component), you need to adjust your data a bit to create docs with typical paragraphs with whatever whitespace you expect between real sentences. Here's one simple example that uses `Doc.from_docs` to merge docs of individual sentences into longer docs with a random paragraph length. We're relying on the fact that the first token in a doc is always marked as the beginning of a sentence, so we're not marking it explicitly, but if your data didn't start as single sentences, you'd just need to set `token.is_sent_start = True` on the right tokens in each `Doc` before adding it to the `DocBin`.

```python
import spacy
from spacy.tokens import Doc
from spacy.tokens import DocBin

sentences = ["This is one sentence.", "This is another sentence."] * 25

nlp = spacy.blank("nl")
db = DocBin()

i = 0
while i < len(sentences):
    # some realistic paragraph sizes
    para_size = random.randint(3, 15)
    # create a Doc for each sentence
    sent_docs = [nlp(sent) for sent in sentences[i : i + para_size]]
    # merge the docs together (adding a single space between docs)
    doc = Doc.from_docs(sent_docs, ensure_whitespace=True)
    # add to the DocBin
    db.add(doc)
    i += para_size

db.to_disk("train.spacy")
```

You also could add newlines to the end of some of the sentences to create multi-paragraph documents. There are many ways to do this, the script above is just one example. The important thing is to create multi-sentence docs that look like your expected input so the model sees realistic sentence boundaries while training.

In terms of adding the component and training from `Example` objects as in the simple training examples (but we recommend `spacy train` for most cases), the first two options should work. What errors are you seeing?

The third option won't work anymore, which is a major difference in v3. You can still create the object, but you can't add it to pipeline because it doesn't have all the necessary config details saved in the object itself.

**Comment by roelvanderburg** [comment]
Dear @adrianeboyd, 

Thanks for the quick reaction. Running above code to create a "train.spacy" file and running command:
``
spacy train config.cfg --paths.train train.spacy --paths.dev dev.spacy -o output_dir
``

Unfortunately gives an
``
Exception: Error while initializing BPE: Token `Ċ` out of vocabulary
``

I found very little information about this error. It might be some encoding issue ?
