### ISSUE TITLE
ValueError: [E196] Refusing to write to token.is_sent_end. Sentence boundaries can only be fixed with token.is_sent_start.

### ISSUE THREAD

**Issue by ChrisChross** [explosion/spaCy#6385]
Hi folks,

I am trying to overwrite the sentence boundaries.
Something based on this post: https://github.com/explosion/spaCy/issues/1885.

For the beginning it works fine, however, if i try to overwrite the token.is_sent_end it throws me an error:
ValueError: [E196] Refusing to write to token.is_sent_end. Sentence boundaries can only be fixed with token.is_sent_start.

````python "filename: my_sentencizer.py"

from spacy.pipeline import Sentencizer

class MySentencizer(Sentencizer):
.... 
    def __call__(self, *args, **kwargs):
        doc = args[0]
        for tok in doc:
            tok.is_sent_start = None
            tok.is_sent_end = None
````

The reason want to do it, is to make sure that none of th prev. set values is existing. 
For some reason it seems to have run have default values (from runnin the sentencizer anyways?) even tho i do not have a "sentencizer" in my pipe.

Than 

```python "filename: main.py"

nlp = spacy.load("de_core_news_sm")
sentencizer = MySentencizer()
nlp.add_pipe(sentencizer, before="parser")
 doc = nlp("Das ist text 1. Das ist Text 2.")

````

Why is that and how to fix it? 

Thanks for help in advance. 
Chris

**Comment by adrianeboyd** [comment]
Hi, `token.is_sent_end` is just derived from `token.is_sent_start`, so you only need to reset `is_sent_start` to reset all the sentence boundaries. You might notice that `is_sent_start` is always `True` for the first token by default, but the others should be `None` unless a pipeline component has modified them.

**Comment by ChrisChross** [comment]
Okay, thanks, that would make sense. The only remaining question is than: if the end is infered from the beginning, is  everything in between alsoautomatically set to None (I think so)?

The strange part is: there is a value that is set before I call MySentencizer. Maybe the default sentencizer is called automatically before the parser (for whatever reason) ?

**Comment by adrianeboyd** [comment]
If no component has touched the `is_sent_start` values, the first one is `True` and the remainder are `None`. If this isn't what you're seeing, there must be some pipeline component that is modifying the values. The `sentencizer` and `parser` both set the sent start values to `True`. The default sentencizer sets the non-start values to `False` and the parser may add new `True` sent starts to any existing sent starts, but it won't modify any existing sent starts and it will leave the remaining values as `None`.

(Note: this is planned to change slightly for the parser in spacy v3, which will also set the remaining values to `False` rather than leaving them as `None`.)
