### ISSUE TITLE
Token.lex.prob returns constant values on nightly. 

### ISSUE THREAD

**Issue by koaning** [explosion/spaCy#6388]
## How to reproduce the behaviour

I think something is up with `Token.lex.prob` on nightly. 

When I run this code; 

```python
import spacy 
nlp = spacy.load("en_core_web_lg")
for t in nlp("bank of the riverside and stuff"):
  print(t.text, t.lex.prob)
```

I get this output. 

```
bank -20.0
of -20.0
the -20.0
riverside -20.0
and -20.0
stuff -20.0
```

It seems like all the words have a constant `prob` value. This is for both `en_core_web_md` and `en_core_web_lg`. 
 
## Your Environment

I'm running on google colab.

## Info about spaCy

- **spaCy version:** 3.0.0rc2
- **Platform:** Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- **Python version:** 3.6.9
- **Pipelines:** en_core_web_md (3.0.0a0), en_core_web_lg (3.0.0a0), en_core_web_trf (3.0.0a0)

**Comment by adrianeboyd** [comment]
Hi, this is a change in v2.3+, where the probability features aren't included with the pretrained models by default. See the section on "Probability and cluster features" for how to load very similar probability tables into a model in v2.3+: https://spacy.io/usage/v2-3#migrating

Be aware that the tables from `spacy-lookups-data` are not identical with the v2.2 models because there are 1M entries instead of 1.3M. The size of the tables in the `spacy-lookups-data` package starts to become a problem, so I just kept the most frequent 1M tokens.

If you need the exact same probabilities, you can export the probabilities from a v2.2 model and load them in if you need the exact same probabilities. You can set `lexeme.prob` manually for a lexeme to whatever prob value you'd like and the value will be saved when you save the model with `nlp.to_disk`.

**Comment by koaning** [comment]
Ah I wasn't aware of that. Thanks for the detailed explanation 👍 !
