### ISSUE TITLE
spacy, unable to installation, conflict with blis

### ISSUE THREAD

**Issue by elzorro321** [explosion/spaCy#6429]
## How to reproduce the problem
Have been trying to install spacy in a virtual environment, which is a prereq for using pycaret. Somehow, it appears that it is trying to compile another package (blis), however blis is already installed in the environment.

`pip install -U spacy --no-cache-dir`

Tried also using `spacy-2.3.2-cp39-cp39-win_amd64.whl` and `blis-0.7.2-cp39-cp39-win_amd64.whl` to install both packages to no avail.

The following packages are already installed:
- preshed>=3.0.2,<3.1.0 
- cymem>=2.0.2,<2.1.0
- murmurhash>=0.28.0,<1.1.0
- thinc==7.4.1

## Your Environment
* Operating System: Windows 10 (vr 2004, OS build 19041.630)
* Python Version Used: 3.9.0 (64bit)
* spaCy Version Used: "trying to use vr 2.3.2"

## Error, output:
See output file attached.
[spacy, install error.txt](https://github.com/explosion/spaCy/files/5581149/spacy.install.error.txt)

**Comment by adrianeboyd** [comment]
Please use python 3.8 for now to install v2.3.2. We'll have python 3.9 wheels for the upcoming bugfix release v2.3.3 soon.

**Comment by adrianeboyd** [comment]
Ah, I see I may have misunderstood. Where did you get `spacy-2.3.2-cp39-cp39-win_amd64.whl` from, since it's not something we've published on pypi?

The underlying problem is that spacy v2.3.2 has the `blis` pins `>=0.4.0,<0.5.0` and there aren't any python 3.9 `blis` wheels published (by us, on pypi) for this version range.

If you want to build the `spacy` v2.3.2 wheels yourself for python 3.9 and you don't want to compile `blis`, you'd need to edit the `blis` pins to `>=0.4.0,<0.8.0` in both `spacy` and `thinc` and build custom wheels for both.

`blis` v0.7.x should be compatible, but we are conservative with upper pins when we publish packages to try to avoid unexpected version conflicts in the future.

**Comment by elzorro321** [comment]
Thank you. Using Python 3.8.6 solved the issue.

It would be quite helpful if the documentation states such an important requirement, as it just says Python 3.5+ as required.

**Comment by adrianeboyd** [comment]
spacy itself supports python 3.9 if you compile from source, it just that it takes a bit of time to prepare new releases and publish prebuilt binary wheels for spacy and all its dependencies after each new version of python has been published.

We've been working on it and I hope we'll have a release for spacy with binary wheels for python 3.9 tomorrow.
