### ISSUE TITLE
v3.0rc2 spacy project push: no client registered to handle "s3" paths

### ISSUE THREAD

**Issue by adamkgoldfarb** [explosion/spaCy#6467]
## How to reproduce the behaviour
1. Create a spacy project in spacy-nightly. 
2. Define outputs in a nested directory.
3. Run script and confirm outputs are correctly captured.
4. Ensure directories exist in s3 (though ideally the "push" command would ensure these exist)
5. Attempt to push outputs to s3 results in a ValueError from pathy:

`ValueError: There is no client registered to handle "s3" paths`

Narrative for above: 

Pulling assets from s3 works well. I can use boto3 in a supporting script as a kind of post-hook to ensure the directories exist, but even then the s3 client won't push the outputs defined in project.yml to their respective directories. I'll open up pathy and check things out next.

## Your Environment
- **spaCy version:** 3.0.0rc2
- **Platform:** macOS-10.16-x86_64-i386-64bit
- **Python version:** 3.8.5

**Comment by adamkgoldfarb** [comment]
Looks like there are only clients for GCS and the local filesystem in pathy at this point. Fine to experiment with GCS and local filesystem until more storage endpoints are added!

**Comment by mgutmann** [comment]
Hello, I am trying to setup a spacy project with an ssh remote. I get the same `ValueError: There is no client registered to handle "s3" paths` problem. I understand that pathy does not support ssh paths for now, but I'm a little confused since the spacy remotes documentation says that it uses smart_open and that any protocol smart_open supports, such as ssh, is supported. Am i missing something? Thank you for your help!
