### ISSUE TITLE
mypy error: Skipping analyzing 'spacy.tokens': found module but no type hints or library stubs

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#6468]
Not a real bug - just static type checker being unhappy.

## How to reproduce the behaviour

Create file `tmp.py`

```python
from spacy.tokens import Doc
```

    > mypy tmp.py                                                                                                                                                                ─╯
    app.py:1: error: Skipping analyzing 'spacy.tokens': found module but no type hints or library stubs

## Info about spaCy

- **spaCy version:** 3.0.0rc2
- **mypy version:** 0.79
- **Platform:** macOS-10.15.7-x86_64-i386-64bit
- **Python version:** 3.8.5

**Comment by mr-bjerre** [comment]
Something odd though. I can't reproduce the error on my ubuntu machine in a similar environment. Thats odd!

**Comment by mr-bjerre** [comment]
Oh wait I just realized that this is also the case in 2.3.4. I just started using `mypy` so it might just not be supported. My mistake (I guess!?). I'll let you guys close it just to be sure.

**Comment by svlandeg** [comment]
I'm guessing this is because `Doc` is a Cython class? But I don't think this a problem?

**Comment by mr-bjerre** [comment]
Yeah maybe not a problem. My VSCode just suddenly started flagging it which it didn't use to but I might have changed some settings that caused it

**Comment by davidatbu** [comment]
[Explosion's blog post regarding spaCy 3.0](https://explosion.ai/blog/spacy-v3-nightly) says:
> spaCy’s user-facing API that’s implemented in pure Python (as opposed to Cython) now comes with type hints

Since `Doc` is implemented in Cython, there are in fact no type hints, so @mr-bjerre , you should not be looking for VSCode issues.

@svlandeg , are there any plans to annotate the Cython code with type hints? The most straight forward way would be to create a `pyi` file corresponding to every `.pyx` file, and then including a `py.typed` file with the word `partial` in it (all of this is from [PEP 561](https://www.python.org/dev/peps/pep-0561/) ).

**Comment by Ierezell** [comment]
Hi, is there any followup on this issue ? I stumbled on the same problem and cannot get mypy typings because of the Cython classes... 

Is it planned to add some pure python typings or in python/mypy to lookup for cython code ?

Thanks in advance, 
Have a great day !
