### ISSUE TITLE
can't install cuda support on linux for cuda 1.1

### ISSUE THREAD

**Issue by lockejan** [explosion/spaCy#6486]
## How to reproduce the problem

first I tried literally the code snippets from the website `pip install -U spacy[cuda]`
this resulted in `zsh: no matches found: spacy[cuda]`
Ok, my shell can't deal with the square brackets.
Used quotation marks then to escape them, which helped here. (Might be good to add this to the docs to make copy+paste work.)

After running that...the dependent cupy build fails always:

```bash
Building wheels for collected packages: cupy
  Building wheel for cupy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/schmitt/git/study/explore-zendesk/.venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cp012vja/cupy_fb58f51e771a4587abb8e187e1e8da9b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cp012vja/cupy_fb58f51e771a4587abb8e187e1e8da9b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-vtt8gtlq
       cwd: /tmp/pip-install-cp012vja/cupy_fb58f51e771a4587abb8e187e1e8da9b/
  Complete output (329 lines):
  Options: {'package_name': 'cupy', 'long_description': None, 'wheel_libs': [], 'wheel_includes': [], 'no_rpath': False, 'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False, 'use_hip': False}

  -------- Configuring Module: cuda --------

  -------- Configuring Module: cusolver --------

  -------- Configuring Module: cudnn --------

  -------- Configuring Module: nccl --------

  -------- Configuring Module: nvtx --------

  -------- Configuring Module: thrust --------

  -------- Configuring Module: cutensor --------
  /tmp/tmpmnwk_i48/a.cpp:1:10: fatal error: cutensor.h: No such file or directory
      1 | #include <cutensor.h>
        |          ^~~~~~~~~~~~
  compilation terminated.
  command 'gcc' failed with exit status 1

  -------- Configuring Module: cub --------

  ************************************************************
  * CuPy Configuration Summary                               *
  ************************************************************

  Build Environment:
    Include directories: ['/opt/cuda/include', '/tmp/pip-install-cp012vja/cupy_fb58f51e771a4587abb8e187e1e8da9b/install/../cupy/core/include']
    Library directories: ['/opt/cuda/lib64']
    nvcc command       : ['/opt/cuda/bin/nvcc']

  Environment Variables:
    CFLAGS          : (none)
    LDFLAGS         : (none)
    LIBRARY_PATH    : (none)
    CUDA_PATH       : /opt/cuda
    NVTOOLSEXT_PATH : (none)
    NVCC            : (none)
    ROCM_HOME       : (none)

  Modules:
    cuda      : Yes (version 11010)
    cusolver  : Yes
    cudnn     : Yes (version 8005)
    nccl      : Yes (version 2708)
    nvtx      : Yes
    thrust    : Yes
    cutensor  : No
      -> Include files not found: ['cutensor.h']
      -> Check your CFLAGS environment variable.
    cub       : Yes

  WARNING: Some modules could not be configured.
  CuPy will be installed without these modules.
  Please refer to the Installation Guide for details:
  https://docs.cupy.dev/en/stable/install.html

  ************************************************************

... (skipped lines here)

    RuntimeError: Missing file: cupy/cuda/cupy_cub.cu
    Please install Cython 0.28.0 or later. Please also check the version of Cython.
    See https://docs.cupy.dev/en/stable/install.html for details.
```

## Your Environment

* Operating System: Arch Linux x86_64, 5.7.11-arch1-1
* **spaCy version:** 2.3.4
* **Platform:** Linux-5.9.11-arch2-1-x86_64-with-glibc2.32
* **Python version:** 3.8.6
* Environment Information: poetry with virtualenv and also tried it with conda.
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
```

**Comment by lockejan** [comment]
After installing cupy manually beforehand via `poetry run pip install cupy-cuda111` it worked.
I think this is related to spacy's setup config. Please correct me if I'm wrong.

**Comment by adrianeboyd** [comment]
The problem is that you may run into errors with cupy v8 and spacy v2, in particular when training new models. There's not a `cupy-cuda111` package for `<8.0.0`, so we haven't added an extra like `spacy[cuda111]` because there's no supported package to download.

You can still compile `cupy` from source for this configuration, but you may need to adjust your setup a little to fix the errors quoted above. It can be tricky to install from source, in particular check the notes in the gray boxes at the top:
https://docs.cupy.dev/en/stable/install.html#installing-cupy-from-source

Also be sure you don't accidentally end up with multiple `cupy` packages installed, like `cupy` and also `cupy-cuda111` or things won't work.

Hmm, I can't get the sdist to work out of the box, so if you want to compile the older version from source, I'd recommend starting from the git repo instead like this:

```
git clone https://github.com/cupy/cupy
cd cupy
git checkout v7.8.0
pip install -U pip setuptools wheel
pip install .
```

(Personally I just downgraded to CUDA 11.0 so there was a binary package available and I didn't have to deal with this. Compiling it is tricky and can take a really long time. I just tested the steps above and it failed after compiling for an hour, so I can't even report that this works for sure, but I imagine I just didn't get the setup quite right.)

We should see if we can fix the underlying `scatter_add` problem in the next version of thinc v7 because this will cause problems as CUDA upgrades come along and there are fewer compatible cupy-cudaNNN packages.

**Comment by lockejan** [comment]
Thanks for the quick reply.

> The problem is that you may run into errors with cupy v8 and spacy v2, in particular when training new models. There's not a cupy-cuda111 package for <8.0.0, so we haven't added an extra like spacy[cuda111] because there's no supported package to download.

I'm not sure if I got this correctly. 
I understand that there's no package available which is compatible with `cupy-cuda111` and cupy `<8.0.0` and that is only important because spaCy isn't compatible with cupy `>=8.0`?

**Comment by adrianeboyd** [comment]
Right, spacy v2.3.4 (really thinc `<=7.4.3`) is not compatible with cupy v8.

These are the only releases on pypi for `cupy-cuda111`: https://pypi.org/project/cupy-cuda111/#history
