### ISSUE TITLE
pos tags disappear after adding custom tokenizer

### ISSUE THREAD

**Issue by koren-v** [explosion/spaCy#6493]
Hi, I've tried to add a custom Japanese tokenizer using your [example](https://spacy.io/usage/linguistic-features#custom-tokenizer). But after adding it, all pos tags become empty strings ('') even if tokenization is done exactly as default (I mean that sentence is split in the same way):

```
import ja_core_news_sm
from spacy.tokens import Doc
import JapaneseTokenizer


class SpacyJapaneseTokenizer:
    def __init__(self, vocab):
        self.vocab = vocab
        self.tokenizer = JapaneseTokenizer.KyteaWrapper()

    def __call__(self, text):
        tokens = self.tokenizer.tokenize(text, return_list=True)
        # All tokens 'own' a subsequent space character in this tokenizer
        spaces = [False] * len(tokens)
        return Doc(self.vocab, words=tokens)

ja_nlp = ja_core_news_sm.load()
ja_nlp.tokenizer = SpacyJapaneseTokenizer(ja_nlp.vocab)

doc = ja_nlp("本を読む")
for t in doc:
    print(t.text, t.lemma_, t.pos_, sep="\t")

# 本	本	
# を	を	
# 読	読	
# む	む	

t.pos_
# ''
```
The packages installation used in the example:
```
pip install kytea
pip install JapaneseTokenizer
git clone https://github.com/neubig/kytea.git
cd kytea/
autoreconf -i
./configure
sudo make
sudo make install
```

* **spaCy version:** 2.3.2
* **Platform:** Linux-5.4.0-1031-azure-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.9

**Comment by adrianeboyd** [comment]
Hi, the reason is that the default `JapaneseTokenizer` uses `sudachipy` to do more than tokenization. Since it has all the required information available at the tokenization step, it assigns tokens, tags, pos, and lemmas. If you replace it with a custom tokenizer, you'll lose this extra annotation.

It looks like KyTea might also provide tags, so you could potentially use these tags and create a tag map that maps them to UPOS tags.

It's also possible you could still use `sudachipy` to tag your docs (depending on whether it supports pre-tokenized texts and whether its models are a good match for KyTea-segmented tokens). If you want to do this, you'd need to write a custom component like a `SudachipyTagger` that calls `sudachipy` to add this annotation. It would look very similar to `JapaneseTokenizer` except it would be called with a `Doc` instead of a text and it would skip the actual tokenization steps.

And you can always train a new `tagger` component using a corpus with part-of-speech annotation, again, as long as the segmentation in the training data lines up well with your tokenizer's segmentation.

**Comment by koren-v** [comment]
Thanks
