### ISSUE TITLE
Train NER with brat Standoff format

### ISSUE THREAD

**Issue by BonarBeavis** [explosion/spaCy#651]
Hi,

I would like to create a workflow to train the NER module with manually created annotations. I would like to use [Brat](http://brat.nlplab.org/). Do I have to write a parse function for the standoff format, according to the training example?

Cheers

**Comment by honnibal** [comment]
The GoldParse class should accept entity annotations by character index. Is
this not working?

**Comment by BonarBeavis** [comment]
It is working, I just wanted to check, if there is already a function to parse the standoff format,  before I write one myself.

**Comment by honnibal** [comment]
spaCy doesn't provide any data readers. I think it's better to split that sort of thing into another package.

**Comment by honnibal** [comment]
Just pushed the NER usage tutorial to spacy.io, which has some more details about training the entity recogniser with stand-off annotations: https://spacy.io/docs/usage/entity-recognition

**Comment by benolayinka** [comment]
@BonarBeavis, did you write a function to parse standoff? I'm about to do it too. Someone wrote a nice python library to work with brat repos natively, so I'm just planning to extend it. https://github.com/clips/bratreader/tree/master/bratreader

**Comment by BonarBeavis** [comment]
@benolayinka, no I did not it is all yours.

**Comment by demongolem** [comment]
I too am doing a similar thing, taking existing BRAT annotations and trying to feed them to the spaCy ner trainer.  It goes without saying the toughest part is going from the global token offset start and end tags in BRAT to the local offset start and end tags of a sentence.  The two are the same if we treat the whole document as a single sentence, but I imagine this would not enable training to proceed in a meaningful fashion.  It would be so much more practical though if instead of feeding sentence by sentence for training to feed document by document.  If this is already possible, an example on the documentation pages would be helpful because I deal with documents.

**Comment by benolayinka** [comment]
@demongolem I did it with bratreader https://github.com/clips/bratreader/tree/master/bratreader

If I can find my files, I'll upload them. If you want to do it yourself, bratreader exposes sentence objects and some indexes internally. You can use those to calculate the offsets by subtracting token indexes from sentence beginning indexes.

**Comment by demongolem** [comment]
@benolayinka I already have a bunch of python helper utilities to read the BRAT format.  I have tried bratreader and still have that available in my code directories, but I was hoping I would not have to do all the calculations myself that you mention.  Certainly if you do have code that helps with this offset calculation for local sentence offset, I think it would benefit us all to share that.  But, in creating sentences, are there going to be annotations that have to be thrown away because they span 2 sentences (i.e. mistake in sentence splitting).

**Comment by benolayinka** [comment]
Here's how I did it. This is from my forked version of bratreader, I made
some slight changes to allow recursive folder searching for Repomodel
objects. -> https://github.com/benolayinka/bratreader

keys is a dict translating brat keys to spaCy keys. See train_ner.py.

def get_annotated_sents(doc, keys):
ann_sents = []
for sent in doc.sentences:
anns = []
ann_sent=u" ".join([x.form for x in sent.words])
for word in sent.words:
if word.annotations:
for ann in word.annotations:
for label, valency in ann.labels.items():
anns.append((ann.realspan[0]-sent.start, ann.realspan[1]-sent.start,
keys.get(label,label)))
if anns:
ann_sents.append((ann_sent,anns))
return ann_sents

**Comment by benolayinka** [comment]
Here's how I did it. This is from my forked version of bratreader, I made
some slight changes to allow recursive folder searching for Repomodel
objects. -> https://github.com/benolayinka/bratreader

keys is a dict translating brat keys to spaCy keys. See train_ner.py.

```
def get_annotated_sents(doc, keys):
    ann_sents = []
    for sent in doc.sentences:
        anns = []
        ann_sent=u" ".join([x.form for x in sent.words])
        for word in sent.words:
            if word.annotations:
                for ann in word.annotations:
                    for label, valency in ann.labels.items():
                        anns.append((ann.realspan[0]-sent.start, ann.realspan[1]-sent.start, keys.get(label,label)))
        if anns:
            ann_sents.append((ann_sent,anns))
    return ann_sents
return ann_sents
```
