### ISSUE TITLE
Sentencizer Exception: Error while initializing BPE: Token `Ċ` out of vocabulary

### ISSUE THREAD

**Issue by roelvanderburg** [explosion/spaCy#6529]
Thanks for the quick reaction. Running above code to create a "train.spacy" file and running command:

``
spacy train config.cfg --paths.train train.spacy --paths.dev dev.spacy -o output_dir
``

Unfortunately gives an

``
Exception: Error while initializing BPE: Token `Ċ` out of vocabulary
``

_I found very little information about this error. It might be some encoding issue ?_

_Originally posted by @adrianeboyd in https://github.com/explosion/spaCy/issues/6382#issuecomment-726064716_

**Comment by adrianeboyd** [comment]
See the original issue #6382 for more context.

I suspect you ended up with a transformers pipeline because of the current `init config` defaults and not because you picked it on purpose? A transformers pipeline is probably complete and total overkill for this particular use case, and this error may just be something like a library version mismatch related to some transformers dependencies? I'm not sure without more info.

If your goal is just to train a `senter` model, try this for the config instead, which uses spacy's default tok2vec instead:

```bash
spacy init config config.cfg -p senter -l nl -C
```

**Comment by roelvanderburg** [comment]
Thanks Adrianboy, this worked
