### ISSUE TITLE
[enhancement] Disjunctions in Matchers

### ISSUE THREAD

**Issue by asciiascetic** [explosion/spaCy#670]
It would be awfully nice to be able to do something like

````python

matcher.add_pattern('MyPattern', [{POS: ['NOUN','PROPN'], 'OP' : '+'}, {IS_PUNCT: True}])

````

Where the lists are disjunctions on token  matches (like the `|` operator in regular expressions).  Is  something like this supported or must a separate pattern be added for each alternate case?

**Comment by honnibal** [comment]
Currently this is unsupported. I see how this would be nice, though.

The idea at the moment is to give you a pretty low-level view of the matcher. Unlike a normal regex situation, you've got the normal Python logic to "roll your own sugar" -- so the lack of higher level constructs in the pattern language isn't so bad. Expanding out that disjunction is just a for loop away, after all.

I'm wary of adding more constructs to the pattern matcher, because this is a situation where backwards incompatibility will really suck. It's easy to imagine a team investing a lot into a good pattern grammar...If we then change how patterns work, they'll probably have to fork.

So: I'd like to be quite conservative in what we add here. I don't think the current system is absolutely perfect — but I'd like to change it slowly, and get people to do as much in user-space as they can.

**Comment by asciiascetic** [comment]
Yeah no doubt. Unless its a feature that a significant hunk of users craves then I agree that its prudent to just wait.

So, in order to accomplish the effect suggested by the above, the recommended course is to do something like:

````python
nominals = ['NOUN','PROPN']

for pos in nominals:
    matcher.add_pattern('MyPattern', [{POS: pos, 'OP' : '+'}, {IS_PUNCT: True}])

````

Yeah that seems fine :+1: 

Thanks for the commentary fellow, and thanks for the project. Its a blast to use!
