### ISSUE TITLE
Why does pipeline perform worse than normal operation?

### ISSUE THREAD

**Issue by mitramir55** [explosion/spaCy#6700]
Hi, I've been using spacy matcher to detect passive voice in my data. However, I have around 1 million records, each containing around 10 sentences. Here the speed of the process is a problem and that's why I need to use SpaCy pipelines that can utilize CPU usage. But unfortunately, the pipeline is taking around 10x more time than the simple mapping of each record and finding the matches. I think maybe I'm missing a simple thing here. 
Thanks in advance!

```
nlp = spacy.load("en_core_web_md", disable=["ner"])
matcher = Matcher(nlp.vocab)

passive_rule1 = [
    {"DEP": "nsubjpass"},
    {"DEP": "xcomp", "OP": "*"},
    {"DEP": "aux", "OP": "*"},
    {"DEP": "nsubjpass", "OP": "*"},
    {"DEP": "auxpass"},
    {"DEP": "nsubj", "OP": "*"},
    {"TAG": "VBN"},
]
passive_rule2 = [
    {"DEP": "attr"},
    {"DEP": "det", "OP": "*"},
    {"Tag": "NOUN", "OP": "?"},
    {"TAG": "VBN"},
]


matcher.add("passive_rule1", None, passive_rule1)
matcher.add("passive_rule2", None, passive_rule2)

%%time
docs = nlp.pipe(data_1, n_process = -1, batch_size = 50)
pass_list = [1 if matcher(doc) else 0 for doc in docs]
>> output: ~1min 26s

```

- Operating System: Windows 10
- Python Version Used:  Python 3.8.3
- spaCy Version Used: 2.3.5

**Comment by adrianeboyd** [comment]
Multiprocessing in windows can be slow, especially with larger models with vectors, because it uses spawn rather than fork. As a result, `nlp.pipe()` with `n_process>1` is not necessarily going to be faster than using a single process for relatively short tasks (on the order of a few minutes).

On CPU `batch_size=50` is quite small, too. I'd suggest at least `1000`, which is the default for `nlp.pipe()`, you can go potentially a lot higher if you have short texts and/or a lot of RAM) and once you have an idea of how much RAM one process needs for a certain batch size, you can experiment with starting with small numbers of processes for `n_process` (I'd start with 2-4) to see if the overall running time improves.

In addition, patterns with many `*` operators can be slow in general if there are a lot of partial matches that the `Matcher` has to keep track of, but if it's not a problem for your texts with `nlp()` rather than `nlp.pipe()`, then that's not what's causing it to be slower in this example, either.

**Comment by mitramir55** [comment]
Thank you very much! Indeed, I tried a few different ways and found that my system can perform best with n_process = 4 and batch_size around 1000. I guess while I tried out my matcher on a small number of sentences and records, the overhead was significant compared to when I stuck to one core, but moving one to larger corpora, I found using more processes can be of great help.

**Comment by f0lie** [comment]
I ran into this issue with Windows vs Linux multiprocessing. I can't really give a good estimate on size because the data set is 43 medical papers and I am not really sure what's the total size of text. I do know that it takes a while. On Windows it takes `51` seconds but running the same code on Linux takes `14` seconds. It's literally running the same code, I am using WSL2 so I just go to the Windows part and run that. I know @adrianeboyd stated that Windows would be slower but I didn't think it would be this bad. I am wondering what causes this difference.

Also I noticed that number of function calls is different between the two systems.

```
def get_dependencies(pipeline, text_df, file_name, compress=False) -> None:
    print("Finding the dependencies")
    if compress:
        csv_file = gzip.open(file_name + ".gz", 'wt', encoding='utf-8')
    else:
        csv_file = open(file_name, 'wt', encoding='utf-8')

    def iter_row(input_df):
        for _, row in input_df.iterrows():
            yield str(row['abstract']), {"cord_uid": row["cord_uid"], "type": "abstract"}
            yield str(row['full_text']), {"cord_uid": row["cord_uid"], "type": "full_text"}

    def token_to_str(dep_tok):
        children = [f"{child}" for child in dep_tok.children]
        return f'"{dep_tok.text}",{dep_tok.dep_},"{dep_tok.pos_}",' \
               f'"{dep_tok.head.text}",{dep_tok.head.pos_},{children}\n'

    # The every row of the CSV file is a single word.
    # type is whether it's the full_text or abstract
    # sentence is the serial id of the text that it belongs to
    csv_file.write("cord_uid,type,sentence,text,dep,pos,head_text,head_pos,children\n")
    for doc, context in pipeline.pipe(iter_row(text_df), as_tuples=True, batch_size=1000, n_process=4):
        sentence = 0
        for sent in doc.sents:
            for token in sent:
                csv_file.write(f"{context['cord_uid']},{context['type']},{sentence}," + token_to_str(token))
            sentence += 1

    csv_file.close()
```

Windows: 
```
         4266507 function calls (4221439 primitive calls) in 50.870 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    57/50    0.000    0.000    0.009    0.000 <frozen importlib._bootstrap>:1017(_handle_fromlist)
        9    0.000    0.000    0.000    0.000 <frozen importlib._bootstrap>:103(release)
        9    0.000    0.000    0.000    0.000 <frozen importlib._bootstrap>:143(__init__)
        9    0.000    0.000    0.000    0.000 <frozen importlib._bootstrap>:147(__enter__)
```

Linux
```
         3689632 function calls (3675013 primitive calls) in 14.670 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    52/49    0.000    0.000    0.001    0.000 <frozen importlib._bootstrap>:1017(_handle_fromlist)
        7    0.000    0.000    0.000    0.000 <frozen importlib._bootstrap>:103(release)
        7    0.000    0.000    0.000    0.000 <frozen importlib._bootstrap>:143(__init__)
        7    0.000    0.000    0.000    0.000 <frozen importlib._bootstrap>:147(__enter__)
        7    0.000    0.000    0.000    0.000 <frozen importlib._bootstrap>:151(__exit__)
```
