### ISSUE TITLE
Removing entity with certain pattern 

### ISSUE THREAD

**Issue by yw2903** [explosion/spaCy#6710]
EntityRuler could be added in the pipeline to look for entity with certain pattern. Is there a component I can add to remove entity with certain pattern? For example, after training my custom NER model, the model sometimes will predict "No.48" as DATE. I want to remove those predictions that follow the pattern "No.+". Thanks

**Comment by adrianeboyd** [comment]
No, there is no provided component. It would probably be easiest to the extend the `EntityRuler` class and just modify the `__call__` method to remove rather than add entities. Remember that to edit the entities in v2, you need to set all entities through `doc.ents` at once from a list, so you'll need to keep track of the original entities and only remove spans from that list in order to preserve the remaining entities. (In v3, it will be possible to set entities individually with the new `doc.set_ents()`.)

Alternatively, you can implement a custom component as described here that works however you like: https://spacy.io/usage/processing-pipelines#custom-components .
