### ISSUE TITLE
Sentencizer not recognizing newlines as sentence boundary when lines start or end with spaces

### ISSUE THREAD

**Issue by Buratinator** [explosion/spaCy#6728]
I'm having a hard time making the sentensizer recognize line breaks as sentence boundaries in multiline strings. It seems that it cannot handle cases where there are spaces at the end or start of the lines around the line break. Code to reproduce is below.

## How to reproduce the behaviour

My example: 

```
import spacy

nlp = spacy.load('en_core_web_sm', disable=['ner'])

sentencizer = nlp.create_pipe("sentencizer")
sentencizer.punct_chars.extend(['\n', '\$', '\r', '\r\n'])
nlp.add_pipe(sentencizer, before="parser")

input_string = '''"Table of Content  :  
 Study Coverage
 Executive Summary&#xA0;
 Breakdown Data by Manufacturers&#xA0; 
Breakdown Data by Type&#xA0;  
 Breakdown Data by Application&#xA0;
&#x2026;  
 Company Profiles&#xA0;  
 Future Forecast&#xA0;  
 Market Opportunities, Challenges, Risks and Influences Factors Analysis&#xA0;  
 Value Chain and Sales Channels Analysis&#xA0; 
Research Findings and Conclusion  
 Appendix&#xA0;  
Continued &#x2026;  
Global Fintech Block $Chain Market: $Key Pointers  

AAA \n BBB 
CCC\nDDD"'''

input_nlp = nlp(input_string)

for i,new_sentence in enumerate(input_nlp.sents):
  print(i, new_sentence.text)
```

The expected output would be 18 sentences, but the code above recognizes only 6:

```
0 "Table of Content  :  
 Study Coverage
 Executive Summary&#xA0;
 Breakdown Data by Manufacturers&#xA0; 

1 Breakdown Data by Type&#xA0;  
 Breakdown Data by Application&#xA0;
&#
2 x2026;  
 Company Profiles&#xA0;  
 Future Forecast&#xA0;  
 Market Opportunities, Challenges, Risks and Influences Factors Analysis&#xA0;  
 Value Chain and Sales Channels Analysis&#xA0; 

3 Research Findings and Conclusion  
 Appendix&#xA0;  
Continued &#x2026;  
Global Fintech Block $Chain Market: $Key Pointers  

AAA 
 BBB 

4 CCC

5 DDD"
```

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.7.4
* spaCy Version Used: 2.1.8
* Environment Information: Using VS Code and Anaconda 4.9.2

**Comment by adrianeboyd** [comment]
This is mostly likely related to how whitespace is tokenized. Except for the single space following a word, which is stored together with the word, consecutive whitespace characters are grouped together into larger whitespace tokens, and the sentencizer only checks whether `token.text` matches one of the punct chars exactly. (Punct chars is a misnomer. It doesn't have to be punctuation and it's really the token texts, not just chars.)

You'll want to compare each `token.text` for your doc to the punct chars to see whether they match exactly, and you can probably figure out why it isn't splitting like you expect. (The punct chars are regular strings, so `\$` is probably not what you want, either.)

You can 1) preprocess texts, 2) add a lot of possible whitespace combinations to the sentencizer (which is a pain / very verbose, but maybe doable for your task), or 3) write a custom sentence segmentation component that handles whitespace differently.

If you want to use the sentencizer without modifications, another option is to use the retokenizer to split up whitespace tokens into individual characters so they are easier to enumerate/match, or you could even write a custom tokenizer, although I wouldn't recommend that as a first choice, since the other options will be easier to implement.

**Comment by Buratinator** [comment]
Thanks. Perhaps the online documentation should be expanded a bit to reflect the information on how the sentencizer works, as it's helpful in building optimal pipelines.
