### ISSUE TITLE
Misleading error when getting empty span's `text` attribute

### ISSUE THREAD

**Issue by nj-vs-vh** [explosion/spaCy#6755]
Slicing empty span from Doc works without errors (e.g. `doc[:0]` or `doc[3:3]`), but attempt to use `text` attribute of a resulting empty span throws `IndexError: [E201] Span index out of range`. However, `text_with_ws`, attribute works fine, so it'll do as a workaround for my usage, but that seems like a very unintuitive behaviour.

## How to reproduce the behaviour
```python
import spacy

nlp = spacy.load('en')
doc = nlp('something')
print(doc[:0].text_with_ws)  # prints empty string, as expected
print(doc[:0].text)  # throws IndexError: [E201] Span index out of range
```

## Your Environment
* **spaCy version:** 2.3.5
* **Platform:** Linux-5.8.0-38-generic-x86_64-with-glibc2.29
* **Python version:** 3.8.5
* **Models:** en

**Comment by svlandeg** [comment]
Thanks for the report and minimal code snippet! Always appreciated :-)

This looks to be a small bug in the implementation of `span.text`: it tries to remove the last space of the last token before returning the result, but this gives an `IndexError` when the span is empty, because there is no last token. Should be fixed by PR #6772

**Comment by mzeidhassan** [comment]
@svlandeg Hi Sophie,
sorry to reopen this issue, but I think this issue on textacy is related, right?

https://github.com/chartbeat-labs/textacy/issues/314

**Comment by svlandeg** [comment]
Hi @mzeidhassan : Could be, yes, I'll leave a message on that thread to clarify.

**Comment by adrianeboyd** [comment]
I think it's probably due to the new span bounds checks, although I haven't looked at that code in the detail.

**Comment by svlandeg** [comment]
I doubt it Adriane? The span bounds check would throw an `E035` in the constructor, no?
I also haven't looked at the textacy code in detail, but the error occurs specifically when calling `span.text`.

**Comment by adrianeboyd** [comment]
I think it's both: the span bound check in `__getitem__` leads to `span.text` failing for a 0-length span when it didn't in earlier versions because you used to be able to access `span[-1]` even for 0-length spans (it would return the token before the span). That's the only thing that changed between v2.3.2 and v2.3.5, and the lack of the bounds check was masking the `.text` bug.
