### ISSUE TITLE
Wrong sentence separation (FR_core_news_*)

### ISSUE THREAD

**Issue by pVesian** [explosion/spaCy#6769]
## How to reproduce the behaviour
Not sure if this is a problem on my end or not since I'm just getting started with ML & spacy. It's also my first issue here so perhaps I got it all wrong.

It seems the fr_core_news models split sentences when they contain `[` or `«` or `’`.
I could theoretically replace all `[]` with `()`, however using `«` is a very common way to quote in french.
I also don't know what to do about `’` since it's used a lot by people using Microsoft Word or thinking it looks better than `'`.

Source of text: http://www.opex360.com/2020/08/03/deux-membres-de-la-dgse-mis-en-examen-pour-tentative-de-meurtre-en-dehors-de-leurs-fonctions/
Similar behaviour with http://www.opex360.com/2021/01/10/le-royaume-uni-litalie-et-la-suede-ont-signe-un-protocole-daccord-sur-le-developpement-du-tempest/
I haven't tested other articles

Result (excerpts):
```
C’est une affaire dont la Direction générale de la sécurité extérieure [DGSE] se serait bien passée.
Deux militaires de son Service action [SA], affectés au Centre parachutiste d’
entraînement spécialisé [
CPES] de Cercottes [
Loiret].
En effet, les deux hommes, âgés de 25 et 28 ans, ont été mis en examen et écroués pour « tentative d’homicide volontaire en bande organisée » ainsi que pour « recel en bande organisée de vol, transport, acquisition, détention d’armes de catégorie B » et « association de malfaiteurs en vue de la commission de ces crimes et délits punis de 10 ans d’emprisonnement.
» Un troisième homme a été arrêté trois jours plus tard.
Ils circulaient à bord d’un véhicule volé à Créteil [Val de Marne].
Les deux autres étant le Centre parachutiste d'instruction spécialisée [CPIS] de Perpignan et le Centre parachutiste d’entraînement aux opérations maritimes [
CPEOM] de Quélern.
```

The sentences aren't exactly the ones from the article so I rewrote them with very few differences for testing. The behavior is the same with the full article than with individual sentences.
Tested with sm, md and lg
Depending on the model different results occur but the pattern remains the same

**What's weird**:
* sentence break at `Centre parachutiste d’entraînement spécialisé` but not at `Centre parachutiste d’entraînement aux opérations maritimes` or ` à bord d’un véhicule`
* sentence break at `d’emprisonnement. » Un troisième` but not in other cases. This could in theory make sense since the quote ended after the dot, but still, blockquotes?
* sentence break at `Centre parachutiste d’entraînement aux opérations maritimes [CPEOM] de Quélern` and `Centre parachutiste d’entraînement spécialisé [CPES] de Cercottes [Loiret].` but not at `sécurité extérieure [DGSE] se` or `Service action [SA],`

Code:
```python
import spacy
docs = [
    "C’est une affaire dont la Direction générale de la sécurité extérieure [DGSE] se serait bien passée.",
    "Deux militaires de son Service action [SA], affectés au Centre parachutiste d’entraînement spécialisé [CPES] de Cercottes [Loiret].",
    "En effet, les deux hommes, âgés de 25 et 28 ans, ont été mis en examen et écroués pour « tentative d’homicide volontaire en bande organisée » ainsi que pour « recel en bande organisée de vol, transport, acquisition, détention d’armes de catégorie B » et « association de malfaiteurs en vue de la commission de ces crimes et délits punis de 10 ans d’emprisonnement. » Un troisième homme a été arrêté trois jours plus tard.",
    "Ils circulaient à bord d’un véhicule volé à Créteil [Val de Marne].",
    "Les deux autres étant le Centre parachutiste d’instruction spécialisée [CPIS] de Perpignan et le Centre parachutiste d’entraînement aux opérations maritimes [CPEOM] de Quélern."
]

nlp = spacy.load('fr_core_news_sm')
# nlp = spacy.load('fr_core_news_md')
# nlp = spacy.load('fr_core_news_lg')

for doc in docs:
    doc = nlp(doc)

    for sentence in doc.sents:
        print(sentence)
```

## Your Environment
* **spaCy version:** 2.3.5
* **fr_core_news_ version:** 2.3.0
* **Platform:** Windows-8.1-6.3.9600-SP0
* **Python version:** 3.8.7

Please let me know what I can do to help.

**Comment by adrianeboyd** [comment]
The French data comes from a single corpus (UD French Sequoia) with relatively normalized texts and some of these characters/tokens don't appear at all, so they're a bit like `UNK` tokens for the parser when it's trying to predict sentence boundaries.

One option is to normalize your texts so they look more like the training data, but this is often not practical/desired.

Instead of modifying the texts, another option is to tell the spacy model what the normalized forms are for tokens that don't appear in the training data, or for tokens like `[` that you want it to handle it differently. These normalized forms are used as features for all the built-in pipeline components. You can figure out which token (whole token text from the tokenizer, not individual character) is similar in the training data and add a `NORM` value.

Just adding a few norms fixes nearly all of the issues above:

```python
nlp.vocab["["].norm_ = '('
nlp.vocab["]"].norm_ = ')'
nlp.vocab["d’"].norm_ = "d'"
```

It's frequently a problem when our training data all comes from one source with one punctuation standard, or from texts that were written/processed before unicode was common. Some languages come with a normalization table that's always included in the models and for some of our corpora, we also generate orthographic variants for punctuation while training. These tables are stored in the [`spacy-lookups-data`](https://github.com/explosion/spacy-lookups-data) package. If you'd like to contribute a normalization table (as `fr_lexeme_norm.json`) or orthographic variant rules (as `fr_orth_variants.json`), that would be welcome! If you'd like, the easiest way is to make a PR to `spacy-lookups-data`.

English and German should have good examples for the format / options. The norm mapping is simple, just double-check that the tokenization lines up. The orth variants is a bit more complicated and some of the tag-specific options won't make sense because the French data doesn't have fine-grained tags. You can use the UD POS tag `PUNCT` (or whichever UD POS tag makes sense) in this `"tag"` value, though. It could also be used for `d’`, anything that correspond to a whole token.

I'd like to add character-based orthographic variants at some point, too, but it's kind of far down on my to-do list currently.

**Comment by pVesian** [comment]
Thanks @adrianeboyd, that snippet fixed it. I tried using `spacy-lookups-data` but I'm just not at that level yet. Sorry I can't help more.

**Comment by adrianeboyd** [comment]
No, `nlp.vocab["’"].norm_ = "'"` doesn't work for `d’` because the model looks up the norm for the token as a unit (based on the whole token text, not the individual characters). This is why you might want character-based orthographic variants instead of just the token-based ones we're using right now.

You might want both normalizations, though, if `’` also appears as a standalone token in your data.

```python
nlp.vocab["’"].norm_ = "'"
nlp.vocab["d’"].norm_ = "d'"
```
