### ISSUE TITLE
Example.from_dict throws `[E981] The offsets of the annotations for links could not be aligned to token boundaries.`

### ISSUE THREAD

**Issue by Joozty** [explosion/spaCy#6792]
## How to reproduce the behaviour

I am trying to train my EntityLinker component and when I try to create an example object I get an error `[E981] The offsets of the annotations for links could not be aligned to token boundaries.` I has clearly something to do with the doubled apostrophe character.

```python
import spacy
from spacy.training import Example

nlp = spacy.load("en_core_web_md")


# Doesn't throw any error
text = "''friend's text and link"
Example.from_dict(nlp(text), {"links": {
    (len(text) - 4, len(text)): {
        "1": 1.0
    }
}})

# Throws ValueError: [E981] The offsets of the annotations for `links` could not be aligned to token boundaries.
text = "''friend's text and'' link"
Example.from_dict(nlp(text), {"links": {
    (len(text) - 4, len(text)): {
        "1": 1.0
    }
}})
```

Note: Thi is a very simple example to demonstrate the error. I work with more complex text (Wikipedia dump) where I tried to strip all markup but there can sadly happen cases like this.

## Your Environment

* Operating System: Ubuntu 20.04.1
* Python Version Used: 3.8
* spaCy Version Used: spacy-nightly 3.0.0rc2

Thanks for helping me in this matter

**Comment by svlandeg** [comment]
Thanks for providing a minimal code snippet - that's always convenient :-)

I tested this on the recent `3.0.0rc3` + the `en_core_web_md` 3.0.0a1 model, and this snippet doesn't display the error on my end. I'm guessing the tokenization might be slightly changed in the new model.

There's two things in general though:
- When creating the gold data, you really do need to make sure that the entity links correspond to proper token boundaries. There is no way for spaCy to store the entities/links otherwise. You can specify the tokens with the `words=[...]` argument, more documentation here: https://nightly.spacy.io/api/data-formats#dict-input
- You can print the example objects you created to inspect whether the annotations were actually parsed correctly. In the code snippet that you provided, you'll see that in both cases, `'links': {}` which is obviously not what you want. This happens because you didn't specify the entities that you're linking: they should have the same start and end offset, and should get an NER label type.

For instance:
```
text = "''friend's text and'' link"
annots = {
        "entities": [(len(text) - 4, len(text), "THING")],
        "links": {(len(text) - 4, len(text)): {"1": 1.0}},
}
ex = Example.from_dict(nlp(text), annots)
print(ex)
```
Gives me:
```
{'doc_annotation': {'cats': {}, 'entities': ['O', 'O', 'O', 'O', 'O', 'O', 'U-THING'], 'links': {(22, 26): {'1': 1.0}}}, 'token_annotation': {'ORTH': ["''", 'friend', "'s", 'text', 'and', "''", 'link'], 'SPACY': [False, False, True, True, False, True, False], 'TAG': ['', '', '', '', '', '', ''], 'LEMMA': ['', '', '', '', '', '', ''], 'POS': ['', '', '', '', '', '', ''], 'MORPH': ['', '', '', '', '', '', ''], 'HEAD': [0, 1, 2, 3, 4, 5, 6], 'DEP': ['', '', '', '', '', '', ''], 'SENT_START': [1, 0, 0, 0, 0, 0, 0]}}

```
