### ISSUE TITLE
Text display issue when using dispaCy in manual mode.

### ISSUE THREAD

**Issue by sahil-malhotra** [explosion/spaCy#6798]
## How to reproduce the behaviour

On running this on a Jupyter Notebook:
```python
from spacy import displacy

ex = [{"text": "lorem ipsum $12 some entity $ 12 plus $15 lorem ipsum.",
       "ents": [{"start": 16, "end": 27, "label": "PRODUCT"}],
       "title": None}]
html = displacy.render(ex, style="ent", manual=True)
```
I get the following:

![image](https://user-images.githubusercontent.com/16478068/105607233-a9943380-5dc3-11eb-8725-652baf02d7c7.png)

The formatting gets broken after the occurrence of entity span, maybe because of some special characters like `$`

I did try the `jupyter=True` param, still getting the same formatting issues.

## My Environment

* **spaCy version:** 2.1.8
* **Platform:** Darwin-20.2.0-x86_64-i386-64bit
* **Python version:** 3.7.4

**Comment by polm** [comment]
This appears to be related to https://github.com/explosion/spaCy/pull/4840, which was integrated in 2.2.4, so you should be able to fix it by upgrading just a few versions. Your sample code works correctly for me with the latest v3.

The issue here is that by default Jupyter assumes any paired dollar signs indicate LaTeX math.

**Comment by sahil-malhotra** [comment]
Works well on the current version. Thanks!
