### ISSUE TITLE
Disabling pipeline parts has no effect in spacy 3?

### ISSUE THREAD

**Issue by poke1024** [explosion/spaCy#6831]
## How to reproduce the behaviour
In spacy 3.0.0rc5, disabling parts of a pipeline using `disable` (https://spacy.io/usage/processing-pipelines#disabling) seems to have no effect, whereas the same code works with spacy 2:

```
(spacy2) liebl@ch01:~> python
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> spacy.__version__
'2.3.5'
>>> nlp = spacy.load("de_core_news_lg")
>>> nlp("Hallo grausame Welt.", disable=["tagger", "parser", "ner"]).to_json()
{'text': 'Hallo grausame Welt.', 'tokens': [{'id': 0, 'start': 0, 'end': 5}, {'id': 1, 'start': 6, 'end': 14}, {'id': 2, 'start': 15, 'end': 19}, {'id': 3, 'start': 19, 'end': 20}]}
```

```
(spacy3) liebl@ch01:~> python
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> spacy.__version__
'3.0.0rc5'
>>> nlp = spacy.load("de_core_news_lg")
>>> nlp("Hallo grausame Welt.", disable=["tagger", "parser", "ner"]).to_json()
{'text': 'Hallo grausame Welt.', 'tokens': [{'id': 0, 'start': 0, 'end': 5, 'pos': 'NOUN', 'morph': 'Case=Nom|Gender=Neut|Number=Sing', 'lemma': 'Hallo'}, {'id': 1, 'start': 6, 'end': 14, 'pos': 'ADJ', 'morph': 'Case=Acc|Degree=Pos|Gender=Fem|Number=Sing', 'lemma': 'grausame'}, {'id': 2, 'start': 15, 'end': 19, 'pos': 'NOUN', 'morph': 'Case=Acc|Gender=Fem|Number=Sing', 'lemma': 'Welt'}, {'id': 3, 'start': 19, 'end': 20, 'pos': 'PUNCT', 'morph': '', 'lemma': '.'}]}
```

### spacy 3
spaCy version    3.0.0rc5                      
Location         /u/liebl/miniconda3/envs/spacy3/lib/python3.7/site-packages/spacy
Platform         Linux-5.3.18-lp152.60-default-x86_64-with-glibc2.10
Python version   3.7.9                         
Pipelines        de_core_news_lg (3.0.0a1), de_dep_news_trf (3.0.0a1)

### spacy 2
spaCy version    2.3.5                         
Location         /u/liebl/miniconda3/envs/spacy2/lib/python3.7/site-packages/spacy
Platform         Linux-5.3.18-lp152.60-default-x86_64-with-glibc2.10
Python version   3.7.9                         
Models

**Comment by adrianeboyd** [comment]
This isn't a bug, it's just that the components are extended a bit in v3. Check `nlp.pipe_names` to see which components are currently in the pipeline:

```python
nlp = spacy.load("de_core_news_sm")
print(nlp.pipe_names) # ['tok2vec', 'tagger', 'morphologizer', 'parser', 'ner', 'attribute_ruler', 'lemmatizer']
```

In v2 the components were all independent, but this isn't the case in v3, so it's useful to understand how things are related:

* `tagger`, `morphologizer`, and `parser` depend on `tok2vec`
* `ner` is independent
* the German lookup `lemmatizer` will work without any earlier components, but for some other languages the rule-based or POS-lookup-based lemmatizers only makes sense after the `tagger` or `morphologizer`
* `attribute_ruler` maps tag to pos for some languages (although not German, since it uses the `morphologizer` for `pos` instead), but it also enforces the custom `SPACE` tag/pos on whitespace tokens

You can add arbitrary token-level exceptions to the `attribute_ruler`, but in the provided v3 pipelines it's mainly used to handle exceptions/mappings for the `tagger` and the `morphologizer`.

**Comment by poke1024** [comment]
@adrianeboyd Thank you!

I'm closing this.
