### ISSUE TITLE
Unicode apostrophe confuses tokenizer

### ISSUE THREAD

**Issue by pokey** [explosion/spaCy#685]
When the tokenizer sees the [unicode apostrophe](http://www.fileformat.info/info/unicode/char/2019/index.htm), it doesn't tokenize correctly.  For example:

```
import spacy

nlp = spacy.load('en', parser=False)

print(list(nlp.tokenizer("I'm hungry")))
print(list(nlp.tokenizer("I\u2019m hungry")))
```

outputs

```
[I, 'm, hungry]
[I’m, hungry]
```

## My Environment
* OS X 10.11.6
* Python 3.5.2
* spacy 1.2.0

**Comment by ines** [comment]
Thanks, good catch! This should probably be added to the tokenizer exceptions.

I'm currently in the process of reorganising the language data and we're gonna merge the changes pretty soon, so there's little point in fixing this in the old, messy format now. I'll do it it on the new [organize-language-data](https://github.com/explosion/spaCy/tree/organize-language-data/spacy) branch instead so it will definitely be fixed in the next release.
