### ISSUE TITLE
spaCy Sentence Splitting goes wrong

### ISSUE THREAD

**Issue by ChrisChross** [explosion/spaCy#6863]
## How to reproduce the behaviour
I think there is problem with the spaCy sentence splitter. 

```
text = "The Drop – Bargeld ist ein US-amerikanisches Kriminalfilm-Drama des belgischen Regisseurs Michaël R. Roskam aus dem Jahr 2014. Das Drehbuch stammt von Autor Dennis Lehane, der dazu seine eigene Kurzgeschichte Animal Rescue verarbeitete."
nlp =  spacy.load('de_core_news_lg')
doc = nlp(text)
[sent for sent in doc.sents]
Out[1]: 
[The Drop – Bargeld ist ein US-amerikanisches Kriminalfilm-Drama des belgischen Regisseurs Michaël R. Roskam aus dem Jahr,
 2014. Das Drehbuch stammt von Autor Dennis Lehane, der dazu seine eigene Kurzgeschichte Animal Rescue verarbeitete.]
```
EDIT: It seem in general, if a sentence ends with a number, it is not separated correctly. 

## Your Environment

* Operating System: macOS
* Python Version Used: 3.8.5
* spaCy Version Used: 2.3.5
* spaCy model Version Used: 2.3.0

**Comment by adrianeboyd** [comment]
Hi, the sentence segmentation is done by default by the statistical parser, which will not be 100% accurate. In this case the tokenization is probably the source of the problem, since it tokenizes `2014.` as one token, so the parser doesn't see a separate `.` that it might otherwise predict as the end of a sentence. With the rule-based tokenizer it's hard to distinguish `2014 . ` at the end of a sentence from an ordinal number like `3.` in `3. Januar`.

You can modify the tokenizer settings if you'd like to see if it helps for your task, but be aware that other cases like `3. Januar` might not be analyzed correctly since the tagger and parser weren't trained on this tokenization. Look at the tokenizer's suffix regexes: https://spacy.io/usage/linguistic-features#native-tokenizer-additions
