### ISSUE TITLE
Github example links on training page are mostly reporting a 404 error

### ISSUE THREAD

**Issue by ijdickinson** [explosion/spaCy#6866]
I'm looking at the `Training spaCy's statistical models` page. Most of the example code blocks are reporting an error instead of showing the code. Clicking on the suggested GitHub links returns a 404 error.

Example screenshot:

![image](https://user-images.githubusercontent.com/63979/106389520-8842d100-63db-11eb-85f2-91deec327857.png)

## Which page or section is this issue related to?
https://spacy.io/usage/training#entity-linker

**Comment by honnibal** [comment]
Ah, thanks for pointing this out.

This is a transitonal problem, while we prepare the v3 release. The links on the site point over to the master branch of the repo, which now has the v3 code. We'll be publishing v3 (and updating the website) in about 12 hours. 

In the meantime, you can find the examples on the v2.x branch of the repo. We'll also get the links fixed so that they display correctly.

**Comment by ines** [comment]
Just updated the website – sorry about that! The examples and links should now correctly point to the `v2.x` branch (you might have to do a hard refresh for it to update).

**Comment by ijdickinson** [comment]
Confirm fixed. Thank you!
