### ISSUE TITLE
matcher.add() type error

### ISSUE THREAD

**Issue by the1gofer** [explosion/spaCy#6901]
It seems to be failing on the matcher.add line, and from what I can tell through your documentation, this should be fine.

## How to reproduce the behaviour
```
        matcher = Matcher(Parser.nlp.vocab)
        Matcher.add("CityState", pattern)
        matches = matcher(self.doc)
```
TypeError: descriptor 'add' requires a 'spacy.matcher.matcher.Matcher' object but received a 'str'

## Your Environment
- **spaCy version:** 3.0.1
- **Platform:** Darwin-19.6.0-x86_64-i386-64bit
- **Python version:** 3.7.6
- **Pipelines:** en_core_web_trf (3.0.0)* 
- Operating System: mac o 10.15.7

**Comment by adrianeboyd** [comment]
Hi, you want `matcher.add` instead of trying to call this as a class method. This is a good type of question for our new discussions board, so I'll transfer it there in a minute. You'll get an automatic message that it's been locked, but everything will be copied over and the discussion can continue in the thread there.

I can't find an example with this mistake in the docs, but if you do find a non-working example or other mistake, it's fine to submit that as a bug report in the issue tracker, which we're trying to keep focused on bug reports.
