### ISSUE TITLE
Wrong boundaries for sentences with inverted excalamation and question marks

### ISSUE THREAD

**Issue by 0x2b3bfa0** [explosion/spaCy#6919]
The sentencizer considers inverted interrogation and exclamation marks like part of the previous sentence, and, depending on the model, as a whole sentence on their own.

## How to reproduce the behaviour
```python
>>> import spacy
>>> parser = spacy.load("xx_ent_wiki_sm")
>>> parser.add_pipe(spacy.pipeline.Sentencizer())
>>> print(list(parser("¡Hola! ¿Qué tal?").sents))
["¡Hola! ¿", "Qué tal?"]
```

The correct output would be `["¡Hola!", "¿Qué tal?"]`; please note the inverted question mark moved to the correct sentence.

## Environment
* **spaCy version:** 2.3.5
* **Platform:** macOS-10.15.7-x86_64-i386-64bit
* **Python version:** 3.9.1

_Nota bene: this issue has only been tested against the `xx_ent_wiki_sm` and `es_core_news_sm` models._

**Comment by adrianeboyd** [comment]
The `sentencizer` algorithm is pretty simple rule-based algorithm. It finds sentence-final tokens and then sets the next non-punctuation token as the start of the next sentence. This is to handle cases like `"A sentence."` where the sentence-final punctuation is the period rather than the quote, but we want the quote to be part of the previous sentence. This isn't the right behavior for the Spanish inverted sentence-initial punctuation.

You could potentially try changing `token.is_punct` to `token.is_right_punct` here, but I'm worried this could have unwanted side effects for a lot of languages that don't use inverted punctuation, since `is_right_punct` might not cover enough cases by default:

https://github.com/explosion/spaCy/blob/c70e6ee72da59fac588b530cd5ad1295ea880b17/spacy/pipeline/pipes.pyx#L1577

The `sentencizer` results depend on the tokenization and the language defaults (e.g., `English()` vs. `Spanish()`), but not on the other components in the model.

The `Sentencizer` is a plain python class (no cython, despite the fact that it's in `pipes.pyx`), so it would be easy to copy and modify it as a custom pipeline component with your changes, too.

**Comment by 0x2b3bfa0** [comment]
For the record, the best solution for my specific multi-language use case was using the new [`SentenceRecognizer`][1] with the [`xx_sent_ud_sm`][2] senter model.

[1]: https://spacy.io/api/sentencerecognizer
[2]: https://spacy.io/models/xx#xx_sent_ud_sm

**Comment by 0x2b3bfa0** [comment]
> _You could potentially try changing token.is_punct to token.is_right_punct here, but I'm worried this could have unwanted side effects for a lot of languages that don't use inverted punctuation, since is_right_punct might not cover enough cases by default._

I see another potentially elegant solution to this issue in case #6917 gets merged:

```python
    if seen_period and not (token.is_punct and not token.is_left_punct) and not is_in_punct_chars: 
```

**Comment by adrianeboyd** [comment]
That is the kind of thing `xx_sent_ud_sm` should be useful for.

I'm not sure `(token.is_left_punct or not token.is_punct)` would work because tokens like `"` are in both left and right punct.

**Comment by 0x2b3bfa0** [comment]
What would be the implications of the `"` quote ubiquity? I think that even closed quotes aren't enough to terminate a sentence, but I could be wrong.

**Comment by polm** [comment]
Sorry for the late reply.

I think the issue with the quote is that it wouldn't behave as expected in your conditional, which could change its behavior and have it work more like an inverted exclamation mark. 

Since we've outlined a workaround for this, even if it's not very elegant, I'm going to go ahead and mark this resolved. 

Note that since this was posted, we've moved questions like this to discussions, to keep bug reports separate and more visible. If you or anyone else has more thoughts on this it might be better to open a Discussion than posting here.
