### ISSUE TITLE
IS_SENT_END does not exist

### ISSUE THREAD

**Issue by snthibaud** [explosion/spaCy#6986]
I noticed the specifier `IS_SENT_START` on the below page, but apparently there is no `IS_SENT_END`. Is there a reason for this? Is there another way to match a sentence end?

## Which page or section is this issue related to?
https://spacy.io/usage/rule-based-matching

**Comment by adrianeboyd** [comment]
No, there's no `IS_SENT_END` for the Matcher because the built-in Matcher attributes refer to the underlying cython data, not the python objects. We don't want to store duplicate information in the underlying `TokenC` struct: https://spacy.io/api/cython-structs#tokenc. The built-in Matcher attributes are the ones stored in `TokenC` and `LexemeC`, not all properties available for the python `Token` class.

See the expandable box "Why are not all token attributes supported?": https://spacy.io/usage/rule-based-matching

If you'd like to use it, you can match `IS_SENT_START` on the following token or use a custom token extensions like `token._.is_sent_end` with `{"_": ...}` pattern for this feature. Note that a custom token extension will be slower than matching on `IS_SENT_START`.

**Comment by snthibaud** [comment]
@adrianeboyd Thank you for your answer!
> {"_": ...}

So what would the pattern look like exactly? Should it use a regex with `$`?

**Comment by adrianeboyd** [comment]
The patterns depend on the type of the custom extension, so something like `{"_": {"is_sent_end": True}}` for a boolean value.

There's no way for us to validate this in the pattern validation, so you have be sure your patterns make sense for the values it's going to try to compare or you can see unexpected behavior/errors.
