### ISSUE TITLE
Modifying spans annotation before training 

### ISSUE THREAD

**Issue by yw2903** [explosion/spaCy#6993]
By using prodigy I am able to create a training set, however, I would like to clean the annotated entities before training with spacy (for example, removing special character at the end). However, I get error that says "span object is not modifiable
". How can I go around with that?

**Comment by svlandeg** [comment]
Hi!

This type of usage question is probably better suited for the new discussion forum, so I'll move it there. Don't worry if you get an email saying that this issue is closed/locked - it really is just transferred to the Discussions and will remain an open thread there.

To answer your question, I think the easiest way for you to get around this, is to query the original `doc.ents`, loop through them to clean them, and create a new (similar) set of entities that you can set afterwards with `doc.set_ents`.
