### ISSUE TITLE
PhraseMatcher inconsistent matches with attr='LOWER'

### ISSUE THREAD

**Issue by psychonaute** [explosion/spaCy#6994]
## How to reproduce the behaviour

When I'm running the PhraseMatcher against dotted text and with attr='LOWER', weirdly some lowercase/uppercase combinaison doesn't work. 

If I  remove it or replace '.' with '!' the inconsistency disappears

**Step to reproduce:**
```python
import spacy
from spacy.matcher import PhraseMatcher #import PhraseMatcher class

nlp = spacy.load('en_core_web_sm')
matcher = PhraseMatcher(nlp.vocab, attr='LOWER')
matcher.add("Phrase Matching", None, *[nlp.make_doc("abcd")])

test_list = [
    "test ABCD. case",
    "test aBCD. case",
    "test abcd. case",
    "test abCD. case",
    "test abcD. case",
    "test aBcD. case",
    "test AbcD. case",
    "test abcD! case",
    "test aBcD! case",
    "test AbcD! case",
]

docs = list(nlp.pipe(test_list))
for doc in docs:
    matches = matcher(doc)
    if matches:
        print(doc.text, "-> Match")
    else:
        print(doc.text,"-> Don't match")
```

**Result in:**

```
test ABCD. case -> Match
test aBCD. case -> Match
test abcd. case -> Match
test abCD. case -> Match
test abcD. case -> Don't match
test aBcD. case -> Don't match
test AbcD. case -> Don't match
test abcD! case -> Match
test aBcD! case -> Match
test AbcD! case -> Match
```

## Info about spaCy
* **spaCy version:** 2.3.5
* **Platform:** Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.28
* **Python version:** 3.9.1

**Comment by adrianeboyd** [comment]
This is a tricky case related to how the tokenizer tries to detect whether a period is part of an abbreviation or not. You can check the tokenization for each of your test texts and see that sometimes you get `["abcd", "."]` and sometimes you get `["abcD."]`. If it's one token, the pattern token `abcd` won't match.

The tokenizer suffix pattern is sensitive to whether the letters before the period are capitalized, so you can have a middle initial like `A.` as one token but split the period off at then of a sentence. It's just a heuristic that works fairly well for our training data and there's no way for the pattern to be perfect with the built-in tokenizer implementation. You can probably improve this for your task by modifying the suffix patterns so that the periods are all split off as suffixes? See: https://spacy.io/usage/linguistic-features#native-tokenizer-additions

Be aware that there may be some minor side effects (especially for the parser) because the modified tokenization is different from the training data and you might get slightly different parses or sentence boundaries.

**Comment by psychonaute** [comment]
I see, that make sense now. Thanks for your details answer and to all the team for their work. 👍 Closing it
