### ISSUE TITLE
Getting Doc, Token and Span vectors with transformer model

### ISSUE THREAD

**Issue by ogabrielluiz** [explosion/spaCy#7008]
Hi! 
In spacy 3.0 we can access the tensors through `doc._.trf_data.tensors`. The documentation states that we can get the doc hidden state by accessing the "last tensor that is 3-dimensional".

My question is how do we get a span tensor or a token tensor? 
for a doc with length 3 doc._.trf_data.tensors[-2] gives me a (3,1,768) shaped tensor, IIRC, possibly, a tensor for each token or wordpiece. Now if I want a span tensor do I just average the tensors of its tokens? 

## Your Environment

- Operating System: Windows 10
- Python Version Used: Python 3.8.2
- spaCy Version Used: 3.0+
- Environment Information:

**Comment by adrianeboyd** [comment]
We have left this part up to the user in v3, since different tasks may have different needs. You can see how this was set with user hooks for vectors and similarity in v0.6.x, where it summed the tensors for spans (which may not be what you want):

https://github.com/explosion/spacy-transformers/blob/ebef817af5c0077e8f7019b77d6768da1fd482eb/spacy_transformers/pipeline/tok2vec.py#L193-L207
