### ISSUE TITLE
Cases not taken into account in method spacy.lang.en.syntax_iterators.noun_chunks?

### ISSUE THREAD

**Issue by jonabaa** [explosion/spaCy#7113]
## How to reproduce the behaviour

```
import spacy
from spacy import displacy

nlp = spacy.load("en_core_web_lg")

text = 'We applied value added taxes ("VAT").'
doc = nlp(text)

for chunk in doc.noun_chunks:
    print(chunk.text)

file_name = "./dependencies.html"
options = {"compact": True, "collapse_punct": False, "jupyter": False}
html = displacy.render(doc, style="dep", options=options)
with open(file_name, "w") as file:
    file.write(html)
```
gives the following output:
```
We
value added taxes
"VAT
```
and the following .html-file:
![image](https://user-images.githubusercontent.com/42806356/108340508-f14a8700-71d8-11eb-8cf6-42100ec59ced.png)

## Problem description

I assume the way we want to merge noun chunks is either to leave out the quotation marks or include them both.
If we look at the dependency tree of the word VAT, it seems like this would encourage such a behavior. 
This leads me to think that there are some cases not taken into account in the method spacy.lang.en.syntax_iterators.noun_chunks?

## Environment

* **spaCy version:** 2.3.2
* **Platform:** Linux-5.4.0-62-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.6.12

**Comment by adrianeboyd** [comment]
The current English noun chunks iterator assumes that the head noun is at the right edge of the noun chunk, so it only looks to the left when extending the chunk, which is why you get the opening quote and not the closing quote.

You can customize it in v2.3.x by modifying the noun chunks iterator function within the language defaults, e.g. for `English` it would be `English.Defaults.syntax_iterators["noun_chunks"]`. In v3, you'd modify `nlp.vocab.get_noun_chunks` instead after loading a pipeline.

These changes aren't saved with `nlp.to_disk()` (we can't safely serialize a function), so you would need to modify it each time for that language (v2) or loaded model (v3) in your script.
