### ISSUE TITLE
Enhancement: Allow for multiple loggers

### ISSUE THREAD

**Issue by KennethEnevoldsen** [explosion/spaCy#7187]
Currently, it does not seem possible to use multiple loggers using the config:
```
[training.logger]
@loggers = ["spacy.ConsoleLogger.v1", "spacy.WandbLogger.v1"]
```

Which gives the following error:
```
[...]
  File "/home/kenneth/.Envs/spacy_train/lib/python3.6/site-packages/spacy/util.py", line 150, in has
    if func_name.startswith("spacy."):
AttributeError: 'list' object has no attribute 'startswith'
```

## Your Environment

- **spaCy version:** 3.0.3
- **Platform:** Linux-4.15.0-130-generic-x86_64-with-Ubuntu-18.04-bionic
- **Python version:** 3.6.9

**Comment by svlandeg** [comment]
That's right, the config currently expects exactly one logger. That said, the `WandbLogger` actually [uses](https://github.com/explosion/spaCy/blob/master/spacy/training/loggers.py#L108) the `ConsoleLogger` internally, so that's definitely a feasible workaround if you want to combine multiple logging facilities. And to combine the `WandbLogger` with the `ConsoleLogger`, you don't have to do anything, it's built in ;-)

**Comment by KennethEnevoldsen** [comment]
Thanks that was indeed the intention.
