### ISSUE TITLE
spaCy `conj` link to parent object

### ISSUE THREAD

**Issue by kootenpv** [explosion/spaCy#724]
Feature request: I would like to have a link to a parent object for the dep_ tag `conj`. I'm not even sure if there is a logical way to do it, but I'm hoping that @honnibal has an idea about this.

Example:

```
Input: I want a cat and a dog

 want	(VERB,	ROOT)
---- I	(PRON,	nsubj)
---- cat	(NOUN,	dobj)
-------- a	(DET,	det)
-------- and	(CONJ,	cc)
-------- dog	(NOUN,	conj)
------------ a	(DET,	det)

```

In this case, I'd like "dog" to also be treated as "the object". What is the best way to go about this?

Another example:

```
Input: Dogs and cats are animals I like

 are	(VERB,	ROOT)
---- Dogs	(NOUN,	nsubj)
-------- and	(CONJ,	cc)
-------- cats	(NOUN,	conj)
---- animals	(NOUN,	attr)
-------- like	(VERB,	relcl)
------------ I	(PRON,	nsubj)
```

Perhaps a very naive search would be for me to search upwards to a object or subject, but since you are already marking a tag as `conj`, I'm pretty sure you have an idea what the originating object is? 
And do you know if it always has to be an object/subject, or is there another dep type you can come up with? My apologies for the long story.

**Comment by adam-ra** [comment]
Spacy is trained on a corpus with CLEAR-style coordination chains (look for coordinations in http://www.mathcs.emory.edu/~choi/doc/clear-dependency-2012.pdf).
In spaCy output, the first (left-most) conjunct is attached directly to its head, while the subsequent conjuncts are attached to the previous conjunct as dependency.  Also, commas may play the role of coordinating conjuncts.
What you want is called “conjunct propagation”. It may be implemented as relatively simple graph operations as long as you're willing to abandon native Spacy structure for graph representations. I've implemented this using networkx graphs and would recommend this unless you really need the Spacy data structures (anyway then you're lost because the original data structures are Cython objects, immutable).

The caveat is that you cannot transform top-level coordinations this way (if the parsed phrase has no main verb but the coordinating conjunct is on top — for instance, “cats and dogs”).

**Comment by honnibal** [comment]
See `token.conjuncts` :)
