### ISSUE TITLE
Note on frozen components

### ISSUE THREAD

**Issue by fcggamou** [explosion/spaCy#7270]
Hi, this is a very minor question, but this block of text in the documentation sparked some doubts:

> "NOTE ON FROZEN COMPONENTS
> Even though frozen components are not updated during training, they will still run during training and evaluation. This is very important, because they may still impact your model’s performance – **for instance, a sentence boundary detector can impact what the parser or entity recognizer considers a valid parse**. So the evaluation results should always reflect what your pipeline will produce at runtime."

Can you clarify the bolded text? I'm using NER models; should I add a sentence boundary detector to my pipelines? If I do, how can I make the NER use it? 

Thanks!

**Comment by polm** [comment]
For reference, [here](https://spacy.io/usage/training#config-components:~:text=NOTE%20ON%20FROZEN%20COMPONENTS)'s a link to the note.

The note is not a recommendation that you use a particular component, it's just a note that even though frozen components don't learn themselves, they can modify the input (and thus the performance) of components that come after them in the pipeline. A sentence boundary detector can modify the parser or entity recognizer because parses won't cross sentence boundaries - an adjective can't modify a noun in another sentence. 

The takeaway from this is that your frozen components should be **consistent** between training and inference, not that you should use a particular component.

> I'm using NER models; should I add a sentence boundary detector to my pipelines? If I do, how can I make the NER use it?

By default spaCy models include sentence tokenization so you don't have to do anything. If you want to customize it look at the [Sentencizer](https://spacy.io/api/sentencizer) (rule-based) or [SentenceRecognizer](https://spacy.io/api/sentencerecognizer) (statistical, trainable) components.

**Comment by fcggamou** [comment]
Thanks for your answer. 

This is more of an advice kind of question, inspired by that note: when training a new NER model, is it recommended to use a sentence recognizer first? I.e. should my training examples be per sentence, instead as per text document?

Thanks!

**Comment by polm** [comment]
Since this is more of a usage question, I'm going to move it to a Discussion - this issue will be locked but you can follow the link to the forum.
