### ISSUE TITLE
Construct a Doc object from dataset with sent_starts  and deps/heads

### ISSUE THREAD

**Issue by d5555** [explosion/spaCy#7415]
I'm trying to constructing  a `Doc` object from dataset with  `words`, `spaces`, `sent_starts`, `deps` and `heads`. 
`doc = Doc(nlp.vocab, words=words, sent_starts= sent_starts, spaces=spaces, heads=heads, deps = deps)`
After assigning heads/deps,  Doc object  changes sent_starts and I cannot reassign sent_starts , otherwise I get error/warning that Doc was already parsed. 
How can I reassign sent_starts after Doc was parsed? 

I think we should give priority to `sent_starts` if it is provided when creating Doc object or set `sent_starts`  to `None` when we want to prioritize parser

## Your Environment
- Operating System: windows
- Python Version Used: 3.6
- spaCy Version Used: 3.0.3

**Comment by adrianeboyd** [comment]
The short answer is that you can't with `Doc.__init__` and in general. you probably shouldn't, or you should be prepared for some of the doc properties and attributes to break, since they assume that sentence boundaries align with parse boundaries. I think if you try hard you might be able to get them out of sync, but we try fairly hard to prevent you from doing this.

What's the use case where you have sent starts that don't align with parse boundaries?

Or are you concerned that sentence boundaries are missing if you just have heads and deps? When you set heads and deps, sent starts are automatically assigned based on the parse trees.

**Comment by d5555** [comment]
I just need to recreate doc object according to my dataset to further work with the doc.
Maybe to train NER or CATS when I already have tags and deps included into Doc.  
 I can't do it because parser changes sentence boundaries and the doc doesn't correspond  dataset anymore.

**Comment by adrianeboyd** [comment]
Hmm, can you give a concrete example of what your data looks like and how you're loading it? I'm a bit confused from your description of having heads+deps from the dataset vs. the parser adding sentence boundaries?

**Comment by adrianeboyd** [comment]
And let me convert this to a discussion thread. This issue will get locked, but the new discussion thread will be open.
