### ISSUE TITLE
ValueError: [E030] Sentence boundaries unset.  when train my own entity linker

### ISSUE THREAD

**Issue by gaohuan2015** [explosion/spaCy#7459]
Hi, I am using spacy 3.0.3 to train my own entity linking model. I am getting an error when the model need to update parameters  ( **nlp.update(batch)**) ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: `nlp.add_pipe('sentencizer')`. Alternatively, add the dependency parser or sentence recognizer, or set sentence boundaries by setting `doc[i].is_sent_start`.  But I have already added sentencizer in pipeline, but this doesn't work. 

Here is my code:
 ```python
import spacy
import random
from spacy.vocab import Vocab
from spacy.kb import KnowledgeBase
from spacy.pipeline import EntityRuler
from spacy.util import minibatch, compounding
from spacy.pipeline.entity_linker import DEFAULT_NEL_MODEL
from spacy.training import Example

spacy.require_gpu()
nlp = spacy.blank("en")
nlp.add_pipe('parser')
ruler = nlp.add_pipe("entity_ruler")
pattern = [{"label": "PERSON", "pattern": [
    {"LOWER": "michael"}, {"LOWER": "jordan"}]}]
ruler.add_patterns(pattern)

def sample_train_data():
    train_data = []
    text_1 = "Michael Jordan plays basketball"
    dict_1 = {
        "entities": [(0, 14, "Person")],
        "links": {(0, 14): {"Q7381115": 1.0}}
    }
    train_data.append((text_1, dict_1))

    return train_data

def create_kb(vocab):
    vocab2 = Vocab().from_disk("KB/vocab")
    kb = KnowledgeBase(vocab=vocab2, entity_vector_length=300)
    kb.from_disk("KB")
    print(f"Entities in the KB: {kb.get_entity_strings()}")
    print(f"Aliases in the KB: {kb.get_alias_strings()}")
    return kb

examples = []
for text, annots in sample_train_data():
    doc = nlp.make_doc(text)
    examples.append(Example.from_dict(doc, annots))
if "entity_linker" not in nlp.pipe_names:
    entity_linker = nlp.add_pipe("entity_linker", last=True)
    entity_linker.set_kb(create_kb)
    

losses = {}
optimizer = nlp.initialize()
for i in range(20):
    random.shuffle(examples)
    for batch in minibatch(examples, size=8):
        loss = nlp.update(batch)
        print(loss)

**Comment by polm** [comment]
I think this is possibly the same as #7288, so that may help you. 

Also, you say you've added a sentencizer but I don't see it in the code here?

**Comment by adrianeboyd** [comment]
Yes, this is the same issue.

The problem is that your `Example` objects only contain tokenization and no other annotation in the predicted doc (`example.predicted`), so when it's updating the model, it doesn't see any sentence boundaries when it runs its prediction step. You want to replace `nlp.make_doc` with `nlp` to run the whole pipeline (including the component that sets sentence boundaries) and then also set the entities on the predicted doc:

```python

nlp = spacy.blank("en")
nlp.add_pipe("sentencizer")

...

for text, annots in sample_train_data():
    doc = nlp(text)
    examples.append(Example.from_dict(doc, annots))
    # add gold entities to predicted doc
    example.predicted.ents = example.reference.ents
```

For this example, it would be simpler to `sentencizer` instead of a new `parser`, which would need to be trained before it can provide useful sentence boundaries and then frozen while training the entity linker. You could use components from an `en_core_web_*` (`senter` or `parser` for sentence boundaries, `ner` for automatic entities), but you need source and freeze the components correctly in the config, which is more complicated than using `sentencizer`.

If you're training from a config (which we'd recommend over this kind of script once you move beyond toy data), you need to use a custom corpus reader that adds the sentences and entities to the predicted docs. See an example in the [`nel_emerson`](https://github.com/explosion/projects/tree/v3/tutorials/nel_emerson) project here:

https://github.com/explosion/projects/blob/4fa445a165de30c7e7877e17dc7fe8bea12b8198/tutorials/nel_emerson/scripts/custom_functions.py

We hope to make this easier in v3.1, so you can just set up a component like `parser` or `ner` in your pipeline and choose whether it should be applied to the predicted docs during training without these extra steps.

**Comment by gaohuan2015** [comment]
Thanks very much for your help. The problem is resolved.
