### ISSUE TITLE
Processing Pipelines - User Hooks Clarifications

### ISSUE THREAD

**Issue by pmbaumgartner** [explosion/spaCy#7469]
I was reading through the [User Hooks](https://spacy.io/usage/processing-pipelines#custom-components-user-hooks) section of the pipeline docs and it wasn't clear to me where this `SimilarityModel` should go in the code. Since it's between two examples of using `@Language.factory`I thought I needed to add a named component, but that's not right because I get an error about the initialization signature and it looks like this takes `model` and not `nlp`. When/how do these hooks get registered in the pipeline?

Additionally, the example mentions you can update `similarity`,  but that doesn't show up in the table in the `user_hooks` row.

Finally, I'm not exactly clear how one would update `vector` since it's a property and not a method like `similarity`. I gave a crack at what I thought this might look like below, but can't test out anything until I get the prior questions answered.

```python
class SimilarityModel:
    def __init__(self, model):
        self._model = model

    def __call__(self, doc):
        doc.user_hooks["similarity"] = self.vector

    @property
    def vector(self, obj1):
        return [0, 1, 2, 3, 4]  # example vector
```

## Which page or section is this issue related to?
[User Hooks](https://spacy.io/usage/processing-pipelines#custom-components-user-hooks)

**Comment by adrianeboyd** [comment]
You can override token vector lookup with a user hook for use with similarity methods. Note that this doesn't override the vector for the feature extraction in the built-in statistical models. Those models access the underlying vector table directly. (You could do it with a custom `tok2vec`, but speed would be a concern.)

The user hooks are one of the few things that haven't been turned into registered functions and as such can't be saved with the doc. We considered it for v3, but decided it was too breaking and not a priority because it's used relatively rarely. So they're not registered, they're just plain `Callable` objects.

`Doc.similarity` is implemented, just missing from the table in the docs. Because you're comparing two docs, you'd want your similarity hook to take two args (doc1 and doc2). A toy example would look like this:

```python
import spacy
from spacy.language import Language
import numpy as np


class SimilarityModel:
    def __init__(self, name):
        self.name = name
        pass

    def __call__(self, doc):
        doc.user_hooks["similarity"] = self.similarity
        return doc

    def similarity(self, doc1, doc2):
        return np.dot(doc1.vector, doc2.vector)


@Language.factory("similarity_component")
def create_similarity_component(nlp, name):
    return SimilarityModel(name)


nlp = spacy.load("en_core_web_md")
nlp.add_pipe("similarity_component")
print(nlp("cat").similarity(nlp("dog")))
```

You put `similarity_component` in your pipeline so that it adds the user hook, and then if you call `doc1.similarity(doc2)`, it should call the similarity method in the user hook instead of the default one. If you want `doc1.vector` to do something different than the default, then you need to add separate user hook for vectors, either in this component or elsewhere, or you can completely override `similarity` to do whatever it wants with the data in the doc, for instance if your similarity component has its own internal vector table to use instead. The `SimilarityModel.similarity` method has access to the entire doc and all its annotations.
