### ISSUE TITLE
Wrong links in the GET STARTED section of the docs

### ISSUE THREAD

**Issue by bartosik-hep** [explosion/spaCy#748]
All links in the **GET STARTED** section of the [usage docs](https://spacy.io/docs/usage/adding-languages) point to the project's main page.

**Comment by ines** [comment]
Hmm, I'm not sure I understand this correctly – could you give an example?

**Comment by bitraten** [comment]
There are similar issues on https://spacy.io/docs/,
the links in the top section of the menu (SPACY) all point to the main page.

**Comment by ines** [comment]
Wow, this is weird. I think what's happening here is that for some reason, Safari doesn't interpret the height of the logo correctly, and since it's fixed positioned, its container (including the link) overlaps part of the site.

Turns out I set the logo sizing in a messy way, so fixing this did the trick. Will be pushing an update in a second. Thanks for the report!
