### ISSUE TITLE
POS different in nlp.pipe

### ISSUE THREAD

**Issue by ELanzarini** [explosion/spaCy#7482]
I came across what I think is potentially odd behaviour when using the default spacy pipeline. The part-of-speech (POS) tagging using the pipeline is different from the result I get if I use `nlp` directly on the text. I have also seen the same error if different batch sizes in the pipeline are used.

**Can you confirm is this known behaviour?**

## Worked Example

Here is an example to replicate this - the specific error is on *'am'* in the second sentence:
```python
import spacy

nlp = spacy.load('en_core_web_sm', disable=['ner', 'entity_ruler', 'tok2vec', 'transformer'])

texts = ["I am more than happy to purchase this", "It was Main Street at 11am yesterday morning."]

# Using the pipeline of the entire list
for doc in nlp.pipe(texts):
    print([(t.text, t.tag_, t.pos_) for t in doc])

# result ('am', 'VBP', 'VERB')

# Loop through the list and create doc individually
for item in texts:
    doc = nlp(item).doc
    print([(t.text, t.tag_, t.pos_) for t in doc])

# result  ('am', 'RB', 'ADV')
```

## Your Environment

- **Platform:** Darwin-20.2.0-x86_64-i386-64bit
- **Python Version Used**: 3.7.6
- **spaCy Version Used**: 2.1.9
- **Environment Information**: en-core_web_sm (v. 2.1.0)

**Comment by svlandeg** [comment]
Hi @ELanzarini, thanks for the detailed report.

I do think this was a bug in the older versions of spaCy, I see you're using 2.1.9. I remember looking into this, and adding additional tests to ensure this behaviour doesn't happen in the newer versions: https://github.com/explosion/spaCy/blob/master/spacy/tests/pipeline/test_tagger.py#L172
```
    # Make sure that running pipe twice, or comparing to call, always amounts to the same predictions
    texts = [
        "Just a sentence.",
        "I like green eggs.",
        "Here is another one.",
        "I eat ham.",
    ]
    batch_deps_1 = [doc.to_array([TAG]) for doc in nlp.pipe(texts)]
    batch_deps_2 = [doc.to_array([TAG]) for doc in nlp.pipe(texts)]
    no_batch_deps = [doc.to_array([TAG]) for doc in [nlp(text) for text in texts]]
    assert_equal(batch_deps_1, batch_deps_2)
    assert_equal(batch_deps_1, no_batch_deps)
```
So in short, I think upgrading spaCy should solve your issue. 

We've recently revamped spaCy to [v3](https://spacy.io/usage/v3), which has a few backwards incompatibilities (and loads of new features!). However, if you don't want to migrate, you could also try one of the more recent v2 versions, such as v2.3.5. I'm pretty sure the behaviour was fixed in that version at least.

**Comment by ELanzarini** [comment]
Hi @svlandeg -- thank you for your quick response and really great to hear that this was a known issue and has been resolved. I'll look into upgrading spaCy to solve this. Thanks again.
