### ISSUE TITLE
Wrong results from dependency matcher

### ISSUE THREAD

**Issue by wayne315315** [explosion/spaCy#7499]
## How to reproduce the behaviour
Here's the sample code to reproduce the error [code link](https://github.com/wayne315315/spacy_dp_bug/blob/master/bug.ipynb
)
In the example, I wrote a dependency pattern for extracting the subjects of the conjunctive verbs with the help of custom extension, **"has_subj"**, and other attributes (POS, DEP, ...). 
You can see in the last cell, even though I specify that  **PREDICATE** should be **"has_subj" : False**, some of the results from the DependencyMatcher  are with **PREDICATE** with **"has_subj": True**, such as the following:

Relation : is_1_conj
-> PREDICATE : is (pos: VERB) (dep: conj) (has_subj: True)
-> OMIT_1 : is (pos: AUX) (dep: ROOT) (has_subj: True)
-> OMIT_2 : was (pos: VERB) (dep: conj) (has_subj: False)
-> SUBJ : He (pos: PRON) (dep: nsubj) (has_subj: False)
-> OBJ : bartender (pos: NOUN) (dep: attr) (has_subj: False)

## Your Environment
- **spaCy version:** 3.0.3
- **Platform:** Linux-5.4.0-67-generic-x86_64-with-Ubuntu-18.04-bionic
- **Python version:** 3.6.9
- **Pipelines:** en_core_web_md (3.0.0), en_core_web_lg (3.0.0), en_core_web_sm (3.0.0), en_core_web_trf (3.0.0)

**Comment by adrianeboyd** [comment]
Thanks for the report! This is a bug related to custom extensions and running the dependency matcher on spans rather than docs. A workaround is to run `matcher(doc)` instead of `matcher(sent)`.

**Comment by wayne315315** [comment]
Thanks @adrianeboyd 
Just wonder which released version will fix this issue, and when it will be released.

**Comment by adrianeboyd** [comment]
It should be fixed in v3.0.6. There are still several open PRs needed to fix this (#7528, #7574) and we don't have a planned release date at this point.

And although there are some advantages to using `span.as_doc` (no dangling dependencies outside the span), overall this is a slow way to handle spans. If you're processing whole documents and not just a small number of spans extracted from a document, it would be better to use `matcher(doc)` and the sort the matches by sentence based on the return token IDs. The matches are all restricted to being within a single sentence so the results for an individual sentence should be the same.

At some point we should extend the dependency matcher so that it processes the spans without making a copy, but this might be a bit tricky due to the dangling dependencies you could get for an arbitrary spans rather than sentence spans. I'm not sure how much work it would be, but we'd be happy to accept a PR that modifies this.
