### ISSUE TITLE
OMP: Error #15: Initializing libiomp5md.dll Error while Training ner_fashion_brands model

### ISSUE THREAD

**Issue by Sandy1811** [explosion/spaCy#7533]
Hi, I am getting "OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized" error, while running the training script on the ner_fashion_brands model.

https://github.com/explosion/projects/tree/v3/tutorials/ner_fashion_brands

Training command I am using: "python -m spacy train ./configs/config.cfg --output ./output -V"

Error:
<img width="810" alt="error" src="https://user-images.githubusercontent.com/30496770/112018596-b8455f80-8b54-11eb-974f-bcefe5e6a219.PNG">

spaCy Info: 
<img width="419" alt="spacy_info" src="https://user-images.githubusercontent.com/30496770/112017858-05750180-8b54-11eb-99f6-24c4a1f3a56a.PNG">

**Comment by polm** [comment]
Sorry you're having trouble with this. 

Does this happen if you use spaCy in other ways, or just with this project? If you haven't used spaCy otherwise, could you try importing it? 

Also, could you upgrade to the latest spaCy version? 3.0.0rc5 is slightly out of date now, and rc releases aren't intended for long term use.

**Comment by Sandy1811** [comment]
Thanks for replying. My issue is resolved now. I have created a new virtual env and installed spaCy again.

spaCy info:
![image](https://user-images.githubusercontent.com/30496770/112108765-ac9a7d00-8bd6-11eb-8d6f-fe6f0a2e3bd4.png)

**Comment by polm** [comment]
Glad to hear you fixed it, thanks for reporting back! I guess it's possible it was just something weird about your environment.
