### ISSUE TITLE
spacy convert KeyError: 'jsonl'

### ISSUE THREAD

**Issue by baiziyuandyufei** [explosion/spaCy#7587]
## How to reproduce the behaviour

when I convert the classification jsonl file to .spacy format file, prompt the error below:

command:
```
python -m spacy convert input_data output_data
```

prompt:
```
File "/usr/local/lib/python3.6/dist-packages/spacy/cli/convert.py", line 120, in convert
    func = CONVERTERS[converter]
KeyError: 'jsonl'
```

my .jsonl file like this:

```
{"text": "“士兵突击”90天，新兵连教会了我们什么", "cats": {"transport": 0, "education": 0, "military": 1}}
```

## Info about spaCy

- **spaCy version:** 3.0.5
- **Platform:** Linux-4.19.121-linuxkit-x86_64-with-Ubuntu-18.04-bionic
- **Python version:** 3.6.9
- **Pipelines:** zh_core_web_trf (3.0.0a1)

**Comment by bdewilde** [comment]
+1 on this error, only with macOS and PY3.9.

I've been fairly confused by the docs on how to structure my training data for a text categorization pipeline, so I'm not sure if this is user error of some sort? The closest thing I've found is [binary training format](https://spacy.io/api/data-formats#binary-training), but it details a complex, deprecated data format and an internal-only data format, and otherwise links out to `Corpus`, `Example`, `convert`, `DocBin`, ... pages, none of which (as far as I can tell) have a text categorization example to refer to.

There's also [this example dataset](https://github.com/explosion/spaCy/blob/master/extra/example_data/textcat_example_data/cooking.jsonl), but it looks like I'll need another data transformation step [like this](https://github.com/explosion/spaCy/blob/master/extra/example_data/textcat_example_data/textcatjsonl_to_trainjson.py) in order to get the data into the (deprecated?) format that `convert` may then be able to work with.

Please help, I'm lost in your lovely docs. :)

**Comment by polm** [comment]
Short answer: `jsonl` format for training data isn't supported. The only supported JSON format is the v2 format, which is not jsonl and is deprecated.

Longer answer: The standard way to represent training data in v3 is to make a DocBin, which is just a list of docs, and save that to the binary format. The full format details of everything are kind of complex but in practice this is actually pretty straightforward.

@bdewilde The example cooking dataset you linked to hasn't been updated since September of last year, so it doesn't reflect standard use for v3. 

[This example](https://github.com/explosion/projects/blob/3c17ba90490301e8665503a6516adf3f77bb5b07/pipelines/textcat_demo/scripts/convert.py) from the recent projects repo is a better overview of how you make training data for textcat in v3. 

A sort of minimal example would look like this:

```
import spacy
from spacy.tokens import DocBin

nlp = spacy.blank("en")
texts = ... # your training data
db = DocBin() # this will store the training examples
for text in texts:
    doc = nlp.make_doc(text)
    doc.cats = ... # set the true category labels
    db.add(doc)

db.to_disk("train.spacy") # save a binary training file
```

Does that clarify things?

**Comment by baiziyuandyufei** [comment]
Thank @polm 

run the [convert.py](https://github.com/explosion/projects/blob/3c17ba90490301e8665503a6516adf3f77bb5b07/pipelines/textcat_demo/scripts/convert.py) file like below, then sucessful!
`python convert.py zh input_data/dev.jsonl input_data/dev.spacy`

there also some suggest to the convert.py

1. the convert.py only support the file convert, not the directory. when I miss the 'lang' parameter, then pompt miss output directory.
2. if after convert, the code pompt how many line converted, how many line readed, and list the category set, maybe is better!

**Comment by polm** [comment]
Glad that solved your problem, thanks for the suggestions!

**Comment by bdewilde** [comment]
Thanks a ton @polm ! The new method is indeed very straightforward. I see now that I was confused about what was meant by "binary format" — for "JSON format", we mean data saved as JSON _and_ a specification about how that data should be structured, but the only info I found for the former case was "make and save a DocBin". I was thinking you'd have to attach the labels and such to each Doc in a particular way/structure, but in fact you just need to set up each Doc's info as if it were runtime and not training.
