### ISSUE TITLE
Parts of speech Tagging - Prediction

### ISSUE THREAD

**Issue by balajich** [explosion/spaCy#7608]
## How to reproduce the behaviour

No predecting verb properly.
```
#Parts of speech prediction
import spacy
nlp= spacy.load('en_core_web_sm') 
doc = nlp(u'Ines plays tennis three times a week')
#Parts of speech prediction
for token in doc:
    print(token.text,token.pos_)

doc = nlp(u'Balaji plays tennis three times a week')
#Parts of speech prediction
for token in doc:
    print(token.text,token.pos_)
```
Ines PROPN
plays VERB
tennis NOUN
three NUM
times NOUN
a DET
week NOUN

Balaji PROPN
**plays NOUN**
tennis VERB
three NUM
times NOUN
a DET
week NOUN

Why in the second stance it identifies plays as Noun it should be verb.
## Your Environment

* Operating System: Windows
* Python Version Used: 3.7
* spaCy Version Used: 2.4
* Environment Information:

**Comment by polm** [comment]
Sorry you're having trouble with this. Since spaCy's models are statistical, they aren't perfect or predictable, and when they do make errors it's often hard to explain exactly what caused them. You can read more about that in https://github.com/explosion/spaCy/issues/3052. 

That said, it looks like you're using an old version of spaCy. I tried this with the latest 3.0.5 and it works correctly, marking `plays` as a VERB in the second sentence. So it looks like we've gotten better in this case!

**Comment by balajich** [comment]
Thank you polm.   Issues bound to occur in any library. Its the community support that  makes the difference. Thank you for taking time and helping me to understand the issue. Please close the issue.
