### ISSUE TITLE
Spacy recognize € as punctuation

### ISSUE THREAD

**Issue by quangduc** [explosion/spaCy#7613]
## How to reproduce the behaviour
Hi, I am using spacy with English model en_core_web_trf. When I check the lexeme of €, it shows $, which is as expected:

```
nlp.vocab["€"].norm_ ===> $
``` 

But when I parse this sentence "Digital-First Tylko Raises €22 Million in Series C as Part of Its Commitment to Set New Standards in the Furniture Industry", it recognize € as punctuation:

<img width="1677" alt="Screen Shot 2021-03-30 at 08 20 22" src="https://user-images.githubusercontent.com/4360657/112942683-ca189b00-9130-11eb-8868-61a8d511ca53.png">

In the meanwhile, if I replace € by $, I get the expected dependency tree:

<img width="1669" alt="Screen Shot 2021-03-30 at 08 21 29" src="https://user-images.githubusercontent.com/4360657/112942782-f0d6d180-9130-11eb-87d5-6fd6ca764d64.png">

I have no idea how to resolve this. Can you please help me? Thanks a lot

## Your Environment

* Operating System:  Mac 10.15.7
* Python Version Used: 3.9
* spaCy Version Used: 3.0.0

**Comment by polm** [comment]
Huh, that is weird. Note that `is_punct` is actually False. Also the € seems to be correctly tagged as SYM on the small English model. 

This might just be an issue with the training data in the Transformer models.

**Comment by quangduc** [comment]
yes. I just want to say that I use the model directly without any personal training data. Do you have any workaround way to fix it?

**Comment by adrianeboyd** [comment]
No, there's currently no way to fix this without retraining or fine-tuning the model. `NORM` isn't the only feature used by the model and a lot of the current English training data is from ~20 years ago and it turns out that the Euro symbol doesn't appear at all.

The dependency parser will preserve all existing sentence boundaries, but there's no way to provide rule-based constraints or partial parses that restrict how a particular token is analyzed. Given how the transition-based parsing algorithm works, it would be difficult to incorporate this.

If you do want to fine-tune the model, this kind of training data should be relatively easy to generate automatically: just substitute these symbols in sentences that you have with the correct parses already and update the model.

Note that the POS tags and `is_punct` are completely separate from each other and from the dependency parse. If you want to force a particular POS for a particular token, you can add an exception to the `attribute_ruler` that's applied after the tagger is run, see: https://spacy.io/usage/linguistic-features#mappings-exceptions. Adding these kinds of exceptions will not change the dependency parse.
