### ISSUE TITLE
vocab.strings cannot retrieve string with hash ID

### ISSUE THREAD

**Issue by xiaohy9** [explosion/spaCy#7619]
## How to reproduce the behaviour
```
nlp = spacy.load("en_core_web_sm")
len(nlp.vocab.strings)

coffe_hash= nlp.vocab.strings['coffee']
print(coffe_hash)
coffee_string = nlp.vocab.strings[coffe_hash]
print(coffee_string)
```

Error message:
KeyError: "[E018] Can't retrieve string for hash '3197928453018144401'. This usually refers to an issue with the `Vocab` or `StringStore`."

But after I processed a doc with the word coffee, it worked
```
doc = nlp("I love coffee")
coffee_string = nlp.vocab.strings[coffe_hash]
print(coffee_string)
```

## Your Environment

* Operating System:
* Python Version Used: 3。7
* spaCy Version Used: 2.2.4
* Environment Information:

**Comment by polm** [comment]
This appears to have been an issue in 2.2 that is resolved in v3 https://github.com/explosion/spaCy/issues/1985.

**Comment by adrianeboyd** [comment]
To clarify, the missing strings mentioned in that issue are a separate problem. For this `coffee` example, this is the expected behavior for the `StringStore` API in both v2 and v3, see this comment: https://github.com/explosion/spaCy/issues/1985#issuecomment-650565611

It would probably be better if the course example used `nlp.vocab.strings.add("coffee")` instead.
