### ISSUE TITLE
Tokenizer.explain and tokenizer.__call__ return inconsistent results in spacy 3.0.5

### ISSUE THREAD

**Issue by nrodnova** [explosion/spaCy#7694]
## How to reproduce the behaviour
```
model_sm = spacy.load('en_core_web_sm')
text = '13.5 cm/s.'
model_sm.tokenizer.explain(text)
```
prints the following:
```
[('TOKEN', '13.5'),
 ('TOKEN', 'cm'),
 ('INFIX', '/'),
 ('TOKEN', 's'),
 ('SUFFIX', '.')]
```
And this fragment
```
for token in model_sm.tokenizer(text) :
    print(token)
```
prints:
```
13.5
cm
/
s.
```
The final period gets attached to s when the text is tokenized, but explain method shows it as a SUFFIX

## Your Environment

- **spaCy version:** 3.0.5
- **Platform:** Darwin-18.7.0-x86_64-i386-64bit
- **Python version:** 3.7.3
- **Pipelines:** en_core_web_lg (3.0.0), en_core_web_md (3.0.0), en_core_web_sm (3.0.0), en_core_web_trf (3.0.0)

**Comment by adrianeboyd** [comment]
Thanks for the report! `Tokenizer.explain` was missing some updates for changes to the tokenizer in v3.

**Comment by nrodnova** [comment]
@adrianeboyd I am seeing a few small tokenization differences in English. One of them is that a single letters with a period following it do not get split, and they used to in spacy 2. Things like `a.` or `s.` are a single token now. Do you happen to know off the top of your head where it is coming from?

**Comment by adrianeboyd** [comment]
The difference between v2 and v3 is how special cases that contain affixes and that are adjacent to other tokens/affixes are handled.

Both versions have the same special case `s.` (for all lowercase letters `a.`, `b.`, etc.). You always get `s.` if the token is between spaces, but in v2.3.5 if it's adjacent to other tokens/affixes, you can get this behavior:

```python
import spacy
nlp = spacy.blank("en")
assert [t.text for t in nlp("s.")] == ['s.']
assert [t.text for t in nlp("m/s.")] == ['m', '/', 's', '.']
```

In v3.0 there's an additional check for special cases after the affixes are split to find the case it missed above:

```python
import spacy
nlp = spacy.blank("en")
assert [t.text for t in nlp("s.")] == ['s.']
assert [t.text for t in nlp("m/s.")] == ['m', '/', 's.']
```

Similar things happen with unbalanced prefixes/suffixes, so `("s.` would be split into `s .` and `"s."` wouldn't. The changes are to try to find special cases more consistently, and they also allow spaces in special cases which wasn't possible in v2 so you could have an exception like `out of` if you wanted this to be one token.

**Comment by nrodnova** [comment]
Hi @adrianeboyd , what solution would you suggest to preserve the old behavior? I am having problems with sentence breaking after expressions like `n/a.` or `mm/s.` among others. If I remove `['a.' - 'z.']` from special cases, then I am messing up people's names, like `John F. Smith`.  On top of that, I have a lot of tokenization-sensitive annotation data. I am using a custom tokenizer class derived from spaCy's Tokenizer with modified prefix/suffix/infix rules. The easiest (but not the most elegant by any means) solution seems to be emptying `self._special_matcher` patterns, but I do not have access to it because it is not exposed outside of Cython. Overwriting `__call__` method and skipping the call to `self._apply_special_cases(doc)`would be better, but then again I have no access to `self._tokenize_affixes`

**Comment by adrianeboyd** [comment]
Hi, sorry for the delayed response, somehow I lost my draft here...

Let's see, the special cases are case sensitive, so removing `a.` - `z.` shouldn't affect names like `John F. Smith`. (To be honest, I don't really think these abbreviations should be in the default special cases for all languages, but they've been in the library for a long time.)

If you want to expose the `_special_matcher` in python you'd have to declare the attributes as `readonly` or `public` in `tokenizer.pxd`, so:

```python
    cdef readonly PhraseMatcher _special_matcher
```

I don't think we have any particular reason to prevent you accessing the internals in python in general (we could consider making this change for spacy v3.1), but you'd have to be pretty careful with this, since adding a new special case would clear the cache and re-add the exceptions, so it would be pretty brittle.

Having a custom tokenizer that overrides `__call__` would be the cleanest option, and with registered functions it's pretty easy to have an additional package that provides a modified tokenizer, but you can only extend the `Tokenizer` in cython. Extending the cython class is not too difficult, the problem is that the pip packaging is hard to get right. I was curious about how much work it would be so I created a demo that shows this change just to `__call__`:

https://github.com/adrianeboyd/custom-cython-tokenizer

You could install this package in your venv and then `custom_tokenizer.v1` would be available for use in your config. You could then add this package as a requirement to your model in `meta.json` under `"requirements"`. (Or you can always import it in your code instead of installing the package.)
