### ISSUE TITLE
TAG_MAP definition and POS training for languages with complex grammar

### ISSUE THREAD

**Issue by ecamaj** [explosion/spaCy#780]
Croatian language has very complex grammar and POS tagging consists of many elements (tags):
http://nlp.ffzg.hr/data/tagging/msd-hr.html#msd.msds-hr

so, when all those elements are added to TAG_MAP, example: 

```
'Agcfpi': {'Degree': 'Cmp', 'Gender': 'Fem', 'Number': 'Plur', 'pos': 'ADJ'},
'Ps3npap-n-a': {'Gender': 'Neut',
                    'Number': 'Plur',
                    'Number[psor]': 'Plur',
                    'Person': '3',
                    'Poss': 'Yes',
                    'PronType': 'Prs',
                    'Variant': 'Long',
                    'pos': 'DET'},
...
```
and then using training script for POS traning there is problem with morphology/attrs scripts.

Conclusion after chat with Matt - morphology and attrs scripts should be rewritten for better support of the new languages.

## Environment
* Operating System: MacOS Sierra
* Python Version Used: 3.5
* spaCy Version Used: 1.6

**Comment by adrianeboyd** [comment]
Hi, we're going through older issues now that the final v3.0 release is coming quite soon with a lot of new features. One of the new features is a `morphologizer` component that can be used instead of the tag map to learn POS + morphology features directly rather than mapping them from the fine-grained tags with a tag map.

You can try it out currently through the `spacy-nightly` release: https://nightly.spacy.io . Most of the pretrained pipelines now come with a morphologizer component, so you can try one out (English doesn't have a morphologizer, but most other languages do): https://nightly.spacy.io/models

One of the example projects (called `pipelines/tagger_parser_ud`, see the first highlighted box) shows the whole workflow for how to train a tagger, morphologizer, and parser from a UD corpus: https://nightly.spacy.io/usage/projects

Please feel free to open a new issue if you run into any problems!
