### ISSUE TITLE
nlp.pipe with multiprocessing does not exit when encountering an error

### ISSUE THREAD

**Issue by alexcombessie** [explosion/spaCy#7934]
## How to reproduce the behaviour
```python
import spacy 
texts = ["This is a super long text", "I love spaCy"]
nlp = spacy.blank("en")
nlp.max_length = 1
list(nlp.pipe(texts, n_process=2))
```
Google colab: https://colab.research.google.com/drive/18JbYH6Vje-vBNvsGBJ9cNxIEIRj4K-xz?usp=sharing

This code snippet will display an error:
```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/spacy/language.py", line 2027, in _apply_pipes
    sender.send([doc.to_bytes() for doc in docs])
  File "/usr/local/lib/python3.7/dist-packages/spacy/language.py", line 2027, in <listcomp>
    sender.send([doc.to_bytes() for doc in docs])
  File "/usr/local/lib/python3.7/dist-packages/spacy/language.py", line 2023, in <genexpr>
    docs = (make_doc(text) for text in texts)
  File "/usr/local/lib/python3.7/dist-packages/spacy/language.py", line 1063, in make_doc
    Errors.E088.format(length=len(text), max_length=self.max_length)
ValueError: [E088] Text of length 25 exceeds maximum of 1. The parser and NER models require roughly 1GB of temporary memory per 100,000 characters in the input. This means long texts may cause memory allocation errors. If you're not using the parser or NER, it's probably safe to increase the `nlp.max_length` limit. The limit is in number of characters, so you can check whether your inputs are too long by checking `len(text)`.
```

But the process will never exit, and run forever.

## Your Environment
* Operating System: reproduced on macOS (11.2.3) and Linux (CentOS 7 and Ubuntu 18.04)
* Python Version Used: reproduced on CPython 3.6 and 3.7
* spaCy Version Used: reproduced on spacy 2.3.5, 3.0.5, and 3.0.6
* Environment Information: nothing in particular

**Comment by adrianeboyd** [comment]
Hi, thanks for the report! This seemed like a pretty annoying bug, so I went ahead and had a look in #8004.

**Comment by alexcombessie** [comment]
Hi @adrianeboyd,

Thanks a lot for looking into this yourself! Much appreciated. I had done some initial investigation in my PR #7936, but I was not sure how to fix this.

I will have a look at your PR #8004 to understand how to did it 🙇 

Cheers,

Alex

**Comment by adrianeboyd** [comment]
It's all kind of headache-y.

Some notes:

The main thing is that the workers have to send back the correct number of items or it will hang because it's counting the returned docs to know when it's done.

It's not specific to this bug report, but I think logging still isn't going to work if you're logging to the same file from multiple child processes.

The error handling behavior differs depending on whether the components implement `pipe` or not. If they do and an error is caught and not raised by the error handler (ignored or converted to a warning), the whole batch is discarded, but if they don't implement `pipe` then only the individual documents are discarded. I think if you're doing anything other than `raise_error` for errors, you'll have to deal with it being a little inconsistent.

If the error is in `make_doc` then it's handled slightly differently with and without multiprocessing, which is also not ideal, but maybe not worth the effort to fix.

And I couldn't get the mock logger in pytest to detect the warnings from child processes, but I don't know for sure that it's even possible.
