### ISSUE TITLE
Loading local models explanation is unclear

### ISSUE THREAD

**Issue by jreades** [explosion/spaCy#7968]
Hi -- I'm trying to slim down a Docker image and also allow for updates to the NLP models that I've created or downloaded by loading them from a mounted volume instead of baking them into the image directly. That also allows these models to be persistent so that I don't have to keep re-downloading them even if they are ones provided via the default `spacy.load()` functionality. 

However, the only comment on how to do this is ambiguous:
> You can place the model data directory anywhere on your local file system. To use it with spaCy, simply assign it a name by creating a shortcut link for the data directory.

What I'd like to do is either:
1. Be able to specify a location when I run `python -m spacy.download 'en_core_web_lg'`, or 
2. Download a `.gz` model file from the recent releases to my computer and then make that available to spaCy via `spacy.load()` so that I never need to 'install' them into Docker (where they will not persist between restarts). However, when I tried this spaCy claimed not to be able to interpret the `config.cfg` information being provided.

The only way I've found around this is to download the model as normal, load it, and then call `nlp.to_disk('path/to/model')`. A nice solution would simply be to have a parameter on the command line for downloading, but spaCy doesn't appear to pay attention to any of the clues that I found on StackOverflow (`$SPACY_DATA_DIR`, `--data-path`, or `model.path`).

## Which page or section is this issue related to?

This is in relation to the guidance for [manually downloading spaCy models](https://github.com/explosion/spacy-models#manual-download-and-installation).

**Comment by adrianeboyd** [comment]
Ah, sorry for the confusion, the README in `spacy-models` has gotten a bit out-of-date. The more up-to-date docs are here: https://spacy.io/usage/saving-loading#models, although the difference between loading from packages and loading from directories is not clarified as well as it could be.

The "data dir" info/answers are all only relevant for spacy v2. These settings have been removed from v3 because they relied on symlinks that caused a lot of cross-OS installation headaches.

So, starting with v3.0.0, you really want to install model packages with `pip`, since in case they include custom code it's only loaded automatically if it's installed as a package, not from a directory, which is probably what's leading to the config.cfg errors you're seeing. You can load from a directory as long as you import the required code in advance in your script, but using packages makes this easier, especially for third-party models.

The basic version is that you download the `.tar.gz` or `.whl` for the model you want and then install it directly with pip:

```bash
pip install /path/to/models/en_core_web_sm-3.0.0-py3-none-any.whl
```

You can click on "release details" on any model entry in https://spacy.io/models to get a link to the github release and scroll down to the bottom of the page to find the attached model files. For your own custom models, you can use `spacy package` to create pip-installable packages.

You can also use `-f` with pip to have it search a local directory for wheels, e.g.:

```bash
pip install en_core_web_sm==3.0.0 -f /path/to/models
```

`spacy download` is custom for our provided pipelines (it always checks a compatibility table in the `spacy-models` github repo), so having it check other paths doesn't really make sense.

We had caching disabled in the v2 `spacy download` command because `pip` sometimes ran out of memory trying to create the cache entries for large models, especially when people often had less RAM when the earliest versions of v2 were released. We re-enabled it for v3 and also made wheels rather than `.tar.gz` files the default for faster installs with `pip`, but I can report that at least on my end, the caching still doesn't seem to work correctly in all envs, but I've never figured out exactly what's going on.

**Comment by jreades** [comment]
Thanks that's really helpful and does a lot to help me understand the changes and the rationale behind them. 

I guess what I'm trying to figure out is the best way to distribute the Docker image _without_ pre-installing all of the models my students and researchers might need as these 'bloat' the image and bake in a specific release. Technically, I guess this is the way Docker is supposed to work, but I'm teaching students on all sorts of connections with different first languages... so some of them will also want to install models for their own language, so installing the md or lg models for multiple languages would make the image much, much larger. 

But, of course, once a Docker image is built you can't permanently install new libraries since it's a read-only FS aside from the mounted directory. So my idea was to have a folder on the mounted drive where they could drop any models (either a pre-existing one from spaCy or one that we develop together) and load them dynamically.

Thinking it through I've come up with the following:

### Solution 1

I guess I could have a provisioning script that scans a directory on start-up and loads any models it finds using the `pip` syntax... those will be lost when the container is shut down, but if the loading is automatic on start-up then it doesn't much matter. 

### Solution 2
This also seems to work in JupyterLab:

1. Use the downloader
```python
! python -m spacy download en_core_web_md
! python -m spacy download en_core_web_lg
```

And then save each to disk: 
```python
import spacy
import os
for m in ['en_core_web_md','en_core_web_lg']:
    p = os.path.join(os.environ.get('SPACY_DATA_DIR'),m)
    if not os.path.exists(p):
        print(f"Loading {m}")
        nlp = spacy.load(m)
        nlp.to_disk(p)
```

They can now be loaded locally:
```python
p = os.path.join(os.environ.get('SPACY_DATA_DIR'),'en_core_web_lg')
nlp = spacy.load(p)
```

I note these down mainly so that anyone else dealing with my slightly odd set of requirements can get some ideas about how to resolve. If you want to close now I'll completely understand, but if other people would have similar issues with Docker images there might be a bit more demand for a straightforward non-pip approach.

Cheers.

**Comment by adrianeboyd** [comment]
Just note again that option 2 will work not for packages that include with extra code. It's not saved with `nlp.to_disk()` or loaded with `spacy.load()` when loading from a path.

The URLs are not difficult to generate if you want to download the packages once directly, e.g.:

https://github.com/explosion/spacy-models/releases/download/zh_core_web_trf-3.0.0/zh_core_web_trf-3.0.0-py3-none-any.whl

For models before v3.0.0 there are only `.tar.gz`, not `.whl` files.

I had another idea:

You might consider having a shared directory where the model packages are **installed as packages** and having users add that to `PYTHONPATH`? The models are all compatible across python/OS versions, so I think something like this would work:

```bash
pip install en_core_web_sm-3.0.0-py3-none-any.whl -t /path/to/models
export PYTHONPATH=$PYTHONPATH:/path/to/models
python -c "import spacy; spacy.load('en_core_web_sm')"
```

**Comment by adrianeboyd** [comment]
Thanks again for the report, we've updated the `spacy-models` READMEs for v3.

**Comment by jreades** [comment]
That last option (have a shared directory in the writeable mount point of the image) seems like the right one and I'm trying it out now, but since I'm also mucking about with transformers at the same time and need to rebuilt the image it's hard to know if I've done it all correctly at the moment. I'll add a comment if it _doesn't_ work.

Really appreciate your taking the time to respond and to update the documentation.
