### ISSUE TITLE
spaCy load time for pos tagger is too large when using multiprocessing

### ISSUE THREAD

**Issue by theultimatecrouton** [explosion/spaCy#800]
[Stack Overflow question ](http://stackoverflow.com/questions/41988915/avoiding-loading-spacy-data-in-each-subprocess-when-multiprocessing)

As per the SO question. I am trying to avoid the overhead of loading spacy in many separate processes when multiprocessing. As far as I can tell, since the loaded spacy object cannot be serialized, it cannot be shared amongst processes, therefore each process must load its own version of the object which is very expensive. Is there a workaround for this? Note that I really, really don't want to use multithreading (which would allow this to work).

Also, I only need POS tagging, is there any way to load only the relevant data for this rather than everything (parser, NER etc)?

## My Environment
* Operating System: Ubuntu 16.04
* Python Version Used: 3.5.2
* spaCy Version Used: 1.6.0

**Comment by honnibal** [comment]
Have you tried setting `parser=False` and `add_vectors=False` when you load? That should make the loading <5s.

Btw serialisation wouldn't help --- deserialisation is the same as loading. The problem is more about the size and shape of the data being loaded. Btw the tagger doesn't currently release the GIL, so multithreading isn't helpful here. I would definitely recommend multithreading for the parser, though.

The tagger is quite fast...If I'm tagging a lot of texts I'll usually just separate the inputs into batches and execute the script over each one, e.g. have a separate invocation of the program for each month of data.

**Comment by theultimatecrouton** [comment]
Thanks for your reply, very helpful.

I had `parser=False` but not `add_vectors=False`, putting that in does take 5s off the loading time which is handy.
