### ISSUE TITLE
Japanese Tokenizer Returning Tokens Inconsistent with Sudachipy or Ginza

### ISSUE THREAD

**Issue by xichencl** [explosion/spaCy#8027]
## Bug
"申し込ん" is expected to be tokenized/segmented into one word, but gets broken up into two. This is not consistent with Sudachipy, which is I believe what spaCy uses in the backend? (see results below).  Also tried the latest version of spacy with the latest model. Same results. 
When I pip install ginza, however, that seems to have solved the problem, either using spacy.load('ja_ginza') or spacy.load('ja_core_news_sm'). 

## How to reproduce the behaviour
Spacy clean install and load
>>> import spacy
>>> nlp = spacy.load("ja_core_news_sm")
>>> doc = nlp("申し込ん")
>>> [tok.text for tok in doc]
['申し', '込ん']

## Sudachipy 
echo "申し込ん" | sudachipy
申し込ん	動詞,一般,*,*,五段-マ行,連用形-撥音便	申し込む

## Ginza
>>> import spacy
>>> nlp = spacy.load('ja_ginza')
>>> doc = nlp("申し込ん")
>>> [tok.text for tok in doc]
['申し込ん']

## Your Environment
* Operating System: MacOS
* Python Version Used: 3.6
* spaCy Version Used: 2.3.2
* Environment Information: pipenv

**Comment by polm** [comment]
spaCy is just using SudachiPy mode A, which is more fine-grained than the default mode on the command line. The output is equivalent if you do this (I'm going to use 申し込む because it's valid by itself and shows the same issue):

    echo "申し込む" | sudachipy -m A

Mode A is basically UniDic short unit words, which is also the unit used in training corpora, so spaCy uses that. I think SudachiPy defaults to B, which is why you see this difference. 

This particular case is weird because with UniDic 申し込む is a single token. It looks like SudachiPy splits compound verbs, but only when they're used as verbs; as nouns (申し込み or  受け付け) they are a single token. Not sure where this particular detail is in their documentation.

**Comment by xichencl** [comment]
Thank you @polm! Is there a way we can choose which model we use in spacy? I wonder if the change would be trivial to engineer. Splitting compound verbs would be useful in some use cases, i imagine, but annoying in others, where we want to preserve the meaning of the compound verb, as the individual verbs that make up the compound verb may take on somewhat different meanings.

**Comment by polm** [comment]
It's not hard to change the tokenizer mode, you just need to this:

```
# default
import spacy
nlp = spacy.load("ja_core_news_sm")
doc = nlp("申し込む")
print([tok.text for tok in doc])

# B Mode
from sudachipy import tokenizer, dictionary

tok = dictionary.Dictionary().create("B")
nlp.tokenizer.tokenizer = tok
nlp.tokenizer.split_mode = "B"

doc = nlp("申し込む")
print([tok.text for tok in doc])
```

However, since the word vectors and models all depend on the tokenizer mode, I wouldn't expect to be able to use the pretrained models this way. You can use vectors from [ChiVe](https://github.com/WorksApplications/chiVe), which is the source of static vectors in the pretrained models, and offers vectors for a few Sudachi settings, but you'd need to train your own models.

**Comment by adrianeboyd** [comment]
I wouldn't recommend modifying the tokenizer in `ja_core_news_sm` because the statistical components won't work well with the modified split mode and you don't want to accidentally end up using the pipeline in this state.

Instead, you can initialize a blank `ja` pipeline with just `sudachipy` settings as shown here: https://spacy.io/usage/models#japanese

**Comment by polm** [comment]
Note that the config option at the link is for v3, not v2. If you're just getting started I would recommend upgrading though.

**Comment by adrianeboyd** [comment]
Ah, sorry I missed that. Here are the v2 settings: https://v2.spacy.io/usage/models#japanese
