### ISSUE TITLE
spacy-models/template is out of date

### ISSUE THREAD

**Issue by tallpauley** [explosion/spaCy#8038]
The package template in `spacy-models/template` differs from the format actually used by `spacy package` in `spacy/cli/package.py`.

I found it particularly confusing as I was trying to understand how spacy discovered models via `entry_points`, as the `setup.py` in `spacy-models/template` doesn't include this. Not a big thing, just found this confusing. Maybe `template/` can be removed? Or am I missing something?

**Comment by polm** [comment]
Sorry about that, it looks like the template hasn't been update since it was added in 2017, so it's definitely out of date. Removing it may be the right thing. Thanks for reporting it!

In the meantime the `spacy/cli` scripts are the right place to look to understand how model loading works, though the details are considered more of an implementation detail than a user-facing API.

**Comment by polm** [comment]
Going to close this since there's a PR to remove the directory. https://github.com/explosion/spacy-models/pull/105
