### ISSUE TITLE
spacy ImportError when installed in clean python2 anaconda environment. 

### ISSUE THREAD

**Issue by Skyba** [explosion/spaCy#810]
When i execute the following four lines of code : 
```
conda create -n python2 python=2 anaconda
source activate python2
pip install spacy
python >> import spacy
```
I get the error message `ImportError: /home/basilev/anaconda3/envs/python2/lib/python2.7/site-packages/spacy/morphology.so: undefined symbol: PyFPE_jbuf`

I have seen the reported [Problem importing Spacy in Spyder/IPython](https://github.com/explosion/spaCy/issues/333), however  in my case, installing and reinstalling numpy does not seem to solve it. I tried th same with a python3 environment, everything works nice and smooth! 

Does anyone have an idea of how to approach this problem ? Any help is greatly appreciated ! 

## My Environment
* Operating System: ubuntu trusty 
* Python Version Used: 2.7
* spaCy Version Used: 1.6
* Environment Information: Anaconda

**Comment by honnibal** [comment]
99% of the time this sort of problem gets traced back to different copies of Python executing different parts of the process. I have to say this happens to me too *all the time*, even though I do this stuff day in, day out :(

Try this. When you type `python` and get into the interpreter, have a look where you're importing stuff from:

```python
>>> import math
>>> math.__file__
'/Users/matt/.pyenv/versions/2.7.9/lib/python2.7/lib-dynload/math.so'
```

Okay, so I'm executing this `pyenv 2.7.9` copy — if I expected to have a virtualenv, I'd see immediately what was wrong. But let's say this version is right. Now do:

```
python -m pip install 
```

This guarantees that `pip` is being run by the correct Python. Otherwise, you can end up with a `PATH` variable that looks things up in some order such that `python` and `pip` get resolved differently. I still haven't 100% understood how this happens, but it does...

Incidentally this is why we have `python -m spacy.en.download` instead of a `spacy` command. It's more typing, but at least it's one less thing to go wrong...

**Comment by Skyba** [comment]
Thank you for your response! 

As you suggested I tried the same as in my original post, this time with `python -m pip install spacy`. I still get the same error (PyFPE_jbuf). 

So i cloned the repo and executed `python -m spacy.en.download`. 
This gave me a `/home/basilev/anaconda3/envs/python2/bin/python: No module named attrs` error. 

according to capdevc's comment on [issue 253](https://github.com/explosion/spaCy/issues/253), this should be solvable by using (if i understand correctly) a `pip install .` command followed by `python -m spacy.en.download`. But I am still stuck with that attrs error :/. 

I also update thinc just in case - did not seem to change anything.

**Comment by Skyba** [comment]
By the way, i have found a workaround : I simply reinstalled anaconda / ipython in a new virutal environment, and it seems to work fine. 

But a solution might help other people who bump on the same problem =) Cheers!

**Comment by ines** [comment]
Great to hear you got it to work – and thanks for sharing the solution!
