### ISSUE TITLE
Token prob attribute in to_array

### ISSUE THREAD

**Issue by mtdineen** [explosion/spaCy#815]
Hi,

I am having issues with outputting prob tags in the to_array function. The tags are being generated but are appearing as 0 in to_array output:
```
import spacy.en
from spacy import attrs
import numpy as np

nlp = spacy.en.English()

toks = nlp(u"This is a simple sentence.", True, True)

print "Extracting probability"
print np.array(toks.to_array([attrs.PROB]))


print "Even though the prob is detected"
print [t.prob for t in toks]
```

## Your Environment
* Operating System: Windows 10
* Python Version Used: 2.7
* spaCy Version Used: 1.2.0

**Comment by honnibal** [comment]
This is tricky because the probabilities are naturally a float, while `to_array` returns an integer-typed array. I think the idea was to round the log probabilities to the nearest integer value, which still feels reasonable. Certainly zeros are wrong, though!

In summary: you might want to consider not using `to_array` here, because even after the bug is fixed you'll still be getting an approximate answer. If efficiency is the problem, just make your loop in Cython:

```
# cython: infer_types=True
probs = numpy.zeros((doc.c.length,), dtype='float32')
probs_ptr = <float*>probs.data
for i in range(doc.c.length):
    probs_ptr[i] = doc.c[i].lex.prob
return probs
```

This should compile to straight-forward C, with a single pointer dereference.

**Comment by mtdineen** [comment]
Thanks I thought it might be an issue with the underlying datatypes alright. I'll write the probabilities in a loop as suggested.
