### ISSUE TITLE
Unsupervised Named Entity Suggestion?

### ISSUE THREAD

**Issue by eromoe** [explosion/spaCy#829]
Hi,

I am new to spaCy and Named Entity Recognition. Now I want to train a Chinese Named Entity model, but most of articles I saw about Named Entity Recognition are talking that it need people to label a tokenized dataset for trainning, just as I see in https://spacy.io/docs/usage/entity-recognition#updating .

If spaCy provide a way to suggest the Possible Named Entity Candidates (Such as unsupervised trainning a dataset), then I can pick enough number of correct Named Entity out and use that for further trainning. It would be much more efficient.

**Comment by ines** [comment]
I agree – this is definitely something we care about a lot! We've been experimenting with different approaches for more efficient training and active learning, and it's working pretty well so far. So we're hoping to be able to release something along those lines soon.

In the meantime, here are some ideas that might help:

* use an algorithm like [word2vec](https://radimrehurek.com/gensim/models/word2vec.html) to find a set of similar entities, then classify the contexts
* you could also take inspiration from [spaCy annotator](https://github.com/explosion/spacy-dev-resources/tree/master/spacy-annotator) by @tcrossland, a trainable server for named entities. It's still experimental, but the concept behind it is potentially very useful for this task. It can even be hooked up with an (also experimental) [front-end](https://github.com/tcrossland/spacy-annotator) that lets you highlight entities manually.

**Comment by ines** [comment]
Quick update: We have since released [Prodigy](https://prodi.gy), an annotation tool for creating training data interactively with a model in the loop that suggests the most relevant examples for annotation. To get over the cold-start problem, you can pass in match patterns (similar to the ones used by spaCy's `Matcher`) describing entity candidates. For a full end-to-end example of training a new entity type, check out [this video tutorial](https://www.youtube.com/watch?v=l4scwf8KeIA).

Prodigy is our first commercial product, and comes with built-in spaCy support, as well as options for loading in your own models from other libraries.
