### ISSUE TITLE
ImportError: DLL load failed on Windows

### ISSUE THREAD

**Issue by eromoe** [explosion/spaCy#830]
Hi, 

I  have tried 
- uninstall `pip uninstall -y spacy thinc cymem murmurhash preshed ujson`
- reinstall `pip install spacy`

but always get:

```
>python -c "import spacy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Python27\lib\site-packages\spacy\__init__.py", line 3, in <module>
    from .util import set_lang_class, get_lang_class
  File "D:\Python27\lib\site-packages\spacy\util.py", line 11, in <module>
    from .attrs import TAG, HEAD, DEP, ENT_IOB, ENT_TYPE
ImportError: DLL load failed: 应用程序无法启动，因为应用程序的并行配置不正确。有
关详细信息，请参阅应用程序事件日志，或使用命令行 sxstrace.exe 工具。
```

## Your Environment

* Operating System:  Windows 7/10 X64
* Python Version Used: python 2.7.12 win32
* spaCy Version Used: latest
* Environment Information:  Git-bash installed, share some unix commad in cmd . Microsoft Visual C++ Compiler for Python 2.7 installed.

**Comment by eromoe** [comment]
Note, this error seems only happen on python2.7. `import spacy` is fine when I use Anaconda 3

    Operating System: Windows 7 X64
    Python Version Used: 3.5 env
    spaCy Version Used: latest
    Environment Information: Anaconda 3

**Comment by NickLarsen** [comment]
This is the same for me.  I install both 32bit and 64 bit versions of python and it happens no matter what.

**Comment by ines** [comment]
We just released v1.7.0. Could you check again to see if it's fixed now? If you're still having problems, feel free to reopen.

* [Release notes](https://github.com/explosion/spaCy/releases) for 1.7.0
* [Models documentation](https://spacy.io/docs/usage/models)
* [Command line interface documentation](https://spacy.io/docs/usage/cli)

**Comment by abubakarsohail** [comment]
I am having exact same error. Please check the screenshot
![capture](https://cloud.githubusercontent.com/assets/20099503/24180958/d2b10fd2-0ed9-11e7-8742-8bd155ba39fd.PNG)

**Comment by honnibal** [comment]
Hard to debug ata distance, but some thoughts:

* Are you on 32bit Python? That doesn't work unfortunately

* As always, upgrading is more brittle than clean installation. Installing into your system Python is bad for this reason, because you can't wipe your state clean. But try uninstalling spacy, thinc and preshed and then reinstalling.

**Comment by abubakarsohail** [comment]
@honnibal Yes, I am on 32bit Python.  Okay. I'll install python + everything from the start. Should I use 64 bit Python?

**Comment by abubakarsohail** [comment]
@honnibal Still the same. Please check the screenshots. I am using Python 32 bit.
![capture](https://cloud.githubusercontent.com/assets/20099503/24215330/40843ce8-0f5a-11e7-8f20-012398821f9d.PNG)
![capture](https://cloud.githubusercontent.com/assets/20099503/24215349/4e1e54e2-0f5a-11e7-9ffa-75c689c14df7.PNG)

**Comment by abubakarsohail** [comment]
@honnibal for the record, I have tried python 64 bit as well. same error.

**Comment by jeremied3** [comment]
Have win10, tried installing spacy, it failed, tried through conda and stuff and then i got:

C:\Users\>python -m spacy.en.download all
C:\Python27\python.exe: DLL load failed: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

Some websites recomended doing:
Install VS Express 2008
https://go.microsoft.com/fwlink/?LinkId=104679
Install "Visual C++ 2008 Express Edition"
Install
https://www.microsoft.com/en-us/download/details.aspx?id=44266
Install
https://www.microsoft.com/en-us/download/confirmation.aspx?id=15336

pip install -U spacy
python -m spacy download en
but it wasn't working . However when i run:
pip uninstall -y spacy thinc cymem murmurhash preshed ujson

and then tried python -m spacy download en 
it worked fine and solved my spacy issues. Cheers!

**Comment by honnibal** [comment]
I think your pip and your python might be pointing to different installations. If you do `python -m pip` instead of `pip` you might see more consistent results. Not sure!
