### ISSUE TITLE
Import spacy gives ImportError for click.exceptions (typer)

### ISSUE THREAD

**Issue by demongolem-biz** [explosion/spaCy#8309]
## How to reproduce the behaviour

`import spacy`

## Your Environment

* Operating System: RHEL 7.6
* Python Version Used: 3.6
* spaCy Version Used: 3.0.6
* Environment Information: VirtualBox VM

```
Stack trace is as follows:
Traceback (most recent call last):
  File "/home/brick/eclipse-workspace/NeuralCorefWork/Trial1.py", line 3, in <module>
    import spacy
  File "/home/brick/.local/lib/python3.6/site-packages/spacy/__init__.py", line 14, in <module>
    from .cli.info import info  # noqa: F401
  File "/home/brick/.local/lib/python3.6/site-packages/spacy/cli/__init__.py", line 3, in <module>
    from ._util import app, setup_cli  # noqa: F401
  File "/home/brick/.local/lib/python3.6/site-packages/spacy/cli/_util.py", line 8, in <module>
    import typer
  File "/home/brick/.local/lib/python3.6/site-packages/typer/__init__.py", line 7, in <module>
    from click.exceptions import Exit as Exit
ImportError: cannot import name 'Exit'
```

**Comment by polm** [comment]
What is your typer/click version? Please give the whole output of `pip freeze` so we can check versions of things. Also, how did you install spaCy? 

I was able to get a typer-related error by using the latest click version, but using the latest version required by typer - which is what is normally installed when installing spaCy - works fine.

**Comment by ygorg** [comment]
## How to reproduce the behaviour

`python -m spacy download en_core_web_sm`

## Your Environment
    Operating System: Ubuntu 16.04.6 LTS
    Python Version Used: 3.7.1
    spaCy Version Used: 3.0.6
    pip Version Used: 20.1.1
    click Version installed automatically: 8.0.1
    Environment Information: Travis CI

<details>
  <summary>ModuleNotFoundError: No module named 'click._bashcomplete'</summary>

```bash
Traceback (most recent call last):
  File "/opt/python/3.7.1/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/python/3.7.1/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/python/3.7.1/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/spacy/__init__.py", line 14, in <module>
    from .cli.info import info  # noqa: F401
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/spacy/cli/__init__.py", line 3, in <module>
    from ._util import app, setup_cli  # noqa: F401
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/spacy/cli/_util.py", line 8, in <module>
    import typer
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/typer/__init__.py", line 29, in <module>
    from .main import Typer as Typer
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/typer/main.py", line 11, in <module>
    from .completion import get_completion_inspect_parameters
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/typer/completion.py", line 10, in <module>
    import click._bashcomplete
ModuleNotFoundError: No module named 'click._bashcomplete'
```
</details>

The package to install are : `python -m pip install six spacy nltk networkx numpy scipy scikit-learn unidecode future joblib`

Here is a [pastebin](https://pastebin.com/2PnyGCiu) of the Travis python setup.
Interesting extract of the pastebin:
`ERROR: typer 0.3.2 has requirement click<7.2.0,>=7.1.1, but you'll have click 8.0.1 which is incompatible.` 

## On my local computer (clean virtualenv)
    Operating System: Ubuntu 18.04.5
    Python Version Used: 3.7.5
    spaCy Version Used: 3.0.6
    pip Version Used: 21.0.1
    click Version installed automatically: 7.1.2
    Environment Information: Travis CI

It first collects click v8.0.1 and then collects click v7.1.2.
With click v8.0.1 it does not work, but with 7.1.2 everything is smooth.

*I wonder why OP and my Travis install click v8.0.1 instead of v7.1.2 like on my computer.*
I think maybe the new way pip deals with requirements might be what causes this problem.

**Comment by polm** [comment]
OK, this is happening because you're installing nltk at the same time and it either specify the most recent version or doesn't do version pegging, and pip decides to install that version for whatever reason. 

This should go away if you manually peg the click version. Because this is caused by an interaction with other packages there's nothing we can do on our end to fix it.

**Comment by polm** [comment]
Wait, to clarify, are you (@ygorg and @demongolem) the same person?

**Comment by ygorg** [comment]
@polm No, I am not the same person as demongolem. I ran into the same problem and wanted to add more info about this issue.
Thanks for the explanation !

**Comment by polm** [comment]
Thanks for the clarification. Since the error output is not exactly the same I'm not 100% sure this is the same error, though it seems likely it's related to the click version. @demongolem-biz If this doesn't resolve your issue please let me know, but I'm marking this resolved for now. 

(Also apologies to `@demongolem` if you are a different person from `@demongolem-biz`!)

**Comment by demongolem** [comment]
demonology and demongolem-biz are the same person, in different contexts.

For me click 6.x was what was installed and so that is the source of the
error.  The explanation is plausible in that other products requiring a
different version of click likely did it.

I know the advice to create a new environment at the start of the process,
but I generally like to minimize the number of environments I have.
