### ISSUE TITLE
SpaCy ignoring negative-samples/documents during NER gold standard evaluation

### ISSUE THREAD

**Issue by ankush91** [explosion/spaCy#8418]
## How to reproduce the behaviour
SpaCy is ignoring negative samples/documents for NER evaluation. This is happening during training while evaluating on a dev dataset as well as while calling the `Language.evaluate()` method on a set of gold standard `Example` objects. This might be the issue within the src that I am facing: https://github.com/explosion/spaCy/blob/e796aab4b30283a1cb3b54a0e83f41cc7b198eba/spacy/scorer.py#L714

I trained an NER model which has a number of documents (without the target entity) containing numeric strings like percents/monetary etc. and they do not correspond to the specific target entity (it's a specific type of domain-specific rate that I am trying to model). I wrote a custom evaluation script and verified that model isn't doing well in terms of precision (because of the higher false positives), however the spaCy `Scorer` gives it a high precision (and f1) because it ignores all the negative samples/documents for purposes of evaluation. This functionality is also important while choosing the `best` model (created in `model-best` using `spacy train..`). Are there any workarounds to include negative samples for evaluation?

## Your Environment
- **spaCy version:** 3.0.6
- **Platform:** Darwin-18.7.0-x86_64-i386-64bit
- **Python version:** 3.7.7
- **Pipelines:** en_core_web_lg (3.0.0), en_core_web_trf (3.0.0)

**Comment by adrianeboyd** [comment]
Hi, can you show how you created your training docs, in particular the ones without entities?

The token `ENT_IOB` attribute has four possible values: unset, `I`, `O`, and `B`, and by default it's unset. That line in the evaluation should only ignore documents with unset annotation, since this indicates that we don't know whether the doc has entities or not. If you know that it doesn't contain entities, the tokens should all be `O` instead. If you set `doc.ents = spans`, then any tokens that aren't in the provided spans are set to `O`. `doc.set_ents` gives you more control about how tokens outside the list of provided spans are handled, which allows you to also mark spans as unset or add an entity without modifying any surrounding tokens.

When you're creating a doc, you can use `doc.ents = []` to set all tokens to `O`.

**Comment by ankush91** [comment]
@adrianeboyd : this was my process to create spacy docbins and train using the cmd line with the cfg file (unannotated docs had empty lists passed as below) - 
```
db = DocBin()
......
ents = {'entities': []}
 annot_doc = Example.from_dict(doc, ents)
 db.add(annot_doc.reference)
......
```

I verified and it contains all 0 for token-level `ent_tok` attrs. of documents without the target entities. These documents also result in `has_annotation('ENT_IOB')` to `False`. I basically do not wish to ignore these documents either during training or evaluation. Am I missing something?  

If this isn't intended behavior, then this code block is where I thought the issue is. If this is intentional, then let me know how to proceed - https://github.com/explosion/spaCy/blob/e796aab4b30283a1cb3b54a0e83f41cc7b198eba/spacy/scorer.py#L714

**Comment by adrianeboyd** [comment]
That looks like a bug in `Example.from_dict`, which looks like it's skipping the empty list instead of setting `O`. We will have a look!

As a workaround in the meanwhile, you can try adding `example.reference.ents = []` and see if this training data works like you expect?

**Comment by ankush91** [comment]
@adrianeboyd - yeah I can check if this helps in the meantime.

**Comment by ankush91** [comment]
Hi @adrianeboyd - This definitely helped, I am getting matching scores now, thank you! So it's most likely the bug you mentioned.

**Comment by adrianeboyd** [comment]
Thanks again for the report, that is a pretty bad bug! The fix is in the PR linked above and should be in the next release.
