### ISSUE TITLE
Update constraints on pydantic

### ISSUE THREAD

**Issue by Ierezell** [explosion/spaCy#8428]
Update the pydantic constraint as the next version will allow specifying config in a pyproject.toml

Spacy having a requirement under next version it will be impossible to use spacy and the new pydantic (pyproject compatible) version.
Note : here is the pydantic PR for that : https://github.com/samuelcolvin/pydantic/issues/2895

## Your Environment

- **spaCy version:** 3.0.6
- **Platform:** Linux-5.12.10-arch1-1-x86_64-with-glibc2.33
- **Python version:** 3.9.5
- **Pipelines:** en_core_web_lg (3.0.0), en_core_web_sm (3.0.0), en_core_web_trf (3.0.0)

Thanks in advance, 
Have a great day

**Comment by adrianeboyd** [comment]
Hi, I'm not 100% sure I understand what you're asking. It sounds like you're concerned that the current pydantic requirement `<1.9.0` will prevent you from using the next version in the future?

Or are you running into bugs with the most recent version of pydantic (1.8.2)?

In general, we prefer to keep relatively tight upper pins because minor version updates do often lead to incompatibilities, and we'd rather test new versions internally first so that users don't run into as many problems, and once we've confirmed that everything works, we'll extend the version range in the next patch release.

**Comment by espdev** [comment]
@adrianeboyd 

Currently, the current version of SpaCy in PyPI (3.0.6) has the following constraints for pydantic: `pydantic>=1.7.1,<1.8.0`

I also cannot use the version in my Poetry based project. I'm getting `SolverProblemError` when I'm trying to add SpaCy via poetry because my project already depends on pydantic `^1.8.1`.

Could you say when do you plan to make a release with pydantic constraints `<1.9.0`?

**Comment by adrianeboyd** [comment]
Ah, sorry, I was looking at the constraints in `master` for the next version (v3.1.0) which are `pydantic>=1.7.4,!=1.8,!=1.8.1,<1.9.0`. We are working on the final details for this release right now. No promises, but my guess would be within a week or so.

There will also be a patch release to v3.0 as v3.0.7 with similar constraints, but the schedule for that is less clear at this point.

(I'm still a bit confused about the link to the open PR in pydantic?)

**Comment by Ierezell** [comment]
Hi @adrianeboyd, thanks for the reply ! 

It's perfect to know that it will change (and improve). 

I will wait for the new version and will be able to use pydantic in mypy. 

The problem in the open PR is that : 

People want to use mypy to have typings hints etc...
Pydantic have a module to integrate in mypy and give pydantic typings. 
Pydantic need a configuration to be included in mypy.
Mypy is able to use `pyproject.toml` for it's configuration. 

Pydantic was not able to parse `pyproject.toml` to have the config at the same place. 
So people made a PR to fix this and have all the config at one place. 
Which lead to this PR because the new PR in pydantic will increase version which will be higher than spacy requirements. 

(hope it's clear as explanation, don't hesitate to tell me if it was not)

Have a great day
