### ISSUE TITLE
New 'easy' label for issues

### ISSUE THREAD

**Issue by bhargavvader** [explosion/spaCy#844]
Wondering if @ines and @honnibal could help introduce an 'easy' or 'beginner' label for issues. Would be useful for students (like me, and others) to start hacking away with whatever little contributions possible. I can imagine this would also save some time while you guys deal with the more pressing issues!

**Comment by ines** [comment]
Sure, that's a good idea! We currently only have a [`help wanted`](https://github.com/explosion/spaCy/labels/help%20wanted) label, but we've mostly been using that for more complex feature requests.

Just created [`help wanted (easy)`](https://github.com/explosion/spaCy/labels/help%20wanted%20%28easy%29) (I thought mentioning "help wanted" in the tag might be nice, just to make it clear that it means "easy for others who want to help", rather than just easy for us to fix or something). We're currently working on another pre-v2.0 bug fix release anyways, so this is actually a good time to go through the outstanding issues and tag the "easy" ones.

Thanks for taking the initiative on this btw – helping people (especially students and beginners) contribute has always been important to us, so it's great to have some input on how to make this easier. (And I'm happy to see our little community growing so much over the past couple of months 😊 )

**Comment by ines** [comment]
Just updated the [`help wanted (easy)`](https://github.com/explosion/spaCy/labels/help%20wanted%20%28easy%29) label with some outstanding issues, and also added a note about this to the [contributing guidelines](https://github.com/explosion/spaCy/blob/master/CONTRIBUTING.md#contributing-to-the-code-base). Will keep adding more issues over the next couple of weeks!

Let us know if the contribution scope is okay and if the descriptions are sufficient, or if there's anything else that should be explained or included to make it easier to contribute.
