### ISSUE TITLE
ModuleNotFoundError: No module named 'spacy.lemmatizer'

### ISSUE THREAD

**Issue by saipavanmeruga** [explosion/spaCy#8460]
## How to reproduce the behaviour

```
      4 import spacy
      5 from spacy.lang.en.stop_words import STOP_WORDS
----> 6 from spacy.lemmatizer import Lemmatizer
      7 from spacy.lookups import Lookups
      8 from cosine_similarity import calculate_cosine_similarity
```
## Your Environment

* Operating System: Windows 10
* Python Version Used:Python 3.9.5
* spaCy Version Used: spacy v3.0.6

**Comment by adrianeboyd** [comment]
It's hard to know for sure without more details, but this code was probably written for spacy v2. You can install the most recent version of v2 with `pip install spacy==2.3.7`. It's usually best to install this in a new virtual environment because pip sometimes doesn't upgrade/downgrade all the dependencies cleanly.

**Comment by adrianeboyd** [comment]
Let me convert this to a discussion since I don't think it's a bug in spacy. This issue will be locked but you can follow the link to the new discussion thread.
