### ISSUE TITLE
matcher doesn't match with '*' operator and Boolean flag

### ISSUE THREAD

**Issue by jmugan** [explosion/spaCy#850]
I want to match anything where 'frank' follows 'bob'; e.g., 'bob and and and cat frank'.

    IS_ANY_TOKEN = matcher.vocab.add_flag(lambda x: True)
    matcher.add_pattern("FarAway",[{LOWER: "bob"},{'OP': '*', IS_ANY_TOKEN: True},{LOWER: 'frank'}])

This code does not match 'bob and and and cat frank'.

`IS_ANY_TOKEN` works for one token if I don't use the `+` or `*` operator. It does kind of work for the `?` operator.

For example 
`matcher.add_pattern("FarAway",[{LOWER: "bob"},{'OP': '?',IS_ANY_TOKEN: True},{LOWER:'frank'}])`
matches 'bob and frank' but not 'bob frank'.

Is this a bug or is there something obvious I am doing wrong?

## Your Environment

* Operating System: mac
* Python Version Used: 2.7
* spaCy Version Used: 1.1.2
* Environment Information:

**Comment by honnibal** [comment]
Hi,

Try the more recent version --- 1.6.0. Issue #766 might be relevant here though.

Thanks,
Matt

**Comment by jmugan** [comment]
Upgrading to 1.6.0 didn't fix it. I get the same behavior.

**Comment by honnibal** [comment]
Confirmed --- thanks for giving a test case; added it as a regression.

The bug is triggered because your variable-length pattern matches the next token as well. I implemented the matcher in a fairly hacky way, instead of as a proper DFA. This bug is a symptom of that: I'm not handling the ambiguity properly here.

I'll have a think about what to do. If I can't fix this quickly i can at least add a mitigation, that checks whether user patterns are subject to this problem.

**Comment by honnibal** [comment]
Difficult case to handle with the current code.

The code currently works like this:

* Start with a list of potential patterns, an empty queue of open patterns, and an empty list of matches.
1. For each token:
1.1 For each open pattern,
1.1.1 Choose an action, apply it.  
1.2 Check each potential pattern. Add matches to the open patterns.

Currently the `*` operator triggers the `REPEAT` action, which keeps the pattern in the queue, at the same position. This way, we'll check the same again on the next token in the document. This is wrong: we need to keep it on the queue, but we also need to open another option. None of the other actions cause this to happen, and I didn't think of this case ahead of time.

There are a few fixes that could be applied here, and in the short term none of them seem terribly complicated. But I'm hesitating a bit, because it feels like we're in a hole here, and it might not be smart to keep digging. It might be better to redesign this, instead of programming our way out of the immediate problem.

**Comment by honnibal** [comment]
Moving discussion to #864
