### ISSUE TITLE
Support tokenize with pos tagging

### ISSUE THREAD

**Issue by eromoe** [explosion/spaCy#854]
Since many Chinese tokenizers need tag pos in order to cut a sentence, they usually have method

1. just cut sentence and return tokens
2. cut sentence  and return tokens with pos tags.

But from https://spacy.io/docs/api/tagger
> Annotate part-of-speech tags on Doc objects.

So current approach have to split the work in two pieces, it means do twice same work with Chinese Tokenizer , which is very unefficient and redundant.

**Comment by honnibal** [comment]
Hey,

I've thought about this a bit too. I think for Chinese the best approach will be to "tokenize" into a sequence of characters. This is a sort of null tokenization strategy, that you would create a little class for yourself. Then you would learn tags that jointly encode the POS and the word boundaries. You might want to use the entity recogniser class for this, since the task is fundamentally similar. Alternatively you can just use the tagger class, and manage the begin/middle/outside book-keeping yourself.

Another strategy is to do joint POS tagging, segmentation and parsing. You could do that by transforming the treebank annotations, so that instead of words as leaves, you have single characters. You would pick either the leftmost or the rightmost character as the head of the word, and then attach the other characters to that head character. Then you can learn this new tree with the existing dependency parser.

Either way, after you've learned the word boundaries, you probably want to merge the multi-character tokens. There's an open issue to be aware of on this: currently the merge operation is quadratic in the length of the document. We need another implementation that does batch merge operations.

Hope that helps,
Matt

**Comment by eromoe** [comment]
@honnibal 
Thank you ,

I am tring to train the  POS tagger with this example https://github.com/explosion/spaCy/blob/master/examples/training/train_tagger.py . I collect 30000 articles, and use `thulac(a Chinese tokenizer)` to cut all of them into "sequence of words with pos tag", then use spacy training.  Is this way OK? (PS: dump model seems has some trouble when model is very large, it dumps nothing when training finish, but if  I just train 100 article it works... I will test more.)

But if `tokenize" into a  sequence of characters` , how do I learn tags that jointly encode the POS and the word boundaries? I am not an expert in NLP, I think the tokenizer is very important in Chinese (though I know deep learning can cope with sequence of characters, but the performance and F1 score are still lower than crf.  ). Currently, all the Chinese tokenizers I seen are using crf to train model, because crf has the best F1. And they already contain POS tagging feature, in the main article I just wonder why can't we just embed that.

**Comment by ines** [comment]
Merging this with #2011! 🎉
