### ISSUE TITLE
Loading a vocabulary where the strings store has been removed fails if it is not excluded

### ISSUE THREAD

**Issue by qthurier** [explosion/spaCy#8819]
I've trained an NER model using the CLI, but I don't want the model artefacts to contain any string extracted from the training dataset. To circumvent this I'd like to load the model and attach to it a vocabulary that doesn't contain the strings store. Using the parameter _vocab_ in the _load_ method won't work unless the vocabulary is specifically excluded see "How to reproduce the behavior".

On top of that I've 2 questions:

- Is it the intended way to do this?
- Is _strings.json_ the only file that contains strings in the artefacts saved by the CLI?

## How to reproduce the behaviour
This would raise on error:
```
import spacy
vc = spacy.vocab.Vocab().from_disk("src/slimcontacts/artefacts/vocab", exclude=['strings'])
model = spacy.load("src/slimcontacts/artefacts", vocab=vc)
```

This wouldn't:
```
import spacy
vc = spacy.vocab.Vocab().from_disk("src/slimcontacts/artefacts/vocab", exclude=['strings'])
model = spacy.load("src/slimcontacts/artefacts", exclude=['vocab'], vocab=vc)
```

## Your Environment
* Operating System: Ubuntu
* Python Version Used: 3.7.9
* spaCy Version Used: 3.1.1

**Comment by adrianeboyd** [comment]
It does look like there are some bugs related to not passing `exclude` to the vocab in serialization, but I can't reproduce an error with the code above. This doesn't do what you want (in several aspects), but it runs without errors for me:

```python
import spacy
nlp = spacy.load("en_core_web_sm")
nlp.to_disk("tmp_model_dir")
vocab = spacy.vocab.Vocab().from_disk("tmp_model_dir", exclude=['strings'])
model = spacy.load("tmp_model_dir", vocab=vocab)
```

The main issues are:

* You almost never want to initialize a vocab with `Vocab()` because it will be missing a lot of language-specific settings. Instead:
   ```python
   nlp = spacy.blank("en") # or nlp = English() or whatever language
   vocab = nlp.vocab
   # do stuff
   ```
* I think the intended workflow would be more like:
   ```python
   model = spacy.load("tmp_model_dir", vocab=vocab, exclude=["strings"])
   ```
   Unless you exclude them, it would be expected that the strings from `tmp_model_dir` are loaded into the provided vocab.
* Be aware that pipeline components in general are allowed to assume that labels that have been added to the `StringStore` previously will be there in the future. I think all the built-in components in the core library re-add their labels if necessary just in case, but you might run into errors with custom components. A related comment: https://github.com/explosion/spaCy/discussions/7794#discussioncomment-692092

I think the easiest workaround is to replace `strings.json` with an empty list (`[]`) in the directory you're loading from. If you want to do it programmatically, then I think this the easiest approach currently:

```python
import spacy
blank_nlp = spacy.blank("en")
nlp = spacy.load("en_core_web_md")
# save the existing vocab and lookups
lookups = nlp.vocab.lookups
vectors = nlp.vocab.vectors
# overwrite the vocab with a blank vocab
nlp.vocab = blank_nlp.vocab
# restore the original lookups and vectors
nlp.vocab.lookups = lookups
nlp.vocab.vectors = vectors
```

If we fix the bugs with exclude, then I think the idea is that this would work:

```python
nlp.to_disk("model_dir", exclude=["strings"])
nlp = spacy.load("model_dir", exclude=["strings"])
```

You would also have to exclude the strings on load because otherwise there's an error if `strings.json` is missing.

This would also work, but contain the strings in the saved path:

```python
nlp.to_disk("model_dir")
nlp = spacy.load("model_dir", exclude=["strings"])
```
