### ISSUE TITLE
Minor: A strange morphological feature value in EN model?

### ISSUE THREAD

**Issue by xsway** [explosion/spaCy#8852]
## How to reproduce the behaviour
```
>> [w.morph for w in nlp('From the AP comes this story:')]

[,
 Definite=Def|PronType=Art,
 NounType=Prop|Number=Sing,
 Number=Sing|Person=Three|Tense=Pres|VerbForm=Fin,
 Number=Sing|PronType=Dem,
 Number=Sing,
 ]
```

It's a minor thing, but **Person=Three** is not a feature value I have seen in UD English treebanks - it's not listed in acceptable values in annotation guidelines https://universaldependencies.org/u/feat/Person.html. Normally it's **Person=3**, as in below:

```
>> [w.morph for w in nlp('He is here')]

[Case=Nom|Gender=Masc|Number=Sing|Person=3|PronType=Prs,
 Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin,
 PronType=Dem]
```

Is it an issue or these annotations come from some other source? Thanks for clarifying!

## Your Environment
en_core_web_sm model
* Operating System: MacOS Apple M1
* Python Version Used: 3.9
* spaCy Version Used: 3.0.6
* Environment Information: conda installation

**Comment by adrianeboyd** [comment]
Thanks for the report, that's a mistake in the `attribute_ruler` patterns. We can get it fixed in the next release of the `en` models. If you want to fix it locally, you can update this pattern in the `attribute_ruler`:

```json
  {
    "patterns":[
      [
        {
          "TAG":"VBZ"
        }
      ]
    ],
    "attrs":{
      "POS":"VERB",
      "MORPH":"Number=Sing|Person=Three|Tense=Pres|VerbForm=Fin"
    },
    "index":0
  }
```

An early version of the morphological features in spaCy v2 used `One/Two/Three` instead of `1/2/3` to avoid confusion between the `int`/`str` types, but in v3 we switched to all UD values (although you can use arbitrary features and values in general). This case was missed when the English morphological rules were imported from v2 into v3.

**Comment by xsway** [comment]
I see, thanks for the detailed explanation! I can adapt the code on my side, it's a minor thing. I just thought it looked funny and decided to report, I'm glad if it was useful :)

**Comment by adrianeboyd** [comment]
I've fixed this in our internal training repo, so it should be fixed in the next model releases. Thanks again for the report!
