### ISSUE TITLE
Should "/" not be a separate token and cause a split?

### ISSUE THREAD

**Issue by kootenpv** [explosion/spaCy#891]
```python
In [32]: [x for x in nlp("I want/need something")]
Out[32]: [I, want/need, something]
```

Perhaps you're thinking of more common cases where it shouldn't be split? I'd almost think you should make "/" to be a `conj`.

**Comment by ines** [comment]
Thanks – and that's weird, I totally would have thought that this was already split correctly. Just added a regression test and played around with this quickly – it might be as simply as just adding the `/` character [here](https://github.com/explosion/spaCy/blob/master/spacy/language_data/punctuation.py#L110).

But we need to make sure to test this properly and make sure it doesn't break any of the tokenizers that rely on the default punctuation.

**Comment by ines** [comment]
All worked as expected and the fix will be included in the next point release. The likely reason why `/` was excluded in the past was because we didn't have a good way of protecting URLs – since we introduced `token_match` and regex patterns for URLs, this is no problem anymore and `/` can be included in the infixes.
