### ISSUE TITLE
French tokenization - iconsistent application of exceptions in FR_BASE_EXCEPTIONS & other unexpected tokenization

### ISSUE THREAD

**Issue by e-nesse** [explosion/spaCy#8916]
Two possibly related issues: 
1. Tokenization exceptions in spacy/lang/fr/_tokenization_exceptions_list.py -> FR_BASE_EXCEPTIONS are not applied and/or are applied inconsistently, sometimes seeming to depend on upper/lower case
2. French tokenization produces inconsistent and unexpected results with inverted constructions (est-ce vs c'est)

Always possible that I have fundamentally misunderstood something in how spaCy works, apologies if that's the case.

```
import spacy
nlp = spacy.load('fr_dep_news_trf')
```

1. 'monte-plat' and 'là-bas': tokenization exceptions not applied:
```
test_1 = nlp('Regarde le monte-plat là-bas.')
[t.text for t in test_1]
```
Expected output of test_1: ['Regarde', 'le', 'monte-plat', 'là-bas', '.']
Actual output of test_1: ['Regarde', 'le', 'monte', '-', 'plat', 'là', '-', 'bas', '.']

2. 'peut-être' vs. 'Peut-être', ['-', 'ce'] vs '-ce' - tokenization exception not applied if case differs, also unexpected tokenization of an inversion:
```
test_2 = nlp('C'est peut-être un chat.')
test_3 = nlp('C'est Peut-être un chat.') (note improper capital P)
test_4 = nlp('Peut-être est-ce un chat.')
print([t.text for t in test_1])
print([t.text for t in test_2])
```
Expected output of test_2: ['C'', 'est', 'peut-être', 'un', 'chat', '.'] (tokenization exception should see 'peut-être' as one token)
Actual output of test_2: ['C'', 'est', 'peut-être', 'un', 'chat', '.'] (success)

Expected output of test_3: ['C'', 'est', 'Peut-être', 'un', 'chat', '.'] 
Actual output of test_3: ['C'', 'est', 'Peut', '-', 'être', 'un', 'chat', '.'] (tokenization rule not applied if case differs)

Expected output of test_4: ['Peut-être', 'est', '-', 'ce', 'un', 'chat', '.']
Actual output of test_4: ['Peut', '-', 'être', 'est', '-ce', 'un', 'chat', '.'] (tokenizer does not split 'est', '-', 'ce' correctly on hyphen (here, inversion marker))

This happens with several exceptions from spacy/lang/fr/_tokenization_exceptions_list.py that I tried, but is not consistent in all cases. Sometimes, text containing 'Anne-marie' rather than 'Anne-Marie' will be tokenized as ['Anne', '-', 'marie'].

Additionally, the exceptions that contain spaces, such as a number of city names - 'Les Ormes-sur-Voulize' etc. - are tokenized as two tokens rather than one: 'Les' (DET) and 'Ormes-sur-Voulize' (PROPN) - Perhaps this is to be expected if the text is split on whitespaces before tokenization exceptions are applied... In which case, any tokenization exceptions containing a space may not work as expected, i.e. 'Les Ormes-sur-Voulize' as one token rather than two.

The consequences of these issues are particularly devastating for any statistics on part-of-speech types, since these patterns in tokenization lead to misleading tagging, e.g. 'peut-être' tokenized as ['peut', '-', 'être'] often results in all three tokens (including '-') being assigned .pos_ of 'ADV', so any script that counts adverbs in a document will return inflated numbers; and tokenizing 'est-ce' as ['est', '-ce'] results in lemmatization of '-ce' as '-ce' (rather than 'ce'), etc.

## Your Environment
- **spaCy version:** 3.1.1
- **Platform:** Windows-10-10.0.19041-SP0
- **Python version:** 3.8.8
- **Pipelines:** fr_dep_news_trf (3.1.0)

**Comment by adrianeboyd** [comment]
Hi, rule-based French tokenization of hyphens (without any information beyond the token forms at the tokenization stage) is definitely very difficult to do well.

I think the misunderstanding here is that the rules from `_tokenizer_exceptions_list` are not used in the default French pipelines because they are slow:

https://github.com/explosion/spaCy/blob/a1e9f1946022112f7cd3c4c566691c5117a22850/spacy/lang/fr/tokenizer_exceptions.py#L10-L12

You can see if adding them improves the performance for your task, however you would probably want to retrain the model from scratch if the differences are large because the pipeline will not perform well on tokens and token sequences it's never seen before. You'd have to compare the performance on your task to see how well it works to use the existing `fr_dep_news_trf` model on the modified tokenization.

Something like the statistical tokenizer from `stanza` might be a better alternative, although also much slower.

**Comment by adrianeboyd** [comment]
Since I don't think this is directly a bug, let me move this to the discussion board...
