### ISSUE TITLE
OOM and Unreleased GPU Memory 

### ISSUE THREAD

**Issue by ericmclachlan** [explosion/spaCy#8984]
It seems to be incredibly difficult to manage GPU utility when using language models on GPU.

## How to reproduce:

```
import spacy
import time

models = [
    'en_core_web_lg',
    #'de_core_news_lg',
]

i = 0
while True:
    spacy.prefer_gpu()
    nlp = spacy.load(models[i % len(models)])
    print('.')
    time.sleep(1)
    del nlp
    i += 1
```

## Error 1: Unreleased GPU memory

Running the above program will load the English language model into GPU multiple times [it seems]. Running this will eventually consume 6498MiB /  8129MiB of GPU RAM [as reported by nvidia-smi]. And that's just loading the models.

Counterintuitively, if you uncomment the German model in the list, memory consumption will stabilize at 2156MiB /  8129MiB.

Using del, gc.collect(), and torch.cuda.empty_cache() doesn't seem to release the memory.

## Error 2: Out of Memory Errors

For my use case, I'm trying to use a lot of language models but I'm unable to swap models out due to out-of-memory (OOM) errors thrown when the GPU memory gets full. I think the abovementioned bloating of GPU memory means that if we get a batch containing any significant size (10K), it can cause an OOM error.

---
I suspect both these errors are symptoms of the same underlying problem, which is why I've only reported one issue.

The silver bullet solution for me is for you to tell me, "Read the documentation and you'll see you can free GPU memory using [insert special] command."

Failing that, I'm running out of ideas about how to use spaCy for more than a handful of languages. Your help would be very much appreciated.

## Your Environment

Output from `python -m spacy info --markdown`:

- **spaCy version:** 3.1.0
- **Platform:** Linux-5.4.0-1055-azure-x86_64-with-glibc2.27
- **Python version:** 3.8.0
- **Pipelines:** de_dep_news_trf (3.1.0), ca_core_news_lg (3.1.0), pt_core_news_lg (3.1.0), pl_core_news_md (3.1.0), pt_core_news_sm (3.1.0), ro_core_news_sm (3.1.0), lt_core_news_lg (3.1.0), ru_core_news_lg (3.1.0), ro_core_news_lg (3.1.0), fr_dep_news_trf (3.1.0), es_core_news_lg (3.1.0), es_dep_news_trf (3.1.0), nl_core_news_lg (3.1.0), ja_core_news_sm (3.1.0), it_core_news_lg (3.1.0), el_core_news_sm (3.1.0), mk_core_news_lg (3.1.0), fr_core_news_sm (3.1.0), da_core_news_lg (3.1.0), en_core_web_trf (3.1.0), de_core_news_lg (3.1.0), nb_core_news_sm (3.1.0), nb_core_news_lg (3.1.0), nl_core_news_sm (3.1.0), ja_core_news_lg (3.1.0), fr_core_news_lg (3.1.0), en_core_web_sm (3.1.0), zh_core_web_lg (3.1.0), el_core_news_lg (3.1.0), it_core_news_sm (3.1.0), lt_core_news_sm (3.1.0), en_core_web_lg (3.1.0), ca_core_news_trf (3.1.0), da_core_news_trf (3.1.0), pl_core_news_sm (3.1.0), zh_core_web_trf (3.1.0)

**Comment by adrianeboyd** [comment]
It is definitely the case that you have to do some management in terms of batch size and text length to successfully run the models on GPU, and this can definitely be frustrating. The `parser` and `ner` components in particular do not scale linearly in terms of memory use vs. text length. Some batches or texts will simply be too large to process no matter what else you do. Splitting up long texts to keep texts under a known maximum length can really help overall since it evens out of the memory usage per batch and you can figure out a good batch size for your GPU + pipeline + texts.

The info here about cupy and the warning about `nvidia-smi` are relevant: https://docs.cupy.dev/en/stable/user_guide/memory.html

You can use `cupy` functions to see a few more details about what's going on with the memory pool:

```python
import spacy
import time
import cupy

spacy.prefer_gpu()

models = [
    'en_core_web_lg',
    'de_core_news_lg',
]

mempool = cupy.get_default_memory_pool()

i = 0
while True:
    print(mempool.used_bytes(), mempool.total_bytes())
    nlp = spacy.load(models[i % len(models)])
    print('.')
    time.sleep(1)
    del nlp
    i += 1
```

You can free memory in cupy with `mempool.free_all_blocks()` in order to see the effects in `nvidia-smi`, but with cupy-only usage (not also with `trf` models), this will probably only have the effect of being slower than letting cupy manage memory itself.

If you're switching back and forth between cupy-only (`sm/md/lg`) and `trf` models (cupy + torch), you might be running into issues because torch and cupy aren't sharing memory pools by default. The gpu allocator is usually set to `"pytorch"` during training as the default, but it looks like it's not set by default when you just run a pipeline. I'm not entirely sure this will make a difference, but you can see if this helps:

```python
from thinc.api import set_gpu_allocator

set_gpu_allocator("pytorch")
```

And then in this setup you'd need to use torch's memory utils to profile what's going on: https://pytorch.org/docs/stable/notes/cuda.html#cuda-memory-management. Again, if you find yourself manually freeing memory, it usually means something else is going wrong because the default memory management should work as long as no individual batch gets too large to process. With torch you also won't see memory being freed in `nvidia-smi` until it gets close to its memory limits.

**Comment by ericmclachlan** [comment]
Thanks for the detailed reply, @adrianeboyd. I'm gonna pour over this for a while and get back to you. I appreciate the thoughtful reply.

**Comment by ericmclachlan** [comment]
Thank you, @adrianeboyd, for your response. Sometimes, knowing what is the problem is _**not**_ is half-way to finding a solution. 

As it turns out, I had a cache mapping my input text to `doc` objects. This was to reduce the load of having to analyze a text more than once. As it turns out, the cached docs somehow prevented the freeing up of GPU resources. Once I removed the cache, it seems the GPU memory was deallocated successfully.

If you feel inclined to elaborate why this might be, I am curious. But I also understand if you have better things to do with your time.

SpaCy-team: You all rock! Seriously. You have made an incredible product.

**Comment by adrianeboyd** [comment]
That issue is explained here: https://github.com/explosion/spaCy/issues/7593#issuecomment-828246588

**Comment by ericmclachlan** [comment]
Reporting back to say, this...

```py
from thinc.api import set_gpu_allocator

set_gpu_allocator("pytorch")
```
... made a HUGE difference.

I went from...
```
DEBUG: en: 0Mb / 0Mb (Used/Total)
DEBUG: da: 1104384Mb / 1366528Mb (Used/Total)
DEBUG: de: 1164800Mb / 1999872Mb (Used/Total)
DEBUG: it: 2996736Mb / 5183488Mb (Used/Total)
DEBUG: pt: 614642176Mb / 617754112Mb (Used/Total)
DEBUG: nl: 1214922240Mb / 1218425344Mb (Used/Total)
ERROR: An error occurred while loading SpaCy model: nl_core_news_lg.
Out of memory allocating 600,000,000 bytes (allocated so far: 1,218,425,344 bytes).
```
to
```
DEBUG: en: 0Mb / 0Mb (Used/Total)
DEBUG: de: 0Mb / 0Mb (Used/Total)
DEBUG: pt: 0Mb / 0Mb (Used/Total)
DEBUG: da: 0Mb / 0Mb (Used/Total)
DEBUG: es: 0Mb / 0Mb (Used/Total)
DEBUG: it: 0Mb / 0Mb (Used/Total)
DEBUG: ca: 0Mb / 0Mb (Used/Total)
DEBUG: nl: 0Mb / 0Mb (Used/Total)
DEBUG: ja: 0Mb / 0Mb (Used/Total)
DEBUG: zh: 0Mb / 0Mb (Used/Total)
DEBUG: fr: 0Mb / 0Mb (Used/Total)
DEBUG: el: 0Mb / 0Mb (Used/Total)
DEBUG: mk: 0Mb / 0Mb (Used/Total)
DEBUG: ru: 0Mb / 0Mb (Used/Total)
DEBUG: lt: 0Mb / 0Mb (Used/Total)
DEBUG: ro: 0Mb / 0Mb (Used/Total)
```

**Comment by adrianeboyd** [comment]
Glad to hear it! I think we should add this as a default when `trf` models are loaded, just as we do in training, but I think we'll have to think a little bit about the best way to implement it. It's currently part of the training-only config that's not read at all when you just load a model, so we'll have to think about how to manage the settings.

**Comment by adrianeboyd** [comment]
Another issue would be better, but you can set limits for pytorch: https://pytorch.org/docs/stable/generated/torch.cuda.set_per_process_memory_fraction.html#torch.cuda.set_per_process_memory_fraction

This particular method may not be exactly what you need, but search for the settings that give pytorch overall or per-process memory limits.

**Comment by adrianeboyd** [comment]
It took us a while to get back to this, but we are currently planning to automatically set the pytorch allocator when you load a thinc model that uses `PyTorchShim`: https://github.com/explosion/thinc/pull/598

**Comment by adrianeboyd** [comment]
The pytorch allocator is now set automatically in thinc v8.0.14+.
