### ISSUE TITLE
Language Models Not Loading

### ISSUE THREAD

**Issue by melissa-d** [explosion/spaCy#907]
import spacy is working, but not nlp = spacy.load('en')

**Comment by ines** [comment]
Hey! Could you provide some more info on what exactly is not working and what error messages you see? There are several possible problems / solutions:

1. Have you [downloaded a model](https://spacy.io/docs/usage/models)? By default, spaCy ships without models, so you'll have to download them. For the small English one, it's simply `python -m spacy download en`.

2. Is the model [linked](https://spacy.io/docs/usage/models#usage) to the `en` shortcut? If you use the `spacy download` command, a link will be created automatically that lets you load the model via `spacy.load`. This means that if you've downloaded a model manually or via pip, or via its specific name, you'll have to create a link so spaCy knows which model to load as `en`. For example:

```bash
python -m spacy download en_core_web_md # download medium English model
python -m spacy link en_core_web_md en # link that model to the shortcut 'en'
```

3. Something else, like conflicting models – this depends on the error message you're seeing.

**Comment by melissa-d** [comment]
I don't think I'm getting any error messages - it just won't load.

**Comment by honnibal** [comment]
Could you describe the behaviour in more detail? If there are no error messages, how do you know it isn't loading?

**Comment by honnibal** [comment]
Hmm. We have some debug commands, could you give us the results from:

`python -m spacy info`
`python -m spacy info en`

It sounds to me like your system might be running out of memory? So that's a useful thing to watch as well. Btw the command should be loaded within a minute, so if it's taking longer than that it's definitely hung. Another possibility is that the symlinks have somehow resulted in an infinite loop? I'm not sure how that could happen, or what the result would be if it did.

**Comment by melissa-d** [comment]
Please delete my account and unsubscribe me from these notifications.
