### ISSUE TITLE
error of symbolic link privilege not held when installing en model

### ISSUE THREAD

**Issue by fodkastir** [explosion/spaCy#915]
* Operating System: Win 7
* Python Version Used: 3.5
* spaCy Version Used:  1.7
* Environment Information:
I can download the file successfully, but an error occurred and ended the install process. Any hints for solving the issue. Thanks!!! 
![default](https://cloud.githubusercontent.com/assets/11641418/24278535/c66c41a0-101a-11e7-9741-93f0fc7b696f.PNG)

**Comment by ines** [comment]
Thanks for the report! I just did a quick search for the error message and it looks like it might be caused by [insufficient permissions](http://stackoverflow.com/questions/32877260/privlege-error-trying-to-create-symlink-using-python-on-windows-10). Do you have admin privileges and if not, could you try run `python -m spacy link en_core_web_sm en` as admin? If this doesn't help, this issue might be related to the more general problems with symlinks on Windows (see #909).

In the meantime, you can also import the model as a module and call its `load()` method (this doesn't require any symlinks):

```python
import spacy
import en_core_web_sm  # or any other model you downloaded via spacy download or pip

nlp = en_core_web_sm.load()
```

You could also copy the model data into the `spacy/data` directory, or create a symlink to the model data manually. When you call `spacy.load('model_name')` spaCy will look for folders and symlinks of that name in the `spacy/data` directory.

**Comment by fodkastir** [comment]
Thanks for your help ines.
I ran `python -m spacy link en_core_web_sm en` as admin and everything works now.

**Comment by ines** [comment]
Perfect, I'm glad it worked. Thanks for updating!
