### ISSUE TITLE
Latest versions 1.7+ not on conda yet

### ISSUE THREAD

**Issue by MandarKulkarni40** [explosion/spaCy#923]
Hi

I am trying to install spaCy NLP library on Anaconda python3.
I executed following commands and installed spacy

conda install spacy

I could import the spacy module without any error. However, when i try to download the files for english using following command, 

python -m spacy download en

I get an error

**"ImportError: No module named 'en_core_web_sm'"**

Can you please help me to resolve the issue?

**Comment by ines** [comment]
Sorry – spaCy v1.7 isn't on conda yet, but it's coming soon!

If you've installed spaCy directly from conda, you've actually downloaded the old version (1.6), which doesn't support the new model download commands yet. You can use pip to install spaCy v1.7:

```bash
pip install -U spacy
```

We'll update this thread as soon as the new version is up on conda.

**Comment by ines** [comment]
Merging this with #946 while we're working on fixing this!

**Comment by ines** [comment]
Turns out we got confused by the badge that still shows the old version. v1.7.3 should be up on `conda-forge`. To make sure you're installing the right version, you can also run this command:

```bash
conda install -c conda-forge spacy=1.7.3
```

**Comment by rolando** [comment]
@ines I've opened an issue about the badge not being updated: https://github.com/ContinuumIO/anaconda-issues/issues/1584

**Comment by ines** [comment]
@rolando Thanks a lot! I wasn't 100% sure if this was an Anaconda issue, or whether we were looking in the wrong place or didn't quite understand the setup well enough.

Btw, would this issue tracker also be a good place to ask about deleting / merging / updating the old spaCy distributions? We've sent a support request via email a while ago, but haven't received a response.

Anaconda: https://anaconda.org/anaconda/spacy (still 0.101.0)
Old spaCy org: https://anaconda.org/spacy/spacy (still 0.101.0, and we seem to have deleted the account associated with this, so we can't delete or update it now)

Sorry, I hope we're not bothering you too much with all the Anaconda stuff – but both @honnibal and I don't have much experience with the platform yet.

**Comment by rolando** [comment]
> would this issue tracker also be a good place to ask about deleting / merging / updating the old spaCy distributions?

Yes, but I can't tell whether your request will be attended in a timely manner. I think @jakirkham (from conda-forge) would be able to provide a better insight about how does packages updates work in the default anaconda channel. However, from what I can tell, the default channel does not update non-core packages very often, and I believe that was one of the motivations to start the conda-forge community.

As for the spacy org, unless users explicitly use that channel it won't be a problem. The default `conda search` command searches only in the default anaconda's channel so packages from spacy org won't show up.

If the users follow the instructions to add the `conda-forge` channel or if they have it already set up, `conda` will pick the latest release across all configured channels unless specified otherwise. 

> Sorry, I hope we're not bothering you too much with all the Anaconda stuff 

No problem!

**Comment by jakirkham** [comment]
So I don't know lots of details about how `defaults` works internally, but they do a reasonable job of updating packages in `defaults`. Though you may need to nudge them with an issue to update periodically and it is up to them to schedule and solve this problem internally. However, the inclusion of packages into `defaults` is less clear.

The creation of `conda-forge` was a way around the inclusion problem. Though it also puts the release mechanisms in the hands of developers like yourselves or stakeholders. As a consequence this allows packages to be updated by the community on demand.

Hope that fills the gaps.
