### ISSUE TITLE
n_process > 1 causes pipeline to hang on Windows 7

### ISSUE THREAD

**Issue by Mwni** [explosion/spaCy#9232]
Processing text using `pipe(x, n_process=2)` causes the pipeline to hang. Workers processes are being repeatedly spawned and killed in a ~5 second time frame, but there are no errors. The task works flawlessly if n_process=1. Tried with `en_core_web_lg` and `en_core_web_md`.

SpaCy 3.1.2
Python 3.8
Windows 7

**Comment by adrianeboyd** [comment]
Can you provide more information about the components in your pipeline?

**Comment by Mwni** [comment]
Yes, it ranges from all the default components to everything disabled (excluded) except the `tokenizer` and `sentencizer`.

**Comment by adrianeboyd** [comment]
Hmm, I'm not sure what might be due to Windows 7 here and it's not a version that we can support (or even have access to for testing). From the behavior my first guess is it's running out of memory, but it's really hard to know. If `en_core_web_sm` works and `en_core_web_lg` doesn't, then it might be memory. Have you tried the same thing with a newer version of Windows?

**Comment by Mwni** [comment]
Yeah it does look like it comes down to the OS. I will try later on Linux. The thing that's strange is that it doesn't throw any errors, even though the worker processes clearly fail and get respawned.

**Comment by Mwni** [comment]
Yes this specific bug does not occur on Linux

**Comment by adrianeboyd** [comment]
The only thing I can think of is to make sure you have 64-bit python and not 32-bit python. I thought that spacy v3 would work in theory with 32-bit python, but we don't explicitly test it, so I'm not really sure. spacy v2 definitely doesn't work with 32-bit python.
