### ISSUE TITLE
pipeline multiprocessing still only using a single core

### ISSUE THREAD

**Issue by geoHeil** [explosion/spaCy#926]
## Problem description

Based on https://explosion.ai/blog/multithreading-with-cython and https://github.com/explosion/spaCy/issues/172 I created a small space pipeline to 

- read documents from the file system
- tokenize them in parallel

the pipeline is available here https://github.com/geoHeil/advancedInformationRetrieval/blob/master/project1/concurrentTokenization.ipynb. But I noticed, that at least in my *real* pipeline, only a single core is used. Please tell me if this is a bug in spaCy or with my code and how to concurrently perform this tokenization operation.

```
def iter_and_parse_all_files(p):
    for root, dirs, files in os.walk(p):
        for file in files:
            if not file.startswith('.'):
                print('using: ' + str(os.path.join(root, file)))
                path = os.path.join(root, file)
                text_file = open(path, 'r').read()
                soup = BeautifulSoup(text_file,'html.parser')
                for doc in soup.find_all("doc"):
                    strdoc = doc.docno.string.strip()
                    text_only = str(doc.find_all("text")[0])
                    yield (strdoc, text_only)

token_counter = 0
print('document id: ' + id)
for token in doc_token:
    if token.is_alpha:
        if not token.is_stop:
            if len(token.orth_) > 1:            
                token_counter += 1
token_counter
```

## Info about spaCy

* **spaCy version:** 1.7.2
* **Platform:** Darwin-16.4.0-x86_64-i386-64bit
* **Python version:** 3.6.0
* **Installed models:** en, en_core_web_md
* Operating System:  osx 10.12.3
* Python Version Used: 3.5.3 via conda
* spaCy Version Used:  1.7.2

**Comment by honnibal** [comment]
Only the parser and entity recogniser are currently multi-threaded. Making use of multi-threading requires us to release the GIL around the relevant code, which means it mustn't make any calls into Python.h --- so we can't use any Python objects or call into the Python standard library. This is particularly hard for the tokenizer, because we want to allow the user to provide Python functions in the tokenizer, and we want to allow the user to provide Python callbacks in the vocab.

**Comment by geoHeil** [comment]
Thanks for clarification.
