### ISSUE TITLE
Installed old models cause NER problem in v1.7.3

### ISSUE THREAD

**Issue by faizan86** [explosion/spaCy#931]
Hi,

NER does not work with new English models that were released in v.1.7. Is this  a known issue?  I installed spacy with pip, downloaded and linked the models. However i'm unable to get Named Entities. It was working fine in previous version.How can I fix this?

Operating System: Windows 10 

Python Version Used: 2.7 64 bit

spaCy Version Used: 1.7

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by faizan86** [comment]
Deleting models from older version solved the issue for me.

**Comment by ines** [comment]
Thanks for updating with your solution!

That's interesting – so did it load the old model instead of the new one? And did you link the new model as `en` and loaded it via `spacy.load('en')`? 

I just want to make sure there's no bug here. In theory, [`resolve_model_name`](https://github.com/explosion/spaCy/blob/master/spacy/deprecated.py#L90) should check if there's an old English model installed (if you use `spacy.load('en')` and no `en` link can be found), and then raise a compatibility error.

**Comment by faizan86** [comment]
I linked the new model(50 MB) as en and and loaded it via spacy.load('en'). Doing this did not return entities, just blank screen. 

To avoid any confusion, I decide to use the following approach as i found it much cleaner:

Pip installed new model, and loading the model with:
 
    import en_core_web_sm
    nlp = en_core_web_sm.load()

Now I can extract the entities.
