### ISSUE TITLE
Matcher save added matcher and load them

### ISSUE THREAD

**Issue by vladimircape** [explosion/spaCy#940]
I didn't find possibility to save my matcher

I can add new pattern
> from spacy.matcher import Matcher
> matcher = Matcher(nlp.vocab)
> matcher.add_pattern("HelloWorld", [{LOWER: "hello"}, {IS_PUNCT: True}, {LOWER: "world"}])
 
and I want to save it and load in next use. How to make it? I find Load, but didn't find save

**Comment by honnibal** [comment]
The load method is likely to be deprecated in future.

There's no reason to save and load the matcher...Just reuse whatever method you used to add things to  it.

**Comment by vladimircape** [comment]
I have 10000 words to be matched like name of Funds and i make new entity FUND, and i wrote Flask appliction, Right now i put them to file and load data from file to Spacy Matcher in all request, it will be better to make possibility to make in by Spacy.It will be more faster also

**Comment by jorisdhondt** [comment]
I have a similar request regarding the save & load options for the matcher.  Is this something that could be revisited in the future?  I currently have about 260k new entities & related patterns for biological data.  For various reasons training the NER on these entities is not possible.  For these types of applications a saved matcher state would be interesting.

**Comment by ines** [comment]
@vladimircape @jorisdhondt This should hopefully be much easier in v2.0, using the new `PhraseMatcher`. The phrase matcher takes `Doc` objects instead of token patterns, and allows you to efficiently match large terminology lists. With the new pipeline architecture and extensions API, you could even create your own, simple pipeline component that matches your terms and assigns entity labels. 

v2.0 is currently in alpha, but already available on pip as `spacy-nightly`.

More details and examples:

* [`PhraseMatcher` usage guide](https://alpha.spacy.io/usage/linguistic-features#adding-phrase-patterns)
* [`PhraseMatcher` API docs](https://alpha.spacy.io/api/phrasematcher)
* [Introducing custom pipelines and extensions for spaCy v2.0](https://explosion.ai/blog/spacy-v2-pipelines-extensions) (includes examples of using the `PhraseMatcher` for entities and emoji)
* [Code example of component labelling countries](https://github.com/explosion/spaCy/blob/develop/examples/pipeline/custom_component_countries_api.py) using data from a REST API
* [Code example of component labelling companies](https://github.com/explosion/spaCy/blob/develop/examples/pipeline/custom_component_entities.py) using a custom terminology list
