### ISSUE TITLE
Right way for adding acronyms 

### ISSUE THREAD

**Issue by osoleole** [explosion/spaCy#944]
I work with texts that have a great deal of acronyms. I need to mach them with other texts that can be without acronyms but the meanings are related. I represent acronyms as a sum (or any suitable function) of vectors of words that constitute acronym. For example I have dictionary with many thousand of acronyms: 
{"AAER":[ "Accounting", "and", "Auditing", "Enforcement", "Release"],......}.
I add acronyms into vocabulary, add some flag (for example 63) for them to be True. While processing doc I check this flag for for every word in my doc, and when I meet acronym I check my dictionary to get all words and get a vector from vocabulary for each word in acronym. Maybe there is more elegant and optimal way you could advise me?

**Comment by honnibal** [comment]
Your approach sounds pretty good to me. If you want the `.vector` attribute to "magically" be computed using your custom strategy you could register your function in `doc.user_token_hooks['vector']`. You would add the function that registers this hook to the `nlp.pipeline` attribute.

Another thing you could do is work in the opposite direction: identify phrases as *expansions* of acronyms, and assign them the same word vector as the expansion. You would do this by using the `Matcher` or `PhraseMatcher` class with your dictionary, and then using the `doc.merge()` method to collapse these into  single phrase. You could then assign them the same vector as the acronym. Alternatively you could pre-process the text this way and then train word2vec --- this way you'll get a vector for the whole phrase, instead of just the component tokens.
