### ISSUE TITLE
Latest versions 1.7+ not on conda yet

### ISSUE THREAD

**Issue by randomgambit** [explosion/spaCy#946]
Hello there,

Thanks for this wonderful package. I am using Anaconda on a windows 64 machine, and I have a hard time installing it and using it. I ran

```
conda config --add channels conda-forge
conda install spacy
```

and I also ran  ` python -m spacy.en.download all`

Now, if I use the two-liner available on your website, I get an error

```
import spacy                         # See "Installing spaCy"
nlp = spacy.load('en')               # You are here.
doc = nlp(u'Hello, spacy!')          # See "Using the pipeline"
print((w.text, w.pos_) for w in doc) 

<generator object <genexpr> at 0x000000000F162678>

```
 and 
```
sentences = [s for s in doc.sents]
print(len(sentences))

```
gives 

```
ValueError: sentence boundary detection requires the dependency parse, which requires data to be installed. If you haven't done so, run: 
python -m spacy.en.download all
to install the data
```

Any ideas?
Thanks!!

**Comment by ines** [comment]
Hey – sorry, I think you've accidentally installed the old version v1.6 that doesn't yet use the new download commands. The latest version 1.7+ is not on conda yet (see #923), but we're working on that.

In the meantime, you can always use pip to install the latest version:
```bash
pip install spacy
```

**Comment by ines** [comment]
I just checked again and I misread your issue, sorry. Turns out I got confused by the conda badge that still lists version 1.6. The new version should be up and you've probably downloaded it correctly. You can make sure it downloads the latest version using this command:

```bash
conda install -c conda-forge spacy=1.7.3
```

Your problem seems to be that you've used the old download commands to download the models. As of 1.7+, models can be downloaded like this:

```
python -m spacy download en
python -m spacy download de
```

For more info on this, see the [models documentation](https://spacy.io/docs/usage/models).

**Comment by randomgambit** [comment]
Hello thanks for the answer.
I just did both

`conda install -c conda-forge spacy=1.7.3 `and
```
python -m spacy download en
python -m spacy download de
```
 it says linking successful but after restarting Spyder I still get the above errors. Is there anything else to do to make it work?

Thanks

**Comment by rolando** [comment]
Could you show us the output of `python -m spacy info` in the console? And inside spyder, the output of the following code:

```
from spacy.cli import info
info()
```

**Comment by randomgambit** [comment]
yup!

```
    Info about spaCy

    Python version     2.7.13
    Platform           Windows-10-10.0.14393
    spaCy version      1.7.3
    Installed models
    Location           D:\anaconda\lib\site-packages\spacy
```


```
from spacy.cli import info
info()


    Info about spaCy

    Python version     2.7.13         
    Platform           Windows-10-10.0.14393
    spaCy version      1.7.3          
    Installed models                   
    Location           D:\anaconda\lib\site-packages\spacy
```

**Comment by abbottLane** [comment]
I'm seeing the exact same issue as @randomgambit . A workaround that I've found is to import the model like this:
```
import spacy
import en_core_web_sm

nlp = en_core_web_sm.load()
r = nlp(u'This is a sentence. This is another one. And this is a third for good measure.' )
for s in r.sents:
    print(s)

-----------------------------------output----------------------
>>>This is a sentences.
>>>This is another one.
>>>And this is a third, for good measure.
```

**Comment by randomgambit** [comment]
workaround works for me!

**Comment by ines** [comment]
This sounds a lot like the problem described in #934. Especially since you're on Windows + Python 2, and also got the `Invalid switch` message.

For Windows and Python 2, spaCy uses `mlink` to create the symlinks, and the paths were being passed in as strings, not Windows paths, which for some reason fails silently and still displays the success message.

The fix is already on master, so if you build from source, it'll likely solve this issue. Otherwise, importing models as modules as described above should always work. We tried to make sure spaCy never fully relies on the `download` and `link` commands that interact with the user's file system.
