### ISSUE TITLE
displaCy Chinese is broken

### ISSUE THREAD

**Issue by bittlingmayer** [explosion/spaCy#9857]
## How to reproduce the behaviour
1. Go to https://explosion.ai/demos/displacy
2. Change the language to e.g. Romanian and the text to e.g. `123`
3. Watch the spinner spin and the results update
4. Change the language to Chinese and the text to e.g. `abc`
5. No spinner and no update

## Your Environment

N/A

**Comment by adrianeboyd** [comment]
Thanks for the report, we are looking into it!

**Comment by adrianeboyd** [comment]
As a note, if you uncheck "collapse phrases" Chinese will work in the online demo and an internal fix for this in the demo is coming soon. The displacy module itself is fine for Chinese as long as you don't enable the `collapse_phrases` option, since there isn't a syntax iterator for noun chunks for Chinese.

**Comment by adrianeboyd** [comment]
This is finally fixed!
