### ISSUE TITLE
nlp.pipe slow with trf after spawn

### ISSUE THREAD

**Issue by JayThibs** [explosion/spaCy#9922]
## How to reproduce the behaviour

I'm trying to use the transformer model, but it's unbearably slow compared to the large model. It wasn't working at all before I added `set_start_method("spawn")`, but now it's just to slow to use. With tqdm I'm getting: `30it [01:43,  3.45s/it]`. However, when I run with the large model, I get: 30it [00:37,  1.25s/it]. Once the loop starts with the large model, it is super faster. This is not the case with the transformer. Is this expected? Is there anything I can do about it?

```
from multiprocessing import set_start_method
set_start_method("spawn")
# nlp = spacy.load("en_core_web_lg")
sentences = []
sample_qa_text_list = qa_text_list[0:30] # list of strings
i = 0
for doc in tqdm(nlp.pipe(sample_qa_text_list, batch_size=8, n_process=3)):
    try:
        doc = nlp(sample_qa_text_list[i])
        i += 1
    except Exception as e:
        i += 1
        print(e)
        print("Error in sentence: " + str(sample_qa_text_list[i]))
        continue
    for sent in doc.sents:
        if sent[0].is_title and sent[-1].is_punct:
            has_noun = 2
            has_verb = 1
            for token in sent:
                if token.pos_ in ["NOUN", "PROPN", "PRON"]:
                    has_noun -= 1
                if token.pos_ in ["VERB"]:
                    has_verb -= 1
            if has_noun < 0 and has_verb < 0:
                sentences.append(sent)
# print(sentences)
for sentence in sentences:
    print(sentence)
    # print(result, end='', flush=True)
```

## Your Environment
Colab
* spaCy Version Used: 3.2.1

**Comment by honnibal** [comment]
Were you planning to use the GPU? If so, you haven't enabled it, which might be behind the problem. You can use then GPU by setting `spacy.prefer_gpu()`. You'll also want to set `thinc.api.use_pytorch_for_gpu_memory()` to make sure the right allocator is being used. You probably won't be able to use multiprocessing with the GPU, because the GPU will need to allocate more memory per process and it will run out of memory. This is generally true of other frameworks -- it's not something specific to spaCy.

Finally, if you're planning to run on CPU, the main thing to be aware of is the interaction between the number of threads PyTorch will be trying to start up per process, and the number of processors. The specifics will depend on how many cores your machine has, but you'll probably want to reduce the number of OpenMP threads PyTorch is using. Otherwise you'll end up with more threads than cores, and the program will end up task-swapping, and ultimately will be slower than if you had only used one process.

**Comment by adrianeboyd** [comment]
Additionally, if you're going to run this on CPU, instead of using spawn, try this to prevent the deadlock you were probably running into before: https://github.com/explosion/spaCy/issues/8678#issuecomment-878005376

But no matter what you do, `trf` models are just going to be slow on CPU: https://spacy.io/usage/facts-figures#benchmarks-speed

**Comment by JayThibs** [comment]
@honnibal @adrianeboyd Thank you for the response. I was not looking to do inference on the GPU, but now it seems much more wise to do so given how slow the multiprocessing is on the CPU.


> Otherwise you'll end up with more threads than cores, and the program will end up task-swapping, and ultimately will be slower than if you had only used one process.

This is likely the issue. Not sure how to deal with this. I'll look into what @adrianeboyd posted if GPU doesn't work.

**Comment by JayThibs** [comment]
@honnibal When I try to run `use_pytorch_for_gpu_memory()`, I get an error with CuPy"

```
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

original error: libnvrtc.so.11.2: cannot open shared object file: No such file or directory
```

**Comment by JayThibs** [comment]
Ok, so I've decided to go with using the large model + multiprocessing, but the loop takes a long time to start on Windows. I'm now using Colab (for Linux) to run the code and it's much faster.

On Windows, it take about 1min45s to start the loop, but on Linux it's starting right away. Any ideas on how to resolve this?

**Comment by JayThibs** [comment]
I was able to make the code run in docker, much faster! Windows was the issue.

**Comment by adrianeboyd** [comment]
Thanks for reporting back! The speed difference (once you get beyond the linux deadlock) is due to using spawn (windows) vs. fork (linux).
